### ISSUE TITLE
Serverless template missing mappings to `GetBlogAsync`

### ISSUE THREAD

**Issue by superlogical** [aws/aws-lambda-dotnet#10]

**Comment by normj** [comment]
Thanks for letting us know. I have pushed a new version of the blueprint with the mapping. You will see it the next time you start Visual Studio and create a project based on on the blueprint.

**Comment by superlogical** [comment]
No worries, thanks for the awesome library, I've already used this at work @xero and got something into production last friday. C# Lambdas FTW

**Comment by normj** [comment]
Very cool!
