### ISSUE TITLE
dotnet lambda package producing different zip files on Ubuntu versus Windows

### ISSUE THREAD

**Issue by ibuchan72390** [aws/aws-lambda-dotnet#100]
I'm currently using the Amazon.Lambda.Tools version 1.4.0.  I have a little bit of weirdness that seems to be occurring as I go across environments.  My dev machine is a Windows 10 laptop; however, I have Bamboo setup on an Ubuntu EC2 instance as my CI / CD solution.  I've been plugging along nicely and have been getting everything to work up until last night when I hit a huge wall with deploying my lambda function generated in Ubuntu.  I would simply end up getting an error that indicates the following:

{
  "errorType": "LambdaException",
  "errorMessage": "Unable to load assembly '<project-name>, Culture=neutral, PublicKeyToken=null'."
}

The only times I've seen this issue prior is usually due to a malformed package, so I thought I would verify the contents of the package. Any manual uploads from my Windows machine were working fine. I proceeded to extract the zip file from Ubuntu to my local instance where I could unzip it.  Despite the minor (~50kb) differences in package sizes; the contents appeared pretty much the same.  I tried editing my project.json, thinking that it was some issue with environmental builds to no effect.  

Eventually, I thought I would just try to upload the file again via the Lambda UI from my Windows machine.  At first the package failed with the same error message; so I thought I would unzip it and try re-zipping the contents.  To my surprise; rezipping the package created on my Ubuntu Bamboo server on my Windows machine made everything start to work again.

Might there be anything with the zip process during "dotnet lambda package" that could cause differences across environments?  If so, how can I equalize the generated packages to ensure the zip file generated on Ubuntu can be directly uploaded to my Lambda function via the following cli method:

aws lambda update-function-code --function-name <name> --zip-file fileb://<file>

**Comment by normj** [comment]
Can you provide the output when you run `dotnet lambda package` on your ubuntu box? 

On windows the Lambda tooling just uses the .NET Compression library to zip up the function. If you are deploying a function from Linux you need to chmod +r all the dlls and compress the package with the `zip` cli to preserve the file permissions. `dotnet lambda package` will take care of all that for you assuming it finds `chmod` and `zip` commands in the path. I'm curious if the output from `dotnet lambda package` will show it ran `chmod` and used the `zip` cli.

**Comment by ibuchan72390** [comment]
I think I can see the issue right now from your description.  I don't believe the "zip" command is currently installed on my Ubuntu box.  I can definitely see the chmod getting executed appropriately; however, I'm a little surprised that it didn't complain about not finding the "zip" command!  It still seems to indicate that it zips the file without issue and a final zip is produced.  I'll attempt to install the "zip" command on my Ubuntu box and try this again.  A post of my current Bamboo log is attached below.

[dotnet lambda package - Bamboo Log.txt](https://github.com/aws/aws-lambda-dotnet/files/920429/dotnet.lambda.package.-.Bamboo.Log.txt)

**Comment by normj** [comment]
The tool is assuming that if `zip` isn't found then it is running on Windows. We should look for a better indicator of the platform it is running on.

**Comment by ibuchan72390** [comment]
That definitely fixed it!  Thank you very much for your quick reply!
