### ISSUE TITLE
Routing of Identity Pages in Lambda

### ISSUE THREAD

**Issue by bveeni** [aws/aws-lambda-dotnet#1001]
Hi everyone,
Hope everyone is doing well.
I am developing dotnet core React web app, with Identity server for authorization.
Here, I am facing with directing url when publishing app to aws lambda.
For example:
In local development, when clicking on register page, it takes me to 
https://localhost:5001/Identity/Account/Register?returnUrl=/authentication/login
and working fine.
But my app on AWS lambda, clicking on register takes me to
https://72x...-southeast-2.amazonaws.com/Identity/Account/Register?returnUrl=/authentication/login
which is not working.
I suppose the URL should be
https://7..a.execute-api.ap-southeast-2.amazonaws.com/Prod/Identity/Account/Register?returnUrl=/authentication/login

How can I make this happen. i.e directing to URL having /Prod for Identity pages.
Let me know if anyone came through such issues
Thanks

### Environment

* Build Version: 
* OS Info: 
* Build Environment: 
* Targeted .NET Platform:  

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
@bveeni Please check [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=visual-studio) for details on how to configure identity including the URLs. If you need assistance with ASP.NET Core specific issues, Microsoft's https://github.com/dotnet/aspnetcore repo might be helpful.

**Comment by bveeni** [comment]
Thanks Ashis,
It doesn't work for React one. I suppose, we need to configure on react js
files, as we have api-authorization components like
apiAuthorizationConstant.js, apiAuthorizationRoutes.js. But , I am not sure
on how to configure properly.

For register,
If I change path
 IdentityRegisterPath: '/Identity/Account/Register'
to
  IdentityRegisterPath: '/Prod/Identity/Account/Register',
under file apiAuthorisationConstant.js file, then it works fine for
register.
Therefore, I feel currently its not taking "/Prod/" and is not working.

When checking on console, I see error saying "Could not load setting for
Authorize.js"
Proper configuration for React on ASP Net core for Identity URL might
resolve it.


Binita Shrestha
Web Developer
Odessi Group Pty Ltd

**Comment by ashishdhingra** [comment]
> Thanks Ashis, It doesn't work for React one. I suppose, we need to configure on react js files, as we have api-authorization components like apiAuthorizationConstant.js, apiAuthorizationRoutes.js. But , I am not sure on how to configure properly. For register, If I change path IdentityRegisterPath: '/Identity/Account/Register' to IdentityRegisterPath: '/Prod/Identity/Account/Register', under file apiAuthorisationConstant.js file, then it works fine for register. Therefore, I feel currently its not taking "/Prod/" and is not working. When checking on console, I see error saying "Could not load setting for Authorize.js" Proper configuration for React on ASP Net core for Identity URL might resolve it. Binita Shrestha Web Developer Odessi Group Pty Ltd

@bveeni Please check stackoverflow post https://stackoverflow.com/questions/60429647/i-am-facing-issue-to-set-redirect-url-to-react-page-from-identityserver4-while-r for guidance on similar issue. Since this is not and AWS issue, it would be helpful if you post your question at Microsoft's https://github.com/dotnet/aspnetcore repo in case you still face the issue. Closing this issue.
