### ISSUE TITLE
path parameter in connection method url

### ISSUE THREAD

**Issue by majidse** [aws/aws-lambda-dotnet#1002]
hello to every one. 
i have a question in dotnet core aws websocket api getaway. 
when we create project like this, default we have 3 function (OnConnectHandler, SendMessageHandler, OnDisconnectHandler) and when we publish this project, automatically it's create a websocket and 3 function and connect this function to routes. and create a url like this :
**wss://----------.execute-api.eu-central-1.amazonaws.com/dev**

and i can connect to this url with wscat. but my question is how can i change the setting for getting this url 
**wss://----------.execute-api.eu-central-1.amazonaws.com/dev/111**

thanks.

**Comment by ashishdhingra** [comment]
@majidse Could you please elaborate the issue with more details:
- Sample code along with '.csproj' file 
- Steps for deployment 
- Current configuration after deployment.
- Desired configuration or result

**Comment by majidse** [comment]
hi
please consider a simple code that created with aws template in dotnet core. 
we have 3 functions (OnConnectHandler, SendMessageHandler, OnDisconnectHandler). 
in OnConnectHandler function we have two input APIGatewayProxyRequest and ILambdaContext.
the configuration for deploy is :
`{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "An AWS Serverless Application.",
  "Parameters": {
    "ConnectionMappingTableName": {
      "Type": "String",
      "Default": "SimpleChatConnections",
      "Description": "The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters.",
      "MinLength": "3",
      "MaxLength": "50",
      "AllowedPattern": "^[A-Za-z_]+$"
    }
  },
  "Resources": {
    "ConnectionMappingTable": {
      "Type": "AWS::DynamoDB::Table",
      "Properties": {
        "TableName": {
          "Ref": "ConnectionMappingTableName"
        },
        "AttributeDefinitions": [
          {
            "AttributeName": "connectionId",
            "AttributeType": "S"
          }
        ],
        "KeySchema": [
          {
            "AttributeName": "connectionId",
            "KeyType": "HASH"
          }
        ],
        "BillingMode": "PAY_PER_REQUEST"
      }
    },
    "OnConnectFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "bootstrap::NGSC.OCPP.CentralSystem.Functions::OnConnectHandler",
        "Runtime": "dotnetcore3.1",
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          {
            "DynamoDBCrudPolicy": {
              "TableName": {
                "Ref": "ConnectionMappingTableName"
              }
            }
          }
        ],
        "Environment": {
          "Variables": {
            "TABLE_NAME": {
              "Ref": "ConnectionMappingTableName"
            }
          }
        }
      }
    },
    "OnDisconnectFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "bootstrap::NGSC.OCPP.CentralSystem.Functions::OnDisconnectHandler",
        "Runtime": "dotnetcore3.1",
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          {
            "DynamoDBCrudPolicy": {
              "TableName": {
                "Ref": "ConnectionMappingTableName"
              }
            }
          }
        ],
        "Environment": {
          "Variables": {
            "TABLE_NAME": {
              "Ref": "ConnectionMappingTableName"
            }
          }
        }
      }
    },
    "SendMessageFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "bootstrap::NGSC.OCPP.CentralSystem.Functions::SendMessageHandler",
        "Runtime": "dotnetcore3.1",
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          {
            "DynamoDBCrudPolicy": {
              "TableName": {
                "Ref": "ConnectionMappingTableName"
              }
            }
          },
          {
            "Statement": {
              "Effect": "Allow",
              "Action": "execute-api:ManageConnections",
              "Resource": "arn:aws:execute-api:*:*:*/@connections/*"
            }
          }
        ],
        "Environment": {
          "Variables": {
            "TABLE_NAME": {
              "Ref": "ConnectionMappingTableName"
            }
          }
        }
      }
    },
    "ocpptest": {
      "Type": "AWS::ApiGatewayV2::Api",
      "Properties": {
        "Name": "ocpptest",
        "ProtocolType": "WEBSOCKET",
        "RouteSelectionExpression": "$request.body.message"
      }
    },
    "ConnectRoute": {
      "Type": "AWS::ApiGatewayV2::Route",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "RouteKey": "$connect",
        "AuthorizationType": "NONE",
        "OperationName": "ConnectRoute",
        "Target": {
          "Fn::Join": [
            "/",
            [
              "integrations",
              {
                "Ref": "ConnectInteg"
              }
            ]
          ]
        }
      }
    },
    "ConnectInteg": {
      "Type": "AWS::ApiGatewayV2::Integration",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "IntegrationType": "AWS_PROXY",
        "IntegrationUri": {
          "Fn::Sub": [
            "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${function}/invocations",
            {
              "region": {
                "Ref": "AWS::Region"
              },
              "function": {
                "Fn::GetAtt": [
                  "OnConnectFunction",
                  "Arn"
                ]
              }
            }
          ]
        }
      }
    },
    "DisconnectRoute": {
      "Type": "AWS::ApiGatewayV2::Route",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "RouteKey": "$disconnect",
        "AuthorizationType": "NONE",
        "OperationName": "ConnectRoute",
        "Target": {
          "Fn::Join": [
            "/",
            [
              "integrations",
              {
                "Ref": "DisconnectInteg"
              }
            ]
          ]
        }
      }
    },
    "DisconnectInteg": {
      "Type": "AWS::ApiGatewayV2::Integration",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "IntegrationType": "AWS_PROXY",
        "IntegrationUri": {
          "Fn::Sub": [
            "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${function}/invocations",
            {
              "region": {
                "Ref": "AWS::Region"
              },
              "function": {
                "Fn::GetAtt": [
                  "OnDisconnectFunction",
                  "Arn"
                ]
              }
            }
          ]
        }
      }
    },
    "SendMessageRoute": {
      "Type": "AWS::ApiGatewayV2::Route",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "RouteKey": "sendmessage",
        "AuthorizationType": "NONE",
        "OperationName": "ConnectRoute",
        "Target": {
          "Fn::Join": [
            "/",
            [
              "integrations",
              {
                "Ref": "SendMessageInteg"
              }
            ]
          ]
        }
      }
    },
    "SendMessageInteg": {
      "Type": "AWS::ApiGatewayV2::Integration",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "IntegrationType": "AWS_PROXY",
        "IntegrationUri": {
          "Fn::Sub": [
            "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${function}/invocations",
            {
              "region": {
                "Ref": "AWS::Region"
              },
              "function": {
                "Fn::GetAtt": [
                  "SendMessageFunction",
                  "Arn"
                ]
              }
            }
          ]
        }
      }
    },
    "Deployment": {
      "Type": "AWS::ApiGatewayV2::Deployment",
      "DependsOn": [
        "ConnectRoute",
        "SendMessageRoute",
        "DisconnectRoute"
      ],
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        }
      }
    },
    "Stage": {
      "Type": "AWS::ApiGatewayV2::Stage",
      "Properties": {
        "ApiId": {
          "Ref": "ocpptest"
        },
        "DeploymentId": {
          "Ref": "Deployment"
        },
        "StageName": "dev"
      }
    },
    "OnConnectPermission": {
      "Type": "AWS::Lambda::Permission",
      "DependsOn": [
        "OnConnectFunction",
        "ocpptest"
      ],
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Ref": "OnConnectFunction"
        },
        "Principal": "apigateway.amazonaws.com"
      }
    },
    "OnDisconnectPermission": {
      "Type": "AWS::Lambda::Permission",
      "DependsOn": [
        "OnDisconnectFunction",
        "ocpptest"
      ],
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Ref": "OnDisconnectFunction"
        },
        "Principal": "apigateway.amazonaws.com"
      }
    },
    "SendMessagePermission": {
      "Type": "AWS::Lambda::Permission",
      "DependsOn": [
        "SendMessageFunction",
        "ocpptest"
      ],
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Ref": "SendMessageFunction"
        },
        "Principal": "apigateway.amazonaws.com"
      }
    }
  },
  "Outputs": {
    "WebSocketURI": {
      "Value": {
        "Fn::Join": [
          "",
          [
            "wss://",
            {
              "Ref": "ocpptest"
            },
            ".execute-api.",
            {
              "Ref": "AWS::Region"
            },
            ".amazonaws1.com/",
            {
              "Ref": "Stage"
            }
            
          ]
        ]
      },
      "Description": "The WSS Protocol URI to connect to"
    }
  }
}`


and in the aws site i choose "Integration Request" for connect route and use Use Lambda Proxy integration for this route.
do you need any other info ?!

**Comment by aaoswal** [comment]
Hi @majidse,
I could not figure out the context behind the configurations listed earlier and reproduce the issue.
Could you please provide a sample code that I could use to reproduce?

Thanks,
Anish.
