### ISSUE TITLE
Upgrade `Amazon.Lambda.Core.dll` to newer version

### ISSUE THREAD

**Issue by TrongTheAlpaca** [aws/aws-lambda-dotnet#1003]
## Description

My knowledge around assemblies is limited, but if I'm not mistaken it seems like the `Amazon.Lambda.Core` used in the LambdaTestTool is outdated (see below image). 

![image](https://user-images.githubusercontent.com/46680221/144008668-af945f5b-0780-49ac-a008-d6ee98845775.png)
_Content from the NuGet package https://nuget.info/packages/Amazon.Lambda.TestTool-6.0/0.11.3_

### Is your Feature Request related to a problem?

When running the code with the LambdaTestTool, the assemblies from LambdaTestTool will be used instead of the one installed through NuGet for the project, breaking the code if you are using functionalities from a newer version. 

![image](https://user-images.githubusercontent.com/46680221/144009808-5ddfd8cf-6bec-4c4f-9641-680d59020d89.png)
*The above error message appear when you use functionalities such as `Amazon.Lambda.Core.LogLevel.Debug` from `Amazon.Lambda.Core 2.1.0`.*

---

This is a :rocket: Feature Request

**Comment by normj** [comment]
Thanks for pointing this out. I have pushed out a PR to get the toolkit to use the latest version of Amazon.Lambda.Core.

**Comment by normj** [comment]
Sorry for the delay but version 0.11.4 is out which updates the test tool to the latest version of Amazon.Lambda.Core.
