### ISSUE TITLE
APIGateway: access AWSRequestID

### ISSUE THREAD

**Issue by peterdeme** [aws/aws-lambda-dotnet#103]
Hi Guys,

Is there any way to access AWS Request ID inside WebAPI?
If we want to setup an exception page where we provide the request id to the customer, how could access the request id?

Would it be possible to put it into HttpContext somewhere here?

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L121

My idea:

1.)
```csharp
var context = this.CreateContext(features);
context.HttpContext.Items["AWSRequest"] = request;
```
2.) Make CreateContext method virtual in APIGatewayProxyFunction.cs

Thank you,
Peter

**Comment by normj** [comment]
I'm thinking of putting the whole ILambdaContext and the original Lambda request in HttpContext. That should help the cases of getting a hold of data that didn't get marshaled in the HttpRequest.

**Comment by peterdeme** [comment]
Thank you, that would be awesome.

**Comment by normj** [comment]
I pushed out version 0.10.0-preview1 of `Amazon.Lambda.AspNetCoreServer` which allows you to access the APIGatewayProxyRequest and ILambdaContext objects through HttpContext.Items collection with the collection keys **APIGatewayRequest** and **LambdaContext**.

**Comment by peterdeme** [comment]
Norm, thats's awesome, thank you!
