### ISSUE TITLE
Add SQSBatchResponse class

### ISSUE THREAD

**Issue by Dreamescaper** [aws/aws-lambda-dotnet#1033]
I this article I can see you can return partial success for SQS batch via SQSBatchResponse class, but seems like it is not available for .NET. 
https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

Is it possible to add it? Thanks!

**Comment by Dreamescaper** [comment]
This request has no relation to AspNetCore, we don't even use it.

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-lambda-dotnet/pull/1039 is merged. The update has been released in version `2.1.0` of the `Amazon.Lambda.SQSEvents`.
