### ISSUE TITLE
.NET Resources and localization

### ISSUE THREAD

**Issue by vvenegasv** [aws/aws-lambda-dotnet#104]
Hi, I'm trying to make an API with API Gateway and Lambda Function with .NET Core, that returns messages in several languages.

It's common in .NET implement this feature with resources, but in the [lambda's forum](https://forums.aws.amazon.com/thread.jspa?threadID=254102&tstart=0) they tell me that resources is not supported yet.

Is there a workaround or another approach?

I made an example project on [Github ](https://github.com/vvenegasv/error-lambda-netcore-localization)to reproduce this behavior.

Also, I have an [API Gateway endpoint](https://q6dzim5nb6.execute-api.us-east-1.amazonaws.com/prod?language=1), where 1 is for french, 2 is for italian and 3 is an invalid language.

Finally, I post this question in [StackOverflow](http://stackoverflow.com/questions/43506436/aws-lambda-is-not-recognizing-the-culture-on-net-core) too.

Thanks a lot!

**Comment by vvenegasv** [comment]
Hi, I want to know if there is a planning to include this feature in the near future, or if there is a workaround. 

Best Regards
Vladimir Venegas

**Comment by normj** [comment]
This is an issue with how the .NET Core code is loaded in Lambda. We have no immediate plans on making any changes on how the code is loaded because that would be a large amount of work and we want to focus our engineering effort on the next iteration of .NET Core Lambda. We recognize this issue is a bug and we look to solve it in the next iteration.

**Comment by vvenegasv** [comment]
Hi, thanks @normj Ok, I understand. And have you a recommended approach to send located messages? I was thinking put all messages in a JSON file and create a wrapper in a singleton, that handles all messages that I need to include in my response.

**Comment by normj** [comment]
What you suggest is probably what I would do. It might be better to keep the same xml format as the RESX files instead of JSON so when the bug is fixed in the future it would be easier to switch back to it.

**Comment by normj** [comment]
This is now fixed in the new .NET Core 2.0 Lambda runtime that was released today, https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-0-support-released/

**Comment by CodeRevver** [comment]
This isn't working for resources as files.  I'm getting the value of the resource ref. e.g.

  <data name="VoteIdea" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>VoteIdea.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>
  </data>

Gives me back: VoteIdea.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8
