### ISSUE TITLE
Static page path

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#105]
Not sure if this is a Lambda or a Dotnet Core issue.

If you create an ASP.NET Core project with static pages. i.e. in your startup.cs Configure you have "app.UseStaticFiles();"

I can serve up the static page using a string such as:
https://xxxxxxxxxx.execute-api.loc.amazonaws.com/Prod/html/general.html

but, references within this resource such as:
```
    <link rel="StyleSheet" type="text/css" href="css/style.css" />
```

are not found. They are attempted to be served up by:
https://xxxxxxxxxx.execute-api.loc.amazonaws.com/css/style.css

which of course fails (404).

In the end, I have to use:
```
    <link rel="StyleSheet" type="text/css" href="/Prod/css/style.css" />
```

which does not work in development (i.e. run locally).

Can anyone shed some light on this behavior?

Thanks,
Dave

**Comment by genifycom** [comment]
I have confirmed that

webRootPath = _hostingEnvironment.WebRootPath;

returns "/var/task/wwwroot" which will not work under Prod.

**Comment by normj** [comment]
Thanks for letting us know. I'll do some investigating.

**Comment by normj** [comment]
Is this still a problem? I have not been able to reproduce the problem. The Lambda team was doing some work to make sure the working directory was configured correctly. I'm wondering if that resolved this issue.

**Comment by normj** [comment]
I think this is solved and have not been able to reproduce any problems. If you can reproduce it feel free to reopen.
