### ISSUE TITLE
Add contracts for user pool lambda trigger sources to Amazon.Lambda.CognitoEvents

### ISSUE THREAD

**Issue by jon-armen** [aws/aws-lambda-dotnet#1050]
## Describe the Feature
Provide the contracts used by lambda trigger sources

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-identity-pools-working-with-aws-lambda-trigger-sources

### Is your Feature Request related to a problem?
In order to handle lambda trigger sources in dotnet, these classes must be implemented in customer code.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @jon-armen,

Good morning.

Thanks for submitting the feature request. We would discuss this this with development team, however, we cannot commit on the timelines by which this could be implemented. Feel free to contribute by submitting a PR.

Thanks,
Ashish

**Comment by jon-armen** [comment]
> Hi @jon-armen,
> 
> Good morning.
> 
> Thanks for submitting the feature request. We would discuss this this with development team, however, we cannot commit on the timelines by which this could be implemented. Feel free to contribute by submitting a PR.
> 
> Thanks, Ashish

Thank you for the details.  I've pushed a draft PR, currently only including the PreSignup trigger handling.  I'll continue to implement the others as I have time.  Any early feedback from the dev team would be appreciated to make sure the approach I'm taking is acceptable.

**Comment by jon-armen** [comment]
@ashishdhingra , PR is ready for review.

**Comment by normj** [comment]
The PR with this change has been released as part of version 2.1.0 of Amazon.Lambda.CognitoEvents.
