### ISSUE TITLE
Amazon.Lambda.Annotations.HttpMethod conflicts with System.Net.Http.HttpMethod when using implicit using statements

### ISSUE THREAD

**Issue by martincostello** [aws/aws-lambda-dotnet#1053]
## Describe the Feature

If the Implicit Using Statements feature of the .NET 6 SDK is enabled in a project using Amazon.Lambda.Annotations, any attempt to use the `[RestApi]` attribute will result in a compiler error due to ambiguity caused by the default inclusion of the `System.Net.Http` namespace as a using statement in all C# files in the project.

```sh
Error	CS0104	'HttpMethod' is an ambiguous reference between 'Amazon.Lambda.Annotations.HttpMethod' and 'System.Net.Http.HttpMethod'
```

This creates friction to the developer experience when using the annotations library, and may confuse less experienced developers, particularly those new to .NET and adopting it from .NET 6.

## Proposed Solution

Suggestions include:

* Rename the type to remove the ambiguity.
* Automatically add the alias below if implicit using statements are enabled and the package is referenced.
* Automatically add the alias to any Lambda templates using the library in the .NET CLI for new project creation.
* Document how to resolve the ambiguity.

### Describe alternatives you've considered

Manually resolve the ambiguity using an alias in relevant code files:

```csharp
using HttpMethod = Amazon.Lambda.Annotations.HttpMethod;
```

Manually add an additional implicit using statement to apply an alias in all C# files to resolve the ambiguity.

```xml
<ItemGroup>
  <Using Include="Amazon.Lambda.Annotations.HttpMethod" Alias="HttpMethod" />
</ItemGroup>
```

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by normj** [comment]
Agreed the implicit namespaces in .NET 6 makes this awkward. I pushed a breaking PR to rename the enum to `LambdaHttpMethod`. I'm open to better names. https://github.com/aws/aws-lambda-dotnet/pull/1056

**Comment by ganeshnj** [comment]
https://www.nuget.org/packages/Amazon.Lambda.Annotations/0.4.3-preview is out containing the fix.
