### ISSUE TITLE
PreTokenGenerationTrigger.cs file is not there in the source.  

### ISSUE THREAD

**Issue by ajaygote** [aws/aws-lambda-dotnet#1057]
I am working on Pre Token Generation trigger and I could not find Amazon.Lambda.CognitoEvents.LambdaTriggerEvents.PreTokenGenerationTrigger file. I have checked master and dev both repo. 

I have included the nuget package - Amazon.Lambda.CognitoEvents in my project. And I can only see the Amazon.Lambda.CognitoEvents.CognitoEvent class and not the PreTokenGenerationTrigger class.
Am I missing anything?

**Comment by ashishdhingra** [comment]
Hi @ajaygote,

Good morning.

Thanks for reporting guidance issue. Yes, you are correct that the only event model class available in `Amazon.Lambda.CognitoEvents` is `CognitoEvent`. There was a similar issue https://github.com/aws/aws-lambda-dotnet/issues/1050 reported few days back, user has submitted a draft PR https://github.com/aws/aws-lambda-dotnet/pull/1051 which needs to be reviewed by the team. This PR does not cover all the triggers listed at https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html.

Thanks,
Ashish

**Comment by jon-armen** [comment]
@ajaygote, I've been working to update #1051 , which now has the classes you were looking for.  I have a few more classes to go, but should be done in the next few days.  Then it will be up to when the AWS team can review and complete.
