### ISSUE TITLE
Amazon.Lambda.Annotations generates invalid code causing CS0029 error for async method

### ISSUE THREAD

**Issue by martincostello** [aws/aws-lambda-dotnet#1058]
## Description

Declaring a function with a method signature similar to the below will generate a compiler CS0029 error when using the Amazon.Lambda.Annotations when attempting to build the project.

```csharp
[LambdaFunction]
public async Task<int> AddAsync(int x, int y)
{
    return await Task.FromResult(x + y);
}
```

```sh
C:\Coding\martincostello\dotnet-lambda-annotations\src\LambdaAnnotations\Amazon.Lambda.Annotations.SourceGenerator\Amazon.Lambda.Annotations.SourceGenerator.Generator\MathsFunctions_AddAsync_Generated.g.cs(22,20): error CS0029: Cannot implicitly convert type 'int' to 'System.Threading.Tasks.Task<int>' [C:\Coding\martincostello\dotnet-lambda-annotations\src\LambdaAnnotations\LambdaAnnotations.csproj]
```

Enabling [`EmitCompilerGeneratedFiles`](https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/#emitting-compiler-generated-files) in the project shows that the compiled code is generating a `Task<Task<T>>` instead of `Task<T>`, causing the type mismatch and compilation failure.

```csharp
public async Task<System.Threading.Tasks.Task<int>> AddAsync(int x, int y)
{
    return await mathsFunctions.AddAsync(x, y);
}
```

The error only occurs if the user method is declared as `async`, if the code is declared without it as shown below, the code compiles successfully.

```csharp
[LambdaFunction]
public Task<int> AddAsync(int x, int y)
{
    return Task.FromResult(x + y);
}
```

The error is also resolved if a `[RestApi(...)]` attribute is added.

While the missing attribute is probably a mistake on the part of the developer as it lacks the specification of a trigger for the Lambda, the invalid generated code does not point them to the problem or a resolution to it.

## Reproduction Steps

Clone the [`Async-CS0029`](https://github.com/martincostello/dotnet-lambda-annotations/tree/Async-CS0029) branch of the https://github.com/martincostello/dotnet-lambda-annotations repo and run `dotnet build`.

### Environment

* Build Version: Amazon.Lambda.Annotations `0.4.2-preview`
* OS Info: Windows 10
* Build Environment: Visual Studio and the .NET SDK on the CLI
* Targeted .NET Platform: `net6.0`

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by normj** [comment]
Thanks for the bug report @martincostello we'll take a look to see what is going wrong.

**Comment by ganeshnj** [comment]
Verified this happens for 0-event attached Lambda functions, where response type in the generated method stays as the user method response type but due to hardcoding `Task<>` for async method, we get an extra `Task<>`.

There should be tests for covering all the cases for 0-event lambda functions like we have for API Gateway event based lambda functions to ensure we have covered all possible cases.

**Comment by ganeshnj** [comment]
https://www.nuget.org/packages/Amazon.Lambda.Annotations/0.4.3-preview is out containing the fix.
