### ISSUE TITLE
Microsoft.AspNetCore.Rewrite causes lambda to fail

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#106]
If you add the rewrite library "Microsoft.AspNetCore.Rewrite": "1.0.1" to a lambda project, it fails with:

at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
Operation is not supported on this platform.: PlatformNotSupportedException
at System.Runtime.InteropServices.OSPlatform.get_Windows()

This appears to be an ASP.NET Core 1.0 project.

Does this need to be reported to Microsoft?

Thanks,
Dave

**Comment by damianh** [comment]
Yep, report to MS.

**Comment by normj** [comment]
The problem is Microsoft.AspNetCore.Rewrite depends on .NET Core 1.1. I don't understand why the .NET Core tooling even allows this behavior when you are targeting `netcoreapp1.0`. 

Yesterday I pushed out a new version of the VS toolkit that errors out when you try and deploy with dependencies requiring .NET Core 1.1. I'll be pushing out a new version of the .NET Core CLI integration that will also have this validation soon.

**Comment by genifycom** [comment]
Thanks Norm, I will test it.
The Microsoft.AspNetCore.Rewrite nuget package is v1.0.1 so I had assumed that it was ok for DotNet Core 1.0

It also says .NETStandard.Version v1.3

Does this mean that Lambda will currently support up to .NETStandard v1.2?

Thanks,
Dave

**Comment by normj** [comment]
Versioning in .NET Core is definitely confusing right now.

The way I view it is .NET Standard is specification of what a platform must implement to say it supports a version of the .NET Standard. Then .NET Core has a 1.0 and a 1.1 implementation of the .NET Standard. That implementation is the [.NETStandard.Library](http://www.nuget.org/packages/NETStandard.Library/) NuGet meta package. Version 1.6.0 of NETStandard.Library is the .NET Core 1.0 implementation of .NET Standard and 1.6.1 is the .NET Core 1.1 implementation.

So if you look at Microsoft.AspNetCore.Rewrite 1.0.1 you can see it has a dependencies on NETStandard.Library 1.6.1 which is the .NET Core 1.1 implementation of the .NET Standard.

Hopefully that is helpful and not just more confusing :)

**Comment by genifycom** [comment]
Ok got it.

Thanks for the explanation.
