### ISSUE TITLE
Lambda Authorizer through Serverless Template

### ISSUE THREAD

**Issue by ArcaneTSGK** [aws/aws-lambda-dotnet#1074]
Hi guys,

I am having difficulty discerning how I can add a Lambda Authorizer to my API using the SAM template file. 

It is very easy to deploy a lambda authorizer function and then in API gateway using the GUI select API -> Authorizers -> Create new (select my authorizer from the dropdown etc) but I would like this done in the template. 

My template looks as follows 

I've omitted the root resource, metadata and the standard bits like templateformat, description, etc..

```
"AspNetCoreFunction": {
  "Type": "AWS::Serverless::Function",
  "Properties": {
    "PackageType": "Image",
    "ImageConfig": {
      "Command": ["MyFunction::MyFunction.LambdaEntryPoint::FunctionHandlerAsync"]
    },
    "ImageUri": "",
    "MemorySize": 128,
    "Timeout": 30,
    "Policies": [ "AWSLambda_FullAccess" ],
    "Events": {
      "ProxyResource": {
        "Type": "Api",
        "Properties": {
          "Path": "/{proxy+}",
          "Method": "ANY"
        }
      }
    }
  }
}
```

What I would like to add in for this specific function, but I'm not sure where or how is something like

```
"Auth": {
  "DefaultAuthorizer": "POCIdentityAuthorizer",
  "Authorizers": {
    "POCIdentityAuthorizer": {
      "FunctionArn": "the ARN of my existing lambda authorizer function",
      "Identity": {
        "Headers": [ "Authorization" ]
      },
      "EnableSimpleResponses": true
    }
  }
}
```

Is this possible using SAM templates or would I need to use CloudFormation to achieve the result I'm looking for. 

``

### Environment
* OS Info: AWS Lambda
* Build Environment: docker
* Targeted .NET Platform:  .NET 6

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @ArcaneTSGK,

Good afternoon.

Thanks for posting guidance question. [Lambda authorizer examples](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis-lambda-authorizer.html) provides some examples for using lambda authorizer. May be you could try using the YAML template, convert it to JSON using [CloudFormation Integrated JSON and YAML editor](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/working-with-templates-cfn-designer-json-editor.html) and try using in your serverless template. Hope this helps.

Thanks,
Ashish
