### ISSUE TITLE
[AWS Lex] "null" values from Lex v2 Chatbot Request

### ISSUE THREAD

**Issue by omf-jnguyen** [aws/aws-lambda-dotnet#1077]
## Context
- Goal: Setup blueprint "OrderFlowers" chatbot with AWS Lex v2 using .NET Core 3.1 and AWS Lambda. [(Link)](https://docs.aws.amazon.com/lex/latest/dg/gs-bp.html)
- This may be an issue with Lex v2 rather than with Lambda, but this may be unlikely as Python and Node.js work fine when interchanged with the .NET lambda used.

## Description

- When invoking the OrderFlowers blueprint lambda function via AWS Lex, the `LexEvent` does not populate the expected fields, such as `CurrentIntent` and `SlotDetails`.
- Compare this to using the Python or Node.js blueprints which do populate the expected fields.

## Reproduction Steps

1. Create a new .NET project using the "AWS Lambda Project (.NET Core - C#)" template with the "Order Flowers Chatbot" Blueprint.
2. Log the `lexEvent` variable to CloudWatch within the **FunctionHandler** function: `LambdaLogger.Log(JsonSerializer.Serialize(lexEvent));`
3. Publish the solution to AWS Lambda (default settings, arbitrary function name).
4. Create a new Lex v2 Chatbot with the "Order Flowers Chatbot" Example.
5. Configure the new chatbot to use the new lambda function you uploaded under Bot > Alias > Language.
6. Under Intents > OrderFlowers > Fulfillment > Advanced Options, ensure "Use a Lambda function for fulfillment" is checked.
7. Save the intent, build the bot, and test the conversation.
8. An error should appear when attempting to fulfill the intent - when you check CloudWatch, the **LexEvent** body should appear with `null` values for fields such as `CurrentIntent` and `SlotDetails`.

### Logs
**Lex**
`Invalid Lambda Response: Received error response from Lambda: Unhandled`

**CloudWatch**
```
{
    "CurrentIntent": null,
    "SlotDetails": null,
    "Bot": {
        "Name": "OrderFlowersBot",
        "Alias": null,
        "Version": "DRAFT"
    },
    "UserId": null,
    "InputTranscript": "yes",
    "InvocationSource": "FulfillmentCodeHook",
    "OutputDialogMode": null,
    "MessageVersion": "1.0",
    "SessionAttributes": null,
    "RequestAttributes": null,
    "AlternativeIntents": null,
    "SentimentResponse": null,
    "RecentIntentSummaryView": null,
    "ActiveContexts": null
}
```

### Environment
* Build Version: Amazon.Lambda.Core 2.1.0, Amazon.Lambda.LexEvents 3.0.0, Amazon.Lambda.Serialization.SystemText 2.2.0 
* OS Info: Windows 10 Enterprise 
* Build Environment: Visual Studio 2019 
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
- There may be an issue serializing the incoming request from Lex v2 based on the configuration laid out in the current Order Flowers .NET 3.1 blueprint. To resolve this, effort will need to be made comparing the expected Lex v2 request payload with the actual payload and the serialization may have to be adjusted accordingly.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @omf-jnguyen,

Good afternoon.

Upon investigating further, looks like the [Amazon Lex V2](https://docs.aws.amazon.com/lexv2/latest/dg/what-is.html) could be having a different request/response format (reference [Using an AWS Lambda function](https://docs.aws.amazon.com/lexv2/latest/dg/lambda.html)). Hence, this is not a bug, instead a new feature request to implement new POCO classes, perhaps better to be part of new project `Amazon.Lambda.LexV2Events`. While I cannot commit timeline by which this feature request can be implemented, feel free to contribute in the form of PR. You may take existing [Amazon.Lambda.LexEvents](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.LexEvents) project as a starting point and take guidance from [Amazon Lex V2 API reference](https://docs.aws.amazon.com/lexv2/latest/dg/API_Reference.html) for model classes.

Thanks,
Ashish

**Comment by omf-jnguyen** [comment]
Thanks for the swift reply @ashishdhingra  - really appreciate the insight and guidance. Will follow-up with a PR in the near future then unless you guys beat me to it.

**Comment by 1bberto** [comment]
Its related to the version!
Lex V1: https://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html

And V2: https://docs.aws.amazon.com/lexv2/latest/dg/lambda.html#lambda-input-format

I`m facing the same issue!

**Comment by omf-jnguyen** [comment]
@1bberto - yup, realized that so I ended up implementing my own custom models based on v2. Now works like a charm for me!

Here's a gist in case anyone else wants to use them: https://gist.github.com/omf-jnguyen/dbd6cfebeb82780976038e1514a6ecb6

**Comment by 1bberto** [comment]
@omf-jnguyen - nice! I think that ifs working like a charm that is totally fine then.
the only thing that you don't need on your code are the attributes ```JsonPropertyName``` on your properties, I think that on the serialization the capitalization is not checked

**Comment by ashishdhingra** [comment]
[Amazon.Lambda.LexV2Events 1.0.0](https://www.nuget.org/packages/Amazon.Lambda.LexV2Events/1.0.0) has been released.
