### ISSUE TITLE
JSON setting files ignored in Lambda

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#108]
I couldn't find the issue that mentioned this problem, but somewhere else we were discussing about the appsettings.json being ignored.

Attached is a test lambda to reproduce.

It's very simple.
It uses `Microsoft.Extensions.Configuration` packages to setup some settings.

I set up three values in an InMemory provider (First, Second, Third) all set to InMemory
Then I add a JSON file with two values (Second and Third) set to JSON
Finally, in the default settings, I add a value Third = ENV.

The expected behavior would be:
First: InMemory
Second: JSON
Third: ENV

Here you can see the output on CloudWatch (removed all non relevant data)
```
START RequestId: b1ae2741-2c22-11e7-a775-7f68ee8b00da Version: $LATEST
Test
...
Third: ENV
Second: InMemory
First: InMemory
...
END RequestId: b1ae2741-2c22-11e7-a775-7f68ee8b00da
REPORT RequestId: b1ae2741-2c22-11e7-a775-7f68ee8b00da	Duration: 754.39 ms	Billed Duration: 800 ms Memory Size: 128 MB	Max Memory Used: 28 MB	
```

[TestAppSettings.zip](https://github.com/aws/aws-lambda-dotnet/files/964695/TestAppSettings.zip)

**Comment by PavelSafronov** [comment]
You may need to call `SetBasePath` first:
```
builder.SetBasePath(Directory.GetCurrentDirectory());
builder.AddInMemoryCollection(values);
builder.AddJsonFile("appsettings.json", true);
builder.AddEnvironmentVariables();
```

**Comment by Kralizek** [comment]
Thanks. I will try.

**Comment by Kralizek** [comment]
@PavelSafronov thank you. it worked as expected. :)
