### ISSUE TITLE
Mock Lambda Test Tool does not work when using net6 running in a container

### ISSUE THREAD

**Issue by andywatermarkmedical** [aws/aws-lambda-dotnet#1080]
## Description
Create a Lambda ASP.Net Core Web API (C#) (.NET 6 Core Container Image)(AWS) and debug using Mock Lambda Test Tool

After a successful build while in VS 2022, I try to debug using Mock Lambda Test Tool.  I get the following error in the console window:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
The application to execute does not exist: 'C:\Users\Andy.Espinosa\.dotnet\tools\.store\amazon.lambda.testtool-6.0\0.11.4\amazon.lambda.testtool-6.0\0.11.4\tools\net6.0\any\Amazon.Lambda.TestTool.BlazorTester.dll'.
C:\Users\Andy.Espinosa\.dotnet\tools\dotnet-lambda-test-tool-6.0.exe (process 25748) exited with code -2147450726.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## Reproduction Steps
1.	Open Visual Studio 2022
2.	Create a new project
3.	Select template: Lambda ASP.Net Core Web API (C#) (.NET 6 Core Container Image)
4.	Provide the name of project
5.	Provide the profile for AWS Toolkit
6.	Build Solution
7.	Debug using Mock Lambda Test Tool

### Logs
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
The application to execute does not exist: 'C:\Users\Andy.Espinosa.dotnet\tools.store\amazon.lambda.testtool-6.0\0.11.4\amazon.lambda.testtool-6.0\0.11.4\tools\net6.0\any\Amazon.Lambda.TestTool.BlazorTester.dll'.
C:\Users\Andy.Espinosa.dotnet\tools\dotnet-lambda-test-tool-6.0.exe (process 25748) exited with code -2147450726.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

launchSettings.json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:52178/",
      "sslPort": 44304
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "LambdaCore6WebApi": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    },
    "Mock Lambda Test Tool": {
      "commandName": "Executable",
      "commandLineArgs": "--port 5050",
      "workingDirectory": ".\\bin\\$(Configuration)\\net6.0",
      "executablePath": "%USERPROFILE%\\.dotnet\\tools\\dotnet-lambda-test-tool-6.0.exe"
    }
  }
}

### Environment
* Build Version: "Amazon.Lambda.AspNetCoreServer" Version="7.0.1"
* OS Info: Linux Container running .NET 6
* Build Environment: Visual Studio 2022
* Targeted .NET Platform:  .NET 6

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @andywatermarkmedical.

Good afternoon.

Unfortunately I'm unable to reproduce the issue. I'm able to run the Lambda test tool when using `Lambda ASP.Net Core Web API (C#) (.NET 6 Core Container Image)` template. The only difference is that the Lambda Test Tool 6.0 in my case is installed under `C:\Users\<<USERNAME>>\.dotnet\tools\.store\amazon.lambda.testtool-6.0\0.11.4\amazon.lambda.testtool-6.0\0.11.4\tools\net6.0\any`.
<img width="1650" alt="Screen Shot 2022-02-18 at 1 49 37 PM" src="https://user-images.githubusercontent.com/67916761/154766121-4952edb6-42aa-4154-ad03-10900e646d33.png">

Could you please upgrade to latest version of AWS Toolkit for Visual Studio 2022 (in my case, the version is `1.25.0.0`) and re-install lambda test tool 6.0?

Thanks,
Ashish

**Comment by andywatermarkmedical** [comment]
Ashish,

Thanks for your response.  I reinstalled AWS VS toolkit and tried to reinstall ..lambda.testtool.. However I received the following error:  Failed to create shell shim for tool 'amazon.lambda.testtool-6.0': Command 'dotnet-lambda-test-tool-6.0' conflicts with an existing command from another tool. 

To overcome the above error reference the following: https://stackoverflow.com/questions/58599978/cannot-start-lambda-with-mock-lambda-test-tool

Works now.  For some reason the installation of the toolkit was not correct as it should have installed the test-tool properly.

Thanks!
Andy
