### ISSUE TITLE
How to set dotnet6 runtime in CDK? 

### ISSUE THREAD

**Issue by Roman-Blinkov** [aws/aws-lambda-dotnet#1088]
Hi everyone!
How to set dotnet6 runtime in CDK? 
Currently it is not supported by Amazon.CDK Version=1.145.0

**Comment by peterwoodworth** [comment]
Hey @Roman-Blinkov,

The CDK will be able to support this once [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime) enables support for the dotnet6 Runtime. Until then, there won't be a way to create a lambda with the CDK with this Runtime.

**Comment by ashishdhingra** [comment]
> Hey @Roman-Blinkov,
> 
> The CDK will be able to support this once [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime) enables support for the dotnet6 Runtime. Until then, there won't be a way to create a lambda with the CDK with this Runtime.

@Roman-Blinkov Hope this provides guidance. Support for `dotnet6` target should be available in CloudFormation soon (along with any documentation updates, e.g., https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime) and  would be subsequently supported by CDK. Closing this issue for now.

**Comment by Roman-Blinkov** [comment]
> Hey @Roman-Blinkov,
> 
> The CDK will be able to support this once [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime) enables support for the dotnet6 Runtime. Until then, there won't be a way to create a lambda with the CDK with this Runtime.

AWS SAM already works for me via Visual Studio, but CDK not ready

**Comment by peterwoodworth** [comment]
Exactly, the CDK relies on CloudFormation, and CloudFormation currently does not support this runtime yet.

**Comment by Roman-Blinkov** [comment]
This issue waiting for 1 line commit approval
https://github.com/aws/aws-cdk/pull/19144/commits

**Comment by normj** [comment]
@Roman-Blinkov You are right the CloudFormation service does support the new `dotnet6` runtime and in a JSON/Yaml template you can specify the runtime as `dotnet6`. In CDK the `Runtime` enum will need to be updated which I believe, but I'm not on the CDK team, happens when the CDK team picks up the next CloudFormation schema changes. I'm not sure when that happens.
