### ISSUE TITLE
LambdaLoggerOptions should support wildcard categories

### ISSUE THREAD

**Issue by cfbarbero** [aws/aws-lambda-dotnet#109]
It would be nice to be able to use some sort of wildcard in the logger category.  The LambdaLoggerOptions built from IConfiguration doesn't support this.  This is supported in most logging frameworks like [NLog](https://github.com/NLog/NLog/wiki/Configuration-file#example-rules) and Log4Net.

For example:
```
{
  "Lambda.Logging": {
    "IncludeCategory": false,
    "IncludeLogLevel": false,
    "IncludeNewline":  false,
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Information",
      "Foo.*": "Information",
      "Foo.Bar.*": "Warning",
      "Foo.Bar.Baz": "Critical",
      "*": "Error"
    }
  }
}
```

## Rules
- Exact matches of Category take precedence.
  - "Microsoft" would log at information and above
- More specific wildcards match over less specific.
  - "Foo.Bar.Baz" would log at critical and above
  - "Foo.Bar.something" would log at error and above
  - "Foo.Other" would log at Information and above
- Catch all root level is supported with just a "*"
  - "blah" would log at Error and above
- Wildcards are only supported at the end of a category
  - "Foo.*.Blah" would throw an exception

**Comment by normj** [comment]
Closing this and will track it with your pull request. https://github.com/aws/aws-lambda-dotnet/pull/110
