### ISSUE TITLE
Version tags in the repository

### ISSUE THREAD

**Issue by vscheidegger** [aws/aws-lambda-dotnet#1090]
## The Question
Why there are no tags in this repo? It is pretty hard to debug and find issues on older versions when they are not tagged.
How is this controlled?

### Environment

* Build Version: 
* OS Info: 
* Build Environment: 
* Targeted .NET Platform:  

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @vscheidegger.

Good morning.

Thanks for posting guidance question. Currently we do not use version tags in this repository. There are multiple libraries in this repository including Lambda Core and Event POCO classes, and there is currently no feasible way to use version tags. After each release, we include an entry in [RELEASE.CHANGELOG.md](https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md) along with the version bump commit for a specific library. Bu comparing the RELEASE.CHANGELOG.md and version bump commit, you could get details of the specific commit for an issue. Hope this helps.

Thanks,
Ashish

**Comment by vscheidegger** [comment]
From the Changelog reference I could count ~270 versions:
![image](https://user-images.githubusercontent.com/92516894/155773279-8e316ba4-c9cd-41f1-95fc-f3f051f26afb.png)

It's not a really high number...
Tagging strategies like `{{component}}/{{version}}` shouldn't affect performance.

**Comment by ashishdhingra** [comment]
Thanks for the inputs. Based on discussion with the team, we are tracking this internally and might eventually prioritize to use version label tags in the future. Closing this issue here.
