### ISSUE TITLE
Lambda Annotations - Complex Request type is always null

### ISSUE THREAD

**Issue by bruceharrison1984** [aws/aws-lambda-dotnet#1094]
Playing around with the new Annotations library, and I cannot seem to get a complex request to come through in the body of a POST request. 

```csharp
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]
...
[LambdaFunction()]
[HttpApi(LambdaHttpMethod.Post, "/")]
public async Task Create([FromBody] CreateNewAccountRequest req, ILambdaContext context)
{
    if (req is null) throw new ArgumentNullException(nameof(req));

    using var cts = Utility.Utility.CreateLambdaLinkedToken(context.RemainingTime);

    context.Logger.LogInformation($"Creating account '${req.AccountName}'");

    await accountService.CreateAccount(req.AccountName, context.Logger, cts.Token);
}
...
public class CreateNewAccountRequest
{
    public string AccountName { get; set; }
}
```

Attempted payload from within Mock Lambda Test Tool:
```json
{
  "AccountName": "TestAccount"
}
```

Issuing any (blank or as above) request through the mock lambda tool always yields:
```json
{
"statusCode":400,
"headers":{"Content-Type":"application/json","x-amzn-ErrorType":"ValidationException"},
"body":"{\"message\": \"1 validation error(s) detected: Value  at 'body' failed to satisfy constraint: Value cannot be null. (Parameter 'json')\"}",
"isBase64Encoded":false}
```

The error is thrown before even hitting the `Create` method, so it seems like something is going with during deserialization because the ArgumentNullException never gets hit.

Starting the Lambda via `sam local start-api` sending the same payload, it appears to be properly passed in. So this seems to be something to do with how Mock Lambda tools works.

It also appears the just using the basic API request type, all properties and values on the `req` object are null when using the Mock Lambda Tool:
```csharp
public async Task<IActionResult> Create(APIGatewayHttpApiV2ProxyRequest req, ILambdaContext context)
```

**Comment by ashishdhingra** [comment]
Reproducible using `Amazon Lambda Test Tool 6.0` version `0.12.0` and [Amazon.Lambda.Annotations 0.5.0-preview](https://www.nuget.org/packages/Amazon.Lambda.Annotations/0.5.0-preview).

**Comment by normj** [comment]
Since you are using `HttpApi` attribute you need to pass in an [HTTP API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) full event object.  Below is an example that works with your example. 

The difference between the Mock test tool and `sam local` is the Mock tool invokes the code like a Lambda function and so you have to pass in the full event object and `sam local` emulate the API Gateway endpoint so you can make request to `sam local` like a regular REST API call.

```
{
  "version": "2.0",
  "routeKey": "$default",
  "rawPath": "/",
  "rawQueryString": "",
  "cookies": [
  ],
  "headers": {
  },
  "queryStringParameters": {
  },
  "requestContext": {
    "accountId": "123456789012",
    "apiId": "api-id",
    "domainName": "id.execute-api.us-east-1.amazonaws.com",
    "domainPrefix": "id",
    "http": {
      "method": "POST",
      "path": "/",
      "protocol": "HTTP/1.1",
      "sourceIp": "IP",
      "userAgent": "agent"
    },
    "requestId": "id",
    "routeKey": "$default",
    "stage": "$default",
    "time": "12/Mar/2020:19:03:58 +0000",
    "timeEpoch": 1583348638390
  },
  "body": "{\"AccountName\": \"TestAccount\"}",
  "pathParameters": {
  },
  "isBase64Encoded": false,
  "stageVariables": {
  }
}
```

**Comment by bruceharrison1984** [comment]
This makes perfect sense, and I don't know how I failed to make that connection. Thanks for the explanation.
