### ISSUE TITLE
Expose Environment variables in ILambdaContext

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#11]
Right now, Environment variables are found in the ClientContext that is populated only when the function is invoked by the Mobile SDK.

Wouldn't be better to have the Environment variables available directly in the LambdaContext that we can receive at execution time?

I am aware that we can use `System.Environment.GetEnvironmentVariable(<environmentvariablename>)`but it makes the code so poorly testable.

**Comment by Kralizek** [comment]
I was actually thinking of giving it a try myself but I couldn't find any concrete implementation but the one in the `Amazon.Lambda.TestUtilities` package.

Am I missing something?

**Comment by PavelSafronov** [comment]
Can you provide a list of the environment variables you are looking for? Some of these may already be exposed on ILambdaContext.

**Comment by Kralizek** [comment]
Mostly the custom ones you use to configure the Lambda.

**Comment by Kralizek** [comment]
Any comment about this suggestion? Also, is there any way I can contribute?

**Comment by Thaina** [comment]
@PavelSafronov I think the point he mention is, Custom Env var that could be set at lambda function. It could be a long list of keyvalue. And whenever we want to edit that list we need to get the whole list without reserved and system env variable

In my case I have lambda cron update everyday. I use environment variable to count number of day it was updated. I need to call `GetFunctionConfiguration` to get env list of current function, then update the day, and call `SetFunctionConfiguration` to set it back

If we expose those env in context object it would be easier to access and set, without get

But

@Kralizek It sadly that the core system of lambda does not give that in any language. Not in nodejs or java. We need AWS team to update the system before we could write library to support it

**Comment by Kralizek** [comment]
Wouldn't be easy to fix for .NET?

```
public interface ILambdaContext
{
    ...
    IDictionary EnvironmentVariables { get; }
    ...
}
```

and, in the concrete class implementing ILambdaContext, simply add

`public IDictionary EnvironmentVariables => System.Environment.GetEnvironmentVariables();`

if you want to be fancy, you can cast that `IDictionary` into a `IDictionary<string, string>`

**Comment by adamhathcock** [comment]
I don't understand why this has to be part of the SDK.  If you really want it, just make your own class that wraps `System.Environment.GetEnvironmentVariables()` and inject it in your constructor yourself.

**Comment by Thaina** [comment]
@Kralizek I used to think like you until I had found that there are EnvironmentVariables of system itself that I don't set it by myself and it hard to exclude all those

So the best solution for me is using `lambda.GetFunctionConfiguration().Environment.Variables`

**Comment by normj** [comment]
@Thaina it sounds like you are asking for the executing Lambda function to have a quick way to change the environment variables set in the Lambda function configuration. That brings in a host of concurrency questions and the service IAM role is likely not going to have permissions to modify the function's configuration.

**Comment by Thaina** [comment]
@normj It not only for change but we could set our own env variable in a way that can be iterate. To iterate all EnvVarible and exclude system keyword is prone to error

And I was set role of my lambda function to have lambda invoke permission. So it can change its own env variable programmatically when needed

I don't think it againts concurrency. Because changing env variable of lambda not affect current call. It effect the next call. It more like parameter of recursive function

**Comment by normj** [comment]
I see where you are going with this but it is beyond the scope of what we can do for the .NET Core tooling. You are looking for a Lambda service change that affects all runtimes. For that type of request I'd suggest going to the Lambda forums, https://forums.aws.amazon.com/forum.jspa?forumID=186.
