### ISSUE TITLE
API Gateway Integration Broken on Top-Level Statement Lambda using Source Generators

### ISSUE THREAD

**Issue by napalm684** [aws/aws-lambda-dotnet#1106]
## Description

API Gateway Lambda Proxy for REST APIs is not sending the request object body/path etc. to the handler on a top-level function using source generators approach for JSON Serialization.

## Reproduction Steps

```csharp
using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.Core;
using Amazon.Lambda.RuntimeSupport;
using Amazon.Lambda.Serialization.SystemTextJson;

var handler = (APIGatewayProxyRequest request, ILambdaContext context) =>
{
    context.Logger.LogInformation("Path " + request.Path + " body " + request.Body);
    return new APIGatewayProxyResponse { StatusCode = 200 };
};

await LambdaBootstrapBuilder.Create(handler, 
    new SourceGeneratorLambdaJsonSerializer<HttpApiJsonSerializerContext>())
    .Build()
    .RunAsync();
```

```csharp
using System.Text.Json.Serialization;
using Amazon.Lambda.APIGatewayEvents;

namespace MyProject;

[JsonSerializable(typeof(APIGatewayProxyRequest))]
[JsonSerializable(typeof(APIGatewayProxyResponse))]
public partial class HttpApiJsonSerializerContext : JsonSerializerContext
{
}
```

Other info: `DefaultLambdaJsonSerializer` works as expected, so I suspect the problem lies with use of `SourceGeneratorLambdaJsonSerializer`

### Logs

N/A - Reproduce-able solution provided above

### Environment

* Build Version: 
Amazon.Lambda.Serialization.SystemTextJson 2.2.0
Amazon.Lambda.RuntimeSupport 1.7.0 
* OS Info: N/A -- Lambda
* Build Environment: dotnet cli
* Targeted .NET Platform:  6.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by napalm684** [comment]
Another update, I suspect this happens because there doesn't seem to be a way to customize the JsonSerializerOptions to match the default serializer.

**Comment by normj** [comment]
I'm taking a look into how we can expose the customization of the `JsonSerializerOptions`.

**Comment by normj** [comment]
The PR is out to get the issue fixed. https://github.com/aws/aws-lambda-dotnet/pull/1120 I'll try and get this out as soon as I can.

**Comment by napalm684** [comment]
Thank you for the speedy response.  Looking forward to the release!

**Comment by normj** [comment]
Version 2.3.0 of **Amazon.Lambda.Serialization.SystemTextJson** is out which makes `SourceGeneratorLambdaJsonSerializer` use the same `JsonSerializerOptions` as `DefaultLambdaJsonSerializer`.

The side affect of this change is the `JsonSourceGenerationOptions` attribute will no longer have any affect. If you want to customize the `JsonSerializerOptions` you need to extend `SourceGeneratorLambdaJsonSerializer`. This is documented in the package's [README](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/README.md) file.
