### ISSUE TITLE
API Gateway for DotNet Lambda

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#111]
What is the magic to get API Gateway working with a DotNet Lambda?

For example for the base ASP.NET Core to invoke /api/values

I tried adding resources for /Prod/api/values and for /api/values but in either case when I test I get

Decoded string is not a valid IDN name.

Thanks,
Dave

**Comment by PavelSafronov** [comment]
Using [AWS Toolkit for Visual Studio](https://aws.amazon.com/visualstudio/) you can deploy Lambda functions that are exposed through API Gateway. Take a look at [this blog post](https://aws.amazon.com/blogs/developer/aws-serverless-applications-in-visual-studio/) for more information.

**Comment by milla** [comment]
@PavelSafronov When will Lambda support .net core 1.1?

**Comment by genifycom** [comment]
My understanding is that .net core 1.0 is the only LTS version and Amazon will only support LTS versions. This means that 1.1 will not be supported. We will have to wait until the next Microsoft LTS version release.

**Comment by genifycom** [comment]
Hi Pavel, yes this is the way I deploy right now. But I wanted to set up an API gateway directly through the create API page and with the rest actions as resources. This is the bit I am having trouble with.

**Comment by PavelSafronov** [comment]
I'd recommend going with the AWS CloudFormation approach as outlined in the blog post I linked earlier, as it will perform the setup for you, can be versioned, and can be shared. Going through the AWS Console is a more manual process.

However, if you do want to use the AWS Console to setup API Gateway, you of course can. Some good resources to get you started on that is the [Amazon API Gateway documentation](http://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html) and the related [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=199).

This repo is specifically for questions and bug reports for the multiple `Amazon.Lambda.*` NuGet packages, and your overall question seems to be about the service and the Console, so I'm closing this issue.
