### ISSUE TITLE
How to make a connection to RDS MS SQL 2019 Instance using certificate from a Lambda?

### ISSUE THREAD

**Issue by gopinathrimc** [aws/aws-lambda-dotnet#1112]
## How to specify Cert Store from a Lambda to connect to a MS SQL 2019 RDS Instance ?

I have a lambda function written in dotnet 6 from which am trying to call a stored procedure in MS SQL 2019 RDS Instance. I am using Microsoft.Data.SqlClient with encrypt=true;TrustServerCertificate=false;  as part of the connection string.

But am getting the following exception:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)

---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
```

Do i need to specify a certificate to use from the lambda function to establish the connection? if so how to go about doing it?

### Environment

* Build Version: Microsoft.Data.SqlClient 4.1.0
* OS Info:  OSX Monterey
* Build Environment: VSCode + Terminal `dotnet` 
* Targeted .NET Platform:  dotnet 6

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @gopinathrimc,

Thanks for posting guidance question.

Could you please share the sample code and steps used to deploy Lambda function along with any specific RDS settings, to reproduce the issue? In the meanwhile, following links might be helpful: 
- [Tutorial: Configuring a Lambda function to access Amazon RDS in an Amazon VPC](https://docs.aws.amazon.com/lambda/latest/dg/services-rds-tutorial.html)
- [Can Lambda and RDS Play Nicely Together?](https://blog.thundra.io/can-lambda-and-rds-play-nicely-together)
- https://github.com/npgsql/npgsql/issues/2834#issuecomment-682171872
- [How do I successfully connect to my Amazon RDS instance using an SSL connection?](https://aws.amazon.com/premiumsupport/knowledge-center/rds-connect-ssl-connection/)
- [Using SSL with a Microsoft SQL Server DB instance](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/SQLServer.Concepts.General.SSL.Using.html)

Thanks,
Ashish

**Comment by gopinathrimc** [comment]
@ashishdhingra ,

Lambda is created as part of a CDK stack and deployed using the CDK CLI. 

The lambda and the RDS are in the same VPC and i have assigned the private subnets used by the RDS instance as part the Lambda configuration in CDK.


In the CDK
```
var vpc = Vpc.FromVpcAttributes(this, "Vpc", new VpcAttributes {
                            AvailabilityZones = new [] { "us-east-1a", "us-east-1b","us-east-1c" , "us-east-1d"},
                            PrivateSubnetRouteTableIds = new[] {"rtb-XXXX","rtb-YYYY","rtb-ZZZZ","rtb-QQQQ"},
                            PrivateSubnetIds = new [] { "subnet-XXXX", "subnet-YYYY","subnet-ZZZZ" , "subnet-QQQQ"},
                            VpcId = "vpc-AAAA"
                        });

var lambda = new Function(this,"[FnName]", new FunctionProps() {
                              ...
                            Vpc = vpc
                        }
```


In the Lambda

```
using (SqlConnection cnTemp = new SqlConnection(connectionStrings)
 {
                using (SqlCommand cmdTemp = new SqlCommand())
                {
                    cmdTemp.CommandType = System.Data.CommandType.StoredProcedure;
                    cmdTemp.CommandText = "spQQQQ";
                        //Setup parameters
                        ...
                    cmdTemp.Connection = cnTemp;
                    cnTemp.Open();
                    cmdTemp.ExecuteNonQuery();
               }
}

```
When the connection string uses Encrypt=True;TrustServerCertificate=True; I am able to make the stored procedure call. 

But when I change the connection string to Encrypt=True;TrustServerCertificate=False;  
I get the following exception:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.

```
So how do I go about validating the Remote certificate against the client certificate with in a lambda?

Thanks

**Comment by ashishdhingra** [comment]
@gopinathrimc [Updating applications to connect to Microsoft SQL Server DB instances using new SSL/TLS certificates](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/ssl-certificate-rotation-sqlserver.html) provides some information about your use case. But it doesn't say much about Lambda. I'm also not sure if you are affected by the issue https://github.com/dotnet/SqlClient/issues/1402. [Using TrustServerCertificate](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax#using-trustservercertificate) provides some ADO.NET specific information, but might not be helpful. Were you able to do successful validation locally, before deploying to Lambda? Based on information available online, you could try using `RemoteCertificateValidationCallback`, details could be available in Microsoft's documentation on how to use it with ADO.NET.

**Comment by ashishdhingra** [comment]
@gopinathrimc [Updating applications to connect to Microsoft SQL Server DB instances using new SSL/TLS certificates](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/ssl-certificate-rotation-sqlserver.html) provides some information about your use case. But it doesn't say much about Lambda. I'm also not sure if you are affected by the issue https://github.com/dotnet/SqlClient/issues/1402. [Using TrustServerCertificate](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-string-syntax#using-trustservercertificate) provides some ADO.NET specific information, but might not be helpful. Were you able to do successful validation locally, before deploying to Lambda? Based on information available online, you could try using `RemoteCertificateValidationCallback`, details could be available in Microsoft's documentation on how to use it with ADO.NET.
