### ISSUE TITLE
How to configure LambdaLoggerOptions LogLevels filters from environment variables?

### ISSUE THREAD

**Issue by anuith** [aws/aws-lambda-dotnet#1117]
## The Question

I'm creating a Lambda Function created from template in Visual Studio and use AWS Lambda Logging by calling `AddLambdaLogger` in `IServiceCollection` chain like this :

```c#
var services = new ServiceCollection();
var configuration = new ConfigurationBuilder()
    .SetBasePath(System.IO.Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json")
    .AddEnvironmentVariables("appsettings_")
    .Build();

services
    .AddLogging(builder => builder
        .SetMinimumLevel(LogLevel.Debug)
        .AddLambdaLogger(configuration, "Logging")
    );

...
```

It works fine when environment variables set from `launchSettings.json` like this :

```jsonc
{
  "profiles": {
    "Mock Lambda Test Tool": {
      ... 
      "environmentVariables": {
        "appsettings_Logging__LogLevel__MyNamespace.MyClass": "Debug"
      }
    }
  }
}
```

But environment variable on Lambda configuration page cannot contain dots `.`

I tried using double underscore like `MyNamespace__MyClass` but not work.

My current workaround is to change the `appsettings.json` file and upload the package to Lambda function.

Is there any way to set those configuration without having to upload the package?

### Environment

* Build Version: `3.1.0`
* OS Info: `Windows 10`
* Build Environment: `Visual Studio`
* Targeted .NET Platform:  `.NET Core 3.1`

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @anuith,

Good morning.

Thanks for posting guidance question. Could you please refer section `Using log levels` at [Lambda function logging in C#
](https://docs.aws.amazon.com/lambda/latest/dg/csharp-logging.html) which states that you could leverage `AWS_LAMBDA_HANDLER_LOG_LEVEL` environment variable to achieve your use case. AWS Lambda does not document support for hierarchical environment variables.

Refer https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0, which states that `launchSettings.json` file:
- Is only used on the local development machine.
- Is not deployed.
- Contains profile settings

Thanks,
Ashish

**Comment by anuith** [comment]
Thank you @ashishdhingra

I think I can use `AWS_LAMBDA_HANDLER_LOG_LEVEL` for this situation. But it would be better if in the future it can support hierarchical environment variables in a way. Like letting developers escape `.` with some other characters.

And I forgot to mention that I only tried `launchSettings.json` on my local machine and not intended to use it in Lambda deployment.
