### ISSUE TITLE
Lambda Test UI not displaying for dotnet 6

### ISSUE THREAD

**Issue by charithjj** [aws/aws-lambda-dotnet#1119]
I have installed AWS .NET Mock Lambda Test Tool and all the configs have correct values. I am trying to get the test UI getting displayed. 
This is all what I get. Is there any known issue with dotnet6?

This site can’t provide a secure connectionlocalhost sent an invalid response.
[Try running Windows Network Diagnostics](javascript:diagnoseErrors()).
ERR_SSL_PROTOCOL_ERROR

This is a :bug: bug-report

**Comment by charithjj** [comment]
Hi Ashish
Thanks for the reply!
Our environment has an automatic https redirection. Is there anyway to pass --https or --ssl as a command line argument in order to support https? 

Looks like it has been hardcoded at the moment...
Thanks,
Charith

**Comment by ashishdhingra** [comment]
> Hi Ashish
> 
> Thanks for the reply!
> 
> Our environment has an automatic https redirection. Is there anyway to pass --https or --ssl as a command line argument in order to support https? 
> 
> 
> 
> Looks like it has been hardcoded at the moment...
> 
> Thanks,
> 
> Charith

@charithjj No, there is no such option at the moment.

**Comment by ronaldorss** [comment]
I had the same problem, I solved it by clearing the chrome cache.

**Comment by savanvadalia** [comment]
Hey @ashishdhingra ,

I think this happening because chrome enforces SSL/https now by default, I tried changing my default browser to firefox and it worked fine. Can you please suggest a option to use the mock lambda test too in SSL/https?

**Comment by 0samaHaider** [comment]
Same error. Resolved with using http instead of https.
