### ISSUE TITLE
Executable Assembly Functions Not Processing Events - JetBrains Rider

### ISSUE THREAD

**Issue by napalm684** [aws/aws-lambda-dotnet#1126]
## Description
Following the instructions here https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider to setup JetBrains Rider along with instructions found in the dotnet 6 test tool UI (see Documentation link) results in events being queued that never process/execute.

## Reproduction Steps

aws-lambda-tools-defaults.json
```
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "us-east-1",
  "configuration": "Debug",
  "framework": "net6.0",
  "function-runtime": "dotnet6.0",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-handler": "MyFunction"
}
```

launchSettings.json
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "MyFunction": {
      "commandName": "Executable",
      "commandLineArgs": "--port 5050",
      "executablePath": "/Users/xxx/.dotnet/tools/.store/amazon.lambda.testtool-6.0/0.12.1/amazon.lambda.testtool-6.0/0.12.1/tools/net6.0/any/Amazon.Lambda.TestTool.BlazorTester.dll",
      "workingDirectory": "/Users/xxx/dev/MyFunction/src/MyFunction",
      "environmentVariables": {
        "AWS_LAMBDA_RUNTIME_API": "localhost:5050",
        "AWS_PROFILE": "myawsprofile",
        "AWS_REGION": "us-east-1",
      }
    }
  }
}
```

### Logs

None to provide no error, just events don't process

### Environment

* Build Version:  amazon.lambda.tools version 5.3.0
* OS Info:  MacOS Monterey v12.3
* Build Environment:  JetBrains Rider 2021.3.3
* Targeted .NET Platform:  6.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @napalm684,

Good afternoon.

Could you please share the sample code and the request(s) from Lambda Test Tool UI which are queued but never executed for you? This appears to be a basic scenario and should work. 

Thanks,
Ashish

**Comment by napalm684** [comment]
@ashishdhingra 
I need some time to pull together a post-able repro for you.

**Comment by napalm684** [comment]
So this produces the issue for me:

- Install templates `dotnet new -i Amazon.Lambda.Templates`
- Run `dotnet new lambda.EmptyTopLevelFunction --name <your pick>`
- Open the project in Rider and add a _launchSettings.json_ under a `Properties` folder in the project
- Take the sample _launchSettings.json_ above and put those contents in updating for your directory paths
- Take the contents for _aws-lambda-tools-defaults.json_ and update the project's file to those contents
- Switch Rider to use the launch configuration you created in _launchSettings.json_
- Debug the project
- Go to Executable assembly page
- Enter event "whatever string you like"
- Verify it never gets processed in the Queued Events section of the UI

Hope this helps.

**Comment by ashishdhingra** [comment]
Appears to be reproducible. Not sure if additional action needs to be taken to process Queued events.
<img width="1421" alt="Screen Shot 2022-04-04 at 12 24 03 PM" src="https://user-images.githubusercontent.com/67916761/161617101-99168390-c6b2-4b86-b322-172453eebcc8.png">

Visual Studio Code appears to have the same issue. (Visual Studio for Mac 2019 cannot be tested since it doesn't support .NET 6 projects).

**Comment by sl-omideidivandi** [comment]
I have same problem in VS2022 and VsCode
I'm just running the example form Aws Blog to test top level statement and ca not reach the code locally from Test tool

**Comment by savva312** [comment]
Hello, I am having the same issue, is there an update on this yet?

**Comment by lajo-scanmarket-com** [comment]
Also having same issue

**Comment by ashishdhingra** [comment]
> @normj I've seen you using it in a youtube video succesfully and I don't think it's Rider related: https://www.youtube.com/watch?v=l4_WNjMHDx8&t=3386s
> 
> Do you maybe have an idea why I and also others can't get it working?

@napalm684 Following video, looks like the Lambda Test tool for executable assembly tab, displays the message **For Lambda functions written as executable assemblies, i.e. custom runtimes functions and top level statement functions, this page can be used for testing the functions locally. Set the AWS_LAMBDA_RUNTIME_API environment variable to localhost:5050 while debugging executable assembly Lambda function. More information can be found in the [documentation](http://localhost:5050/documentation).**. So once, you invoke the Lambda test tool in web browser and queue the test event(s), 
- Right click the project and select `Modify Run Configuration...`.
- In `Edit Run Configuration` dialog, add environment variable `AWS_LAMBDA_RUNTIME_API` with value `localhost:5050`.
- Click `Apply` and then `OK`.
- Setup breakpoint in Lambda handler.
- Right click project again and select `Debug <<projectname>>`.

I tested and it works. Please verify the same at your end and confirm if this issue could be closed.

**Comment by napalm684** [comment]
> eue

I had that env var set and it still doesn't work. I will have to watch the youtube video and report back.

![image](https://user-images.githubusercontent.com/8197405/178521909-67774663-2bd3-44be-b8b9-44e4ab918c10.png)

**Comment by napalm684** [comment]
I have it working from the test tools perspective it is triggering, with one exception. There seems to be an issue with calling AWS services in debug inside the handler or initializer. If you wait long enough this error seems to come up consistently:

```
System.InvalidOperationException: Assembly AWSSDK.SSOOIDC could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.SSOAWSCredentials, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.SSOOIDC, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'AWSSDK.SSOOIDC, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Amazon.Runtime.Internal.ServiceClientHelpers.GetSDKAssembly(String assemblyName)
   at Amazon.Runtime.Internal.ServiceClientHelpers.LoadTypeFromAssembly(String assemblyName, String className)
   at Amazon.Runtime.Internal.ServiceClientHelpers.LoadServiceConfigType(String assemblyName, String serviceConfigClassName)
   at Amazon.Runtime.Internal.ServiceClientHelpers.CreateServiceConfig(String assemblyName, String serviceConfigClassName)
   at Amazon.Runtime.SSOAWSCredentials.CreateClient[T](String serviceClassName, String serviceConfigName, String parentAssemblyName)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.SSOAWSCredentials.CreateClient[T](String serviceClassName, String serviceConfigName, String parentAssemblyName)
   at Amazon.Runtime.SSOAWSCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.XRay.Recorder.Handlers.AwsSdk.Internal.XRayPipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at MyProject.Common.Services.RegistrationService.GetRegistrationRecord(String identifier) in /Users/xxxx/dev/xxxx/my-project/src/MyProject.Common/Services/RegistrationService.cs:line 71
   at Program.<Main>$(String[] args) in /Users/xxxx/dev/xxxx/my-project/src/MyProject/Handler.cs:line 24
   at Program.<Main>(String[] args)
```

**Comment by ashishdhingra** [comment]
> I have it working from the test tools perspective it is triggering, with one exception. There seems to be an issue with calling AWS services in debug inside the handler or initializer. If you wait long enough this error seems to come up consistently

@napalm684 Are you by any chance using SSO locally? If yes, this doesn't appear to be production scenario where you might not be able to use SSO in actual Lambda environment and permissions are set by attaching IAM roles.

**Comment by napalm684** [comment]
@ashishdhingra yes we use SSO for local development.

**Comment by normj** [comment]
@napalm684 To use SSO you need to take a dependency on `AWSSDK.SSO` and `AWSSDK.SSOOIDC` for the SDK to resolve your credential profile into AWS credentials. Since you only need the SSO packages for local debug I suggest adding the dependencies to the project file conditionally so they don't get added to the deployment bundle for Lambda. Here is an example of what I mean.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='DEBUG'">
    <PackageReference Include="AWSSDK.SSO" Version="3.7.0.179" />
    <PackageReference Include="AWSSDK.SSOOIDC" Version="3.7.0.179" />
  </ItemGroup>

</Project>
```

**Comment by napalm684** [comment]
Thx @normj that did it.

This can be closed. While I think the documentation for the tool might be a little more robust, for anyone that stumbles upon this until that time, here is what I did with rider.

- Run ~/.dotnet/tools/dotnet-lambda-test-tool-6.0 in its own process/terminal
- Add the env var for AWS_LAMBDA_RUNTIME_API as described above
- If using SSO add the conditional packages as described by @normj 
- Debug your project
- Queue up an event and you should hit your breakpoint(s)

Thanks everyone for the assistance getting this running and shortening my team's feedback loop! 🥳

**Comment by normj** [comment]
@napalm684 Great to hear you are working. I agree the documentation for this feature is lacking and it is important we get that fixed. I think your SSO issue is also a great candidate to go in the tool's FAQ.
