### ISSUE TITLE
IHostApplicationLifetime ApplicationStarted OnStarted not being reached/not registered

### ISSUE THREAD

**Issue by alancosta-iress** [aws/aws-lambda-dotnet#1127]
### Environment

* Build Version:  7.0.1
* OS Info:  Windows 10
* Build Environment:  Visual Studio 2019
* Targeted .NET Platform: netcoreapp3.1

---

The `IHostApplicationLifetime` is not available when the Lambda entry point is initiated via `APIGatewayProxyFunction` base class. Is this by design? We want to wait for services configuration to be finished to finally have some initialisation calls, but registration of `OnStarted` (i.e [IHostApplicationLifetime](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1#ihostapplicationlifetime-interface-2)) is never reached. This works just fine when the service runs via the main function.

**Comment by ashishdhingra** [comment]
Need to check with the team on this limitation.

**Comment by alancosta-iress** [comment]
Okay, that is **not** an issue with AspnetCoreServer. I misplaced an asynchronous call in OnStarted. Nothing to do with the host coming from the base class. Closing it.
