### ISSUE TITLE
dotnet lambda deploy-function failing with LambdaException

### ISSUE THREAD

**Issue by PaulColeman** [aws/aws-lambda-dotnet#113]
Is there a preferred docker image for building dotnet lambda code? I'm currently using `microsoft/dotnet` (in a bitbucket pipeline) and then using ` dotnet lambda deploy-function` to publish and deploy it. 

When I try to test the function in Lambda I get a `LambdaException` error that states "Unable to load assembly". However, if I build locally on my Windows 10 machine (not using the docker image) and use the same `dotnet lambda deploy-function` command everything works.

I have made sure that my project is targeting `netcoreapp1.0` and I'm using Amazon.Lambda.Tools 1.5.0; I'm guessing that something is a little off with that docker image.

For "fun" I compared the dependency files for the two different builds and found a few differences, but only with the "sha512", and only for the following packages:

- microsoft.extensions.*
- newtonsoft.json/9.0.1
- system.data.common/4.1.0
- system.runtime.serialization.primitives/4.1.1

**Comment by PaulColeman** [comment]
I've figured out a bit more about the puzzle. 

If I download the zip that is produced by `dotnet lambda deploy-function` (by the `microsoft/dotnet
` docker image in bitbucket) and then re-upload it via the Upload Function Package in the AWS Lambda console it still fails. **However** if I take the same zip, unzip it on my machine, and re-zip it and upload that package via the lambda console **it works**.

I'm attaching the zip file that is failing. Its the BlogFunction example.

https://github.com/aws/aws-lambda-dotnet/files/978719/BlogFunction.zip

**Comment by normj** [comment]
I suspect what is happening is `Amazon.Lambda.Tools` can't find the `zip` utility program in your docker image.

When deploying from Linux the deployment tool searches for the command line tool `zip` in your path and uses that to zip up the publish folder. This is needed to maintain Linux file permissions that the .NET Zip library doesn't do. Right now the code searches for `zip` in the path and if it doesn't find it assumes this is Windows and uses the .NET Zip library. I have made a change that will go out with the next version that error out with a proper error message if you are deploying from Linux and we can't find `zip`

**Comment by PaulColeman** [comment]
That was it! When I installed zip (`apt-get -y install zip`) everything worked as expected.

**Comment by normj** [comment]
Great!

**Comment by otakusid** [comment]
Please can you add an option that disable creating of zip archive? With this parameter **Amazon.Lambda.Tools** just put all binaries in specified folder. This make behavior of **Amazon.Lambda.Tools** similar to **dotnet cli** and users have ability to use the same set of tools to compile lambda functions and usual .net core apps.

At this moment if I want to build aws lambda I cant use **microsoft/aspnetcore-build** docker image recomended by Microsoft without additional modifications. Also I should change default flow because archive alredy created by **Amazon.Lambda.Tools**
