### ISSUE TITLE
AspNetCoreServer HTTP request body empty

### ISSUE THREAD

**Issue by danielbichuetti** [aws/aws-lambda-dotnet#1133]
## Description
Request body is not being correctly deserialized using WebApi blueprint. It's always null. If passing pure string, them it reads

## Reproduction Steps
1. Create Lambda ASP.NET Core Web Api.

2. Add one complex type and then try to get it on post
`
public class Test
{
  public string value;
}
`
`   
// POST api/values
[HttpPost]
public void Post([FromBody] Test testObject)
 {
    return testObject.value;
 }
`
3. Make a POST sending a json like
`
{
  "value":"testString"
}
`
4. Return is always null and if the post is a pure string, like "testString" then it gets.

### Environment

* Build Version: Amazon.Lambda.ASpnetCoreServer 7.1
* OS Info: Amazon Linux
* Build Environment: Visual Studio 2022
* Targeted .NET Platform:  .NET 6

This is a :bug: bug-report

**Comment by danielbichuetti** [comment]
When using ASP.NET Minimal API Template which uses AspNetCoreServer.Hosting and AddAWSLambdaHosting, it worked fine. Issue is only on old way of doing it.

**Comment by normj** [comment]
I just tried to reproduce the issue and my post worked correctly. My suspicion is Amazon.Lambda.AspNetCoreServer 7.1 didn't get packaged in the Lambda function and instead 7.0 went in. Can you confirm the NuGet package is updated and be sure to do a Save All in VS before launching the deploy wizard. I'm guessing the package was updated but the csproj file wasn't saved yet to disk.

Here is what I did to reproduce, let me know if I'm missing a step.

Created non-minimal style project.

![image](https://user-images.githubusercontent.com/1653751/161355676-c2c74688-f4cc-413d-8114-6d2ebe314f19.png)

Confirmed my version of `Amazon.Lambda.AspNetCoreServer` was set to 7.1.0

Controller code:
```csharp
[Route("api/[controller]")]
public class ValuesController : ControllerBase
{
    // GET api/values
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }

    // GET api/values/5
    [HttpGet("{id}")]
    public string Get(int id)
    {
        return "value";
    }

    // POST api/values
    [HttpPost]
    public string Post([FromBody] Test value)
    {
        Console.WriteLine(value.Value);
        return value.Value.ToUpper();
    }
}

public class Test
{
    public string Value { get; set; }
}
```

Postman test:
![image](https://user-images.githubusercontent.com/1653751/161355746-e94fa512-e93c-44cc-b85e-8f71c882a868.png)

**Comment by danielbichuetti** [comment]
Hello @normj! 

I have just made another test. This time I manually run dotnet clean and rebuild, before publishing. I'm making use of VS 2022 Preview 2.0. I think this was related to the updated package not being built repeatedly. 

I remember some years ago one issue with VS not doing proper cleaning before rebuilding after saving. I'll test VS later and report to MS if I find anything.

I appreciate your reply. You are definitely a great member of the community.

Have a great weekend.
