### ISSUE TITLE
Ajax invoke support in .NET Mock Lambda Test Tool

### ISSUE THREAD

**Issue by wahmedswl** [aws/aws-lambda-dotnet#1137]
### Describe the feature

Currently we can test via payload when The AWS .NET Mock Lambda Test Tool is ran. Is there any option that we can invoke it externally eg: via ajax request to hook into the debug cycle transparently. 

### Use Case

It will enable transparent debug cycle from Browser to Lambda Function albeit via some tweak to payload etc if required. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

<PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.4.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="2.0.0" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="3.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.SNSEvents" Version="2.0.0" />
    <PackageReference Include="AWSXRayRecorder.Handlers.AwsSdk" Version="2.8.3" />
    <PackageReference Include="AWSXRayRecorder.Handlers.System.Net" Version="2.7.3" />

### Targeted .NET Platform

.Net Core 3.1

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @wahmedswl,

Good morning.

Thanks for the feature request. I'm not sure if this feature is feasible but I will review it with the team. While I cannot commit on the timeline, but would post any updates here.

Regards,
Ashish

**Comment by wahmedswl** [comment]
Hi, feasible mean cannot support or weird/unrealistic etc? Lambda Test Tool has all the features, current for test payload need to be copy-pasted. Just having api endpoint that can be directly invoked will open up it for direct consumption.

Thanks

**Comment by wahmedswl** [comment]
Hi, https://github.com/aws/aws-lambda-runtime-interface-emulator project kinda does this i guess, but it depends on the Docker. So, having this directly here would help a lot.

Thanks

**Comment by ashishdhingra** [comment]
Closing this in favor of new issue https://github.com/aws/aws-lambda-dotnet/issues/1279.
