### ISSUE TITLE
typo in APIGatewayEvents.ProxyRequestContext property

### ISSUE THREAD

**Issue by belgab1980** [aws/aws-lambda-dotnet#1140]
### Describe the bug

ConnectionAt is not deserialized correctly

### Expected Behavior

ConnectionAt property set to the returned value

### Current Behavior

ConnectionAt always set to 0

### Reproduction Steps

Just run a WebSocket API

### Possible Solution

rename ConnectionAt to ConnectedAt or add an alias in order to not break code that uses the current name.

### Additional Information/Context

sample raw json returned in Websocket API:
    "requestContext": {
    ...
        "**connectedAt**": 1649450522109,
    ...
    },

### AWS .NET SDK and/or Package version used

Amazon.Lambda.APIGatewayEvents v2.4.0

### Targeted .NET Platform

.net core 3.1

### Operating System and version

any

**Comment by ashishdhingra** [comment]
Hi @belgab1980,

Good morning.

Could you please share the sample code for the Lambda function to troubleshoot the issue? Looking at [aws-lambda-java-events > APIGatewayV2WebSocketEvent](https://github.com/aws/aws-lambda-java-libs/blob/a9819fb50b2926ad9e31a30f4365cdc8be9d4023/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2WebSocketEvent.java#L228), this appears to be an issue, but I could not find any detail about `connectedAt` property at https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-create-api-as-simple-proxy, so want to make sure that we are looking at the right class.

Thanks,
Ashish

**Comment by belgab1980** [comment]
Hi Ashish,

 

I’m using a Websocket API Gateway.

 

This is from the code I’ve download a few days ago

\aws-lambda-dotnet-master\Libraries\src\Amazon.Lambda.APIGatewayEvents\APIGatewayProxyRequest.cs

…

            /// <summary>

            /// The Epoch-formatted connection time in a WebSocket API.

            /// <para>

            /// This field is only set for WebSocket API requests.

            /// </para>

            /// </summary>

            public long ConnectionAt { get; set; }

…

 

It should read

            public long ConnectedAt { get; set; }

 

 

The RAW JSON Request Context I’m seeing is as follows:

    "requestContext": {

        "routeKey": "$connect",

        "authorizer": {

            "principalId": "<MyId>",

            "integrationLatency": 10436,

            …

        },

        "eventType": "CONNECT",

        "extendedRequestId": "0123456789=",

        "requestTime": "08/Apr/2022:20:42:02 +0000",

        "messageDirection": "IN",

        "stage": "test",

        "connectedAt": 1649450522109,

        "requestTimeEpoch": 1649450522110,

        "identity": {

            "userAgent": "MyAgent",

            "sourceIp": "192.0.2.1"

        },

        "requestId": "0123456789=",

        "domainName": "0123456789.execute-api.us-east-1.amazonaws.com",

        "connectionId": "0123456789=",

        "apiId": "0123456789"

    }

 

 

I’m using it in a code like this (I’m using a modified version of APIGatewayProxyRequest in order for RequestContext.ConnectedAt to work):

public async Task<APIGatewayProxyResponse> FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context)

        {

…

             

                DateTimeOffset connectedAt = DateTimeOffset.FromUnixTimeMilliseconds(request.RequestContext.ConnectedAt);

…            

        }

 

Gabriele

**Comment by ashishdhingra** [comment]
@belgab1980 I think instead of modifying existing class, we need to have separate `APIGatewayWebsocketProxyRequest` as shown in [Go](https://github.com/aws/aws-lambda-go/blob/a0b8edad15ca314981ef1bcbc0b58283191dcbf9/events/apigw.go#L169) repository. This needs review with the team.

**Comment by ashishdhingra** [comment]
Just for reference, [API Gateway WebSocket API mapping template reference](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html) specifies `$context.connectedAt` parameter.

**Comment by ashishdhingra** [comment]
Fixed in [Amazon.Lambda.APIGatewayEvents version 2.4.1](https://www.nuget.org/packages/Amazon.Lambda.APIGatewayEvents/2.4.1)
