### ISSUE TITLE
Enhance MarshalRequest/InvokeFeatures to setup the IHttpRequestIdentifierFeature

### ISSUE THREAD

**Issue by brendonparker** [aws/aws-lambda-dotnet#1148]
### Describe the feature

Enhance the Lambda to AspNetCore handoff to include either (or both) the `AwsRequestId` from the `ILambdaContext` and the `TraceId` from the `LambdaContext`.

### Use Case

This will help log correlation with things like AWS X-Ray, or other AWS Logs that are capturing the RequestId.

### Proposed Solution

1. Enhance `Amazon.Lambda.AspNetCoreServer.Internal.InvokeFeatures` to implement `Microsoft.AspNetCore.Http.Features.IHttpRequestIdentifierFeature`.
2. Enhance the various implementations of `MarshallRequest` to setup the `IHttpRequestIdentifierFeature`, specifying using the `ILambdaContext.AwsRequestId`.

### Other Information

See linked discussion for the path I took to get here. I'm not certain which makes more sense to use, the AwsRequestId or the TraceId. May depend on if you are using AWS X-Ray. Perhaps configurable?

This _may_ be considered a breaking change, as it will no longer use the dotnet-generated RequestId. However, I feel using the AwsRequestId is more correct.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.Hosting 1.0.0

### Targeted .NET Platform

.NET Core 3.1, .NET 6

### Operating System and version

Windows 10, OSX Mojave, Ubuntu, AmazonLinux

**Comment by brendonparker** [comment]
Here is the discussion: https://github.com/aws/aws-lambda-dotnet/discussions/1147

**Comment by normj** [comment]
Thanks for the great feature request. I like the idea of having the `HttpContext.TraceIdentifier` match the X-Ray trace ID. I think we should aim to do that.

As far as customization goes in the older style of writing ASP.NET Core Lambda functions you used to be able to override methods from a base class to customize the marshalling between API Gateway and ASP.NET Core. That ability got lost in the new approach using the `AddAWSLambdaHosting` extension method to initialize Lambda. My plan is to allow `Action` callbacks to be added during the `AddAWSLambdaHosting` method to provide back the old customization features.

**Comment by brendonparker** [comment]
Yes, some config or extensibility hooks may solve parts of this. 

Let me know if I can be of more help, create a PR, etc.

**Comment by normj** [comment]
I put out the PR set the `HttpContext.TraceIdentifier` property. https://github.com/aws/aws-lambda-dotnet/pull/1172

I haven't add the customization features yet because that one is more complicated and I didn't want getting the trace identifier to be blocked on that. The trouble with customization feature is the parameters to the Action callback change depending on what you are using for `LambdaEventSource`. So I'm still debating the best solution for that.

**Comment by brendonparker** [comment]
Sweet!

**Comment by sakopov** [comment]
Probably a bad idea, but just throwing it out there... Why not just provide access to `ILambdaContext` similar to how `HttpContext` is given access to via [`IHttpContextAccessor`](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Http/Http/src/HttpContextAccessor.cs)? I feel like this is something that should be available to the entire request pipeline. Especially in controller actions when deploying Web API as a serverless function.

**Comment by brendonparker** [comment]
@sakopov Agree, adding the TraceId to the `ILambdaContext` may also be a nice enhancement. But ultimately not necessary if the ASPNET request gets the RequestId set properly upstream. The approach that @normj took will ensure the framework's notion of "RequestId" is set using the Lambda TraceId, which will get picked up in other logging scenarios outside of your own application's logs.
