### ISSUE TITLE
An error occurred while attempting to execute your code

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#115]
Hello AWS,

When attempting to run my code, the lambda gives an error as following. I could not think of a way to either test it locally or get a detailed error.

I guess the problem is happened when I tried to invoke another Lambda function from within this Lambda function. Is there any settings that need to be set before perform such operation?

Would you mind help me resolve this issue? Thanks in advance.

```
{
  "errorType": "LambdaException",
  "errorMessage": "An error occurred while attempting to execute your code."
}
```

**Comment by PavelSafronov** [comment]
There's no code or project file, so it's impossible to say what's going wrong. Please try to isolate the error case to the smallest reproducible case.

**Comment by MZhoume** [comment]
@PavelSafronov Minimal code repo: https://github.com/MZhoume/DemoFunction

Thanks in advance.

**Comment by PavelSafronov** [comment]
You're missing a reference to AWSSDK.Lambda. Adding one solved the problem. Not sure how the `dotnet` tools ignored that little fact, but there you have it.

**Comment by rolan-liwanag** [comment]
Hi.. I am having the same problem. Here is the error...

{"errorMessage":"An error occurred while attempting to execute your code.","errorType":"LambdaException"}

i followed the example here...
https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html

and i got that error. please help.
