### ISSUE TITLE
Error with ASP.NET 6.0 Web API to Lambda

### ISSUE THREAD

**Issue by speterson-zoll** [aws/aws-lambda-dotnet#1150]
### Describe the bug

When creating an ASP.NET 6.0 Web API app, packaging it and pushing it up to a Lambda function via the console, I get this error when testing:

"errorMessage": "A public method named 'ConfigureProduction' or 'Configure' could not be found in the 'Program' type."

### Expected Behavior

I expected the Lambda to run and return "Hello World" from my Home controller

### Current Behavior

I received this error:

```
{
  "errorType": "TargetInvocationException",
  "errorMessage": "Exception has been thrown by the target of an invocation.",
  "stackTrace": [
    "at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)",
    "at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)",
    "at System.Activator.CreateInstance(Type type)",
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.GetCustomerObject(Type customerType) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 407",
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Init(Action`1 customerLoggingAction) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 122",
    "at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeInitializer.InitializeAsync() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeInitializer.cs:line 46",
    "at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InitializeAsync() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 155"
  ],
  "cause": {
    "errorType": "InvalidOperationException",
    "errorMessage": "A public method named 'ConfigureProduction' or 'Configure' could not be found in the 'Program' type.",
    "stackTrace": [
      "at Microsoft.AspNetCore.Hosting.StartupLoader.FindMethod(Type startupType, String methodName, String environmentName, Type returnType, Boolean required)",
      "at Microsoft.AspNetCore.Hosting.StartupLoader.FindConfigureDelegate(Type startupType, String environmentName)",
      "at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)",
      "at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)",
      "at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()",
      "at Microsoft.Extensions.Hosting.HostBuilder.Build()",
      "at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()",
      "at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor(StartupMode startupMode)",
      "at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor()",
      "at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()",
      "at ZOLL.EphemeralEndpoints.Api.LambdaEntryPoint..ctor()",
      "at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)"
    ]
  }
}
```

### Reproduction Steps

1. Created a new ASP.NET 6.0 Web API application
2. Added a unit test project
3. Added a Home controller with a Get method to return “Hello World”
4. I ran `dotnet lambda package --project-location "MyEndpoints.Api/" --configuration Release --framework net6.0 --output-package "MylEndpoints.zip" --function-architecture arm64`
5. I added `public partial class Program {}` to the bottom of the Program.cs file to allow the unit tests to run
6. Manually created the function in AWS console and uploaded the zip file from step 4 above

Notes:

1. `Program.cs` does not have a class definitition; it is now implicit in the standard template
2. There is no longer a `Startup.cs file`; all functionality in the pre-.NET 6.0 `Startup` Is in `Program`
3. However, `Program` (as created by default) does not have any methods
4. For example, the `Configure` method, formerly placed in `Startup `in older ASP.NET applications, is not in Startup, but the **contents** of that method are in the new, implicit `Program` class

I used the following as the JSON for my Test (via the console), which is a pared down version of the "Amazon API Gateway AWS Proxy" selection:

```
{
  "resource": "/Home",
  "path": "/Home",
  "httpMethod": "GET",
  "isBase64Encoded": true
}
```

My handler is: `MyEndpoints.Api::MyEndpoints.Api.LambdaEntryPoint::FunctionHandlerAsync`

### Possible Solution

It appears that the underlying AWS code is still expecting pre-.NET 6.0 `Program` and `Startup` files.  I say this because the error message `A public method named 'ConfigureProduction' or 'Configure' could not be found in the 'Program' type.`  makes me think the code is still looking for these methods, even though the new project format does NOT have them. 

### Additional Information/Context

Using Rider 2021.3.4 to create and run the project on a MacBook Pro using the default ASP.NET Web API template
.NET Runtime 6.0.4
.NET SDK 6.0.202

### AWS .NET SDK and/or Package version used

**Explicitly installed:**
Amazon.Lambda.AspNetCoreServer 7.1.0
AWSSDK.Extensions.NETCore.Setup 3.7.2

**Implicitly installed:**
Amazon.Lambda.APIGatewayEvents 2.4.0
Amazon.Lambda.ApplicationLoadBalancerEvents 2.1.0
Amazon.Lambda.Core 2.1.0
Amazon.Lambda.Logging.AspNetCore 3.1.0
Amazon.Lambda.Serialization.SystemText.Json 2.2.0
AWSSDK.Core 3.7.6

### Targeted .NET Platform

.NET 6

### Operating System and version

macOS Monterrey version 12.3.1

**Comment by ashishdhingra** [comment]
Hi @speterson-zoll,

Good afternoon.

I'm unsure if you are using the correct templates. The simplified way to create .NET Serverless WebAPI project that uses AWS Lambda is:
- To install the AWS .NET CLI project templates using command `dotnet new -i Amazon.Lambda.Templates`.
- Use `dotnet new serverless.AspNetCoreWebAPI` to create a basic barebones project with tests that includes a sample `ValuesController`. I also configures proper entry point.
- Add controller(s) and define route(s) per your needs in the project.
- Use `dotnet lambda deploy-serverless --configuration Release --framework net6.0 --function-architecture arm64` to deploy the serverless project. This configures CloudFormation template and uses it for deployment.

I used the above steps for deployment, and the WebAPI using API Gateway is working without any issues. In case you are manually creating resources and do not want to go through the `dotnet lambda deploy-serverless` process, then at very minimum you could compare the structure of the project created by `dotnet new serverless.AspNetCoreWebAPI` and use it as a reference for your ASP.NET 6.0 Web API project.

Thanks,
Ashish

**Comment by speterson-zoll** [comment]
Thanks you very much; your worked just fine.   I was able to use the default template for 3.1, but not for 6.0.
