### ISSUE TITLE
Function handler name incorrectly generated in serverless.template when using Amazon.Lambda.Annotations

### ISSUE THREAD

**Issue by PeterKneale** [aws/aws-lambda-dotnet#1155]
### Describe the bug

Function handler name incorrectly generated
Functions in the root of a project generate correctly, functions in folders append the folder name (name space to the assembly name)

### Expected Behavior

A function in the root should generate 
```json
"Handler": "Stores::Stores.FunctionGetStore_Execute_Generated::Execute"
```
A function in the namespace `Stores.Functions`
```json
"Handler": "Stores::Stores.Functions.FunctionGetStore_Execute_Generated::Execute"
```

### Current Behavior

A function in the root generates:
```json
"Handler": "Stores::Stores.FunctionGetStore_Execute_Generated::Execute"
```
A function in the namespace `Stores.Functions` generates:
```json
"Handler": "Stores.Functions::Stores.Functions.FunctionGetStore_Execute_Generated::Execute"
```
Note the assembly name above is now incorrect ^ 

### Reproduction Steps

Generate a new project using the lambda annotations template, move the function from the root of the project into a subfolder, adjust namespaces accordingly and rebuild the project. The assembly name will now be corrupted with the namespace.

```
dotnet new serverless.Annotations --name Bob
```

- Make a folder in src called Functions
- Move Functions.cs into Functions
- Change namespace to Bob.Functions
```
dotnet build
dotnet lambda package
```
Open `serverless.template` and observe:
```json
"Handler": "Bob.Functions::Bob.Functions.Functions_Default_Generated::Default",
```
The assembly name is now incorrect

### Possible Solution

-

### Additional Information/Context

-

### AWS .NET SDK and/or Package version used

<PackageReference Include="Amazon.Lambda.Annotations" Version="0.5.0-preview" />

### Targeted .NET Platform

.net 6

### Operating System and version

windows 10 (Visual Studio + Rider)

**Comment by normj** [comment]
Thanks for reporting the issue. I was able to reproduce and we'll work on getting the issue fixed.

**Comment by PeterKneale** [comment]
@normj tested in `0.5.1-preview` - working nicely
