### ISSUE TITLE
AspNetCoreServer - Binary Data Response: Unable to expand length of this stream beyond its capacity

### ISSUE THREAD

**Issue by ibuchan72390** [aws/aws-lambda-dotnet#118]
So, I've been working with the AspNetCoreServer to host a .NET Core web API via a Lambda function.  Everything has been working all fine and good until I had to start proxy loading file content through S3. At first, I had some issues working with Binary Content until I realized I needed to customize my API Gateway to ensure they're transferred correctly. Right now, I'm able to load most of my files through my Lambda proxy to S3; however, the larger file of the series seems to be causing the following error on response:

```
Unable to expand length of this stream beyond its capacity.: NotSupportedException
at System.IO.UnmanagedMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.Write(String value)
at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Amazon.Lambda.Serialization.Json.JsonSerializer.Serialize[T](T response, Stream responseStream)
at lambda_method(Closure , Stream , Stream , ContextInfo )
```

Now, my assumption here is that somehow the response stream is surpassing the limits allowed by either Lambda or API Gateway.  From my readings, I gather that a Lambda response has a limit of 6 MB from the following link: http://docs.aws.amazon.com/lambda/latest/dg/limits.html

I can specifically tell from the file size of my PDF in S3 that I'm about 5.3 MB.  I've added an extra method to my controller response to do an in-memory evaluation of the file size and it's coming up to about 5.26 MB.  I've noticed that since I've added the binary content types to API Gateway, I'm getting a new line in my CloudWatch logs indicating "Response Base 64 Encoded: True".  Now, it appears that I'm receiving a Base 64 encoded string client-side instead of a direct binary content stream.

From my understanding, Base 64 encoding will increase the size of a given piece of text about 33%, is there any chance that this is causing me to go over the 6 MB limit for the Lambda function?  As such, that might cause the stream overflow exception that I'm receiving?

I'm somewhat at a loss here.  It appears that my client is receiving base 64 encoded strings, but I had assumed that by adding these items to the Binary Content Types in my API Gateway, that I would receive the byte[] instead of the Base 64 encoded version of the byte[].  Or is this Binary Content implementation in API Gateway simply a sugar layer to allow us to work with binary types without manually converting to a Base 64 string in our controller?

**Comment by ibuchan72390** [comment]
So, after a little bit more experimentation, I can definitely confirm that the Base 64 encoded version of the string I'm returning is above the 6MB limit. After adding some logging for the in-memory evaluation of the my return, I then converted it to a Base 64 string, just like I believe API Gateway is doing with Binary array.

    [Information] iAMGlobalAngular2.School.Api.Controllers.FileAccessController: Pre Base 64 File Size:
    [Information] iAMGlobalAngular2.School.Api.Controllers.FileAccessController: 5.26 MB
    [Information] iAMGlobalAngular2.School.Api.Controllers.FileAccessController: Base 64 File Size:
    [Information] iAMGlobalAngular2.School.Api.Controllers.FileAccessController: 7.01 MB

I would think that the API Gateway conversion of this value to a Base 64 string would occur outside of the Lambda context, allowing me to surpass the 6 MB response limit; however, that does not appear to be what's happening here. 

Is my reasoning here along the right lines or am I completely off base?  This is the only thing I could seem to think of, particularly given how close it is to the supposed limit.  Do I even have the Binary Content Types setup correctly in API Gateway if I'm seeing this behavior?

**Comment by PavelSafronov** [comment]
According to the [Amazon API Gateway documentation](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-output-format), binary data has to be sent back as a base64-encoded string.
So what you're seeing is exactly the expected behavior.

**Comment by ibuchan72390** [comment]
Interesting, I thought for sure that the binary stream would have exited the lambda function allowing for the conversion to happen at the API Gateway layer instead of the Lambda layer.  I was hoping this would allow me to negate that encoded string's limit violation.  Thank you very much for the clarification, on where the Base 64 encoding is occurring. I'll try to use the "Private Content Through CloudFront" pattern instead.
