### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly Microsoft.AspNetCore.Diagnostics.Abstractions, Version=6.0.0.0

### ISSUE THREAD

**Issue by starkcolin** [aws/aws-lambda-dotnet#1184]
### Describe the bug

I'm seeing frequent Lambda errors where the assembly Microsoft.AspNetCore.Diagnostics.Abstractions cannot be loaded.  This assembly is part of the ASP.NET Core runtime, so it should always be present.

Using Lambda .NET 6 runtime with ASP.NET Core

### Expected Behavior

Assembly is loaded, no exception is thrown. 

### Current Behavior

Example stacktrace:  

`System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. An internal error occurred.(0x8007054F)
File name: 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'  
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)  
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)  
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited\|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)  
at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)`

### Reproduction Steps

 Not sure exactly what triggers it, but I believe it's related to the exception middleware in ASP.NET Core.

### Possible Solution

Assembly is not present in the Lambda runtime.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer version 7.2.0

### Targeted .NET Platform

.NET 6

### Operating System and version

Lambda

**Comment by ashishdhingra** [comment]
Hi @starkcolin,

Good afternoon.

Thanks for reporting the issue. Would it be possible for you to share the minimal code solution/project to reproduce the issue? I just want to make sure that we have almost the same environment/configuration.

Regards,
Ashish

**Comment by starkcolin** [comment]
Not easily unfortunately.  The code is confidential, and it would take a pretty substantial effort to create a new project and attempt to reproduce it there.  I've provided you with the ZIP file that the Lambda code is running from, with all proprietary code removed.  The packages.lock.json file will also show what the dependencies are.  Not sure how much help that is, so let me know if there's anything else I can provide you.
[LambdaEnvironment.zip](https://github.com/aws/aws-lambda-dotnet/files/8766405/LambdaEnvironment.zip)

**Comment by ashishdhingra** [comment]
> runtime

@starkcolin Thanks for the reply. Could you please share the package references from `.csproj` file? This would make it easier to develop simple Serverless ASP.NET Web API application using the packages in your environment.

**Comment by starkcolin** [comment]
OK I'll try to follow up and get a working repro project, but it will probably take some time.  If the issue stops occurring in the meantime, then I'll report that back as well and close the issue.

**Comment by SamRD2** [comment]
I have this issue also on .NET 6. 
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.17.0" />
    And entity framework latest version don't seem to load.
