### ISSUE TITLE
Access Lambda context object in AWS Serverless Application

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#1187]
### Describe the feature

I can't seem to find any examples of accessing the Lambda Context object for an AWS Serverless Application.

I want to get the awsRequestId for correlating the API call logging.

I did find this article https://stackoverflow.com/questions/72069469/access-ilambdacontext-in-lambda-entrypoint-for-dotnet-serverless-api
which suggests that getting the lambda context is not possible?

### Use Case

The context object has a number of very useful properties for an AWS Serverless Application in dotnet lambda.

The awsRequestId can be used to trace an API call through an application for example.

### Proposed Solution

Allow the override to work to obtain the Context object

     public override async Task<APIGatewayProxyResponse> FunctionHandlerAsync(APIGatewayProxyRequest request, ILambdaContext lambdaContext)
        {
            Context = lambdaContext;
            return await base.FunctionHandlerAsync(request, lambdaContext);
        }

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.1.0

### Targeted .NET Platform

.NET Core 6.0

### Operating System and version

Windows 10 21H2

**Comment by normj** [comment]
I'm confused what you mean about "AWS Serverless Application" in this context. Usually that just means deploying your Lambda functions via CloudFormation but the programming model isn't changed. Are you talking about one of our high level abstractions like the ASP.NET Core bridge library for Lambda or the Lambda Annotations library?

**Comment by genifycom** [comment]
Hi Norm,

No just talking about an "AWS Serverless Application" project type in Visual Studio with a Blueprint of "ASP.NET Core Web App"

In such an App, the FunctionHandlerAsync is not exposed by default. 

If I override it:
`        public override async Task<APIGatewayProxyResponse> FunctionHandlerAsync(APIGatewayProxyRequest request, ILambdaContext lambdaContext)
        {
            LambdaLogger.Log($"INFO::LambdaLogger in FunctionHandlerAsync AwsRequestId:{lambdaContext.AwsRequestId}");
            return await base.FunctionHandlerAsync(request, lambdaContext);
        }
`
then I can see the correct AwsRequestId. But if I store the lambdaContext in a static variable and try and access it in the Init method of the same class, then the lambdaContext has become null.

It seems that the lambdaContext is only available within the FunctionHandlerAsync function but nowhere else.

Is there a way to get to it?

**Comment by genifycom** [comment]
There must be a way since it appears that the LambdaLogger has access to and logs AwsRequestId

**Comment by ashishdhingra** [comment]
@genifycom Thanks for submitting the feature request. Could you please share the sample project to reproduce the scenario mentioned above?

Thanks,
Ashish

**Comment by genifycom** [comment]
public class LambdaEntryPoint : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
{
    protected override void Init(IWebHostBuilder builder)
    {
        //How to get ILambdaContext lambdaContext here?? Need to access the lambdaContext.AwsRequestId to set as correlation id in Serilog

         CreateLogger();

        builder
            .UseSerilog()
            .UseStartup<Startup>();
    }
}
