### ISSUE TITLE
Unable to determine service/operation name to be authorised for GetFunctionUrlConfig in GovCloud regions.

### ISSUE THREAD

**Issue by kcoetzee** [aws/aws-lambda-dotnet#1188]
### Describe the bug

The Lambda Function URL functionality is not yet present in GovCloud regions, so the following error is encountered when Function URL related operations such as (GetFunctionUrlConfig) is called by the Lambda Tools for Powershell Publish-AWSPowerShellLambda command:

"Error creating function url config for function: Unable to determine service/operation name to be authorised".

A new function can be successfully deployed without any issues, however, if the Publish-AWSPowerShellLambda is used on an existing function, it breaks because of the GetFunctionUrlConfig operation.

Since it isn't clear when Function URLS will be deployed to GovCloud regions, is there any fix or work-around which could be suggested?

### Expected Behavior

Function deployed successfully.

### Current Behavior

Error creating function url config for function: Unable to determine service/operation name to be authorised

Exception: C:\Program Files\PowerShell\Modules\AWSLambdaPSCore\3.0.1.0\Private\_DeploymentFunctions.ps1:221
Error publishing PowerShell Lambda Function: -1 CALLSTACK: Command

### Reproduction Steps

1) Deploy a PowerShell Lambda function using the Publish-AWSPowerShellLambda command **in a GovCloud region.**
2) When you run the Publish-AWSPowerShellLambda again, you will encounter the error I have described above (without needing to make any changes to the function itself)

### AWS .NET SDK and/or Package version used

dotnet 6.0.5
powershell 7

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux, Windows 10, WIndows 11

**Comment by ppittle** [comment]
A fix has been deployed as part of [Amazon.Lambda.Tools 5.4.2](https://www.nuget.org/packages/Amazon.Lambda.Tools/5.4.2).

The next time you run `Publish-AWSPowerShellLambda`, the tooling should download the latest version of `Amazon.Labmda.Tools` and work as expected.

**Comment by yobyot** [comment]
Thanks, @ppittle.

Is there a version for M1 Macs yet?

<img width="885" alt="2022-06-06_17-07-22" src="https://user-images.githubusercontent.com/14332263/172249518-2c8f6f00-4da2-402a-9b1f-14cad13119c4.png">

**Comment by normj** [comment]
There is just a single package for any platform including M1 Macs. I wonder since you are in GovCloud if you are using a different feed then NuGet.org, possibly a local feed. You can firm that by executing the `dotnet nuget list source` command. I suspect you have a local folder or private feed that is needs to be manually updated with the version 5.4.2 from NuGet.org.

**Comment by yobyot** [comment]
Thanks.

**Comment by yobyot** [comment]
Well, it was some kind of nasty cache problem. Don't know why but on one of my Macs, 5.4.2 was pulled but on another it wasn't. Same feeds in NuGet.config on both machines.

`dotnet nuget locals all --clear`  along with manually deleting `~/.nuget/packages` took care of it 
<img width="1009" alt="2022-06-06_21-21-23" src="https://user-images.githubusercontent.com/14332263/172275786-bbd05740-768d-41a9-9518-d654bed68c49.png">

I'm all set. 

Thanks again, @normj @ppittle.

**Comment by normj** [comment]
Excellent, glad you got it sorted and apologize for the inconvenience.
