### ISSUE TITLE
Can't invoke a Lambda function that takes an int as a parameter with `dotnet lambda invoke-function`

### ISSUE THREAD

**Issue by bjhogan** [aws/aws-lambda-dotnet#1197]
### Describe the bug

There doesn't seem to be a way to invoke a Lambda function using `dotnet lambda invoke-function` when the parameter to the function is an int. 

Create a new Lambda function - 
```
dotnet new lambda.EmptyFunction --name TakesANumber
```

Change the `FunctionHandler` to  -

```
public string FunctionHandler(int input, ILambdaContext context)
{
    return $"you sent {input}";
}
```

Can't find a way to invoke this function using `dotnet lambda invoke-function --payload ...`

Have tried payloads with a variety of quotes, decimal places, etc. 

### Expected Behavior

Ability to invoke a function with a int payload.

### Current Behavior

Cannot invoke function with an int payload.

### Reproduction Steps

See description.

### AWS .NET SDK and/or Package version used

Amazon Lambda Tools for .NET Core applications (5.4.2)

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Reproducible. Sending just `12` (for example) via AWS Lambda console works.

**Comment by ashishdhingra** [comment]
We need to implement fix similar to one in PR https://github.com/aws/aws-lambda-dotnet/pull/1851.

**Comment by ashishdhingra** [comment]
Fix released in [Amazon.Lambda.Tools 5.11.1](https://www.nuget.org/packages/Amazon.Lambda.Tools/5.11.1)
