### ISSUE TITLE
Ability to deploy a Lambda package via dotnet CLI

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#12]
As of now, we can produce a package by running the command `dotnet lambda package`.
It would be great if we could have `dotnet lambda publish` to deploy the latest package created (either the output of `package` or `deploy-function`).

This is useful in CI/CD setups that don't/can't depend on S3 storage.

The story is:
* developer edits code
* developer commits and pushes changes
* ci-server builds latest version
* ci-server executes tests
* ci-server creates package
* sysadmin deploys latest version

**Comment by normj** [comment]
If deploy-function had an extra parameter taking in a zip file, that would if present. cause deploy-function to skip the build and package step and just use the zip file would that work for you?

I'm hesitant to add a separate "publish" command  because the difference between deploy-function and publish-function will not be obvious to users. Plus I would also have to add publish-serverless as well.

**Comment by Kralizek** [comment]
Oh, that would work just as fine.
The important is the use case =)

**Comment by normj** [comment]
I pushed out version 1.1.0-preview1 version of Amazon.Lambda.Tools package which has a new **--package** for the deploy-function and deploy-serverless commands that will provide this support.

**Comment by derwasp** [comment]
@normj is there a way to get Lambda Tools as a stand alone application? Even though I can use `--package` I still need to start `dotnet lambda` in the directory where I have a `csproj` with Tools installed.
And if I were to split the process into two steps, it would be problematic.

I am using FAKE + Paket and I tried downloading [Amazon.Lambda.Tools](https://www.nuget.org/packages/Amazon.Lambda.Tools) and running `dotnet dotnet-lambda.dll help package` and this is what I got as output:

```
C:\repo\TestApp\packages\build\Amazon.Lambda.Tools\lib\netcoreapp1.0>dotnet dotnet-lambda.dll help package
AWS Lambda Tools for .NET Core functions
Project Home: https://github.com/aws/aws-lambda-dotnet

package:
   Command to package a Lambda project into a zip file ready for deployment

   dotnet lambda package [arguments] [options]
   Arguments:
      <ZIP-FILE> The name of the zip file to package the project into
Unknown error: Could not load file or assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. The system cannot find the file specified.
   at Amazon.Lambda.Tools.LambdaToolsDefaultsReader.LoadDefaults(String projectLocation, String configFile)
   at Amazon.Lambda.Tools.Program.PrintUsage(String command, String description, IList`1 options, String arguments)
   at Amazon.Lambda.Tools.Program.Main(String[] args)
```
