### ISSUE TITLE
AddAWSLambdaHosting for Controller-based API and APIGateway

### ISSUE THREAD

**Issue by ansehh** [aws/aws-lambda-dotnet#1209]
### Describe the bug

I have an existing .NET 6 Project with Program.cs and Startup.cs and the only thing to make it runnable for AWS Lambda was to add         
`services.AddAWSLambdaHosting(LambdaEventSource.RestApi);
`

Deploying it via Terraform and then manually add a Function Url allows me to call my lambdaUrl/health endpoint. Everything is working pretty well. 

But configuring a APIGatway to proxy my URL to my Lambda Endpoint leads to:

`
@message | 2022-06-19T11:25:55.932Z 68ff44b7-6e98-439c-b7a5-6b02847fbd2e fail System.NullReferenceException: Object reference not set to an instance of an object.at Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction.MarshallRequest(InvokeFeatures features, APIGatewayHttpApiV2ProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass26_0`2.<<GetHandlerWrapper>b__0>d.MoveNext()--- End of stack trace from previous location ---at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)
-- | --
`

What I need to configure to reach my endpoint from API Gateway?

### Expected Behavior

Receiving my response after calling the {proxy+} endpoint of my API.

### Current Behavior

@message | 2022-06-19T11:25:55.932Z 68ff44b7-6e98-439c-b7a5-6b02847fbd2e fail System.NullReferenceException: Object reference not set to an instance of an object.at Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction.MarshallRequest(InvokeFeatures features, APIGatewayHttpApiV2ProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass26_0`2.<<GetHandlerWrapper>b__0>d.MoveNext()--- End of stack trace from previous location ---at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)
-- | --

### Reproduction Steps

Creating a normal .NET 6 WebApi Project and         services.AddAWSLambdaHosting(LambdaEventSource.RestApi);
 to ConfigureServices of Startup and deploy it to Lambda.

### AWS .NET SDK and/or Package version used

.NET 6
 Assembly Amazon.Lambda.AspNetCoreServer, Version=2.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604

### Targeted .NET Platform

.NET6

### Operating System and version

Lambda

**Comment by ashishdhingra** [comment]
Hi @ansehh,

Good morning.

Could you please confirm if you are trying to point API Gateway to Lambda function URLs? I'm unsure if it is possible since both are separate implementations for exposing Lambda function. 

Few helpful articles below:
- [AWS Lambda Function URLs vs. Amazon API Gateway](https://www.serverlessguru.com/blog/aws-lambda-function-urls-vs-amazon-api-gateway)
- [AWS Lambda Function URL vs API Gateway – When to Use What](https://beabetterdev.com/2022/04/06/aws-lambda-function-url-vs-api-gateway-when-to-use-what/)

Thanks,
Ashish

**Comment by ansehh** [comment]
Hey @ashishdhingra,

no I am not pointing to the Function URL. I try to not use function url because I want to use my own domain later on for the lambda. https://api.xxxx.

I am pointing to the Entry Point of the Lambda:
<img width="730" alt="Bildschirmfoto 2022-06-21 um 10 23 28" src="https://user-images.githubusercontent.com/93390946/174753054-714f9fd2-3d2f-4753-a3a2-59ba7cb46064.png">

Handler is configured like this:
<img width="1033" alt="Bildschirmfoto 2022-06-21 um 10 25 15" src="https://user-images.githubusercontent.com/93390946/174753347-1fac7559-c457-48cc-b3a7-791df23e4de0.png">

<img width="846" alt="Bildschirmfoto 2022-06-21 um 10 27 49" src="https://user-images.githubusercontent.com/93390946/174753978-fdb7ca55-34b7-4281-85c5-189bce6a9d75.png">

Proxy integration true or false makes no difference.

**Comment by ansehh** [comment]
My issue was to explicit set the memory two more than 128 MB in my terraform code obviously... :/
Everything is working now as expected.
