### ISSUE TITLE
dotnet lambda deploy-serverless on Debian Jessie produces a non working function

### ISSUE THREAD

**Issue by derwasp** [aws/aws-lambda-dotnet#121]
It sounds like madness, but after 3 days of fighting I am more than sure that it's the case.

So, I have an application, which I am trying to put in a Lambda function using `Amazon.Lambda.AspNetCoreServer` and `dotnet lambda` tooling.

When the application is built on Windows or OSX, everything works like charm.
But my Jenkins docker slaves are based on Debian. Everything builds fine and when I try to access my function I receive a 500-ish error saying that something bad happened.

And this is what I see in logs:
`Unable to load assembly 'MyVeryAwesome.Api, Culture=neutral, PublicKeyToken=null'.: LambdaException`

Here is a CloudWatch screenshot:

![image](https://cloud.githubusercontent.com/assets/10754345/26249955/b76d63d6-3ca8-11e7-94c1-cfa23abb7526.png)

I was comparing archive's contents from different environments to find why it doesn't work. Some dlls were of different versions and that made me thinking it's .NET Core's fault. And there is something definitely wrong with it, but it was not the cause of the problem.

So, what was it?
When I was about to give up and go back to my ECS/EC2 solution I tried getting the archive from s3, unzip it and zip it back. Simple as that, no changes, just unzip and zip back.
I was shocked when it worked.
Then I added a bodge into my CI which unzips the package, zips it back and then uses deploy-serverless with  `--package` option.
And it worked again.

But something tells me that it was not intended to work this way ;)

**Comment by PaulColeman** [comment]
Does this help?

https://github.com/aws/aws-lambda-dotnet/issues/113

**Comment by derwasp** [comment]
@PaulColeman I swear I googled for it. It is indeed the same issue, thank you.

What I don't understand though is why FAKE's [zip helper](http://fsharp.github.io/FAKE/apidocs/fake-ziphelper.html) zips the file with no issues.

**Comment by derwasp** [comment]
Since I can not "uncreate" my issue, I will just continue asking here ;)

@normj I read your reply to @PaulColeman, but I didn't understand the reasoning behind the necessity of calling the zip utility, can you please elaborate on that?
Since Lambda is running on Linux already, when I am publishing my stuff from Windows, I don't have any permissions. Why should I maintain them when I am publishing from Linux?

**Comment by PaulColeman** [comment]
@derwasp Next time Bing it. ;-)

**Comment by normj** [comment]
I believe what happens, but I won't claim to be an expert of zip archives, on Windows the .NET compression libraries pick up a default Linux file permissions since Windows doesn't support Linux file permissions. On Linux the .NET compression libraries don't pick up any of the file permissions so they lose their read permission.


I have checked (https://github.com/aws/aws-lambda-dotnet/commit/7f9117485e535976ee1766e2514d9c1b8835cd40) in a fix to the tooling that will go out with the next version. With this fix you will get a proper error message when running on Linux and the tooling can't find the zip utility. This will go out with the next version of the tooling. Sorry about the difficulties discovering the issue.

**Comment by derwasp** [comment]
@normj but what I done to "fix" the issue was repacking it on the same machine. I just used FAKE script to unpack and repack the files. Do you think it uses some magic to make it work?

**Comment by derwasp** [comment]
I can see that it uses `ICSharpCode.SharpZipLib` and not the standard .net compression library. Maybe that is why it works.

**Comment by derwasp** [comment]
I've tested .NET Core's zip file using the code from Lambda Tools.. And after `unzip archive.zip -d destination_folder` files have no permissions at all.

![image](https://cloud.githubusercontent.com/assets/10754345/26264122/fde5edfa-3cdb-11e7-8c47-825dbb642bf9.png)

**Comment by derwasp** [comment]
Looks like it's related to this:
https://github.com/dotnet/corefx/pull/18565

**Comment by normj** [comment]
Good find on the GitHub pull request. Good to see this issue is being resolved in the future.

**Comment by derwasp** [comment]
@normj sorry for spamming you with messages.
You can close this issue if you feel like it. Or you can keep it so the code can be changed once .NET Core guys have fixed that.
Thank you!

**Comment by normj** [comment]
I'm going to close it for now. It will be while before we can make that change.
