### ISSUE TITLE
Can You Use Lambda Annotations,  Top-Level, APIGatewayHttpApiV2ProxyRequest and MapControllers all together?

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-lambda-dotnet#1224]
### Describe the issue

EDIT: Clarification:  Attempting to not use Minimal APIs - have oodles of controllers already properly decorated and working.

I am trying to convert an AWS Lambda AspNet .net50 app to the newer style .net60 top level.

I understand that I need to use `builder.Services.AddAWSLambdaHosting(LambdaEventSource.HttpApi);`

and I have my top-level program running (and it has MapControllers).

But, how do I specify to find and use my legacy function with the APIGatewayHttpApiV2ProxyRequest parameter?

Because I am using top level, I need to specify only the assembly name in the handler (which, if I am correct, negates the possibility of using the `[LambdaFunction]` attribute, correct?).

I can't find any documentation on to combine all these.

Or do I need to go thru all my controllers and decorate them with `[HttpApi]` attribute?  (Ugh)...  And then if I do that, am I really using ASPNET anymore, or is it all aws lambda magic and I've thrown out ASPnet?

Sorry, confused....?

### Links

https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/

**Comment by hounddog22030** [comment]
So, a little experimenting yields that you must "handcode" the function into the template as below and then everything just works, not using the legacy function with the APIGatewayHttpApiV2ProxyRequest parameter?

```
    "AspNet": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "BubbleBoy.WebApi",
        "Runtime": "dotnet6",
        "MemorySize": 10240,
        "Timeout": 30,
        "Role": {
          "Ref": "LambdaExecutionRole"
        },
        "Events": {
          "ProxyResource": {
            "Type": "HttpApi",
            "Properties": {
              "Path": "/{proxy+}",
              "Method": "ANY"
            }
          },
          "RootResource": {
            "Type": "HttpApi",
            "Properties": {
              "Path": "/",
              "Method": "ANY"
            }
          }
        }
      }
    }
```

**Comment by ashishdhingra** [comment]
@hounddog22030 Also refer https://github.com/aws/aws-lambda-dotnet/discussions/1195#discussioncomment-2961622 to see if that helps.

**Comment by hounddog22030** [comment]
> * Is AddAWSLambdaHosting only for minimal API or it will also work with AP IWith controllers #1152 (comment)

That definitely helps, thanx.

**Comment by ashishdhingra** [comment]
@hounddog22030 Please confirm if we could close this issue.

**Comment by hounddog22030** [comment]
> @hounddog22030 Please confirm if we could close this issue.

Yes.  Thank you.  I could use some help on here, though:  https://github.com/aws/aws-extensions-for-dotnet-cli/discussions/222

Thanks.
