### ISSUE TITLE
S3 EventName is being returned as an object instead of a string

### ISSUE THREAD

**Issue by jcstorms1** [aws/aws-lambda-dotnet#1226]
### Describe the bug

When using the `S3Event` in my handler function, I expected the EventName attribute to be a string. Instead, the returned attribute is an object of `"EventName": { "Value": "ObjectCreated:Put" }`. This leads to a failure  when trying to unmarshall the payload into the GO equivalent of the S3 event in an extension.

### Expected Behavior

As described in the docs [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html), I would expect the `EventName` attribute to return a string. This is the behavior shown for GO, as described in the example S3 event [here](https://github.com/aws/aws-lambda-go/blob/main/events/s3.go).

### Current Behavior

Current behavior is that an object is returned instead of a string, as described above. This does not align with docs and other examples for different runtimes.

### Reproduction Steps

I used a modified AWS provided example
```
        public object HandlerS3Event(S3Event s3Event, ILambdaContext context)
        {
            foreach (var record in s3Event.Records)
            {
                var s3 = record.S3;
                Console.WriteLine($"[{record.EventSource} - {record.EventTime}] Bucket = {s3.Bucket.Name}, Key = {s3.Object.Key}");
            }
            return new { statusCode = 200, body = "ok!" };
        }
```

### AWS .NET SDK and/or Package version used

Amazon.Lambda.S3Events 2.0.1

### Targeted .NET Platform

.NET Core 3.1

### Operating System and version

Big Sur

**Comment by normj** [comment]
I do agree I wish we wouldn't have made the Lambda S3 event object extend from a type in the SDK. It puts an unnecessary dependency to the `AWSSDK.S3` package for users that want a simple type. I would be open to a PR that removes the dependency on the SDK and then do a major version bump of the package.

**Comment by jcstorms1** [comment]
Hey @normj thanks for the response. I'd like to know if you have any suggestion on what this change would entail? Would you be able to provide some more details on how to approach this change?

**Comment by normj** [comment]
@jcstorms1 Basically take the SDK code from [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Util/S3EventNotification.cs). Remove the JSON parsing logic and replace uses of `ConstantClass` to string and make sure the existing S3 event parsing tests in the repo pass.

**Comment by ashishdhingra** [comment]
@jcstorms1 Would you be willing to contribute a PR to fix this issue?

**Comment by jcstorms1** [comment]
Hey @ashishdhingra  sorry for the delay. Just opened the PR above.

**Comment by ashishdhingra** [comment]
[Amazon.Lambda.S3Events version 3.0.0](https://www.nuget.org/packages/Amazon.Lambda.S3Events/3.0.0) as part of PR https://github.com/aws/aws-lambda-dotnet/pull/1237.
