### ISSUE TITLE
Unhandled exceptions which contain non ASCII characters in the exception message cause a Runtime.ExitError

### ISSUE THREAD

**Issue by JonOJet** [aws/aws-lambda-dotnet#1231]
### Describe the bug

When a .Net 6 Lambda Function that is deployed to the AWS Lambda environment (this issue does not present itself when the Lambda is invoked locally) throws an unhandled exception that contains a non-ascii character (E.g. •), the Lambda terminates with a Error: Runtime exited with error: signal: aborted Runtime.ExitError.

An example of where this causes a problem is when the Lambda Function is part of a Step Function as the thrown exception is no longer passed back to the Step Function state machine but the Runtime.ExitError is instead. 

### Expected Behavior

The original unhandled exception which contains non ASCII characters is handled by the Lambda Function execution runtime and returned to the caller.

### Current Behavior

An additional unhandled exception is thrown in the Lambda runtime when handling the original exception. Looking in the related Cloudwatch logs, it looks like an exception is being thrown due to a headers value containing non ASCII characters:
_Unhandled exception. System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters._

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-ca8955d7-7fff-8c21-90a9-1b97c34a7fd0"><div dir="ltr" style="margin-left:0pt;" align="left">

2022-06-30T09:26:51.384+01:00 | at Worker.LambdaHandlers.RunCommand[TOutput,TModel](ILambdaContext context, StepInput`1 model, Func`2 command, Action`1 preExecuteAction) in /app/src/Worker/LambdaHandlers.cs:line 245
-- | --
2022-06-30T09:26:51.384+01:00 | at Worker.LambdaHandlers.ValidateMenuWithMenuCards(StepInput`1 model, ILambdaContext lambdaContext) in /app/src/Worker/LambdaHandlers.cs:line 73
2022-06-30T09:26:51.384+01:00 | at lambda_method1(Closure , Stream , ILambdaContext , Stream )
2022-06-30T09:26:51.384+01:00 | at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
2022-06-30T09:26:51.384+01:00 | at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 56
2022-06-30T09:26:51.384+01:00 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176
2022-06-30T09:26:51.480+01:00 | Unhandled exception. System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, Encoding encoding)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer, Boolean async)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-06-30T09:26:51.480+01:00 | at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2022-06-30T09:26:51.480+01:00 | at Amazon.Lambda.RuntimeSupport.InternalRuntimeApiClient.ErrorWithXRayCauseAsync(String awsRequestId, String lambda_Runtime_Function_Error_Type, String errorJson, String xrayCause, CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/InternalClientAdapted.cs:line 496
2022-06-30T09:26:51.480+01:00 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 182
2022-06-30T09:26:51.480+01:00 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.RunAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 137
2022-06-30T09:26:51.480+01:00 | at Amazon.Lambda.RuntimeSupport.RuntimeSupportInitializer.RunLambdaBootstrap() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/RuntimeSupportInitializer.cs:line 49
2022-06-30T09:26:51.480+01:00 | at Amazon.Lambda.RuntimeSupport.Program.Main(String[] args) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Program.cs:line 19
2022-06-30T09:26:51.480+01:00 | at Amazon.Lambda.RuntimeSupport.Program.<Main>(String[] args)

</div></b>
</body>
</html>

### Reproduction Steps

1. Create a .Net 6 Lambda Function which throws an unhandled exception that contains a non ASCII character in the exception message.
2. Deploy the Lambda to the AWS Platform.
3. Invoke the Lambda.
4. Review the Cloudwatch logs for the Lambda Functions invocation and see that a Runtime.ExitError occurred due to an unhandled System.Net.Http.HttpRequestException. 

### Additional Information/Context

This only happens when executing the Lambda Function on the AWS platform. When run locally using the Mock Lambda Test Tool, the unhandled System.Net.Http.HttpRequestException is not thrown 

### AWS .NET SDK and/or Package version used

Amazon.Lambda.RuntimeSupport 1.8.2

### Targeted .NET Platform

.Net 6

### Operating System and version

Lambda Runtime: .NET 6 (C#/PowerShell)

**Comment by ashishdhingra** [comment]
@JonOJet Thanks for opening the bug report. Could you please share the below information:
- Although quite obvious from the issue reproduction steps, please share the sample code to reproduce the issue.
- Also advise on why the unhandled exception should not be logged in the CloudWatch logs.
- Do you see different behavior when using ASCII characters in exception message?
- In Lambda Test Tool, did you check the output text area for any unhandled exceptions? Or if logging these exceptions using LoggerContext, did you check the CloudWatch logs for the configured local IAM account?

Thanks,
Ashish

**Comment by JonOJet** [comment]
Hi @ashishdhingra 

Hopefully this answers your questions 😄 

- Although quite obvious from the issue reproduction steps, please share the sample code to reproduce the issue.

If you create a Lambda function which contains the following code, it will reproduce the issue when the Lambda is executed on the AWS Platform:
`throw new Exception("Unhandled exception with non ASCII character: •");`

- Also advise on why the unhandled exception should not be logged in the CloudWatch logs.

It is fine for the unhandled exception to be logged in the CloudWatch logs - I only included the CloudWatch logs as they showed what was actually going on to explain why a Runtime.ExitError was being returned instead of the original unhandled exception due to another unhandled exception occurring in Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync

- Do you see different behaviour when using ASCII characters in exception message?

When using ACSII characters in the exception message, the thrown unhandled exception is returned to the caller. This is what I would expect to happen as a Runtime.ExitError does not occur.

- In Lambda Test Tool, did you check the output text area for any unhandled exceptions? Or if logging these exceptions using LoggerContext, did you check the CloudWatch logs for the configured local IAM account?

When using the Lambda Test Tool, the unhandled exception which contains the non ASCII character is returned in the response. Looking in the Log Output box, I can see the Unhandled exception. The "System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.” error does not occur so I am assuming this error is occurring due to the Lambda runtime environment on the AWS Platform.
Looking at the output from the Mock Lambda Test Tool, it is using Amazon.Lambda.TestTool.Runtime.LambdaExecutor.ExecuteAsync to execute the Lambda. Whereas on the AWS Platform, it is Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync that is executing the Lambda. I expect there is a difference between these two ways of executing the Lambda code and handling thrown exceptions which results in the difference of behaviour when handling exceptions with non ASCII characters in the exception message.

**Comment by ashishdhingra** [comment]
Need to reproduce it in different SDK (Java or JavaScript). May be the error is thrown at the Lambda platform level.

**Comment by ashishdhingra** [comment]
@JonOJet I tried reproducing the issue with the code below:
```C#
using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace Project.Lambda;

public class Function
{
    
    /// <summary>
    /// A simple function that takes a string and does a ToUpper
    /// </summary>
    /// <param name="input"></param>
    /// <param name="context"></param>
    /// <returns></returns>
    public string FunctionHandler(string input, ILambdaContext context)
    {
        throw new Exception("Unhandled exception with non ASCII character: ♂");
    }
}
```

It does log the error `Runtime.ExitError`. However, it also logs the original exception (see `fail System.Exception: Unhandled exception with non ASCII character: ♂`:
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                           message                                                                                                                                                           |
|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1657737228994 | START RequestId: 28731217-0d5e-4fbb-978c-b612932a3a25 Version: $LATEST                                                                                                                                                                                                                                                      |
| 1657737229365 | 2022-07-13T18:33:49.305Z 28731217-0d5e-4fbb-978c-b612932a3a25 fail System.Exception: Unhandled exception with non ASCII character: ♂                                                                                                                                                                                        |
| 1657737229365 | at Project.Lambda.Function.FunctionHandler(String input, ILambdaContext context) in D:\source\repros\TestLambdaNet6\TestLambdaNet6\Function.cs:line 21                                                                                                                                                                      |
| 1657737229365 | at lambda_method1(Closure , Stream , ILambdaContext , Stream )                                                                                                                                                                                                                                                              |
| 1657737229365 | at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145                                                                                             |
| 1657737229365 | at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 56                                                                                                       |
| 1657737229365 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176                                                                                                                          |
| 1657737229545 | Unhandled exception. System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.                                                                                                                                                                                                              |
| 1657737229545 | at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async)                                                                                                                                                                                                                                                 |
| 1657737229545 | at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, Encoding encoding)                                                                                                                                                                                                                              |
| 1657737229545 | at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer, Boolean async)                                                                                                                                                                                                        |
| 1657737229545 | at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)                                                                                                                                                                                             |
| 1657737229545 | at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)                                                                                                                                                                                             |
| 1657737229545 | at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)                                                                                                                                          |
| 1657737229545 | at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)                                                                                                                                                                                                |
| 1657737229545 | at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)                                                          |
| 1657737229545 | at Amazon.Lambda.RuntimeSupport.InternalRuntimeApiClient.ErrorWithXRayCauseAsync(String awsRequestId, String lambda_Runtime_Function_Error_Type, String errorJson, String xrayCause, CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/InternalClientAdapted.cs:line 496  |
| 1657737229545 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 182                                                                                                                          |
| 1657737229545 | at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.RunAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 137                                                                                                                                 |
| 1657737229545 | at Amazon.Lambda.RuntimeSupport.RuntimeSupportInitializer.RunLambdaBootstrap() in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/RuntimeSupportInitializer.cs:line 49                                                                                                                                                 |
| 1657737229545 | at Amazon.Lambda.RuntimeSupport.Program.Main(String[] args) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Program.cs:line 19                                                                                                                                                                                      |
| 1657737229545 | at Amazon.Lambda.RuntimeSupport.Program.<Main>(String[] args)                                                                                                                                                                                                                                                               |
| 1657737229767 | END RequestId: 28731217-0d5e-4fbb-978c-b612932a3a25                                                                                                                                                                                                                                                                         |
| 1657737229767 | REPORT RequestId: 28731217-0d5e-4fbb-978c-b612932a3a25 Duration: 770.43 ms Billed Duration: 771 ms Memory Size: 256 MB Max Memory Used: 80 MB Init Duration: 224.85 ms                                                                                                                                                      |
| 1657737229767 | RequestId: 28731217-0d5e-4fbb-978c-b612932a3a25 Error: Runtime exited with error: signal: aborted Runtime.ExitError                                                                                                                                                                                                         |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
"

```

Please recheck if the original exception is reported in your CloudWatch logs.

**Comparison with Node.js**
`Node.js 16.x` lambda with the following code reports the custom error, may be the request pipeline is different than .NET:
```JavaScript
exports.handler = async (event) => {
    // TODO implement
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    
    throw new Error("Unhandled exception with non ASCII character: ♂");
    return response;
};
```
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                                                                                  message                                                                                                                                                                                   |
|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1657737898328 | START RequestId: b5b86351-ecc5-4086-9b9a-72aacd9636ad Version: $LATEST                                                                                                                                                                                                                                                                                                     |
| 1657737898336 | 2022-07-13T18:44:58.336Z b5b86351-ecc5-4086-9b9a-72aacd9636ad ERROR Invoke Error  {"errorType":"Error","errorMessage":"Unhandled exception with non ASCII character: ♂","stack":["Error: Unhandled exception with non ASCII character: ♂","    at Runtime.exports.handler (/var/task/index.js:8:11)","    at Runtime.handleOnce (file:///var/runtime/index.mjs:548:29)"]}  |
| 1657737898359 | END RequestId: b5b86351-ecc5-4086-9b9a-72aacd9636ad                                                                                                                                                                                                                                                                                                                        |
| 1657737898359 | REPORT RequestId: b5b86351-ecc5-4086-9b9a-72aacd9636ad Duration: 28.93 ms Billed Duration: 29 ms Memory Size: 128 MB Max Memory Used: 56 MB Init Duration: 149.56 ms                                                                                                                                                                                                       |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by JonOJet** [comment]
Hi @ashishdhingra

That is correct, the original exception which contains the non-ASCII character is logged to the Cloudwatch logs. 

However, the problem is that the Runtime.ExitError exception is returned to the caller instead of the original exception that contains the non-ASCII character. 

Looking at the stack trace in your logs, a second exception is thrown when handling the exception which contains a non-ASCII character that results in the Runtime.ExitError error.
`1657737229545 | Unhandled exception. System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.  `

This is a specific issue when the Lambda is used as a step in an AWS Step Function as the Runtime.ExitError is returned to the Step Function instead of the original exception which was thrown that contains a non-ASCII character.

This did not happen when using .netcore 3.1. The original exception which contain the non-ASCII character was returned to the Step Function and could be processed via our error handling flow.

**Comment by ashishdhingra** [comment]
Possible fix could be:
- Either HtmlEncode the error cause string used while calling `request_.Headers.Add("Lambda-Runtime-Function-XRay-Error-Cause", xrayCause);` so as to convert convert non-ASCII character to HTML entity https://github.com/aws/aws-lambda-dotnet/blob/882299b606e0f54df463e95177a8e9b4837bbe85/Libraries/src/Amazon.Lambda.RuntimeSupport/Client/InternalClientAdapted.cs#L475 to either, 
OR, 
- Modify [LambdaBootstrap.ConstructHttpClient()](https://github.com/aws/aws-lambda-dotnet/blob/882299b606e0f54df463e95177a8e9b4837bbe85/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs#L225) to initialize `HttpClient` with UTF8 `HeaderEncodingSelector` in SocketsHttpHandler as proposed in https://github.com/dotnet/runtime/issues/38711 (this only works for .NET 5 or later per https://github.com/dotnet/docs/pull/21197).
```C#
if NET6_0_OR_GREATER
            // Create the SocketsHttpHandler directly to avoid spending cold start time creating the wrapper HttpClientHandler
            var handler = new SocketsHttpHandler
            {
                RequestHeaderEncodingSelector = delegate { return System.Text.Encoding.UTF8; }
            };

...
...
            var client = new HttpClient(handler);
#else
```

**Comment by normj** [comment]
Version of 1.8.8 of Amazon.Lambda.RuntimeSupport has been released with the fix. If your functions are deployed as executable, for example using top level statements, then update to the latest version of Amazon.Lambda.RuntimeSupport. If you function is deployed as a class library you will have to wait till the managed runtime is updated with the latest version of Amazon.Lambda.RuntimeSupport.

**Comment by JonOJet** [comment]
Thanks @normj 😄

**Comment by ashishdhingra** [comment]
This should be fixed now with latest managed runtime containing the version `1.8.8` of `Amazon.Lambda.RuntimeSupport`.
