### ISSUE TITLE
Amazon.SimpleNotificationService.Util Message.MessageText is misspelled and incompatible with AWS SDK for .NET

### ISSUE THREAD

**Issue by xfree123** [aws/aws-lambda-dotnet#1256]
### Describe the bug

I'm using Amazon.SimpleNotificationService.Util.Message .NET AWSSDK.CORE and AWSSDK.SimpleNotificationService in HTTP/HTTPs subription Endpoit solutions.  In SimpleNotificationService.Message class is spelled  MessageText see [Message.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs) but the data send from Amazone SNS called "message". 

### Expected Behavior

This causes the Message class to fail when ingesting a message produced by this library.

### Current Behavior

1

### Reproduction Steps

To reproduce:
Create a new .NET MVC APi (.net Framework). Reference AWSSDK.Core and AWSSDK.SimpleNotificationService.

Add SNS controller:
```

public class SNSController : ApiController
    {
        private static string className = MethodBase.GetCurrentMethod().DeclaringType.Name;
        public readonly Logger logger = NLog.LogManager.GetCurrentClassLogger();
        [HttpPost]
        public HttpResponseMessage Post(string id = "")
        {
            try
            {
                var jsonData = Request.Content.ReadAsStringAsync().Result;
                var sm = Amazon.SimpleNotificationService.Util.Message.ParseMessage(jsonData);
                logger.Debug(jsonData);
                logger.Debug(sm);
                if (sm.IsSubscriptionType)
                {
                    sm.SubscribeToTopic();
                }
                if (sm.IsNotificationType)
                {
                    logger.Info("Message received from SNS:" + sm.TopicArn);
                    dynamic message = JsonConvert.DeserializeObject(sm.MessageText);
                    logger.Info("EventTime : " + message.detail.eventTime);
                    logger.Info("EventName : " + message.detail.eventName);
                    logger.Info("RequestParams : " + message.detail.requestParameters);
                    logger.Info("ResponseParams : " + message.detail.responseElements);
                    logger.Info("RequestID : " + message.detail.requestID);
                    
                }
          
                return Request.CreateResponse(HttpStatusCode.OK, new { });
            }
            catch (Exception ex)
            {
                logger.Fatal(ex); ;
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new { status = "unexpected error" });
            }
        }
    }
```
The above line throws:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference at CallSite.Target(Closure , CallSite , Object )
   at AWSSNS3.Controllers.SNSController.Post(String id)

On line: dynamic message = JsonConvert.DeserializeObject(sm.MessageText);
```

Because the body json like this:

```
{
  "Type" : "Notification",
  "MessageId" : "da41e39f-ea4d-435a-b922-c6aae3915ebe",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Subject" : "test",
  "Message" : "test message",
  "Timestamp" : "2012-04-25T21:49:25.719Z",
  "SignatureVersion" : "1",
  "Signature" : "EXAMPLElDMXvB8r9R83tGoNn0ecwd5UjllzsvSvbItzfaMpN2nk5HVSw7XnOn/49IkxDKz8YrlH2qJXj2iZB0Zo2O71c4qQk1fMUDi3LGpij7RCW7AW9vYYsSqIKRnFS94ilu7NFhUzLiieYr4BKHpdTmdD6c0esKEYBpabxDSc=",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem",
   "UnsubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-2:123456789012:MyTopic:2bcfbf39-05c3-41de-beaa-fcfcc21c8f55"
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleNotificationService, Version=3.7.3.86

### Targeted .NET Platform

NET Framework 4.x

### Operating System and version

Windows

**Comment by ashishdhingra** [comment]
Hi @xfree123,

Good morning.

As I understand, you are trying to use [Amazon.SimpleNotificationService.Util.Message](https://github.com/aws/aws-sdk-net/blob/5f988602d1c847a5c229ed69bf8070f2a6d051ef/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L21) to handle the incoming SNS message. Since the `MessageText` is exposed on the public interface, changing it's name could be a breaking change.

Kindly advise on how you receive this JSON on the POST action on your API controller. For Lambda event integration, we have [Amazon.Lambda.SNSEvents](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.SNSEvents) package which has the customized `Message` class per the structure of Lambda event.

Thanks,
Ashish
