### ISSUE TITLE
Issue with unhandled exception message been multilined

### ISSUE THREAD

**Issue by svoychik** [aws/aws-lambda-dotnet#1265]
### Describe the bug

As a result of unhandled exceptions, logs are written into Cloudwatch in multiline format. 
https://github.com/aws/aws-lambda-dotnet/pull/1165 - previous attempt to fix the issue didn't help so this probably has to be double-checked 

For us, this issue causes quite a lot of garbage logs, which distracts attention from really important things 

### Expected Behavior

The exception message is stored as a single CloudWatch row. That's how it worked before on .NET 3.1

### Current Behavior

Currently, exception logs are multilined, see screenshot
![image](https://user-images.githubusercontent.com/7015817/182610793-fcb5a129-52fc-47e5-9780-0631692ed1af.png)

### Reproduction Steps

You need to use lambda with .NET 6 AWS-supported runtime. 
Then make that lambda fail -  Throw any exception from lambda `ExecuteAsync` method and open CloudWatch logs to see the multilined exception logs 

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.1.0
Amazon.Lambda.Serialization.Json 2.0.0
Amazon.Lambda.APIGatewayEvents 2.4.1
Amazon.Lambda.Logging.AspNetCore 3.1.0
AWSSDK.CloudWatch 3.7.4.25
AWSSDK.DynamoDBv2 3.7.3.50
AWSSDK.StepFunctions 3.7.0.174

### Targeted .NET Platform

.NET 6

### Operating System and version

.NET 6 runtime

**Comment by normj** [comment]
Hi @svoychik 

I pinged the Lambda team on the status of the deployment and they have been doing a lot of internal changes to how their runtime deployments. The side effect is the change made to the .NET runtime client hasn't been deployed yet to the managed runtime. Sorry for the delay.

**Comment by svoychik** [comment]
Hi @normj 
Thanks for the response.
Is there a place where I can track the latest updates to the .NET runtime in terms of the version of packages to not spend a lot of time trying to understand whether the Lambda team released the fix or not?

Also, considering the speed of delivery (more than 3 months), it looks like a big reason to think about whether we really want to use custom runtime or the one provided by AWS 🤔.  
I'd like to know the Lambda team's vision on the processes. Are such long delays still going to happen?

**Comment by DillonN** [comment]
Seeing the same issue on .NET 6 still. We did manage to find a workaround, but it's not that pretty. Basically implement a quick custom `ILogger` implementation that logs to `Console.Out`, but replaces all `\n` characters with `\r`. CloudWatch seems to pick up on the carriage return as an internal line break and formats the messages as expected.

**Comment by BenjaRav** [comment]
@ashishdhingra I see this is marked as queued now. Is it possible to have an estimate for how long tasks like this usually resides in a queued state, before being started? I'm contemplating continuing to try to implement the fix Dillon suggested here, but i feel it will be wasted if a internal fix from AWS is around the corner.

**Comment by BenjaRav** [comment]
Any updates on this?

**Comment by ashishdhingra** [comment]
The changes are pushed, closing this issue. Feel free to open a new one in case of any issue.

**Comment by SaaimaMulla** [comment]
> > May I know which release is this fix part of. I have updated all the NuGet packages for AWS but hasn't fix this for me. @ashishdhingra
> 
> @SaaimaMulla Per [#1265 (comment)](https://github.com/aws/aws-lambda-dotnet/issues/1265#issuecomment-1204134370), it's the Lambda runtime fix/change. Please advise:
> 
> * How you are deploying your Lambda. Are you deploying it as a container.
> * What region are you using for deployment?
> 
> Thanks, Ashish

Yes it is deployed in containers for region Europe-Ireland

**Comment by niels-foreflight** [comment]
I don't know who to tag, since the last tag to @ashishdhingra didn't get replied. So i'm tagging @normj as well.

We are also still experiencing this issue with unhandled exceptions being printed as multiline. 
Our Lambdas s running in us-east-1. As docker containers using the newest base image from public.ecr.aws/lambda/dotnet:6, but the issue still persist.

**Comment by normj** [comment]
@niels-foreflight It is a limitation with the running functions as a container image that exceptions get written out as multiline. Basically in containers Lambda is capturing stdout from the container to send CloudWatch Logs and with that there is no way to know the end of a log message other then making the assumption on newlines. The fix we did before only affected when deploying as a zip file.

**Comment by pjmvp** [comment]
On ECS one can [configure the AWS log driver](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html) with `awslogs-multiline-pattern`.

Any way something similar can be achieved with Lambda running functions as a container image?

**Comment by pjmvp** [comment]
@normj , any plans on making it possible to have these logs w/ exceptions in a single log entry, similar to what one does with ECS?
Or are there any workarounds you'd recommend?
Thank you.
