### ISSUE TITLE
web.config file is missing

### ISSUE THREAD

**Issue by petro2050** [aws/aws-lambda-dotnet#1299]
When I create a web api project, the `readme.md` file has a line under `Project Files` which reads

`web.config - used for local development.`

However, this file is not created.

**Comment by normj** [comment]
Transferred to the .NET repo where the blueprints live.

**Comment by peterrsongg** [comment]
Hello @petro2050 this has been addressed in 2022-11-16's release. It was a typo. Closing the comment since the change has been merged in.
