### ISSUE TITLE
Dotnet lambda package permissions issue

### ISSUE THREAD

**Issue by kjmoon** [aws/aws-lambda-dotnet#130]
I've been running dotnet lambda package on my local machine (MacOS) and the package.zip runs fine on AWS Lambda. But when I run the same command on my Jenkins slave as ec2-user (rhel), Lambda can't find my assembly.

I've narrowed it down to a permissions issue. When I create the package on my local machine, the permissions are -rwxr--r-- but from the Jenkins slave it is -rwxr-----@. I assume the lack of a read permission in the Everyone group is causing the issue.

Is this an issue with AWS Lambda Tools or is something misconfigured on my Jenkins slave?

**Comment by normj** [comment]
Short answer is on your Jenkins Linux slave you need to make sure `zip` is available in the path.

When running the dotnet CLI Lambda tools on Linux it searches for the commandline utility `zip` to create the zip file which would maintain the file permissions. In earlier versions of the Amazon.Lambda.Tools package if it didn't find `zip` in the path then it assumed the deployment was happening on Windows and would use .NET Core built in compression library. In the latest version it detects if it is running on Linux and if it can't find `zip` in the path it throws an error about needing `zip`.

**Comment by kjmoon** [comment]
Hmm. ```zip``` is in my path and it's installed on my Linux box. 

I'm currently running v 1.5.0 of the Lambda tools so I figured there should be an error being thrown if ```zip``` isn't found, but it isn't.

**Comment by normj** [comment]
Can you add the console output to the issue?

**Comment by normj** [comment]
Also it was the 1.6.0 release that added the error check.

**Comment by kjmoon** [comment]
I've just ran the job using 1.6.0 of the Lambda Tools. The Jenkins Console Output is below, some things are redacted:

[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] sh
 Running shell script
dotnet build --configuration Release

[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Lambda Package)
[Pipeline] dir
Running in /var/lib/jenkins/workspace/**REDACTED**
[Pipeline] {
[Pipeline] sh
[**REDACTED**.FileToDB.Lambda] Running shell script
 dotnet lambda package ../pub/package.zip --configuration Release -f netcoreapp1.1
Executing publish command
... invoking 'dotnet publish', working folder '/var/lib/jenkins/workspace/**REDACTED**/**REDACTED**.FileToDB.Lambda/bin/Release/netcoreapp1.1/publish'
... publish: Microsoft (R) Build Engine version 15.1.548.43366
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   **REDACTED** -> /var/lib/jenkins/workspace/**REDACTED**/**REDACTED**/bin/Release/netcoreapp1.0/**REDACTED**.dll
... publish:   **REDACTED** -> /var/lib/jenkins/workspace/**REDACTED**/**REDACTED**/bin/Release/netcoreapp1.1/**REDACTED**a.dll
Changed permissions on published dll (chmod +r **REDACTED**.Lambda.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Core.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.S3Events.dll).
Changed permissions on published dll (chmod +r Amazon.Lambda.Serialization.Json.dll).
Changed permissions on published dll (chmod +r AWSSDK.Core.dll).
Changed permissions on published dll (chmod +r AWSSDK.Extensions.NETCore.Setup.dll).
Changed permissions on published dll (chmod +r AWSSDK.KeyManagementService.dll).
Changed permissions on published dll (chmod +r AWSSDK.S3.dll).
Changed permissions on published dll (chmod +r FlatFiles.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Configuration.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Configuration.Abstractions.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Configuration.FileExtensions.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Configuration.Json.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.DependencyInjection.Abstractions.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.FileProviders.Abstractions.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.FileProviders.Physical.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.FileSystemGlobbing.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Logging.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Logging.Abstractions.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Logging.Console.dll).
Changed permissions on published dll (chmod +r Microsoft.Extensions.Primitives.dll).
Changed permissions on published dll (chmod +r Newtonsoft.Json.dll).
Changed permissions on published dll (chmod +r Ninject.dll).
Changed permissions on published dll (chmod +r System.Collections.NonGeneric.dll).
Changed permissions on published dll (chmod +r System.Data.Common.dll).
Changed permissions on published dll (chmod +r System.Diagnostics.Contracts.dll).
Changed permissions on published dll (chmod +r System.Runtime.CompilerServices.Unsafe.dll).
Changed permissions on published dll (chmod +r System.Runtime.Serialization.Primitives.dll).
Changed permissions on published dll (chmod +r **REDACTED**.PurchaseFile.dll).
Flattening platform specific dependencies
... flatten: runtimes/unix/lib/netstandard1.3/System.Data.SqlClient.dll
... flatten: runtimes/unix/lib/netstandard1.3/System.IO.Pipes.dll
... flatten: runtimes/unix/lib/netstandard1.3/System.Text.Encoding.CodePages.dll
Zipping publish folder /var/lib/jenkins/workspace/**REDACTED**/**REDACTED**.FileToDB.Lambda/bin/Release/netcoreapp1.1/publish to /var/lib/jenkins/workspace/**REDACTED**/pub/package.zip
Creating directory /var/lib/jenkins/workspace/**REDACTED**/pub
... zipping:   adding: **REDACTED**.Lambda.dll (deflated 62%)
... zipping:   adding: **REDACTED**.Lambda.pdb (deflated 29%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 57%)
... zipping:   adding: Amazon.Lambda.S3Events.dll (deflated 58%)
... zipping:   adding: Amazon.Lambda.Serialization.Json.dll (deflated 56%)
... zipping:   adding: AWSSDK.Core.dll (deflated 66%)
... zipping:   adding: AWSSDK.Extensions.NETCore.Setup.dll (deflated 54%)
... zipping:   adding: AWSSDK.KeyManagementService.dll (deflated 72%)
... zipping:   adding: AWSSDK.S3.dll (deflated 63%)
... zipping:   adding: FlatFiles.dll (deflated 61%)
... zipping:   adding: Microsoft.Extensions.Configuration.dll (deflated 45%)
... zipping:   adding: Microsoft.Extensions.Configuration.Abstractions.dll (deflated 48%)
... zipping:   adding: Microsoft.Extensions.Configuration.FileExtensions.dll (deflated 47%)
... zipping:   adding: Microsoft.Extensions.Configuration.Json.dll (deflated 46%)
... zipping:   adding: Microsoft.Extensions.DependencyInjection.Abstractions.dll (deflated 54%)
... zipping:   adding: Microsoft.Extensions.FileProviders.Abstractions.dll (deflated 45%)
... zipping:   adding: Microsoft.Extensions.FileProviders.Physical.dll (deflated 46%)
... zipping:   adding: Microsoft.Extensions.FileSystemGlobbing.dll (deflated 49%)
... zipping:   adding: Microsoft.Extensions.Logging.dll (deflated 43%)
... zipping:   adding: Microsoft.Extensions.Logging.Abstractions.dll (deflated 54%)
... zipping:   adding: Microsoft.Extensions.Logging.Console.dll (deflated 48%)
... zipping:   adding: Microsoft.Extensions.Primitives.dll (deflated 49%)
... zipping:   adding: Newtonsoft.Json.dll (deflated 60%)
... zipping:   adding: Ninject.dll (deflated 58%)
... zipping:   adding: System.Collections.NonGeneric.dll (deflated 60%)
... zipping:   adding: System.Data.Common.dll (deflated 52%)
... zipping:   adding: System.Diagnostics.Contracts.dll (deflated 46%)
... zipping:   adding: System.Runtime.CompilerServices.Unsafe.dll (deflated 42%)
... zipping:   adding: System.Runtime.Serialization.Primitives.dll (deflated 48%)
... zipping:   adding: **REDACTED**.PurchaseFile.dll (deflated 61%)
... zipping:   adding: **REDACTED**.PurchaseFile.pdb (deflated 47%)
... zipping:   adding: **REDACTED**.FileToDB.Lambda.deps.json (deflated 80%)
... zipping:   adding: System.Data.SqlClient.dll (deflated 61%)
... zipping:   adding: System.IO.Pipes.dll (deflated 54%)
... zipping:   adding: System.Text.Encoding.CodePages.dll (deflated 30%)
... zipping:   adding: config/awsconfig.json (deflated 20%)
... zipping:   adding: config/config.dev.json (deflated 26%)
... zipping:   adding: config/config.json (deflated 35%)
Created publish archive (/var/lib/jenkins/workspace/**REDACTED**/pub/package.zip).
Lambda project successfully packaged: /var/lib/jenkins/workspace/**REDACTED**/pub/package.zip
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Upload)
[Pipeline] dir
Running in /var/lib/jenkins/workspace/**REDACTED**/pub
[Pipeline] {
[Pipeline] sh
[pub] Running shell script
 sudo aws s3 cp package.zip s3://bucket/lambda/**REDACTED**/**REDACTED**.lambda.FileToDB.1.0.0.57.zip --sse
Completed 1.2 MiB/1.8 MiB (1.2 MiB/s) with 1 file(s) remaining    
Completed 1.5 MiB/1.8 MiB (1.3 MiB/s) with 1 file(s) remaining    
Completed 1.8 MiB/1.8 MiB (1.4 MiB/s) with 1 file(s) remaining    
Completed 1.8 MiB/1.8 MiB (1.2 MiB/s) with 1 file(s) remaining    
[Pipeline] End of Pipeline
Finished: SUCCESS


The console output for the lambda is:
```
{
  "errorType": "LambdaException",
  "errorMessage": "Unable to load assembly 'Blah.FileToDB.Lambda, Culture=neutral, PublicKeyToken=null'."
}
```

**Comment by normj** [comment]
Thanks for the output. Looks like you are targeting netcoreapp1.1. Lambda currently only supports netcoreapp1.0.

**Comment by kjmoon** [comment]
Interesting. Well I've been doing ```dotnet lambda package ../pub/package.zip -c Release -f netcoreapp1.1``` on my local machine and the Lambda runs fine.

I can change the project down to 1.0 and see if it works. The handler I have is on 1.1 but the main application, which is in a different project with bulk of the code/business logic runs on 1.0.

**Comment by kjmoon** [comment]
Follow Up: So I converted everything to netcoreapp1.0 but the contents of my package still have permission of ```-rwxr-----``` and I'm still getting 
```
{
  "errorType": "LambdaException",
  "errorMessage": "Unable to load assembly 'Blah.FileToDB.Lambda, Culture=neutral, PublicKeyToken=null'."
}
```

**Comment by kjmoon** [comment]
Another quick follow up, I ended up doing ```chmod -R 755``` in the directory of the binaries before I zip it up and the error message goes away.

So I think it is a permissions issue but I would think that ```dotnet lambda package``` does do a chmod 755 before zipping.

**Comment by alanedwardes** [comment]
I think I am also seeing this issue using BitBucket pipelines - when I upload from there using `dotnet lambda deploy-function` (tools version 1.5.0) I get the following in CloudWatch: `Unable to load assembly 'Estranged.Lambda.Api.Rest, Culture=neutral, PublicKeyToken=null'.: LambdaException`

However when deploying locally from Visual Studio with the publishing UI, it works fine. Deployment ZIPs from both have the same number of files and size. Will check the permissions too and reply back.

**Comment by PaulColeman** [comment]
Does this help: https://github.com/aws/aws-lambda-dotnet/issues/113

**Comment by alanedwardes** [comment]
Hi, yes, in my case this completely fixed the problem! Thanks @PaulColeman :)

**Comment by normj** [comment]
Closing because I believe everybody has there permission issue resolved. If that is not the case feel free to reopen.

**Comment by darbio** [comment]
I am still getting this error when I try and run using a custom runtime. The executable isn't set to `+x` so won't run on AWS. `zip` is in my path and runs.

**Comment by normj** [comment]
What version of Amazon.Lambda.Tools are using? To use the recent custom runtime support you should use at least version 3.1.4 although I would recommend version 3.2.0 which was released yesterday.

If you are still seeing issues after upgrading I recommend opening a new issue as this is a very old issue and adding communication to old issues tend to get lost. Be sure to let us know what OS you are using as well if you open an issue.
