### ISSUE TITLE
Logging providers are not disposed in Amazon.Lambda.AspNetCoreServer.Hosting

### ISSUE THREAD

**Issue by ThomasArdal** [aws/aws-lambda-dotnet#1306]
### Describe the bug

I'm not 100% sure here. But I think there's a problem with logging when running Lambdas on the new .NET 6 runtime with minimal API. It probably works fine when logging to something that takes 1 ms. But in case of remote loggers I'm experiencing problems. Let's say we have set up code like this in the `Program.cs` file:

```csharp
builder.Services.AddLogging(logging =>
{
    logging.AddMyRemoteLoger();
});
```

`AddMyRemoteLogger` is invented for this issue but it represents a logging provider that catch messages and call an external endpoint.

In an Lambda doing something like this:

```csharp
private readonly ILogger<MyEndpoint> _logger;

public MyEndpoint(ILogger<MyEndpoint> logger)
{
    _logger = logger;
}

public override async Task HandleAsync(MyRequest req, CancellationToken ct)
{
    _logger.LogInformation("Request");
}
```

This should trigger an information message to the logger and it does. The issue is that before the remote logger provider is actually able to finish its work, the runtime is closed down. This behavior is only present when running on AWS and not when running on localhost. I guess localhost keeps the process open or something.

I found out that this might be an issue by changing the `HandleAsync` method to this:

```csharp
public override async Task HandleAsync(MyRequest req, CancellationToken ct)
{
    _logger.LogInformation("Request");
    Thread.Sleep(1000);
}
```

When doing so, the remote logger will have time to make the HTTP request that store the log.

This is a common problem with remote loggers that Microsoft.Extensions.Logging solved with `IDisposable`. When implementing a remote logger, you need to implement `Dispose` on the provider and store any pending log messages before returning from that call. Frameworks like ASP.NET Core then automatically calls the `Dispose` method. The problem here is that the .NET 6 runtime for AWS Lambdas doesn't seem to call `Dispose`.

### Expected Behavior

Expect `Dispose` to be called after executing a lambda.

### Current Behavior

`Dispose` doesn't seem to be called.

### Reproduction Steps

Steps are in the description.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.Hosting 1.3.1

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @ThomasArdal,

Good afternoon.

Could you please share the sample code solution for `MyRemoteLogger` to investigate the issue?

Thanks,
Ashish

**Comment by ThomasArdal** [comment]
The idea here is that I want to log to both Cloudwatch and another destination.

I'll try to see if I can put a sample together.

**Comment by ThomasArdal** [comment]
@ashishdhingra Ok, here's a repository that I hope will re-create this. I'm having problems deploying this lambda and calling it. Maybe I'm just not skilled enough in AWS and I'm doing something wrong.

https://github.com/ThomasArdal/LambdaRemoteLogger

Let me go through what is created there. The `LogEndpoint` class has a single endpoint that can be POSTed to through:

```
https://localhost:7168/log/error
```

This does nothing more than logging an information message through an injected `ILogger`. Logging is configured in `Program.cs`:

```csharp
builder.Services.AddLogging(logging =>
{
    logging.AddRemoteLogger();
});
```

I have implemented a logger and provider for the remote logger. The remote logger doesn't actually log to a remote service but simulates it. Internally it is implemented with a message queue where all log messages are added to the queue. Then every 10 seconds, the queue is processed and a line is written to `Console.WriteLine` to tell that messages are being processed.

This approach works as long as the process is running and 10 seconds pass. You can test this by running the project on localhost and POSTing a few times to the endpoint. Within 10 seconds, a line is written to the console indicating how many messages are being processed.

This does, of course, not work if the process is shut down since that will clear the queue before it is processed. To make this work, frameworks always need to call `Dispose` on all logging providers configured. This is done automatically in a framework like ASP.NET Core. When running this example project on localhost, I can see that the `Dispose` method is called when CTRL+C'ing the console window. Everything good.

My theory is that when this is running on AWS, the `Dispose` method is not called. Or the `Dispose` method is called and then the runtime closes down before the code return from `Dispose`.

**Comment by normj** [comment]
@ThomasArdal This is a challenge with anything that runs in the background in Lambda like a message queue to pushing logs to a remote provider. When the event is completed the background processes are paused and unless another event goes back into the same Lambda compute container there is no guarantee the background process will finish its work.

I don't see how a call to dispose will help because we would have to dispose of the whole ASP.NET Core runtime and then restart the ASP.NET Core runtime on the next event which would cause terrible performance. Out of curiosity what logging provider are you using in your real application?

**Comment by ThomasArdal** [comment]
@normj I totally understand the challenge. You cannot keep the runtime running in case any background threads want to do work at some point. But that's why the `Dispose` is there. When running this code on localhost and the runtime is shut down, the `Dispose` method is called. When running on AWS it looks like it is not called. For inspiration, ASP.NET Core has this exact thing implemented to make sure that configured services are shut down nicely. To be fair I should probably compare with Azure Functions and not a website since they share the same lifecycle as lambda. I'm pretty sure functions also call the `Dispose` method on configured services.

Most of the code for the logger provided through the repository is taken from here: https://github.com/elmahio/Elmah.Io.Extensions.Logging.

**Comment by petarrepac** [comment]
"When running this code on localhost and the runtime is shut down, the Dispose method is called."

on localhost you send a "message" (like CTRL+C) to the **process** running the ASP.NET and then ASP.NET code nicely shutdown cleaning and disposing what's needed

when the "Lambda service" decides that it will not use some compute container anymore, it just kills it, without any notice
that's why there is not "Dispose" called and things nicely being shutdown
BTW, this functionality would be nice to have, but it is not up to the .NET team in AWS it seems

@normj - do I understand this working correctly ?

also, and most important: **is writing to std out (e.g. Console.WriteLine) taking 0 ms and is "guaranteed" to be delivered to CloudWatch** ??????

**Comment by normj** [comment]
@petarrepac You have it write. The .NET process running inside the Lambda compute environment has no signal of when it is being killed. So the only alternative would be to dispose all of ASP.NET Core after every request and then restart for the next request. That would be unacceptable performance. So @ThomasArdal I agree with you in principal but this is one of the tradeoffs when running ASP.NET Core designed for long running process as a Lambda function. Most thinks work well inside Lambda but there are a few tradeoffs.

**Comment by ThomasArdal** [comment]
@normj Isn't there some kind of shutdown hook or similar that one could subscribe to? In case anything needs to shutdown "correctly".

**Comment by normj** [comment]
@ThomasArdal there is no shutdown hook in a Lambda compute environment.

**Comment by ThomasArdal** [comment]
Ok, thank you for your help. I think the way to solve this for me is to write some documentation.

I'll close this one.
