### ISSUE TITLE
Monitor Dead Letter Queue does not return attributes and messageattributes of messages

### ISSUE THREAD

**Issue by william-keller** [aws/aws-lambda-dotnet#1307]
### Describe the bug

Monitor Dead Letter Queue does not return attributes and messageattributes of messages

When Start Monitoring is clicked, just the body of the message is passed to the lambda function.

### Expected Behavior

Pass the complete message to the lambda function

### Current Behavior

Just the message body is passed to the lambda function

### Reproduction Steps

Launch the web application

Go to DLQ Monitor

Select a Queue

Start Monitoring

### Possible Solution

I am submitting the PR with the complete solution for this problem

### AWS .NET SDK and/or Package version used

All

### Targeted .NET Platform

All

### Operating System and version

All

**Comment by normj** [comment]
Associated PR has been released as part of 0.12.4. Thanks for the PR!
