### ISSUE TITLE
Lambda test tool not starting on MacOS

### ISSUE THREAD

**Issue by rickythefox** [aws/aws-lambda-dotnet#1309]
### Describe the bug

Lambda test tool does not start on MacOS.

### Expected Behavior

Lambda test tool starts

### Current Behavior

Test tool does not start. The following error is shown when manually executing `./Amazon.Lambda.TestTool.BlazorTester.dll`:

```exec: Failed to execute process: '/Users/xxx/.dotnet/tools/.store/amazon.lambda.testtool-6.0/0.12.4/amazon.lambda.testtool-6.0/0.12.4/tools/net6.0/any/Amazon.Lambda.TestTool.BlazorTester.dll' the file could not be run by the operating system.```

### Reproduction Steps

Create a new lambda project.
Put the following configuration in `launchSettings.json` and try to run the test tool.
```
    "Mock Lambda Test Tool": {
      "commandName": "Executable",
      "commandLineArgs": "--port 5050",
      "workingDirectory": ".",
      "executablePath": "$(HOME)/.dotnet/tools/.store/amazon.lambda.testtool-6.0/0.12.4/amazon.lambda.testtool-6.0/0.12.4/tools/net6.0/any/Amazon.Lambda.TestTool.BlazorTester.dll",
      "environmentVariables": {
      }
    }
```

### AWS .NET SDK and/or Package version used

dotnet 6.0.100

### Targeted .NET Platform

.NET 5

### Operating System and version

MacOS 12.6

**Comment by ashishdhingra** [comment]
Hi @rickythefox,

Good morning.

The steps to configure Lambda Test Tool on Mac are different from Windows. Please follow the steps at https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-visual-studio-for-mac and let me know if it works for you (I tested it locally and the steps work).

Thanks,
Ashish
