### ISSUE TITLE
`dotnet new lambda/serverless.* ...` fails with .NET 7.0.100-rc.1.22431.12

### ISSUE THREAD

**Issue by bjhogan** [aws/aws-lambda-dotnet#1317]
### Describe the bug

With the .NET SDK 7.0.100-rc.1.22431.12, `dotnet new lambda.EmptyFunction ...` and other templates fail. 

```
> dotnet new lambda.EmptyFunction -n MyEmptyFunction
Template "Lambda Empty Function" could not be created.
Failed to create template.
Details: Object reference not set to an instance of an object.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#100
```

```
> dotnet new serverless.AspNetCoreWebApp -n AspNetCoreWebApp
Template "Lambda ASP.NET Core Web Application with Razor Pages" could not be created.
Failed to create template.
Details: Object reference not set to an instance of an object.
```

### Expected Behavior

`dotnet new lambda.EmptyFunction ...` creates the appropriate projects.

### Current Behavior

Command fails with - 

```
Template "Lambda Empty Function" could not be created.
Failed to create template.
Details: Object reference not set to an instance of an object.

For details on the exit code, refer to https://aka.ms/templating-exit-codes#100
```

### Reproduction Steps

Download .NET SDK 7.0.100-rc.1.22431.12 

Run `dotnet new lambda.EmptyFunction -n MyEmptyFunction`

### Possible Solution

Can workaround this problem by creating a `global.json` file for an earlier version of .NET.
 
`dotnet new globaljson --sdk-version 6.0.401`

### AWS .NET SDK and/or Package version used

.NET SDK 7.0.100-rc.1.22431.12

Amazon.Lambda.Templates (version 6.3.0)
amazon.lambda.tools version 5.4.5

### Targeted .NET Platform

.NET SDK 7.0.100-rc.1.22431.12

### Operating System and version

Windows 10

**Comment by normj** [comment]
I opened up an issue against on the Microsoft templating repository to get some help debugging this issue. https://github.com/dotnet/templating/issues/5300

**Comment by normj** [comment]
Version 6.4.0 of the template has been released with the fix. Thanks for reporting the issue Bryan!
