### ISSUE TITLE
AWS lambda in docker container run local

### ISSUE THREAD

**Issue by schmallaria** [aws/aws-lambda-dotnet#1324]
### Describe the bug

I have created an ASP.NET 6 minimal API project which is running in a docker container hosted in a AWS lambda function. When i run the container via Visual Studio debug command everything is working as expected. I'm also able to deploy the image to ECR and run the project in a Lambda. These two cases are working. 

Now I try to get a third case running. I want to be able to pull the image from ECR and run it locally using `docker run` command. 

**Dockerfile**
```
FROM public.ecr.aws/lambda/dotnet:6 AS base

ENV KRB5_CONFIG=/etc/krb5.conf
ADD krb5.conf /etc/krb5.conf

FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim as build
COPY . /MinimApiTest

WORKDIR /MinimApiTest

RUN dotnet build "MinimApiTest.csproj" -o /app/build

FROM build AS publish
RUN dotnet publish "MinimApiTest.csproj" -c Release -o /app/publish

FROM base AS final
COPY --from=publish /app/publish ${LAMBDA_TASK_ROOT}
CMD [ "MinimApiTest" ]
```

I have pulled the image successfully from ECR and started the container with the following command:

`docker run -dt -p 5000:80 MinimalApiTest:latest`

I get the error message: `entrypoint requires the handler name to be the first argument`.

What commands/argument should i use to get the container running on my local machine?

### Expected Behavior

n/a

### Current Behavior

n/a

### Reproduction Steps

n/a

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.Hosting 1.3.1

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @schmallaria,

Good afternoon. 

Following articles might be helpful:
- [Creating Lambda container images](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html) for required container settings.
- [Testing Lambda container images locally](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html)

Thanks,
Ashish

**Comment by schmallaria** [comment]
I have seen these articles. But can't get it running.

I've tried to run another command which invokes the lambda entrypoint directly.

`docker run -it -p 5000:80 --name MinimalApi --entrypoint /lambda-entrypoint.sh MinimalApiTest:latest MinimalApiTest`

With this i got the following message in the logs

`[INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)`

But my API is still not running. Note, that i'm using [this nuget package](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer.Hosting) for hosting the .NET API. There are no examples and no documentation on how to build and run a docker container locally when using this package.

**Comment by normj** [comment]
When you run the image locally are you trying to access it like a REST API? I think you were close with your second post but you can't send REST request directly to the ASP.NET Core application you have to post them through the Lambda emulator running in the container. For example in the common ASP.NET Core project template that has the GET `/weatherforecast` endpoint. you do an `POST` to `http://localhost:9000/2015-03-31/functions/function/invocations` with a request payload of 

```
{
  "body": null,
  "resource": "/{proxy+}",
  "path": "/weatherforecast",
  "httpMethod": "GET",
  "queryStringParameters": {

  },
  "pathParameters": {
    "proxy": "weatherforecast"
  },
  "stageVariables": {
    "baz": "qux"
  },
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, sdch",
    "Accept-Language": "en-US,en;q=0.8",
    "Cache-Control": "max-age=0",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    "Host": "1234567890.execute-api.{dns_suffix}",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Custom User Agent String",
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "requestContext": {
    "accountId": "123456789012",
    "resourceId": "123456",
    "stage": "prod",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": null,
      "cognitoIdentityId": null,
      "caller": null,
      "apiKey": null,
      "sourceIp": "127.0.0.1",
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": null,
      "userAgent": "Custom User Agent String",
      "user": null
    },
    "resourcePath": "/{proxy+}",
    "httpMethod": "GET",
    "apiId": "1234567890"
  }
}
```

**Comment by unfunco** [comment]
Apologies for commenting on this old issue, but I ran into the same error message when using Go, the issue for me was caused by an incorrect port mapping, changing that when running the container fixed the error, the runtime interface emulator is listening on port 8080.

`docker run --publish "9000:8080" ...`

**Comment by pratyushdev-codes** [comment]
I have made an Agentic AI , and trying to deploy it to AWS lambda using Docker images. I am getting this error on the terminal and unable to run the Docker image..
Error: 16 Jan 2025 17:56:20,772 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
^C16 Jan 2025 17:56:24,043 [INFO] (rapid) Received signal signal=interrupt
16 Jan 2025 17:56:24,043 [INFO] (rapid) Shutting down...
16 Jan 2025 17:56:24,045 [WARNING] (rapid) Reset initiated: SandboxTerminated
16 Jan 2025 17:56:24,046 [INFO] (rapid) Waiting for runtime domain processes termination

<img width="697" alt="Image" src="https://github.com/user-attachments/assets/cd750816-3a38-4554-ac17-2d94b2d20858" />
