### ISSUE TITLE
Unable to validate Oauth JWT, getting Platform not supported exception

### ISSUE THREAD

**Issue by automagic** [aws/aws-lambda-dotnet#133]
I seem to be getting this error trying to validate a JWT access token.  This seems to work fine locally.  Has anyone seen this before?   Basically i'm just doing:

```
            var options = new JwtBearerOptions
            {
                Audience = authOptions.Value.Audience,
                Authority = authOptions.Value.Authority,
            };

            app.UseJwtBearerAuthentication(options);
```

```FCW-SvnQ6UGJ6PKXO-a2rKwA. 
IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: M0MxM0VBMzczNjRFNTdCREFBMjNCMTQxNzBBMjcyOTRBNDczMjdBNg
'.
Exceptions caught:
 'System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Internal.Cryptography.Pal.OpenSslX509Encoder.BuildRsaPublicKey(Byte[] encodedData)
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PublicKey()
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.IsSupportedAlgorithm(String algorithm, SecurityKey key)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)```

**Comment by normj** [comment]
Could you share your project file? I'm curious what dependencies you are using.

**Comment by automagic** [comment]
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.2" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0-rc1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.9.0-preview1" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.1" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.0.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.3.1" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.0.0-rtm-beta4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.1.0" />
  </ItemGroup>
```

**Comment by normj** [comment]
You are pulling in dependencies that are based on .NET Core 1.1. You are getting this error because Lambda supports .NET Core 1.0.

**Comment by automagic** [comment]
Specifically which dependencies?

**Comment by normj** [comment]
Here is my pass setting your dependencies at .NET Core 1.0 level

```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.2" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.2" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0-rc1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.2" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.0.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.3.1" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.0.0-rtm-alpha5" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.0.1"/>
  </ItemGroup>
```

**Comment by automagic** [comment]
Thank you... I downgraded the libraries to the following set, but am still getting the original error after deployment:

```
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.2" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.2" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0-rc1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.2" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.0.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.3.1" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.0.0-rtm-beta4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.0.1" />
  </ItemGroup>
```

**Comment by automagic** [comment]
nal.Cryptography.Pal.OpenSslX509Encoder.BuildRsaPublicKey(Byte[] encodedData)
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PublicKey()
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.IsSupportedAlgorithm(String algorithm, SecurityKey key)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: '{"alg":"RS256","typ":"JWT","kid":"M0MxM0VBMzczNjRFNTdCREFBMjNCMTQxNzBBMjcyOTRBNDczMjdBNg"}.{"iss":"https://auth.2ndwatch-dev.auth0.com/","sub":"auth0|58f5354190cc374e953862ca","aud":["https://localhost:5000","https://auth.2ndwatch-dev.auth0.com/userinfo"],"azp":"pluAiuiTF6Y4OmTBtdpvdpFWmV350XYk","exp":1498850209,"iat":1498763809,"scope":"openid profile email write:users read:users name","gty":"password"}' 
Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: M0MxM0VBMzczNjRFNTdCREFBMjNCMTQxNzBBMjcyOTRBNDczMjdBNg
'.
Exceptions caught:
 'System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Internal.Cryptography.Pal.OpenSslX509Encoder.BuildRsaPublicKey(Byte[] encodedData)
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PublicKey()
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.IsSupportedAlgorithm(String algorithm, SecurityKey key)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: '{"alg":"RS256","typ":"JWT","kid":"M0MxM0VBMzczNjRFNTdCREFBMjNCMTQxNzBBMjcyOTRBNDczMjdBNg"}.{"iss":"https://auth.2ndwatch-dev.auth0.com/","sub":"auth0|58f5354190cc374e953862ca","aud":["https://localhost:5000","https://auth.2ndwatch-dev.auth0.com/userinfo"],"azp":"pluAiuiTF6Y4OmTBtdpvdpFWmV350XYk","exp":1498850209,"iat":1498763809,"scope":"openid profile email write:users read:users name","gty":"password"}' 
Request successfully matched the route with name '(null)' and template 'users'. 
Action 'Platform.API.Controllers.UserController.Post (Platform.API)' with id '433e3fbe-3fce-4a1b-9c97-b4623b504ec3' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
Executing action Platform.API.Controllers.UserController.GetUsers (Platform.API) 
Executing action method Platform.API.Controllers.UserController.GetUsers (Platform.API) with arguments (1, 100) - ModelState is Valid 
Authorization failed for user: (null). 
Executed action method Platform.API.Controllers.UserController.GetUsers (Platform.API), returned result Microsoft.AspNetCore.Mvc.ChallengeResult. 
Executing ChallengeResult with authentication schemes (). 
AuthenticationScheme: Bearer was challenged. 
Executed action Platform.API.Controllers.UserController.GetUsers (Platform.API) in 101.7452ms 
Request finished in 117.9456ms 401  
Response Base 64 Encoded: False
END RequestId: a85d1e3c-5cff-11e7-b83f-27d57881dc21
REPORT RequestId: a85d1e3c-5cff-11e7-b83f-27d57881dc21	Duration: 172.17 ms	Billed Duration: 200 ms 	Memory Size: 1024 MB	Max Memory Used: 75 MB

**Comment by normj** [comment]
You still have Microsoft.AspNetCore.JsonPatch version 1.1.1 which pulls in Microsoft.CSharp and System.Reflection.TypeExtensions version 4.3.0 which is part of .NET Core 1.1.

Could you attach the *.deps.json file that should be in your publish folder? That would give more clues of what is pulling on .NET Core 1.1 dependencies.

**Comment by automagic** [comment]
Why specifically would either of those libraries cause this specific error?  Also, those libraries require netstandard1.5, why would they be incompatible with netcore 1.0?    Do you have any documentation on why system libraries with a 4.3.0 version are not compatible,  would be helpful to our team.  

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by automagic** [comment]
After downgrading all my packages to completely ensure that 4.3.0 libraries are not imported, and adding  ```<NetStandardImplicitPackageVersion>1.6.0</NetStandardImplicitPackageVersion>```
to the .csproj files, it does indeed work.   

I find it pretty unfortunate that we have to downgrade packages so far in order to run on lambda.

**Comment by normj** [comment]
I agree it is unfortunate that you have to downgrade packages. It is something we want to figure out how we can improve in the future.

Documentation in .NET Core versioning is sparse. Basically what happens is when you pull in 4.3.0 references or NETStandard.Libdary 1.6.1 but your project is targeting .NET Core 1.0, which you need to for Lambda, the .NET Core packaging process brings in a lot of the  system dlls from .NET Core 1.1. It does that because it finds references that are different then what is included in netcoreapp1.0. Then when the function is running the .NET Core assembly loader will pick up those system dlls over the system dlls we compiled for the Lambda environment and then you get errors like you got.

I'm closing this because it looks like you were able to get paste your issue.
