### ISSUE TITLE
"." is treated as invalid character and is replaced with "_"

### ISSUE THREAD

**Issue by taiyanzu** [aws/aws-lambda-dotnet#134]
To reproduce(Mac OS):

```
dotnet new lambda.EmptyFunction --name Company.Team.ProductA
cat Company.Team.ProductA/src/Company.Team.ProductA/Function.cs | grep namespace
```
Expected:

`namespace Company.Team.ProductA`

Actual:

`namespace Company_Team_ProductA`

In contrast, if you run 

```
dotnet new console --name Company.Team.ProductB
cat Company.Team.ProductB/Program.cs | grep namespace
```
you get `namespace Company.Team.ProductB` as expected.

Another related error in `Readme.md` is that the directory names do not exist:
```
cd "Company_Team_ProductA"
cd "Company_Team_ProductA/test/Company_Team_ProductA.Tests"
cd "Company_Team_ProductA/src/Company_Team_ProductA"
```

They should be:

```
cd "Company.Team.ProductA"
cd "Company.Team.ProductA/test/Company.Team.ProductA.Tests"
cd "Company.Team.ProductA/src/Company.Team.ProductA"
```

It seems invalid characters are replace with "_". But according to [vs_projectname](https://www.npmjs.com/package/vs_projectname) "." is valid.

Because "." is heavily used in .NET projects to organize code, it should not be escaped with "_".

**Comment by normj** [comment]
I opened up the https://github.com/dotnet/templating/issues/1193 issue on the dotnet/templating repository to find a fix for this issue but it doesn't look like there is a fix you in the templating engine. Sounds like a fix is coming, or probably came out yesterday as part of the .NET Core 2.0 release. But if I make that change then users with the pre .NET Core 2.0 cli will be even more broken.

**Comment by normj** [comment]
Version 3.0.0 of `Amazon.Lambda.Templates` released today now has this fixed.
