### ISSUE TITLE
LambdaLogger with "X-Amzn-Trace-Id"

### ISSUE THREAD

**Issue by RomanBorysenok** [aws/aws-lambda-dotnet#135]
Hello,

Thank you for all efforts!
I have a question regarding appending `CorrelationId` to all logs that is written to the CloudWatch.

Simple example for `Serilog`:

We could create a simple middleware and append `CorrelationId` to the `LogContext`.

```
using (LogContext.PushProperty(Constants.CorrelationId, correlationId))
{
   return _next(context);
}
```
Is there a way how to append `CorrelationId` with `LambdaLogger`?

Thanks!

**Comment by normj** [comment]
LambdaLogger doesn't have anything like that built in right now. You would need to manually add it now which could easily be done by wrapping a custom object around LambdaLogger that appended and then use the custom object throughout your function to log.
