### ISSUE TITLE
Lambda Annotations: error caused by mismatch in HttpApi attribute parameters and method parameters

### ISSUE THREAD

**Issue by aandonoska** [aws/aws-lambda-dotnet#1351]
### Describe the bug

When using Lambda Annotations with Rest API, if the number of parameters in the "HttpApi" attribute do not match the parameters defined in the method itself the following error is shown:
`This is a bug. Please run the build with detailed verbosity (dotnet build --verbosity detailed) and file a bug at https://github.com/aws/aws-lambda-dotnet with the build output and stack trace y parameter of type int passing is not supported.   at Amazon.Lambda.Annotations.SourceGenerator.Templates.LambdaFunctionTemplate.TransformText()	
`

I was able to fix the issue on my side, I'm opening this issue in case it is of any value on your side based on the error message.

### Expected Behavior

A more meaningful error message is shown.

### Current Behavior

`This is a bug. Please run the build with detailed verbosity (dotnet build --verbosity detailed) and file a bug at https://github.com/aws/aws-lambda-dotnet with the build output and stack trace y parameter of type int passing is not supported.   at Amazon.Lambda.Annotations.SourceGenerator.Templates.LambdaFunctionTemplate.TransformText()	
`

### Reproduction Steps

[LambdaFunction()]
[HttpApi(LambdaHttpMethod.Get, "/add/{x}")]
 public int Add(int x, int y, ILambdaContext context)
 {
    ...
}

### AWS .NET SDK and/or Package version used

/

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Based on discussion with the team, the action item is to improve the error messaging.

**Comment by ashishdhingra** [comment]
> Based on discussion with the team, the action item is to improve the error messaging.

After upgrading to `Amazon.Lambda.Annotations` version `0.13.2`, the error message given during compile time is improved as shown below:
| Severity | Code          | Description                                                                        | Project               | File                                                                      | Line | Suppression State |
|----------|---------------|------------------------------------------------------------------------------------|-----------------------|---------------------------------------------------------------------------|------|-------------------|
| Error    | AWSLambda0107 | Route template /add/{x}/{y} is invalid. Missing y parameters in method definition. | LambdaAnnotationsTest | D:\source\repros\LambdaAnnotationsTest\LambdaAnnotationsTest\Functions.cs | 53   | Active            |

Hence, closing this issue.
