### ISSUE TITLE
The type or namespace name 'ServiceProvider' could not be found error in Amazon.Lambda.Annotations.SourceGenerator.Generator(short issue description)

### ISSUE THREAD

**Issue by anwarjaved** [aws/aws-lambda-dotnet#1357]
### Describe the bug

I am trying to use Amazon.Lambda.Annotations.SourceGenerator.Generator and it seems it ghenerates wrong code. Instead of using IServiceProvider type they use ServiceProvider Type which result in exception.
[error.txt](https://github.com/aws/aws-lambda-dotnet/files/9941500/error.txt)
![image](https://user-images.githubusercontent.com/99399/200061105-1ecbcdd4-04ed-446a-931a-ef99c87771df.png)

### Expected Behavior

It should compile properly as there is no issue in the code.

### Current Behavior

Failed in Code Generation by Amazon.Lambda.Annotations.SourceGenerator.Generator 

### Reproduction Steps

Use Amazon.Lambda.Annotations0.9.0-preview in project and try to setup  [LambdaStartup] on class.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Annotations 0.9.0-preview

### Targeted .NET Platform

.Net 6

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Hi @anwarjaved,

Good afternoon.

Thanks for reporting the issue. Could you please share the detailed steps to reproduce the issue, may be the sample code solution? I used Visual Studio 2022 annotations template as per instructions at https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Annotations#visual-studio-2022 and upgraded to `Amazon.Lambda.Annotations` version `0.9.0-preview`, however, unable to reproduce the issue.

Thanks,
Ashish

**Comment by farooqiqbal1** [comment]
I am facing this issue, any update on this?

**Comment by normj** [comment]
@farooqiqbal1 This issue was closed for being stale and we never got repo scenario. If you are having an issue I would appreciate hearing about it. Could you open a new issue and provide some sample code and possibly your project file to understand what is happening.

**Comment by farooqiqbal1** [comment]
@normj Actually the issue was on my end, I copied the code from the template into my existing project. For the context the error was generated due to missing package ```Microsoft.Extensions.DependencyInjection```. However because I copied the contents of the ```.csproj``` file so I was not expecting a missing package. Comes out the boilerplate that you have on Github has another framework referenced ```Microsoft.AspNetCore.App``` which has this package installed inside it therefore doesn't require the packages to be explicitly installed. However in my case the project was not having this framework referenced nor the package installed therefore I was getting this error.

**Comment by normj** [comment]
@farooqiqbal1 Thanks for the follow up. I added the `Microsoft.AspNetCore.App` framework reference to reduce the deployment bundle and ever so slightly improve cold start performance when using dependency injection.

**Comment by farooqiqbal1** [comment]
@normj maybe you should mention it in the docs.

**Comment by idoroshenko** [comment]
> Microsoft.Extensions.DependencyInjection

@farooqiqbal1 I had the same missing package. It helped me to fix the issue. Thanks
