### ISSUE TITLE
Allow NativeAOT to be executed as a part of .NET Lambda managed runtime

### ISSUE THREAD

**Issue by sagulati** [aws/aws-lambda-dotnet#1358]
### Describe the feature

Currently for Executable Assemblies, the Amazon.Lambda.RuntimeSupport package looks for ${Executable_Assembly}.dll when initializing the lambda function. For NativeAOT and [Single File Executable Assemblies](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli), Update this to also look for "${Executable_Binary}" without ".dll". 

A link to the line in question can be seen here:
[https://github.com/aws/aws-lambda-dotnet/blob/0e8e42a0fe818f1adc1f97bb035f2535934c16b4/Libraries/src/Amazon.Lambda.RuntimeSupport/bootstrap.sh#L44](https://github.com/aws/aws-lambda-dotnet/blob/0e8e42a0fe818f1adc1f97bb035f2535934c16b4/Libraries/src/Amazon.Lambda.RuntimeSupport/bootstrap.sh#L44)

### Use Case

Allow NativeAOT and Single file executables to be run as a part of .NET Lambda managed runtime. Compiling the .NET executable assembly as NativeAOT generates a self-contained single compressed executable file that does not work in .NET managed runtime and the AWS Lambda Custom Runtime is required. 

### Proposed Solution

Update the bootstrap.sh file to add support for single executable file. 

If the Lambda_Handler does not contain ":" and {EXECUTABLE_ASSEMBLY}.dll is not found, then look for Single Executable file at path "${LAMBDA_TASK_ROOT}/${LAMBDA_HANDLER}" and execute it.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Lambda.RuntimeSupport 1.8.2

### Targeted .NET Platform

.NET6 / .NET 7

### Operating System and version

ASL2

**Comment by ashishdhingra** [comment]
Appears to be a valid feature request. Needs review with the team.

**Comment by sagulati** [comment]
@ashishdhingra [PR raised](https://github.com/aws/aws-lambda-dotnet/pull/1365).

**Comment by ashishdhingra** [comment]
@sagulati Please refer the blog post [Building serverless .NET applications on AWS Lambda using .NET 7](https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/) for the Native AOT support and see if it covers your scenario.

Thanks,
Ashish

**Comment by sagulati** [comment]
@ashishdhingra - Thanks for sharing the blog post. The blog post talks about deploying NativeAOT in **custom runtime** using AWS tooling. Scenario i have is to enable running NativeAOT as apart of **.NET Lambda managed runtime**. So these are two different scenarios and [PR i have raised](https://github.com/aws/aws-lambda-dotnet/pull/1365) will allow to execute .NET6/.NET7 NativeAOT as a part of Lambda .NET managed runtime. Thanks Sanjay.

**Comment by ashishdhingra** [comment]
@sagulati I see that PR is already merged. Please confirm if we could close this issue.

**Comment by sagulati** [comment]
@ashishdhingra - yes the issue can be closed. Thanks for reviewing the PR and accepting it.
