### ISSUE TITLE
AbstractLambdaJsonSerializer does not reuse JsonSerializerOptions resulting in Performance penalty

### ISSUE THREAD

**Issue by udlose** [aws/aws-lambda-dotnet#1359]
### Describe the bug

`JsonSerializerOptions` are supposed to be re-used across usages with the same settings - see [Reuse JsonSerializerOptions instances](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/configure-options?pivots=dotnet-6-0#reuse-jsonserializeroptions-instances).  Not re-using `JsonSerializerOptions` instances causes performance penalties.

While browsing the AWS source for `Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer` I noticed that `CreateDefaultJsonSerializationOptions` creates a new `JsonSerializerOptions` instance and does not re-use instances: https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/AbstractLambdaJsonSerializer.cs#L131-L147

### Expected Behavior

`JsonSerializerOptions` instances would be re-used (performance improvement)

### Current Behavior

`JsonSerializerOptions` instances are not re-used (performance penalty)

### Reproduction Steps

See source code for `Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer`: https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/AbstractLambdaJsonSerializer.cs#L131-L147

### Possible Solution

Wrap the creation of new `JsonSerializerOptions` with `Lazy<T>` so that instances are:
1. lazily created
2. more importantly, they are re-used

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Serialization.SystemTextJson v2.3.0

### Targeted .NET Platform

.NET 6

### Operating System and version

Amazon  Linux

**Comment by udlose** [comment]
@ashishdhingra Thank you for your quick review!  To be fair, I haven't profiled this to measure the negative performance impact the current code has.  I follow the .NET world pretty closely and know that there have been many performance issues reported by Microsoft customers regarding the performance impact of repeatedly creating new instances of `JsonSerializerOptions`. There are a few Github threads on the matter:

- [Temporary use of JsonSerializerOptions slows down Performance of JsonSerializer.Serialize](https://github.com/dotnet/runtime/issues/38982)
- [Thread starvation on high load with System.Text.Json](https://github.com/dotnet/runtime/issues/40072)
- [Reuse JsonSerializerOptions when used with JsonSerializerContext](https://github.com/dotnet/runtime/issues/64025)
- [Avoid performance issues with JsonSerializer by reusing the same JsonSerializerOptions instance](https://www.meziantou.net/avoid-performance-issue-with-jsonserializer-by-reusing-the-same-instance-of-json.htm) 

Respectfully, I wouldn't classify a performance improvement as a Feature Request.

**Comment by normj** [comment]
Hi @udlose, this method is only called during the constructor of the serializer. The Lambda runtime client which uses the serializer only creates one instance of the serializer. So in Lambda's case there is nothing to reuse since the serializer is only created once.

**Comment by udlose** [comment]
Hi @normj . Thanks for the reply. Is this called only once per instantiation/warmup of the Lambda or once per invocation of the Lambda? IOW, if there are 10 invocations of the lambda before the Lambda spins down, is the serialized constructed once or 10 times?

**Comment by normj** [comment]
It would be called only once per Lambda compute environment or what I think you are calling "instantiation/warmp". It is not called for every Lambda invocation.

**Comment by udlose** [comment]
> It would be called only once per Lambda compute environment or what I think you are calling "instantiation/warmp". It is not called for every Lambda invocation.

Ok. I will close the issue. Thanks.
