### ISSUE TITLE
IFormFile content has changed on zip file

### ISSUE THREAD

**Issue by Newp** [aws/aws-lambda-dotnet#1366]
### Describe the bug

When a file is transferred via IFormFile, when a .txt file is transferred, the length of the file sent by the client, md5 hash values, and so on are delivered to the controller/action equally. However, both the length and the value have changed when you transferred the zip file. We tested it by changing the extension, but it didn't affect it, and we expect it to be converted to some conditions in the file being transferred. The API gateway proxy was used.

### Expected Behavior

When I send the zip file, I hope the binary value received from the local server and aws lambda is the same.

### Current Behavior

no error, no logs in this action. just binary data is malformed.

### Reproduction Steps

1. that is action in controller, it returns size, md5hash of received form data.

```
    static async Task<byte[]> GetBytesAsync(IFormFile file)
    {
        var bytes = new byte[(int)file.Length];
        using var stream = file.OpenReadStream();

        await stream.ReadAsync(bytes, 0, bytes.Length);
        Console.WriteLine($"{file.Name} >> {file.FileName} size : {bytes.Length}, bytes: {Convert.ToBase64String(bytes)}");

        return bytes;
    }
    [HttpPost("echo")]
    [Consumes("multipart/form-data")]
    public async Task<dynamic> EchoPostFilesAsync([FromForm] IFormFile zip)
    {
        var bytes = await GetBytesAsync(zip);
        return new
        {
            size = bytes.Length,
            md5 = Convert.ToBase64String( md5.ComputeHash(bytes)),
            text = encoding.GetString(bytes)
        };
    }
```

3. when post abc123.txt then it returns same binary value
4. create abc123.zip by abc123.txt.
5. when post asc123.zip then it returns not same binary value, and more bigger size on lambda runtime

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.Hosting 1.3.1

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10, .net6 web api runtime

**Comment by ashishdhingra** [comment]
Hi @Newp,

Good morning.

Thanks for raising the issue. Could you please confirm if the ZIP file is corrupted at the destination? Although I'm not sure, the binary content during transmission might be `Base64` encoded over HTTP/HTTPS, this might report the different size and MD5 hash than expected source value.

Thanks,
Ashish
