### ISSUE TITLE
ILambdaContext's ILambdaLogger Interface methods for logging Log or LogLine doesn't append datetimestamp and awsRequestId to the log messages

### ISSUE THREAD

**Issue by vellozzi** [aws/aws-lambda-dotnet#137]
(copied from https://github.com/aws/aws-sdk-net/issues/695)

## Expected Behavior
Log statements should append datetimestamp and awsrequestId in front which can used for tracking purpose in cloudwatch logs
## Possible Solution
I've implemented an extension method which appends the datetime and awsrequestID for my lambda solution
Current Log methods can utilize the similar approach, this works in node sdk and python sdk by default, would be nice to have the feature by default in .net sdk as well
## Steps to Reproduce (for bugs)
write a simple lambda function and log few statements using ILambdacontext logger Log method.
check in cloud watch that these log messages dont have a tracking id.
write a simple lambda function with node or python the default log statements append the awsrequestId
## Context
was difficult to track log message from cloud watch stream, and create elastic search kibana reports based on timestamp
## Your Environment

* Operating System and version: windows
* Visual Studio version: 2015
* Targeted .NET platform: .NETCore 1.1.0

## .NET Core Info

* .NET Core version used for development: 1.1.0
* .NET Core version installed in the environment where application runs: 1.1.0
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by gokarnm** [comment]
Hi @premgv, I agree the log statements using  _ILambdacontext.Logger_ are not consistent with other runtimes. We cannot change this now as we might break customers depending on the existing format.
We'll address this the next iteration of .NET Core support in Lambda.

**Comment by normj** [comment]
Marking this as an enhancement to remind us to take a look at this for the next .NET Core runtime where we could potential make this change.

**Comment by ashishdhingra** [comment]
@vellozzi This appears to be fixed in latest version. Closing this issue. Please reopen in case issue still exists.
