### ISSUE TITLE
Inconsistent class name for Simple S3 function blueprint

### ISSUE THREAD

**Issue by shruti0085** [aws/aws-lambda-dotnet#1377]
### Describe the bug

Simple S3 function blueprint produces a class called `Functions` in the Lambda project whereas most other blueprints produce a class called `Function` which is used to produce/determine the Function handler. Eg. the function handler produced in aws-lambda-tools-defaults.json for a project called AWSLambdaActionUpload is:
`"function-handler" : "AWSLambdaActionUpload::AWSLambdaActionUpload.Function::FunctionHandler"`.
This causes a failure when the Simple S3 function is invoked using the `S3:Put` sample example request because the class name is incorrect.

Related issue:
[AWS Toolkit for Visual Studio](https://github.com/aws/aws-toolkit-visual-studio/issues/304) had a bug report filed for a typo in Simple S3 lambda function handler. 

Workaround:
Redeploying with the function handler set to `AWSLambdaActionUpload::AWSLambdaActionUpload.Functions::FunctionHandler` works as expected.

### Expected Behavior

The class name should be `Function.cs` and function handler should be `"function-handler" : "AWSLambdaActionUpload::AWSLambdaActionUpload.Function::FunctionHandler"` for the Simple S3 function blueprint.

### Current Behavior

Simple S3 function invoked using the `S3:Put` sample request fails with errors due to incorrect function handler.

### Reproduction Steps

* Deploy Simple S3 function with the pre-populated function handler and invoke it using S3 Put request template where it throws an error

* Redeploy after correcting the function handler to have `Functions` and that should work successfully

### Possible Solution

Rename class to `Function.cs` in the blueprint

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.100.27

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Reproducible using the current latest version `6.8.0` of lambda templates (could be installed using `dotnet new -i Amazon.Lambda.Templates`). The class and namespace used by simple SNS function blueprint is correct (for example). 

- For Simple S3 function, file name was `Functions.cs` but the class name was corrected during cleanup work in commit https://github.com/aws/aws-lambda-dotnet/commit/b72a1c1dba6e2d1cc1c7d6a8a7d2501f02f5235b; however, [aws-lambda-tools-defaults.json](https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/vs2022/SimpleS3Function/template/src/BlueprintBaseName.1/aws-lambda-tools-defaults.json) was not updated in the process.
- For Simple SNS/SQS Function blueprint, the class is `Function` and file name is `Function.cs`. So may be we could follow same conventions for Simple S3 function.

Needs review with the team.

**Comment by ashishdhingra** [comment]
This appears to be fixed in [Amazon.Lambda.Templates 6.8.1](https://www.nuget.org/packages/Amazon.Lambda.Templates/6.8.1).
