### ISSUE TITLE
Using [JsonRequired] attribute on a dynamic type throws JsonSerializationException when returning from Lambda Function

### ISSUE THREAD

**Issue by jonathann92** [aws/aws-lambda-dotnet#139]
Hi I have a class with a dynamic property and I put the [JsonRequired] Attribute on top of it. When the lambda tries to return it is throwing an error. However when I remove the [JsonRequired] on the dynamic object it does not throw an error. I am able to use JsonConvert.SerializeObject(person, settings); in another part of my code before calling the lambda.

Here's my class:

```
public class Person
    {
        [JsonRequired]
        public string Name { get; set; }

        [JsonRequired]
        public int Age { get; set; }

        [JsonRequired]
        public dynamic Stuff { get; set; }
    }
```

Here's the error:

```
{
  "errorType": "JsonSerializationException",
  "errorMessage": "Cannot write a null value for property 'Stuff'. Property requires a value. Path ''.",
  "stackTrace": [
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)",
    "at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)",
    "at Amazon.Lambda.Serialization.Json.JsonSerializer.Serialize[T](T response, Stream responseStream)",
    "at lambda_method(Closure , Stream , Stream , ContextInfo )"
  ]
}
```

**Comment by normj** [comment]
I'm not able to reproduce the error. Can add the environment variable `LAMBDA_NET_SERIALIZER_DEBUG` to the function configuration with a value of `true`. That will cause the original request to be written to the log file before serialization. Once it is written there can you add the request to the issue?

Also make sure you are using version 1.1.0 of the Amazon.Lambda.Serialization.Json package.

**Comment by jonathann92** [comment]
Hi sorry I was tracking the bug down and I found that somewhere along the process the dynamic property was being set to null. Thanks for your help though
