### ISSUE TITLE
Referencing other projects breaks AWS Lambda Test Tool

### ISSUE THREAD

**Issue by nathanvj** [aws/aws-lambda-dotnet#1398]
### Describe the bug

Sorry I was quite busy and only just got the time to create an example repository.
My [previous issue](https://github.com/aws/aws-lambda-dotnet/issues/1371) got closed, so I decided to create a new one.

So to summarize, the following exception is thrown when I reference another project from my Lambda project:
```
FileNotFoundException: Could not load file or assembly 'LambdaTestToolError.Lambda, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

I would be very grateful if someone could take a look. The example repository can be found here:
[https://github.com/nathanvj/LambdaTestToolError](https://github.com/nathanvj/LambdaTestToolError)

Kind regards

### Expected Behavior

Be able to reference other projects from my Lambda project without a problem.

### Current Behavior

Whenever I add a project reference, the lambda test tool breaks. Note that the function works if I publish to AWS and do a test run from there, but I want to be able to use the Mock Lambda Test Tool to debug.

### Reproduction Steps

Example repo:
[https://github.com/nathanvj/LambdaTestToolError](https://github.com/nathanvj/LambdaTestToolError)

1. Clone
2. Open project
3. Run Mock Lambda Test Tool

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.1.0
Amazon.Lambda.Serialization.SystemTextJson 2.3.0

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Reproducible using customer's code.

**Comment by ashishdhingra** [comment]
This could be duplicate of https://github.com/aws/aws-lambda-dotnet/issues/1235.

**Comment by nathanvj** [comment]
Seems indeed to be the same issue (apologies), and the provided workaround (deleting the .deps.json file) works fine for now but is pretty annoying to constantly do during development.

**Comment by ashishdhingra** [comment]
@nathanvj Could you please verify if using the latest version `0.14.0` of Lambda Test tool fixes the issue reported here.

**Comment by nathanvj** [comment]
Seems like this is fixed! Great work 👍🏻 

However if multiple projects contain a `aws-lambda-tools-defaults.json` file, only the functions defined in one of them are being shown in the tool - and only one of them can be found in `bin` folder. Is this expected behavior? Is there a way I can at least select which `aws-lambda-tools-defaults.json` file to use?

My use case is:
I have an .NET API deployed on AWS Lambda with AWS Gateway, and a separate project containing some Lambda functions that mainly contain background tasks.

Project structure:
- `MyApp.API`
  - Controllers
  - aws-lambda-tools-defaults.json
- `MyApp.Lambda`
  - Functions
  - aws-lambda-tools-defaults.json
  - launchSettings.json

`launchSettings.json` defined in `MyApp.Lambda`:
```
{
  "profiles": {
    "MyApp.Lambda": {
      "commandName": "Executable",
      "executablePath": "%USERPROFILE%\\.dotnet\\tools\\dotnet-lambda-test-tool-6.0.exe",
      "commandLineArgs": "--port 5050",
      "workingDirectory": ".\\bin\\$(Configuration)\\net6.0",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Mock Lambda Test Tool": {
      "commandName": "Executable",
      "executablePath": "%USERPROFILE%\\.dotnet\\tools\\dotnet-lambda-test-tool-6.0.exe",
      "commandLineArgs": "--port 5050",
      "workingDirectory": ".\\bin\\$(Configuration)\\net6.0"
    }
  }
}
````
