### ISSUE TITLE
LambdaValidationException when invoking Annotation Lambda

### ISSUE THREAD

**Issue by vezaynk** [aws/aws-lambda-dotnet#1399]
### Describe the bug

I am trying out the [.NET Annotations Lambda Framework (Preview)](https://aws.amazon.com/blogs/developer/introducing-net-annotations-lambda-framework-preview/) and am having issues using it.

I deploy:

```
dotnet lambda deploy-function
```

And then I invoke via lambda url and get an internal error. When checking cloudwatch logs I see this:

```
Amazon.Lambda.RuntimeSupport.ExceptionHandling.LambdaValidationException: Could not find the specified handler assembly with the file name 'LambdaTest, Culture=neutral, PublicKeyToken=null'. The assembly should be located in the root of your uploaded .zip file.
```

Am I deploying it wrong?

### Expected Behavior

Should return a method result

### Current Behavior

Results 404

### Reproduction Steps

Generate from template `serverless.Annotations`, deploy using `dotnet lambda deploy-function`.

### AWS .NET SDK and/or Package version used

Only the template

### Targeted .NET Platform

Dotnet6

### Operating System and version

Linux

**Comment by ashishdhingra** [comment]
@vezaynk Thanks for opening the issue. As @jeastham1993 mentioned, please try using `dotnet lambda deploy-serverless`.

**Comment by vezaynk** [comment]
It works! Thank you!
