### ISSUE TITLE
LambdaException after Deployment

### ISSUE THREAD

**Issue by pchachoo** [aws/aws-lambda-dotnet#140]
I'm using VS Professional 2017 Version 15.2 to deploy an ASP.NET Core Web API to AWS Lambda. My application works exactly as expected when I run it locally, but gives me a LambdaException when I deploy it. I have the right IAM role and CloudWatch access set up. 
I don't have any of the dependencies that might be causing the issue mentioned here:

https://forums.aws.amazon.com/thread.jspa?messageID=758195

The solution suggested in issue #97 is not possible for me. #93 also does not work as PreserveCompilationContext has always been false for my project.

I was initially targeting netcoreapp1.1 but have since downgraded to netcoreapp1.0 and forced it to use netstandard1.6.0 instead of 1.6.1 as per a suggested solution in #124 but that didn't change the error I get:

```

> An exception was thrown when the constructor for type 'aws.lambda.LambdaFunction' was invoked. Check inner exception for more details.: LambdaException at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) at System.RuntimeType.CreateInstanceSlow(Boolean publicO
> An exception was thrown when the constructor for type 'aws.lambda.LambdaFunction' was invoked. Check inner exception for more details.: LambdaException
> 
> 
> at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
> at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
> at System.Activator.CreateInstance(Type type, Boolean nonPublic)
> at System.Activator.CreateInstance(Type type)
> Exception has been thrown by the target of an invocation.: TargetInvocationException
> at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
> at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
> at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
> at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
> Native image cannot be loaded multiple times: FileLoadException
> at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
> at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)
> at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
> at aws.lambda.Startup.ConfigureServices(IServiceCollection services)

```

I'm very new to Lambda, so if anyone can help, I'd appreciate it a lot. What am I missing here?

**Comment by normj** [comment]
Would it be possible to add to the issue the contents of your csproj file?

**Comment by pchachoo** [comment]
Of course, this is what it looks like:

> <Project Sdk="Microsoft.NET.Sdk.Web">
>   <PropertyGroup>
>     <TargetFramework>netcoreapp1.0</TargetFramework>
>     <PreserveCompilationContext>false</PreserveCompilationContext>
>   </PropertyGroup>
>   <ItemGroup>
>     <Folder Include="wwwroot\" />
>   </ItemGroup>
>   <ItemGroup>
>     <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.0" />
>     <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.1" />
>     <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.1" />
>     <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.1" />
>     <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
>     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />  
>     <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.0" /> 
>     <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.0" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.0" />
>     <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
>     <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.0" />
>     <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.0.3" />
>     <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
>     <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
>     <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.1.0" />
>     <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
>     <PackageReference Include="NETStandard.Library" Version="1.6.0" />
>     
>   </ItemGroup>
>   <ItemGroup>
>     <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0" />
>     <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.6.0" />
>   </ItemGroup>
> </Project>

**Comment by pchachoo** [comment]
Of course, here it is:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />  <!--1.1.2-->
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.0" /> 
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.0.3" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
    <PackageReference Include="NETStandard.Library" Version="1.6.0" />
    
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0" />
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.6.0" />
  </ItemGroup>
</Project>
```

**Comment by normj** [comment]
The Microsoft packages that have a version number of 1.1.x depend on .NET Core 1.1. So when we invoke `dotnet publish` to prepare the package it will pull in .NET Core 1.1 dependencies that will fail. For each of those packages can you change the version to the latest 1.0.x version. For example Microsoft.EntityFrameworkCore's latest .NET Core 1.0 version is `1.0.4`.

**Comment by pchachoo** [comment]
I tried using older versions of the Microsoft packages but unfortunately am still getting the same error message in the CloudWatch logs. Also, on a related note, is there an easier way to know which version should be used with .netcoreapp1.0 than scanning the dependencies of every package on NuGet Gallery? 

This is what the updated .csproj file contains:

> 
> <Project Sdk="Microsoft.NET.Sdk.Web">
>   <PropertyGroup>
>     <TargetFramework>netcoreapp1.0</TargetFramework>
>     <PreserveCompilationContext>false</PreserveCompilationContext>
>   </PropertyGroup>
>   <ItemGroup>
>     <Folder Include="wwwroot\" />
>   </ItemGroup>
>   <ItemGroup>
>     <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.0" />
>     <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.1" />
>     <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.1" />
>     <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.1" />
>     <PackageReference Include="Microsoft.EntityFrameworkCore" Version="1.0.4" />
>     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.4" />  
>     <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.0" /> 
>     <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.0" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.0" />
>     <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.1" />
>     <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.0" />
>     <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.0.3" />
>     <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
>     <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.0.1" />
>     <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.0.1" />
>     <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
>     <PackageReference Include="NETStandard.Library" Version="1.6.0" />
>     
>   </ItemGroup>
>   <ItemGroup>
>     <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0" />
>     <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.4.0" />
>   </ItemGroup>
> </Project>

**Comment by pchachoo** [comment]
Turns out the issue was with how the database was being accessed. It couldn't initialize the DB context and set up the database, so it kept crashing. DBInitializer was called in Configure() and services.AddDbContext() in ConfigureServices() in Startup.cs, which is where the error originates. 

Downgrading the packages was necessary and definitely helped, thank you!

**Comment by normj** [comment]
Great! Glad you figured out your issue.
