### ISSUE TITLE
JsonException when deserialising ECSTaskStateChangeEvent

### ISSUE THREAD

**Issue by prashant-dealx** [aws/aws-lambda-dotnet#1406]
### Describe the bug

If a lambda function is set to trigger on ECSTaskStateChangeEvent, we run into the following exception if environment variables are set on the Task Definition.
![image](https://user-images.githubusercontent.com/99950669/210717755-0a6dd5b6-3661-4bff-be54-44a283cfa0be.png)

### Expected Behavior

Expected output:
![image](https://user-images.githubusercontent.com/99950669/210717457-67bd0e51-09fe-4e18-91ca-078408be9b04.png)

The above output is what my lambda function is set to do

### Current Behavior

Output when environment variables are set on task:
![image](https://user-images.githubusercontent.com/99950669/210717755-0a6dd5b6-3661-4bff-be54-44a283cfa0be.png)

Exception:
![image](https://user-images.githubusercontent.com/99950669/210717264-b403a22b-bc5f-4885-bbdb-03edb39f3f7b.png)

Exception Text File
[Exception.txt](https://github.com/aws/aws-lambda-dotnet/files/10349888/Exception.txt)

### Reproduction Steps

Create a lambda function with ECSTaskStateChangeEvent input:
![image](https://user-images.githubusercontent.com/99950669/210718666-ada933cd-a4da-4213-82b4-38f16e6cf924.png)

Run the function with environment variables in the supplied input: 
[reproduction.txt](https://github.com/aws/aws-lambda-dotnet/files/10349955/reproduction.txt)

An exception should be raised.
![image](https://user-images.githubusercontent.com/99950669/210717755-0a6dd5b6-3661-4bff-be54-44a283cfa0be.png)

### Possible Solution

Issue occurs due to mismatch between supplied JSON from the ECSTaskStateChangeEvent input and ContainerOverride class.
Environment variables are a list of object with **name**  and **value** as properties. In the Container override class, it is defined as a List of **KeyValuePair**.
https://github.com/aws/aws-lambda-dotnet/blob/d774b02f4c89b81d8ba959478d8f6b73c6b35fc4/Libraries/src/Amazon.Lambda.CloudWatchEvents/ECSEvents/ContainerOverride.cs#L30

 The properties of KeyValuePay are **Key** and **Value** which **DO NOT** correspond to the supplied properties, i.e **name**  and **value**.

To resolve the issue, I created an **EnvironmentVariable** class which contains **name**  and **value** as properties and then replaces the List of KeyValuePair with a list of EnvironmentVariable. This succesfully resolved the issue.
![CloudWatchEventsChanges](https://user-images.githubusercontent.com/99950669/210720393-a91f593a-e911-44f7-84e4-997620f74108.png)

### AWS .NET SDK and/or Package version used

Amazon.Lambda.CloudWatchEvents 4.0.0
Amazon.Lambda.Core 2.1.0
Amazon.Lambda.Serialization.SystemTextJson 2.3.0

### Targeted .NET Platform

.Net 6.0

### Operating System and version

Linux

**Comment by ashishdhingra** [comment]
The fix has been released in [Amazon.Lambda.CloudWatchEvents 4.0.1](https://www.nuget.org/packages/Amazon.Lambda.CloudWatchEvents/4.0.1)
