### ISSUE TITLE
Suddenly cannot publish

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#141]
Hmm, something changed July 24 2017 or July 25.

When I try to publish now I get the following:

Error: Project is referencing NETStandard.Library version 1.6.1. Max version supported by netcoreapp1.0 is 1.6.0.
Error: NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1.
Error: Check the following dependencies for versions compatible with netcoreapp1.0:
Error: 	amazon.lambda.apigatewayevents : 1.1.0
Error: 	amazon.lambda.aspnetcoreserver : 0.10.1-preview1
Error: 	amazon.lambda.serialization.json : 1.1.0
Error: 	microsoft.aspnetcore : 1.0.3
Error: 	microsoft.visualstudio.web.codegeneration : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.core : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.entityframeworkcore : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.templating : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.utils : 1.0.1
Error: 	microsoft.visualstudio.web.codegenerators.mvc : 1.0.1
Error: 	nuget.frameworks : 3.5.0

I understand the message but I cannot find anything targettng NETStandard.Library version 1.6.1.

References are:

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.3" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.1-preview1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.2" />
  </ItemGroup>

Anyone know what is going on?

Thanks,
Dave

**Comment by genifycom** [comment]
Seems to be something with Visual Studio 2017. Recreated the project from scratch and it is now fine.

**Comment by normj** [comment]
microsoft.visualstudio.web.codegeneration references NETStandard.Library 1.6.1

https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration/1.0.1
