### ISSUE TITLE
Downloading an Excel File from DotNet Lambda Serverless gives corrupted file

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#1419]
### Describe the bug

Same situation as https://stackoverflow.com/questions/63365410/aws-serverless-excel-download

Simple AWS Serverless API that returns an Excel binary.

```
     public IActionResult Test()
        {
            var memoryStream = ExcelGenerator.GetExcelClosedXml();
            return File(memoryStream, contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileDownloadName: "aws_items.xlsx");
        }
```

Since this is Serverless, it will be returning via the API Gateway.

In the LambdaEntryPoint Init method code I have (as per Normj's suggestion):

`            RegisterResponseContentEncodingForContentEncoding("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ResponseContentEncoding.Base64);
`

In the API Gateway I have binary media types set like in this post https://github.com/ClosedXML/ClosedXML/issues/1283

Calling this API locally from Postman I get a Content-Length of 6285
The file is valid:
[local_items.xlsx](https://github.com/aws/aws-lambda-dotnet/files/10505789/local_items.xlsx)

Calling this API via AWS I get a Content-Length of 9486 and x-amzn-Remapped-Content-Length of 6266
The file is invalid:
[aws_items.xlsx](https://github.com/aws/aws-lambda-dotnet/files/10505792/aws_items.xlsx)

The binaries are not the same (7kb vs 10kb).

https://github.com/ClosedXML/ClosedXML/issues/1283
would indicate that this was working.

Has something changed?

Any help appreciated!

### Expected Behavior

I hope to be able to download a valid Xcel file from AWS Serverless API

### Current Behavior

The download file is corrupted somehow (wrong encoding?)

### Reproduction Steps

Generate a simple Excel file in AWS Serverless API and try to return it to the client.

### Possible Solution

Some documentation on how to do this would be great.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer 7.3.0

### Targeted .NET Platform

.Net 6

### Operating System and version

Windows 11

**Comment by genifycom** [comment]
I tested a different API

`        public IActionResult TestBinary()
        {
            var sevenItems = new byte[] { 0x01, 0x02, 0x03, 0x04, 0x05, 0x20, 0x20 };
            var memoryStream = new MemoryStream();
            memoryStream.Write(sevenItems, 0, sevenItems.Length);
            memoryStream.Seek(0, SeekOrigin.Begin);

            return File(memoryStream, contentType: "application/octet-stream", fileDownloadName: "test.bin");
        }`

and the returned binary is fine from AWS, so it appears to be an issue with Excel.

Perhaps the 

`RegisterResponseContentEncodingForContentEncoding("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ResponseContentEncoding.Base64);`

is not actually working? How can I verify this?

**Comment by ashishdhingra** [comment]
@genifycom What is the actual extension of Excel file you are downloading? Is it `xls` or `xlsx`. The `xls` is a binary format, whereas `xlsx` is an [Office Open XML](https://en.wikipedia.org/wiki/Office_Open_XML) format. You would need to set the content encoding as per source format.

Thanks,
Ashish

**Comment by genifycom** [comment]
I am downloading an xlsx (which is encoded as a zip file internally, so is binary)

The MIME type application/vnd.openxmlformats-officedocument.spreadsheetml.sheet should be for an xlsx as per https://learn.microsoft.com/en-us/previous-versions/office/office-2007-resource-kit/ee309278%28v=office.12%29

**Comment by ashishdhingra** [comment]
> I am downloading an xlsx (which is encoded as a zip file internally, so is binary)
> 
> The MIME type application/vnd.openxmlformats-officedocument.spreadsheetml.sheet should be for an xlsx as per https://learn.microsoft.com/en-us/previous-versions/office/office-2007-resource-kit/ee309278%28v=office.12%29

@genifycom I suspect the ZIP encoding is causing issues with the file size. Is the issue reproducible when you use `xlsx` file without ZIP encoding?

**Comment by genifycom** [comment]
Just to be clear. The Office Open XML is encoded internally as a zip file. This is the way it is delivered.

If you take any xlsx file and rename it to .zip, you will see the internal contents so that is already xlsx

**Comment by genifycom** [comment]
So if I change the API to say

` public IActionResult Test()
        {
            var memoryStream = ExcelGenerator.GetExcelClosedXml();
            return File(memoryStream, contentType: "application/octet-stream", fileDownloadName: "aws_items.xlsx");
        }`

then the Excel file is downloaded correctly. This would indicate that 

`RegisterResponseContentEncodingForContentEncoding("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ResponseContentEncoding.Base64);`

is either not working or being called in the wrong place?

**Comment by genifycom** [comment]
https://stackoverflow.com/questions/57975325/returning-binary-data-from-asp-net-core-mvc-using-serverless-and-aws-api-gatewa

This one may be relevant, so checking it out.

**Comment by genifycom** [comment]
Current workaround is to use contentType: "application/octet-stream" but this causes some issues.

Would like to get it to work with contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

**Comment by ashishdhingra** [comment]
@genifycom Based on my discussion with the team, this doesn't appear to be the Lambda library issue, and appears to be related to some configuration in the API Gateway for returning defined file types. Some reference I found in API Gateway documentation:
- [Working with binary media types for REST APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html)
- [Content type conversions in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-workflow.html)
- [Return binary media from a Lambda proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/lambda-proxy-binary-media.html)

Thanks,
Ashish

**Comment by normj** [comment]
I played around with this and I got it working. From what I can tell you are setting **content-type** to `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` but then calling `RegisterResponseContentEncodingForContentEncoding` which is saying look at the **content-encoding** header to base 64 encode the return data. When I switched to 

```
RegisterResponseContentEncodingForContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ResponseContentEncoding.Base64);
```

Then it worked fine for me. 

For reference here is my CloudFormation template for enabling binary media with API Gateway.
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.",
  "Parameters": {},
  "Conditions": {},
  "Resources": {
    "AspNetCoreApi": {
      "Type": "AWS::Serverless::Api",
      "Properties": {
        "StageName": "Prod",
        "BinaryMediaTypes": [
          "*~1*"
        ]
      }
    },
    "AspNetCoreFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "ReturnExcelTestRegular::ReturnExcelTestRegular.LambdaEntryPoint::FunctionHandlerAsync",
        "Runtime": "dotnet6",
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          "AWSLambda_FullAccess"
        ],
        "Events": {
          "ProxyResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/{proxy+}",
              "Method": "ANY",
              "RestApiId": {
                "Ref": "AspNetCoreApi"
              }
            }
          },
          "RootResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/",
              "Method": "ANY",
              "RestApiId": {
                "Ref": "AspNetCoreApi"
              }
            }
          }
        }
      }
    }
  },
  "Outputs": {
    "ApiURL": {
      "Description": "API endpoint URL for Prod environment",
      "Value": {
        "Fn::Sub": "https://${AspNetCoreApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
      }
    }
  }
}
```

**Comment by genifycom** [comment]
Got it. Thanks Norm that works fine. I didn't realize that I was calling the wrong init method.

Thanks for your help :)
