### ISSUE TITLE
NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#143]
Ok I reported this earlier then closed it, now I have it again.

When I publish to AWS Lambda I now get:

Error: Project is referencing NETStandard.Library version 1.6.1. Max version supported by netcoreapp1.0 is 1.6.0.
Error: NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1.
Error: Check the following dependencies for versions compatible with netcoreapp1.0:
Error: 	amazon.lambda.apigatewayevents : 1.1.0
Error: 	amazon.lambda.aspnetcoreserver : 0.10.2-preview1
Error: 	amazon.lambda.serialization.json : 1.1.0
Error: 	microsoft.aspnetcore : 1.0.5
Error: 	microsoft.visualstudio.web.codegeneration : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.core : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.entityframeworkcore : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.templating : 1.0.1
Error: 	microsoft.visualstudio.web.codegeneration.utils : 1.0.1
Error: 	microsoft.visualstudio.web.codegenerators.mvc : 1.0.1
Error: 	nuget.frameworks : 3.5.0

My references packages are included here:

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.4" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.1" />
  </ItemGroup>

The closest of my references to a NETStandard.Library 1.6.1 is the package Microsoft.AspNetCore.Mvc which shows a dependency of .NETStandard, Version=v1.6

Is one of the lambda packages accidentally referencing .NET Core 1.1?

Thanks

**Comment by PavelSafronov** [comment]
Can you provide your project file?

**Comment by genifycom** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
    
  </PropertyGroup>

  <ItemGroup>
    <None Remove="aws-lambda-tools-defaults.json.old" />
    <None Remove="serverless.template" />
    <None Remove="serverless.template.old" />
  </ItemGroup>

  <ItemGroup>
    
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.4" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.10.2-preview1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.0.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.1.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.1.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.0.1" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.0.11" />
  </ItemGroup>
  
  <ItemGroup>
    
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.5.0" />
  </ItemGroup>
</Project>

**Comment by PavelSafronov** [comment]
Not sure what your message is referring to, I was asking for your project.json or *.csproj file.

**Comment by genifycom** [comment]
Hmmm, weird. I pasted the whole .csproj file and if I click edit I can see it all.
Can you not see it at all?

**Comment by PavelSafronov** [comment]
Seems like GitHub was mangling it. I edited your comment to add ``` tags and that seems to have worked.

**Comment by PavelSafronov** [comment]
Think this is the dependency graph that pulls in `NETStandard.Library 1.6.1`, which is what ultimately our tools identify as problematic:
* Your application references [Microsoft.VisualStudio.Web.CodeGeneration.Design 1.0.1](https://www.nuget.org/packages/microsoft.visualstudio.web.codegeneration.design/1.0.1)
* [Microsoft.VisualStudio.Web.CodeGeneration.Design 1.0.1](https://www.nuget.org/packages/microsoft.visualstudio.web.codegeneration.design/1.0.1) references [Microsoft.VisualStudio.Web.CodeGenerators.Mvc 1.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/1.0.1)
* [Microsoft.VisualStudio.Web.CodeGenerators.Mvc 1.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGenerators.Mvc/1.0.1) references NETStandard.Library 1.6.1

Removing reference to Microsoft.VisualStudio.Web.CodeGeneration.Design allowed me to publish to Lambda.

**Comment by genifycom** [comment]
Wonderful, thanks Pavel.

Interesting that Visual Studio does not show this dependency through Nuget.

Can I run the dependency graph so I can sort out these issues in the future?

Thank you,
Dave

**Comment by PavelSafronov** [comment]
Curious. Not sure how it ended up in the csproj then.
I'm unaware of a tool that shows this information, but agree that it would be helpful.
Is your issue resolved?

**Comment by genifycom** [comment]
Yes thank you 👍
