### ISSUE TITLE
.NET6 Minimal API not serving GUI page

### ISSUE THREAD

**Issue by AdalbertKhoolsaat** [aws/aws-lambda-dotnet#1434]
### Describe the bug

As a demo, I tried deploying a GraphQL API (using HotChocolate) on AWS Lambda, using Minimal API and API Gateway Proxy Integration (REST). 

Functionally, things seem to work fine at the moment. However, the GUI that comes with HotChocolate (Banana Cake Pop) won't properly render. When navigating to the API url it looks like things are loading, but then it stops. 

### Expected Behavior

Another Lambda API using the standard Web API template, same Integration and using the same versions of the HotChocolate packages is able to properly render the GUI right away. 

I expected the Minimal API to do the same.

### Current Behavior

Only after F5'ing between 5~10 times does the page finally appear. 

CloudWatch logging for the Lambda shows successful GET requests for source files (retrieved as chunks). But not all the required chunks are being fetched.

Network tab in Dev Tools shows 500 errors on fetching separate chunks, with one of the response headers being _x-amzn-errortype: InternalServerErrorException_

### Reproduction Steps

Requirements:
- .NET 6 Lambda
- Minimal API template 
- API Gateway Proxy Integration (REST)
- HotChocolate (13.0.2)

Bare minimum of setup in Program.cs should work:
builder.Services
.AddGraphQLServer()
 .AddQueryType<Query>();

&

app.MapGraphQL()

With **Query** as an empty public class. 

### AWS .NET SDK and/or Package version used

<PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.5.0" />		
<PackageReference Include="AWSSDK.SecurityToken" Version="3.7.101.7">
<PackageReference Include="HotChocolate.AspNetCore" Version="13.0.2" />

### Targeted .NET Platform

.NET 6

### Operating System and version

AWS Lambda

**Comment by ashishdhingra** [comment]
Hi @AdalbertKhoolsaat,

Good morning.

Could you please share the following:
- Sample code solution for the scenarios where it works.
- Sample code solution which uses minimal API and doesn't work or has the issue mentioned above.
- Step by step deployment steps, describing special scenarios, if any.

While we would not be able to troubleshoot any issues related to `HotChocolate (13.0.2)`, we could try analyzing any configuration issues.

Thanks,
Ashish

**Comment by armourian** [comment]
getting following issue
Error: executable assembly /var/task/[apiname].dll was not found.
