### ISSUE TITLE
ILambdaInvokeBuilder doesn't exist

### ISSUE THREAD

**Issue by paulomonteirodev** [aws/aws-lambda-dotnet#1458]
### Describe the issue

I was trying follow this guide https://github.com/aws/aws-lambda-dotnet/blob/master/Docs/lambda-annotations-design.md, but I can't use Configure method because ILambdaInvokeBuilder doesn't exist

### Links

https://github.com/aws/aws-lambda-dotnet/blob/master/Docs/lambda-annotations-design.md

**Comment by normj** [comment]
We haven't implemented that part of the design yet. That doc is more of a picture of where we want to get the library and asking for feedback on the design.

**Comment by paulomonteirodev** [comment]
I would like to store all configs from APIGatewayProxyRequest.StageVariables before to use DI, because my database secret manager config is configured in the ApiGateway StageVariables. Is there any way to do that?

**Comment by ashishdhingra** [comment]
> I would like to store all configs from APIGatewayProxyRequest.StageVariables before to use DI, because my database secret manager config is configured in the ApiGateway StageVariables. Is there any way to do that?

@paulomonteirodev Thanks for the inputs. Please help log your requirement on https://github.com/aws/aws-lambda-dotnet/pull/961.
