### ISSUE TITLE
Make StatusCode and Body available in IHttpResult/HttpResult

### ISSUE THREAD

**Issue by kabaluk** [aws/aws-lambda-dotnet#1468]
### Describe the feature

Make StatusCode and Body available in IHttpResult/HttpResult,
 this would make unit testing lambdas returning IHttpResults a lot simpler.

### Use Case

A lot of Api's return either 200 OK or 400 BadRequest.
There is no easy way to unit test if the result of a Annotation Lambda is returning the correct httpStatus and or body

### Proposed Solution

Make Status code and body available on IHttpResult and/or HttpResult.
The fields are already mandatory in HttpResult, no Reason for them to not be public (or at least public get)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Annotations 0.13.0.0

### Targeted .NET Platform

.NET6

### Operating System and version

ALL SUPPORTED

**Comment by ashishdhingra** [comment]
@kabaluk Good afternoon. Thanks for submitting feature request. The commit https://github.com/aws/aws-lambda-dotnet/commit/e44e48d2c3539c97c26a4c04d1cb3907eb3185fb added support for `5XX` status codes to Annotations framework. Are you referring to add other status codes? Feel free to contribute PR which could be reviewed by the team.

Thanks,
Ashish
