### ISSUE TITLE
Scheduled events

### ISSUE THREAD

**Issue by tarurar** [aws/aws-lambda-dotnet#147]
Which package can be used to work with scheduled cloud watch events?

**Comment by Kralizek** [comment]
There is no package supporting it.

#88 here I suggest a class that supports some of the information sent from CloudWatch.
#16 here there is a discussion where @normj shows possibilities and problems that need to be solved to be able to support the whole message.

**Comment by normj** [comment]
Closing as duplicate of https://github.com/aws/aws-lambda-dotnet/issues/16

I understand this would be really useful, I just don't have a way yet to keep all the different possible event types coming from CloudWatch events updated all the time.
