### ISSUE TITLE
Latest AWS Lambda dotnet image is only for arm

### ISSUE THREAD

**Issue by lionel1704** [aws/aws-lambda-dotnet#1471]
### Describe the bug

The latest image uploaded today is for ARM and not AMD64
![image](https://user-images.githubusercontent.com/20953719/228231119-f3e6680c-4203-4085-8a94-49c1fe879c70.png)

### Expected Behavior

The last version had separate images for arm and amd64. Is this being migrated to use a single multi-platform image?

### Current Behavior

The latest image seems to support only arm64.

### Reproduction Steps

Build a docker image that uses the latest base image:
```
FROM public.ecr.aws/lambda/dotnet:7
```

The image always targets arm64

### AWS .NET SDK and/or Package version used

N/A

### Targeted .NET Platform

.NET 7

### Operating System and version

Amazon Linux

**Comment by normj** [comment]
@arturomonge @lionel1704 Acknowledge this is an unintended breaking behavior. Previously we only had the `amd64` image and as part of this month's patch we added an `arm64`. That was not intended to replace the `amd64` and `public.ecr.aws/lambda/dotnet:7` should have been a multi arch image similar to how we did .NET 6.

I'm tracking down what went wrong and will try and this fixed up as soon as possible.

**Comment by normj** [comment]
New images have been pushed fixing the issue. The `public.ecr.aws/lambda/dotnet:7` tag is now correctly a multi arch image so it will work for either `amd64` or `arm64`.

Sorry for this mistake and thanks for your patience's.

**Comment by ashishdhingra** [comment]
@lionel1704  Please verify this at your end if this is fixed and confirm if we could close this issue.

**Comment by lionel1704** [comment]
This works as expected now. Thank you!
