### ISSUE TITLE
(104): Connection reset by peer

### ISSUE THREAD

**Issue by wahmedswl** [aws/aws-lambda-dotnet#1474]
### Describe the bug

We are seeing internment failures on our Network Calls (Http + SOAP/WCF) on .Net Core 3.1. The invoked endpoints/services work fine and throws sometimes as well. We are getting following error
```
System.AggregateException: One or more errors occurred. (Unable to read data from the transport connection: Connection reset by peer.)
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
```

### Expected Behavior

We shouldn't see this error and network calls should succeed without issue.

### Current Behavior

```
System.AggregateException: One or more errors occurred. (Unable to read data from the transport connection: Connection reset by peer.)
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
```

### Reproduction Steps

We are getting these inside Lambda on Network Calls. These are invoked via Step Function at Hourly interval and around 50/60+  API calls at each run. 

### AWS .NET SDK and/or Package version used

```<PackageReference Include="AWSSDK.Core" Version="3.7.2.2" />```

### Targeted .NET Platform

.Net Core 3.1

### Operating System and version

Lambda

**Comment by normj** [comment]
Have you been able try deploying the function using .NET 6? .NET Core 3.1 is out of support from Microsoft and this week entered the first phase of deprecation on Lambda.

**Comment by wahmedswl** [comment]
@normj Nope, there are multiple api endpoints. Initially we thought that it's 3rd party vendor but later we saw happening on multiple vendors. That's why we raised this issue. 
@ashishdhingra Yes, this is not related to AWS Sdk but 3rd party api invoke via Lambda.

**Comment by normj** [comment]
My guess is the third party library is maintaining socket level connection and the library/third party service doesn't like when Lambda freezes the compute container between invokes. Maybe the service is expecting keep alive messages to be sent while function is frozen. Is it possible to create the third party client for each invoke or catch the error and recreate the client if you get this error?

**Comment by wahmedswl** [comment]
@normj Client is not cached/kept and created on every network call.

**Comment by ashishdhingra** [comment]
@wahmedswl Please help share the information mentioned in https://github.com/aws/aws-lambda-dotnet/issues/1474#issuecomment-1494613781 to investigate further.

Thanks,
Ashish
