### ISSUE TITLE
Outdated documentation for configuring .NET 3.1 Mock AWS Lambda Test Tool on Mac

### ISSUE THREAD

**Issue by goosewin** [aws/aws-lambda-dotnet#1475]
### Describe the issue

# Issue

I'm reporting an issue with the documentation for configuring the .NET 3.1 Mock AWS Lambda Test Tool on Mac. The current guide provides instructions for configuring Visual Studio for Mac to use the `Amazon.Lambda.TestTool.WebTester31.dll` entry assembly, which is no longer available on the latest versions of Amazon.Lambda.TestTool-3.1 NuGet package.

After some investigation, I found that this entry assembly is only available on older versions of the package (e.g., version 0.10.0). Therefore, I believe that the guide is outdated and needs to be updated to reflect the changes in the latest versions of the package.

I suggest that the documentation be updated to provide alternative instructions for configuring the tool with the latest package versions. This could include identifying the new entry assembly or providing updated steps for configuring Visual Studio for Mac to use the latest package version.

# Environment

- OS Info: MacOS 13.1
- Target platform: .NET Core 3.1

### Links

Lambda Test Tool - Guide for Mac:
[https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-visual-studio-for-mac](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-visual-studio-for-mac)

**Comment by ashishdhingra** [comment]
Agreed that this needs to be updated. There is a below note for JetBrains Rider. Perhaps similar note needs to be added for Mac (or common note).
```
Note: if using the .NET Core Mock Lambda Test Tool 3.1 version 0.11.0, you will need to use the BlazorTester DLL (Amazon.Lambda.TestTool.BlazorTester.dll) and set the Exe path to the full path of the BlazorTester DLL.
```

**Comment by ashishdhingra** [comment]
[Lambda Test Tool Readme](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool) has been updated.
