### ISSUE TITLE
Can you publish lambda versions?

### ISSUE THREAD

**Issue by sloanyb** [aws/aws-lambda-dotnet#148]
Hi, I've been investigating with the `-fp true` switch of `deploy function` and sure enough it creates a version 1 as well as a `$latest`, but I cannot find any way to make either `dotnet lambda deploy-function` or `dotnet lambda deploy-serverless` create new versions of the lambda on each deploy.

Is there some way to actually get new version numbers * for each deploy ** so that function versioning can be used instead of it just always updating `$latest`?

\* Ideally I can specify my own version number so they're consistent with TeamCity, but auto incrementing from 0 would be OK

** Ideally of `deploy serverless` but if it's just `deploy function` that's OK

**Comment by normj** [comment]
Lambda doesn't allow you to specify the version number when you publish. The `-fp` argument maps to the `Publish` property to the [UpdateFunctionCode](http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html) service operation.

**Comment by genifycom** [comment]
Can we do a feature request on this one?

For example if one is doing a CDN Viewer Request function (via Lambda@Edge), then you need versioning.
It is also becoming more important to allow publish and test in place before promoting to go live. It is just way to hard to have a completely separate Dev environment.

So this way we could publish to a version. Try that version in place first. Then indicate to Lambda@Edge (for example) that this version can replace the current live one.

**Comment by normj** [comment]
@genifycom I think what you want is [Lambda Alias](https://docs.aws.amazon.com/lambda/latest/dg/aliases-intro.html). You can't control the version number Lambda creates but you can have a dev and prod alias that point to specific Lambda versions.

You could have a workflow where new revisions are pointed to by the dev alias and once you are happy with that version update the prod alias to point the version the dev alias was pointing to.

A possible feature the .NET tooling could have is when we execute `deploy-function` it could take in an alias. If set then deploy Lambda function with publish set to true causing a new version. Then update/create the provided Alias to point to the new version. If you think that is useful then I suggest opening a new feature request for that feature.
