### ISSUE TITLE
Update libc6 package to upgrade libstc++ (GLIB) binary to 3.4.26 from 3.4.24.

### ISSUE THREAD

**Issue by zeusongit** [aws/aws-lambda-dotnet#1483]
### Describe the feature

The base images for lambda still have an older version of libc6, is it possible for you to update the base image with the latest version?
Is this something that is planned for future releases? Can you tell us about the timeline?

### Use Case

We can use binaries build on the latest libc6 version.

### Proposed Solution

Update libc6 package to upgrade libstc++ (GLIB) binary to 3.4.26 from 3.4.24.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

NA

### Targeted .NET Platform

.NET6

### Operating System and version

AL

**Comment by ashishdhingra** [comment]
Needs review with the team to update the libstc++ (GLIB) binary version.

**Comment by ashishdhingra** [comment]
P86597992

**Comment by ashishdhingra** [comment]
@zeusongit We have opened an internal ticket with Lambda team notifying them about this request. Closing this ticket. I would post update here that I receive from Lambda team, if any.
