### ISSUE TITLE
Illegal characters in path exception

### ISSUE THREAD

**Issue by rudygt** [aws/aws-lambda-dotnet#15]
Hi, 

I stepped into an issue while trying to deploy the empty upper case example 

![error](https://cloud.githubusercontent.com/assets/1120692/21148649/891bfb42-c11e-11e6-9576-7cf17d150e9e.png)

I found that the issue was that my path environment variable contains a quoted string

![path](https://cloud.githubusercontent.com/assets/1120692/21148668/99053514-c11e-11e6-912b-6a7403d136c3.png)

and the Path.Combine method would fail in this piece of code 

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/DotNetCLIWrapper.cs#L226

It took me a while to find out, so It will be nice if we could improve the feedback to the user

let me know if you would take a pull request, maybe we can wrap the call on a try/catch and just print a warning to avoid this blocking the deployment process, as far as I know the quoted strings are valid on the PATH environment variable in windows, I don't now if this could happen also in other platforms.  (I'm using windows 10). 

Thanks.

**Comment by normj** [comment]
Thanks for letting us know. We have the try/catch change queued up and should go out today or tomorrow.

**Comment by normj** [comment]
We just pushed out version 1.11.1.4 of the toolkit that handles quotes in the path.

**Comment by rudygt** [comment]
Thanks!
