### ISSUE TITLE
Lambda ASP.NET Core Minimal API complains about missing 'libhostpolicy.so' library when deployed

### ISSUE THREAD

**Issue by baynezy** [aws/aws-lambda-dotnet#1512]
### Describe the bug

I have created a vanilla project from the *Lambda ASP.NET Core Minimal API* template. I have called it `ProfileAPI`. I have deployed it via Terraform to AWS. The function will not execute successfully.

### Expected Behavior

The function should allow me to execute the `/` route and the `Calculator` routes in the template.

### Current Behavior

Via API GW I get a `500 Internal Server Error`. If I trigger it via the AWS console using the `apigateway-api-proxy` template I get the following error:-

```json
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 899a669f-cbd3-43cb-b06a-24398aea22df Error: Runtime exited with error: exit status 131"
}
```

```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/var/task/'.
Failed to run as a self-contained app.
- The application was run as a self-contained app because '/var/task/ProfileAPI.runtimeconfig.json' did not specify a framework.
- If this should be a framework-dependent app, specify the appropriate framework in '/var/task/ProfileAPI.runtimeconfig.json'.
START RequestId: 899a669f-cbd3-43cb-b06a-24398aea22df Version: $LATEST
RequestId: 899a669f-cbd3-43cb-b06a-24398aea22df Error: Runtime exited with error: exit status 131
Runtime.ExitError
END RequestId: 899a669f-cbd3-43cb-b06a-24398aea22df
REPORT RequestId: 899a669f-cbd3-43cb-b06a-24398aea22df	Duration: 162.41 ms	Billed Duration: 163 ms	Memory Size: 128 MB	Max Memory Used: 3 MB	
```

### Reproduction Steps

1. Create a new project from *Lambda ASP.NET Core Minimal API* template.
2. Publish to AWS with relevant roles and API GW integration
3. Test function

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer.Hosting 1.5.1

### Targeted .NET Platform

net6.0

### Operating System and version

Amazon Lambda

**Comment by ashishdhingra** [comment]
Hi @baynezy,

Good afternoon.

Thanks for reporting the issue. Although I didn't try reproducing it using Terraform, I was unable to reproduce it using `Publish to AWS Lambda` option in Visual Studio, which uses `.NET Deploy Tool` behind the scenes. Kindly note that my project was using `Amazon.Lambda.AspNetCoreServer.Hosting` version `1.6.0`. Could you please check the following:
- Does your `.csproj` file has the element `<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>`? If not, could you please try adding it and test again?
- For your use case, what is the `Acchitecture` in `Runtime settings` for the underlying Lambda function? In my case, it was `x86_64`.
- If possible, please share the sample code solution and deployment steps to reproduce the issue.

Thanks,
Ashish

**Comment by baynezy** [comment]
@ashishdhingra thank you so much for taking the time to look into this. I will answer your questions as best I can.

_Does your .csproj file has the element `<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>`? If not, could you please try adding it and test again?_

It does.

```
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <AWSProjectType>Lambda</AWSProjectType>
        <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <!-- Generate ready to run images during publishing to improvement cold starts. -->
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.5.1" />
    </ItemGroup>
</Project>
```

_For your use case, what is the `architecture` in `Runtime settings` for the underlying Lambda function? In my case, it was `x86_64`._

The same.

_If possible, please share the sample code solution and deployment steps to reproduce the issue._

If you follow the steps in [this repository](https://github.com/baynezy/LambdaIssue) you can replicate the problem.

Much appreciated.

**Comment by baynezy** [comment]
Thanks, @normj - that makes sense. In this instance I had been using my Win10 laptop to build the project.

That explains why using the same Cake script I have successfully built and deployed from an Ubuntu-based GitHub Action. 

I had avoided the `dotnet lambda` tooling because as far as I can tell, it relies on the CDK/serverless framework and I want to standardise on Terraform.

Can I use `dotnet lambda publish` to generate the files I need? Or am I also going to need those other tools?

**Comment by baynezy** [comment]
@normj - based on your help I have made a [change to the Cake script](https://github.com/baynezy/LambdaIssue/commit/60f6915ccedb6fabb7ab1c44d9293e042f8421e1) and that is now working perfectly.

Thanks very much for your patients and help.

**Comment by normj** [comment]
@baynezy Thanks for sharing the solution. Out of curiosity why do you want to `SelfContained` set to `true`? Why not use the version of .NET that is available in the managed runtime and have a smaller deployment bundle?

Also the `Amazon.Lambda.Tools` does not use the CDK. I think you are thinking of the [AWS.Deploy.Tool](https://github.com/aws/aws-dotnet-deploy) which is more for container applications. If you are using `Amazon.Lambda.Tools` for deployment it talks directly to Lambda or CloudFormation depending on your choice. If you just want the deployment bundle then `dotnet lambda package` command is basically a wrapper around the `dotnet publish` command with extra validations and the output is a zip file. It is fine if you don't want to use it I just wanted to make sure it was clear the CDK was not involved and the tool is actually quite light weight.

**Comment by baynezy** [comment]
@normj - sorry I missed this reply. You are correct; that was a mistake on my part. It worked in my reproduction case, but I did need to set it to `false` for my actual deployment.
