### ISSUE TITLE
Wrong parsing of environment variables from aws-lambda-tools-defaults.json

### ISSUE THREAD

**Issue by michelemottini** [aws/aws-lambda-dotnet#1520]
### Describe the bug

The environment variables inside `aws-lambda-tools-defaults.json` are within quotes - e.g. 

```
 . . . 
    "environment-variables"    : "\"key1\"=\"value1\";\"key2\"=\"value2\"; . . . ",
 . . . 
```

but the current code expects them without quotes.

### Expected Behavior

When  `aws-lambda-tools-defaults.json` contains quoted environment variables - e.g. 

```
 . . . 
    "environment-variables"    : "\"key1\"=\"value1\";\"key2\"=\"value2\"; . . . ",
 . . . 
```

the lambda code being executed sees environment variable `key1` with value `value1` etc,

### Current Behavior

When  `aws-lambda-tools-defaults.json` contains quoted environment variables - e.g. 

```
 . . . 
    "environment-variables"    : "\"key1\"=\"value1\";\"key2\"=\"value2\"; . . . ",
 . . . 
```

the lambda code being executed environment sees variable `"key1"` with value `"value1"` etc,

### Reproduction Steps

A function with a body containing only

```
		Console.WriteLine( "key1: {0}", Environment.GetEnvironmentVariable( "key1" ) );
```

should write `key1: value1` when defining the variable `key1` with value `value1` but it does not write any value

### AWS .NET SDK and/or Package version used

AWSSDK.Lambda 3.7.108.1

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10 Enterprise

**Comment by ashishdhingra** [comment]
@michelemottini Good morning. Thanks for opening the issue. If you refer the sample `aws-lambda-tools-defaults.json` at [Basic AWS Lambda Project](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/lambda-creating-project-in-visual-studio.html), the `Information` element within the file clearly mentions that `This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.`. In other words, this file is only used by the AWS Toolkit for Visual Studio tooling or [AWS Extensions for .NET CLI](https://github.com/aws/aws-extensions-for-dotnet-cli) tooling to populate the default values during Lambda function deployment.

For testing purposes, in a Lambda function project, the environment variables set in `aws-lambda-tools-defaults.json` are populated in Visual Studio `Publish to AWS Lambda` wizard settings:
![Screenshot 2023-06-05 at 10 41 46 AM](https://github.com/aws/aws-lambda-dotnet/assets/67916761/ac5fa463-db77-44f7-92df-f3c7439a9d52)

After the function is deployed, these environment variables are set in Lambda function configuration in AWS console:
![Screenshot 2023-06-05 at 10 47 50 AM](https://github.com/aws/aws-lambda-dotnet/assets/67916761/7c80769d-faa6-445d-9cc9-96a62563fac9)

Please confirm if you are trying to debug the Lambda function locally and expecting environment variables set in `aws-lambda-tools-defaults.json` to be read. If yes, then these need to be instead set in `launchsettings.json` (refer https://github.com/aws/aws-lambda-dotnet/issues/583#issuecomment-588492347).

Thanks,
Ashish

**Comment by michelemottini** [comment]
> confirm if you are trying to debug the Lambda function locally and expecting environment variables set in aws-lambda-tools-defaults.json to be read

Yes, that's it

> If yes, then these need to be instead set in launchsettings.json

Thanks, that works

> [aws-lambda-tools-defaults.json] is only used by the AWS Toolkit for Visual Studio tooling or [AWS Extensions for .NET CLI](https://github.com/aws/aws-extensions-for-dotnet-cli) tooling to populate the default values during Lambda function deployment.

This does not appear to be true: when I debug the lambda function locally I can see that the environment variables from `aws-lambda-tools-defaults.json` have actually been read, just with extra quotes - I have this in my `aws-lambda-tools-defaults.json`:

```
    "environment-variables"    : "\"OPENSEARCH_URL\"=\"https://search-os-test-rhfdkfigwnfk4ebvscjlbtiyxq.us-east-1.es.amazonaws.com\""

```

and see also https://github.com/aws/aws-lambda-dotnet/blob/882299b606e0f54df463e95177a8e9b4837bbe85/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/LambdaConfigFile.cs#L23

and this is what I see for the environment variables in the debugger when running the lambda locally:

![image](https://github.com/aws/aws-lambda-dotnet/assets/1046280/f3289312-88ea-4d09-b3c2-f4c182b205bb)

**Comment by ashishdhingra** [comment]
> > [aws-lambda-tools-defaults.json] is only used by the AWS Toolkit for Visual Studio tooling or [AWS Extensions for .NET CLI](https://github.com/aws/aws-extensions-for-dotnet-cli) tooling to populate the default values during Lambda function deployment.
> 
> This does not appear to be true: when I debug the lambda function locally I can see that the environment variables from `aws-lambda-tools-defaults.json` have actually been read, just with extra quotes - I have this in my `aws-lambda-tools-defaults.json`:
> 
> ```
>     "environment-variables"    : "\"OPENSEARCH_URL\"=\"https://search-os-test-rhfdkfigwnfk4ebvscjlbtiyxq.us-east-1.es.amazonaws.com\""
> ```
> 
> and this is what I see for the environment variables in the debugger when running the lambda locally:
> 
> ![image](https://user-images.githubusercontent.com/1046280/243481750-f3289312-88ea-4d09-b3c2-f4c182b205bb.png)
> 
> and see also
> 
> https://github.com/aws/aws-lambda-dotnet/blob/882299b606e0f54df463e95177a8e9b4837bbe85/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/LambdaConfigFile.cs#L23

@michelemottini Ahh, got it. The tool appears to load config files at https://github.com/aws/aws-lambda-dotnet/blob/882299b606e0f54df463e95177a8e9b4837bbe85/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/TestToolStartup.cs#L91 and read environment variables from `aws-lambda-tools-defaults.json` at https://github.com/aws/aws-lambda-dotnet/blob/882299b606e0f54df463e95177a8e9b4837bbe85/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/Runtime/LambdaDefaultsConfigFileParser.cs#L74.

Noticed that when `Publish to AWS Lambda` is used and option to `Save settings to aws-lambda-tools.defaults.json for future deployments.` is selected, it persists the environment variables in this file in the format reported by you.

When running the code in Lambda Test Tool, during debugging, `System.Environment.GetEnvironmentVariables()` lists these variables as below:
```
["\"key1\""]: "\"value1\""
...
["\"key2\""]: "\"value2\""
```
Appears to be an issue. Needs review with the team.

Thanks,
Ashish

**Comment by normj** [comment]
Whoops, sorry about that. I put out a PR to handling parsing with quotes the same as the deployment CLI. https://github.com/aws/aws-lambda-dotnet/pull/1521

**Comment by michelemottini** [comment]
No problem, thanks for the super-quick response @normj @ashishdhingra

**Comment by normj** [comment]
@michelemottini Version 0.13.1 just got released with the PR addressing the quotes. Can you confirm it fixed your issue and if so close the issue?

**Comment by michelemottini** [comment]
Works like a charm, thanks @normj
