### ISSUE TITLE
dotnet lambda deploy-function hangs on `Determining projects to restore...`

### ISSUE THREAD

**Issue by smartshader** [aws/aws-lambda-dotnet#1534]
### Describe the bug

When I run dotnet lambda deploy-function to deploy my application it hangs on `Determining projects to restore...`
Memory consumption start increasing slowly to 50G then the process dies from out of memory error

### Expected Behavior

It should build and deploy my function to aws

### Current Behavior

Amazon Lambda Tools for .NET Core applications (5.7.0)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Found /etc/os-release
Architecture not provided, defaulting to x86_64 for container build image.
Executing publish command
Starting container for native AOT build using build image: public.ecr.aws/sam/build-dotnet7:latest-x86_64.
... invoking 'docker run --name tempLambdaBuildContainer-f0f338eb-4fc0-404e-906a-ce467253d865 --rm --volume "/home/imad/Projects/FLO/EMS.Core":/tmp/source/ -i -u 1000:1000 -e DOTNET_CLI_HOME=/tmp/dotnet -e XDG_DATA_HOME=/tmp/xdg public.ecr.aws/sam/build-dotnet7:latest-x86_64 dotnet publish "/tmp/source/functions/events/EventBrokerState" --output "/tmp/source/functions/events/EventBrokerState/bin/Release/net7.0/publish" --configuration "Release" --framework "net7.0" --self-contained true /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 /p:StripSymbols=true' from directory /home/imad/Projects/FLO/EMS.Core
... docker run: MSBuild version 17.6.1+8ffc3fe3d for .NET
... docker run:   Determining projects to restore...
ERROR: Container build returned 137

### Reproduction Steps

Only happens on linux
My csproj uses Native AOT image
```xml
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AWSProjectType>Lambda</AWSProjectType>
        <AssemblyName>bootstrap</AssemblyName>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PublishAot>true</PublishAot>
        <StripSymbols>true</StripSymbols>
        <TrimMode>partial</TrimMode>
    </PropertyGroup>
```

### Additional Information/Context

cat /etc/os-release
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy

dotnet --info
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  21.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.304/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.410 [/usr/share/dotnet/sdk]
  7.0.304 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### AWS .NET SDK and/or Package version used

Amazon.Lambda.RuntimeSupport 1.8.7
Amazon.Lambda.Core 2.1.0
amazon.lambda.tools 5.7.0

### Targeted .NET Platform

.Net Core 7.0.304-7e794e2806

### Operating System and version

Linux Mint 21.1 Ubuntu jammy

**Comment by bhoradc** [comment]
Hi @smartshader,

Apologies for the long silence here. Below are the steps that I took to reproduce the issue. 

- Launched an EC2 instance using an Ubuntu image (22.04.2 LTS). 
- Installed Dotnet SDK 7.0 and Docker 24.0.4 on the ubuntu instance. 
- Created a NativeAOT project using dotnet lambda template `dotnet new lambda.NativeAOT`
- Build the Lambda deployment package without encountering any issue `dotnet lambda deploy-function`

![image](https://github.com/aws/aws-lambda-dotnet/assets/122290643/6d020d67-c854-4b59-8e4b-4a490e676000)

Is there anything from above steps that I might have missed in reproducing the issue you encountered? Kindly let me know as I am unable to reproduce the memory error.   

Regards, 
Chaitanya

**Comment by smartshader** [comment]
Hi @bhoradc,

I was using Linux Mint Vera on my desktop so I don't know if that configuration had something specific to it. We have moved out from dotnet lambda to golang lambda so I think you can close this issue. 

Regards,
