### ISSUE TITLE
Missing documentation on running AOT lambdas in test tool

### ISSUE THREAD

**Issue by SamuelCox** [aws/aws-lambda-dotnet#1539]
### Describe the issue

As far as I can tell, there is no proper documentation on how to use the lambda test tool for .net 7 AOT

```JSON
{
  "Information": [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
    "dotnet lambda help",
    "All the command line options for the Lambda command can be specified in this file."
  ],
  "profile": "default",
  "region": "eu-west-1",
  "configuration": "Release",
  "function-runtime": "provided.al2",
  "function-memory-size": 256,
  "function-timeout": 30,
  "function-handler": "bootstrap",
  "msbuild-parameters": "--self-contained true"
}
```

```JSON
{
  "profiles": {
    "Mock Lambda Test Tool": {
      "commandName": "Executable",
      "commandLineArgs": "--no-ui --payload payload.json",
      "workingDirectory": ".\\bin\\$(Configuration)\\net7.0",
      "executablePath": "C:\\Users\\%USERNAME%\\.dotnet\\tools\\dotnet-lambda-test-tool-7.0.exe",
      "args": [ "--port 5050" ]

    }
  }
}
```
throws this error:
![image](https://github.com/aws/aws-lambda-dotnet/assets/6514954/3cfa9b0a-40ef-4a95-993c-066782d667d3)

If I listen to the error message (which every amazon sample on line uses "bootstrap" as the handler for aot) then I get this
![image](https://github.com/aws/aws-lambda-dotnet/assets/6514954/4623a085-182d-4cf3-ae11-961a130be622)

Would massively appreciate proper documentation on this and/or a description of what I'm doing wrong

### Links

https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md

**Comment by ashishdhingra** [comment]
@SamuelCox Thanks for reporting the issue. Please refer to https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#testing-executable-assemblies for testing Native AOT Lambda functions. These are compiled as executable assemblies. More information can be found in the test tool documentation available at http://localhost:5050/documentation (this is the endpoint after Test tool is launched).

Please let me know if it helps.

Thanks,
Ashish

**Comment by SamuelCox** [comment]
![image](https://github.com/aws/aws-lambda-dotnet/assets/6514954/d987d710-07bc-4069-bc23-4738da1c043f)
Still doesn't work

**Comment by ashishdhingra** [comment]
> https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#testing-executable-assemblies

@SamuelCox Here are the updated steps working for me:
- Install Lambda Test Tool version 7.0 using command `dotnet tool install -g Amazon.Lambda.TestTool-7.0`.
- Navigate to project's root directory containing `.csproj` file.
- Run `dotnet lambda-test-tool-7.0` to launch Lambda Test Tool.
- As mentioned in Lambda Test Tool 7.0 documentation at http://localhost:5050/documentation, in project's `launchSettings.json`, specify the environment variables either via Visual Studio Debug UI or modifying the `launchSettings.json` manually:
```JSON
{
  "profiles": {
    "LambdaNativeAOT": {
      "commandName": "Project",
      "environmentVariables": {
        "AWS_LAMBDA_RUNTIME_API": "localhost:5050",
        "AWS_PROFILE": "default",
        "AWS_REGION": "us-east-2"
      }
    }
  }
}
```
- Setup breakpoint in Lambda Function handler.
- Debug project using Visual Studio.
- In Lambda Test Tool's `Executable Assembly` page, queue the event (for project created using Native AOT Visual Studio AWS template, the handler converts input string to upper case and returns it. Hence we may pass double quoted string, e.g. `"Hello World"` from test tool)

Breakpoint in Visual Studio should be hit now.

I agree the Lambda Test Tool documentation needs to be elaborated or made more clear.

Thanks,
Ashish

**Comment by acre-rociokatsanis** [comment]
Thank you Ashish... this works for me!!! One more question, how can I add environment variables? I have defined them in the template.yaml file, and when I run "sam local invoke" they are read from there. But when I debug using the method you describe here, my program does not read these environment variables.

**Comment by ashishdhingra** [comment]
Lambda Test Tool documentation (accessible at after launching the tool) is quite elaborate to explain steps for debugging. Hence, closing this issue.
___
<h2>Test Executable Assembly Functions</h2>
<p>
    .NET Lambda functions can be written as an executable assembly. This is done for Lambda functions using custom runtime or using .NET top level statements. These functions include the 
    Lambda runtime client implemented in the Amazon.Lambda.RuntimeSupport NuGet package. In an executable assembly function the Lambda runtime client is initialized and connects to a 
    local REST endpoint for Lambda events to process.
</p>
<p>
    The <b>Executable Assembly</b> page in this tool hosts a local Lambda runtime API for the Lambda runtime client to connect to. On this page you can queue events for the Lambda 
    function to process.
</p>
<h4>Connect Executable Assembly Functions</h4>
<p>
    To test Lambda function built as an executable assembly the environment variable <b>AWS_LAMBDA_RUNTIME_API</b> must be set to 
    <b>localhost:5050</b>. This will tell Amazon.Lambda.RuntimeSupport to connect to this instance of the test tool for Lambda
    events to process. To configure AWS credentials and region for the function the environment variables <b>AWS_PROFILE</b> and <b>AWS_REGION</b> can be set. 
</p>
<p>
    Here is an example of a .NET executable assembly Lambda function's <i>launchSettings.json</i> file used in Visual Studio for debugging that connects to the test tool and 
    sets the profile and region.
    <pre>
{
  "profiles": {
    "Lambda Runtime API": {
      "commandName": "Project",
      "environmentVariables": {
        "AWS_LAMBDA_RUNTIME_API": "localhost:5050",
        "AWS_PROFILE": "test-profile",
        "AWS_REGION": "us-west-2"
      }
    }
  }
}
    </pre>
<h4>Programmatically Queue Events</h4>
To queue an event to be processed without using the UI send a <b>POST</b> request to <b>http://localhost:5050/runtime/test-event</b> with the 
JSON Lambda event document as the POST request's body.
</p>

**Comment by ashishdhingra** [comment]
Lambda Test tool Readme at [Testing Executable Assemblies](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#testing-executable-assemblies) has been updated to add steps for debugging executable assemblies.
