### ISSUE TITLE
ASP.NET Core 2 Support

### ISSUE THREAD

**Issue by uxsoft** [aws/aws-lambda-dotnet#154]
With ASP.NET Core 2 there is a new way to create a webhost

Instead of:
protected override void Init(IWebHostBuilder builder)
...

We now have:
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

**Comment by normj** [comment]
When Lambda supports .NET Core 2.0 we'll take a look at updating the `Amazon.Lambda.AspNetCoreServer` for the changes to ASP.NET Core 2.0.

**Comment by ytn3rd** [comment]
@normj out of curiosity, now that [beanstalk supports .NET Core 2.0](https://aws.amazon.com/blogs/developer/aws-elastic-beanstalk-updated-with-net-core-2-0/) will that be coming to Lambda anytime soon, or not so because we need .NET Core 2.0 to be lts?

**Comment by arpit-nagar** [comment]
Any updates by when we can have support of .Net Core 2.0 ?

**Comment by ytn3rd** [comment]
@arpit-nagar, .NET Core 2.0 is not LTS (Long Term Support) so as far as they have said elsewhere it won't suddenly get added.

As to my previous comment wiht beanstalk getting .NET Core 2.0 so can we have it now, normj has a response over [here](https://github.com/aws/aws-lambda-dotnet/issues/149#issuecomment-326391410) regarding that.

I feel this should now be closed.

**Comment by FrederikNygaardSvendsen** [comment]
I really need to know if support for .net core 2.0 is in development, and if not, if support is even planned... This is a huge deal

**Comment by ytn3rd** [comment]
@FrederikNygaardSvendsen , aws-lambda only supports LTS versions of dotnetcore, so you need to go ask the [dotnetcore](https://github.com/dotnet/core) people when 2.0 is going to become LTS, nothing is happening here until then.

**Comment by normj** [comment]
@FrederikNygaardSvendsen I can't give any timing or details but I will say we know the a new .NET Core Lambda runtime is critical to the community and we are working hard on the next version.

**Comment by FrederikNygaardSvendsen** [comment]
@normj Thanks for letting me know

**Comment by Kralizek** [comment]
@normj maybe you should add this news in the ReadMe considering how many requests you are getting :P

**Comment by normj** [comment]
Closing this in favor of tracking the upcoming .NET Core 2.0 support with issue https://github.com/aws/aws-lambda-dotnet/issues/149
