### ISSUE TITLE
Partial batch failure support with Amazon.Lambda.KinesisEvents

### ISSUE THREAD

**Issue by danny-zegel-zocdoc** [aws/aws-lambda-dotnet#1553]
### Describe the feature

When processing a kinesis stream configured with `reportBatchItemFailures` as `true` I expected to find a `StreamsEventResponse` object defined in `Amazon.Lambda.KinesisEvents` so I can report a partial batch failure similar to how `Amazon.Lambda.DynamoDBEvents` has `StreamsEventResponse` and `Amazon.Lambda.SQSEvents` has `SQSBatchResponse`.

The documentation here https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#services-kinesis-batchfailurereporting indicates that this is already available for Java and I would appreciate this feature added for dotnet.

### Use Case

This feature would be appreciated when using a Lambda to process a Kinesis stream that has `ReportBatchItemFailures` configured to `true`.

### Proposed Solution

Implement `StreamsEventResponse` in the `Amazon.Lambda.KinesisEvents` package.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Lambda.KinesisEvents

### Targeted .NET Platform

.NET 6 and up

### Operating System and version

N/A

**Comment by ashishdhingra** [comment]
This has been implemented in [Amazon.Lambda.KinesisEvents v2.1.0](https://www.nuget.org/packages/Amazon.Lambda.KinesisEvents/2.1.0).
