### ISSUE TITLE
Lambda Test Tool Null Exception When No Project Directory Found

### ISSUE THREAD

**Issue by joshuaseither** [aws/aws-lambda-dotnet#1555]
### Describe the bug

The lambda test tool throws a null exception when no parent project directory is found relative to the built binaries path.

This occurs when the output path of `dotnet build` is changed via `--output` or other method such as using [nx-dotnet](https://github.com/nx-dotnet/nx-dotnet) which configures a different output path via a `props` file.

### Expected Behavior

The mock tool web page should display and allow lambda execution.

### Current Behavior

The mock tool web page displays the following exception:

```
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
Amazon.Lambda.TestTool.LocalLambdaOptions.GetPreferenceDirectory(bool createIfNotExist) in C:\build\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\LocalLambdaOptions.cs, line 63
```

### Reproduction Steps

```bash
dotnet new lambda.EmptyFunction --name MyApp
dotnet build ./MyApp/src/MyApp --output ./dist
cp ./MyApp/src/MyApp/aws-lambda-tools-defaults.json ./dist
cd ./dist
dotnet-lambda-test-tool-6.0
```

### Possible Solution

https://github.com/aws/aws-lambda-dotnet/pull/1556

#### Nuget Packages

- Amazon.Lambda.Core=2.1.0
- Amazon.Lambda.Serialization.SystemTextJson=2.3.1

#### Tool Version
* dotnet-lambda-test-tool-6.0=0.13.1

### Targeted .NET Platform

.NET 6

### Operating System and version

Arch Linux, Windows 10

**Comment by ashishdhingra** [comment]
The fix in the PR has been released in version `0.14.0` of `Amazon.Lambda.TestTool`.
