### ISSUE TITLE
Error on deploy when referencing a .NET Standard library

### ISSUE THREAD

**Issue by bslatner** [aws/aws-lambda-dotnet#157]
I recently discovered that if I add a reference to a project targeting .NET Standard 1.4 to my serverless project, I get the following error on `dotnet lambda deploy-serverless`:

```
Error: Project is referencing NETStandard.Library version 1.6.1. Max version supported by netcoreapp1.0 is 1.6.0.
Error: NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1.
Error: Check the following dependencies for versions compatible with netcoreapp1.0:
Error:  amazon.lambda.apigatewayevents : 1.1.0
Error:  amazon.lambda.serialization.json : 1.1.0
Error:  testclasslibrary : 1.0.0

```
To reproduce. From Visual Studio 2017 (latest updates installed):

* File -> New Project
* Select AWS Serverless Application (.NET Core)
* Pick anything for the blueprint. I chose the blog API
* From project directory
  * dotnet restore
  * dotnet build
  * dotnet lambda deploy-serverless
* Observe that deployment works
* Right click on solution in VS. Add .NET standard class library
* Change targeting of library to .NET Standard 1.4
* In Solution Explorer, right click on Dependencies under serverless app
* Add a project reference to the class library
* File -> Save All
* From project directory
  * dotnet restore
  * dotnet build
  * dotnet lambda deploy-serverless
* Observe that deployment fails

**Comment by bslatner** [comment]
Incidentally, this appears to happen regardless of which version of .NET Standard you target in the class library.

**Comment by normj** [comment]
In your csproj file for the class library can add the following as a sibling to the TargetFramework to force the implicit reference of NETStandard.Library to be 1.6.0.

```xml
<NetStandardImplicitPackageVersion>1.6.0</NetStandardImplicitPackageVersion>
```

**Comment by normj** [comment]
Closing as I believe my last comment should unblock you. If not feel free to reopen.

**Comment by bslatner** [comment]
That did the trick. Thanks.

**Comment by mrwcjoughin** [comment]
thanks @normj - that tag did the trick!
