### ISSUE TITLE
Support for executable assemblies when using Lambda Annotations

### ISSUE THREAD

**Issue by jeastham1993** [aws/aws-lambda-dotnet#1571]
### Describe the feature

The current implementation of Lambda Annotations relies on using the class based handler approach. Add support for executable assemblies so that runtimes that require the Lambda runtime to be manually bootstrapped can also be used. Behind the scenes, this will generate the static main method used as the entrypoint.

### Use Case

As a developer, I want to use non-managed runtime versions of .NET but this requires me to understand how to bootstrap the runtime manually.

### Proposed Solution

Update the existing source generator to generate a `Program.cs` file if targetting an executable assembly. If there are multiple handlers in the same Lambda function add an Environment Variable to determine which handler is used.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

N/A, this is a new feature.

### Targeted .NET Platform

.NET 6, .NET Standard 2.0

### Operating System and version

All

**Comment by jeastham1993** [comment]
I have a PR ready to raise for this, just looking to get the tests working.

**Comment by ashishdhingra** [comment]
Needs review with the team. @jeastham1993 Feel free to contribute PR.

**Comment by jeastham1993** [comment]
@ashishdhingra PR raised
https://github.com/aws/aws-lambda-dotnet/pull/1573

**Comment by normj** [comment]
Closing the issue now that the PR has been merged and released.
