### ISSUE TITLE
Method-level JSON serialisers are not respected in Annotations

### ISSUE THREAD

**Issue by mrmoo-zoopla** [aws/aws-lambda-dotnet#1572]
### Describe the bug

When using the new Annotations framework, method-level JSON serialisers are "lost" during the code generation process, with the result that only one serialiser can be used, the one declared at assembly level.

### Expected Behavior

The serialiser specified on each lambda function method should be used for that function.

### Current Behavior

The assembly-level serialiser is the only one available.

### Reproduction Steps

To reproduce, create a C# library project which contains two classes which each express an operation as a lambda function.  Mark each with a `LambdaSerializer` attribute specifying a non-default serialiser which exhibits some of kind of special deserialisation behaviour

Test the two functions and see that the behaviour of the assembly-level serialiser is used.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Annotations 1.0.0

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10 and Ubuntu

**Comment by ashishdhingra** [comment]
This is most likely a feature request. Needs review with the team.

**Comment by ashishdhingra** [comment]
Refer https://github.com/aws/aws-lambda-dotnet/pull/1573#discussion_r1301445977.

**Comment by normj** [comment]
In newer versions of the Annotations library it respects the method level seriailizer attribute. I believe support was added in version 1.1.
