### ISSUE TITLE
Specify return code&message for custom authorizer.

### ISSUE THREAD

**Issue by ibobkovitransition** [aws/aws-lambda-dotnet#159]
It would be nice to have ability to specify custom return code & message in scope of custom authorizer.

**Comment by normj** [comment]
Version 1.1.2 of **Amazon.Lambda.APIGatewayEvents** was released today which adds this support.

**Comment by swlasse** [comment]
Awesome, thanks for this @normj. Works perfectly! For info, this also solves my request in #98
