### ISSUE TITLE
Stage variables for custom authorizer.

### ISSUE THREAD

**Issue by ibobkovitransition** [aws/aws-lambda-dotnet#160]
It would be nice to add opportunity to fetch stage variables in scope of custom authorizer.

**Comment by dHihich** [comment]
Any update on the issue?

**Comment by dHihich** [comment]
I've just noticed that a new type of Authorizer was released - Request Authorizer. The documentation says that this type of Authorizer supports headers, query strings, stage variables, or context parameters. It looks like it's exactly what we need, right?

Can you please give us an approximate estimate when this feature is going to be included in .NET Core SDK?

Thank's in advance

**Comment by normj** [comment]
**APIGatewayCustomAuthorizerRequest** was updated in version 1.1.2 of **Amazon.Lambda.APIGatewayEvents** to include the REQUEST type properties.
