### ISSUE TITLE
Request sent from Lex to Lambda not deserialized

### ISSUE THREAD

**Issue by NeetaA** [aws/aws-lambda-dotnet#161]
Where to add variable LAMBDA_NET_SERIALIZER_DEBUG with a value of true to your Lambda function?
Can you please tell me the File or syntax for it to add in which file exact?

**Comment by normj** [comment]
In the Lambda function view in either the Visual Studio toolkit or the web console you can set environment variables for the function. That is where you add the LAMBDA_NET_SERIALIZER_DEBUG environment variable.

**Comment by NeetaA** [comment]
Can you please share the reference link or Specify Code snippet to add in which file?


Regards,
Neeta Avasare
Software Engineer - Harbinger Systems Pvt. Ltd.
Office: +91.20.2528.4201 / 2 / 3 (Ext no. 165)
Cell: +91 7517893824
________________________________

**Comment by NeetaA** [comment]
Can you please share the reference link or Specify Code snippet to add in which file?

**Comment by normj** [comment]
In the configuration tab is where you can set that environment variable.

![image](https://user-images.githubusercontent.com/1653751/34281338-f076c766-e672-11e7-87bb-2136f60ec9d0.png)
