### ISSUE TITLE
S3 EventType constant seems to have different underlying values

### ISSUE THREAD

**Issue by deadsetgav** [aws/aws-lambda-dotnet#162]
Hi, 

I don't know if this is a bug or I am just using the EventType constants wrong.

I am trying to write a lambda function to read the contents of new files dropped into an S3 bucket.
I only want to action new files sent to the S3 bucket - when I try to check the EventType on the S3 event record - I get problems:

```
        public async Task<string> Function(S3Event evnt, ILambdaContext context)
        {
            var s3Event = evnt.Records?[0].S3;
            if (s3Event == null)            
                return null;
            
            var record = evnt.Records?[0];
            if (record.EventName == EventType.ObjectCreatedPut)
            {
                // This does not work - as the EventType underlying string constant in the record.EventName is "ObjectCreated:Put" 
                // however the contstant value of the EventType is "S3:ObjectCreated:Put"
            }
          
        }
```

I'm on the latest versions of both the Amazon.Lambda.S3Events and Amazon.S3 packages

Thanks

Gav

**Comment by normj** [comment]
Unfortunately this is be being caused by a discrepancy between how the event type is being sent for the PutBucketNotification operation, which was when the constant was added, and how the event type name is being sent as part of the Lambda event.

I'm trying figure out how I can fix this in a non breaking way.

**Comment by normj** [comment]
I have pushed out a version  3.3.16.2 of AWSSDK.S3 which updates the comparison of EventType to consider s3:ObjectCreated:X and ObjectCreated:X as the same. Version 1.0.2 of Amazon.Lambda.S3Events has the dependency to AWSSDK.S3 updated to this new version.
