### ISSUE TITLE
.NET Mock Lambda Test Tool test harness page non-functional when launched from JetBrains Rider (release 0.15.0)

### ISSUE THREAD

**Issue by Dakkith** [aws/aws-lambda-dotnet#1625]
### Describe the bug

Running Amazon.Lambda.TestTool version 0.15.0 from JetBrains Rider (with the .NET executable Amazon.Lambda.TestTool.BlazorTester.dll as the launcher) results in a non-functional test page. None of the buttons work (unable to submit test events).

Inspecting the browser network debug tab shows that the "http://localhost:5050/_framework/blazor.server.js" returns a 404 not found error. 

Uninstalling the tool and installing the previous version 0.14.1 works fine.

### Expected Behavior

Expecting the blazor test page to be functional when clicking buttons to submit events.

Expecting the test page to receive a HTTP OK 200 status when requesting "http://localhost:5050/_framework/blazor.server.js" file.

### Current Behavior

The page loads the static assets, but is not functional when attempting to interact with any of the buttons.

Inspecting the browser network debug tab shows that the "http://localhost:5050/_framework/blazor.server.js" returns a 404 not found error. 

### Reproduction Steps

Find the full path for the "Amazon.Lambda.TestTool.BlazorTester.dll" file:

    %USERPROFILE%\.dotnet\tools\.store\amazon.lambda.testtool-6.0\0.15.0\amazon.lambda.testtool-6.0\0.15.0\tools\net6.0\any\Amazon.Lambda.TestTool.BlazorTester.dll

From within JetBrains Rider:

    Select Run->Edit Configurations...
    Push the + button to add a configuration and select .NET Executable
    Set the Exe path field to the full path of Amazon.Lambda.TestTool.BlazorTester.dll as described above
    Set the Working directory field to the .NET Core Lambda project root
    Push OK

After following these steps, any time you start the debugger in Rider, it will subsequently launch the .NET Mock Lambda Test Tool.

### Additional Information/Context

Have tried with multiple browsers, and against a different localhost URL (http://127.0.0.1:5050/). 
Only restoring the previous version (0.14.1) of the tool got me back to a functional test harness page.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.TestTool (0.15.0)

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by OxfordGrid** [comment]
I've got the same behaviour when launching from VS 2022 in Win 11 (.net 6).
It started happening a couple of days ago. No changes to the projects were done. The only thing I can think of that happened between the time it worked and yesterday - a Windows Tue update.

Things tried (none helped):
- running an empty Lambda project
- running the Mock Test Tool in FF, FF private window, Chrome
- Updating VS 2022 to the latest version
- Trying an empty Lambda project on a different laptop with Win 10
- Deleting dotnet-lambda-test-tool-6.0.exe and reinstalling it with dotnet tool install -g Amazon.Lambda.TestTool-6.0

Please fix it asap, as it stops the whole development process atm.

**Comment by normj** [comment]
Very sorry about the breaking behavior. I have PR out and will work on getting it released as fast as I can. Till then you will need to revert back to `0.14.1`.

https://github.com/aws/aws-lambda-dotnet/pull/1627

**Comment by OxfordGrid** [comment]
@normj After downgrading to 0.14.1 I'm gettin "The connection has timed out" when I launch from VS. Is there anything else I need to do in Visual Studio?

**Comment by AztecRuler** [comment]
I have just decided to create a test Lambda in the AWS environment and publish to there for the moment for testing, not ideal but means I can keep working while it is being reverted.

**Comment by normj** [comment]
Apologize again for the bug. Version `0.15.1` has been released.

**Comment by OxfordGrid** [comment]
Thanks all is working now!

**Comment by AztecRuler** [comment]
just run 
`dotnet tool update --global Amazon.Lambda.TestTool-6.0 --version 0.15.1`
for anyone who is having the issue.

**Comment by ashishdhingra** [comment]
@Dakkith Please check if updating to latest version using command `dotnet tool update --global Amazon.Lambda.TestTool-6.0 --version 0.15.1` works for you.

**Comment by Dakkith** [comment]
Working nicely on version 0.15.1.

Thank you for the quick response.
