### ISSUE TITLE
Blazor.server.js not found

### ISSUE THREAD

**Issue by Mairaj06** [aws/aws-lambda-dotnet#1628]
Hi,
My mock tool 6.0 (0.15.0) suddenly stopped working, and i am unable to debug because functionhandler is not being invoked. When i checked the console i see 404 for the blazor.server.js file, i don't know what happened because i didn't change anything inside lambda function.

![image](https://github.com/aws/aws-lambda-dotnet/assets/24219499/27ba10d3-afb6-45d6-8a72-418716ceffcd)

Also in command line i see the file name i am not sure what happened

![image](https://github.com/aws/aws-lambda-dotnet/assets/24219499/f1ec32b7-e4cd-433f-b0cd-a6e05d727b4b)

### Expected Behavior

Should be executing my lambda

### Current Behavior

Mock tool not sending call to function

### Reproduction Steps

Install the latest version of mock tool

### AWS .NET SDK and/or Package version used

AWS SDK

### Targeted .NET Platform

.Net 6.0

### Operating System and version

Windows 11 22H2

**Comment by Nilar55** [comment]
I also faced the same problem. So how to fix:

- Remove dotnet-lambda-test-tool-6.0.exe from C:\Users\username.dotnet\tools
- Install previous working version `dotnet tool install --global Amazon.Lambda.TestTool-6.0 --version 0.14.1`

**Comment by AztecRuler** [comment]
just run 
dotnet tool update --global Amazon.Lambda.TestTool-6.0 --version 0.15.1
for anyone who is having the issue.

**Comment by ashishdhingra** [comment]
@Mairaj06 Please check if updating to latest version using command `dotnet tool update --global Amazon.Lambda.TestTool-6.0 --version 0.15.1` works for you.

**Comment by Mairaj06** [comment]
@All actually downgrading worked for me as mentioned by @Nilar55
