### ISSUE TITLE
Method MarshallResponse in AspNetCoreServer.APIGatewayProxyFunction needs to set Content-Encoding for binary content

### ISSUE THREAD

**Issue by gerdb42** [aws/aws-lambda-dotnet#1634]
### Describe the bug

Upon returning binary content from a Lambda (e.g. an image/png), MarshallResponse turns the content into a base64-encoded string and sets IsBase64Encoded to true. But this leads to processing errors on the client side. Besides setting IsBase64Encoded to true, it should also set the "Content-Encoding"-Header to "base64".

### Expected Behavior

If IsBase64Encoded is set to true, "Content-Encoding"-Header is set to "base64".

### Current Behavior

Client displays returned image/png as broken.

### Reproduction Steps

Create a .net-based lambda and enable UseStaticContent. Enable binary content in ApiGateway as documented. Request an image/png through the lambda through a browser. Browser will show a broken image.

### Possible Solution

If MarshallResponse turns the response to base64 and sets IsBase64Encoded to true, "Content-Encoding" should be set to "base64" as well.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.AspNetCoreServer 8.1.0

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
@gerdb42 Good morning. Please refer the below references:
- [Mozilla Developer: Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding)
- [Content-Encoding tokens](https://en.wikipedia.org/wiki/HTTP_compression#Content-Encoding_tokens)
- https://docs.w3cub.com/http/headers/content-encoding
- https://stackoverflow.com/questions/17154967/is-content-encoding-being-set-to-utf-8-invalid

The original media/content type is specified in the [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header, and that the Content-Encoding applies to the representation, or "coded form", of the data. If the original media is encoded in some way (e.g. a zip file) then this information would not be included in the Content-Encoding header.

`base64` doesn't appear to be a valid value for `Content-Encoding` header.

Could you share the sample Lambda code that you are using to return the image (this would make reproducing this issue faster)?

For your use case, could you share the markup used to display image on client side using Base64 string? Also refer [How to display Base64 images in HTML?](https://www.geeksforgeeks.org/how-to-display-base64-images-in-html/) on how to display images using Base64 string.

Thanks,
Ashish

**Comment by gerdb42** [comment]
To reproduce, simply create a ASP.NET page, add "app.UseStaticFiles();" to your Configure Method in Startup and provide some images in your wwwroot-folder. If the page is hosted on a webserver, you're all set to serve images.
However, if the page is hosted in AWS lambda and served through proxy integration in AWS API Gateway, binary content has to be Base64 encoded before it is returned to API Gateway. According to the docs also the IsBase64Ecoded-flag has to be set to true. But that seems to be not sufficient. If I set Content-Type to "image/png" and IsBase64Encoded to true, the Body gets Base64-encoded again and the client chokes complaining about a broken image. Only if I also set Content-Encoding to "base64" (which might well be a extension by API Gateway) the content arrives correctly at the client.

The markup at the client side is a simple img-tag like `<img src="https://my-aws-site/myapp/images/MyImage.png" />`.

My only addition to the original MarshallResponse method from https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs are the following lines after the call to Utilities.ConvertAspNetCoreBodyToLambdaBody:
```
                if (response.IsBase64Encoded && string.IsNullOrWhiteSpace(contentEncoding))
                {
                    response.MultiValueHeaders["Content-Encoding"] = new List<string>() { "base64" };
                }
```
I'm not sure what the clue is here. Shouldn't IsBase64Encoded=true be enough?

Regards
gerdB

**Comment by ashishdhingra** [comment]
@gerdb42 Could you please check if you have set `Content-Type` header in Lambda proxy integration with API Gateway. Kindly refer below:
- [Working with binary media types for REST APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html)
  - Also, refer https://stackoverflow.com/questions/35804042/aws-api-gateway-and-lambda-to-return-image for C# example (I have not tested it though).
- [Serve images with AWS Lambda and Node.js](https://medium.com/dailyjs/serve-images-with-aws-lambda-ffd01abae845) for example.

Thanks,
Ashish
