### ISSUE TITLE
dotnet lambda package failing in VS2017 v15.3

### ISSUE THREAD

**Issue by jyothi530** [aws/aws-lambda-dotnet#164]
In VS 2017 v15.3 Package downgrade warnings (error code:NU1605) are treated as errors which will fail the build. But we can configure the setting in Project Build properties to not treat them as errors. I have changed the setting to treat NU1605 as warnings. Now my "dotnet publish" command is working without any errors. But when I try to run "dotnet lambda package" it is failing by considering package downgrade(NU1605) as error. I think "dotnet lambda package" command is not considering project settings. Can anyone please review

**Comment by jyothi530** [comment]
Not an issue. "dotnet lambda package" publishes in "release" configuration mode. I have changed the setting only for "Debug" mode. I applied the setting for "release" mode as well. Now "dotnet lambda package" is working without any issues.

**Comment by jbeck8176** [comment]
@jyothi530 Thank you for leaving your comment. I had the exact same situation and you documenting it saved my day.
