### ISSUE TITLE
Lambda PowerShell Functions Do Not Log Debug Messages to CloudWatch Messages 

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-lambda-dotnet#1641]
### Describe the bug

_We already have internal case and ticket V1078993289 for this, but creating this so others can track a fix publicly._

### Expected Behavior

"Write-Debug" should print to CloudWatch messages when adding -Debug parameter or using $DebugPreference to get the message displayed on console.

### Current Behavior

Messages aren't logged.

### Possible Solution

This probably is happening because "Write-Debug" isn't included in these events https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.PowerShellHost/PowerShellFunctionHost.cs#L294

**Comment by ashishdhingra** [comment]
The change has been released in [AWSLambdaPSCore 4.0.2.0](https://www.powershellgallery.com/packages/AWSLambdaPSCore/4.0.2.0).

Kindly note the following to enable debugging:
- Refer [$DebugPreference](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.4#debugpreference). In PowerShell code, you:
  - Either need to set `$DebugPreference = "Continue"` at the beginning of script; **OR**
  - Or include `-Debug` parameter while executing `Write-Debug` (e.g. `Write-Debug "Testing Lambda PowerShell Write-Debug" -Debug`)
- Also set environment variable `AWS_LAMBDA_HANDLER_LOG_LEVEL` with value `DEBUG` (refer blog post [Introducing the .NET 6 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/)). This will enable Debug logs at Lambda level.
