### ISSUE TITLE
Launching amazon.lambda.testtool-6.0 as debugger in RIDER fails to find any config files or Lambda methods in browser

### ISSUE THREAD

**Issue by derekvantonder3DD** [aws/aws-lambda-dotnet#1651]
### Describe the bug

When launching amazon.lambda.testtool-6.0 as per the instructions in "Debugger configuration for Jetbrains RIDER", **I'm not sure which directory to use for the working directory**. The test tool launches a browser window, but I can't pick a lambda method or a config file. I've tried almost every directory in my project with no luck. What, exactly, is the testtool looking for in the working directory? A CF YAML template? Would love to have better documentation around this.

<img width="1885" alt="image" src="https://github.com/aws/aws-lambda-dotnet/assets/150106590/a33122a6-d83a-4b99-9e6e-c6fe0670d6b4">

I have had success debugging with the following launchSettings.json, but I have to manually attach the debugger each time after the browser launches, which is frustrating:

```
"profiles": {
    "(macOS) Mock Lambda Test Tool": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "lambda-test-tool-6.0 --port 5050",
      "environmentVariables": {
        "AWS_PROFILE": "XXXXXXXX",
        "AWS_REGION": "XXXXXXXX",
        "AWS_LAMBDA_RUNTIME_API" : "localhost:5050"
      }
    },
```

### Expected Behavior

The amazon.lambda.testtool-6.0 debugger attaches automatically and finds the config/lambda methods.

### Current Behavior

Exceptions are thrown and the debugger won't start.

### Reproduction Steps

Don't have a clean repo to provide at this point, hoping for clarification on what the working directory should contain first.

### Possible Solution

Documentation around what files exactly the test tool expects to find in the working directory when the debugger launches.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.2.0

### Targeted .NET Platform

net6.0

### Operating System and version

macOS

**Comment by ashishdhingra** [comment]
@derekvantonder3DD Good morning. Please follow instructions at [Lambda Test tool: Configure for JetBrains Rider](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider). It has one of the steps to `Set the Working directory field to the .NET Core Lambda project root`.

Thanks,
Ashish

**Comment by darthhiggy** [comment]
Hey, so, I'm having the same issue and I don't see a resolution. The link from the one comment is not helpful as that is the first thing I did. I set my project root and it has a config in there.

**Comment by eddiemcs3** [comment]
Re-opening the issue to follow-up @darthhiggy.

**Comment by darthhiggy** [comment]
So, I resolved the issue late yesterday. It had to do with the config. It was missing some key sections. I don't know what section I was missing originally but I found a copy of a working one and copied that. I didn't find much about the config file I'm the documentation but it might be there somewhere.

**Comment by eddiemcs3** [comment]
Thank you for the follow-up @darthhiggy.  We'll follow-up to see what can be improved in the documentation so that it is clear.
