### ISSUE TITLE
Cant find the dotnet sdk when installed using the microsoft package feed

### ISSUE THREAD

**Issue by jkoopmanndataflor** [aws/aws-lambda-dotnet#1680]
### Describe the bug

I'm trying to update the dotnet sdk for my wsl installation running ubuntu. For that I uninstalled the dotnet 7 sdk and changed the source from which I get the .net sdk, from the ubuntu feed to the official microsoft feed as described here :
https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#solutions

After installing the dotnet 8 sdk, and reinstalling the dotnet amazon lambda tools I get the following error when running dotnet lambda deploy-serverless ...

You must install .NET to run this application.

App: /home/kira/.dotnet/tools/dotnet-lambda
Architecture: x64
App host version: 8.0.2
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.2

### Expected Behavior

After running 
dotnet tool install -g Amazon.Lambda.Tools
I can run any dotnet lambda command.

### Current Behavior

dotnet lambda deploy-serverless ... fails with the error 

You must install .NET to run this application.

App: /home/kira/.dotnet/tools/dotnet-lambda
Architecture: x64
App host version: 8.0.2
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.2

### Reproduction Steps

Installl wsl, with the default ubuntu distro
Install dotnet 8 sdk from the microsoft feed as described here: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
Attempt to install and run amazon.lambda.tools, e.g. dotnet tool install -g Amazon.Lambda.Tools 

### AWS .NET SDK and/or Package version used

amazon.lambda.tools' (version '5.10.1')

### Targeted .NET Platform

.Net 8

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
@jkoopmannAtDATAflor Good afternoon. Could you please share the exact steps followed to install .NET 8 SDK on your Ubuntu distribution? The link https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-ubuntu#solutions mentions 2 scenarios.

Also, the said error is thrown by the `dotnet` command. The issue https://github.com/dotnet/runtime/issues/79237 talks about similar problem, not sure if it is related to your use case.

Thanks,
Ashish
