### ISSUE TITLE
Support for .net Core 1.1 ? 

### ISSUE THREAD

**Issue by DerrickF** [aws/aws-lambda-dotnet#169]
Now that .net core 1.1 is officially LTS, any word on when lambda will be updated to support 1.1? Theres a bunch of nuget packages that are restricted to 1.1+ that we want to use in our serverless project but cant right now :(

**Comment by Kralizek** [comment]
I second that. The 1.0 restriction is making our life harder day-by-day.
I hope to hear about .NET Core 2.0 on Lambda at re:Invent 2017 tho :D

**Comment by normj** [comment]
Closing this as duplicate, you can checkout my previous comments on this here. Short answer is we are focus are engineering effort on the newer versions of .NET Core and not planning support for .NET Core 1.1. I don't have timing information I can share but trust me I know how important this is.

https://github.com/aws/aws-lambda-dotnet/issues/149#issuecomment-326391410
