### ISSUE TITLE
DOTNET_GCHeapHardLimit is still needed with .NET 8

### ISSUE THREAD

**Issue by Dreamescaper** [aws/aws-lambda-dotnet#1699]
### Describe the bug

I was investigating rare OutOfMemory issues with our lambdas. I've tried to re-add DOTNET_GCHeapHardLimit environment variable, which I've removed after an update to .NET 8. And it does seem to fix the issue, even though I was under the impression that it's not required anymore with .NET 8.

### Expected Behavior

Lambdas shouldn't fail with OutOfMemory issues without any additional steps.

### Current Behavior

Lambdas still fail with OutOfMemory exceptions, unless DOTNET_GCHeapHardLimit env var is set.

### Additional Information/Context

Here's a plot of Memory Usage before and after DOTNET_GCHeapHardLimit variable was set. You can see that RAM usage doesn't get as close to 512MB after env var is added.

![image](https://github.com/aws/aws-lambda-dotnet/assets/17177729/16f650d9-5739-4ba7-a66e-2fccfe1b5954)

### Targeted .NET Platform

.NET 8

### Operating System and version

AmazonLinux

**Comment by Dreamescaper** [comment]
I'm not sure whether it matters or not, but we use DataDog Lambda extensions:
arn:aws:lambda:<AWS_REGION>:464622532012:layer:dd-trace-dotnet:15
arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-Extension:55

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by ashishdhingra** [comment]
Reference issue https://github.com/dotnet/runtime/issues/83563

**Comment by Dreamescaper** [comment]
> Reference issue https://github.com/dotnet/runtime/issues/83563

I was under the impression that it affects ECS only, no?

**Comment by dscpinheiro** [comment]
Norm wrote a blog post about this last year, it mentions Lambda as well: https://aws.amazon.com/blogs/developer/configuring-net-garbage-collection-for-amazon-ecs-and-aws-lambda/

**Comment by Dreamescaper** [comment]
@dscpinheiro 
Exactly. Per my understanding of that post (see Conclusion), Lambda was blocked by this issue: https://github.com/dotnet/runtime/issues/70601#issuecomment-1473243288 .
It was closed in .NET 8, and should've been resolved on Lambda's side by this PR: https://github.com/aws/aws-lambda-dotnet/pull/1578

**Comment by mikebollandajw** [comment]
i am experiencing out of memory errors even with DOTNET_GCHeapHardLimit 0x20000000

**Comment by ashishdhingra** [comment]
@Dreamescaper Good afternoon. Please advise if it is possible to share sample code and steps for reproduction.

**Comment by mikebollandajw** [comment]
we are holding back on moving to .net 8 from .net 6 until we can understand more why out of memory errors are happening on all services we have migrated

**Comment by Dreamescaper** [comment]
@ashishdhingra 
Unfortunately, I cannot share our product code, and I wasn't able to reproduce it with a quick sample.
I'll try to investigate more a bit later.

**Comment by afroewis** [comment]
I am facing the same issue in a .NET 8 App Service. Scaling up to a machine with more memory doesn't help. An OutOfMemoryException is thrown when allocating a big object (even though there is more than enough memory left).

**Comment by normj** [comment]
@Dreamescaper or anybody else having this issue would it be possible to share your `<assembly-name>.deps.json` file from the deployment bundle? Also if you could log the results of calling `GC.GetGCMemoryInfo().TotalAvailableMemoryBytes.ToString("N0")` and report the value along with your function's configuration that would help. 

What I want to make sure is if your function is bring in its own version of `Amazon.Lambda.RuntimeSupport` that the latest version is being brought in. That library is the one that was updated for .NET 8 and set the max heap size.

**Comment by mikebollandajw** [comment]
> i pulled down the lambda runtimezip and checked the app.deps.json and search for RuntimeSupport but there were no matches

**Comment by Dreamescaper** [comment]
@mikebollandajw 
Sorry for delay.
No, I don't package RuntimeSupport. Why would I need that if I'm using .NET8 managed runtime?

**Comment by mikebollandajw** [comment]
> @mikebollandajw Sorry for delay. No, I don't package RuntimeSupport. Why would I need that if I'm using .NET8 managed runtime?

Sorry, you asked us to provide the deps file and check for that, was it something else you wanted?

**Comment by Dreamescaper** [comment]
Oh, that's probably for @normj :)

**Comment by Maverick1983** [comment]
I have same problem on Lambda with .net 6. I add this _**DOTNET_GCHeapHardLimit**_, but seem not working.

```
(d8016fe2-5745-4722-a97c-fa417114d376) Endpoint response body before transformations: {
  "errorType": "JsonSerializerException",
  "errorMessage": "Error converting the response object of type Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse from the Lambda function to JSON: Exception of type 'System.OutOfMemoryException' was thrown.",
  "stackTrace": [
    "at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Serialize[T](T response, Stream responseStream)",
    "at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass26_0`2.<<GetHandlerWrapper>b__0>d.MoveNext()",
    "--- End of stack trace from previous location ---",
    "at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)"
  ],
  "cause":   {
    "errorType": "OutOfMemoryException",
    "errorMessage": "Exception of type 'System.OutOfMemoryException' was thrown.",
    "stackTrace": [
      "at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)",
      "at System.GC.<AllocateUni [TRUNCATED]
```

**Comment by SeijiSuenaga** [comment]
`DOTNET_GCDynamicAdaptationMode=1` didn't solve the problem in my case.

I wonder whether #1578 should've set `GCHeapHardLimit` to 75% of the function's memory, to align with Microsoft's default that is documented here:  
https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-hard-limit

> If this limit isn't configured but the process is running in a memory-constrained environment, that is, inside a container with a specified memory limit, a default value is set. **That default is the greater of 20 MB or 75% of the memory limit on the container.**

I'm not sure, but it sounds like the heap isn't the only thing that tries to allocate memory, so if it's allowed to use all of the function's available memory, other allocations could fail.

**Comment by normj** [comment]
@SeijiSuenaga Possibly but at this point I can't change the value because the change would be automatically applied to running Lambda functions and that could break functions.

I hadn't seen that comment before I made the change but I had wonder if there was a better value then 100%. If the function is given a lot of memory, say 1 GB, then giving up 25% of that seems like a lot. By default there really isn't much else running in the Lambda sandbox to give up 25% but admittedly there is some memory used outside of .NET.

Are you seeing better results with 75%?

**Comment by SeijiSuenaga** [comment]
@normj I do have a function that was running reliably with 2 GB and 75% heap hard limit, but then had a failure when we removed the limit.  With the limit, the function's reported "Max Memory Used" was peaking around 85%, and when we removed the limit, reported usage peaked at 100%.  One of the invocations that reported 100% usage failed with:

> Error: Runtime exited with error: signal: killed

Giving up 25% does seem like a lot for large memory sizes.  I'm not sure how much we can extrapolate from my function, but I suppose its 85% reported usage when given 2 GB and 75% heap limit implies that it was using about 0.2 GB of non-heap memory at the time?

**Comment by normj** [comment]
Lambda extensions would be separate process that would use some of the max memory available in the Lambda compute environment.

**Comment by geertendoornenbal** [comment]
We are seeing the same thing after updating from dotnet6 tot dotnet8. Suddenly lambdas that had no issue with memory, are experiencing out of memory issues. A lambda that we had issues before, but we managed to fix with DOTNET_GCHeapHardLimit env variable now is also giving out of memory issues (with or without the env variable).
What are the next steps on resolving this?
