### ISSUE TITLE
MarshallRequest dose not support request.body?

### ISSUE THREAD

**Issue by zdjohn** [aws/aws-lambda-dotnet#17]
in method `MarshallRequest` https://github.com/aws/aws-lambda-dotnet/blob/144df7cb7988ae8fb007d5ea7e172d23faff0d5b/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L122
it dose not marshall `request.Body`is this intended and lambda for c# not suppoting body yet? 
as when the request is forwarded to asp.net api contorller, i am getting `null` request 

I am wondering if i am using it wrong, and there is another way of passing request body via api gateway using lambda?

**Comment by normj** [comment]
Thanks for letting us know. I'll take a look.

**Comment by normj** [comment]
I pushed out version 0.8.2-preview1 of Amazon.Lambda.AspNetCoreServer that now marshals the request body.

Thanks again for letting us know.

**Comment by zdjohn** [comment]
Awesome, thanks for the quick response

**Comment by normj** [comment]
No problem. I hope to give this preview library more attention after the holidays. Any feedback would be greatly appreciated.
