### ISSUE TITLE
Unable to build solution (Failed to retrieve information about 'AWSSDK.DynamoDBv2')

### ISSUE THREAD

**Issue by jakejscott** [aws/aws-lambda-dotnet#170]
````
PS C:\dev\aws-lambda-dotnet\Libraries\src\Amazon.Lambda.DynamoDBEvents> dotnet restore
  Restoring packages for C:\dev\aws-lambda-dotnet\Libraries\src\Amazon.Lambda.DynamoDBEvents\Amazon.Lambda.DynamoDBEvents.csproj...
C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(102,5): error : Failed to retrieve information about 'AWSSDK.DynamoDBv2' from remote source 'C:\dev\aws-lambda-dotnet\Deployment\nuget-packages'. [C:\dev\aws-lambda-dotnet\Libraries\src\Amazon.Lambda.DynamoDBEvents\Amazon.Lambda.DynamoDBEvents.csproj]
PS C:\dev\aws-lambda-dotnet\Libraries\src\Amazon.Lambda.DynamoDBEvents>
````

**Comment by normj** [comment]
The build script `buildtools\build.proj` creates that folder which is where this solution's NuGet packages will be written. We do that so in our build script we can test the blueprints against the latest built bits in the build script. The `Deployment` folder is never checked it it is just where the build artifacts are placed.

I think what I need to do is have the NuGet.config file in the root repository but with a different name. Then as part of our build script copy the file to the `Deployment` folder with the NuGet.config file name.

**Comment by normj** [comment]
I moved the NuGet.config to the buildtools sub folder and copy it to the Deployment folder during the build script. VS will no longer be affected by the NuGet.config file.
