### ISSUE TITLE
.NET8 AOT ARM64 deps.json missing

### ISSUE THREAD

**Issue by mark-keaton** [aws/aws-lambda-dotnet#1706]
### Describe the bug

When building the default NativeAOT Template project sample, there is a message in the build steps, if you build with the flag `-farch arm64`:

```
Missing deps.json file. Skipping flattening runtime folder because  is an unrecognized format
```

There are multiple spaces after "because", but we are not sure what is in an unrecognized format.

Then when we try to run the Lambda, we get this error:

```
Error: .NET binaries for Lambda function are not correctly installed in the /var/task directory of the image when the image was built. The /var/task directory is missing the required .deps.json file.
```

(As a sidenote, the deps.json file DOES appear in `/bin/Release/net8.0/linux-arm64/***.deps.json` after the `dotnet lambda package`)

### Expected Behavior

We expected the deps.json to be included properly.

### Current Behavior

deps.json file is not being included.

### Reproduction Steps

```bash
dotnet new lambda.NativeAOT -n NativeAotSample
dotnet lambda package -farch arm64
```

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Tools 5.10.3

### Targeted .NET Platform

.NET 8

### Operating System and version

OSX Sonoma 14.1.1

**Comment by normj** [comment]
When you deploy what do you set the function handler string to? It should be just the name of the assembly not the class library style of `<assembly>::<type-name>::<method-name>`.

**Comment by mark-keaton** [comment]
> When you deploy what do you set the function handler string to? It should be just the name of the assembly not the class library style of `<assembly>::<type-name>::<method-name>`.

That worked! I must have missed that in the documentation. Sorry about that.
