### ISSUE TITLE
Use custom serializer options for responses instead of default one

### ISSUE THREAD

**Issue by Nairda015** [aws/aws-lambda-dotnet#1715]
### Describe the bug

I don't see a way to set serialization options on all responses from lambda 

### Expected Behavior

I can control serialization options of responses like DefaultIgnoreCondition

### Current Behavior

Default serializer is used and I have no idea how to override it's behavior 

### Reproduction Steps

Create custom serializer like in [this](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/README.md#customizing-serialization-options) example with DefaultIgnoreCondition set to WhenWrittingNull and return json with null values 

### Possible Solution

[Here](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Templates/APIGatewayInvoke.tt#L20) I want to use serializer options from custom serializer like in [this](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/README.md#customizing-serialization-options) example instead of default one.
It will require changes in if check from first link and maybe [here](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Generator.cs#L387-L397)

### Additional Information/Context

-

### AWS .NET SDK and/or Package version used

Annotation.Framework 1.2

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
Appears to be a feature request.

**Comment by ashishdhingra** [comment]
> Yes I have LambdaSerializerAttribute on assembly level and it works as expected but to populate something different than null [here](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Templates/APIGatewayInvoke.tt#L20) you need to set SerializerJsonContextName and only place in code where it is set is in this strange if statement [here](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Generator.cs#L387)

Needs review.

**Comment by normj** [comment]
I agree this is a gap in Annotations to be able to customize the HTTP response body JSON serialization outside if using System.Text.Json's .NET attributes on your POCO for serialization customization.

**Comment by Nairda015** [comment]
Sounds good but why we can't reuse serialization options from [custom serializer](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/README.md#customizing-serialization-options) it is already [there](https://github.com/aws/aws-lambda-dotnet/blob/497e646d799d8c3b3c7560257d407b45e580174e/Libraries/src/Amazon.Lambda.Annotations.SourceGenerator/Templates/LambdaFunctionTemplate.tt#L41)



(I updated the links in original comment  because there was duplication instead of this example above)

**Comment by Nairda015** [comment]
Do you have a vision of how you would implement it or my idea about resolving the handler from DI with the interface and adding interceptors from [Castle.Core](https://github.com/castleproject/Core) is good enough?

**Comment by ashishdhingra** [comment]
This should have been addressed via PR https://github.com/aws/aws-lambda-dotnet/pull/1748 and available in [Amazon.Lambda.Annotations v1.4.0](https://www.nuget.org/packages/Amazon.Lambda.Annotations/1.4.0) package.
