### ISSUE TITLE
Lambda Annotations can raise CS1591 warning

### ISSUE THREAD

**Issue by chrischappell-rgare** [aws/aws-lambda-dotnet#1727]
### Describe the bug

A CS1591 warning is raised if a Lamba project using Lambda Annotations has documentation file generation enabled. The project will not build at all if it has TreatWarningsAsError enabled.

### Expected Behavior

The generated code can use #pragma warning disable CS1591 to prevent the warning from being raised.

### Current Behavior

Each public member has warning CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'.

### Reproduction Steps

Add `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to a project using Amazon.Lambda.Annotations.

### Possible Solution

Enclose the generated code in #pragma warning disable CS1591.

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Annotations 1.3.0

### Targeted .NET Platform

.Net 8

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
Needs review with the team. Probably low hanging fruit.

**Comment by ashishdhingra** [comment]
Low hanging fruit P1. Possible related discussion https://github.com/aws/aws-lambda-dotnet/discussions/1733.

**Comment by ashishdhingra** [comment]
This should have been addressed via PR https://github.com/aws/aws-lambda-dotnet/pull/1748 and available in [Amazon.Lambda.Annotations v1.4.0](https://www.nuget.org/packages/Amazon.Lambda.Annotations/1.4.0) package.
