### ISSUE TITLE
Terribly slow cold start when in VPC

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#174]
Hi,

we are experiencing extremely slow cold starts when our Lambda is placed in a VPC.
The lambda hosts an ASP.NET Core web site via the serverless application template.

I'm not sure if this is only related to the .NET Core 1.0 runtime or a general problem.

**Comment by normj** [comment]
The VPC performance hit is across all Lambda runtimes because there is overhead setting up the Elastic Network Interface. I know the Lambda team is aware of this but that issue is beyond the scope of what we support from this repository.

**Comment by Kralizek** [comment]
Ok, sorry. I didn't know it was a common problem.
