### ISSUE TITLE
Operation is not supported on this platform when performing GetObject against S3.

### ISSUE THREAD

**Issue by malcernie** [aws/aws-lambda-dotnet#176]
Scenario: 
-	I have a C# (dotnet core 1.0) Lambda function trying to perform a GetObject against an S3 bucket using the AWSSDK’s.
-	On a windows platform (i.e. my laptop), it works perfectly well
-	On the Lambda platform (presumably Linux), it errors.
-	AWSSDK.Core version 3.3.18.2 (latest)
-	AWSSDK.S3 version 3.3.11.4 (latest)
-	Microsoft.NETCore.App 1.0.5 (appears to be enforced by AWS libraries, latest is 1.0.7 in the dotnet core 1.0 stream and 1.1.4 in the dotnet core 1.1 stream) 

Code Snippet:
     AmazonS3Client client = new AmazonS3Client(Amazon.RegionEndpoint.EUWest1);
     GetObjectResponse response = await client.GetObjectAsync(bucket, key);

It errors at the GetObjectAsync with “Operation is not supported on this platform.”, which according to the stack is within the 

     at System.Runtime.InteropServices.OSPlatform.get_Windows()
     at Amazon.Runtime.ClientConfig.get_HttpClientCacheSize()
     at Amazon.Runtime.HttpRequestMessageFactory.CreateConfigUniqueString(IClientConfig clientConfig)
     at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpRequest(Uri requestUri)
     at Amazon.Runtime.Internal.HttpHandler`1.CreateWebRequest(IRequestContext requestContext)
     at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()
     etc….

Interested in your thoughts.

**Comment by normj** [comment]
Could I see your project file? This error usually indicates that some dependency in your project is causing .NET Core 1.1 to be pulled in. If you do a `dotnet publish` on your project do you see System dll being copied to the publish folder?

**Comment by malcernie** [comment]
Hi, thanks for the response.

The .sln contains the following:

{code}
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26730.12
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyApp", "MyApp\MyApp.csproj", "{AB48547D-1DDD-4DEF-B0FB-E96A384DCBFB}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{AB48547D-1DDD-4DEF-B0FB-E96A384DCBFB}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{AB48547D-1DDD-4DEF-B0FB-E96A384DCBFB}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{AB48547D-1DDD-4DEF-B0FB-E96A384DCBFB}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{AB48547D-1DDD-4DEF-B0FB-E96A384DCBFB}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {8B563FE1-F8B3-4CB2-B4E2-DE58B7A55972}
	EndGlobalSection
EndGlobal
{code}

The csproj has:

{code}
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <Version>1.0.14</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.18.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.11.4" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>

</Project>
{code}

A {code}dotnet publish{code} generates

{code}
23/10/2017  17:24           614,912 AWSSDK.Core.dll
24/10/2017  11:21           403,456 AWSSDK.S3.dll
05/11/2016  05:55           450,248 Microsoft.CSharp.dll
18/06/2017  13:57           639,488 Newtonsoft.Json.dll
05/11/2016  05:55            21,856 System.AppContext.dll
05/11/2016  05:55            27,320 System.Buffers.dll
05/11/2016  05:55            93,432 System.Collections.Concurrent.dll
05/11/2016  05:55            88,472 System.Collections.NonGeneric.dll
05/11/2016  05:55            45,984 System.Collections.Specialized.dll
05/11/2016  05:55            21,720 System.ComponentModel.dll
05/11/2016  05:55            36,256 System.ComponentModel.Primitives.dll
05/11/2016  05:55           121,776 System.ComponentModel.TypeConverter.dll
05/11/2016  05:55            35,760 System.Diagnostics.DiagnosticSource.dll
05/11/2016  05:56           114,392 System.Dynamic.Runtime.dll
05/11/2016  05:56            29,592 System.IO.Compression.ZipFile.dll
05/11/2016  05:56            22,432 System.IO.FileSystem.Primitives.dll
05/11/2016  05:56           128,840 System.Linq.dll
05/11/2016  05:56           458,104 System.Linq.Expressions.dll
05/11/2016  05:56            49,352 System.ObjectModel.dll
05/11/2016  05:56            22,392 System.Reflection.Emit.dll
05/11/2016  05:56            22,960 System.Reflection.Emit.ILGeneration.dll
05/11/2016  05:56            22,952 System.Reflection.Emit.Lightweight.dll
05/11/2016  05:56            29,600 System.Reflection.TypeExtensions.dll
05/11/2016  05:57            22,352 System.Runtime.InteropServices.RuntimeInformation.dll
05/11/2016  05:57            71,392 System.Runtime.Numerics.dll
05/11/2016  05:56            31,168 System.Runtime.Serialization.Formatters.dll
05/11/2016  05:57            29,632 System.Runtime.Serialization.Primitives.dll
05/11/2016  05:57            23,472 System.Security.Cryptography.OpenSsl.dll
05/11/2016  05:57            45,504 System.Security.Cryptography.Primitives.dll
05/11/2016  05:57           113,912 System.Text.RegularExpressions.dll
05/11/2016  05:57            50,016 System.Threading.dll
05/11/2016  05:57            25,864 System.Threading.Tasks.Extensions.dll
05/11/2016  05:57           606,592 System.Xml.ReaderWriter.dll
05/11/2016  05:57           111,312 System.Xml.XDocument.dll
05/11/2016  05:57           138,104 System.Xml.XmlDocument.dll
27/10/2017  19:02            73,643 MyApp.deps.json
27/10/2017  19:02             9,216 MyApp.dll
27/10/2017  19:02             1,784 MyApp.pdb
{code}

It's a very simple app at the moment, doesn't appear to be pulling in [code]System.dll[code].  Do you recommend a particular version of the AWS SDK or Newtonsoft to be compatible with the current Lambda offering?

**Comment by normj** [comment]
What I meant by System dll where all of the System.*.dll files in your publish folder which you do have. They are getting drag into the publish folder because you are targeting .NET Core 1.0 but the version 10.0.3 of Newtonsoft.Json that you are referencing has dependencies on the .NET Core 1.1 System packages. 

Can you try changing the version of Newtonsoft.Json to version 9.0.1?

**Comment by malcernie** [comment]
You're a genius, changing to Newtonsoft.Json v9.0.1 solved the problem.  Is there a cheat sheet anywhere on these known issues?

**Comment by normj** [comment]
The clue I look for is if you look at the list of dependencies for a NuGet packages and if references .NETStandard.Library 1.6.1 that means it is requiring .NET Core 1.1. .NET Core 1.0 .NETStandard.Library 1.6.0 was for .NET Core 1.0.

The versioning is really difficult right now but it should be better when we get to the next version of .NET Core Lambda. In .NET Core 2.0 there is no longer a dependency on the .NETStandard.Library NuGet packages that causes most of these problems.

**Comment by mariowood** [comment]
Replied to https://github.com/aws/aws-sdk-net/issues/781 as well, but essentially the fix for me was to downgrade AWSSDK.S3 from 3.3.14 to 3.3.10.

I was unable to downgrade Newtonsoft.Json to 9.0.1 as i'm using the NEST nuget package which has a dependency on Newtonsoft.Json >= 10.0.0

**Comment by Sipsip** [comment]
I have a simliar issue but witjh .NET Core 2.0 using the following references:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="1.0.2" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.22.5" />
    <PackageReference Include="AWSSDK.KeyManagementService" Version="3.3.5.5" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.18.2" />
    <PackageReference Include="Microsoft.Bing.Speech" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.1.3" />
  </ItemGroup>

</Project>

```

getting 

```
One or more errors occurred. (Operation is not supported on this platform.): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
```

Can this also a problem with the Newtonsoft.Json dependency?
