### ISSUE TITLE
X-Ray tracing for lambda proxy missing basic details such as Url and Method

### ISSUE THREAD

**Issue by sudsy** [aws/aws-lambda-dotnet#177]
The only property that is logged when you enable tracing an a lambda proxy using the Amazon.Lambda.AspNetCoreServer package is the StatusCode. 

I can see that the AWSXRayRecorder package is not compatible with netcore so I can't add custom tracing.

Since the Amazon.Lambda.AspNetCoreServer middleware is already installed it would be great if it handled the basic properties you would expect when tracing an http service.

**Comment by normj** [comment]
As you mentioned we don't have the AWSXRayRecorder package working on .NET Core but this is high on our list to get done. And yes I agree once we have the AWSXRayRecorder on .NET Core it should make it very easy to turn on for ASP.NET Core applications, through Lambda or Kestrel, to get the common HTTP metrics you would expect.

**Comment by normj** [comment]
Closing this in favor tracking this feature request with issue https://github.com/aws/aws-sdk-net/issues/500
