### ISSUE TITLE
.NET8 AOT x64 deps.json missing and 

### ISSUE THREAD

**Issue by kopticx** [aws/aws-lambda-dotnet#1772]
### Describe the bug

When I publish my lambda with Native AOT and boostrap as handler I get the error:
`Error: fork/exec /var/task/bootstrap: exec format error Runtime.InvalidEntrypoint`
And in the build logs you see the following message
`Missing deps.json file. Skipping flattening runtime folder because  is an unrecognized format`

Here is the repo 
[https://github.com/kopticx/StyrkMiddleware](url)

### Expected Behavior

We expected the deps.json to be included properly snd stop seeing the error

### Current Behavior

deps.json file is not being included.

### Reproduction Steps

dotnet new lambda.NativeAOT -n NativeAotSample
dotnet lambda deploy-function NativeAotSample

### AWS .NET SDK and/or Package version used

Amazon.Lambda.Core 2.2.0

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 11

**Comment by bhoradc** [comment]
Hi @kopticx, 

Thank you for reporting the issue. 

Can you please confirm if the function handler string is set correctly in your case, as pointed out by @normj in similar [issue](https://github.com/aws/aws-lambda-dotnet/issues/1706#issuecomment-2018909863)?

Regards, 
Chaitanya

**Comment by ashishdhingra** [comment]
@kopticx Good morning. Thanks for reporting the issue. From https://github.com/aws/aws-lambda-dotnet/issues/1706#issuecomment-2018909863, could you please check the function handler string to? It should be just the name of the assembly not the class library style of <assembly>::<type-name>::<method-name>.

Thanks,
Ashish

**Comment by kopticx** [comment]
Well, actually im using the assembly attributes to GenerateMain automatically, and the doc says i have to use the  `<AssemblyName>bootstrap</AssemblyName>` and my `aws-lambda-tools-defaults.json` is supposed to has 

```json
{
  "Information": [""],
  "profile": "",
  "region": "",
  "configuration": "Release",
  "function-runtime": "provided.al2",
  "function-memory-size": 512,
  "function-timeout": 30,
  "function-handler": "bootstrap"
}
```

I tried as you mentioned, but I continue recibing the same error.

What i'm supposed to do? I have to install something more to use the assemblyName bootstrap?

**Comment by kopticx** [comment]
I have updated my `aws-lambda-tools-defaults.json` to this:
```json
{
  "Information": [
    ""
  ],
  "profile": "",
  "region": "",
  "configuration": "Release",
  "function-runtime": "dotnet8",
  "function-memory-size": 512,
  "function-timeout": 30,
  "function-handler": "bootstrap",
  "ANNOTATIONS_HANDLER": "Styrk.Middleware.DbConnector.Lambda.Function::FunctionHandler"
}
```

as the doc `https://aws.amazon.com/es/blogs/compute/introducing-the-net-8-runtime-for-aws-lambda/` says, yet im recibing this error:
`error MSB3073: The command ""/tmp/dotnet/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.6/tools/ilc" @"obj/Release/net8.0/linux-x64/native/bootstrap.ilc.rsp"" exited with code 137. [/tmp/source/src/Styrk.Middleware.DbConnector/Styrk.Middleware.DbConnector.Lambda/src/Styrk.Middleware.DbConnector.Lambda/Styrk.Middleware.DbConnector.Lambda.csproj]`

**Comment by Beau-Gosse-dev** [comment]
I see you've added `"function-runtime": "dotnet8",` in the last message, which is good. .NET 8 AOT should be deployed to the .NET 8 runtime to make sure all the needed dependencies are included. It won't run on the old `provided.al2` as you had it originally. 

I also see a `serverless.template` file, but your repro steps include `dotnet lambda deploy-function`. It you want to use serverless templates, you need to call `dotnet lambda deploy-serverless`. 

I also tried to run your code (From GitHub using `dotnet lambda deploy-function`) on the .NET 8 managed runtime and got the below output which is different. I'm not getting any build issues.
```
INIT_REPORT Init Duration: 29.08 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
INIT_REPORT Init Duration: 82.91 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
START RequestId: 160512d5-b4bc-42d7-b20c-025c521cb16c Version: $LATEST
RequestId: 160512d5-b4bc-42d7-b20c-025c521cb16c Error: Runtime exited without providing a reason
Runtime.ExitError
END RequestId: 160512d5-b4bc-42d7-b20c-025c521cb16c
REPORT RequestId: 160512d5-b4bc-42d7-b20c-025c521cb16c	Duration: 98.72 ms	Billed Duration: 99 ms	Memory Size: 512 MB	Max Memory Used: 9 MB	
```

Can you try deleting your `bin` and `obj` directory to make sure everything is starting clean for the build? Sometimes native AOT builds don't clean the directory correctly and can cause issues. 

The error `Missing deps.json file. Skipping flattening runtime folder because  is an unrecognized format` is not relevant and is expected for native AOT builds.

**Comment by kopticx** [comment]
Hi, i actually just updated my Github code, i changed the value on my template and aws-lambda-tools-defaults.json, and now im having this error `/var/task/bootstrap: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /var/task/bootstrap)` when i try to test my lambda, i have navigating and i found a guy who has the same error but in Go 

It's something relationed with the Docker image? I can't get it

Thanks, greats.

**Comment by Beau-Gosse-dev** [comment]
Please change `"function-runtime": "provided.al2",` to `"function-runtime": "dotnet8",`

Provided Al2 doesn't have a new enough glibc for .NET 8

**Comment by kopticx** [comment]
I just updated the function-runtime as you mentioned and it works, yet im still having problems with the execution, it's like if the Dependency Injection doesn't work with AWS Lambdas AOT, i supposed i have to work without NativeAot and dependency Injection, thanks a lot.

Best regards.

**Comment by Beau-Gosse-dev** [comment]
@kopticx  One thing I'd highly recommend (if you're not already) is to disable AOT and make sure everything is working as expected first before turning it back on. Non-AOT can provide more helpful error messages and AOT only complicates things, so it's good to make sure you're starting from a clean working solution.

**Comment by ashishdhingra** [comment]
> I have updated my aws-lambda-tools-defaults.json to this:
> 
> {
>   "Information": [
>     ""
>   ],
>   "profile": "",
>   "region": "",
>   "configuration": "Release",
>   "function-runtime": "dotnet8",
>   "function-memory-size": 512,
>   "function-timeout": 30,
>   "function-handler": "bootstrap",
>   "ANNOTATIONS_HANDLER": "Styrk.Middleware.DbConnector.Lambda.Function::FunctionHandler"
> }
> as the doc https://aws.amazon.com/es/blogs/compute/introducing-the-net-8-runtime-for-aws-lambda/ says, yet im recibing this error:
> error MSB3073: The command ""/tmp/dotnet/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/8.0.6/tools/ilc" @"obj/Release/net8.0/linux-x64/native/bootstrap.ilc.rsp"" exited with code 137. [/tmp/source/src/Styrk.Middleware.DbConnector/Styrk.Middleware.DbConnector.Lambda/src/Styrk.Middleware.DbConnector.Lambda/Styrk.Middleware.DbConnector.Lambda.csproj]

@kopticx The blog https://aws.amazon.com/es/blogs/compute/introducing-the-net-8-runtime-for-aws-lambda/ specifies to update `aws-lambda-tools-defaults.json` to below:
```JSON
{
  "function-architecture": "x86_64",
  "function-runtime": "dotnet8",
  "function-handler": "<your-assembly-name>",
  "environment-variables",
  "ANNOTATIONS_HANDLER=<your-function-handler>",
}
```
`<your-assembly-name>` is by default name of your project (unless you changed it in project properties).

Please change `function-handler` to your correct assembly name and see if error goes away.

Thanks,
Ashish

**Comment by kopticx** [comment]
Well, after a few weeks, I tried again and I got it, you were right, actually I just need to add `ANNOTATIONS_HANDLER` as environment variable and `FunctionHandler` as value, I didn't need to use `dotnet lambda deploy-serverless` or `function-runtime": ”provided.al2`, thank you all for your help, hopefully soon they will add NativeAOT to S3 and Dynamo.
