### ISSUE TITLE
Environment variables not updating when running lambda update-function-config

### ISSUE THREAD

**Issue by odyth** [aws/aws-lambda-dotnet#178]
Trying to setup my build server to deploy my lambda functions.  I have my build serer upload a config file to S3 then I run `dotnet lambda deploy-function -c Release` command from the Amazon.Lambda.Tools Nuget package.  My aws-lambda-tools-default.json file is below and the uploaded s3 file I set as the ConfigFileKey in the environment-variables.  My code updates, however the environment variables do not.  I tried then running `dotnet lambda update-function-config` after deploy-function and the environment variables still do not update.  Function-timeout and memory-size also do not update when running dotnet lambda update-function-config

```
{
    "region" : "us-east-1",
    "configuration" : "Release",
    "framework"     : "netcoreapp1.0",
    "function-name" : "FunctionName",
    "function-description" : "some description.",
    "function-handler"     : "ProjectNamespace::FunctionName::HandleAsync",
    "function-memory-size" : 128,
    "function-role"        : "FUNCTION_ROLE",
    "function-timeout"     : 30,
    "function-runtime"     : "dotnetcore1.0",
    "function-subnets"     : "FUNCTION_SUBNETS",
    "function-security-groups" : "FUNCTION_SECURITY_GROUPS",
    "environment-variables"    : "\"ConfigFileKey\"=\"config-files/Release/5.5.3/Lambda/LambdaSettings.yaml\""
}
```

**Comment by odyth** [comment]
function-timeout and memory-size also do not update when running dotnet lambda-deploy-function

**Comment by odyth** [comment]
ah looks like these get used when creating a function, but if updating then you need to run 
`dotnet lambda update-function-config

**Comment by odyth** [comment]
Looks like this behavior is by design....

> When redeploying to an existing function or executing dotnet lambda update-function-config only profile, region, framework and configuration are used from this file to avoid accidentally changing any configuration settings on the function.

**Comment by Kralizek** [comment]
It would be nice to have a switch to enable this :)

**Comment by normj** [comment]
I like that idea, seems look a good comprise. The trick is going to be naming that switch :)

Could you open a separate issue to track that feature request?
