### ISSUE TITLE
Additional file type application/wasm to AbstractAspNetCoreFunction.cs

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#1786]
### Describe the feature

Please can you add application/wasm to AbstractAspNetCoreFunction.cs

This is to allow a DotNet Lambda function to serve up wasm files for WebAssembly.

For reference, see https://github.com/aws/aws-lambda-dotnet/issues/1781

Thank you.

### Use Case

So that Dotnet Lambda Blazor can operate in SSR or CSR mode.

### Other Information

The workaround currently is to add to lambdaEntryPoint

    protected override void Init(IHostBuilder builder)
    {
        base.RegisterResponseContentEncodingForContentType("application/wasm", Amazon.Lambda.AspNetCoreServer.ResponseContentEncoding.Base64);
    }

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Standard Lambda Serverless application under DotNet 8

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 11

**Comment by normj** [comment]
This valid to add. If you want to submit a PR that adds the content type that would help get this released sooner.

**Comment by ashishdhingra** [comment]
Changes merged to `dev`. It would be released along with other changes that would be queued shortly.
