### ISSUE TITLE
Give possiblity to fully update function configuration via dotnet commands

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#179]
As in #178, currently some of the settings, like the environment variables, set in the `aws-lambda-tools-defaults.json` are taken into consideration only during the first deploy via `dotnet lambda deploy-function`. Even using `dotnet lambda update-function-config`, will not update the settings accordingly.

The documentation says that this is an intended behavior but it makes it difficult for witty users.
As @normj stated [here](https://github.com/aws/aws-lambda-dotnet/issues/178#issuecomment-341634205), it would be a good compromise to have a switch that allows us to override the default behavior.

When deploying a function the first time,
`dotnet lambda deploy-function --fully-update-configuration`, the switch has no effect as we are already using the whole set of settings.

When deploying a function afterwards,
`dotnet lambda deploy-function --fully-update-configuration`, the switch causes the whole set of settings to be pushed into the function configuration, as if it were a first-deploy.

When updating a function configuration,
`dotnet lambda update-function-config --fully`, the switch causes the whole set of settings to be pushed into the function configuration.

Note, the switches' name are just a suggestion and are not part of the feature request: any value will work.

**Comment by normj** [comment]
I pushed out version **1.9.0** of **Amazon.Lambda.Tools** which has a new **--apply-defaults** switch that if set to true will use the values from **aws-lambda-tools-defaults.json** when updating an existing function.

**Comment by Kralizek** [comment]
Thanks @normj!

Does the flag work on both ’deploy-function’ and ’update-function-config’?

**Comment by normj** [comment]
Yes, it works for both and the **--apply-defaults** switch can be in the **aws-lambda-tools-defaults.json** file as well like the other switches.
