### ISSUE TITLE
Missing documentation links.

### ISSUE THREAD

**Issue by dsiz** [aws/aws-lambda-dotnet#1790]
### Describe the issue

Almost all the documentation links in https://github.com/aws/aws-lambda-dotnet/tree/master/PowerShell#community-posts

except "[AWS Lambda and PowerShell](https://www.yobyot.com/aws/lambda-powershell/2018/09/13/) - By Alex Neihaus" are either unavailable or thow a 404

### Links

https://github.com/aws/aws-lambda-dotnet/tree/master/PowerShell#community-posts

**Comment by bhoradc** [comment]
Hi @dsiz, 

Thank you for recommending a documentation fix on the [README.md ](https://github.com/aws/aws-lambda-dotnet/tree/master/PowerShell#community-posts) section. I will review this further with the team. 

Regards, 
Chaitanya

**Comment by ashishdhingra** [comment]
Removed Community Posts section from [PowerShell/README.md](https://github.com/aws/aws-lambda-dotnet/tree/master/PowerShell).
