### ISSUE TITLE
Lambda tool zipping on OS X doesn't work with path with a space

### ISSUE THREAD

**Issue by adamhathcock** [aws/aws-lambda-dotnet#18]
Here's the print before it tries to zip:
```
Zipping publish folder /Users/adam/code/new stack/Narochno.Lambda.Slack/test/EventTester/bin/Release/netcoreapp1.0/publish to /Users/adam/code/new stack/Narochno.Lambda.Slack/test/EventTester/bin/Release/netcoreapp1.0/EventTester.zip
```

this warning follows that line, probably from the zip command line tool:
```
... publish: 	zip warning: name not matched: stack/Narochno.Lambda.Slack/test/EventTester/bin/Release/netcoreapp1.0/EventTester.zip
```

looks like something needs to be quoted

**Comment by normj** [comment]
Thanks for letting us know. I'll take a look.

**Comment by normj** [comment]
I pushed out version 1.0.4-preview1 of Amazon.Lambda.Tools that fixes the issue with spaces in the path. Thanks again for letting us know about the issue.

**Comment by adamhathcock** [comment]
Just sat down to get the email from you.  It works, thanks!
