### ISSUE TITLE
Unable to make connection with Npgsql (.NET Core) in AWS Lambda to PostgreSQL RDS

### ISSUE THREAD

**Issue by KFayal** [aws/aws-lambda-dotnet#180]
I've been beating my head on the wall for this for quite a few days now.  Essentially where I am now is that I have taken my Lambda function outside of my VPC, then I've opened my RDS to be publicly accessible from anywhere on the PostgreSQL port.  I can connect using this function from my dev workstation to the RDS, but for the life of me, this is not happening from my Lambda function.  At first I was spinning my wheels on the whole permissions thing then I realized when I was able to connect to it from my dev workstation and run the function I've written to do a simple FirstOrDefault query.

I am able to compile and publish the lambda function from Visual Studio 15.4.2.  I'm using Npgsql.EntityFrameworkCore.PostgreSQL 1.0.2, (Npgsql 3.1.8) - the last version to be allowed because after that they included the .netstandard 1.6.1 libraries, which is blocked from publishing via the Lambda tooling inside Visual Studio 15.4.2.   

Anyway, here's the error I get when I try to run this simple query.  

```
var contextOptions = new DbContextOptionsBuilder()
                    .UseNpgsql(cnxString)
                    .Options;
// Now that we have the connection set up the database connection
TestEntities.TestDbContext _db = new TestEntities.TestDbContext(contextOptions);

var result = _db.TestTable.FirstOrDefault(tbl => tbl.Recordid == 5);
```
Connection refused    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
   at Npgsql.ConnectorPool.Allocate(NpgsqlConnection conn, NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnection.OpenInternal()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Tester.Function.Test()

I've modified the code a little bit just to isolate the Npgsql code.

I have also added the NetworkInformation.dll library manually to my aws-lambda-tools-defaults.json file as some have suggested in other posts, and I see that file is getting added to the package .zip file.

"additional-files": [
    "runtimes/linux/lib/netstandard1.3/System.Net.NetworkInformation.dll"
  ]

Anyway, I'm just hoping someone has ran into this issue, and can point out what I'm doing wrong.

**Comment by normj** [comment]
The security group you specified for the Lambda configuration did you add it as an ingress rule to the security group that your RDS database is using. Even if they are the same security group you need do that which will say everything in that security group can access each other.

**Comment by KFayal** [comment]
Norm, Thanks for the response.  Yes, I had a security group named sg-XXXXaf7a, and inside that security group I have two inbound rules - one allowing PostgreSQL traffic from my public workstation IP, the other allowing PostgreSQL traffic from the same Security Group sg-XXXXaf7a.  But was still getting that same error.

**Comment by HaroonSaid** [comment]
Check your project  to ensure you don't have any code is not pulling in .NET Standard 1.6.1.
It took me several days of trial and error to figure out that System.Data.SqlClient version 4.3 (even that it said it would work with .net-standard 1.3) was not compatible and I had to go back to 4.1 
Did you try Npgsql.EntityFrameworkCore.PostgreSQL 1.0?

**Comment by KFayal** [comment]
HaroonSaid, Thanks for the suggestion.  The dependencies list shows I'm clear of .NET Standard 1.6.1.  You can't even publish to Lambda with the Visual Studio tooling if you go above 1.6.0, or .netcoreapp 1.0.  I am able to publish, it's just the connection refused issue.

**Comment by Kralizek** [comment]
chiming in because I'm looking into PostgreSQL too. Did you try with an empty Lambda that only connects to the database?

**Comment by KFayal** [comment]
No I did not.  I have moved on to another solution.  Didn't have time to figure this out.

**Comment by normj** [comment]
I'm gonna close this because with .NET Core 2.0 Lambda support the driver issues with .NET Core 1.1 and .NETStandard.Library 1.6.1 go away.
