### ISSUE TITLE
APIGatewayHttpApiV2ProxyRequest.RequestContext.Http is coming back as null even though it's not nullable

### ISSUE THREAD

**Issue by AgStarRay** [aws/aws-lambda-dotnet#1850]
### Describe the bug

I've been trying to migrate a .NET 7 AOT project to a .NET 8 AOT one. After much difficulty, I decided to try out the example here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html
I got this to deploy and there's nothing apparently wrong with the integration, but when I try to use `apigProxyEvent.RequestContext.Http`, it comes back as null. I added `[JsonSerializable(typeof(APIGatewayHttpApiV2ProxyRequest.HttpDescription))]` to the LambdaFunctionJsonSerializerContext, but it doesn't seem to have any effect.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

APIGatewayHttpApiV2ProxyRequest in the handler to have a value of type HttpDescription within RequestContext, containing information such as Method, Protocol, SourceIp, UserAgent, etc.

### Current Behavior

apigProxyEvent.RequestContext has a value, but apigProxyEvent.RequestContext.Http is null

### Reproduction Steps

Follow all the steps in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html
Run `sam build; sam deploy --guided` to test if the example works.
Add this code at the beginning of FunctionHandler
```csharp
        if(apigProxyEvent.RequestContext.Http == null) {
            return new APIGatewayHttpApiV2ProxyResponse
            {
                Body = """{"message":"Http is null!!"}""",
                StatusCode = 502,
                Headers = new Dictionary<string, string> { { "Content-Type", "application/json" } }
            };
        }
```
Run `sam build; sam deploy` to see if Http has a value.

### Possible Solution

If Http is meant to be null sometimes, mark this field as nullable.
Or if it's supposed to have a value, fix or offer some serialization steps to get it to exist.

### Additional Information/Context

I updated some of the referenced packages in hopes that it was fixed already.

### AWS .NET SDK and/or Package version used

    <PackageReference Include="Amazon.Lambda.Core" Version="2.3.0" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.11.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.1" />

### Targeted .NET Platform

.NET 8 AOT

### Operating System and version

Windows 11

**Comment by AgStarRay** [comment]
Adding a bit more context, if I use `JsonSerializer.Serialize(apigProxyEvent, typeof(APIGatewayHttpApiV2ProxyRequest), LambdaFunctionJsonSerializerContext.Default)` I get this response (censored):
```json
{
  "Version": null,
  "RouteKey": null,
  "RawPath": null,
  "RawQueryString": null,
  "Cookies": null,
  "Headers": null,
  "QueryStringParameters": null,
  "RequestContext": {
    "AccountId": "<value>",
    "ApiId": "<value>",
    "Authorizer": null,
    "DomainName": "testPrefix.testDomainName",
    "DomainPrefix": "testPrefix",
    "Http": null,
    "RequestId": "<guid>",
    "RouteId": null,
    "RouteKey": null,
    "Stage": "test-invoke-stage",
    "Time": null,
    "TimeEpoch": 0,
    "Authentication": null
  },
  "Body": null,
  "PathParameters": null,
  "IsBase64Encoded": false,
  "StageVariables": null
}
```
RequestContext seems to be the only thing serialized in the request from what I see, where some properties are filled in.

**Comment by ashishdhingra** [comment]
@AgStarRay Good afternoon. If you refer class [ProxyRequestContext](https://github.com/aws/aws-lambda-dotnet/blob/34f39fde0eafb80eeb9c95f9eea17ca49f764c3b/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayHttpApiV2ProxyRequest.cs#L77C22-L77C41), it has the [Http](https://github.com/aws/aws-lambda-dotnet/blob/34f39fde0eafb80eeb9c95f9eea17ca49f764c3b/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayHttpApiV2ProxyRequest.cs#L107) property which is of type [HttpDescription](https://github.com/aws/aws-lambda-dotnet/blob/34f39fde0eafb80eeb9c95f9eea17ca49f764c3b/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayHttpApiV2ProxyRequest.cs#L217). It is a reference type and hence contain a `null` value. The [APIGatewayHttpApiV2ProxyRequest](https://github.com/aws/aws-lambda-dotnet/blob/34f39fde0eafb80eeb9c95f9eea17ca49f764c3b/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayHttpApiV2ProxyRequest.cs#L11C18-L11C49) is populated by the HTTP API integration, refer [Create AWS Lambda proxy integrations for HTTP APIs in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) for payload format guidance. The .NET Lambda library defines a POCO class that serializes/deserializes request/response format. Are you getting any runtime error during deserialization process? Or is it a recommendation to mark it as `null` based on new .NET 8/9 language features (in that case this should be marked a a feature request for new framework targets)?

Thanks,
Ashish

**Comment by AgStarRay** [comment]
If APIGatewayHttpApiV2ProxyRequest is meant for an HTTP API, then why does the example deploy a REST API?

According to [the original steps I took](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html), the SAM template seems to deploy the function with a REST API event (`Type: Api`), not an HTTP API event (`Type: HttpApi`). I assume that's what is supposed to be used. Regardless, I switched it from APIGatewayHttpApiV2ProxyRequest to APIGatewayProxyRequest and I was able to get all the details I needed from a REST API.

I did not see any runtime errors in Cloudwatch, but I think since the template was deploying a REST API and using a class meant for HTTP APIs that it failed to properly teach me how to setup a REST API. It doesn't seem like there's a bug in the AWS packages related to this, but rather it's just a mistake in the tutorial; either the SAM template needs to be updated to have `Type: HttpApi` or the class being used in the bootstrap builder should be `APIGatewayProxyRequest`. I don't think it's necessary to integrate nullable types because of this.

**Comment by ashishdhingra** [comment]
@AgStarRay Good morning. Please refer to code comment https://github.com/aws/aws-lambda-dotnet/blob/943862ff5c96e2508f4278c1f869379202fec9a9/Blueprints/BlueprintDefinitions/vs2022/AspNetCoreWebAPI/template/src/BlueprintBaseName.1/LambdaEntryPoint.cs#L11 in blueprint:
```C#
...
public class LambdaEntryPoint :

    // The base class must be set to match the AWS service invoking the Lambda function. If not Amazon.Lambda.AspNetCoreServer
    // will fail to convert the incoming request correctly into a valid ASP.NET Core request.
    //
    // API Gateway REST API                         -> Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    // API Gateway HTTP API payload version 1.0     -> Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    // API Gateway HTTP API payload version 2.0     -> Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction
    // Application Load Balancer                    -> Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction
    // 
    // Note: When using the AWS::Serverless::Function resource with an event type of "HttpApi" then payload version 2.0
    // will be the default and you must make Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction the base class.

    Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
{
...
```

For REST API, you would need to use `Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction`, which you confirmed works.

Regarding SAM template updating, our team does not own SAM templates. Please open the issue at https://github.com/aws/aws-sam-cli to report the issue, it should be corrected by SAM CLI team.

Thanks,
Ashish
