### ISSUE TITLE
DKIM failing SES

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#186]
I have recently started testing SES receive mail.

I noticed that none of the replies like today "Re: [aws/aws-lambda-dotnet] Memory Leak Encountered in Lambda based AspNetCore Kestrel Hosting (#185)" are getting through.

This is because in AWS Lambda,  receipt.dkimVerdict.status is returning FAIL for these messages and are getting bounced (deliberate as per ses-bounce).

Is anyone else seeing this DKIM fail?

I know this is not directly related to aws-lambda-dotnet but missing messages is a problem.

**Comment by ibuchan72390** [comment]
I got an email notification from that post when normj replied about 1 hour ago.

**Comment by normj** [comment]
You might want to ask this question in the SES forums. Somebody from the SES team would have a better understanding of what is going on as this is more of a service question than a .NET Lambda question.

**Comment by genifycom** [comment]
Will do Norm.
