### ISSUE TITLE
Environment Variable in Running Serverless ASP.NET Core Web APIs 

### ISSUE THREAD

**Issue by GeraldBauerImplan** [aws/aws-lambda-dotnet#189]
I see that the "Running Serverless ASP.NET Core Web APIs" is no longer a Preview and began investigating how to use. 

I am trying to determine how the env.EnvironmentName is defined/set and the ability to change it for my other environments (Development, Integration, and Beta). I am not seeing the variable "ASPNETCORE_ENVIRONMENT" in the Environment Variables grid (csproj => right click and chose "Properties" => select "Debug" tab). I have added ASPNETCORE_ENVIRONMENT and set it to Development - it is picked up. Without having ASPNETCORE_ENVIRONMENT, the environment name is set to Production. 

I know how to set ASPNETCORE_ENVIRONMENT on a Windows machine but not on an AWS Serverless (AWS Lambda?). I am not going to presume that it is defined in and picked up from the Lambda Console "Environment variables" since this AWS methodology did not work in EC2 instances nor Elastic Beanstalks. 

Please advise on how to set the env.EnvironmentName on an AWS Serverless so that it is picked up. Also please tell me if it is a departure from current .NET Core method of getting the environment name value. We are dependent on knowing that variable value for our environment specific values. Thank you for your time.

**Comment by normj** [comment]
You would set the ASPNETCORE_ENVIRONMENT environment variable in the `serverless.template` file which is a CloudFormation template. Here is an example with the value for ASPNETCORE_ENVIRONMENT coming in as a parameter. If you use this template be sure to update the `Handler` back to your project's handler.

```json
{
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Transform" : "AWS::Serverless-2016-10-31",
  "Description" : "An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.",

  "Parameters" : {
	"AspNetCoreEnvironment" : {
	    "Type" : "String",
        "Description" : "The value for the ASPNETCORE_ENVIRONMENT environment variable",
        "Default" : "Production"
	}
  },

  "Resources" : {

    "Get" : {
      "Type" : "AWS::Serverless::Function",
      "Properties": {
        "Handler": "ServerlessSetAspNetCoreEnvironment::ServerlessSetAspNetCoreEnvironment.LambdaEntryPoint::FunctionHandlerAsync",
        "Runtime": "dotnetcore1.0",
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [ "AWSLambdaFullAccess" ],
        "Environment" : {
          "Variables" : {
            "ASPNETCORE_ENVIRONMENT" : { "Ref" : "AspNetCoreEnvironment" }
          }
        },
        "Events": {
          "PutResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/{proxy+}",
              "Method": "ANY"
            }
          }
        }
      }
    }
  },

  "Outputs" : {
  }
}
```

You can also adjust the environment variables on the configuration tab in the Lambda function view inside the Visual Studio toolkit. 

Also the ASP.NET Core Web API is still preview. Our plan is to GA that library soon with the upcoming .NET Core 2.0 support.

**Comment by GeraldBauerImplan** [comment]
Thank you for your quick response. (So much to learn, little time allowed.) Didn't see the Preview in the fine print ;-)

**Comment by normj** [comment]
I feel you on the so much to learn and so little time.
