### ISSUE TITLE
LexEvent.CurrentIntent.SlotDetails missing?

### ISSUE THREAD

**Issue by J4S0Nc** [aws/aws-lambda-dotnet#190]
Based on the [docs](http://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html) there is a slotDetails object on the current intent. How do I get this object information in C#? 

```
{
  "currentIntent": {    
    "slotDetails": {
      "slot name": {
        "resolutions" : [
          { "value": "resolved value" },
          { "value": "resolved value" }
        ],
        "originalValue": "original text"
      },
      "slot name": {
        "resolutions" : [
          { "value": "resolved value" },
          { "value": "resolved value" }
        ],
        "originalValue": "original text"
      }
    },...
```

**Comment by J4S0Nc** [comment]
To add a little more detail on why this is needed, we are using amazon.Time slot types:

http://docs.aws.amazon.com/lex/latest/dg/built-in-slot-time.html

>  Amazon Lex uses the slotDetails attribute of a Lambda event to pass resolutions for the ambiguous times to your Lambda function. For example, if your bot prompts the user for a delivery time, the user can respond by saying "10 o'clock." This time is ambiguous. It means either 10:00 AM or 10:00 PM. In this case, the value in the slots map is null, and the slotDetails entity contains the two possible resolutions of the time. Amazon Lex inputs the following into the Lambda function:
```

"slots": {
   "deliveryTime": null
},
"slotDetails": {
   "deliveryTime": {
      "resolutions": [
         {
            "value": "10:00"
         },
         {
            "value": "22:00"
         }
      ]
   }
}
```

**Comment by normj** [comment]
Thanks for letting us know. Looks like our event class is out of date and I'll take a look at updating it.

**Comment by normj** [comment]
I pushed out version 1.0.2 of Amazon.Lambda.LexEvents that is updated to contain slot details

**Comment by normj** [comment]
Closing as I believe this is fixed. Feel free to reopen if that is not the case.
