### ISSUE TITLE
Argument --function-publish does not create a new version

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-lambda-dotnet#194]
Expected Behavior
------------
`dotnet lambda deploy-function --function-publish true` should, for an existing function, update the code and create a new version, updating $latest.

Actual Behavior
------------
Code for an existing function is updated, but no versions are created.

[Looking at the code](https://github.com/aws/aws-lambda-dotnet/blob/551bd59bd286b726aa382aa6805863ab7dadf540/Libraries/src/Amazon.Lambda.Tools/Commands/DeployFunctionCommand.cs#L250) it appears `Publish` is not provided to `LambdaClient.UpdateFunctionCodeAsync`, regardless of the status of the command line argument.

**Comment by normj** [comment]
Thanks for letting us know. I see for an existing functions I need to make a separate call to LambdaClient.PublishVersionAsync. I'll make that fix and it will go out with the upcoming .NET Core 2.0 support.

**Comment by ddrinka** [comment]
According to [Introduction to AWS Lambda Versioning](https://docs.aws.amazon.com/lambda/latest/dg/versioning-intro.html) and [UpdateFunctionCode](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html) you should be able to just pass `Publish: true` like I mentioned above to atomically update the Lambda function's code and create a new version.

**Comment by normj** [comment]
The problem is that via the deploy command you can be updating both the function configuration and the function code. And you can't publish on the UpdateFunctionConfiguration which currently happens after UpdateFunctionCode.

**Comment by normj** [comment]
This fix went out today as part of `Amazon.Lambda.Tools` 2.0.0. The 2.0.0 release of this library supports both .NET Core 1.0 and .NET Core 2.0.
