### ISSUE TITLE
Redirect to Login 

### ISSUE THREAD

**Issue by tiemtran** [aws/aws-lambda-dotnet#195]
Hi all. I can not  auto redirect when user not login. Asp.Net core 2.0

![screenshot_43](https://user-images.githubusercontent.com/16088066/34604169-6d4b3250-f239-11e7-969a-24eb150562bf.png)

**Comment by normj** [comment]
Closing as this can't be a Lambda .NET Core question since .NET Core 2.0 is not supported yet in Lambda.
