### ISSUE TITLE
How to run deploy-serverless without specific project context ?

### ISSUE THREAD

**Issue by tsibelman** [aws/aws-lambda-dotnet#197]
I see that it is possible to give a package to deploy-serverless via parameter so it looks like It should be easy to separate package and deploy into two different steps on a build server, but it's not clear how to run deploy-serverless with no context of a specific project.

Is it possible to run deploy-serverless with no context of a specific project?

**Comment by normj** [comment]
There is not a great answer for this right now. Right now how CLI extensions work they are based on a project. It looks like in .NET Core 2.1 they are going to address this issue and make tools be installed globally.

https://dasmulli.blog/2018/01/23/exploring-global-net-core-tools/?utm_content=buffer37bd1&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by Kralizek** [comment]
Wow! This would be great to have! Especially in a CI context, most of the dotnet commands work at solution level but lambda needs to be executed at project level...

**Comment by normj** [comment]
I'm going to close this as there isn't anything we are going to do now. When we have the Global tools feature in .NET Core we will revisit this idea. I don't want to do anything hacky now when there is a better long term solution coming.

**Comment by tsibelman** [comment]
Thank you, Norm for the information we would be waiting for this.
