### ISSUE TITLE
AWS Lambda and .Net synchronization context

### ISSUE THREAD

**Issue by pawepaw** [aws/aws-lambda-dotnet#198]
Hi,

How aws lambda c# dlls are loaded and run? What runtime is it? Are they hosted somehow under asp.net core or how it's done?

I'm asking because of synchronization context. In asp.net core they removed it and you can block async code without worrying about deadlocks https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html So is there synchronization context in aws lambda or not?

I'm asking because i believe i got deadlock once on .Result with ThreadCancelledException and i am not sure if that was real.

**Comment by gokarnm** [comment]
@pawepaw , we don't create a synchronization context in the host that loads and executes the  Lambda function. Are you seeing a [synchronization context](https://docs.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext.current?view=netcore-1.0#System_Threading_SynchronizationContext_Current) being available in your code?

**Comment by pawepaw** [comment]
ok you are right. Rechecked that and deadlock was in our sdk which was calling aws lambda from asp.net code. Thanks and sorry for bothering!
