### ISSUE TITLE
Unable To Package under AWS CodeBuild

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-lambda-dotnet#199]
I have created a AWS Lambda project using VS2017

I have a CodeBuild project for it (Ubuntu .net core 2.0)

I am running the command "dotnet lambda package" in CodeBuild, but I am receiving an error of "It was not possible to find any compatible framework version"

The project builds just fine, it's the package command that is failing.

It seems as though the CLI tools call to "dotnet lambda package" is attempting to find the 1.0.0 version of .net core.

Below is a log snippet.

Any thoughts?

Thanks!

[Container] 2018/01/16 03:39:10 Running command dotnet lambda package -c release --framework netcoreapp2.0

03:39:14
It was not possible to find any compatible framework version
It was not possible to find any compatible framework version

03:39:14
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.

03:39:14
- Check application dependencies and target a framework version installed at:
- Check application dependencies and target a framework version installed at:

03:39:14
/

03:39:14
- Alternatively, install the framework version '1.0.0'.
- Alternatively, install the framework version '1.0.0'.

03:39:14

03:39:14
[Container] 2018/01/16 03:39:13 Command did not exit successfully dotnet lambda package -c release --framework netcoreapp2.0 exit status 131
[Container] 2018/01/16 03:39:13 Command did not exit successfully dotnet lambda package -c release --framework netcoreapp2.0 exit status 131

**Comment by hounddog22030** [comment]
This issue can be demonstrated with a CodeBuild - .net core 2 configuration with the below buildspec.yaml

Is this a lambda thing or a codebuild thing?

version: 0.2
phases:
  build:
    commands:
      - dotnet new -i Amazon.Lambda.Templates::*
      - dotnet new lambda.S3 --name Issue
      - cd Issue/src/Issue
      - dotnet restore
      - dotnet lambda package

**Comment by normj** [comment]
I'll take a look

**Comment by normj** [comment]
I see the problem and I'm verifying a fix.

**Comment by normj** [comment]
I just pushed version 2.0.1 of `Amazon.Lambda.Tools` that fixes the issue. Sorry about that.

**Comment by hounddog22030** [comment]
I think that did it.  I can now package.  I won't have a chance to test the output until later tonight, but the zip file passes a manual/visual inspection.

Thanks for the quick turnaround.
