### ISSUE TITLE
package/deploy-serverless is packaging AspNetCore dependencies (Amazon.Lambda.Tools v2.0.1)

### ISSUE THREAD

**Issue by Shockolate** [aws/aws-lambda-dotnet#201]
Hello,
As outlined in [the re:Invent video](https://youtu.be/IfF1E2RJ6Do?t=24m6s), it is my understanding that the lambda compute substrate has the AspNetCore package stored locally. The demo shows a small deployment package with no AspNetCore dependencies.

However, when using the latest tools version for .NET Core 2.0 support, I notice that the AspNetCore dependencies are being packaged, causing a package 10x the size in the video. Is this a bug, or a feature yet to be released?

It is crucial to minimize deployment package size to minimize cold-start time.

EDIT: I am using the exact same NuGet packages and versions as defined in the WebAPI Blueprint.

EDIT2: How I'm calling those CLI tools. Excuse the Ruby-isms:
Package:
```ruby
  Dir.chdir(File.join(SRC_DIR, APPLICATION_NAME)) do
    cmd = 'dotnet lambda package ' \
    '--configuration Release ' \
    '--framework netcoreapp2.0 ' \
    "--output_package #{File.join(PACKAGE_DIR, 'deployment_package.zip')} " \
    '/maxcpucount:1'
    puts "Executing command: #{cmd}"
    raise 'Error packaging.' unless system(cmd)
  end
```
Deployment
```ruby
  Dir.chdir(File.join(SRC_DIR, APPLICATION_NAME)) do
    cmd = 'dotnet lambda deploy-serverless ' \
    "--region #{region[:region]} " \
    '--configuration Release ' \
    '--framework netcoreapp2.0 ' \
    "--package #{File.join(PACKAGE_DIR, 'deployment_package.zip')} " \
    "--s3-bucket <BucketNamePrefix>-#{region[:region]} " \
    '--s3-prefix DeploymentPackages/ ' \
    "--template #{File.join(ROOT, 'serverless.infrastructure.json')} " \
    '--template-parameters ' \
      "ServiceNameParameter=#{APPLICATION_NAME};" \
      "EnvironmentParameter=#{environment} " \
    "--stack-name #{stack_name} " \
    '--stack-wait true '
    puts "Executing command: #{cmd}"
    raise 'Error deploying to environment!' unless system(cmd)
  end
```

**Comment by normj** [comment]
Is this a Web API project created before updating Visual Studio to the latest toolkit? Can you share the csproj file?

**Comment by Shockolate** [comment]
The original solution was a Web API Project (with Tests) that was created with the blueprint from the previous VS Toolkit.
When the latest version was released, I downloaded & installed it, and created a parallel project with the same Blueprint.

I then made changes to the original solution:
* Changed the Target Framework (in VS) to .NET Core 2.0
* Manually changed the source files (copy-paste)
* Uninstalled all NuGet packages (via package manager)
* Installed the exact NuGet Packages from the parallel (new) WebAPI Solution.
* Manually changed the version in the .csproj to use the tools version 2.0.1
* cleaned, restored, and tried to package

Thanks for your attention, @normj 

My .csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="2.0.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.4" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.0.1" />
  </ItemGroup>

</Project>
```

**Comment by normj** [comment]
Ah I forgot in the .NET Core project template I set the Sdk at the root to **Microsoft.NET.Sdk**. I did that to prevent the refs folder being generated in the package bundle. Probably wasn't my best idea :)

Can you update 
```xml
<Project Sdk="Microsoft.NET.Sdk">
```
to
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

I'm finishing up my blog post on Serverless ASP.NET Core, I'll add a note about this migration detail.

**Comment by Shockolate** [comment]
That did the trick!
Thanks, @normj
