### ISSUE TITLE
Missing CsharpHandlers files

### ISSUE THREAD

**Issue by VinditCo** [aws/aws-lambda-dotnet#202]
Hello,

Using latest .NET Core 2.1.4, the Serverless Framework build command :
_dotnet lambda package --configuration release --framework netcoreapp2.0 --output-package bin/release/netcoreapp2.0/deploy-package.zip_

fails to create the following files
CsharpHandlers.deps
CsharpHandlers.dll
CsharpHandlers.pdb

The function then fails to run.

Anyone having the same issue ? Does the build command need additional flags to create CsharpHandlers?

**Comment by Shockolate** [comment]
Can't really help you until you provide more information about your project (the files, deps, etc). I don't know what those 3 files are for, or why they're important.

My inkling is that it's an issue with the Serverless Framework.

**Comment by VinditCo** [comment]
I've looked into this a bit more and I think you're right. The default syntax for function handlers in the Serverless Framework YML setup is :  
_receivepost:
    handler: CsharpHandlers::namespace::class etc_

Thanks for the quick reply!
