### ISSUE TITLE
Question - Are Self Contained Deployments supported?

### ISSUE THREAD

**Issue by dls314** [aws/aws-lambda-dotnet#203]
Mostly in the title.

So far, my experience is that it's not possible to use an SCD, but I could easily be doing something incorrectly.

This comes up for supporting new (patch) versions for the runtime as suggested in these comments.

https://github.com/aws/aws-lambda-dotnet/issues/149#issuecomment-356675040
https://github.com/aws/aws-lambda-dotnet/issues/149#issuecomment-357908328
https://github.com/aws/aws-lambda-dotnet/issues/149#issuecomment-357938402

When trying to use an SCD, I alternate between the following errors when I try to test the function

* `Failed to bind to CoreCLR at '/var/task/libcoreclr.so'` (if there is an empty *.runtimeconfig.json)
* `Could not find the required '*.runtimeconfig.json'. This file should be present at the root of the deployment package.` (if there is no *.runtimeconfi.json)

**Comment by gokarnm** [comment]
@dls314 , Lambda only supports [FDD](https://docs.microsoft.com/en-us/dotnet/core/deploying/#framework-dependent-deployments-fdd). We don't have plans to support SCD currently.
