### ISSUE TITLE
Unable to find *.deps.json file that contains periods

### ISSUE THREAD

**Issue by Guitrum** [aws/aws-lambda-dotnet#204]
We currently have a project that has the namespace of ABC.API.XYZ.Admin

When the project is published and zipped, it creates a ABC.API.XYZ.Admin.deps.json file and uploads it to the lambda function on AWS. But upon testing the function, I get the following error:

```
{
  "errorType": "LambdaException",
  "errorMessage": "Could not find the required 'Admin.deps.json'.  This file should be present at the root of the deployment package."
}
```

After trying different namespaces, project names, assembly names, it appears that the whatever is trying to read the *.deps.json file is truncating the ABC.API.XYZ. from the file name and claiming it cannot find it. Is this a bug?

EDIT: it is worth noting that this is with the out of the box project only adding the necessary tweaks to the serverless.template to get it deployable to AWS

**Comment by sstevenkang** [comment]
Hey thanks for reporting this.  Could you describe in detail the step to create a lambda function?  Did you use AWS Console, VS Toolkit, or dotnet CLI?  

If you updated the Lambda function through AWS Console, what was the exact Handler string you used?

**Comment by Guitrum** [comment]
@sstevenkang Sure thing:

1. Create a new AWS Serverless Application with Tests (.NET Core) project in Visual Studio 2017. Make sure the project is named with periods (i.e. ABC.API.XYZ.Admin.csproj) and that the namespaces are also named with periods (i.e. ABC.API.XYZ.Admin).
2. Modify the serverless.template file to allow for a publish to AWS Lambda to work (I believe this just requires the Resources/ProxyFunction/Properties/Role to be filled out)
3. Right click the project and say Publish to AWS Lambda. Set up the proper region and authentication.
4. Create a brand new stack and S3 bucket by typing in new names. Click Publish.
5. Once the stack is provisioned and the update is complete, visit the Lambda function in AWS.
6. Configure a new test event using the API Gateway AWS Proxy template.
7.  Scroll to the bottom of the template and change the POST to a GET
8. Remove the pathParameters element completely
9. Change path to be "api/values"
10. Save the test and run it.
11. Observe the error message.

Here is the handler string:

`Admin::Admin.LambdaEntryPoint::FunctionHandlerAsync`

Let me know if any of those repro steps do not work for you or if you need anything else.

**Comment by sstevenkang** [comment]
@Guitrum , in the publish directory, what's the name of the DLL?  From the handler string you provided, it looks like the assembly is `ABC.API.XYZ.Admin.dll` but the handler names is telling Lambda to look for `Admin.dll`

The `:` delimited string needs to be the full assembly name.  See documentation [here](https://docs.aws.amazon.com/lambda/latest/dg/dotnet-programming-model-handler-types.html) under **Handler Signatures** section.

**Comment by Guitrum** [comment]
@sstevenkang Looks like that was the problem. Thank you for looking at this so quickly! Everything is working.
