### ISSUE TITLE
`dotnet lambda package` no longer respects `PreserveCompilationContext`

### ISSUE THREAD

**Issue by andycmaj** [aws/aws-lambda-dotnet#206]
My application makes use of the `DependencyContext.CompileLibraries` API, and no longer breaks when packaged with `Amazon.Lambda.Tools` **2.0.1**.

This seems to be due to compilation context no longer being present in my application's `.deps.json` file.

Repro:

1. run `dotnet publish` on a `.csproj` with `<PreserveCompilationContext>true</PreserveCompilationContext>`.
2. observe the generated `.deps.json`
```json
...
"targets": {
    ".NETCoreApp,Version=v1.0": {
      "thechunnel.activityservice/1.0.0": {
        "dependencies": {
          "AWSSDK.Core": "3.3.17",
          "Amazon.Lambda.Core": "1.0.0",
          "Amazon.Lambda.Serialization.Json": "1.0.0",
          "Microsoft.NETCore.App": "1.0.5",
          "TheChunnel.Activities.Common": "1.0.0",
          "TheChunnel.ActivityModules": "1.0.0",
          "TheChunnel.ServiceCommon": "1.0.0"
        },
        "runtime": {
          "TheChunnel.ActivityService.dll": {}
        },
        "compile": {
          "TheChunnel.ActivityService.dll": {}
        }
      },
...
```
3. run `dotnet lambda package` on the same project and unzip the resulting lambda package archive and inspect the `.deps.json`.
```json
...
  "targets": {
    ".NETCoreApp,Version=v2.0": {},
    ".NETCoreApp,Version=v2.0/linux-x64": {
      "TheChunnel.ActivityService/1.0.0": {
        "dependencies": {
          "Amazon.Lambda.Core": "1.0.0",
          "Amazon.Lambda.Serialization.Json": "1.0.0",
          "TheChunnel.Activities.Common": "1.0.0",
          "TheChunnel.ActivityModules": "1.0.0",
          "TheChunnel.ServiceCommon": "1.0.0"
        },
        "runtime": {
          "TheChunnel.ActivityService.dll": {}
        }
      },
      "Amazon.Lambda.Core/1.0.0": {
        "dependencies": {
          "System.Console": "4.0.0",
          "System.IO": "4.3.0",
          "System.Runtime": "4.3.0"
        },
        "runtime": {
          "lib/netstandard1.3/Amazon.Lambda.Core.dll": {}
        }
      },
...
```
4. notice the `compile` sections are missing from the lambda packaged deps file.

In **1.x.x** lambda tools, this `compile` property was preserved, and my `DependencyContext` operations worked.

Any clue what's going on here? Let me know if you need more info...

PS. thanks for working so hard on netcore 2!

**Comment by normj** [comment]
Interesting, I added that because the refs folder was getting drag in for ASP.NET Core Web API projects when I ran the with the `-r linux-x64`. I think you are right the tool should check to see if `PreserveCompilationContext` is explicitly set to true.

**Comment by andycmaj** [comment]
luckily you already have an example of checking something in the project file :)

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Tools/Utilities.cs#L293

if you don't have time for this, and are willing to accept PRs, lemme know.

**Comment by normj** [comment]
PRs are always welcomed and I won't have time for this for awhile.

**Comment by andycmaj** [comment]
having a bit of trouble building so figured i'd ask here since i'm not seeing any obvious documentation for building this at home :)

```
CSC : error CS7027: Error signing output with public key from file '/Workspace/aws-lambda-dotnet/buildtools/local-development.snk' -- Assembly signing not supported. [/Workspace/aws-lambda-dotnet/Libraries/src/Amazon.Lambda.CloudWatchLogsEvents/Amazon.Lambda.CloudWatchLogsEvents.csproj]
    0 Warning(s)
    14 Error(s)
```

is this an environment thing? can we not sign assemblies on osx or something?

**Comment by andycmaj** [comment]
still would like to make a PR for this but need a bit of guidance for dev setup

**Comment by normj** [comment]
Currently .NET Core does not let you do the strong name signing any other platform besides Windows.

I have been meaning to rework the build system so that signing is off by default and just have it enabled as part of our build script for release. You can work around that by changing the following line to false. Just don't make that part of the pull request. https://github.com/aws/aws-lambda-dotnet/blob/a2d895325dcfc5b41bfddbe322b24ea215c5b8c1/buildtools/common.props#L5

**Comment by ashishdhingra** [comment]
Hi @andycmaj,

Good afternoon.

I was going though the backlog and came across this issue. Please let me know if this is still an issue with the latest version or if it could be closed.

Thanks,
Ashish
