### ISSUE TITLE
Nice to have: invalid region causes cli to hang

### ISSUE THREAD

**Issue by jbright** [aws/aws-lambda-dotnet#209]
This was definitely developer error, but it would have saved me a lot of time. If possible, if you have an incorrect region, is there a way to echo that to the user? For example, if my `aws-lambda-tools-defaults.json` file had:

```json
{
   "region": "USEast1",
}
```

(which is incorrect--is should be `us-east-1`) then when running

```
dotnet lambda [any command including list-functions]
```

the command line just hangs. 

Ran into this on a Mac. It would be a "nice to have" feature to save time.

**Comment by normj** [comment]
I think we could do a regex to make sure the region follows a certain pattern but I don't want to hard code to specific known regions causing an update to be required every time Lambda is added to a region.

Did the command line never return? If that happen we should get that fixed.

**Comment by jbright** [comment]
Sure, makes sense.

I ended up terminating the process after a very long wait time, so it effectively hung. I just now tested it now setting my aws-lambda-tools-defaults.json region value to "xyzzy" and the command line hasn't come back yet ... after a couple of minutes.

**Comment by jbright** [comment]
(BTW, I submitted a request to fix a typo on the [.NET Core CLI documentation page](https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html) through the Help link at the bottom of the page. If there's a better way to report a correction to the documentation, LMK.)

**Comment by normj** [comment]
Thanks, I'll track down why it is hanging. That it definitely shouldn't be doing even with an invalid region.

**Comment by ashishdhingra** [comment]
Hi @jbright,

Good afternoon.

I was going through the backlog and came across this issue. Could you please confirm if this is still an issue with the latest AWS .NET CLI tools? I tried to reproduce this with invalid region in `aws-lambda-tools-defaults.json`, it took some time to return (mat be it's trying to resolve the region), but ultimately it didn't hand and returned an error.

Thanks,
Ashish
