### ISSUE TITLE
Updating NuGet packages causes Lambda failures

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#21]
After create an ASP.NET Core project in Visual Studio 2015, there are 13 updates. If you apply them, the default /api/values in Lambda will stop working.

My current working set is included. But if one upgrades say Microsoft.AspNetCore.Routing from 1.0.1 to 1.1.0 then Lambda stops working.

Is this to do with ASP.NET Core on Linux (in which case it is a Microsoft issue) or is this something that can be fixed in Lambda? Just trying to understand how to move this technology forward and quickly.

Thank you.

[project-works.json.txt](https://github.com/aws/aws-lambda-dotnet/files/671186/project-works.json.txt)

**Comment by adamhathcock** [comment]
Lambda is only supporting the 1.0 runtime.  This likely means only the 1.0.x packages will work.

Going to the 1.1 packages depend on the newer System libraries which are for the 1.1 runtime.

Stick to the 1.0.x ASP.NET Core packages and don't blindly update.

**Comment by genifycom** [comment]
Thank you for that. I had thought that only .NET Core 1.1 was supported. I will back everything down.
