### ISSUE TITLE
How to configure LogLevel - .NET Core 2.0

### ISSUE THREAD

**Issue by Shockolate** [aws/aws-lambda-dotnet#213]
Hello,
How can I configure the LogLevel in my ASP.NET Core WebAPI using the BluePrint for .NET Core 2?

I have the default `appsettings.json` in the directory:
```json
{
  "Lambda.Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Information"
    }
  }
}
```
But I want to change Microsoft's LogLevel to Debug. I tried changing the string in that .json, and ran it locally, but the logger did not log any Debug statements.

It seemed intuitive with the .NET Core 1.0 configuration (Startup.cs):
```csharp
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddLambdaLogger(Configuration.GetLambdaLoggerOptions());
            app.UseMvc();
        }
```

But the LoggerFactory seems to be missing from the .NET Core 2.0 signature:
```csharp
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc();
        }
```

**Comment by Shockolate** [comment]
> ran it locally
I think that was my issue. 
It is my understanding that the Lambda.Logging configuration is used only in the Lambda environment.
To configure _local_ logging, you need to add the standard logging configuration:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Information"
    }
  }
}
```

**Comment by Kralizek** [comment]
You can add the ILoggerFactory as a parameter of the ’Configure’ function.

I never tried but I believe that the runtime will try to resolve any service that has been registered in the ‘ConfigureServices‘ method of added to the signature of Configure.
