### ISSUE TITLE
NTH: UnitTest implementation of Amazon.Lambda.AspNetCoreServer

### ISSUE THREAD

**Issue by Shockolate** [aws/aws-lambda-dotnet#214]
# Nice To Have: Amazon.Lambda.AspNetCoreTestServer #
It would be convenient for my team to have a TestServer implementation that extends APIGatewayServer.
Similarly how there's a [TestServer](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs) in [Microsoft.AspNetCore.TestHost](https://www.nuget.org/packages/Microsoft.AspNetCore.TestHost).

This is so we can utilize DI for unit testing and track the request throughout the API, not just in the controller.

## My current workaround ##
Set the `ConfigureServices` method in `Startup.cs` to `virtual`
Create a `TestStartup` class that extends `Startup`:
#### TestStartup.cs ####
```csharp
using System;
using System.Buffers;
using MyService.Repositories;
using FulfilledItemService.UnitTests.Repositories.Entity;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace MyService.UnitTests
{
    public class TestStartup : Startup
    {
        public TestStartup(IConfiguration configuration) : base(configuration) { }

        // Configure Test Services
        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options => options.OutputFormatters.Add(new JsonOutputFormatter(JsonSerializerFactory.DefaultSettings, ArrayPool<char>.Shared)));

            services.AddDefaultAWSOptions(Configuration.GetAWSOptions());

            services.AddSingleton<IRepositoryPattern<TypeA>, InMemoryTypeARepository>();
            services.AddSingleton<IRepositoryPattern<TypeB>, InMemoryTypeBRepository>();
            services.AddSingleton<IMyClient, MockedClientImplementation>();
        }
    }
}
```
Create a `TestLambdaEntryPoint` class that extends `LambdaEntryPoint`.
Override `Init` to use your `TestStartup`:

#### TestLambdaEntryPoint.cs ####
```csharp
using Microsoft.AspNetCore.Hosting;

namespace MyService.UnitTests
{
    public class TestLambdaEntryPoint : LambdaEntryPoint
    {
        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseStartup<TestStartup>();
        }
    }
}
```

Run your tests as outlined in the BluePrint (we use nunit):

#### MyControllerTests.cs ####
```csharp
using Amazon.Lambda.APIGatewayEvents;
using Newtonsoft.Json;
using NUnit.Framework;
using Amazon.Lambda.TestUtilities;
using MyService.UnitTests.SampleRequests;

namespace MyService.UnitTests
{
    [TestFixture]
    public class MyControllerTests
    {
        private LambdaEntryPoint _entryPoint;
        private TestLambdaContext _testLambdaContext;

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _entryPoint = new TestLambdaEntryPoint();
        }

        [SetUp]
        public void SetUp()
        {
            _testLambdaContext = new TestLambdaContext();
        }

        [Test]
        public void TestGet()
        {
            var request = JsonConvert.DeserializeObject<APIGatewayProxyRequest>(Resources.MyEntity_GET_json);
            var response = _entryPoint.FunctionHandlerAsync(request, _testLambdaContext).Result;

            Assert.AreEqual(200, response.StatusCode);

        }
    }
}
```

If I'm approaching this problem entirely the wrong way, please let me know!

**Comment by normj** [comment]
Is the point of this provide an alternative implementation of **ConfigureServices** and **Init** for test purposes? Seems like that is possible now in your test projects to put the extended class in it, is there something blocking that?

**Comment by Shockolate** [comment]
@normj Nope.
I readily admit my AspNetCore ignorance; I don't know if my solution is a workaround or an accepted pattern.
I also don't know if it makes sense to test the middleware itself (i.e. if unit testing the controllers, etc, is sufficient)

**Comment by ashishdhingra** [comment]
Hi @Shockolate,

Good afternoon.

I was going through backlog and came across this issue. Based on your conversation with Norm, kindly confirm if this is still a requirement or is this could be closed.

Thanks,
Ashish
