### ISSUE TITLE
Https support

### ISSUE THREAD

**Issue by jasondaicoder** [aws/aws-lambda-dotnet#215]
Hi guys,

Does this proxy support https protocol? I have set up the .net core webapi as lambda using this library and the api gateway as proxy to invoke the lambda via https. However I am always getting the below errors:

System.InvalidOperationException: The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false.
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerPostConfigureOptions.PostConfigure(String name, JwtBearerOptions options)

It looks like when APIGatewayProxyFunction receives the request it doesn't pass the https down to the lambda underneath.

Any idea?

Thanks

Jason

**Comment by normj** [comment]
We are passing the scheme in as https. For reference here is where that is done in code https://github.com/aws/aws-lambda-dotnet/blob/a2d895325dcfc5b41bfddbe322b24ea215c5b8c1/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L395.

If you can create a simple repo repository I'll take a look

**Comment by normj** [comment]
Closing for lack of activty
