### ISSUE TITLE
Two lambdas produced

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#218]
So with the sample Serverless ASP.NET Core 2.0 app, we get two lambda functions

e.g.
TestServerless-RootPathFunction-1RSR608SQFG33
TestServerless-ProxyFunction-1BGHCA9RFTAS0

and these are linked in to two different parts of the API gateway, / and /{proxy+}

Is this always going to be the case?
What is the difference between the two functions?

**Comment by normj** [comment]
The reason I added the second **AWS::Serverless::Function** was if there is only the /{proxy+} request going to just the root of the web application won't be handled. 

The alternative is I can define the Lambda function in the CloudFormation independently as a **AWS::Lambda::Function** resource and then in a **AWS::ApiGateway::RestApi** resource reference the same function for both the / and /{proxy+} resource paths. I didn't do that because I felt it complicated the CloudFormation template too much for new users to figure out how to expand the CloudFormation template.

**Comment by genifycom** [comment]
Can we not just add a Mock resource in the API Gateway to direct the root call to the /{proxy+} call?

**Comment by normj** [comment]
I'm not sure what you mean by a mock resource, can you provide some more details? Since there is no charge for additional functions what is the problem you are trying to solve?

**Comment by genifycom** [comment]
I mean a mock resource like included below. I use them to redirect from example.com to www.example.com in API gateway.

I am just concerned that instead of one lambda function to keep track of there are now two. I guess since Visual Studio keeps track of updating both at the same time there should not be a problem.

I thought that it might make deployment a little faster if you only had to deploy one dotnet lambda.

---
swagger: "2.0"
info:
  version: "2018-01-03T02:34:03Z"
  title: "LambdaRedirect"
host: "<some host>"
schemes:
- "https"
paths:
  /:
    get:
      consumes:
      - "application/json"
      - "text/html"
      produces:
      - "text/html"
      responses:
        301:
          description: "301 response"
          headers:
            Location:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "301"
            responseParameters:
              method.response.header.Location: "'<lambda proxy location>'"
        requestTemplates:
          text/html: "{\"statusCode\": 301}"
          application/json: "{\"statusCode\": 301}"
        passthroughBehavior: "when_no_templates"
        type: "mock"

**Comment by normj** [comment]
Closing as I believed answered. In the future I might rework the template.

**Comment by genifycom** [comment]
Ok Norm. It would certainly help if there was only a single function.

**Comment by normj** [comment]
I changed my mind and I'm going to reopen this as a enhancement request. I was thinking about this more and I think it might be worth switch away from AWS::SERVERLESS::FUNCCTION the lower level CloudFormation resources. Another advantage I was thinking is we could configure a path in the API Gateway to an S3 bucket for static content like images.

Here is a basic example of what the template would look like without the S3 bucket.

```json
{
  "Description": "An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.",
  "Parameters": {
    
  },
  "AWSTemplateFormatVersion": "2010-09-09",
  "Conditions": {
    
  },
  "Resources": {

    "AspNetCoreFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "",
          "S3Key": ""
        },
        "MemorySize": 512,
        "Environment": {
          "Variables": {
            
          }
        },
        "Handler": "LambdaWebAppNewTemplate::LambdaWebAppNewTemplate.LambdaEntryPoint::FunctionHandlerAsync",
        "Role": {
          "Fn::GetAtt": [
            "RoleForLambdaFunction",
            "Arn"
          ]
        },
        "Timeout": 30,
        "Runtime": "dotnetcore2.0"
      }
    },

    "RoleForLambdaFunction": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy\/service-role\/AWSLambdaBasicExecutionRole",
          "arn:aws:iam::aws:policy\/AWSLambdaFullAccess"
        ],
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        }
      }
    },

    "RestApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Body": {
		  "swagger": "2.0",
          "info": {
            "version": "1.0",
            "title": {
              "Ref": "AWS::StackName"
            }
          },
          "paths": {
            "/": {
              "x-amazon-apigateway-any-method": {
                "x-amazon-apigateway-integration": {
                  "httpMethod": "POST",
                  "type": "aws_proxy",
                  "uri": {
                    "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path\/2015-03-31\/functions\/${AspNetCoreFunction.Arn}\/invocations"
                  }
                },
                "responses": {
                  
                }
              }
            },
            "/{proxy+}": {
              "x-amazon-apigateway-any-method": {
                "x-amazon-apigateway-integration": {
                  "httpMethod": "POST",
                  "type": "aws_proxy",
                  "uri": {
                    "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path\/2015-03-31\/functions\/${AspNetCoreFunction.Arn}\/invocations"
                  }
                },
                "responses": {
                  
                }
              }
            }
          }
        }
      }
    },

    "RestApiDeployment": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "RestApiId": {
          "Ref": "RestApi"
        },
        "StageName": "Stage"
      }
    },

    "RestApiProd": {
      "Type": "AWS::ApiGateway::Stage",
      "Properties": {
        "DeploymentId": {
          "Ref": "RestApiDeployment"
        },
        "RestApiId": {
          "Ref": "RestApi"
        },
        "StageName": "Prod"
      }
    },

    "LambdaPermissionToProdAPIGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "FunctionName": {
          "Ref": "AspNetCoreFunction"
        },
        "SourceArn": {
          "Fn::Sub": [
            "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}\/${__Stage__}\/ANY\/",
            {
              "__Stage__": "*",
              "__ApiId__": {
                "Ref": "RestApi"
              }
            }
          ]
        }
      }
    }




  },
  "Outputs": {
    
  }
}
```

**Comment by brendonparker** [comment]
@normj 
> I was thinking is we could configure a path in the API Gateway to an S3 bucket for static content like images
Have an example template with this? I'm also trying to tackle this.

**Comment by normj** [comment]
The ASP.NET Core blueprint was updated to create only one Lambda function to handle both API Gateway route.
