### ISSUE TITLE
Support IHttpConnectionFeature in AspNetCoreServer

### ISSUE THREAD

**Issue by alanedwardes** [aws/aws-lambda-dotnet#22]
It looks like the implementation of this interface is commented out in `InvokeFeatures` https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/Internal/InvokeFeatures.cs#L21

It would be good to support this, mainly to allow easy access to the client's IP address. Currently you have to grab it from the `X-Forwarded-For` header.

**Comment by adamhathcock** [comment]
:+1:

**Comment by normj** [comment]
Thanks for the feedback. I didn't have time to fully investigate IHttpConnectionFeature interface before release which is why I commented out the implementation. I'll get back to fleshing out the rest of the interfaces after the holidays.
