### ISSUE TITLE
dotnet lambda deploy-function always prompts for a IAM Role, even when set in the defaults

### ISSUE THREAD

**Issue by cannontrodder** [aws/aws-lambda-dotnet#225]
If I use the following command, it runs non-interactively on subsequent deploys of my lambda function:

`dotnet lambda deploy-function MyFunctionName`

When I have my profile set in aws-lambda-tools-default.json like this:

`  "profile": "DotNetLambdaRole",`

I *always* get asked to select the profile during the deploy:

```
Select IAM Role that Lambda will assume when executing function:
    1) DotNetLambdaRole
    2) *** Create new IAM Role ***
```

I wish to use this process to deploy from a CI server and while subsequent deploys will not ask again for this, the first run is going to hang while asking for user input. Is there any way to explicitly issue a command line switch as input? I've looked in the code and it seems you get asked if it is a new function every time.

**Comment by cannontrodder** [comment]
Ah, allow me to answer my own silly question :-)

passing --function-role DotNetLAmbdaRole as a parameter explicitly defines the policy and avoids prompts.

**Comment by normj** [comment]
In your CI you can also pass in  `--disable-interactive true` to prevent from ever prompting for input.
