### ISSUE TITLE
Cannot get the querystring in Lambda

### ISSUE THREAD

**Issue by mkamrani** [aws/aws-lambda-dotnet#226]
I have a Lambda function integrated with API gateway as LAMBDA_PROXY. In the URL Query String Parameter section I have added a parameter (say par) but I cannot get that in my function based on [this](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.APIGatewayEvents):

```
using System;
using Amazon.Lambda.Core;
using Amazon.Lambda.APIGatewayEvents;
using Newtonsoft.Json;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace getValues
{
    public class Function
    {
        public APIGatewayProxyResponse FunctionHandler( APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
        {
            Console.WriteLine($"Processing request data for request {context.AwsRequestId}.");
            Console.WriteLine($"Method = {apigProxyEvent.HttpMethod}.");
            var headerNames = string.Join(", ", apigProxyEvent.Headers.Keys);
            Console.WriteLine($"Specified headers = {headerNames}.");
            var values = new [] { "value1", "value2" };
            return new APIGatewayProxyResponse
            {
                Body = JsonConvert.SerializeObject(values),
                StatusCode = 200
            };
        }
    }
}
```
This is my CloudWatch log

> START RequestId: fa31d346-0fb0-11e8-a698-431f87ab57b1 Version: $LATEST
> Processing request data for request fa31d346-0fb0-11e8-a698-431f87ab57b1.
> Method = .
> Object reference not set to an instance of an object.: NullReferenceException
> at getValues.Function.FunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context) in C:\Users\Mohsenk\Documents\Visual Studio 2017\Projects\xxx\Function.cs:line 15
> at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
> 
> 
> END RequestId: fa31d346-0fb0-11e8-a698-431f87ab57b1
> REPORT RequestId: fa31d346-0fb0-11e8-a698-431f87ab57b1	Duration: 1555.96 ms	Billed Duration: 1600 ms Memory Size: 256 MB	Max Memory Used: 24 MB	

Am I missing something? Any helps appreciated.

**Comment by normj** [comment]
How are you running the function? The exception stacktrace says the null pointer exception happened on line 15 which is where you are accessing the ILambdaContext object. That could only be null if you were running it through a unit test or something outside of Lambda and were passing in at least a mock implementation of ILambdaContext.

If I have the wrong line number could you add the environment variable `LAMBDA_NET_SERIALIZER_DEBUG` with a value of `true` to the Lambda function. That will cause the original JSON request to be written to the logs before serialization. Add that the to the issue and I'll see if we are not serializing something correctly. You can add the environment variables in either Visual Studio's configuration tab for the Lambda function or in the Lambda web console.

**Comment by mkamrani** [comment]
Actually the exception is not about the `ILambdaContext` , but it's the `APIGatewayProxyRequest` argument which is not populated. I tested this claim with providing a request body model, which let's me read some properties of both arguments.

**Comment by normj** [comment]
Okay if you can add the `LAMBDA_NET_SERIALIZER_DEBUG` environment variable to capture the request I'll take a look at why it isn't being marshalled correctly.

**Comment by mkamrani** [comment]
Thanks for the prompt response. I just deployed the API again, after double checking everything and deployed the Lambda again and now it's working! Really have no idea what was the issue, as everything looks very straightforward.
