### ISSUE TITLE
dotnet lambda deploy-function fails to find an existing role

### ISSUE THREAD

**Issue by mipnw** [aws/aws-lambda-dotnet#228]
I'm going through the following tutorial:
https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html

I created the lambda function using
dotnet new lambda.EmptyFunction --name MyFunc --profile MyRole --region MyRegion

MyRole is an existing IAM Role which has the attached AWSLambdaBasicExecutionRole policy.

dotnet restore
dotnet lambda deploy-function MyFunc –-function-role MyRole

It's unclear why I have to repeat MyRole, but ok fine. That command fails with

"Error retrieving configuration for function MyFunc : Credentials for profile MyRole cannot be found"

I tried putting the full ARN of MyRole (arn:aws:iam:xxxxxx:MyRole) in the aws-lambda-tools-defaults.json. The command fails again this time saying it cannot find the arn:aws:iam:xxxxxx:MyRole.

The only way i can get the deployment to work is to clear the profile string in the json config file, deploy, and let the deployment script prompt me to pick a role. Not great for scripting automation...

PS: I also gave MY-USER AWSIAMReadAccess permission in the AWS console, where MY-USER is the user configured with "aws configure", to make sure the dotnet deployment script wouldn't have any permission problem listing existing roles. I don't when I query "aws iam list-roles" myself. This didn't help.

**Comment by normj** [comment]
Sounds like there is some confusion between `profile` and role `role`. **Profile** is your named credentials stored in our ~/.aws/credentials file or registered in the Visual Studio toolkit that are used to deploy the function to Lambda. **Role** is what provides credentials to your executing function.

**Comment by mipnw** [comment]
Got it. Thanks!

**Comment by nickcox** [comment]
Seems to me that the confusion comes from the docs themselves.

> --profile: Your execution role.
>
> To create an IAM role (execution role):
>
> Sign in to the AWS Management Console and open the IAM console at > https://console.aws.amazon.com/iam/.
>
> Follow the steps in IAM Roles in the IAM User Guide to create an IAM role (execution role). As you follow the steps to create a role, note the following:
>
> In Select Role Type, choose AWS Service Roles, and then choose AWS Lambda.
>
> In Attach Policy, choose the policy that best fits your Lambda function's requirements. If it's not interacting with any other AWS services, you would would choose AWSLambdaBasicExecutionRole. However, say your Lambda function is interacting with Kinesis, then you would choose the AWSLambdaKinesisExecutionRole.

**Comment by sakthiveluv** [comment]
![image](https://user-images.githubusercontent.com/34507996/170424094-097bcbce-6fee-4d75-9082-ee5b7bc5ca47.png)

Getting error while deploy into AWS, Please help me
