### ISSUE TITLE
AuthorizedAPIGatewayProxyRequest.ProxyRequestContext doesn't expose custom authorizer properties

### ISSUE THREAD

**Issue by tomguilbault** [aws/aws-lambda-dotnet#23]
ProxyRequestContext should have an 'authorizer' property.  That object should have at least the principalId for when people are using a custom authorizer.

Something like this:
```
        public class ProxyRequestContext 
        {
             ...
            public ProxyAuthorizer authorizer { get; set; }
        }

        public class ProxyAuthorizer
        {
            public string principalId { get; set; }
        }
```

**Comment by normj** [comment]
Thanks for letting us know. I'll get the package updated.

**Comment by normj** [comment]
Version 1.0.2 of Amazon.Lambda.APIGatewayEvents was released that has these fields
