### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer different behaviour on local and AWS

### ISSUE THREAD

**Issue by CrazyBaran** [aws/aws-lambda-dotnet#235]
Hello AWS Team,

There is some problem with your implementation of LambdaEntryPoint, behavior is diffferent than this which is on LocalEntryPoint. To recreate this case you need to made CustomAttribute:

 ```
public class CustomAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
        {
            HttpResponse response = actionExecutedContext.HttpContext.Response;
            LambdaLogger.Log("Test "+ response.StatusCode+ " "+ (response != null).ToString() +" " + 
                response.IsSuccessStatusCode().ToString()+ " " + (actionExecutedContext.Result != null).ToString());
            
            base.OnActionExecuted(actionExecutedContext);
        }
    }  
```

If you test this CustomAttribute with localEntry you will see that StatusCode is set, but when you debug this on AWS you will get 0 cause something work in different order. I investigate this issue with OData team here: OData/WebApi#1227

**Comment by normj** [comment]
I was able to reproduce the issue but not sure yet why it is happening but I'll keep investigating.

**Comment by CrazyBaran** [comment]
Some news in this topic?

**Comment by CrazyBaran** [comment]
This bug still occur, if there is some plan to repair it?

**Comment by hakimio** [comment]
@normj Any plans to fix this?

**Comment by julealgon** [comment]
What's the latest on this? It's been more than a year since the last comment was added. @NGL321 , can you provide an update?

**Comment by NGL321** [comment]
Hey @julealgon,

Sorry for the label and go. We are presently aware of this bug and planning to fix it, but unfortunately I cant give you a more concrete timeline at the moment as it is not in the immediate fix plan.
If this is blocking, you are welcome to submit a pull request to fix and we will review it as soon as able. Alternatively, keep bumping this, and I will make sure it gets attention as soon as feasible (the more people who request a fix, the higher we can move it in our priorities) 😉

😸 😷

**Comment by ashishdhingra** [comment]
Might be similar to https://github.com/aws/aws-lambda-dotnet/issues/570

**Comment by normj** [comment]
The status code being default to 0 has been fixed in the latest version of `Amazon.Lambda.AspNetCoreServer`.
