### ISSUE TITLE
stackTrace strings aren't being escaped on exception 

### ISSUE THREAD

**Issue by n8allan** [aws/aws-lambda-dotnet#236]
If the stack trace includes JSON escape characters (such as "\" characters as part of a Windows path included in a debug build), such characters aren't being escaped ("\\") and thus invalid JSON is being produced.

Here is an example error:
```
{
  "errorType": "Exception",
  "errorMessage": "Incorrect StudentID, LoginCode, or PassCode",
  "stackTrace": [
    "at MyNS.MyMethod() in C:\Projects\SomePath\Session.cs:line 95",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ]
}
```

Reproduction:
1. Build a C# lambda function under debug in Windows.
2. Have said function throw an exception

**Comment by vellozzi** [comment]
We're working on a fix for this and will get it released as soon as possible.

**Comment by vellozzi** [comment]
The fix for this issue has been deployed to production.
