### ISSUE TITLE
Deployment Tools not finding profile

### ISSUE THREAD

**Issue by kylegalbraith** [aws/aws-lambda-dotnet#24]
I have a profile configured in my .credentials file that assumes a role in another account using a source_profile, see below:
```
[new-profile]
role_arn=arn:aws:iam::XXXXXXXX:role/some-role
source_profile=my-source-profile
mfa_serial=arn:aws:iam::XXXXXXXXX:mfa/source-user
```

Yet when I run the dotnet lambda deploy-serverless as below, I get a profile not found. How can I resolve this so that I can deploy the serverless stack into another account?
```
dotnet lambda deploy-serverless my-test-stack -sb my-test-stack --profile new-profile
```

**Comment by normj** [comment]
Currently the AWS SDK for .NET, which this tool is built off, doesn't support assume role credential profile. It is something we are actively working on for the SDK. Once we release the SDK support I'll bump the deployment to the latest version.

**Comment by sonicjolt** [comment]
In our Continuous Integration and Deployment setup, we would like to be able to assume role. But since this is not currently possible, @normj can you suggest a work-around ?

**Comment by normj** [comment]
A work around would be writing code that does the deployment like Amazon.Lambda.Tools does but create your own AWSCredentials work. You could take a runtime dependency on Amazon.Lambda.Tools and call the deployment commands from code passing in credentials. Keep in mind though we don't consider the code in CLI integration a public API and might change the code in the future.

I can't give dates but we are actively rework the SDK's handling of credentials which will then support this use case natively.

**Comment by sonicjolt** [comment]
@normj Thanks a lot. Do you by chance know of an issue I can track, so we know when the re-work has been completed. Or is this a multitude of issues that need to be completed before this native support ?

**Comment by normj** [comment]
I'm leaving this issue open and will post on it when it ships. 

We have most of the work done we. We are currently getting the AWS Toolkit for Visual Studio updated to use the new credential handler which will help validate that it covers the use cases and then we can push out the work.

**Comment by normj** [comment]
Version 1.4.0 of Amazon.Lambda.Tools is updated to pick up to the latest version of the AWS SDK for .NET which has [assume role support](https://aws.amazon.com/blogs/developer/aws-sdk-dot-net-credential-profiles/). 

I haven't added the callback support into the tooling yet for MFA tokens.
