### ISSUE TITLE
ASPNETCORE_ENVIRONMENT=Development forces logging behavior appropriate for local deployment

### ISSUE THREAD

**Issue by szilvaa** [aws/aws-lambda-dotnet#242]
We deploy our code to 3 environments: development/staging and production. We set the `ASPNETCORE_ENVIRONMENT` variable in these lambda environments to Development, Staging and Production respectively.

# Expected behavior
We expect **no difference** in CloudWatch logs in development/staging/production environment unless we explicitly configure different logging ourselves.

# Current behavior
Logging changes radically when `ASPNETCORE_ENVIRONMENT` is set to Development. This happens because of [this line](https://github.com/aws/aws-lambda-dotnet/blob/0bf318e67ae269e10e61f65811711fafd25d029c/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L144) of code. This code appears to make the decision that "Development" implies local deployment. I don't think that such determination should be predicated on the `ASPNETCORE_ENVIRONMENT` variable. The code could check other [Lambda variables](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) like LAMBDA_TASK_ROOT to make this decision instead.

# Steps to repro
1. Deploy a .netcore20 lambda that uses `APIGatewayProxyFunction` as its entry point. 
2. Log something  via ILogger that has a line break in it.
3. Note that the log entry appears in CloudWatch as one entry. (entry can be expanded and you can see the 2 lines)
4. Define `ASPNETCORE_ENVIRONMENT`=Development for your Lambda in the AWS Lambda Console.
5. Log the same entry again.
6. Note that the log entry now appears as 2 entries in CloudWatch (one for each line)

The difference in the above behavior is because in step 5 the *Console* logger is used while in step 2 the LambdaLogger is used.

**Comment by normj** [comment]
I have checked in the change change to look for the existence LAMBDA_TASK_ROOT instead of ASPNETCORE_ENVIRONMENT setting. It will go out with the next release of the library which should be soon. I'll post back when it is released.

**Comment by normj** [comment]
Version 2.0.3 of `Amazon.Lambda.AspNetCoreServer` has this change to switch the logging configuration based on the existence of the `LAMBDA_TASK_ROOT` environment variable.
