### ISSUE TITLE
How to debug in Visual Studio 2017 my AWS Serverless ASP Net Core 2.0 WebAPI

### ISSUE THREAD

**Issue by TonyHenrique** [aws/aws-lambda-dotnet#246]
I wrote a simple  ASP Net Core 2.0 WebAPI and published to AWS Serverless

How can I connect Visual Studio to this remote deployment to debug?

**Comment by normj** [comment]
There is no support for remote debugging with Lambda. On our list of things we would like to work on is integrate our Lambda tooling in Visual Studio with the the [AWS SAM Local project](https://github.com/awslabs/aws-sam-local) which recently added support for .NET Core 2.0
