### ISSUE TITLE
Two Lambda functions created

### ISSUE THREAD

**Issue by Petermarcu** [aws/aws-lambda-dotnet#248]
@genifycom opene this here: https://github.com/dotnet/core/issues/1238

Two C# lambda functions created

When I publish, I see that two Lambda functions have been created. One is xxx-RootPathFuction-yyyy and the other is xxx-ProxyFunction-yyy

The root path one is attached to / in the API Gateway and the proxy one connected to a proxy resource.

Is this always going to be the case or have I done something odd in my application?

**Comment by CrazyBaran** [comment]
Related to #218

**Comment by normj** [comment]
Closing as this is a duplicate of #218. Thanks for letting us know about it Peter.
