### ISSUE TITLE
Which versions of Microsoft.AspNetCore.All is supported?

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-lambda-dotnet#249]
Hey,

I'm curious about what versions of `Microsoft.AspNetCore.All` is supported. The latest version from Microsoft is `2.0.6`, and AFAIK `2.0.3` is only available in the Lambda runtime. Of course I could create self-contained deployment with the latest version but I would rather reduce the size of my Lambda as much as possible.

Thanks.

**Comment by normj** [comment]
Actually Lambda was just recently updated to version 2.0.5 and I have just now updated the control file that our tooling uses to say what versions of Microsoft.AspNetCore.All you can reference to include 2.0.5. 

We are rolling on to getting 2.0.6 deployed.

**Comment by normj** [comment]
Closed as I believe answered for now. We will keep rolling new versions out as they are released but we can't give a timeline as it is dependent on many factors.

**Comment by raRaRa** [comment]
So there's no proper way to check which versions are supported? Should I just try from time to time, or is there a changelog somewhere? Thanks!

**Comment by normj** [comment]
There is nothing "proper" now. Although it isn't part of this repository I can add a entry in this repository's [RELEASE.CHANGELOG.md](https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md) when the next version is available in Lambda if that helps.

.NET Core 2.1 is changing the usage of package store and how Microsoft.AspNetCore.All is distributed so when we get the next version of Lambda available we will be reevaluating how this works for us.

**Comment by raRaRa** [comment]
That would be very helpful. Thanks!
