### ISSUE TITLE
Typo serverless.template

### ISSUE THREAD

**Issue by ryanwilliams83** [aws/aws-lambda-dotnet#251]
"function to get add a blog" -> "function to add a blog"

https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/Msbuild-NETCore_1_0/DynamoDBBlogAPI/template/src/BlueprintBaseName/serverless.template

**Comment by normj** [comment]
Thanks! I have committed the fix so it will go out the next time I publish the templates https://github.com/aws/aws-lambda-dotnet/commit/775a3504aab6e1e446d4d8b00696eb21b4168246
