### ISSUE TITLE
How to enable GZIP in .NET Serverless Application?

### ISSUE THREAD

**Issue by cjnoname** [aws/aws-lambda-dotnet#255]
Hey guys,

I created a new .NET Serverless Application on Lambda and I want to enable the GZIP (Br) Compression.

However, it gives me this Error: **ERR_CONTENT_DECODING_FAILED**

It's working properly on localhost.

I have already enabled the Compression option on API Gateway but it didn't help.

What should I set up to make it working?

Thanks

**Comment by normj** [comment]
Sounds like @naingyelin has answered this question
