### ISSUE TITLE
(F#) Unable to find LambdaEntryPoint inside module

### ISSUE THREAD

**Issue by ollipekka** [aws/aws-lambda-dotnet#257]
I ran into this when creating a demo of SAM Giraffe application (https://github.com/ollipekka/GiraffeDemoLambda).

I'm using the following dependencies:
`
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.4" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.1.1" /
`

Declaring LambdaEntryPoint inside F# module (turns into static class) for example:
`
GiraffeDemo::GiraffeDemo.Serverless.LambdaEntryPoint::FunctionHandlerAsync
`
doesn not work. However, following works:
`GiraffeDemo::GiraffeDemo.LambdaEntryPoint::FunctionHandlerAsync`

This should be reproable by cloning the repository and changing the LambdaEntryPoint under a module and then changing the serverless to correspond to that.

For seamless F# interop, the LambdaEntryPoint should also be found under static classes as well.

**Comment by normj** [comment]
I got this to work. Looks like to access inner classes you need to reference the inner class with a '+' instead of '.'. For example your function handler string should be `GiraffeDemo::GiraffeDemo.Serverless+LambdaEntryPoint::FunctionHandlerAsync`.

**Comment by ollipekka** [comment]
Maybe this could added to documentation somewhere or maybe a reference to the syntax of the cloud formation template when dealing with inner classes (or f# modules in this case).
