### ISSUE TITLE
Unable to get list in query params

### ISSUE THREAD

**Issue by clouddra** [aws/aws-lambda-dotnet#258]
In ASP .NET Core the convention specify lists in query strings is to do

```csharp
[HttpPost("{token}")]
public IActionResult SomeEndpoint(string token, [FromQuery] List<string> listItems) {
    // do something
}
```
To use this endpoint we would call `/token?listItems=item1,listItems=item2`.

However, API Gateway does not support repeated keys. We are only able to retrieve `item2` in listItems (it takes the last item).

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html
> API Gateway enacts the following restrictions and limitations when handling methods with either Lambda integration or HTTP integration.
> 
>     Duplicated query string parameters are not supported.
  
https://docs.aws.amazon.com/apigateway/api-reference/making-http-requests/
> HTTP request query parameters
> 
> When a query parameter is a list type, its value must be a string of comma-separated items. For example, GET /restapis/restapi_id/deployments/deployment_id?embed=apisummary,sdksummary.
> 
> Amazon API Gateway does not support nested query parameters of the form: GET /team?user[id]=usrid on a method request. You could work around this limitation by passing an encoded map as a single parameter and serializing it as part of a mapping template or in your back-end integration.

Using `LAMBDA_NET_SERIALIZER_DEBUG`, I can see that API Gateway is indeed filtering out duplicated string params.

Are there any workarounds for this?

**Comment by normj** [comment]
Since API Gateway isn't passing the duplicates to the Lambda function there isn't much we can do. I suggest chiming in API Gateway forums. Here is an existing post talking about this issue you could +1 to help prioritize this.

**Comment by normj** [comment]
Closing as I don't think there is anything we can from our client tooling till API Gateway supports sending duplicate query strings.

**Comment by pmgalea** [comment]
API Gateway does support multivalue parameters now, the implementation isn’t great but there is a way but the sdk doesn’t support it.

It would be nice however if it just did it transparently as oppose to having to interact with the context.

https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/

Can we rerequest this feature / get involved?

**Comment by normj** [comment]
I created a new issue to track the new multi-value support https://github.com/aws/aws-lambda-dotnet/issues/378

I'm currently working on a 3.0.0 version of `Amazon.Lambda.AspNetCoreServer` with the main feature being Application Load Balancer support but I'll try and get this feature in as well with that release.
