### ISSUE TITLE
Process exited before completing request with lots of If statements

### ISSUE THREAD

**Issue by etarasoff** [aws/aws-lambda-dotnet#259]
Encountered this issue with a lambda and eventually determined that the issue was caused by a piece of code with a large number of copied-from-Excel statements in a helper class that were adding objects to a list. At first I thought the issue might be due to the lambda exceeding the memory threshold as the code was working fine locally but that turned out not to be the case. 

In fact, the issue seemed to be related to just a sheer number of individual code statements, not the number of objects in memory. 

To illustrate this, I created this example where I have a large number of code statements which aren't doing anything. Example log output is pasted below. Unable to catch any exceptions so not sure what to make of this? Any help appreciated.

        public void FunctionHandler(ILambdaContext context)
        {
            // Will generate issue if GetCultureInfos is called
            // Will not generate issue if this line is commented
            List<CultureInfo> cultureInfos = GetCultureInfos(2);

            // Does not generate issue
            List<CultureInfo> cultureInfos2 = new List<CultureInfo>();
            for(int i = 0; i <= 10000; i++)
            {
                cultureInfos2.Add(new CultureInfo("en-US"));
            }
        }

        private List<CultureInfo> GetCultureInfos(int conditional)
        {
            List<CultureInfo> cultureInfos = new List<CultureInfo>();
            if (conditional == 1) { cultureInfos.Add(new CultureInfo("en-US")); }
            if(conditional == 1) { cultureInfos.Add(new CultureInfo("en-US")); }
            if(conditional == 1) { cultureInfos.Add(new CultureInfo("en-US")); }

            // add about 10,000 more lines like this
            
             return cultureInfos;
        }

"Will generate an issue" log output:

START RequestId: 65f60e75-3c29-11e8-bc18-ef16071bed7a Version: $LATEST
END RequestId: 65f60e75-3c29-11e8-bc18-ef16071bed7a
REPORT RequestId: 65f60e75-3c29-11e8-bc18-ef16071bed7a	Duration: 2352.60 ms	Billed Duration: 2400 ms 	Memory Size: 1024 MB	Max Memory Used: 287 MB	
RequestId: 65f60e75-3c29-11e8-bc18-ef16071bed7a Process exited before completing request

"Does not generate issues" log output:

START RequestId: 0cbfd688-3c27-11e8-aed4-1dd4cb7bfc71 Version: $LATEST
END RequestId: 0cbfd688-3c27-11e8-aed4-1dd4cb7bfc71
REPORT RequestId: 0cbfd688-3c27-11e8-aed4-1dd4cb7bfc71	Duration: 20.93 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 23 MB

**Comment by vellozzi** [comment]
We're able to reproduce this.  We're still working on the root cause.  The current theory is that it has to do with the constrained memory environment.  We think it might be possible even though Lambda reports max memory used as much less than the configured amount.

We'll update the issue when we have more information.

**Comment by bjorg** [comment]
It used to be the case that out-of-memory exception would behave this way. However, I recently noticed that `System.OutOfMemoryException` are now shown in the logs. Might be worthwhile repeating the experiment to see what happens.

**Comment by ashishdhingra** [comment]
Hi @etarasoff,

Good morning.

Please let me know if this is still an issue or if it could be closed. As @vellozzi mentioned, this could be due to memory constraints (just an assumption).

Thanks,
Ashish
