### ISSUE TITLE
deploy-serverless fails in UpdateCodeLocationInJsonTemplate

### ISSUE THREAD

**Issue by diacoda** [aws/aws-lambda-dotnet#260]
Hello all, I am a newbie to AWS and was playing with some Lambda. The source is here: https://github.com/diacoda/Car.
I have run botnet lambda package and got a CarFunction-deploy.zip.

Now, I am trying to run:
dotnet lambda deploy-serverless --package CarFunction-deploy.zip and I am failing with 
AWS Lambda Tools for .NET Core functions (2.1.1)
Project Home: https://github.com/aws/aws-lambda-dotnet

Skipping compilation and using precompiled package CarFunction-deploy.zip
Uploading to S3. (Bucket: 204891-lambda-deploy Key: prefix204891-CarLambda-sn-636590941237757320.zip)
... Progress: 50%
... Progress: 100%
Unknown error executing AWS Serverless deployment: Object reference not set to an instance of an object.
   at Amazon.Lambda.Tools.Utilities.UpdateCodeLocationInJsonTemplate(String templateBody, String s3Bucket, String s3Key)
   at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.<ExecuteAsync>d__67.MoveNext()

The content of aws-lambda-tools-defaults.json can be found on GitHub or below for your convenience:
{
  "Information" : [
    "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
    "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",

    "dotnet lambda help",

    "All the command line options for the Lambda command can be specified in this file."
  ],

  "profile":"tr-fr-sandbox",
  "region" : "us-east-2",
  "configuration" : "Release",
  "framework" : "netcoreapp2.0",
  "function-runtime":"dotnetcore2.0",
  "s3-bucket" : "204891-lambda-deploy",
  "s3-prefix" : "prefix",
  "template" : "serverless.json",
  "stack-name" : "204891-CarLambda-sn",
  "stack-wait"    : true,
  "function-memory-size" : 256,
  "function-timeout" : 30,
  "function-handler" : "CarFunction::CarFunction.Functions::Get"
}

serverless.json:
{
    "AWSTemplateFormatVersion" : "2010-09-09",
    "Transform" : "AWS::Serverless-2016-10-31",

   "204891-CarLambda" : {
    "Type" : "AWS::Serverless::Function",
    "Properties": {
        "Handler": "CarFunction::CarFunction.Functions::FunctionHandler",
        "Runtime": "dotnetcore2.0",
        "CodeUri": ".",
        "Description": "Function to get a list of carss",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": "arn:aws::role/204891-lambdabasic" },
      "Events": {
          "Api1": {
              "Type": "Api",
              "Properties": {
                  "Path": "/{o+}",
                  "Method": "ANY"
              }
          },
          "Api2": {
              "Type": "Api",
              "Properties": {
                  "Path": "/Cars",
                  "Method": "GET"
            }
        }
      }
    }
}

Any help is much appreciated. I have no idea why is failing...
At some point in time I tried the package-ci but could not get it to work so I thought this deploy-serverless should be easier ... well... Need your help.

Thanks! Dan

PS: For reference I am on a Mac with VS Code.

**Comment by diacoda** [comment]
hi again, is this the wrong place to ask? maybe someone can point me where? much appreciated...

**Comment by normj** [comment]
This is the right place and I was able to reproduce the issue. Let me do some more investigation and I'll get back to you.

**Comment by normj** [comment]
We'll our deployment code could use better error messaging but the template was invalid. The `AWS::Serverless::Function` needs to be in a `Resources` block. The deployment code was getting a null pointer because it failed to find that node. Also the name of the `AWS::Serverless::Function` must start with alpha characters. Here is my modified version of your template.

```javascript
{
    "AWSTemplateFormatVersion" : "2010-09-09",
    "Transform" : "AWS::Serverless-2016-10-31",

    "Resources" : {
        "CarLambda" : {
            "Type" : "AWS::Serverless::Function",
            "Properties": {
                "Handler": "CarFunction::CarFunction.Functions::FunctionHandler",
                "Runtime": "dotnetcore2.0",
                "CodeUri": "s3://204891-lambda-deploy/CarFunction-deploy.zip",
                "Description": "Function to get a list of cars",
                "MemorySize": 256,
                "Timeout": 30,
                "Role": "arn:aws::role/204891-lambdabasic" 
            },
            "Events": {
                "Api1": {
                    "Type": "Api",
                    "Properties": {
                        "Path": "/{o+}",
                        "Method": "ANY"
                    }
                },
                "Api2": {
                    "Type": "Api",
                    "Properties": {
                        "Path": "/Cars",
                        "Method": "GET"
                    }
                }
            },
            "Tags" : {
                "tr:application-asset-insight-id" : "204891",
                "tr:resource-owner" : "dan.diaconescu"
            }
        }    
    }
}
```

**Comment by diacoda** [comment]
TY @normj I can confirm both deploy-serverless and pacakge-ci now work with the template change you did above. My bad :) . TY again
