### ISSUE TITLE
Lambda ASP.NET Core Web API  template with Odata

### ISSUE THREAD

**Issue by companyopensource** [aws/aws-lambda-dotnet#261]
I am using the library Microsoft.AspNetCore.OData -Version 7.0.0-beta2 for Odata, and the template "Lambda ASP.NET Core Web API "

The LocalEntryPoint works fine with Odata query parameters, but the LambdaEntryPoint does not seem to use the Odata query parameters such as $top, $filter etc
`
public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<Context>();
            services.AddOData();
            services.AddMvc();
}

 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
 var builder = new ODataConventionModelBuilder();
            builder.EntitySet<Entity>("EntityName");
            app.UseMvc(routeBuilder =>
            {
                routeBuilder.MapODataServiceRoute("odata", null, builder.GetEdmModel());
                routeBuilder.Count(QueryOptionSetting.Allowed);
                routeBuilder.Expand(QueryOptionSetting.Allowed);
                routeBuilder.Filter(QueryOptionSetting.Allowed);
                routeBuilder.MaxTop(null);                
            });                        
        }
`

**Comment by normj** [comment]
Could you put together a simple example repository for me debug?

**Comment by CrazyBaran** [comment]
@chrisradek There is issue with EnableQuery and whole Atrribute I think in Lambda. I write about this here #235, you could find my walkaround on OData repository OData/WebApi#1227

**Comment by ashishdhingra** [comment]
Hi @companyopensource,

Good morning.

Please let me know if the workaround mentioned by @CrazyBaran works for you and if this issue could be closed. Looking at the bug OData/WebApi#1227, it appears to be in-progress.

Thanks,
Ashish
