### ISSUE TITLE
dotnet lambda package-ci producing Error determining region -> Error calling AssumeRole

### ISSUE THREAD

**Issue by fschroder** [aws/aws-lambda-dotnet#262]
Hi,
I'm using `dotnet lambda package-ci --profile xxx-nonprod  --s3-bucket xxx-nonprod-deploy --output-template deployed-serverless.template` and I'm getting

> AWS Lambda Tools for .NET Core functions (2.1.1)
> Project Home: https://github.com/aws/aws-lambda-dotnet
> 	
> Unknown error: One or more errors occurred. (Error determining region for bucket xxx-nonprod-deploy: Error determining region for bucket xxx-nonprod-deploy: Error calling AssumeRole for role arn:aws:iam::nnnnnn:role/CrossAccountAdministrators)
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Amazon.Lambda.Tools.Program.Main(String[] args)

If, for example, I do ` aws --profile xxx-nonprod  s3 ls` it works fine.
AWS accounts are configured with an authentication account and then a role must be assumed to interact with the other account. Is this supported by the lambda tooling?

https://github.com/aws/aws-lambda-dotnet/issues/24 suggests this should work.

Thx

**Comment by normj** [comment]
Looks like the role you are assuming is missing the permission to call the GetBucketLocation operation. If you are listing individual operations in your IAM Role's policy the method would be "s3:GetBucketLocation"

**Comment by normj** [comment]
In the latest version of Amazon.Lambda.Tools the check was updated to just be a warning if it failed due to get the region of a bucket.
