### ISSUE TITLE
NoEcho template parameter property is not respected by deploy-serverless command

### ISSUE THREAD

**Issue by torrick** [aws/aws-lambda-dotnet#264]
Given a list of parameters like so: 

```
"Parameters": {
        "DatabaseHost": {
            "Type": "String"
        },
        "DatabaseUsername": {
            "Type": "String",
            "NoEcho": true
        },
        "DatabasePassword": {
            "Type": "String",
            "NoEcho": true
        },
        "DatabaseName": {
            "Type": "String"
        }
}
```

I would expect `DatabaseHost` to be echo'ed in the console while the value for `DatabasePassword` would be masked (******)

Currently the values for `DatabaseHost` and `DatabasePassword` are echoed out to the console when the `deploy-serverless` command is run.

```
dotnet --version
2.1.105
```

```<DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.1.1" />```

Please let me know if there is more information I can provide.

**Comment by normj** [comment]
I agree we should mask those parameter values.

**Comment by normj** [comment]
Version 2.1.3 of `Amazon.Lambda.Tools` looks for the NoEcho property and if found and set to true it will output **** for the parameter value.
