### ISSUE TITLE
swagger yaml parsed incorrectly

### ISSUE THREAD

**Issue by lmunro** [aws/aws-lambda-dotnet#265]
```
MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyApi
      DefinitionBody:
        swagger: 2
        paths:
          '/mypath':
            get:
              responses:
               '200':
                  description: my description
```

In this example '200': ends up as 200: in the template it attempts to deploy.  This fails because the key needs to be a string.  The same template works fine with sam local.

**Comment by wcharlesm** [comment]
I also ran into this issue in addition to errors parsing parsing lines like:

TableName: !Sub "Rides-${AWS::StackName}"

**Comment by normj** [comment]
Closing for lack activity. There is has been a lot of Yaml improvement which hopefully fixed the issue
