### ISSUE TITLE
Any guidance for handling SES events with Lambda .NET?

### ISSUE THREAD

**Issue by winzig** [aws/aws-lambda-dotnet#27]
Is there an ETA for SES (Simple Email Service) Lambda support in .NET? 

Or any recommendations for temporarily going it alone?

**Comment by winzig** [comment]
Am I on the right track: https://github.com/winzig/aws-lambda-dotnet/tree/simple-email-service/Libraries/src/Amazon.Lambda.SimpleEmailEvents

**Comment by winzig** [comment]
And good night ;) 

https://github.com/aws/aws-lambda-dotnet/pull/29

**Comment by normj** [comment]
Pull request merged and [NuGet package](https://www.nuget.org/packages/Amazon.Lambda.SimpleEmailEvents) released. Thanks again for the pull request.
