### ISSUE TITLE
Support for .NET Core 2.1

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-lambda-dotnet#272]
Hi,

Just curious if .NET Core 2.1 support will become available soon after it has been released, or can we expect it taking a longer time, like what happened with .NET Core 2.0? Are there any significant changes that need to be made to Lambda?

On another note, are there any plans to support .NET Core 2.1 RC1? 🤔 

Thanks!

**Comment by vellozzi** [comment]
We're working hard to make .NET Core 2.1 available in Lambda.  
I'm unable to comment on any specific timeline though.  
There are no plans to support .NET Core 2.1 RC1.

**Comment by raRaRa** [comment]
FYI .NET Core 2.1.0 was officially released today. Can't wait to upgrade!

**Comment by Kralizek** [comment]
@raRaRa was it? I couldn't find it anywhere

**Comment by danielabbatt** [comment]
All the nuget packages have been updated. Still no announcement by the looks of it.

**Comment by zolrath** [comment]
Announcement just went up! https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by daolavi** [comment]
Is .net core 2.1 available in Lambda ? According to [this article](https://aws.amazon.com/blogs/developer/net-core-2-1-and-aws/), it looks like not available yet.

**Comment by vellozzi** [comment]
It isn't available yet.  That blog is the right place to look for the announcement though.

**Comment by raRaRa** [comment]
How's the progress coming along? 😁

**Comment by vellozzi** [comment]
Still working on it...

**Comment by normj** [comment]
Out of curiosity what features in 2.1 are you most excited for when it comes to Lambda?

**Comment by raRaRa** [comment]
@normj Mostly runtime & networking performance improvements, `HttpClientFactory`, and `Span<T>`, `Memory<T>`, and friends.

**Comment by raRaRa** [comment]
On another note, are you working on supporting .NET Core `2.1.1` from the start, which has some neat bug fixes, or can we expect `2.1.0` to be supported first?

And thanks for keeping us in the loop, much appreciated. Love the excellent work you guys have done so far. ❤️

**Comment by ferugi** [comment]
The thing I'm most looking forward to with .NET Core 2.1 is [Tired Compilation](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1#jit-compiler-improvements) - as I understand it should offer some significant improvements on [cold start time](https://theburningmonk.com/2017/06/aws-lambda-compare-coldstart-time-with-different-languages-memory-and-code-sizes/).

**Comment by federicorinaldi** [comment]
Based on the[ end of life of .NET Core 2 after the release of 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/) can we get an estimation when this is going to be ready to plan the upgrades?

**Comment by jasonwhetton** [comment]
Any release date in sight yet? Waiting on this to fix compatibility issues with MongoDB atlas.

**Comment by melih154** [comment]
Interested in below features.
- EF 2.1 
    - Performance
    - GroupBy
- .Net Core 2.1
    - `ApiController` attribute and automatic model validation

**Comment by raRaRa** [comment]
Seems like `2.1` was released 22 minutes ago. Going to dig into it later tonight.

**Comment by normj** [comment]
.NET Core 2.1 for Lambda was just released. https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-1-support-released/

**Comment by aaronhudon** [comment]
@normj how long until the VSTS AWS Lambda Deploy Function extension is updated to allow runtime 2.1 selection?

![image](https://user-images.githubusercontent.com/4406811/42477538-54638f2e-8386-11e8-981c-508bc993a49f.png)

**Comment by normj** [comment]
@aaronhudon We plan on getting VSTS updated next week with the new enum. Unfortunately it got batched up with some other VSTS features we have coming out with the next release. Let me know if that is going to be a problem and I can see what we can work out.

**Comment by raRaRa** [comment]
Seems like .NET Core 2.1.2 is now out with some security update. Is it going to be difficult/time consuming process for Lambda to support the latest version of .NET Core?

**Comment by normj** [comment]
@raRaRa We are working on the 2.1.2 but I'm not sure of the timing when it will be in Lambda.

**Comment by virzak** [comment]
I upgraded the AWS Toolkit to version 1.14.4.0, Microsoft.AspNetCore.App to 2.1.0 and Amazon.Lambda.Tools to 2.2.0

When I Publish to AWS Lambda the dialog shows the correct framework (2.1) and deploys smoothly.

However when I access the API, I get an error and the CloudWatch says:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0' was not found.
- Check application dependencies and target a framework version installed at:
/
- Alternatively, install the framework version '2.1.0'.
Failed to execute the Lambda function. The dotnet CLI failed to start with the provided deployment package. Please check CloudWatch logs for this Lambda function to get detailed information about this failure.: LambdaException
```

Am I doing something wrong?

**Comment by normj** [comment]
In your serverless.template file for the AWS::Serverless::Function resource did you update the `Runtime` property to `dotnetcore2.1`. Sorry we should have put that in the blog post.

**Comment by virzak** [comment]
@normj That was the missing piece. Thanks!

**Comment by raRaRa** [comment]
@ferugi Super interesting, thanks for sharing. Do you know if there are any known side effects of using tiered compilation, e.g. could it actually cause overall worse performance while the startup time becomes faster.

**Comment by normj** [comment]
@ferugi Any chance you can quantify the performance improvement? I didn't really notice much in my testing but I might not have had enough of a real world scenario.

**Comment by ferugi** [comment]
Sorry for the slow responce. @normj I don't have a good real world example, but a quick test with Lambda and API Gateway gave [these results](https://i.imgur.com/lJ3gKsd.png).
@raRaRa I don't know enought to give you a real answer. That said, in the test I ran it did look like there was a bit more variation in response time of subsequent calls when Tiered Compilation was enabled.

**Comment by raRaRa** [comment]
@normj Any update on support for .NET Core 2.1.3? Thanks!

**Comment by vellozzi** [comment]
No updates.  We're still working on getting it out as soon as we can.

**Comment by ayalbelling** [comment]
Wonder if anyone has encountered "Process Failure" trying to containerise dotnet core 2.1 on AWS Beanstalk for a Web App?

I've followed the recommendations below for powershell script, aws manifest json and project file changes, but still Beanstalk seems not to be running the core 2.1 container.

POWERSHELL SCRIPT (PreInstallSetup.ps1 in the root of my project)
if(!(Test-Path 'C:\dotnet-hosting-2.1.0-win.exe')) { 
    Invoke-WebRequest -Uri 'https://download.microsoft.com/download/9/1/7/917308D9-6C92-4DA5-B4B1-B4A19451E2D2/dotnet-hosting-2.1.0-win.exe' -OutFile 'C:\dotnet-hosting-2.1.0-win.exe'
    Start-Process "msiexec.exe" -ArgumentList '/i C:\dotnet-hosting-2.1.0-win.exe /quiet /log c:\PreInstallSetup.log' -Wait
}

PROJECT FILE
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Include="aws-windows-deployment-manifest.json" CopyToPublishDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.ElasticBeanstalk.Tools" Version="1.1.4" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="PreInstallSetup.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

AWS MANIFEST JSON (aws-windows-deployment-manifest.json in the root of project)
{
  "manifestVersion": 1,
  "deployments": {
    "aspNetCoreWeb": [
      {
        "name": "ofw-dev",
        "parameters": {
          "appBundle": ".",
          "iisPath": "/",
          "iisWebSite": "Default Web Site"
        },
        "scripts": {
          "preInstall": {
            "file": "PreInstallSetup.ps1"
          }
        }
      }
    ]
  }
}

**Comment by raRaRa** [comment]
https://blogs.msdn.microsoft.com/dotnet/2018/08/02/tiered-compilation-preview-in-net-core-2-1/

**Comment by genifycom** [comment]
Once you have updated to 2.1.2 then 2.1.0 will no longer allow dynamic changes to cshtml files. I get this error https://github.com/dotnet/core/issues/1728

This has forced us to upgrade to 2.1.2 to get back productivity. Unfortunately we can no longer deploy to Lambda so we are currently stuck.

**Comment by amivit** [comment]
Also quite stuck without the latest patch. Will 2.1.1 / 2.1.2 be ready soon, or should we consider changing our architecture entirely, to self-built docker containers with Fargate/self-hosted Kubernetes?

**Comment by vellozzi** [comment]
We're working to get 2.1.2 released as soon as possible.
You shouldn't need to change anything.

**Comment by virzak** [comment]
In the meantime 2.1.3 is out.

Just out of curiosity, what's involved in upgrading to latest .NET major or minor version? Feels like a continuous catch-up cycle.

**Comment by vellozzi** [comment]
There are a lot of steps behind the scenes to build, test, verify and deploy new runtimes into AWS Lambda.

You're totally right about the catch-up cycle thing.   Improving that is one of our top priorities for AWS Lambda .NET Core support.

**Comment by PaulDMendoza** [comment]
2.1.4 is out now.

**Comment by vellozzi** [comment]
We're working on that now instead.  We'll keep you posted.

**Comment by melih154** [comment]
Found out that [this](https://github.com/aspnet/KestrelHttpServer/issues/2694) issue is fixed with .NET Core 2.1.4. 

Seems like a good reason to get Lambda Environment upgraded to 2.1.4 soon :) - as it may help on the good use of underlying CPU resources.

Thanks for the work.

**Comment by raRaRa** [comment]
@melih154 Wow, I wasn't aware of this issue. Is the new socket enabled by default in .NET Core 2.1?

We really need .NET Core 2.1.4 support. 🍕

**Comment by raRaRa** [comment]
And `2.1.5` is out. 
https://blogs.msdn.microsoft.com/dotnet/2018/10/02/net-core-october-2018-update/

**Comment by normj** [comment]
Lambda is deployed with 2.1.4 and 2.1.5 is in the development pipeline. The Lambda [README](https://github.com/aws/aws-lambda-dotnet#version-status) has been updated with a new table tracking the current versions. Hope that helps with the visibility.

**Comment by raRaRa** [comment]
It sure does! Thank you so much.
