### ISSUE TITLE
Logging documentation out of date

### ISSUE THREAD

**Issue by DanielLaberge** [aws/aws-lambda-dotnet#275]
The documentation for Amazon.Lambda.Logging.AspNetCore is wrong and misleading. (https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore#user-content-configuration)

1. The appsettings.json example is wrong. It uses the section "Lambda.Logging", but the code at APIGatewayProxyFunction.CreateWebHostBuilder() uses "Logging": logging.AddLambdaLogger(hostingContext.Configuration, "Logging");

2. The example for "Configuration through code" and Configuration through IConfiguration are also misleading because the LambdaLogger is actually configured by APIGatewayProxyFunction.CreateWebHostBuilder() by default. I was not able to override any settings other than by using appsettings.json with "Logging" as section name.

3. The provided example to filter Microsoft logs does not work, it has to be "Microsoft.*": "Information" to work as expected, not "Microsoft": "Information".

The example in this blog post is also wrong for the same reasons.
https://aws.amazon.com/blogs/developer/running-serverless-asp-net-core-web-apis-with-amazon-lambda/

**Comment by naingyelin** [comment]
I can't get the log filtering to work at all using the Asp.net core 2.1 Web Api Bule Print.
I had this in the appsettings.json according to what @DanielLaberge had discovered. 
`{
    "Logging": {
        "LogLevel": {
            "Default": "Debug",
            "Microsoft.*": "Debug"
        }
    },
    "AppS3Bucket": ""
}`

In my controller I am logging as follows

` public class ValuesController : Controller
    {
        ILogger Logger { get; set; }

        public ValuesController(ILogger<ValuesController> logger)
        {
            this.Logger = logger;
        }
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            Logger.LogDebug("We are here !!!");
            Logger.LogDebug("We are here...");
            return new string[] { "value1", "value2" };
        }
`

I am only able to see [**Information**] level entries in CloudWatch.

**Comment by ashishdhingra** [comment]
@DanielLaberge Just noticed in the code for [LambdaLoggerOptions](https://github.com/aws/aws-lambda-dotnet/blob/eb1e81fc6b33841c192b248d88ede970e53dd092/Libraries/src/Amazon.Lambda.Logging.AspNetCore/LambdaLoggerOptions.cs#L15), there is a constant `DEFAULT_SECTION_NAME` which is set as `Lambda.Logging`. This constant is used in constructor [LambdaLoggerOptions(IConfiguration configuration, string loggingSectionName)](https://github.com/aws/aws-lambda-dotnet/blob/eb1e81fc6b33841c192b248d88ede970e53dd092/Libraries/src/Amazon.Lambda.Logging.AspNetCore/LambdaLoggerOptions.cs#L109).
