### ISSUE TITLE
Custom initialization

### ISSUE THREAD

**Issue by axel-zarate** [aws/aws-lambda-dotnet#278]
When running locally, it's easy to run initialization logic (i.e. database) before the app is run:
```csharp
public static async Task Main(string[] args)
{
    var host = BuildWebHost(args);

    using (var scope = host.Services.CreateScope())
    {
        // Add custom initialization here
        var initializer = scope.ServiceProvider.GetService<DbContextInitializer>();
        await initializer .Run();
    }

    await host.RunAsync();
}
```
However, there does not seem to be a direct way of achieving the same in `APIGatewayProxyFunction`. I have accomplished it using some reflection to tap into a private field of the `APIGatewayProxyFunction` class and get access to the service provider:
```csharp
protected override void PostCreateContext(HostingApplication.Context context, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
{
    if (!_initialized)
    {
        lock (_lock)
        {
            if (!_initialized)
            {
                AsyncHelpers.RunSync(Initialize);
                _initialized = true;
            }
        }
    }
}

private async Task Initialize()
{
    // FIXME: Temporary solution to get access to the service provider
    var hostField = typeof(APIGatewayProxyFunction).GetField("_host",
        BindingFlags.NonPublic | BindingFlags.Instance);
    if (hostField == null)
    {
        throw new ApplicationException("Could not find host field");
    }

    var host = hostField.GetValue(this) as IWebHost;
    if (host == null)
    {
        throw new ApplicationException("Host value is null.");
    }

    var serviceProvider = host.Services;
    // END FIXME

    using (var scope = serviceProvider.CreateScope())
    {
        var logger = scope.ServiceProvider.GetService<ILogger<LambdaEntryPoint>>();
        logger.LogInformation("Running initialization.");

        // Add custom initialization here
        var initializer = scope.ServiceProvider.GetService<AppDbContextInitializer>();
        await initializer.Run();
    }
}
```
Am I missing something? Is there a better solution to this? If not, it would be if `APIGatewayProxyFunction` exposed the necessary services and methods for initialization.

**Comment by normj** [comment]
Why wouldn't you do this initializing in Startup like at the end of ConfigureServices?

**Comment by axel-zarate** [comment]
It works that way too, but the problem is that it runs when trying to generate new migrations (which would result in an error) or when executing integration tests, which caused the undesired effects.

Another option would be to add a piece of middleware to run the initialization, but then it would be deferred to the execution of the first request (which may or may not be desired).

Another use case is when you need to run different initialization logic for Lambda/production and local/testing environments (which can also be achieved by examining the environment name, granted).

Maybe there is no need to introduce the concept of initialization inside the `APIGatewayProxyFunction` class but just exposing the `IServiceProvider` would allow for this and other scenarios to be implemented more easily.

**Comment by normj** [comment]
I like the suggestion of having a `protected virtual` callback. I just checked in a new `PostCreateWebHost` method which will go out with the next release.

https://github.com/aws/aws-lambda-dotnet/commit/6e51d454ff27f0ba3f7bd6cf750757fd515f6831

**Comment by normj** [comment]
Version 3.0.2 of Amazon.Lambda.AspNetCoreServer was released with the new `PostCreateWebHost` method.
