### ISSUE TITLE
Is async recommended?

### ISSUE THREAD

**Issue by winzig** [aws/aws-lambda-dotnet#28]
I've seen function handlers specified like this in your samples:

`public string Handler(S3Event s3Event)`

And also like this from the AWS Toolkit for VS/Lambda support:

`public async Task Handler(S3Event input, ILambdaContext context)`

Is there documentation anywhere on best practices?

**Comment by winzig** [comment]
Oh, duh, sorry! 😁 I just spent a few weeks working on a Node.js-based Lamda function, everything is asynchronous and waterfalls, and was thinking the use of `async` here had some special meaning related to the Lambda execution environment.

**Comment by RoyiNamir** [comment]
@normj It's also related to money. If you function support `async` and you `wait()` or `.Result` it , you're actually holding a thread consuming CPU cycles which ,in large scale , costs more. Right ?

**Comment by Kralizek** [comment]
Imho it's irrelevant because you get billed by the amount of time the container hosting the lambda function is up, not by how much CPU you are actually using.

**Comment by RoyiNamir** [comment]
@Kralizek  https://read.acloud.guru/save-time-and-money-with-aws-lambda-using-asynchronous-programming-3548ea65f751

> One of the easiest ways to tighten your Lambda bill is to not pay for waiting — which means getting your arms around async. Paying for idle is bad.

**Comment by Kralizek** [comment]
@RoyiNamir as I read the article is that you either decompose the lambda in multiple ones and let AWS invoke the next step, or you use language artifacts to parallelise your work until you actually need the result (hence shortening the execution of the lambda).

In .NET lingo, you could do something like
```csharp
var task1 = DoSomethingAsync();
var task2 = DoSomethingElseAsync();
var task3 = DoYetAnotherThingAsync();

await Task.WhenAll(task1, task2, task3);
```
as opposed to 
```csharp
var task1 = await DoSomethingAsync();
var task2 = await DoSomethingElseAsync();
var task3 = await DoYetAnotherThingAsync();
```

**Comment by RoyiNamir** [comment]
@Kralizek  thanks for clarification
