### ISSUE TITLE
Should deploy-function also call update-function-config?

### ISSUE THREAD

**Issue by winzig** [aws/aws-lambda-dotnet#280]
I'm using `dotnet lambda deploy-function --config-file myconfig.json` from this environment:

```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

In my .json file I made a mistake when I first deployed, and used this function-handler:

```
"function-handler": "Serverless::Serverless.Notifications.Functions::SendNotifications",
```

That first "Serverless::" should have been named "Notifications::" because my assembly name is Notifications.dll. So I updated my json to correct this:

```
"function-handler": "Notifications::Serverless.Notifications.Functions::SendNotifications",
```

However, even after I fixed it, I kept getting this error while trying to execute my function:

```
Could not find the required 'Serverless.deps.json'.  This file should be present at the root of the deployment package.
```

I finally noticed in the Lambda console on the AWS website that the "Handler" area was not being updated. It still looked like this even after I deployed many times:

<img width="312" alt="screen shot 2018-05-22 at 7 24 01 pm" src="https://user-images.githubusercontent.com/127062/40400548-7085f4c6-5df7-11e8-9104-2a03a63e9e3e.png">

Once I changed it through the portal, things worked.

I encountered a similar issue with some environment variables I'm setting in that same JSON. They don't seem to be updated once the function is initially created.

This is when I stumbled on the `update-function-config` option for `dotnet lambda`. Is there a performance reason why this functionality wouldn't be happening for every deploy request?

**Comment by normj** [comment]
When I coded it I was worried if we automatically applied all the settings in the config file for existing functions you might change something critical unintentionally. So for deploying an existing function I ignored the function configuration settings from the file. In hindsight I kind of regret that decision because it has caused lots of confusion. you can override the behavior by using the switch `--apply-defaults true` which will force the deploy-function command to take the values from the file. You can also add `apply-defaults` to the config file as well.

**Comment by winzig** [comment]
OK, thank you for the info. 

Perhaps an interactive mode can kick in by default, if it sees a difference between the config in the json and the one at AWS, and ask the user what they want to do?

**Comment by normj** [comment]
The problem with that is it could break peoples CI system that were using these commands that suddenly break by blocked for interactive mode. I think next major version update to the tools I'll probably change the default behavior.

**Comment by winzig** [comment]
Thank you for the explanation, I'll look forward to the change, but in the meantime the `apply-defaults` should solve our current issue.
