### ISSUE TITLE
Versioning confusion

### ISSUE THREAD

**Issue by scionwest** [aws/aws-lambda-dotnet#281]
While reading your [blog post](https://aws.amazon.com/blogs/developer/serverless-asp-net-core-2-0-applications/) noting that .Net Core 2.0 is now supported, it looks like the runtime you support in Lambda is 2.0.4. I know there is a difference between runtime, framework and SDK versions; I'm not able to find a clear answer in Microsofts documentation on which version of the SDK actually includes runtime 2.0.4.

When I look at their [downloads page](https://www.microsoft.com/net/download/all) there isn't an SDK or runtime that is versioned at 2.0.4 for download. From what I could tell, it sounds like 2.1.3 on their [Github download archive](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.4-download.md) has runtime 2.0.4 while the 2.1.3-200 on their official downloads page runs a newer runtime.

Which version of the SDK should be downloaded and installed on our build servers so we ensure what we build can be deployed to Lambda? Which version of the SDK includes Microsoft.AspNetCore.All 2.0.3 for our build servers?

**Comment by scionwest** [comment]
A follow-up question, what is the life-cycle plan for Lambda and their .net core versioning support? Microsoft's [support policy](https://www.microsoft.com/net/support/policy) is that support is dropped 3 months after the next release is provided. With 2.1 looming, what will Amazons support life-cycle be on Lambdas currently targeting 2.0.4 a year after Microsoft drops support?

**Comment by vellozzi** [comment]
Right now you should be using https://github.com/dotnet/core/releases/tag/v2.0.5
We're in the process of updating to https://github.com/dotnet/core/releases/tag/v2.0.7-2 .
Keep an eye out for an announcement when it's released.  Sorry, I can't comment on the specific timeline for this.

**Comment by vellozzi** [comment]
[Here](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) is our support policy for Lambda runtimes.

**Comment by scionwest** [comment]
@vellozzi Where will I see that announcement? Going back through the blog posts for AWS Lambda I don't see any announcements for the 2.0.5 support.

**Comment by vellozzi** [comment]
You should check the blog.  If we missed 2.0.5 it was an oversight.
