### ISSUE TITLE
RemoteCertificateNameMismatch on .NET Core when validating SSL connection to RDS Aurora

### ISSUE THREAD

**Issue by paya-cz** [aws/aws-lambda-dotnet#282]
As per https://github.com/mysql-net/MySqlConnector/issues/498 I am using AWS Lambda .NET Core 2, and try to connect to AWS RDS Aurora cluster (and/or its primary instance). I use [this certificate](https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem) to validate the Aurora SSL certificate. However, the [SslStream](https://msdn.microsoft.com/en-us/library/ms145056(v=vs.110).aspx) and its [certificate validation callback](https://msdn.microsoft.com/en-us/library/system.net.security.remotecertificatevalidationcallback(v=vs.110).aspx) always report the certificate as having a name mismatch ([SslPolicyErrors.RemoteCertificateNameMismatch](https://msdn.microsoft.com/en-us/library/ms145055(v=vs.110).aspx)).

I have used Wireshark to capture the SSL traffic between my local machine and Aurora when using SQL Workbench, and verified that the certificate returned by Aurora is fine, with the subject name being the cluster primary instance endpoint, and cluster endpoint being listed in the alternate subject names.

However, it seems that the Amazon Linux that is hosting the Lambda may have some issue in its SSPI and always report a certificate name mismatch? Running the code on Ubuntu and Windows does not show this problem, but lambda does.

**Comment by bgrainger** [comment]
While investigating this, I found a macOS-specific bug in loading concatenated certificates (“PEM bundles”): dotnet/corefx#29910

**Comment by NGL321** [comment]
Hi @paya-cz,

Unfortunately, since this is an issue with the driver, it is out of our control to fix. For now I am going to close the issue, if you disagree with the assessment, feel free to reopen

😸
