### ISSUE TITLE
.NET Core 2.1 released, please add Lambda support

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-lambda-dotnet#285]
.NET Core and ASP.NET Core 2.1 have been released. Just adding this so you can add Lambda support for it. 

https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

Thanks

**Comment by vellozzi** [comment]
We're working on this.  I'm unable to comment on the timeline of our release though.

**Comment by normj** [comment]
.NET Core 2.1 for Lambda was just released. https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-1-support-released/
