### ISSUE TITLE
Guidance for HttpClient life-cycle in Lambdas

### ISSUE THREAD

**Issue by scionwest** [aws/aws-lambda-dotnet#287]
Microsoft recommends, for most use-cases, that you create a [singleton of HttpClient, configure it and share it](https://blogs.msdn.microsoft.com/shacorn/2016/10/21/best-practices-for-using-httpclient-on-services/) for the life-cycle of the app, or Http request in some cases.

How do Lambda's work in regards to this? Each time my Lambda fires (regardless if cold/warm) is it the same process running each time or a new dotnet process? If it's a new dotnet process each time then I can safely just instantiate and dispose of the `HttpClient` because it's only used once through-out the life-cycle of the Lambda. If the same process is re-used (with the handler invoked multiple times) then I need to handle the life-cycle of my `HttpClient` differently.

Any guidance on how we should treat the usage of HttpClient in Lambda's would be appreciated.

**Comment by normj** [comment]
Here is my talk from NDC Minnesota last month. If you skip ahead to about 2:40 into I go through the lifecycle of a Lambda environment which will hopefully clear things up for you.  

https://vimeo.com/271358846

**Comment by scionwest** [comment]
Answered my question, thanks!

**Comment by judedaryl** [comment]
This was so helpful! Although this is 2 years too late, Thanks!

**Comment by az-oolloow** [comment]
Thanks @normj 

For anyone who comes across this searching for answers - create a singleton HttpClient, it should survive a few invocations of events until such time that you had a long period of inactivity and Lambda destroys the environment running your code.

**Comment by andremantaswow** [comment]
Video link is broken...

@az-oolloow can you share how/where you register it?

My setup is lambda per function with APIGatewayProxyRequest as parameter, and on the begining of the method I create a new ServiceCollection and register my dependencies. I dont see how registering HttpClient there as Singleton will make much difference between invocations

**Comment by markcastle** [comment]
Here is the video for anyone looking for it (even a few years down the line)... https://youtu.be/sgXq5-UGRt8?t=160 
HTH :-)
