### ISSUE TITLE
NullReferenceException on `APIGatewayProxyFunction.MarshallRequest`

### ISSUE THREAD

**Issue by halak** [aws/aws-lambda-dotnet#289]
I have linked CloudWatch trigger to Lambda function that has linked API Gateway trigger already.
That is similar to below code.
```cs
new LambdaEntryPoint()
    .FunctionHandlerAsync(new APIGatewayProxyRequest(), new TestLambdaContext())
    .GetAwaiter()
    .GetResult();
```
[Exception Location](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L474)

Yes, it is bad behaviour.
But, I guess that `APIGatewayProxyFunction.MarshallRequest` is fault tolerant method and above code line was missed null check code. Please review the code.

this code is no throwed exception.
```cs
new LambdaEntryPoint()
    .FunctionHandlerAsync(new APIGatewayProxyRequest() { Path = "/" }, new TestLambdaContext())
    .GetAwaiter()
    .GetResult();
```

**Comment by normj** [comment]
I'm trying to understand the use case. Is to have a CloudWatch schedule event do a keep alive on the ASP.NET Core Lambda function?

**Comment by halak** [comment]
Yes I was done for keep warm... but currently not.
Im reported for code's fault tolerances.
