### ISSUE TITLE
NodeServices/Javascript Services

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#292]
If we use the https://github.com/aspnet/JavaScriptServices service in a C# AWS Lambda function, what will happen?

Does a C# AWS Lambda container automatically contain a node install?

**Comment by normj** [comment]
You don't have access to the Node.js runtime from the .NET Core so I don't see how you would make it work without doing a lot of crazy stuff.

**Comment by genifycom** [comment]
Ok thanks Norm :-)
