### ISSUE TITLE
Support for async API Gateway custom authorizers

### ISSUE THREAD

**Issue by swlasse** [aws/aws-lambda-dotnet#293]
Let's say I have an async API GW authorizer that should always return 401s. When I implement it like this:

```
public async Task<APIGatewayCustomAuthorizerResponse> AuthorizeAsync(Stream input, ILambdaContext context)
{
    await Task.Run(() => throw new Exception("Unauthorized"));
    return null;
}
```

The Lambda runtime wraps the `Exception` into an `AggregateException`:

```
One or more errors occurred. (Unauthorized): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
...
```

I assume this is because the Lambda runtime does a `.Wait()` instead of `GetAwaiter().GetResult()` on the task?

Anyway, API GW then  checks if the `Exception` message _starts_ with `Unauthorized`. In that case, API GW returns a 401, otherwise it returns a 500. Obviously, since the exception is now wrapped into an AggregateException it starts with `One or more...`, causing API GW to return 500 instead of 401.

I could solve this in my authorizer by doing:

```
public APIGatewayCustomAuthorizerResponse Authorize(Stream input, ILambdaContext context)
{
    Task.Run(() => throw new Exception("Unauthorized")).GetAwaiter().GetResult();
    return null;
}
```

... which causes the exception to go unwrapped and thus returning:

`Unauthorized: Exception`

... which matches the API GW "regex", and gives me the desired 401.

However, this forces me to remove the asyncness of the top-level lambda method signature.

I am wondering how the AWS Lambda runtime awaits an async Lambda? I guess the runtime is returning the AggregateExceptions by design?

Further, I would like to know if there is another way around implementing a truly async C# authorizer without me needing to do the "top level" synchronization?

Finally, thanks for making AWS a great place to be for .NET developers! :) Keep up the good work.

**Comment by normj** [comment]
In the .NET Core 2.1 Lambda runtime if you set the environment variable `UNWRAP_AGGREGATE_EXCEPTIONS` to the value `1` then the runtime will unwrap the aggregate exception. We can't make that the default in the 2.1 environment because that would be a breaking change. In future runtimes we will into make that the default behavior.

**Comment by swlasse** [comment]
That is brilliant - thanks for getting back to me on this @normj. Is this and other runtime environment vables documented somewhere? Have tried to look for them, but without any luck.

**Comment by swlasse** [comment]
Setting `UNWRAP_AGGREGATE_EXCEPTIONS: 1` works great. Thanks again @normj.
Can you elaborate on if this and other .NET Core runtime environment variables are documented somewhere?

**Comment by DamirAinullin** [comment]
@normj Do we need to setup UNWRAP_AGGREGATE_EXCEPTIONS  for .NET Core 3.1 Lambda runtime? Or this is already default behavior?

**Comment by normj** [comment]
@DamirAinullin UNWRAP_AGGREGATE_EXCEPTIONS does nothing in .NET Core 3.1 as that is just the default and only behavior in the 3.1 Lambda runtime. I put out a blog post that talks about that change along with many other things. https://aws.amazon.com/blogs/developer/one-month-update-to-net-core-3-1-lambda/
