### ISSUE TITLE
"dotnet lambda deploy-function" fails badly if aws-lambda-tools-defaults.json or credentials profile is missing

### ISSUE THREAD

**Issue by loop-evgeny** [aws/aws-lambda-dotnet#297]
Similar to #152, but still an issue in Lambda Tools for .NET Core applications 2.2.0

When I run `dotnet lambda deploy-function` for a project that does not have a `aws-lambda-tools-defaults.json` it prompts for the details:

```
Enter Build Configuration: (Configuration to build with, for example Release or Debug.)
Enter Framework: (Target framework to compile, for example netcoreapp1.0.)
Enter Runtime: (The runtime environment for the Lambda function)
Enter Framework: (Target framework to compile, for example netcoreapp1.0.)
```

Then, when those details are left blank, it throws a NullReferenceException:

```
Unknown error executing docker push to Amazon Elastic Container Registry: Object reference not set to an instance of an object.
        at Amazon.Lambda.Tools.LambdaUtilities.ValidateTargetFrameworkAndLambdaRuntime(String lambdaRuntime, String targetFramework)
        at Amazon.Lambda.Tools.Commands.DeployFunctionCommand.<PerformActionAsync>d__38.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.<ExecuteAsync>d__10.MoveNext()
```

Even if I explicitly try to use the file with `--config-file aws-lambda-tools-defaults.json` it still does the same thing and does not tell me that the file is missing. (I spent a while troubleshooting this, as I was sure the file was there, but I was actually on a branch that didn't have it.)

Similarly, specifying a profile that doesn't exist with `--profile` does not give an error, but seems to use some other profile (the default one maybe, I'm not sure).

**Comment by normj** [comment]
Looks like we need to add some more validation logic.

**Comment by normj** [comment]
The latest version will now throw an exception with a meaningful error message if the specified config file is not found.

**Comment by loop-evgeny** [comment]
Thanks! What version exactly?
