### ISSUE TITLE
Web App Sample in code fails on PUT

### ISSUE THREAD

**Issue by jkpindahbc** [aws/aws-lambda-dotnet#30]
Attempting to test the sample Web App through PostMan and getting 403.  The functions work as expected if I test it directly but not through the API Gateway.  Is there some special manual setting required to make the requests operate?  Getting a 403.

https://zcxhhsjop3.execute-api.us-west-2.amazonaws.com/Prod

**Comment by pragatiulag** [comment]
we are facing the same issue. how to fix this?

> 
> 
> Attempting to test the sample Web App through PostMan and getting 403. The functions work as expected if I test it directly but not through the API Gateway. Is there some special manual setting required to make the requests operate? Getting a 403.
> 
> https://zcxhhsjop3.execute-api.us-west-2.amazonaws.com/Prod
