### ISSUE TITLE
BUG: dotnet lambda package-ci creates faulty CloudFormation output template with CodeBuild

### ISSUE THREAD

**Issue by ThomasJaeger** [aws/aws-lambda-dotnet#305]
I created a CloudFormation script with two dotnet core C# lambdas named:

> ProcessCreateAccountFromDynamoDBEvent
> CreateAccount

When my buildspec.yml file is being executed in CodeBuild, it creates a wrong CloudFormation template output file where it ignores and overwrites the S3Key of Lambda ProcessCreateAccountFromDynamoDBEvent.

Attached is a comparison of the original CloudFormation stack and the output templated generated. The S3Key produced was CreateAccount-636702840090957270.zip. This file was supposed to go ONLY to the CreateAccount Lambda but instead it uses the same key for two seperate Lambdas including the ProcessCreateAccountFromDynamoDBEvent Lambda.

Please fix this ASAP. Thank you! 

![image](https://user-images.githubusercontent.com/1396719/44311248-f339f200-a3b1-11e8-92b0-a0d5f9be03e4.png)

**Comment by normj** [comment]
The current behavior with this feature is to replace all code locations. I agree with what you are doing is valid but what I need to figure out is if I change the code to only update code locations that are blank  would that cause a breaking change to anybody.

**Comment by normj** [comment]
Closing and use the other one you open for tracking
https://github.com/aws/aws-extensions-for-dotnet-cli/issues/27
