### ISSUE TITLE
Code property of AWS::Lambda::Function ignored

### ISSUE THREAD

**Issue by bslatner** [aws/aws-lambda-dotnet#306]
I'm deploying a serverless application that has two parts:

1) A web API
2) A static web site served up by CloudFront

For part 2, I need to specify a custom OriginResponse function in order to add security headers.

I've tried doing this two ways. First:

```json
    "OriginResponseFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "index.handler",
        "Runtime": "nodejs6.10",
        "Description": "Handle OriginResponse events from CloudFormation.",
        "MemorySize": 128,
        "Timeout": 3,
        "Role": { "Fn::GetAtt": [ "EdgeRole", "Arn" ] },
        "Code": {
          "ZipFile" : "a bunch of javascript code"
        }
      }
    }
```

and the second way:

```json
    "OriginResponseFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "index.handler",
        "Runtime": "nodejs6.10",
        "Description": "Handle OriginResponse events from CloudFormation.",
        "MemorySize": 128,
        "Timeout": 3,
        "Role": { "Fn::GetAtt": [ "EdgeRole", "Arn" ] },
          "Code": {
            "S3Bucket" : "my-bucket",
            "S3Key": "filecontainingindex.js.zip"
          }
        }
    }
```

In both cases, on deployment, the "Code" element is replaced with:

```json
        "Code": {
          "S3Bucket": "deploy-bucket-specified-in-aws-lambda-tools-defaults.json",
          "S3Key": "prefix/myproject-636702828855697731.zip"
        }
```

The expected behavior is that it would honor my explicit "Code" element.

**Comment by normj** [comment]
I want to make sure I understand. You have multiple functions in your template. Some you want the code property replaced but ones that have the code property already set you don't want them updated. Is that the right?

**Comment by bslatner** [comment]
Well, when you put it that way, it sounds crazy :)

I know that the whole point of the exercise is for the "deploy-serverless" operation to take my template and add the Code elements for me. 

My problem is that I have one function that **must** be written in JavaScript (Lambda@EDGE). All my other functions are written in C#. What I'm trying to do is deploy all of it as part of one stack, but that doesn't seem to be possible. My workaround, at present, is to manually create the JavaScript function and explicitly reference its ARN in the template.

I created the issue because it seems like it might be solved by not replacing explicitly specified `Code` properties.

**Comment by normj** [comment]
In version 3.1.0 of `Amazon.Lambda.Tools` the `dotnet lambda deploy-serverless` command will now do what you were asking. 

If the the S3Bucket field is set then the code assumes the code is already uploaded and leaves it that resource in the template alone. 

If S3Bucket is blank and the S3Key is pointing to a file it upload the file to S3 and updated the S3Bucket and S3 Key fields. 

If S3Key is pointing to a directory it will zip up the directory and upload that unless it is detected to be a .NET Core project folder in which case it will do the regular packaging of a .NET Core project and then upload the zip file.

This code is not yet in Visual Studio so you will need to do the deployment from the command line using the [Amazon.Lambda.Tools](https://aws.amazon.com/blogs/developer/net-core-global-tools-for-aws/) Global Tool.
