### ISSUE TITLE
System.Data.SqlClient exclude unnecessary runtimes folders when publishing.

### ISSUE THREAD

**Issue by rknewbow** [aws/aws-lambda-dotnet#31]
When referencing System.Data.SqlClient in a lambda project, after publishing, the publish folder includes a runtimes subfolder with 6 MB of files for the various supported runtimes. When running dotnet lambda package (or deploy-function), the required dlls for SqlClient are copied to the root of the publish folder, but  the runtimes folder is still included in the generated zip file. Is there a reason these need to be included, or is there an option I'm missing?

**Comment by normj** [comment]
Sounds like a good optimization for our tooling to exclude the other runtimes from the runtimes folder that won't be used in Lambda.

**Comment by rknewbow** [comment]
Thanks for the response. It would be great to see this added as an enhancement since it would be preferable to let the lambda CLI handle packaging for us instead of having to roll our own.

**Comment by normj** [comment]
Totally agree the lambda CLI is the place to do this optimization.

**Comment by normj** [comment]
Version 1.3.0-preview1 of Amazon.Lambda.Tools will now flatten the runtimes folder and only include the platform specific dependencies needed for the Lambda runtime.

**Comment by rknewbow** [comment]
Awesome! Thanks Norm. I just tested it and it shaved a couple MB off of the deployed code size.

**Comment by normj** [comment]
Great! Glad it made an impact
