### ISSUE TITLE
 'APIGatewayProxyResponse' does not contain a definition for 'IsBase64Encoded' when dotnet publish

### ISSUE THREAD

**Issue by r01010010** [aws/aws-lambda-dotnet#310]
I'm in Mac. When doing a `dotnet lambda deploy-function` compiler complains with `'APIGatewayProxyResponse' does not contain a definition for 'IsBase64Encoded'`.

The part of code:

      public class Function
      {
          public APIGatewayProxyResponse FunctionHandler(APIGatewayProxyRequest Request, ILambdaContext context)
          {
            return new APIGatewayProxyResponse
            {
                Body = EncodeTo64("foo"),
                IsBase64Encoded = true,
                StatusCode = 200
            };
          }
       }

The `.csproj`

    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <AWSProjectType>Lambda</AWSProjectType>
      </PropertyGroup>
    
      <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
        <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.3.0" />
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.0.0" />
        <PackageReference Include="MongoDB.Bson" Version="2.0.0" />
        <PackageReference Include="MongoDB.Driver" Version="2.0.0" />
        <PackageReference Include="iTextSharp" Version="4.1.2" />
      </ItemGroup>
    
      <ItemGroup>
        <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="2.2.0" />
      </ItemGroup>
    
    </Project>

**Comment by normj** [comment]
In your project file you are reference 1.0.0 of Amazon.Lambda.APIGatewayEvents but the IsBase64Encoded method was added in 1.1.0. The current version is 1.1.3 which I would recommend using.

**Comment by normj** [comment]
Closed as I believe answered
