### ISSUE TITLE
Controller not fire in .Net Core 2.1 when the controller in different project

### ISSUE THREAD

**Issue by jazztong** [aws/aws-lambda-dotnet#311]
Hi,

Before I upgrade AWS .Net project to 2.1, my project used to have one share project that has one common controller use by few projects, and it is able to trigger the controller when deploying to AWS, but after upgrade to .Net 2.1, the controller unable to trigger anymore, anyone has the same issue?

**Comment by normj** [comment]
Can you let me know if this is the same issue as reported here https://github.com/aws/aws-extensions-for-dotnet-cli/issues/21 and if the work around suggest in there works for you?

**Comment by jazztong** [comment]
Thanks @normj, yes it is the same issue, is there anyway that not require to change deployment option?

**Comment by normj** [comment]
I chimed in the .NET Core GitHub issue https://github.com/dotnet/sdk/issues/2122 for an update that I think would allow us to make this automatic. Till then our options our leave `PreserveCompilationContext ` at the default which puts a large **refs** folder in the package bloating the package size or set it to false shrinking the package size and improving colder start but we miss some scenarios like yours.

**Comment by normj** [comment]
Closing as there isn't much more we can do now.
