### ISSUE TITLE
ILambdaContext in constructor

### ISSUE THREAD

**Issue by odyth** [aws/aws-lambda-dotnet#317]
The ILambdaContext seems to be the only way to write things out to cloud watch. If you have one time initialization logic in your constructor it becomes challenging to deal with issues since you can't log anything as you don't have a context yet.

Could you support an option to take an ILambdaContext  as a parameter of your constructor then you can have logging right from the get go?

**Comment by normj** [comment]
ILambdaContext has information that is tied to the specific request that we wouldn't have when the constructor is called.

You can write to the ClouldWatch logs from the constructor by using `Console.WriteLine()`. The Lambda runtime captures all standard out and sends it to CloudWatch logs.

**Comment by odyth** [comment]
Good to know thank you for the update.
