### ISSUE TITLE
lambda.EmptyFunction parameter type seems to conflict with platform assumptions

### ISSUE THREAD

**Issue by jrr** [aws/aws-lambda-dotnet#321]
When you `dotnet new` a `lambda.EmptyFunction`, you get a function signature like this:
```c#
// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
// (...)
public string FunctionHandler(string input, ILambdaContext context) // (...)
// or, in F#:
//     member __.FunctionHandler (input: string) (_: ILambdaContext) =
```
Note that it takes a string as input.

When you deploy and attempt to test it, you'll find that the test tooling wants you to provide JSON input:

```
jrr@jrrmbp ~/r/g/g/s/test-lambda (master)> aws lambda invoke --function-name test-lambda --payload "hello world" out

An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Unrecognized token 'hello': was expecting ('true', 'false' or 'null')
 at [Source: [B@52c0593; line: 1, column: 7]
```

Okay, fine, here's some JSON:
```
jrr@jrrmbp ~/r/g/g/s/test-lambda (master)>
aws lambda invoke --function-name test-lambda --payload '{"Name":"value1"}' /dev/stdout
{
  "errorType": "JsonReaderException",
  "errorMessage": "Unexpected character encountered while parsing value: {. Path '', line 1, position 1.",
  "stackTrace": [
    "at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)",
    "at Newtonsoft.Json.JsonTextReader.ReadAsString()",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)",
    "at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)",
    "at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)",
    "at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)",
    "at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ]
}
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}
```

(also, from the web dashboard, if you try to _Configure test event_, even the "Hello World" event is JSON, and the UI won't let you save non-JSON)

So, I guess there's kind of two issues:
1) The example has a string input param, but the tooling _really_ wants it to be JSON.
2) The LambdaSerializer deserialization doesn't seem to handle an output type of _string_.

(to anyone that encounters this: it works just fine if you define a simple POCO or record type that the system can deserialize to, and use that for the input parameter)

**Comment by ChrisCalzaretta** [comment]
I am having a similar issue I believe. I have some very basic code right now that should describe vpcs. however when I call it, the code throws an error
My input I have logged and it comes out just as it was sent in to the lambda execution


`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.EC2.Model;
using Amazon.Lambda.Core;
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
namespace AWSLambda1
{
    public class Watcher
    {
        Amazon.EC2.AmazonEC2Client EC2Client { get; set; }
        public Watcher()
        {
            EC2Client = new Amazon.EC2.AmazonEC2Client();
        }
        public Watcher(Amazon.EC2.AmazonEC2Client ec2Client)
        {
            this.EC2Client = ec2Client;
        }

        [LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
        public async Task<string> FunctionHandler( string input, ILambdaContext context)
        {
            var t = await this.EC2Client.DescribeVpcsAsync();
            foreach (var i in t.Vpcs)
            {
                context.Logger.LogLine(i.VpcId);
            }
            
            return  "Success";
        }
        `
I get an error of 
{
  "errorType": "AggregateException",
  "errorMessage": "One or more errors occurred. (A task was canceled.)",
  "stackTrace": [
    "at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ],
  "cause":   {
    "errorType": "TaskCanceledException",
    "errorMessage": "A task was canceled."
  },
  "causes": [    {
      "errorType": "TaskCanceledException",
      "errorMessage": "A task was canceled."
    }
  ]
}


I do have a the role assigned with permissions of * for testing at this time.

**Comment by vellozzi** [comment]
If you have an input parameter that's a string you have to send a JSON string to the function.
```String with "quotes"```
would need to be sent as
```"String with \"quotes\""```

This is by design.
