### ISSUE TITLE
Amazon.Lambda.Tools transformations in aws-lambda-tools-defaults.json based stage/prod

### ISSUE THREAD

**Issue by ArcaneTSGK** [aws/aws-lambda-dotnet#323]
Current behaviour:
When running an automated build via Jenkins Pipeline, the command `dotnet lambda deploy-serverless` takes the values from the aws-lambda-tools-defaults.json with no regard for if we are wanting to deploy to Stage/Prod

Expected/desired behaviour: 
It should be possible to transform any of the variables in the defaults.json so a CI/CD Pipeline can use the `dotnet lambda deploy-serverless` command to deploy to the desired environment

**Comment by normj** [comment]
Sorry I'm not sure what you mean by transform. Do you want to have separate json files for Stage or Prod? If so you can create separate files and then specify the file you want using the `--config-file` switch.

**Comment by ArcaneTSGK** [comment]
Thanks for the response, I've successfully implemented using multiple config files.
