### ISSUE TITLE
ASP.NET Core Doesn't Know Authentication Has Occurred

### ISSUE THREAD

**Issue by chrisoverzero** [aws/aws-lambda-dotnet#330]
By directly setting `HttpContext.User`, ASP.NET Core doesn't know that authentication has occurred. This breaks some features that could otherwise be used. These include `Forbid` responses, the `HttpContext.GetTokenAsync` method, claims transformation, and more.

The simplest way to prevent this breakage is to move [the claims principal setting code][] into a service that claims to be an authenticator, but does no more than the current code does: copy already vetted properties into a new `ClaimsPrincipal`. My company has been running a fork of Amazon.Lambda.AspNetCoreServer that has this feature. We've been calling it a pseudo-authenticator. If this is accepted in principle, I can restore the default pseudo-authenticator to Cognito and have an MR open in a day or two.

[the claims principal setting code]: https://github.com/aws/aws-lambda-dotnet/blob/8f3d60815beaa6a497e26e08b3dd5256c80e9759/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L239-L246

**Comment by chrisoverzero** [comment]
Yeah, sure thing. Thanks. 

I’m traveling internationally now, so I’ll rebase and push when I’m back in the States.

**Comment by chrisoverzero** [comment]
Apologies, the abstraction of `AbstractAspNetCoreFunction` in the time since my original post has made the rebase trickier than I expected. We've abandoned the fork, and are now doing the authn bridging in a subclass of `APIGatewayProxyFunction`. (which is a load off me, lemme tell ya)

I've added that code to [a gist][]. Please pay no mind to the term "Platform". It's generalizable -- the current `ClaimsIdentity` code would/could slot into the `CreateIdentity` method.

Just to restate: By performing the setting of `HttpContext.User` in the `InternalPostCreateContext` method, ASP.NET Core doesn't know that authentication has occurred. This prevents the use of a number of ASP.NET Core features. `Forbid`, for example. In the controller of an A.N C application running on Lambda, the `Forbid()` method won't by default correctly return a 403-class response. In A.N C, `ForbidResponse` needs to know what authentication method for which it's claiming that permissions were insufficient. Even though `HttpContext.User` is non-`null`, that's not enough, and `Forbid()` will fail when it gets [a few `ForbidAsync`s deep][]. Similarly, `HttpContext.GetTokenAsync` says "What token?", claims transformation never fires, &c.

I will work on integrating this into the library again, so you can see what an MR for this might look like. (or like you're the expert if the work is trivial to you please do take this away from me)

[a gist]: https://gist.github.com/chrisoverzero/50460f92cdbe457dd25f17e9660d1c93
[a few `ForbidAsync`s deep]: https://github.com/aspnet/AspNetCore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Authentication.Core/src/AuthenticationService.cs#L121

**Comment by ashishdhingra** [comment]
Hi @chrisoverzero,

Good morning.

I was going through the issue backlog and came across this one. Please let me know if this issue needs any attention or if this could be closed.

Thanks,
Ashish

**Comment by chrisoverzero** [comment]
This appears still to be the case, based on my reading of the source code. Once my company retreats from COVID fears enough for us to upgrade some frameworks, I will get a service onto .NET Core 3.1 in order to reproduce with the current version.
