### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=2.1.2.0

### ISSUE THREAD

**Issue by granttrevor** [aws/aws-lambda-dotnet#334]
We've started receiving the following error in a Lambda we have deployed that had been happily working up until yesterday.

We had not deployed a new version for sometime so nothing changed from our end.

The exception is being raised when services.AddMvc() is being called in Startup.

Has anything changed yesterday on the lambda side of things? 

An exception was thrown when the constructor for type 'XXXXXX.XXX.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=2.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.: FileNotFoundException
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)

**Comment by normj** [comment]
Version 2.1.4 of .NET Core has been rolling out through Lambda and although our testing showed this having no negative effects to existing functions the fact that your error messages calls out version 2.1.2 is suspicious.

Can you tell me what region you are deployed to? When you last did your deployment how was the package bundle created? Is it possible for you to include your csproj file into this issue?

**Comment by normj** [comment]
After doing a bit more research `Microsoft.VisualStudio.Web.CodeGeneration.Design` wasn't ever meant to be included as a **PackageReference** and instead a **DotNetCliToolReference**  in a .NET Core 2.0. In .NET Core 2.1 **DotNetCliToolReference** were replaced with global tools.

**Comment by granttrevor** [comment]
Thanks for the follow up @normj . The referrence to Microsoft.VisualStudio.Web.CodeGeneration.Design must have been a remnant from an early version of .NET core.

Great to see 2.1.4 is rolling out.
