### ISSUE TITLE
Unable to deploy serverless stacks using Bamboo

### ISSUE THREAD

**Issue by lrh0000** [aws/aws-lambda-dotnet#335]
I'm trying to implement CI/CD for our .net apps, however dotnet-lambda deploy-serverless fails from Bamboo agent. 

Error creating CloudFormation change set: 1 validation error detected:<Long presigned s3 URl of the cloudformation template here>at 'templateURL' failed to satisfy constraint: Member must have length less than or equal to 1024

What is a good way to avoid the presigned URL's and have dotnet lambda tool generate and use local template for cloudformation stacks? It can upload to s3 for backup, I just don't want to be forced to use template URL since this will be automated  deployment using Bamboo and the long security token strings are ruining the aws URL's during dotnet serverless deployment. 

I tried amazon.lambda.tools versions 2.0.0, 2.2.0, 3.0.1 all of them are forcing the bucket use and there is no documented way to specify local template path in the defaults json template.

**Comment by klaytaybai** [comment]
How long are your bucket paths?  I'm (a little) surprised the signing would make enough of a difference to bring you over this limit.   You may be able to make a work around by shortening the path to your template file.

**Comment by normj** [comment]
There isn't anything we can do in our tooling for this as it is a limitation of CloudFormation. I have let the CloudFormation team know the length restraint for the S3 presigned url is causing pain for users. I would recommend also posting on the AWS CloudFormation forums explaining how presigned urls based on session credentials creates URL that are too long for CloudFormation accept. Service teams are more likely to make changes when they here directly from users.

https://forums.aws.amazon.com/forum.jspa?forumID=92
