### ISSUE TITLE
How to invoke different types of event in the same lambda in c#

### ISSUE THREAD

**Issue by DafuSHI** [aws/aws-lambda-dotnet#337]
Hello,

Since all the event types are defined. How can I have several types of event for the same lambda written in c#?

**Comment by normj** [comment]
The common approach is to put all of your shared logic in a separate .NET function and then have to Lambda functions deployed with the separate .NET function and call that with whatever you needed from the typed class. There is no additional cost for having multiple functions.

If you really want to do this in one Lambda function then don't use a typed class and instead have your function take in a `System.IO.Stream` then read the JSON from it and decided what to do based on the JSON.

**Comment by normj** [comment]
Closing as I believe answered. Feel free to reopen if this didn't answer your question.
