### ISSUE TITLE
Alexa C# Templates in AWS SDK and Toolkit

### ISSUE THREAD

**Issue by jonnycouk** [aws/aws-lambda-dotnet#34]
Could you please add Alexa Skill blueprints in the new C# Lambda Project Blueprints in the AWS Toolkit. 

There are a few useful examples there already but I would love to be able to turn out Alexa Skills in C# as this is the future! ;)

**Comment by kylegalbraith** [comment]
Seems like the Alexa event would need to be added before creating that blueprint, is that correct? @normj

**Comment by normj** [comment]
Yes we would need an Alexa events package first.

**Comment by kylegalbraith** [comment]
@normj I would be happy to create a PR and add that events package. Can't seem to find a definition of what the model event is for Alexa, you happen to have a link to a definition? If not, I will just use my own Alexa skill and get the definition from that.

**Comment by normj** [comment]
I'll gladly take pull request for event types. I haven't look for the documentation on Alexa events yet. 

Here is an example pull request I took for adding a new event type.
https://github.com/aws/aws-lambda-dotnet/pull/29

**Comment by bjorg** [comment]
I've published an app using this Alexa .NET library from this repo:
https://github.com/timheuer/alexa-skills-dotnet

It works great!

**Comment by normj** [comment]
Closing since this is already implemented by `Alexa.NET` and there is no reason to create another library.
