### ISSUE TITLE
Is it possible to call AD PowerShell-based commands against MicrosoftAD Directory Service?

### ISSUE THREAD

**Issue by michael-crawford** [aws/aws-lambda-dotnet#341]
What I'm interested in doing, is from within a Lambda function - read a CSV file containing AD Group information, and create those groups in MicrosoftAD Directory.

Instead of having to a. create a separate EC2 Windows instance, b. Join this to that domain, c. Install AD Tools and d. run the commands from there.

Is this possible? If so, can someone post some code that would show how this could be done? I think many others might be interested. Examples I'm seeing on a quick browse seem to show how to control AWS via PowerShell, but not how to do what I'm asking. Creation of Users and Groups is not something that can be done via the Directory Service API currently.

**Comment by jdemate** [comment]
Not a great solution, but some of the AWS applications that are integrated with AWS Directory Service have APIs that do user management within the directory.  For example, here is a WorkMail API that can create groups within the hosted Active Directory domain.
https://docs.aws.amazon.com/workmail/latest/APIReference/API_CreateGroup.html

As far as I know WorkMail only charges you for the users with a mailbox.  So as long as you don't register users to WorkMail you should not incur additional costs.

**Comment by michael-crawford** [comment]
The advice from AWS Support, FWIW, is that while it may be technically possible to run PowerShell within a Lambda function to do these extra AD tasks, it's likely be be limited, buggy and just not the best way.

So, I'm currently 80% of the way through a new template that is meant to be a close equivalent to an existing template which builds a pair of Domain Controllers in two AZs, with cfn-init and PowerShell to setup subnets, zones, groups, users, DNS entries, etc. The new template creates a MicrosoftAD service and an associated Windows Instance, joins it to the domain, and will run the stuff AWS hasn't automated via the API on that Instance, again via cfn-init and PowerShell. Hopefully I can swap between these two as needed, that's the goal.

I've had to write a few Lambda-backed custom resources to automate this, as the current MicrosoftAD Type in CloudFormation is sorely lacking in functionality. In fact, there are things you can do in the GUI that aren't even possible in the API yet (guys! That's breaking what should be a cardinal rule - API first, then GUI on top, so we can automate everything in the GUI), such as setting up SSO with Console access. What I've added are specific Directory Alias, and ConditionalForwarder. Trying to also add LogSubscriber, but there seems to be a Node.js library version mismatch, so that API function doesn't work within Lambda. It seems we're not allowed to do certain things inside AD tools, like ConditionalForwarders, so PowerShell isn't an option there.

Making this work better deserves more CloudFormation team attention.

**Comment by FredSamuels** [comment]
I would Suggest Calling SSM from lambda to generate the results from the AD environment.

Please note that you need to change the account the SSM runs on as a service on the DC as default is system.

**Comment by ashishdhingra** [comment]
Hi @michael-crawford,

Good afternoon.

I was going through list of backlog issues and came across this one. Looks like you already have a solution for your problem. Please advise if we could close this issue.

Thanks,
Ashish
