### ISSUE TITLE
Support IDisposable for Function Handlers

### ISSUE THREAD

**Issue by nerdamigo** [aws/aws-lambda-dotnet#342]
Issue #131 already touched on this - but I'd like to suggest that while it discusses wanting to do cleanup after each _invocation_, there is also a use case for wanting to do cleanup _on closure_ of the execution environment.

For cleanup within the context of an execution, the suggested approach from normj works well (just wrap the actual function handler's method body w/ a using statement, and have a custom class implement IDisposable.

However, if (for example) I wanted to Bootstrap a DI container in the constructor, and dispose of it when the execution environment "shuts down" the lack of support for IDisposable on the wrapping class becomes more apparent.

I considered using a destructor, but believe the shared contract of IDisposable is a better solution overall.

**Comment by normj** [comment]
If you are wanting for code to be called when the Lambda service reclaims the execution environment there is no service hook for that to happen. When the Lambda service detects a frozen execution environment that hasn't been used in awhile it deletes the execution environment regardless of what is inside the execution environment.

**Comment by nerdamigo** [comment]
Well that's too bad - was there a design decision for the Lamda environment that precludes it from offering such a service hook?

**Comment by normj** [comment]
Closing as there isn't anything more we can do from the .NET side. There would need to be a service behavior change for us to do anything more. For general Lambda comments I would suggest adding post to the Lambda forum where members of the Lambda team will see it. https://forums.aws.amazon.com/forum.jspa?forumID=186
