### ISSUE TITLE
Outdated dependencies 

### ISSUE THREAD

**Issue by firatsarlar** [aws/aws-lambda-dotnet#343]
I was trying to use one my projects with a lamda func. but failed with NewtonSoft version conflict messages  .( Current version 11.2, in lib. it is 9 ).
I tried to build by cloning this repo, but this time I couldn't upgrade netstandart version. 
Any suggestions..

**Comment by normj** [comment]
You should be able to update the version of Newtonsoft in your Lambda function to any version you want. Any chance you can create a repo case for me to take a look at?

**Comment by firatsarlar** [comment]
I'm actually very new to lamda, and also dotnet core, manually managing deps. 
I'll try to replace dll with newer in publish dir and try again. If it fail I'll create a simle repo to reproduce issue.

**Comment by firatsarlar** [comment]
I'm sorry, I tested again ( this time publish directly from vs 2017 ) and it worked.
In my previous attempt I was trying to publish from dotnet lambda publish ...
