### ISSUE TITLE
Can NodeServices and .NET Core 2.1 co-exist in Lambda environment?

### ISSUE THREAD

**Issue by raban33** [aws/aws-lambda-dotnet#344]
Any plans to support https://github.com/aspnet/JavaScriptServices using .NET Core 2.1 runtime. Can a AWS Lambda container have both .NET Core and nodejs runtime co-exist?

**Comment by Kralizek** [comment]
Follow up question, will it be possible sometime in the future to provide a custom-made image for the lambda environment?

**Comment by vellozzi** [comment]
You can package any files you want in your Lambda function deployment package, and use the C# Process class to start other processes.  It may be possible to accomplish it by doing that.

But no, we don't have any plans to support https://github.com/aspnet/JavaScriptServices .

I'm not sure exactly what the AWS Lambda team is planning.  You should contact them and let them know that's something you'd like them to add.
