### ISSUE TITLE
Will AspNetCore 2.2 be supported?

### ISSUE THREAD

**Issue by ckuetbach** [aws/aws-lambda-dotnet#345]
It seems, as if AspNetCore 2.2 is about to be released. Is there a plan to support this version?

**Comment by normj** [comment]
2.2 will not be an LTS and we do not plan on supporting it following Lambda practice of supporting LTS versions of language runtimes. We made the exception for .NET Core 2.0 since the feature set was so compelling over the previous 1.0 runtime.
