### ISSUE TITLE
PowerShell - New-S3Bucket:  Improve error message and cmdlet help info for bucket naming restrictions

### ISSUE THREAD

**Issue by pauby** [aws/aws-lambda-dotnet#347]
When executing the following command: `New-S3Bucket -BucketName SomeLogs` the following error is issued:

```
New-S3Bucket : One or more errors occurred. (The specified bucket is not valid.)
At line:1 char:1
+ New-S3Bucket -BucketName 'SomeLogs'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Amazon.PowerShe...wS3BucketCmdlet:NewS3BucketCmdlet) [New-S3Bucket], AggregateException
+ FullyQualifiedErrorId : Failed to create the specified bucket.
Amazon S3 error: One or more errors occurred. (The specified bucket is not valid.),Amazon.PowerShell.Cmdlets.S3.NewS3BucketCmdlet

New-S3Bucket : One or more errors occurred. (The specified bucket is not valid.)
At line:1 char:1
+ New-S3Bucket -BucketName 'SomeLogs'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Amazon.PowerShe...wS3BucketCmdlet:NewS3BucketCmdlet) [New-S3Bucket], InvalidOperationException
+ FullyQualifiedErrorId : System.AggregateException,Amazon.PowerShell.Cmdlets.S3.NewS3BucketCmdlet
```

Executing `New-S3Bucket -BucketName somelogs` creates the bucket as normal.

The case of the `BucketName` parameter should be handled within the function itself either to convert it to lower case and pass onto AWS to create the bucket (preferred), or an error thrown with a helpful error message advising that the bucket case is important AND update the cmdlet help to say this.

**Comment by klaytaybai** [comment]
Hi @pauby, thank you for your feedback.  The error is by design, but we will consider changing the error message and help information.

Please check out the following for more info:
[Bucket Restrictions documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)

**Comment by pauby** [comment]
@klaytaybai Thanks for your response. I am a little dismayed though that this is by design. It caused me quite a lot of time to work out why this Cmdlet was not working correctly. The error message that is produced is misleading. I appreciate it is likely the output of the API call however.

So there needs to be a bit of work to either update the help and error message or (preferred) convert the name and let the user know (which makes most sense) or the error. Preferably all three.

At the end of the day the user experience is very important. Something as simple as that would really help.

**Comment by klaytaybai** [comment]
@pauby, the help and error messages could change, but I think it is unlikely that we will convert the name.  I can bring this up with the team, but it might be misleading for customers if we change their mixed-case inputs to lower-case.  It could be especially problematic if customers are relying on knowing their bucket names programmatically.  

in case you didn't see it, here is an excerpt from the documentation I linked to:
> Legacy Non–DNS-Compliant Bucket Names
> Beginning on March 1, 2018, we updated our naming conventions for S3 buckets in the US East (N. Virginia) Region to require DNS-compliant names.
> 
> The US East (N. Virginia) Region previously allowed more relaxed standards for bucket naming, which could have resulted in a bucket name that is not DNS-compliant. For example, MyAWSbucket was a valid bucket name, even though it contains uppercase letters. If you try to access this bucket by using a virtual-hosted–style request (http://MyAWSbucket.s3.amazonaws.com/yourobject), the URL resolves to the bucket myawsbucket and not the bucket MyAWSbucket. In response, Amazon S3 returns a "bucket not found" error. For more information about virtual-hosted–style access to your buckets, see Virtual Hosting of Buckets.
> 
> The legacy rules for bucket names in the US East (N. Virginia) Region allowed bucket names to be as long as 255 characters, and bucket names could contain any combination of uppercase letters, lowercase letters, numbers, periods (.), hyphens (-), and underscores (_).
> 
> The name of the bucket used for Amazon S3 Transfer Acceleration must be DNS-compliant and must not contain periods ("."). For more information about transfer acceleration, see Amazon S3 Transfer Acceleration.

**Comment by ashishdhingra** [comment]
Hi @pauby,

Good evening.

I was going through backlog and came across this issue. The specified error is returned by the service operation and the PowerShell CmdLet simply returns the error to the caller. I'm not sure if we can emit specific error messages for each exception. [Bucket Restrictions documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) has details/link for the naming restrictions.

Kindly let us know if this issue could be closed in case no action is required.

Thanks,
Ashish

**Comment by pauby** [comment]
@ashishdhingra Thanks for the response.

There are two issues here and only one has been addressed:

1. Enforce the 'restrictions' for the S3 bucket at the PowerShell level;
1. Output better errors;

The second one has been addressed and while I don't like it, I understand why it is what it  is.

The first one hasn't been addressed. The PowerShell cmdlet can be more helpful by checking the case, and throwing an error. At the very least the help should be updated. If the purpose of providing the PowerShell cmdlets is simply to wrap around the API's and nothing else I think you are doing the PowerShell community and AWS a disservice.

**Comment by ashishdhingra** [comment]
> @ashishdhingra Thanks for the response.
> 
> There are two issues here and only one has been addressed:
> 
> 1. Enforce the 'restrictions' for the S3 bucket at the PowerShell level;
> 2. Output better errors;
> 
> The second one has been addressed and while I don't like it, I understand why it is what it is.
> 
> The first one hasn't been addressed. The PowerShell cmdlet can be more helpful by checking the case, and throwing an error. At the very least the help should be updated. If the purpose of providing the PowerShell cmdlets is simply to wrap around the API's and nothing else I think you are doing the PowerShell community and AWS a disservice.

@pauby Thanks for your response. Please advise if adding link to bucket naming restriction page in `New-S3Bucket` API documentation helpful.
