### ISSUE TITLE
Powershell- Publish-AWSPowerShellLambda fails silently when when trying to publish lambda using a script kept from a network drive. Half-baked lambda function gets published which fails to load dependencies.

### ISSUE THREAD

**Issue by tkushagr** [aws/aws-lambda-dotnet#349]
Publishing and testing the script from local drive works. However when trying to test the function published via PS cmdlet by using the same script file 
which is kept on a network drive via Publish-AWSPowerShellLambda cmd, the following error gets shown. 
Command:
eg: Publish-AWSPowerShellLambda -ScriptPath \\SharedDrive\Scripts\SampleScript.ps1 -Name  psfuncnetworkdrive -Region us-east-1 

Error Received: 
[Error] - The specified module 'AWSPowerShell.NetCore' was not loaded because no valid module file was found in any module directory.

Steps to Reproduce:
1.	I made a new folder or my D drive and shared it as a network resource so that my folder would be available through network via path eg: \\IP-XXXXX\Shared. Made the file available as : \\IP-CXXXXX\Shared\Scripts\SampleCase.PS1 
2.	Made sure to load AWSPowerShell, AWSLambdaPSCore and  AWSPowerShell.NetCore
3.	I made \\IP-XXXXX\Shared\Scripts as my current directory and published the function using following command:
PS Microsoft.PowerShell.Core\FileSystem::\\IP-XXXXX\Shared\Scripts>  Publish-AWSPowerShellLambda -ScriptPath SampleCasePS.ps1 -Name  psfuncnetworkdrive -Region {region}
4.	After publishing, tested this function and got the error shown below:
[Error] - The specified module 'AWSPowerShell.NetCore' was not loaded because no valid module file was found in any module directory. 

*IMPORTANT* : I understand that publishing a lambda through the network drive might not be a supported functionality but the publish should fail
 with a proper error message given to the end user in this case. The current implementation shows no error on PS cmdlet while doing a publish and the error
is made visible only at the time of testing the function. There should have been an error shown on publishing the event notifying the user about the missing modules.

**Comment by tkushagr** [comment]
Thanks for acknowledging. When can we expect this to be fixed? An estimate would be great.

**Comment by austoonz** [comment]
tkushagr@: I'm unable to replicate this issue. I used the sample code below, with the only change being I added "$LambdaInput" to the end of the script so it would return my input. For me, the Lambda Function executed correctly.

```
PS>cd \\server\share\folder
PS>New-AWSPowerShellLambda -Template Basic -ScriptName NetworkDriveSample
PS>cd NetworkDriveSample

# Modify the script, adding $LambdaInput on the last line

PS>Publish-AWSPowerShellLambda -ScriptPath .\NetworkDriveSample.ps1 -Name networktest -Region us-west-2

# Use the Convert module to help convert the response payload:
PS>(Invoke-LMFunction -FunctionName networktest -Region us-west-2 -Payload '{"test":"input"}').payload | ConvertTo-String
{
  "test": "input"
}
```

I see that you also imported the AWSPowerShell module. That isn't required and might be causing issues in your PowerShell session as it isn't compatible with PowerShell Core.

Can you confirm whether you're still seeing this issue?

**Comment by tkushagr** [comment]
austoonz@ : Apologies for the delay in response, I some how missed the communication. I can still reproduce the issue with the test script without importing AWSPowershell module. Here are the steps I followed:

1.	I made a new folder or my D drive and shared it as a network resource so that my folder would be available through network via path eg: \\IP-C613XXX\Shared. Made the file available as : \\IP-C613XXX\Shared\Scripts\sample.PS1 
2.	Ran : Import-Module AWSLambdaPSCore
3.	I made \\IP-C613BDAC\Shared\Scripts as my current directory and published the function using following command:
PS Microsoft.PowerShell.Core\FileSystem::\\IP-C61XXX\Shared\Scripts>  Publish-AWSPowerShellLambda -ScriptPath sample.ps1  -Name  retestpsfunction -Region ap-southeast-2
4.	On publish tested this function and got the same error[1] as the customer reported that AWSPowerShell.NetCore module failed to load:
START RequestId: 517a8f31-c1ee-4f10-b161-7ef3780c2c31 Version: $LATEST
[Error] - The specified module 'AWSPowerShell.NetCore' was not loaded because no valid module file was found in any module director

The current implementation shows no error on PS cmdlet while doing a publish and the error is made visible only at the time of testing the function. There should have been an error shown on publishing the event notifying the user about the missing modules. 

Workaround:

If I use the network shared folder as a mapped drive through PS using the command: net use Y: "\\IP-C613XXX\Shared" and then set the current location of PS to the mapped drive folder where the file exists using the following commands:
	Set-Location Y: 
	cd .\Scripts\ 
And then execute the publish from there:

PS Y:\Scripts> Publish-AWSPowerShellLambda -ScriptPath sample.ps1 -Name  retestpsfunctionredrive -Region ap-southeast-2

On publishing this function and testing it, the function behaves same way as the local function behaved and thus is able to load AWSPowerShell.NetCore module without throwing any errors as shown below:



References:
[1] - START RequestId: 517a8f31-c1ee-4f10-b161-7ef3780c2c31 Version: $LATEST
[Error] - The specified module 'AWSPowerShell.NetCore' was not loaded because no valid module file was found in any module directory.
[Error] - The term 'Get-CWAlarm' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[Error] - The term 'get-ec2instance' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[Error] - Cannot bind argument to parameter 'DifferenceObject' because it is null.
Cannot bind argument to parameter 'DifferenceObject' because it is null.: ParentContainsErrorRecordException
   at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost.ExecuteFunction(Stream inputStream, ILambdaContext context)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
END RequestId: 517a8f31-c1ee-4f10-b161-7ef3780c2c31
REPORT RequestId: 517a8f31-c1ee-4f10-b161-7ef3780c2c31	Duration: 7576.74 ms	Billed Duration: 7600 ms 	Memory Size: 512 MB	Max Memory Used: 124 MB

**Comment by mtboren** [comment]
Hey, @austoonz -- I think the important thing in that attempt to reproduce this issue is:
- the code package for the Lambda function that you made (from the NetworkDriveSample template) would be missing the required PS module `AWSPowerShell.NetCore`

Running the resulting Lambda function, as you pointed out, would appear to work, but that is because the handler script (NetworkDriveSample.ps1) does not actually _use_ anything from said `AWSPowerShell.NetCore` (so, there is no failure in the Lambda invocation, as there is no cmdlet invoked from the `AWSPowerShell.NetCore` in the Lambda code).

Do you notice the lack of the "Modules\AWSPowerShell.NetCore" folder in the code package for the Lambda that you generated in the reproduction experiment?  _That_ absence of modules required by the handler PowerShell script is the essence of this issue, as I understand it.

And, to try to expound on the problem (and not clutter the dialog in this Issue), I opened Issue #484 with more detail.
