### ISSUE TITLE
LexEvent.CurrentIntent.SlotDetails Missing OriginalValue

### ISSUE THREAD

**Issue by EpaSafelite** [aws/aws-lambda-dotnet#353]
Is LexEvent.CurrentIntent.SlotDetails.OriginalValue something that's coming soon on .NET SDK?

**Comment by ashishdhingra** [comment]
https://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html

**Comment by ashishdhingra** [comment]
Addition of new property `OriginalValue` to [SlotDetail](https://github.com/aws/aws-lambda-dotnet/blob/20046865db2afd3cf57b1d92d492f1fb4ec08a9d/Libraries/src/Amazon.Lambda.LexEvents/LexEvent.cs#L152).

**Comment by ashishdhingra** [comment]
Fixed in [Amazon.Lambda.LexEvents 3.0.0](https://www.nuget.org/packages/Amazon.Lambda.LexEvents/3.0.0)
