### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer How to deal with configurations

### ISSUE THREAD

**Issue by paparent** [aws/aws-lambda-dotnet#354]
Hi,

I'm moving a projet from using one handler per api gateway endpoint to using the Amazon.Lambda.AspNetCoreServer package (From AWS Toolkit for Visual Studio).

I'm trying to understand how to get started. To be noted: I'm kinda new to ASP.Net Core Api so ! 

How to deal about configuration ? the configuration is done there: https://github.com/aws/aws-lambda-dotnet/blob/fd13087d3628b3ab66a3f2eff14bfe9d91b7e3f7/Libraries/src/Amazon.Lambda.AspNetCoreServer/APIGatewayProxyFunction.cs#L181

And the files (appsettings.json and appsettings.development.json) are set to Not Copy (at least in the template provided by AWS Toolkit)

Why configuration isn't set more globally? So the LocalEntryPoint can use those config too ?

**Comment by klaytaybai** [comment]
Hi @paparent, your startup has that static Configuration, which should allow you to access it from the LocalEntryPoint.cs file.

Take a look at this [documentation](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config.html) for more info
