### ISSUE TITLE
AWSPowerShell.NetCore 3.3.428.0 | "Aggregate Exception, Task was canceled"

### ISSUE THREAD

**Issue by CloudViking86** [aws/aws-lambda-dotnet#369]
Hi,

Just got started with Lambda so I might overlook something really basic here, in that case I'm sorry to waste your time, normally used to writing scripts in PowerShell running on hosts.
Checked with my colleagues who have Lambda experience albeit not with PS Core and they couldn't find anything wrong in my setup and I've scaled back my code to just try a single command and still get the following error:

`{
  "errorType": "InvalidOperationException",
  "errorMessage": "One or more errors occurred. (A task was canceled.)",
  "stackTrace": [
    "at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost.ExecuteFunction(Stream inputStream, ILambdaContext context)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ],
  "cause": {
    "errorType": "AggregateException",
    "errorMessage": "One or more errors occurred. (A task was canceled.)",
    "stackTrace": [
      "at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)",
      "at Amazon.PowerShell.Cmdlets.SSM.SendSSMCommandCmdlet.CallAWSServiceOperation(IAmazonSimpleSystemsManagement client, SendCommandRequest request)",
      "at Amazon.PowerShell.Cmdlets.SSM.SendSSMCommandCmdlet.Execute(ExecutorContext context)"
    ],
    "cause": {
      "errorType": "TaskCanceledException",
      "errorMessage": "A task was canceled."
    },
    "causes": [
      {
        "errorType": "TaskCanceledException",
        "errorMessage": "A task was canceled."
      }
    ]
  }
}`

Context:
Trying to create a Lambda that is invoked by an SNS-topic when a service goes from "Running" to "Stopped" on host A and then verifying it is actually stopped and starting it on host B (the service can only be started on one server at the time and can't run concurrently on both).

The actual script:
Just dialed everything way back and tried sending a single "Send-SSMCommand" to check the service status on host A:

`$sendssmcommand = Send-SSMCommand -DocumentName "AWS-RunPowerShellScript" -Parameter @{commands = "Get-Service -Name myService| Select-Object -ExpandProperty Status"} -Target @{Key="instanceids";Values=@("i-myInstanceId")}
`

Further info:
This does work locally in Visual Studio when executing the code and I can see that the command was sent to SSM and was successfully received and executed by the host and the reply (i.e. "Stopped").

I can't see that any commands where sent by the Lambda which is quite expected since the task was canceled.

Tried adding an IAM-role that has full permissions on everything to rule out IAM-issues when I executed my full code and not just this snippet and got that the task timed out.
The current IAM-role attached to the Lambda gives full access to SSM (i.e. SSM:*) but the only thing needed should be (ssm:SendCommand).

Thanks for your assistance / Karl

**Comment by klaytaybai** [comment]
Hi @CloudViking86, are you by any chance using a VPC for your hosts?  If you are, is your Lambda able to access it?

**Comment by CloudViking86** [comment]
> Hi @CloudViking86, are you by any chance using a VPC for your hosts? If you are, is your Lambda able to access it?

Thanks for your reply.
Yes it is using a VPC and I used the AWS "AWSLambdaVPCAccessExecutionRole" as a template and appended it with "ssm:SendCommand" and later "ssm:*". I  just now tried giving it "ec2:*" but I still get the same error. I also tried giving it complete access to everything to rule out the problem being IAM-permissions (albeit that was when I tried my full code) and even with access to everything it still failed.

**Comment by CloudViking86** [comment]
Got it solved, a colleague helped me out.
The subnet the Lambda was assigned to does not automatically assign public IPv4 addresses and since SSM is public it wasn't able to reach SSM and timed out. Remove the Lambda from the VPC and it worked instantly!

Thanks for your answer :)
