### ISSUE TITLE
Error listing Lambda functions: The operation was canceled.

### ISSUE THREAD

**Issue by giomaik** [aws/aws-lambda-dotnet#370]
Hello,

I'm running the following powershell script to get SAML credentials and use them to run dotnet lambda commands

```
Import-Module "C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.psd1"
$endpoint = "https://my-domain/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices"
$epName = Set-AWSSamlEndpoint -Endpoint $endpoint -StoreAs ADFS-Demo -AuthenticationType NTLM
$user = "domain\user"
$pword = ConvertTo-SecureString -String "notmypassword" -AsPlainText -Force
$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $user, $pword
Set-AWSSamlRoleProfile -EndpointName $epName -NetworkCredential $credential -StoreAs SAMLDemoProfile

dotnet lambda list-functions --profile SAMLDemoProfile --region eu-west-1
```

But when I execute that I get  `Error listing Lambda functions: The operation was canceled.`
I'm a bit confused as to what is happening here. Authentication seems to have worked OK and the error messages is rather cryptic. Any ideas please?

Thanks

**Comment by ashishdhingra** [comment]
Hi @giomaik, 

Good evening.

I was going through the list of backlog issues and came across this guidance question. Could you please share which file gets updates when you execute `Set-AWSSamlRoleProfile` command - Is it **.aws/credentials** or **.aws/config**?

If this is no longer an issue, please confirm if it could be closed.

Thanks,
Ashish
