### ISSUE TITLE
C# Lambda and FarGate

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#373]
I have several Lambda functions that need to run for longer than 5 minutes so it appears that I should be using AWS FarGate if I want the convenience of serverless.

Does anyone have any documentation on how to package C# DotNet Core for AWS FarGate?

Thank in advance.

**Comment by normj** [comment]
To run in Fargate you just need to create a docker image. There is no special packaging for Fargate other then the docker image.

Also, if you didn't hear you can run Lambda functions now for 15 minutes.

**Comment by genifycom** [comment]
Can you add a note to update the AWS Toolkit Advanced Function Details dialog for Timeout (currently 1-300) and make it 1-900

Thank you
