### ISSUE TITLE
Update to Asp.Net

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-lambda-dotnet#374]
Any idea of when this might be bumping up to a newer version AspNet Core?  Specifically to advance to a newer version EF Core...

**Comment by vellozzi** [comment]
You can always see what version we're supporting, and what's in progress here:
https://github.com/aws/aws-lambda-dotnet/blob/master/README.md

We can't comment on specific timelines.  But that README shows what's going on.

Hope that helps.
