### ISSUE TITLE
SNSMessage.SigningCertUrl is misspelled and incompatible with AWS SDK for .NET V3

### ISSUE THREAD

**Issue by dan-arnold** [aws/aws-lambda-dotnet#376]
I'm using `Amazon.Lambda.SNSEvent` and `Amazon.SimpleNotificationService.Util.Message` (from the .NET AWSSDK) in a .NET Core Lambda solution. The `SigningCertUrl` field is misspelled in the SNSMessage model. In the .NET SDK it is spelled `SigningCertURL` (see [Message.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs)), but in this project it is spelled `SigningCertUrl` in the `SNSMessage` class.

This causes the Message class to fail when ingesting a message produced by this library.

To reproduce:

Create a new .NET Core project. Reference Amazon.Lambda.SNSEvents and AWSSDK.SimpleNotificationService.

```
var message = new SNSEvent
  {
    SigningCertUrl = "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-myguid.pem"
  };
Message.ParseMessage(message);

/* The above line throws:
System.ArgumentNullException: Value cannot be null
Parameter name: uriString
at System.Uri..ctor(String uriString)
at Amazon.SimpleNotificationService.Util.Message.ValidateCertUrl(String certUrl)
at Amazon.SimpleNotificationService.Util.Message.ParseMessage(String messageText)
*/
```

The two referenced files are linked below, one can see the discrepency in master on both repos:
* https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs
* https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.SNSEvents/SNSEvent.cs

**Comment by normj** [comment]
Thanks for bring this to our attention. I'm working on an SDK fix to make it case insensitive when its parsing the JSON.

**Comment by normj** [comment]
Version 3.3.3.18 of AWSSDK.SimpleNotificationService went out yesterday with this fix.
