### ISSUE TITLE
Problem with instance profile AWS credentials

### ISSUE THREAD

**Issue by jnyborg** [aws/aws-lambda-dotnet#38]
Hello,

My team are trying to set up CI for a MVC dotnet core application, where the CI agent runs on an EC2 instance. Since that instance already have access to AWS, we hoped that dotnet lambda deploy-serverless would use instance profile credentials instead of environment variables/default credentials file.(https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html.)

But when we try that, we get the following error:
```
Uploading to S3. (Bucket: <bucket-name> Key: <file>.zip)
... Progress: 12%
... Progress: 15%
... Progress: 22%
... Progress: 25%
... Progress: 31%
... Progress: 34%
... Progress: 41%
... Progress: 44%
... Progress: 50%
... Progress: 60%
... Progress: 72%
... Progress: 75%
... Progress: 82%
... Progress: 85%
... Progress: 91%
... Progress: 94%
... Progress: 100%
Uploading to S3. (Bucket: <bucket name> Key: <name>-serverless-636208434060831440.template)
... Progress: 100%
Found existing stack: True
Error creating CloudFormation change set: 1 validation error detected: Value '<very long url, with security token headers>' at 'templateURL' failed to satisfy constraint: Member must have length less than or equal to 1024
```

Setting .aws/credentials and a profile in defaults.json fixes this problem, so I would think the issue has something to do with relying on instance profile credentials.

Are instance profile credentials supported (and I'm doing something wrong), or will they be in the future? :)

**Comment by normj** [comment]
I was able to use instance profile and execute `dotnet lambda deploy-serverless` with no problems. Using credentials from the instance profile does mean the session token gets added to the the presigned url created to the template for the change set. Session token is a pretty large string but in my testing the presigned URL was about 500 characters well below CloudFormation 1024 max length. Are you using really long names for your S3 bucket or is the value for s3-prefix in aws-lambda-tools-defaults.json really long?

**Comment by jnyborg** [comment]
Thanks for the response. Our S3 name is 21 characters long, which should be reasonable. We had not set the s3-prefix in the -defaults.json, setting it to a short value did not help either.

It looks like the x-amz-security-token header it builds on the templateURL is the biggest sinner - it is 684 characters long in our case. The total length our templateURL is 1077, so I don't think we can reduce the size of S3 name and prefix enough and also have reasonable naming.

Here are some more details on the templateURL we get, if it could help:
```
Error creating CloudFormation change set: 1 validation error detected: Value '
<112 chars url to s3 bucket>
?X-Amz-Expires=3600
&x-amz-security-token=<684 characters long>
&X-Amz-Algorithm=AWS4-HMAC-SHA256
&X-Amz-Credential=<55 chars long>
&X-Amz-Date=20170131T093406Z
&X-Amz-SignedHeaders=host;x-amz-security-token
&X-Amz-Signature=<64 chars long>
```

**Comment by normj** [comment]
Interesting. I have reached out to the CloudFormation team for guidance on long session tokens.

**Comment by normj** [comment]
I pushed version `1.2.0-preview1` of `Amazon.Lambda.Tools` that reworks how `serverless.template` is uploaded. Basically if the template is less then 50,000 bytes it is directly uploaded to CloudFormation avoiding the need for the presigned URL that is causing trouble.

**Comment by jnyborg** [comment]
Awesome! That fixed my issue. Thanks!

**Comment by normj** [comment]
Great!
