### ISSUE TITLE
Documentation Request for Publish-AWSPowerShellLambda

### ISSUE THREAD

**Issue by FredSamuels** [aws/aws-lambda-dotnet#383]
Please update the documentation for the formatting of the hashtable for EnvironmentVariable.

Thank you,

Fred

**Comment by normj** [comment]
Not sure what formatting you mean. The key/value pairs in the Hashtable for the EnvironmentVariable property are applied to the Lambda function. There is no special formatting.

**Comment by FredSamuels** [comment]
When using the "Publish-AWSPowerShellLambda" CmdLet, there is a param -EnvironmentVariable <Hashtable>.

I tried several structures for the has table.. but has issue. I am sure it is just my input of the has table wrong... but figuring i did not see this as a clear how to.. I was suggesting the example of the EnvironmentVariable be added to the examples in you CmdLet. Clearly the use is below but for those still new to PowerShell i was just suggesting an example. 

`
$LambdaData = @{
    Name = 'Lambda-Function-Name'
    ScriptPath = '.\Lambda-Function-Name\Lambda-Function-Name.ps1'
    Region = 'us-east-1'
    IAMRoleArn = 'lambda-assumerole'
    Timeout = 900
    EnvironmentVariable = @{'EnvironmentVariableName' = 'Data','EnvironmentVariableName2'='Data2'}
}

Publish-AWSPowerShellLambda @LambdaData
`

**Comment by FredSamuels** [comment]
clearly this is not what I was asking so clearly I will open a support case ..

**Comment by normj** [comment]
Sorry if I misunderstood something. The added cmdlet example shows how to set environment variables

```
Publish-AWSPowerShellLambda -Name SampleLambda -ScriptPath sample-lambda.ps1 -EnvironmentVariable @{'TABLE_NAME'='MyDynamoDBTable'}
```

Were you looking for an example for a powershell splat?

**Comment by normj** [comment]
@FredSamuels Did you have any more feedback on this issue?

**Comment by FredSamuels** [comment]
I would be happy to help with what I am asking.. I have been working with the SSM architecture team for resolution on these asks.
