### ISSUE TITLE
asp.net core mvc index path does not work when deployed to lambda

### ISSUE THREAD

**Issue by girishnuli** [aws/aws-lambda-dotnet#384]
Uploading an asp.net core mvc project in a lambda function does not allow access to the index path /.

I am basically using this example https://aws.amazon.com/blogs/developer/serverless-asp-net-core-2-0-applications/, but on MacOS with VS code using below steps

Steps to reproduce:
1. Create a new asp.net core 2.1 mvc project using $ dotnet new mvc
2. Add LambdaEntryPoint.cs as shown in above link
3. Setup serverless framework using below configuration:

service: lambdamvctest

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-1
  memorySize: 256
  timeout: 10
  stage: prod
  profile: profilename

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: lambdamvc::lambdamvc.LambdaEntryPoint::FunctionHandlerAsync
    events:
      - http:
          path: /{proxy+}
          method: ANY

Deploy to AWS lambda using $ sls deploy

Testing:
After deploying, I got this url (it is live, you can try it):
https://1nipksexx8.execute-api.us-east-1.amazonaws.com/prod

Accessing the above url gives this error:
{
"message": "Missing Authentication Token"
}

However, we can access all routes using the controller and action name. This works:
https://1nipksexx8.execute-api.us-east-1.amazonaws.com/prod/home/index

I am not sure why this is happening. Is this a lambda issue or have I missed some configuration? Any help is appreciated since this has become a showstopper from using lambda for a project. Thanks.

**Comment by normj** [comment]
To cover the root "/" as well you need to add an extra route in the event section where path is set to just "/" without the {proxy+}.

If you look at our blueprints you can see how in the template we add the two routes to the serverless function.
https://github.com/aws/aws-lambda-dotnet/blob/8160398e9e167cf66c67f467540fa9ebbb60a34a/Blueprints/BlueprintDefinitions/Msbuild-NETCore_2_1/AspNetCoreWebApp/template/src/BlueprintBaseName.1/serverless.template#L28-L41

**Comment by girishnuli** [comment]
@normj Thanks for the quick response! Adding an event for / works perfectly fine.
