### ISSUE TITLE
Route parameters sends encoded value to controller

### ISSUE THREAD

**Issue by ThomasHjorslevFcn** [aws/aws-lambda-dotnet#386]
I have an action method with this signature:

    [Route( "/files/{*path}" )]
    [HttpGet]
    public async Task<ActionResult<BrowseResponse>> Browse( string path )

When I am invoking it locally (IIS Express/Kestrel) with `http://localhost:59252/files/tmh/file%20name.xml`, the value of `path` is `"tmh/file name.xml"`.
However, when invoking the URL `https://app.my-domain.com/files/tmh/file%20name.xml` the value of `path` is `"tmh/file%20name.xml"`.
I'm using `Amazon.Lambda.AspNetCoreServer` version `2.1.0`.

**Comment by justinhelgerson** [comment]
@ThomasHjorslevFcn I'm not sure that this is an AWS Lambda issue.  I'd recommend looking at https://github.com/aspnet/Mvc/issues/4599 and https://github.com/aspnet/AspNetCore/issues/2669.

**Comment by andymac4182** [comment]
Ideally this would work the same was as Kestrel which this appears to be different. Those issues @justinhelgerson appear related to how `/` is encoded not a space which is what is being referenced here.

**Comment by normj** [comment]
@ThomasHjorslevFcn you are correct they value should be the same regardless if the value came from API Gateway or Kestrel. I'm taking a look to see what is going wrong.

**Comment by normj** [comment]
I have checked in a fix in the dev branch to go out with the next release. https://github.com/aws/aws-lambda-dotnet/commit/37fa053f921fc85350dd5c2e384e6599ecb003ef

**Comment by normj** [comment]
Version 3.0.1 of the Amazon.Lambda.AspNetCoreServer has been released with this fixed shipped. Here is a blog post with more info about the new release. https://aws.amazon.com/blogs/developer/updates-for-serverless-asp-net-core/
