### ISSUE TITLE
How to package without 'global' tools

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-lambda-dotnet#387]
Right now I seem to be forced to checking in the `dotnet-lambda` tool into source control because I don't have access to install the tool globally. Preferably I would rather not check that in but I cannot for the life of me figure out how to use the new version.

**Comment by vellozzi** [comment]
Can you give the specific command line and error that happens when you use dotnet install, or tell us more about your situation?  It seems like you should be able to install it.

Have you tried the --tool-path switch from [this page](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)?

**Comment by andymac4182** [comment]
@phillip-haydon Are you able to use the `--tool-path` to install it "locally"?

**Comment by phillip-haydon** [comment]
Oh I didn’t know about the install path. I will try that tomorrow in teamcity and see if I can get it working.

**Comment by normj** [comment]
In the future .NET Core will make this a better experience. In the .NET Core 3.0 previews they already have the concept of local tools. https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/#user-content-local-dotnet-tools

**Comment by normj** [comment]
Closing as I think this is answered is much as we can now.

**Comment by phillip-haydon** [comment]
Sorry for no reply. Chinese New Year so I’m still on holiday and haven’t had time to properly test out the suggestion.

But I think being able to install to a folder will solve the issue of having to check in the tool.

Looking forward to the local tools from .net 3

Thanks!
