### ISSUE TITLE
Support for .Net Core 3.0

### ISSUE THREAD

**Issue by alsofo** [aws/aws-lambda-dotnet#390]
I know that the plan for AWS is to always use the Long Term Support version of Core. I believe for 3 this will be later than 3.0. In the mean time, will .net Core 3.0 get supported in Lambda?

**Comment by klaytaybai** [comment]
Hi @alsofo, thank you for your interest in updates to the .NET SDK.  As a policy, we can't make promises on possible major future work, but we do like to stay current with LTS versions.  Typically updates like this will get [announcements](https://aws.amazon.com/blogs/developer/category/programing-language/dot-net/).  You may also be interested in following this [feature request for Lambda Layers support for .NET Core](https://github.com/aws/aws-extensions-for-dotnet-cli/issues/58).

**Comment by vellozzi** [comment]
Check out this issue: https://github.com/aws/aws-lambda-dotnet/issues/405
