### ISSUE TITLE
AWS Layers and Powershell?

### ISSUE THREAD

**Issue by JustinGrote** [aws/aws-lambda-dotnet#393]
In relation to #319, and the announcement of AWS Layers, is this a potential option to make this simpler? Could the .NET Core Runtime be packaged as a layer, so that the actual Powershell script is far more lightweight and easier to iterate/test? That would be huge, uploading a 22MB file every revision is a major stop gap to rapid development compared to Azure Functions or Azure Automation.

Is there any potential guidance around this?

**Comment by klaytaybai** [comment]
Hi @JustinGrote, thank you for your interest in this!   Consider participating in this discussion about using .NET Core with Layers: https://github.com/aws/aws-extensions-for-dotnet-cli/issues/58

**Comment by burkasaurusrex** [comment]
Now that Layers have .Net Core support, any chance we could bring them Powershell? It would be awesome to be able to upload modules to layers and then have a `-Function-Layers` flag for the Publish-AWSPowerShellLambda cmdlet (similar to `dotnet lambda deploy-function --function-layers`).

**Comment by jgard** [comment]
10 months later, any update here?

**Comment by pcgeek86** [comment]
@normj any thoughts?

**Comment by sgnewman** [comment]
Bueller?  Would love for PS modules to be supported in layers.

**Comment by normj** [comment]
We haven't implemented anything yet for publishing PS modules as a Lambda Layer yet. There is some potentially interesting work we could do there but just haven't prioritized the work yet.

In theory you could zip up your dependent PS modules and publish that as a layer then in your PowerShell script to manually import the modules from the /opt folder that you zipped up in the layer. I haven't tired this but I don't see why it wouldn't work.
