### ISSUE TITLE
"Error deserializing the input JSON" on completely stock empty function template

### ISSUE THREAD

**Issue by NickSuperb** [aws/aws-lambda-dotnet#394]
Created an "Empty Function" new solution with VS2017 using AWS Toolkit templates. Making no changes to the generated solution I run the "Mock Lambda Test Tool" launch profile and select the "Hello World" example request.

```
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}
```

The resulting error is below... I'm having trouble trying to identify the root cause and solution.

```
System.Exception: Error deserializing the input JSON to type String
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.BuildParameters(ExecutionRequest request, ILambdaContext context) in E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 201
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.Execute(ExecutionRequest request) in E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 44
---------------- Inner 1 Exception ------------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.BuildParameters(ExecutionRequest request, ILambdaContext context) in E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 193
---------------- Inner 2 Exception ------------
Amazon.Lambda.Serialization.Json.JsonSerializerException: Error converting the Lambda event JSON payload to a string. JSON strings must be quoted, for example "Hello World" in order to be converted to a string: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
   at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)
---------------- Inner 3 Exception ------------
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Amazon.Lambda.Serialization.Json.JsonSerializer.Deserialize[T](Stream requestStream)
```

**Comment by vellozzi** [comment]
I'm guessing the first parameter of your function  handler is a ```string```
Lambda is looking for is a JSON string ```"string including quotes"``` not a JSON object ```{"prop":"value"}``` 

You should change the input for your test to be a JSON string or change the function to take an object. The object option is a little more involved.  You need to add a NuGet reference to 
```
Amazon.Lambda.Serialization.Json
``` 
and add 
```
[assembly: Amazon.Lambda.Core.LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
``` 
to your function's assembly.

**Comment by NickSuperb** [comment]
The test works quite well with either a string or a null input but that's not the problem here. The template as listed includes the elements that you're suggesting. It seems that even with the `LambdaSerializer ` specified there is still an issue.

https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/Msbuild-NETCore_2_1/EmptyFunction/template/src/BlueprintBaseName.1/Function.cs

**Comment by vellozzi** [comment]
If your code looks just like https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/Msbuild-NETCore_2_1/EmptyFunction/template/src/BlueprintBaseName.1/Function.cs then I think my advice still applies.

If that's the case your function won't accept ```{"Prop":"Value"}``` as input.
If you want to send ```{"prop":"value"}``` you have to define a class like:
```
class FunctionInput
{
    public string Prop { get; set; }
}
```
and your function signature should look like
```
public string FunctionHandler(FunctionInput input, ILambdaContext context)
```

Does that help, or is there something I'm still not seeing?

**Comment by NickSuperb** [comment]
Ok thanks, I think I see what you're getting at. I was expecting a raw string. Specifying an object like the below allows the "Hello World" test from the mock test tool to work properly...

```
public class InputTest
{
    public string Key1;
    public string Key2;
    public string Key3;
}
```

**Comment by vellozzi** [comment]
OK.  I'm glad that helped.

**Comment by Wizard2436829** [comment]
Hi Guys,

I am actually trying to use AWS connect with AWS Lambda and according to the official documentation: https://docs.aws.amazon.com/connect/latest/adminguide/connect-lambda-functions.html 

There is a specific JSON format in which connect makes a request to the lambda function.

I have already tried the C# object approach to bind the connect request with the lambda function.

My problem is that even after the request is generated by connect , it needs slight modification(Manually) and then when i test it with lambda its works fine.

I Actually need to feed that RAW JSON to the method and then deserialize it in my method and attach it with the object.

Does anyone have a clue how to go forward with the RAW JSON input to method parameter.

**Comment by klaytaybai** [comment]
@Wizard2436829, I think you should create a separate issue.

**Comment by RobKraft** [comment]
The AWS-SDK for Visual Studio 2019 creates the stub of FunctionHandler for you.  Unfortunately it is created incorrectly like this:
public string FunctionHandler(string input, ILambdaContext context)
change that to something like:
public object FunctionHandler(Stream input, ILambdaContext context)
and you should be able to get going.

**Comment by richardkeller411** [comment]
The Message Body has to be a string.   Just Stringy the Json.

https://onlinetexttools.com/json-stringify-text

**Comment by infiniteloopltd** [comment]
Came across the same issue. The Error appeared in the Mock Lambda test tool, but when deployed to AWS Lambda, it didn't appear. 

`        public string FunctionHandler(Stream input, ILambdaContext context)
        {
            var rawInput = new StreamReader(input).ReadToEnd();
            LambdaLogger.Log(rawInput);
            return "OK";
        }`
