### ISSUE TITLE
MultiValueHeader use breaks API Gateway redirection?

### ISSUE THREAD

**Issue by Sumo-MBryant** [aws/aws-lambda-dotnet#395]
Using the recently released version 3.0.0, I tested the functionality with my existing system and HTTP redirects no longer appear to work when using API Gateway Proxy.

I had tested the `alb-support-aspnetcore` branch recently and that appeared to work.

Below are some captured responses from the Lambda:

## Before:

```json
{
  "statusCode": 302,
  "headers": {
    "Location": "/ServiceHost/swagger",
    "Content-Type": null
  },
  "body": "",
  "isBase64Encoded": false
}
```

API Gateway returns a `location` header.

## After:

```json
{
  "statusCode": 302,
  "headers": {},
  "multiValueHeaders": {
    "Location": [
      "/ServiceHost/swagger"
    ],
    "Content-Type": []
  },
  "body": "",
  "isBase64Encoded": false
}
```

API Gateway doesn't return a `location` header.

## Workaround

I've worked around this so it isn't a major issue, and I'm happy to accept that this might be a bug in API Gateway and not AspNetCoreServer.

My workaround was to detect the 3XX status code, and move the `Location` header from the `MultiValueHeaders` to the `Headers` dictionary in the response.

**Comment by Rutgerz** [comment]
Can confirm we just spent hours chasing a bug which lead us to this exact cause. How exactly did you work around it?

**Comment by Sumo-MBryant** [comment]
I think you should be able to override the `FunctionHandlerAsync()` method of `APIGatewayProxyFunction` in your derived class.

```csharp
public override async Task<APIGatewayProxyResponse> FunctionHandlerAsync(APIGatewayProxyRequest request, ILambdaContext lambdaContext)
{
    var response = await base.FunctionHandlerAsync(request, lambdaContext);

    // Workaround for a bug (https://github.com/aws/aws-lambda-dotnet/issues/395)
    if (response.StatusCode >= 300 && response.StatusCode < 400)
    {
        response.Headers["Location"] = response.MultiValueHeaders["Location"].First();
        response.MultiValueHeaders = null;
    }

    return response;
}
```

*We* did something slightly different: we implemented our own entrypoint class with a custom implementation of `FunctionHandlerAsync()` which then called the `APIGatewayProxyFunction.FunctionHandlerAsync()` implementation. We did this to enable the same class to use API Gateway or Application Load Balancer.

**Comment by normj** [comment]
Sorry about the issue. I'll take a look. My suspicion is actually the content-type as an array is messing it up. With the single headers collection if content-type was not present API Gateway would default the content-type to application/json. So before I had code in the this library to set content-type explicitly to null of ASP.NET Core didn't return a content-type. I suspect I need to do something similar for the new multi value support. Redirection probably gets messed up when a content-type of application/json gets returned.

**Comment by normj** [comment]
I have confirmed it is the content-type. Adding the missing unit test cases and then I'll get the fix it.

**Comment by normj** [comment]
I just pushed version 3.0.1 of Amazon.Lambda.AspNetCoreServer package. Here is the commit if curious: https://github.com/aws/aws-lambda-dotnet/commit/79400f46119509bcca0cc07da9ce38cd36530ee4

Sorry again for the issue.

**Comment by Sumo-MBryant** [comment]
Thank you for the quick response!

I can confirm 3.0.1 fixes the issue for me.

**Comment by Rutgerz** [comment]
Thanks for the quick turnaround on this. We will update to the newer version this week 👍
