### ISSUE TITLE
"Mock Lambda Test Tool in launchsettings.json

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#397]
Because this is in launchsettings.json and because the executablePath contains the current users directory, when launchsettings.json gets  pushed to a git repository, it will mess up other users.

e.g. Normj will have in launchsettings.json
"executablePath": "C:\\Users\\NormJ\\.dotnet\\tools\\dotnet-lambda-test-tool-2.1.exe",

When he pushes his git repository to me, I will get this executablePath and will find that I cannot run the test tool.

**Comment by andersco** [comment]
I was just going to enter the same issue. I tried replacing the username part of it with %USERNAME% but it just gets replaced by my username when I reopen visual studio.

**Comment by normj** [comment]
Thanks for the suggestion of using %USERNAME% instead of updating the file when the project is opened. I'll need to update the AWS Toolkit for that change which is in the middle of work for VS 2019. Unless you folks tell me this is high priority it will probably get lumped into that work.

**Comment by stevieTheCoder** [comment]
Also running into this issue.  A linked issue for me is that I am overriding the workingDirectory property and this gets reset each time I re-open visual studio.

**Comment by normj** [comment]
I have made the fix in my internal branch of the VS toolkit to add support for VS 2019. (Sorry the toolkit isn't open sourced). The fix will also be in VS 2017. I also change the code to only set workingDirectory when the launchsettings.json file is first being written to for the Lambda test tool.

**Comment by stevieTheCoder** [comment]
Brilliant thank you

**Comment by andymac4182** [comment]
@normj 	Is there any chance the toolkit will be open sourced?

**Comment by genifycom** [comment]
Thanks Norm

**Comment by normj** [comment]
@andymac4182 I would like to get the toolkit open sourced but that is a decent amount of engineering effort I just haven't found the time for.

**Comment by genifycom** [comment]
Can we help you with that :-)

**Comment by wsalmi** [comment]
Please, replace

`"executablePath": "C:\\Users\\%USERNAME%\\.dotnet\\tools\\dotnet-lambda-test-tool-2.1.exe"`
to
`"executablePath": "%USERPROFILE%\\.dotnet\\tools\\dotnet-lambda-test-tool-2.1.exe"`

and enjoy forever!

**Comment by gavsm** [comment]
I second wsalmi's suggestion... %USERNAME% doesn't work correctly for me, I change it to %USERPROFILE% but it keeps changing back which if frustrating.

**Comment by jerhewet** [comment]
Riffing off of @wsalmi, please consider replacing the "workingDirectory" value as well.

From: "workingDirectory": ".\\bin\\Debug\\netcoreapp2.1"
To: "workingDirectory": ".\\bin\\$(Configuration)\\netcoreapp2.1"

**Comment by normj** [comment]
Version 1.16.0.0 of the AWS Toolkit of Visual Studio went out last week which will now use `%USERNAME%` for setting up the executablePath.

@jerhewet That is a good suggestion. I'll make that change to the toolkit.

**Comment by normj** [comment]
@jerhewet Version 0.10.0 went out today with your suggestion of using $(Configuration)
