### ISSUE TITLE
global.json SDK Version Specification

### ISSUE THREAD

**Issue by cbeall** [aws/aws-lambda-dotnet#4]
When you have dotnet build tools 1.0.0-preview3 installed (which installs automatically when you install Visual Studio 2017 RC), it changes the default behavior of `dotnet`. For machines with the latest tooling installed, an errors occurs when initially loading any of the lambda templates from Visual Studio 2015. To fix this problem, you need to manually add a global.json file and then run `dotnet restore` and all is well.

It is considered a best practice for all .NET Core projects to include a global.json that specifies an SDK version. It would be great if the new templates included global.json and explicitly specified 1.0.0-preview2-003131.

See "Side by side install" section below

https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/#dotnet-cli-tools

**Comment by normj** [comment]
I agree we should write the global.json file in the solution if it doesn't already exist in it. I'll take a look at updating our tooling to do that.

**Comment by normj** [comment]
I pushed out version 1.11.1 of the Visual Studio toolkit that now writes the global.json file when the project is created.
