### ISSUE TITLE
Open Source .NET Core Lambda Runtime

### ISSUE THREAD

**Issue by normj** [aws/aws-lambda-dotnet#405]
This issue is to track the effort in the [amazon-lambda-runtimesupport](https://github.com/aws/aws-lambda-dotnet/tree/amazon-lambda-runtimesupport) branch which introduces a new NuGet package called **Amazon.Lambda.RuntimeSupport** that can be used for user provided .NET Core runtimes to Lambda. Example usage of this is to publish .NET Core 2.2 or .NET Core 3.0 preview Lambda based functions.

**Comment by normj** [comment]
Current status is the library is going through CR. Additionally tooling is being worked on to support this. Initially plans is to have the [Amazon.Lambda.Tools](https://github.com/aws/aws-extensions-for-dotnet-cli#aws-lambda-amazonlambdatools) support .NET Core self contained deployment as the way to get the .NET Core runtime bits Lambda.

**Comment by andymac4182** [comment]
If I am reading this correctly we can use the Amazon.Lambda.RuntimeSupport nuget with the existing libraries and it will support self contained deployment?  I would love to be able to support .NET Core 3 Web App deployment behind an ALB.

**Comment by vellozzi** [comment]
Just released [Amazon.Lambda.RuntimeSupport](https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/)

**Comment by DeniseJames** [comment]
When will the update to the AWS Toolkit for Visual Studio?  Is there one for Visual Studio NET 2.1? A walkthrough?

**Comment by vellozzi** [comment]
Amazon.Lambda.RuntimeSupport isn't meant to be used for .NET Core 2.1 lambda functions.  For 2.1 you should use the built-in runtime.

It sounds like your question may be better as its own GitHub issue.  I'm not sure what you mean by the S3 proxy.  

Can you open a new issue and give some more detail?  Open it in this repo if it's Lambda-related, or in https://github.com/aws/aws-sdk-net if it's related to the .NET SDK.

**Comment by normj** [comment]
Closing as the feature has shipped

**Comment by DeniseJames** [comment]
Thanks vellozzi.  I will open my first issue.

**Comment by RoyiNamir** [comment]
@normj So now we can use 2.2 in our lambda when publishing?

But what about the Mock Lambda Test Tool ? in 2.1 projects all is ok.

But in 2.2 we get a bizarre error https://github.com/aws/aws-lambda-dotnet/issues/478
