### ISSUE TITLE
Memory leak in Lambda HTTPS request?

### ISSUE THREAD

**Issue by WyzeTao** [aws/aws-lambda-dotnet#406]
Hi, we have been fighting on an issue with increased latency on on of our Lambda code. The Lambda code consists of 2 HTTPS requests to our server and did nothing else. Before 1/23 10-ish the average Lambda finish time is about 1s. After 1/23 10am, the average finish time increased to ~7s. We changed nothing in our .NET code which makes it very weird. 

In our multi-day investigations we noticed the memory used for our Lambda gradually went up from ~50MB to ~100MB. Then there is a big drop (likely the docker got recycled). When memory was 50MB our response time was ~1s. When memory was 100MB our response time was ~7s. I attached on log file which demonstrates the long delay. For reference, our Lambda was requested as 384MB. We also tried to bump up the memory usage to 1024MB but the issues persisted. 

Our guess is that this was caused by an update from AWS side or .NET side. Can someone help us here? Thanks!

[high_latency_log.txt](https://github.com/aws/aws-lambda-dotnet/files/2904255/high_latency_log.txt)

**Comment by klaytaybai** [comment]
Hi @WyzeTao, we're sorry to hear you saw a performance decrease.  I think it is unlikely that there is an issue caused from the .NET side, especially because you have not made changes to your code.  It looks like there are a lot of external factors outside AWS that might affect your response times for this particular device discovery operation.  Do you have more evidence of a large shift in behavior since 1/23?  Is this consistent?  Has anything changed in your device setup?

**Comment by klaytaybai** [comment]
Hi @WyzeTao, we're till looking into this

**Comment by vellozzi** [comment]
Can you send the following information?
* some repro code (**please redact any sensitive information, like credentials, etc.**)
* what region you're running in
* which runtime you're using

**Comment by WyzeTao** [comment]
Our Lambda server is at N Virginia. Our cloud server is at Oregon (AWS West).
We are using .NET Core 2.0

Here are some sample code:
        {
            var stepTag = "[CameraDiscovery][STEP]";
            Stopwatch sw = new Stopwatch();
            WriteCloudWatchLog($"Begin Discovery"); 
            string token = input.Directive.Payload.Scope.Token;
            var verifyAccessTokenRequest = new VerifyAccessTokenRequest(Configurations.ClientIssure, token);

            sw.Start();
            var verifyAccessTokenResponse = _identityServer.VerifyAccessTokenAsync(verifyAccessTokenRequest).Result;
            sw.Stop();
            WriteCloudWatchLog($"{stepTag}[VerifyAccessToken] Duration = {sw.ElapsedMilliseconds}");
            
            var request = new GetDevicesRequest(Configurations.PhoneId, Configurations.AppVersion,
                verifyAccessTokenResponse.UserCenterAccessToken, Configurations.Sc, Configurations.GetDevicesSv);
            sw.Restart();
            var getDevicesResponse = _applicationCenter.GetDevicesAsync(request).Result;
            sw.Stop();
            WriteCloudWatchLog($"{stepTag}[GetDevices] Duration = {sw.ElapsedMilliseconds}");
            WriteCloudWatchLog($"{stepTag}[GetDevicesSuccess] Response = {JsonConvert.SerializeObject(getDevicesResponse)}");
...
}

**Comment by ashishdhingra** [comment]
Hi @WyzeTao,

Good afternoon.

I was going through backlog and came across this issue. Could you please confirm if this is still an issue? In case this is no longer an issue, kindly advise if we could close the same.

Thanks,
Ashish

**Comment by WyzeTao** [comment]
Hi @ashishdhingra , this is a very old ticket. We no longer have the issue. Please feel free to close it. Thanks!
