### ISSUE TITLE
Problem publishing if using an xUnit 2.2 project

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#407]
If you add an xUnit project to your solution and it is DotNet Core 2.2, then you cannot publish a 2.1 project in the same solution to Lambda.
AWS Publish complains that you cannot publish a 2.2 project.

If you unload the 2.2 xUnit project and save the solution, the publish still complains.
If you remove the 2.2 xUnit project and save the solution, then you can publish.

Why should AWS publish care if you have other non-Lambda 2.2 projects in the solution?

Thanks

**Comment by normj** [comment]
I wasn't able to reproduce the problem. I created a Lambda project with tests, change the framework of the test project to `netcoreapp2.2` and was able to deploy the Lambda project with no problem.

Any chance you could provide a sample solution that demonstrated the problem?

**Comment by girishnuli** [comment]
@normj The dotnet version status page shows that the latest version of .Net core supported by lambda is 2.1.6. Are you saying that we can also deploy version 2.2 apps without any issues? Thanks.

**Comment by Yottster** [comment]
@girishnuli they are talking about something like this
``` 
PROJECT.sln  -  PROJECT.csproj       -> netcoreapp2.1
           \
             -  PROJECT.Tests.csproj -> netcoreapp2.2
```

**Comment by normj** [comment]
@Yottster is correct, we are just talking about a test project being .NET Core 2.2.

**Comment by genifycom** [comment]
Norm, I am unable to reproduce this. Must have been some dependency that is not showing with the latest updates so I will close this one.
