### ISSUE TITLE
APIGatewayProxyFunction: Can't parse Identity from custom lambda authorizer output

### ISSUE THREAD

**Issue by LUS1N** [aws/aws-lambda-dotnet#408]
Custom Lambda Authorizer will output the claims directly in the authorizer object, while the Cognito User Pool token validator outputs the claims under authorizer.claims object, which prevents the claims from being loaded at all, cause the code in `PostCreateContext` is looking in Authorizer.Claims.

**Comment by normj** [comment]
Closing in favor tracking this with your PR. https://github.com/aws/aws-lambda-dotnet/pull/409
