### ISSUE TITLE
WebSockets use inside WebApi on Lambda

### ISSUE THREAD

**Issue by eByte23** [aws/aws-lambda-dotnet#412]
Hi,

I'm currently looking to use ApiGateway Web sockets as a solution on lambda in the same project as WebAPI with the possibility of utilising SignalR.

Using the web sockets alone,  there are a few issues that I have already come across.

As ApiGateway does not use path, resourcePath or other things related too http request as current. The current setup errors in MarshallRequest in APIGatewayProxyFunction.

I will be making this work just wondering if it something that would be consider for a merge as I really don't want to have this sort of custom code in my work projects, for maintainability reasons.

You'll be able to test what I mean and see what I'm working on and testing with here
https://github.com/eByte23/Amazon.Lambda.SignalR/tree/master
and here
https://github.com/eByte23/aws-lambda-dotnet/tree/websockets

Any input would be great.
Thanks

**Comment by eByte23** [comment]
Okay, so got it working pretty easily just had to handle the few cases where null refs occurred.
I haven't really had a look at the standard corefx websocket implementation but I'm guessing you'd have to implement IHttpWebSocketFeature Correct? and pass that through..

**Comment by ashishdhingra** [comment]
Hi @eByte23,

Please confirm if you need any further guidance or if the issue could be closed.

Thanks,
Ashish

**Comment by eByte23** [comment]
Hi,
I am no longer using this feature and unsure if the issue was resolved. 

Will close the ticket.
