### ISSUE TITLE
Error publishing PowerShell Lambda Function: -1

### ISSUE THREAD

**Issue by vmsilvamolina** [aws/aws-lambda-dotnet#413]
When I try to publish a function, I get the following message:
```
Error publishing PowerShell Lambda Function: -1
CALLSTACK:
Command                     Arguments
-------                     ---------
_deployProject              {{S3KeyPrefix=$null}, {S3KeyPrefix=$null}, {S3KeyPrefix=$null}, {S3KeyPrefix=$null}}
Publish-AWSPowerShellLambda {{IAMRoleArn=lambda_basic_execution$null}, {IAMRoleArn=lambda_basic_execution$null}, {IAM...
<ScriptBlock>               {{=$null}, {=$null}, {=$null}, {=$null}}
At C:\Users\vsilva01\Documents\PowerShell\Modules\AWSLambdaPSCore\1.2.0.0\Private\_DeploymentFunctions.ps1:194 char:13
+             throw $msg
+             ~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Error publishin...
:String) [], RuntimeException
+ FullyQualifiedErrorId : Error publishing PowerShell Lambda Function: -1
CALLSTACK:
Command                     Arguments
-------                     ---------
_deployProject              {{S3KeyPrefix=$null}, {S3KeyPrefix=$null}, {S3KeyPrefix=$null}, {S3KeyPrefix=$null}}
Publish-AWSPowerShellLambda {{IAMRoleArn=lambda_basic_execution$null}, {IAMRoleArn=lambda_basic_execution$null}, {IAM...
<ScriptBlock>               {{=$null}, {=$null}, {=$null}, {=$null}}
```
**PowerShell version:** 6.1.1
**AWSLambdaPSCore:** 1.2.0.0
**AWSPowerShell.NetCore:** 3.3.428.0

**Comment by klaytaybai** [comment]
Do you get another error message directly above this that might provide more indication of what the problem is?

**Comment by vmsilvamolina** [comment]
No. I tried a different way to publish; I created a empty function first and then publish with the same name, and the error is the same.

**Comment by vmsilvamolina** [comment]
**Update:** If you create the package using the command `New-AWSPowerShellLambdaPackage -ScriptPath .\functionFile.ps1 -OutputPackage fileUploader.zip` and upload the file (setting the handler correctly) the function works. So, the error is only in the publication process.

**Comment by donovan-middleton** [comment]
I am having the same issue!  I am using the instructions from AWS found here:
https://docs.aws.amazon.com/lambda/latest/dg/lambda-powershell-how-to-create-deployment-package.html
When I go to publish the function, I get the same error @vmsilvamolina described after running the following command within PowerShell Core:
Publish-AWSPowerShellLambda -ScriptPath .\MyFirstPSScript.ps1 -Name MyFirstPSScript -Region us-east-1
I know the command works because I can execute the same commands from a virtual machine on my laptop having the issue!
I have attached a screenshot (and text file) of the full output from the command also shows the version of PowerShell Core and .NET Core.
![Error publishing PowerShell Lambda Function](https://user-images.githubusercontent.com/45984475/59395207-6305d880-8d48-11e9-9f09-4d6b8df17e1d.png)
[Error publishing PowerShell Lambda Function.txt](https://github.com/aws/aws-lambda-dotnet/files/3283618/Error.publishing.PowerShell.Lambda.Function.txt)

**Comment by CarltonW** [comment]
Did get figure this out? I'm having same issue? AWS Support can't seem to figure it out either.

**Comment by donovan-middleton** [comment]
I finally got mine to work. I ended up having to pretty much uninstall all AWS related modules in all PowerShell instances first.  
I ran the following as Administrator in the PowerShell ISE to list the installed modules:
`Get-InstalledModule`
And in my case, I had 3...  So I uninstalled all 3 in the same PowerShell ISE as follows:
`Uninstall-Module -Name AWSLambdaPSCore -AllVersions`
`Uninstall-Module -Name AWSPowerShell -AllVersions`
`Uninstall-Module -Name AWSPowerShell.NetCore -AllVersions`
After I rechecked and made sure everything was gone in the PowerShell ISE, I launched PowerShell Core (pwsh) as Administrator. In there, I did the same looking at installed modules and uninstalling any that were AWS related:
`Get-Module`
`Uninstall-Module -Name ...`
After rechecking PowerShell Core, I went into Visual Studio Code (my editor) as Administrator and checked for the modules in the terminal there. I couldn't uninstall them in the same manner though, but I did find the My Documents\PowerShell\Modules folder with them in there. I simply deleted each, relaunched Visual Studio Code, and checked again... Gone!
Now that everything was gone, I reinstalled what I needed...
I launched PowerShell Core as Administrator again and ran the following:
`Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted`
`Install-Module -Name AWSLambdaPSCore -Scope AllUsers`
This allows me to successfully use the Publish-AWSPowerShellLambda command in PowerShell Core as well as in the Visual Studio Code terminal.
Hope this helps.

**Comment by cwhitmore88** [comment]
Donovan,
Thanks for posting your solution. I'll try it this weekend.

**Comment by ashishdhingra** [comment]
Hi @vmsilvamolina, 

Please confirm if you were able to test the steps shared by @donovan-middleton and if this issue could be closed.

Thanks,
Ashish

**Comment by cwhitmore88** [comment]
Donovan's solution worked for me.

**Comment by vmsilvamolina** [comment]
@ashishdhingra I read now the mention XD, but yes, like @cwhitmore88: Donovan's solution worked for me too.
