### ISSUE TITLE
Invocation Errors not incrementing

### ISSUE THREAD

**Issue by greggchappell** [aws/aws-lambda-dotnet#416]
With a "File > New" Serverless Web Api project if you change an action to throw an exception it doesn't increment the Errors metric on the Lambda monitoring page.

Is this intentional or a bug?

**Comment by klaytaybai** [comment]
Hi @greggchappell, I've been looking into this.  I am inclined to believe that it is a bug, but I want to talk to more people before stating this outright.  Thank you for reporting it.

**Comment by normj** [comment]
Actually from Lambda's point of view the execution was not an error. This is because ASP.NET Core catches all exceptions and returns back a response to API Gateway. The response from API Gateway will have the error HTTP status code. From Lambda point of view though an invocation happen and a response was returned so it was a successful execution.

**Comment by greggchappell** [comment]
Thanks @normj, I thought that might be the rational.

I'd been looking into safe deployments on https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst and LatestVersionErrorMetricGreaterThanZeroAlarm suggested to me that the error metric would increment if the new version was throwing.

If we wanted to implement something that did roll back because the new version was throwing exceptions what would you recommend? A custom metric maybe?

**Comment by ashishdhingra** [comment]
Hi @greggchappell,

Good afternoon.

I was going through the backlog issues and came across this one. One approach could be to log the error with relevant details (like version, etc.) in CloudWatch and use CloudWatch APIs to access log streams to examine the number of errors for that version. Then based on errors reaching certain threshold, rollback the new version that is deployed. 

For custom metric, the documentation [Getting Metrics from Amazon CloudWatch](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cloudwatch-getting-metrics-examples.html) provides some useful information.

Please let me know if above approach sounds helpful and if this issue could be closed.

Thanks,
Ashish
