### ISSUE TITLE
Binary data being transformed into non base64 encoded string during gateway proxy integreation

### ISSUE THREAD

**Issue by whelen-cchevalier** [aws/aws-lambda-dotnet#417]
The `APIGatewayProxyRequest` type defines the body as a string. If I receive a request with `IsBase64Encoded` set to false I have no way to process this data as it comes back in a unknown encoding. Is there a way to have gateway to transform binary data into base64 or receive it in the parameter as binary data?

**Comment by alanedwardes** [comment]
This is an API Gateway setting: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html

Once this is set and deployed, requests have IsBase64Encoded set to true and the body is a base64 encoded string.

**Comment by klaytaybai** [comment]
Hi @whelen-cchevalier, does following Alan's comment resolve your problem?

**Comment by whelen-cchevalier** [comment]
I Stumbled upon a way using a request body. I create an empty model (`{}`) and added it to the request body settings for the `application/octet-stream` content type
