### ISSUE TITLE
Missing a READ Me for CloudWatchEvent

### ISSUE THREAD

**Issue by benlec** [aws/aws-lambda-dotnet#422]
I don't know how to use these CloudWatchEvent.

Obviously there is an error when trying to use it in my handler:

        public void FunctionHandler(CloudWatchEvent<T> evt, ILambdaContext context)
        {
            LambdaLogger.Log(evt.Detail);
        }

Gives me a warning saying:

Error	CS0246	The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?)	AWSLambda1	

Could you help?

**Comment by klaytaybai** [comment]
Hi @benlec, you will need to make your class generic as well.  To use your function with a specific type, you should define your own class to be used in place of T.  You can find some preexisting CloudWatchEvent detail classes in https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.CloudWatchEvents.  You can also create your own like exemplified in https://github.com/aws/aws-lambda-dotnet/issues/88.  You may use this [documentation on event types](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html) as a reference to the data structures you may use.

I'll ask for a README to be created.

**Comment by ashishdhingra** [comment]
Readme added
