### ISSUE TITLE
Packaging issue

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#423]
More frequently now getting an error when doing an AWS Publish from Visual Studio Community Edition 15.9.9

There is no code running and a second publish usually proceeds fine.

... publish: C:\Program Files\dotnet\sdk\2.2.101\Microsoft.Common.CurrentVersion.targets(4863,5): error MSB3491: Could not write lines to file "obj\Debug\netcoreapp2.1\AWSUtilities.csproj.FileListAbsolute.txt". The process cannot access the file '...\AWSUtilities\obj\Debug\netcoreapp2.1\AWSUtilities.csproj.FileListAbsolute.txt' because it is being used by another process. [...\AWSUtilities\AWSUtilities.csproj]

FileListAbsolute.txt should only be getting used by AWS publish.

**Comment by klaytaybai** [comment]
Hi @genifycom, I'm sorry to hear you are experiencing this.  How often is this happening?  It is still working sometimes, right?  Unfortunately, I'm not sure if there is much we are going to be able to do to help.  If you find something that we can try to help with, let us know.  Based on other comments I have read online, people seem to struggle with finding a great solution and instead just deal with workarounds like cleaning and rebuilding or restarting Visual Studio until it works.

**Comment by genifycom** [comment]
It appears to be happening more frequently now. However, this may be because the projects are getting larger :-)

For example this morning two files
project.csprojAssemblyReference.cache and project.csproj.FileListAbsolute.txt are the two most common. I have to attempt the AWS publish at least three times.

I am still trying to locate which process locked the files (trying Process Explorer and Resource Monitor). So far , the locked files do not show up.

Also please note that the AWS Operation Failed dialog is not modal. Please remove this dialog box otherwise you can easily set focus to Visual Studio and end up locked out (i.e. VS indicates an open dialog box).

**Comment by genifycom** [comment]
Update, had to run the publish 6 times to finally get it through. This is a project that uses 7 class libraries referenced by the main project. I am beginning to suspect that the number of class libraries matter as the file in use error often happens in the class libraries.

**Comment by normj** [comment]
If you execute `dotnet publish` on the command line fo the project do you have the same issues? Can you try that with and without Visual Studio opening with the solution?

**Comment by genifycom** [comment]
Hi Norm,

I am going to close this as I can reproduce purely using dotnet publish so it is clearly not an AWS toolkit problem.

Thank you,

Dave
