### ISSUE TITLE
Different behaviour when ASPNETCORE_ENVIRONMENT = Development

### ISSUE THREAD

**Issue by mabead** [aws/aws-lambda-dotnet#424]
In order to standardize the environment names used by our micro-services, I had to change the value of the environment variable ASPNETCORE_ENVIRONMENT from `Dev` to `Development`. This was a terraform one liner. But then, one of my lambdas failed to run. There were problems in the IOC. 

After lots of digging, I found out that it was because of this line https://github.com/aws/aws-lambda-dotnet/blob/09c9e579ca9a5ad038fd40b5be0d324a7fb8beb0/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L185

I must admit that we do something a little weird: in a "normal" lambda (i.e. not a REST API ASP.NET Core lambda), I use the web host builder & IOC outside of the ASP.NET Core pipeline:

```csharp
public async Task FunctionHandlerAsync(DownloadJobPreparationLambdaInput input, ILambdaContext context)
{
    var builder = LocalEntryPoint.BuildWebHostBuilder(new string[0]);
    var host = builder.Build();
    var services = host.Services;

    var worker = services.GetService<IDownloadJobPreparationWorker>();

    await worker.PrepareDownload(Guid.Parse(input.JobId), input.Request);
}
```
The goal behind this strategy is to be able to use the IOC within a lambda. This makes it easier to connect my object with its dependencies from within my lambda entry point. I know that it is weird and unusual, but it is the trick that we found a year or two ago when the .NET generic host did not exist.

Even though it is weird, it works. But then, just changing an environment variable made our lambda fail. As previously said, it is caused by a line that uses `IsDevelopment()`. The `options.ValidateScopes` value should either **always** be `true` or `false`.

IMHO, `aws-lambda-dotnet` should always have the same behavior regardless of the environment. Having the code behave differently between environment is quite problematic in a CI/CD pipeline. The code should behave the same everywhere.

What do you think?

**Comment by normj** [comment]
I'm not quite sure what you are asking. Are you asking us to ignore whatever ASPNETCORE_ENVIRONMENT is set to? This code is a mirror of what ASP.NET Core does when creating the default WebHost which I believe is the right choice.

https://github.com/aspnet/AspNetCore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/DefaultBuilder/src/WebHost.cs#L149-L200

**Comment by mabead** [comment]
At first, yes I was asking to ignore the ASPNETCORE_ENVIRONMENT variable. Having code that does not always behave the same reminds me of the days where we had lots of `#ifdef DEBUG`. I still have a few scars that are still not totally healed ;)

After entering the current issue, I continued to check in ASP.NET Core and found the exact same code that you referred to. Having both ASP.NET Core and AWS Lambda Dotnet behave the same is perfect. I would prefer if the rule was to always have `options.ValidateScopes = true` or `options.ValidateScopes = !context.HostingEnvironment.IsProduction()` so that all pre-production environment behave the same.

All this being said, I am fine with  the current behavior. You can therefore ignore the current issue. Thanks for your input.
