### ISSUE TITLE
Error executing Lambda with Custom .NET Core Runtime

### ISSUE THREAD

**Issue by tonysneed** [aws/aws-lambda-dotnet#426]
I followed instructions ([Announcing Amazon.Lambda.RuntimeSupport](https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/)) for creating and deploying a Lambda function based on .NET Core 2.2 using the new support for custom runtimes.

However, when executing the runtime I get the following error:

```
Error: Runtime failed to start: fork/exec /var/task/bootstrap: no such file or directory
```

My bootstrap file has the following content:

```
#!/bin/sh
# This is the script that the Lambda host calls to start the custom runtime.

/var/task/HelloLambdaNetCore
```

I verified that the publish output includes a `HelloLambdaNetCore` file.

**Comment by normj** [comment]
What version of the Amazon.Lambda.Tools and what OS did you do the deployment? Version 3.2.0 shipped today which contains fix for non-windows platforms dealing with windows line endings that might fix your issue.

**Comment by tonysneed** [comment]
I'm deploying from a Mac with version 3.1.4 of the Amazon.Lambda.Tools. But I can see version 3.2.0 is available, so I will upgrade and re-deploy.

**Comment by tonysneed** [comment]
It works now. Thank you!
