### ISSUE TITLE
Test Blueprint For AspNetCoreWebApp

### ISSUE THREAD

**Issue by ghartsho** [aws/aws-lambda-dotnet#430]
The dotNet Core 2.1 AspNetCoreWebAPI has both an app & test blueprints, but the AspNetCoreWebApp only has an app blueprint. I assume this is why when using the AWS Toolkit for Visual Studio and creating a new AWS Lambda project of type "AWS Serverless Application with Tests (.Net Core)" creates a working app project, but only creates an empty folder for the test project.

Is there a blueprint for AspNetCoreWebApp tests available?

![image](https://user-images.githubusercontent.com/2940274/55121286-d4c67280-50c7-11e9-8d3e-fe46847ac4d1.png)

**Comment by normj** [comment]
There are no tests currently for that blueprint but I agree we should add some.
