### ISSUE TITLE
ApplicationLoadBalancerFunction doesn't play nicely with healthchecks

### ISSUE THREAD

**Issue by aidansteele** [aws/aws-lambda-dotnet#436]
Hi,

**Background:**

Target groups with Lambda targets don't have health checks turned on by default. If you turn on health checks for an ASP.Net Core app using the `ApplicationLoadBalancerFunction.FunctionHandlerAsync` handler, health checks will fail and the Lambda will emit exception stack traces.

The Lambda request payload for health checks is documented [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#enable-health-checks-lambda) as looking like:

```json
{
    "requestContext": {
        "elb": {
            "targetGroupArn": "arn:aws:elasticloadbalancing:region:123456789012:targetgroup/my-target-group/6d0ecf831eec9f09"
        }
    },
    "httpMethod": "GET",  
    "path": "/",  
    "queryStringParameters": {},  
    "headers": {
        "user-agent": "ELB-HealthChecker/2.0"
    },  
    "body": "",  
    "isBase64Encoded": false
}
```

**Problem**:

This line of code is what parses the scheme:

https://github.com/aws/aws-lambda-dotnet/blob/6414d0b750ae7aafe4933095c93c3412b2afeae7/Libraries/src/Amazon.Lambda.AspNetCoreServer/ApplicationLoadBalancerFunction.cs#L63

After this line runs for the above request payload, `requestFeatures.Scheme` is still `null`. This causes a null reference exception here: 

https://github.com/aspnet/Hosting/blob/1da228d28fdfcfb2d77241c4e0413efec1beeafd/src/Microsoft.AspNetCore.Hosting/Internal/HostingRequestStartingLog.cs#L37

The properties after `Scheme` probably fail too, but this is the first to fail.

**Solution**:

Given that ASP.Net Core appears to treat these properties as non-null, we should probably populate them unconditionally. *Any* value will be better than no value. Any thoughts about how you'd best like to approach this? I'd be happy to submit a PR fixing it with unit test coverage.

**Comment by normj** [comment]
That is an interesting one. I'm afraid to just default the value to `https` in case there is a situation that is not correct. I wonder if we should look to see if the user-agent starts with "ELB-HealthChecker" and if so default schema to https.

**Comment by normj** [comment]
PR is submitted to handle ELB Health Check: https://github.com/aws/aws-lambda-dotnet/pull/452

**Comment by normj** [comment]
Version 3.0.4 is out with this fix.

**Comment by normj** [comment]
Closing as the fix was shipped.
