### ISSUE TITLE
Amazon.Lambda.TestTool resolves wrong dll version

### ISSUE THREAD

**Issue by neoned** [aws/aws-lambda-dotnet#437]
I've run into a situation when `LambdaTestTool` resolves wrong dll version.
We have a lambda project targeting **netcoreapp2.1** and referencing **Newtonsoft.Json 12.0.1**.
When starting it via `LambdaTestTool` it loads **Newtonsoft.Json 11.0.2** which is a dependency of **Microsoft.AspNetCore.App** package (2.1.8 in my case) located at `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.1.8`. Looks like `LambdaAssemblyResolver` issue.
Is it expected behavior?
LambdaTestTool version is 0.9.2

**Comment by klaytaybai** [comment]
Hi @neoned.  I don't think this is expected behavior, but I'm having trouble reproducing it.  I'll ask @normj if he has any extra guidance.

**Comment by neoned** [comment]
@klaytaybai Thanks for the quick answer. [Here](https://github.com/neoned/AwsLambdaTestTool-Samples) is a repository with samples allowing to reproduce the issue

**Comment by normj** [comment]
Closing in favor this issue I opened up that explains the issue. https://github.com/aws/aws-lambda-dotnet/issues/453

**Comment by wieslawo** [comment]
I had a similar problem, in my case removing the line from the .csproj file helped
    <PublishReadyToRun>true</PublishReadyToRun>
