### ISSUE TITLE
Handle the raw incoming APIGatewayProxyRequest event

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#444]
In node.js it is easy to write out the incoming APIGatewayProxyRequest event

i.e. exports.handler = async (event) => {
    console.log('Event is '+ JSON.stringify(event));
    const response = {statusCode: 200, body: JSON.stringify('Hello from Lambda!')};
    return response;
};

In ASP.Net Core Web, are we supposed to override FunctionHandlerAsync and do the same thing (i.e. capture, or write out, or change routing).

The main reason for asking is to wire a WebSocket API Gateway ($connect, $disconnect etc) to an ASP.Net Core Web Lambda. I could not find an example of this anywhere (only Norms example of routing to a Lambda function, one for each routeKey).

The $connect event does not have a request.httpmethod so I would be routing this (ideally to the SignalR associated Hub).

I am looking to fit in correctly with a possible future direction, are there existing examples that I missed?

Thanks

**Comment by normj** [comment]
If your goal is you want to see the full raw JSON in your log you can add the environment `LAMBDA_NET_SERIALIZER_DEBUG` with a value of `true`. This is a common trick I use to debug any marshaling issues.

**Comment by genifycom** [comment]
Thanks for that one Norm. Very helpful.

The other bit was being able to take your example https://github.com/normj/netcore-simple-websockets-chat-app and use an ASP.Net Core Web app (instead of multiple separate functions).

For this I believe that I need to intercept the FunctionHandlerAsync and based on the event.routeKey take some action.

Any recommendations of the "right" approach?

**Comment by ashishdhingra** [comment]
Hi @genifycom, 

Good afternoon.

I was going through issue back log and came across this guidance question. I do see that @normj provides some guidance. It's been a while there has been any activity on this issue. Please advise if you still need more guidance or if this issue could be closed.

Thanks,
Ashish
