### ISSUE TITLE
Running `dotnet lambda list-functions` results in `Error listing Lambda functions: Request headers must contain only ASCII characters.`

### ISSUE THREAD

**Issue by adamdry** [aws/aws-lambda-dotnet#447]
Exactly as the title says running `dotnet lambda list-functions` results in `Error listing Lambda functions: Request headers must contain only ASCII characters.`

What can I do to debug this issue? Thanks!

**Update 1**
OS version (from `winver`): Windows 10 v1809 (OS Build 17763.437)
Amazon.Lambda.Tools version (from `dotnet lambda --version`): 3.2.0
AWS Region: eu-west-1
dotnet version (from `dotnet --version`): 2.1.603

I don't think it's getting as far as making the web request. I deliberately invalidated my AWS creds on my local machine and I get the same issue, rather than a perms error from AWS.

**Update 2**
Using Fiddler I can see it:
- tunnels to `http://dc.services.visualstudio.com:443`
- then makes a successful request to `dc.services.visualstudio.com`
- then tunnels to `http://lambda.eu-west-1.amazonaws.com:443`

There are no more requests after this. All have an HTTP response of 200.

**Update 3**
Output from `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.603
 Commit:    ae71c68742

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.603\

Host (useful for support):
  Version: 2.1.10
  Commit:  9013a2af4b

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.603 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by normj** [comment]
A couple questions to help diagnose the issue:
* What OS are you running the command on?
* What version of Amazon.Lambda.Tools are you using?
* What AWS region are you using?

If you are running this on Windows could you use fiddler to capture the failed web request?

**Comment by adamdry** [comment]
@normj thanks, I've updated my question to include those details.

**Comment by klaytaybai** [comment]
@adamdry, we haven't reproduced this yet.  Can you check to see if any headers are being added from http://dc.services.visualstudio.com that contain non-ASCII characters (or if there are any in any request)?

**Comment by adamdry** [comment]
@klaytaybai I can confirm there's only ASCII chars in the headers in those requests, see below:

```
CONNECT dc.services.visualstudio.com:443 HTTP/1.1
Host: dc.services.visualstudio.com:443


HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 08:11:11.885
Connection: close



------------------------------------------------------------------
POST https://dc.services.visualstudio.com/v2/track HTTP/1.1
Content-Type: application/x-json-stream
Content-Length: 877
Host: dc.services.visualstudio.com


HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/10.0
x-ms-session-id: E69CBBC4-54D2-45C2-B5CB-G85C889B610A
Strict-Transport-Security: max-age=31536000
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Name, Content-Type, Accept, Sdk-Context
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
X-Content-Type-Options: nosniff
X-Powered-By: ASP.NET
Date: Fri, 26 Apr 2019 07:11:12 GMT
Content-Length: 49



------------------------------------------------------------------
CONNECT lambda.eu-west-1.amazonaws.com:443 HTTP/1.1
Host: lambda.eu-west-1.amazonaws.com:443


HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 08:11:12.228
Connection: close



------------------------------------------------------------------
```

What I _think_ is happening is that the aws-lambda-dotnet code is preparing the next request (to `http://lambda.eu-west-1.amazonaws.com:443` - confirmed by a colleague where the app is working) and one of the headers it is setting up has non-ASCII chars in it.

The problem is the error doesn't specify which header or what the illegal value is so I can't figure out where the issue might lye.

**Comment by adamdry** [comment]
So this was due to non-ASCII chars existing in my `C:\Users\username\.aws\credentials` file.

Removing the chars solved the issue.
