### ISSUE TITLE
Cannot publish ASp.NET Core to Lambda

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#45]
Using

    "AWSSDK.Core": "3.3.8",
    "AWSSDK.Extensions.NETCore.Setup": "3.3.0.2",
    "AWSSDK.DynamoDBv2": "3.3.2.1",
    "Amazon.Lambda.AspNetCoreServer": "0.8.6-preview1",
    "Amazon.Lambda.Tools": "1.1.0-preview1"

Using ASP.NET Core 1.0 when I try to "Upload Lambda Function" I get:

... publish: No executable found matching command "bower"

This is a new ASP.NET application. Nothing added yet. Just deploying (after changes as per "AWS re:Invent 2016: NEW LAUNCH! Developing Serverless C# Applications (DEV207)"

Where can I find this reference to remove it?

Thanks

**Comment by normj** [comment]
The default Visual Studio ASP.NET Core Web Application adds a reference to bower in the project.json. You can see that in the prepublish section. I believe for that to work you need to have npm installed which is part of node.js.

Not sure why they added a reference to node.js in the default project template but that is not part of the AWS integration.

**Comment by genifycom** [comment]
Got it. Thanks Norm!
