### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, ...'

### ISSUE THREAD

**Issue by JeroenVogelpoel** [aws/aws-lambda-dotnet#450]
Good day,

I've been running into an issues regarding the aws-lambda-dotnet tooling. See below for details.

## Test stepts ##

1. Create a new 'AWS Lambda Project (.NET Core - C#)' project with solution.
2. Add a new 'Class Library (.NET Core)' project.
3. Add ```Newtonsoft.Json``` dependency to class library through NuGet.
4. Add logic that uses anything from ```Newtonsoft.Json```
5. Reference library in AWS Lambda project.
6. Make a call to the class library that calls the functionality written in 4.
7. Debug AWS Lambda project; use mock tool to execute against a string such as ```"test"```

## Expected ##

Normal flow; ```Newtonsoft.Json``` library should be able to handle any calls as normal.

## Actual ##

```
System.IO.FileLoadException
  HResult=0x80131621
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
  Source=TestLibrary
  StackTrace:
   at TestLibrary.Class1.Json(Object input) in C:\Users\Username\source\repos\AWSLambdaTest002\TestLibrary\Class1.cs:line 12
   at AWSLambdaTest002.Function.FunctionHandler(String input, ILambdaContext context) in C:\Users\Username\source\repos\AWSLambdaTest002\AWSLambdaTest002\Function.cs:line 24
```

Example solution: <https://github.com/JeroenVogelpoel/AWSLambdaTest002>

**Comment by AnthonySteele** [comment]
I'm running into the same issue. After some investigation
 * The lambda `.csproj` file contains `<PackageReference Include="Newtonsoft.Json" Version="12.0.2" />` but I expect this version to be usable. We don#t need assembly biding redirects any more.
* The folder for `MyLambda\bin\Debug\netcoreapp2.1` does not contain `Newtonsoft.Json.dll`. Odd, I thought that it should be there.

**Comment by neoned** [comment]
It's the same issue as described here https://github.com/aws/aws-lambda-dotnet/issues/437

**Comment by normj** [comment]
Closing in favor this issue I opened up that explains the issue. https://github.com/aws/aws-lambda-dotnet/issues/453

**Comment by AnthonySteele** [comment]
A few comments:
* The difference between ` Newtonsoft.Json 12.0.2` in the NuGet package version, and assembly version `12.0.0.0` in the error is a red herring. The assembly version is locked to the major, so `12.0.2` will report assembly version `12.0.0.0`.  As noted elsewhere, the conflict is between version `12` and version `11.0.2` which is the version loaded.

* I can confirm this by removing the conflict: downgrade to ` Newtonsoft.Json 11.0.2` throughout the solution, rebuild and run `dotnet-lambda-test-tool-2.1` and I can test the lambda successfully. However I was using `JObject.Property(String, StringComparison)` which is new in v12 so I would prefer another option.

I'm not quite clear if this is just a limitation of `dotnet-lambda-test-tool-2.1`  or of .NET Core 2.1 lambdas in general?

**Comment by uoc1691** [comment]
Intermittently getting the error in AWS, when my serverless application is deployed. Using dotnet core 3.1.



Error

JsonSerializerException

Cause

{
  "errorType": "JsonSerializerException",
  "errorMessage": "Error converting the Lambda event JSON payload to type Amazon.Lambda.CloudWatchEvents.CloudWatchEvent`1[[FSW.AWS.Serverless.Models.CloudWatchS3EventDetail, FSW.AWS.Serverless, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.\n",
  "stackTrace": [
    "at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)",
    "at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"
  ],
  "cause": {
    "errorType": "FileNotFoundException",
    "errorMessage": "Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.\n",
    "stackTrace": [
      "at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)",
      "at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)",
      "at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)",
      "at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)",
      "at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)",
      "at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)",
      "at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Type attributeType, Boolean inherit)",
      "at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)",
      "at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)",
      "at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)",
      "at System.Reflection.CustomAttributeExtensions.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)",
      "at System.Text.Json.JsonPropertyInfo.GetAttribute[TAttribute](PropertyInfo propertyInfo)",
      "at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)",
      "at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)",
      "at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)",
      "at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)",
      "at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)",
      "at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)",
      "at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)",
      "at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)",
      "at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)",
      "at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)"
    ]
  }
}

**Comment by wieslawo** [comment]
I had a similar problem, in my case removing the line from the .csproj file helped
`<PublishReadyToRun>true</PublishReadyToRun>`

**Comment by emkensj** [comment]
removing the <PublishReadyToRun>true</PublishReadyToRun> from .csproj file helped me. Nothing above mentioned helped me, only this.

**Comment by olcampo** [comment]
Same here !

**Comment by fernanduandrade** [comment]
> I had a similar problem, in my case removing the line from the .csproj file helped `<PublishReadyToRun>true</PublishReadyToRun>`

solved my problem, thanks
