### ISSUE TITLE
Make library write out a warning when invoked with the wrong payload from upstream

### ISSUE THREAD

**Issue by hvanbakel** [aws/aws-lambda-dotnet#458]
It would be really helpful to log a warning or something similar when an endpoint is used that derives from the `ApplicationLoadBalancerFunction` but is invoked with an Api Gateway payload or vice versa. 

Especially when switching between the 2 this can catch otherwise hard to find issues because just not all properties get populated.

**Comment by klaytaybai** [comment]
@hvanbakel, thanks for the contribution.  I think we're going to need to discuss the best options for handling this before committing to a merge.  For example, instead of logging a warning, we may consider adding a method to verify the request type.

**Comment by normj** [comment]
Closing this as the work is being tracked in the PR https://github.com/aws/aws-lambda-dotnet/pull/459
