### ISSUE TITLE
APIGatewayProxyRequest and ApplicationLoadBalancerRequest should have a common interface

### ISSUE THREAD

**Issue by rschiefer** [aws/aws-lambda-dotnet#460]
I want to use both the APIGatewayProxyFunction and ApplicationLoadBalancerFunction base classes in different situations.  This would be much easier if their associated types shared common interfaces.  

For example, a IHttpRequest interface which defined properties for Body, QueryString, Path, HttpMethod, etc.  Both the APIGatewayProxyRequest and ApplicationLoadBalancerRequest would implement this interface.

**Comment by normj** [comment]
I don't think that is practical in the base events since they model what the service sends to Lambda. I think with our new [Lambda Annotation](https://github.com/aws/aws-lambda-dotnet/issues/979) library will address this issue.
