### ISSUE TITLE
Error when executing Lambda: Error sending execute request, is the .NET Lambda Test Tool been still running?

### ISSUE THREAD

**Issue by SteveMGits** [aws/aws-lambda-dotnet#461]
Per the screenshot, I receive the following error attempting to execute my Lambda:

Error sending execute request, is the .NET Lambda Test Tool been still running?

The function is not listed in the "Function" dropdown. The code I'm using functions as expected when the compiled code is published to AWS lambda and run online. 

![image](https://user-images.githubusercontent.com/8284546/57709414-f8725780-7638-11e9-92fb-b4508b717348.png)

I am using JetBrains Rider. Here is my debug configuration:

![image](https://user-images.githubusercontent.com/8284546/57711019-f958b880-763b-11e9-84c4-1121e462bb5c.png)

**Comment by klaytaybai** [comment]
Hmm.  So at the very least, we should improve the grammar of this alert. 

The function not being shown in the dropdown might be a separate issue.  We'll need to investigate this some more.

**Comment by rrjamesjr** [comment]
I'm encountering the same issue using Rider as well but I'm on Linux. It lauches the tool as expected with the function and region blank. Upon further investigation I see it was unable to load the aws-lambda-tools-defaults.json file becaues Amazon.Lambda.Serialization.Json could not be laoded. The same project runs fine on Windows 10

![image](https://user-images.githubusercontent.com/4187049/62985382-bce45680-bdfc-11e9-9e07-4557bcb42cb4.png)

**Comment by NGL321** [comment]
Hey @SteveMGits,

We were looking into this again, and if you are still experiencing the problem, we need a little more information to reproduce/understand the problem you are facing/faced.
- Are you using a Serverless template or just uploading to lambda?
- What does your details file look like?
- What is the code you are trying to test?
- Have you experienced this with other projects?
- What is the console output when you get this error?

If you arent experiencing this anymore, feel free to just close the issue.

😸

**Comment by SteveMGits** [comment]
Hi @NGL321 ,

This was for a project for a former employer - I won't be able to get any of the above information, so I'll go ahead and close the issue.

Cheers,
-Steve
