### ISSUE TITLE
ASP.NET Core 2.1 reflection doesn't work when deploying in AWS Lambda

### ISSUE THREAD

**Issue by xplatsolutions** [aws/aws-lambda-dotnet#462]
It looks like Assembly.GetEntryAssembly() is not working correctly in AWS Lambda. Is there any equivalent way to load all the assemblies referenced from entry assembly?

I need this to dynamically register in DI implementation classes ending in a specific naming convention.
‘’’
List<Type> allAssembliesTypes = Assembly
                                    .GetEntryAssembly()
                                    .GetReferencedAssemblies()
                                    .Select(Assembly.Load)
                                    .SelectMany(a => a.GetTypes())
                                    .ToList();
‘’’

For a more complete description please feel free to check this StackOverflow question I created, https://stackoverflow.com/questions/56119647/asp-net-core-2-1-reflection-doesnt-work-when-deploying-in-aws-lambda.

**Comment by normj** [comment]
`Assembly.GetEntryAssembly()` will return back the AWS .NET Lambda bootstrap assembly which is correct as it is the entry point but I recognize it would be unexpected.

Curious if getting the assembly from the Lambda function class would have worked or was that type not available from this code. It sounds like from Stackoverflow you found a work around so I'm going to close this. Sorry we should have responded sooner but if there are any more questions feel free to reopen.
