### ISSUE TITLE
appsettings.json not being published to Lambda

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#464]
I have not yet determined exactly when this happens since it is sporadic.
appsettings.json is created in the publish folder if I use "dotnet publish -c Release -r linux-arm"

However when using "dotnet lambda deploy-function" the appsettings.json is not copied into the zip file.

Is there a way to determine why this is? I have tried changing appsettings.json to Copy Always (in properties in Visual Studio) but it still is not included.

I am using Amazon Lambda Tools for .NET Core applications (3.2.0)

**Comment by RamiSh** [comment]
@genifycom still seeing the same issue?

**Comment by ashishdhingra** [comment]
Hi @genifycom, 

Please advise if using the latest version of Lambda tools resolves the issue.

Thanks,
Ashish
