### ISSUE TITLE
Error in message file

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#465]
dotnet lambda package

shows the error message below. The latest version supported is not shown. Also compatibility is misspelled. 

Project is referencing Microsoft.AspNetCore.App without specifying a version. A version is required to ensure compatiblity with the supported versions of Microsoft.AspNetCore.App in the Lambda compute environment. Edit the PackageReference for Microsoft.AspNetCore.App in your project file to include a Version attribute.  The latest version supported in Lambda is {results.Item2}.

**Comment by genifycom** [comment]
With regard to the actual message. Microsoft indicate that we should remove the Version attribute

**Comment by klaytaybai** [comment]
Which version of amazon.lamba.tools are you using?

**Comment by soydantaylor** [comment]
Reproduced this with DotNetCliToolReference 2.2.0
