### ISSUE TITLE
Get-AWSPowerShellLambdaTemplate Help Examples demonstrates a parameter that is not available.

### ISSUE THREAD

**Issue by austoonz** [aws/aws-lambda-dotnet#466]
[This example](https://github.com/aws/aws-lambda-dotnet/blob/master/PowerShell/Module/Public/Get-AWSPowerShellLambdaTemplate.ps1#L23) shows a "-InstalledOnly" parameter that doesn't exist in the actual function.

This should be implemented, or removed from the examples in a future release.

**Comment by klaytaybai** [comment]
Thanks

**Comment by NGL321** [comment]
Fixed by #468
