### ISSUE TITLE
How to access Request properties in middleware?

### ISSUE THREAD

**Issue by Jthomas54** [aws/aws-lambda-dotnet#472]
I have some request logging middleware and when I attempt to access properties and methods on the `httpContext.Request` object, I just get null exceptions.  I am attempting to access the following properties:

* GetDisplayUrl()
* Method
* Protocol
* Scheme

How can I access these or where can I configure them?  I did try using the `httpContext.Features.Get<IHttpRequestFeature>()` but `Features` seems to be null as well.

**Comment by normj** [comment]
Could you provide a repo that reproduced the issue?
