### ISSUE TITLE
.Net Core (2.1)- Lambda function does work while 2.2 doesn't?

### ISSUE THREAD

**Issue by RoyiNamir** [aws/aws-lambda-dotnet#478]
I've created a simple empty AWS Lambda function using .Net Core 2.1 : 

[![enter image description here][1]][1]

Here is the folder structure : 

[![enter image description here][2]][2]

(here is the [csproj][3])

And a FunctionHandler which gets DI and invoke some dummy method : 

[![enter image description here][4]][4]

Now let's run the "Mock Lambda Test Tool"  , we can see that it works : 

[![enter image description here][5]][5]

**So where is the problem?** 

I've read [here][6] that 2.2 is supported :

> This means you can now author Lambda functions using .NET Core 2.2 and
> .NET Core 3.0 preview. Amazon.Lambda.RuntimeSupport is available as
> source code on GitHub, or as a NuGet package.

And so , I've created a new empty lambda project but with 2.2 : 

[![enter image description here][7]][7]

* [Here are the changes in the CSPROJ file][8]  
* [And here are the changes in the aws-lambda-tools-defaults.json file][9]

Same code. But now when I run "Mock Lambda Test Tool" , I get an error : 

> AWS .NET Mock Lambda Test Tool (0.9.2) Unknown error occurred causing
> process exit: Failed to find a deps.json file    at
> Amazon.Lambda.TestTool.Runtime.LocalLambdaRuntime.Initialize(String
> directory) in
> E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Runtime\LocalLambdaRuntime.cs:line
> 50    at Amazon.Lambda.TestTool.Program.Main(String[] args) in
> E:\JenkinsWorkspaces\Lam\LambdaSandboxCoreCLRApi\Tools\LambdaTestTool\Amazon.Lambda.TestTool\Program.cs:line
> 46 Press any key to exit

Here is the error : 

[![enter image description here][10]][10]

**Question:**

Why is that? I didn't have any `deps.json` file in 2.1 .

So why do I need it in 2.2 ?
Also, what is this path appearing in the error: `E:\JenkinsWorkspaces`... ?
I don't have Jenkins nor something like it.

  [1]: https://i.stack.imgur.com/b3eRQ.png
  [2]: https://i.stack.imgur.com/Zg7JS.png
  [3]: https://gist.github.com/RoyiNamir/ee639c6b66bd295e0bc5569c4533442c
  [4]: https://i.stack.imgur.com/TO8LI.png
  [5]: https://i.stack.imgur.com/X41Kd.png
  [6]: https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/
  [7]: https://i.stack.imgur.com/JqUUN.png
  [8]: https://i.imgur.com/t8o9GJU.jpg
  [9]: https://i.imgur.com/H4qNrQC.jpg
  [10]: https://i.stack.imgur.com/TYRDp.png

**Comment by RoyiNamir** [comment]
Update , I think it's a bug : but I found the reason : 

https://stackoverflow.com/questions/56619863/net-core-2-1-lambda-function-does-work-while-in-2-2-it-doesnt

**Comment by normj** [comment]
Unfortunately the mock testing tool doesn't currently support Lambda functions using the custom runtime feature. We have a GitHub issue tracking this https://github.com/aws/aws-lambda-dotnet/issues/427

**Comment by klaytaybai** [comment]
I'm going to close this out as a duplicate in favor of #427.
