### ISSUE TITLE
Custom lambda runtime fail to run

### ISSUE THREAD

**Issue by HalidCisse** [aws/aws-lambda-dotnet#480]
Hi, I'm following Amazon.Lambda.RuntimeSupport example here
https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.RuntimeSupport
After I publish and invoked the function I got the following error:
`Runtime exited with error: exit status 137`

````
C:\Projects\Lambda>dotnet lambda invoke-function -p "hello world"
Amazon Lambda Tools for .NET Core applications (3.2.3)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Payload:
{"errorType":"Runtime.ExitError","errorMessage":"RequestId: d88fc138-1756-4e8f-b887-d44851c12b84 Error: Runtime exited with error: exit status 137"}

Log Tail:
START RequestId: d88fc138-1756-4e8f-b887-d44851c12b84 Version: $LATEST
Failed to initialize CoreCLR, HRESULT: 0x80004005
END RequestId: d88fc138-1756-4e8f-b887-d44851c12b84
REPORT RequestId: d88fc138-1756-4e8f-b887-d44851c12b84  Duration: 631.51 ms     Billed Duration: 700 ms         Memory Size: 256 MB     Max Memory Used: 18 MB
RequestId: d88fc138-1756-4e8f-b887-d44851c12b84 Error: Runtime exited with error: exit status 137
Runtime.ExitError
````

Please advise.

**Comment by normj** [comment]
What platform did you deploy your function from? Windows, Mac, other? If you wrap the Main function in a try catch and write any exception message to the console do you see anymore logging information in the associated CloudWatch Log stream?

**Comment by HalidCisse** [comment]
I deployed it using the CLI tool `dotnet lambda deploy-function`
Here is the logs on aws console

![image](https://user-images.githubusercontent.com/6313791/60099926-8e2cf680-9750-11e9-86dc-ad19bc908c4f.png)
![image](https://user-images.githubusercontent.com/6313791/60100050-d2b89200-9750-11e9-9af6-cc533ad57a85.png)

**Comment by ashishdhingra** [comment]
Hi @HalidCisse,

Good afternoon.

I was going through the issue backlog and came across this issue. Exit status 137 typically indicates out of memory error. Please let me know if this is still an issue.

Thanks,
Ashish

**Comment by jelili-owolabi-swi** [comment]
Increasing the lambda memory size should fix this.

**Comment by Nithin1716079** [comment]
any one have runtime for PHP in lambda
