### ISSUE TITLE
Support ASP.NET Core 3.0 with Amazon.Lambda.AspNetCoreServer

### ISSUE THREAD

**Issue by normj** [aws/aws-lambda-dotnet#481]
With the .NET Core [custom runtime support](https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/) it is possible to use .NET Core 3.0 for Lambda functions.

ASP.NET Core 3.0 has some breaking changes that require an additional version of Amazon.Lambda.AspNetCoreServer to be created.

The changes have been made in [aspnetcore30-support](https://github.com/aws/aws-lambda-dotnet/tree/aspnetcore30-support) branch. Unfortunately to build the package with our current build infrastructure we would have to install a preview version of .NET Core in our build environment to build production packages which cannot do. Assuming no more significant changes happen to ASP.NET Core 3.0 before GA these changes will go out with the main package when .NET Core 3.0 goes GA. 

For those that want to test a preview version you can checkout my [samples repo](https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeAspNetCore30). In the [nuget-cache](https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeAspNetCore30/nuget-cache) directory is a prebuilt preview version of Amazon.Lambda.AspNetCoreServer.

**Comment by arndklocker** [comment]
With the last update to 3.0.100-preview7-012821, HostingApplication and Context class in namespace "Microsoft.AspNetCore.Hosting" not public anymore!

**Comment by normj** [comment]
Thanks for bringing this to my attention. I'll look to see what we need to do to adapt to .NET Core 3.0.

**Comment by normj** [comment]
The sample has been updated to support .NET Core 3.0 preview 8. Here is the PR that I plan on merging after .NET Core 3.0 is released that contains the changes to Amazon.Lambda.AspNetCoreServer. https://github.com/aws/aws-lambda-dotnet/pull/508

This PR contains breaking changes even for .NET Core 2.1 users. The changes are slight and should only affect users that customized the serialization between API Gateway and ASP.NET Core but I would appreciate feedback on the changes. The list of breaking changes are listed in the PR.

**Comment by andymac4182** [comment]
Great news! I will be deploying a service shortly on Preview 8 I was waiting for the fix before I did it :)

**Comment by normj** [comment]
I pushed some changes in for the upcoming version of Amazon.Lambda.AspNetCoreServer that will support .NET Core 3.0 with Custom Lambda Runtimes. Most notably implementing the required method to send static files from the ASP.NET Core application. I have updated the [samples repo](https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeAspNetCore30) with version 4.0.0-preview2 of Amazon.Lambda.AspNetCoreServer in the nuget-cache folder. I would appreciate feedback on this version.

**Comment by martonx** [comment]
Hi,

When will be the .Net Core 3 support official?

**Comment by normj** [comment]
To be clear .NET Core 3.0 will not be an officially supported runtime in Lambda since it is not an LTS. You can use .NET Core 3.0 with our [Custom Runtime feature](https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/).

I'm working on updating our build infrastructure that pushes out to NuGet to have .NET Core 3.0 on it so I can push this new version of `Amazon.Lambda.AspNetCoreServer`. That will allow users using custom runtimes to also do it with ASP.NET Core 3.0 Lambda functions.

**Comment by psbmiller** [comment]
.NET Core 3.1 will be LTS when released in November, according to [Microsoft](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)  How soon after that release should we expect to see the support in Lambda?

**Comment by psbmiller** [comment]
Makes sense.  I guess I should have asked a bit more generally to verify that since 3.1 will be LTS that we should expect to see it supported natively in Lambda at some point in the future.

**Comment by normj** [comment]
Version 4.0.0 of Amazon.Lambda.AspNetCoreServer has shipped with support for .NET Core 3.0

**Comment by alexAlchemy** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/

LTS Version released a whole 17 hours ago....  is it officially supported yet? ;-)

#Earlyxmas
