### ISSUE TITLE
Assembly name with dot is not supported in the .NET Lambda Test Tool

### ISSUE THREAD

**Issue by AlexandrSHad** [aws/aws-lambda-dotnet#485]
I am using .NET Lambda Test Tool.
If I set a function name like this `Application.LambdaFunction::Application.LambdaFunction.Function::FunctionHandler` I get the error.

_Error sending execute request, is the .NET Lambda Test Tool been still running?_

But if the function name is `ApplicationLambdaFunction::Application.LambdaFunction.Function::FunctionHandler` (without dot in assembly name) all work fine.

Visual Studio 2019: 16.1.5
amazon.lambda.testtool-2.1: 0.9.3
amazon.lambda.tools: 3.2.3

**Comment by klaytaybai** [comment]
Hi @AlexandrSHad, I wasn't able to reproduce the exact error you were seeing.

As a first point, I would like to note that function **names** cannot contain periods.  You will get an error in the AWS Console if you try to do this or this error in the VS Toolkit when you upload:  
Error creating Lambda function: 1 validation error detected: 

> Value 'PeriodAssembly.LambdaTestTool' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?

Using a function name without a period, I was able to successfully execute a function using the Lambda Test Tool when the function-handler looked like this:      
`"function-handler"     : "Testing.AssemblyLambdaTestTool::Testing.AssemblyLambdaTestTool.Function::FunctionHandler"`

Could you please try again? It might work, or this may be a different issue.

**Comment by AlexandrSHad** [comment]
It's very strange but I can not reproduce this too. It only appears at the one particular project which was created manually without using AWS Lambda Project template. It seems the issue is on my side. Sorry for waste your time.
