### ISSUE TITLE
Migrating to VS Code on Mac, getting error on attempted deploy

### ISSUE THREAD

**Issue by eat-sleep-code** [aws/aws-lambda-dotnet#491]
I have an existing Alexa skill that I had built using the AWS Toolkit package in Visual Studio 2019.   I am now trying to migrate to VS Code on the Mac.   

I have my project setup, and attempt to execute: **dotnet lambda deploy-function**

The following is the output of the command which concludes with the rather unhelpful error of: 

> Error retrieving configuration for function MySampleAlexa: The operation was canceled.

There is nothing else that really indicates what caused the error or how to resolve it.

```
Amazon Lambda Tools for .NET Core applications (3.2.3)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Executing publish command
Deleted previous publish folder
... invoking 'dotnet publish', working folder '/Volumes/Data/projects/alexa/bin/Release/netcoreapp2.1/publish'
... Disabling compilation context to reduce package size. If compilation context is needed pass in the "/p:PreserveCompilationContext=false" switch.
... publish: Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Restore completed in 50.41 ms for /Volumes/Data/projects/alexa/Framework.Alexa.csproj.
... publish:   Framework.Alexa -> /Volumes/Data/projects/alexa/bin/Release/netcoreapp2.1/rhel.7.2-x64/Framework.Alexa.dll
... publish:   Framework.Alexa -> /Volumes/Data/projects/alexa/bin/Release/netcoreapp2.1/publish/
Changed permissions on published file (chmod +rx Alexa.NET.dll).
Changed permissions on published file (chmod +rx Amazon.Lambda.Core.dll).
Changed permissions on published file (chmod +rx Amazon.Lambda.Serialization.Json.dll).
Changed permissions on published file (chmod +rx Framework.Alexa.deps.json).
Changed permissions on published file (chmod +rx Framework.Alexa.dll).
Changed permissions on published file (chmod +rx Framework.Alexa.pdb).
Changed permissions on published file (chmod +rx Framework.Alexa.runtimeconfig.json).
Changed permissions on published file (chmod +rx Newtonsoft.Json.dll).
Zipping publish folder /Volumes/Data/projects/alexa/bin/Release/netcoreapp2.1/publish to /Volumes/Data/projects/alexa/bin/Release/netcoreapp2.1/alexa.zip
... zipping:   adding: Alexa.NET.dll (deflated 62%)
... zipping:   adding: Amazon.Lambda.Core.dll (deflated 46%)
... zipping:   adding: Amazon.Lambda.Serialization.Json.dll (deflated 49%)
... zipping:   adding: Framework.Alexa.deps.json (deflated 71%)
... zipping:   adding: Framework.Alexa.dll (deflated 59%)
... zipping:   adding: Framework.Alexa.pdb (deflated 51%)
... zipping:   adding: Framework.Alexa.runtimeconfig.json (deflated 23%)
... zipping:   adding: Newtonsoft.Json.dll (deflated 62%)
Created publish archive (/Volumes/Data/projects/alexa/bin/Release/netcoreapp2.1/alexa.zip).
Error retrieving configuration for function MySampleAlexa: The operation was canceled.`

**Comment by normj** [comment]
The `The operation was canceled.` error message implies some sort of connectivity issue reaching AWS. Is there anything special with your network connection?

**Comment by eat-sleep-code** [comment]
@normj Nothing special with my network.    I use Cox cable, with 8ms ping, 5.8ms jitter, 218Mbps down and 10.1Mbps up (Cox limits upload to around 10Mbps for all plans).   Is there a particular test I can do to test connectivity to AWS?

**Comment by eat-sleep-code** [comment]
@normj Executing **dotnet lambda list-functions** from the root of my user directory (vs from my project folder) gets me slightly different behavior.   Is _us-west-2_ not the appropriate region name?   


```
Amazon Lambda Tools for .NET Core applications (3.2.3)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
Enter AWS Region: (The region to connect to AWS services, if not set region will be detected from the environment.)
us-west-2
Error listing Lambda functions: Host is down
```

**Comment by eat-sleep-code** [comment]
@normj I tried this on a PC, on a completely different network and network provider (this time CenturyLink).

- I installed the current version of .NET Core
- I installed the current version of VS Code
- I executed: dotnet tool install --global Amazon.Lambda.Tools --version 3.2.3
- I downloaded and extracted a copy of my code from my private Git repo.
- I restarted the computer.
- I executed dotnet-lambda dotnet-function

I get this error at the end: **A socket operation was attempted to an unreachable network**

So there does indeed appear to be a connectivity issue, but it is either an issue with the project code or on the AWS end, not with my network (as two disparate networks, two disparate network providers, and two disparate computers and OS's were used).

**Comment by normj** [comment]
I wonder if `dotnet lambda deploy-function` is not resolving to us-west-2 like you are trying to do. Would it be possible to use [Fiddler](https://www.telerik.com/fiddler) to see the failed request and add to the issue the RAW request.

**Comment by eat-sleep-code** [comment]
@normj Here is the RAW request and response:

> GET http://169.254.169.254/latest/meta-data/iam/security-credentials HTTP/1.1
> Host: 169.254.169.254
> 
> HTTP/1.1 502 Fiddler - Connection Failed
> Date: Tue, 16 Jul 2019 00:55:01 GMT
> Content-Type: text/html; charset=UTF-8
> Connection: close
> Cache-Control: no-cache, must-revalidate
> Timestamp: 17:55:01.010

[Fiddler] The connection to '169.254.169.254' failed. <br />Error: NetworkUnreachable (0x2743). <br />System.Net.Sockets.SocketException A socket operation was attempted to an unreachable network 169.254.169.254:80    

Why is there a 169.254.x address?  In fact why would there be an IP address at all?  Shouldn't there be a FQDN in the request URL?

**Comment by klaytaybai** [comment]
Based on your reproduction steps and this request, I'm guessing you haven't set up your AWS credentials properly.  As a last step, it will try to check for IAM credentials from EC2 metadata, which would explain the connection error.

https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html
https://docs.aws.amazon.com/powershell/latest/userguide/specifying-your-aws-credentials.html

**Comment by eat-sleep-code** [comment]
@klaytaybai @normj  It actually appears to have been an issue with my setup.   I had an ~/.aws/config file which was conflicting with the _aws-lambda-tools-defaults.json_ file.   I removed the config file and now it is working.   Wow, that was 4 days of fighting with it for an extra file.   *smack my head* 

Maybe build-output should indicate where it is pulling in the info?   That would have at least pointed us the right direction soon?  

The errors about "socket operation", "host down", etc. also added more confusion and probably could be clarified with the build process.
