### ISSUE TITLE
Defining a user secrets ID element in csproj result in no function handler in mock test tool

### ISSUE THREAD

**Issue by stevieTheCoder** [aws/aws-lambda-dotnet#494]
When adding `<UserSecretsId></UserSecretsId>` element to property group of csproj file the mock test tool does not display the function handler under the function drop down. We want to use a configuration builder to add user secrets

Scenario
Create a Lambda Function empty project
Add a user secret id element
Run mock lambda test tool
No function handler available in drop down
Unable to execute function

Following is called from FunctionHandler

  

        public void BuildConfiguration()
        {
            _environmentName = Environment.GetEnvironmentVariable(Constants.EnvironmentVariables.AspnetCoreEnvironment)
                               ?? Constants.Environments.Production;

            var configurationBuilder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{_environmentName}.json")
                .AddEnvironmentVariables();

            if (_environmentName == Constants.Environments.Development)
            {
                configurationBuilder.AddUserSecrets<Function>();
            }

            _configuration = configurationBuilder.Build();
        }

Further info:
1.15.2.0 AWS toolkit
dotnetcore2.2
Solution platform x64 due to reliance on crappy DB2 package

**Comment by normj** [comment]
You say you are using dotnetcore2.2, are you using the Custom Runtime template? I ask that because Lambda natively supports .NET Core 2.1 and the Lambda test tool doesn't support Custom Runtimes.

**Comment by stevieTheCoder** [comment]
Not using the custom run-time template but appears issue is linked. We are doing some testing with dotnetcore2.2 locally.  

Downgrading everything to .Net Core 2.1 and pointing "workingDirectory": ".\\bin\\x64\\Debug\\netcoreapp2.2" back to ..\netcoreapp2.1 resolves the issue.

Many thanks for clarifying.
