### ISSUE TITLE
APIGatewayProxyRequest parameter is not populated with LambdaTestTool

### ISSUE THREAD

**Issue by madmox** [aws/aws-lambda-dotnet#495]
I just discovered that the AWS toolkit for Visual Studio 2019 includes a version of LambdaTestTool. I wanted to check with the default samples, so I generated a blank AWS serverless project, and pressed F5. LambdaTestTool's web view opens and detects my project settings correctly (region & function are populated). If I submit a request I can even step throught the code using the debugger. Great!

A problem though: the `request` parameter of the function (`APIGatewayProxyRequest`) isn't populated... all properties have their default values (null / false). If I change my function declaration to a POST and submit a request with some JSON content (example "hello world" request), the body is `null`. That's a problem!

* AWS toolkit version: 3.2.3
* Lambda test tool version: 0.9.3
* OS : Windows 10
* dotnet core version: 2.1

**Comment by normj** [comment]
Can you add a copy of the example request you are trying to get work to the issue?

**Comment by madmox** [comment]
I'm just trying to get the default "AWS serverless application" project template to work with LambdaTestTool. This is what I did:
* Open Visual Studio 2019.
* Select "create a new project".
* Select the "AWS serverless application" project template (C#, without tests).
* Select the "empty serverless application" blueprint.
* Save the sln solution file (using the "save all" button).
* Restore nuget packages (packet manager console -> `dotnet restore`).
* Close the solution and reopen it.
* Put a breakpoint in the `Functions.Get` method (before the `return` satement).
* Press F5. This lauched the LambdaTestTool GUI in my browser.
* Select the "Hello World" example request.
* Click the "Execute Function" button in the GUI. This launched my function and hit the breakpoint.
* Inspect the `request` variable from Visual Studio debugger's quick watch.

The variable contains only default values (`null` & `false` values) on all properties. This should not be the case, at the very least the `HttpMethod` property should be `GET`, `body` should contain the example JSON (even though the lambda is bound to a GET, I suspect LambdaTestTool's mock context doesn't care about this), the `Headers` collection should not be `null`... well, I should get some actual values.

**Comment by webMan1** [comment]
Any solution for this? It looks to me like it's just not made to test API gateway requests. If I swap out `APIGatewayProxyRequest` for the model I need to deserialize from `Body` it deserializes and populates it properly, which is great, but is just inconsistent with what we see when in production with an API gateway.

Obviously, if we only care about the body we can just submit 

`{ "Body": "<model json here>"}`

but it would be nice to have all the request properties without having to put them all in the request manually...

**Comment by JBarron333** [comment]
Did you ever discover an answer for this?  I’ve hit exactly the same issue

**Comment by madmox** [comment]
I have given up on using `LambdaTestTool` for testing, since it's possible to use classic ASP.NET Core unit/integration testing with `Amazon.Lambda.AspNetCoreServer`, and `LambdaTestTool` does not add any meaningful value to our project.

However, if you really want to use the tool to test an API gateway proxy request, I realized later that `LambdaTestTool` expects you to put the whole `APIGatewayProxyRequest` object as JSON, not just the request body. So you just need to initialize your test request from the `aws-proxy` request example intead of the `hello-world` example.

**Comment by ashishdhingra** [comment]
Hi @madmox, 

Based on your last comment, please confirm if we are good to close this issue.

Thanks,
Ashish

**Comment by madmox** [comment]
Yep.
