### ISSUE TITLE
Having error Process exited before completing request

### ISSUE THREAD

**Issue by AnushaReddy1998** [aws/aws-lambda-dotnet#498]
I'm starting with AWS Lambda and I'm trying to do a very simple code where i invoke the lambda function using c#.net for storing data into dynamo db but is not working some times when i want to store large data.I tried by increasing the memory size of lambda function but it's not working.

Here is the exception i got ,
{
 "error Message": "Request Id: xxxxxxxxxxxxxxxxxxxxxx Process exited before completing request"
}

**Comment by msimpsonnz** [comment]
Can you share your code and Lambda config settings? What is the Lambda Timeout set at?

**Comment by AnushaReddy1998** [comment]
here is the code i used

    InvokeRequest ir = new InvokeRequest
            {
                FunctionName = "testRequest",
                InvocationType = InvocationType.RequestResponse,
                Payload = JsonConvert.SerializeObject(Reportlist)
            };
            InvokeResponse response = await client.InvokeAsync(ir);

            var sr = new StreamReader(response.Payload);
            JsonReader reader = new JsonTextReader(sr);
            var serilizer = new JsonSerializer();
            var op = serilizer.Deserialize(reader);
            if (op!=null && op is string)
            {

            }
            else
            {
                Mainform.SimpleLogger.Error( op.ToString());
            }

And the Lambda Timeout set at 15 minutes
And memory set at 1024 mb
Please let me know if you want any other details.

**Comment by msimpsonnz** [comment]
You probably don’t want to use InvokeRequest. Check out the Lambda Templates, there is a full solution for Dynamo in the templates there and that will give you a working solution to try
https://docs.aws.amazon.com/lambda/latest/dg/lambda-dotnet-coreclr-deployment-package.html

**Comment by klaytaybai** [comment]
Hello @AnushaReddy1998, this error isn't due to the code invoking your Lambda.  Unless your Lambda function's memory consumption is exceeding the 1024 mb, there is some kind of bug in your Lambda code.  For some reason, it is not returning a response--probably because there is an unhandled exception.

**Comment by AnushaReddy1998** [comment]
@klaytaybai , here is the lambda code  i used.I'm trying to store 30 records at a time, after 2 sec again next 30 records will store.

    public async Task<String> SaveReport(List<ReportJson> Reports, ILambdaContext context)      
     {
            using (client = new AmazonDynamoDBClient())
            {
                using (DBContext = new DynamoDBContext(client))
                {
                    if (Reports == null || Reports.Count == 0)
                    {
                        return "No Data found";
                    }
                    var temp = 0;
                    for (int i = 0; temp <= Reports.Count; i++)
                    {
                        System.Threading.Thread.Sleep(2000);
                        IEnumerable<ReportJson> reports = Reports.Skip<ReportJson>(temp).Take<ReportJson>(30);
                        if (reports!= null && reports.Count() > 0)
                        {
                            var reportbatch = DBContext.CreateBatchWrite<ReportJson>();
                            reportbatch.AddPutItems(reports);
                            await reportbatch.ExecuteAsync();
                        }
                        temp += 30;
                    }
                 }
              }
      }

I checked the logs in cloud watch of lambda function,this exception i found when Lambda function's memory consumption exceeding 1024 mb or maximum  1024 mb is used.

**Comment by msimpsonnz** [comment]
You should move the Dynamo Client initialisation outside of the function. These shouldn’t need to be disposed in the scope of the Lambda execution.
See this example
https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/Msbuild-NETCore_2_1/DynamoDBBlogAPI/template/src/BlueprintBaseName.1/Functions.cs

How large is the payload you are sending? Could you batch it client side and send 1 batch per Lambda call?

**Comment by klaytaybai** [comment]
@msimpsonnz's advice sounds appropriate.  Try giving that a shot. If you are still having difficulty please consider opening a case with Premium Support.  This doesn't seem likely to be an issue with the .NET SDK, so this isn't the appropriate channel for further support on this issue.
