### ISSUE TITLE
Getting package restore failures from Visual Studio 2015 serverless templates.  Yo Works.

### ISSUE THREAD

**Issue by oldnerd** [aws/aws-lambda-dotnet#5]
Getting package restore failures on new serverless solutions deployed from visual studio 2015.

error: Unable to resolve 'Amazon.Lambda.Core (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'Amazon.Lambda.TestUtilities (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'xunit (>= 2.1.0)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'dotnet-test-xunit (>= 2.2.0)' for '.NETCoreApp,Version=v1.0'.

Generating same projects from Yo and using command line build tools works.

**Comment by normj** [comment]
I assume the problem goes away in Visual Studio when you right click on the references and select "Restore Packages". Visual Studio does an initial restore when you create a project but only using a local static cache of NuGet packages that it installs and does pull packages from remotes like NuGet.org. 

We are investigating if there is a way to force Visual Studio to do a restore using remotes.

**Comment by timheuer** [comment]
Confirm restore works for me.

**Comment by oldnerd** [comment]
Doing a restore from vstudio did not.  Doing g one from command line in
project direct Ory did, I assume because I didn't run it with the command
line specifying use of on disk cache only.

Sorry for the false alarm.

**Comment by normj** [comment]
Cool. I'm going to close this for now. I'm hoping with the switch to msbuild coming the initial restore process in Visual Studio will be less flaky.

**Comment by winzig** [comment]
I also was getting this error, tried the right-click Restore in VS 2015, and it still failed. Via the VS command prompt, I was able to get it restored properly with "dotnet restore" command. FYI.
