### ISSUE TITLE
Error using dotnet lambda commands

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#50]
Hello AWS,

When trying to run command like `dotnet lambda list-functions`, it will ask for region and saying that if not set it will detect the region from environment. However, if not entering anything it will generate an error saying `Value cannot be null`, instead of detecting the already set region in aws config file.

<img width="732" alt="error screen shot" src="https://cloud.githubusercontent.com/assets/18595104/22494858/3e014dc6-e809-11e6-9ac9-18e845ad9501.png">

Also, it won't display any character user has entered until the user hits `enter`.

**Comment by normj** [comment]
Thanks for reporting. I'll take a look

**Comment by MZhoume** [comment]
@normj After further inspection, the `dotnet lambda` command do read region specified in `aws-lambda-tools-defaults.json` file. It would be better if it can also read `~/.aws/config` file if no region was specified in that project based json file.

**Comment by MZhoume** [comment]
@normj I don't really know if it is a bug on the `dotnet` cli part, but it would be better if it would display what a user has entered immediately instead of showing them after `enter` key has been hit. (E.g. when it ask user for function name, or to specify a region)

**Comment by normj** [comment]
Not echoing as you type is an issue with the dotnet CLI on nonwindows platforms. I need to spend some time to see if there is a workaround we can do.

**Comment by MZhoume** [comment]
@normj Great! Thanks for this amazing tool again ;)

**Comment by normj** [comment]
I pushed out version `1.2.0-preview1` of `Amazon.Lambda.Tools` that reworked how region is picked to fix this issue. Check the [release notes](https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md) on the change.

**Comment by MZhoume** [comment]
@normj Thanks for the prompt fix ;)

However, it gives a different error when typing nothing into the `Enter AWS Region:` instruction.

<img width="731" alt="screen shot 2017-02-10 at 8 48 45 am" src="https://cloud.githubusercontent.com/assets/18595104/22828958/f7a19e3c-ef6d-11e6-84e4-3e9b7f9ee56f.png">

**Comment by normj** [comment]
Do you have the AWS_REGION environment set or are you running on an EC2 instance? That is the expected error message after the tool has exhausted all possibilities to determine the region.

**Comment by MZhoume** [comment]
@normj I am running on my local machine. And I don't have any environment variable set. I was expecting it would determine the configured default region in `~/.aws/config` using the command `aws configure`.

**Comment by normj** [comment]
Ah, currently the .NET SDK does not currently read the ~/.aws/config file. We are doing some work to the SDK to improve that support. The work we have coming out soon will pull the region from the ~/.aws/config from the default profile as part of its region fallback logic. Will that work for you when it comes out?

**Comment by MZhoume** [comment]
@normj Sweet! That meets my need perfectly! Can't wait for it to come out ;)

**Comment by normj** [comment]
The new version of the AWSSDK.Core came out with this support and version 1.4.0 of Amazon.Lambda.Tools is updated to use the SDK runtime.

**Comment by MZhoume** [comment]
@normj thank you so much for the fix ;)
