### ISSUE TITLE
Changing the serializer settings used by the lambda JsonSerializer

### ISSUE THREAD

**Issue by mabead** [aws/aws-lambda-dotnet#500]
As documented [here](https://docs.aws.amazon.com/lambda/latest/dg/dotnet-programming-model-handler-types.html#lambda-dotnet-add-serializer), the `Amazon.Lambda.Serialization.Json.JsonSerializer` is based on Newtonsoft's JSON.Net. To define our serialization settings, we typically use the procedure described [here](https://www.newtonsoft.com/json/help/html/DefaultSettings.htm). For example, we often have something in our programs initialization code to make sure that the `enum` are serialized as strings and not as integers:

```csharp
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    Converters = new List<JsonConverter>
    {
        new StringEnumConverter() { CamelCaseText = false }
    }
};
```
Unfortunately, it looks like the JsonSerializer provided by AWS does not use the default conversion settings. For example, let's consider the following code:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.Lambda.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace TestToolTrial
{
    public enum Direction
    {
        Up,
        Down,
    }

    public class SomeResult
    {
        public string Text { get; set; }
        public Direction Direction { get; set; }
    }


    public class Function
    {
        public Function()
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                Converters = new List<JsonConverter>
                {
                    new StringEnumConverter() { CamelCaseText = false }
                }
            };
        }

        public SomeResult FunctionHandler(ILambdaContext context)
        {
            var result = new SomeResult
            {
                Text = "Hello",
                Direction = Direction.Down,
            };

            var resultAsString = JsonConvert.SerializeObject(result);
            Console.WriteLine("Result as string is : " + resultAsString);

            return result;
        }
    }
}
```
When I deploy this lambda and invoke it from the AWS console (or if I use it with the Lambda Test Tool), I see that the lambda returns this:
```json
{
  "Text": "Hello",
  "Direction": 1
}
```
As you can see, my `Direction` enum is not serialized as a string. 
But when I look in CloudWatch to see the output of `Console.WriteLine`, I see this: `Result as string is : {"Text":"Hello","Direction":"Down"}`. This is what I expected.

So my question is: 
How can we change the serializer settings used by the `Amazon.Lambda.Serialization.Json.JsonSerializer`?

**Comment by mabead** [comment]
Note that it's not only the `Converters` that we try to set by default. We also want to set the:
- ContractResolver
- DatetimeZoneHandling
- TypeNameHandling
- NullValueHandling
- etc

We therefore can't use [this](https://github.com/aws/aws-lambda-dotnet/blob/e66185877623f4c518e7632c460cdf4a3e7795ae/Libraries/src/Amazon.Lambda.Serialization.Json/JsonSerializer.cs#L42) constructor. 

What would be ideal would be to be able to subclass the `JsonSerializer` and use a constructor that would look like this:

```csharp
public JsonSerializer(Action<JsonSerializerSettings> customizeSerializerSettings) 
{
    JsonSerializerSettings settings = new JsonSerializerSettings();
    settings.ContractResolver = new AwsResolver();
    customizeSerializerSettings(settings); 
    // ...
}
```

That way, we would be able to easily customize the serializer settings.

What do you think?

**Comment by normj** [comment]
I would take PR for adding this constructor.

**Comment by mabead** [comment]
@normj The PR is available here https://github.com/aws/aws-lambda-dotnet/pull/503.

**Comment by normj** [comment]
Version 1.6.0 of Amazon.Lambda.Serialization.Json is out with the PR. Thanks for the PR!
