### ISSUE TITLE
The variable '$pathToInstallationChecks' cannot be retrieved because it has not been set.

### ISSUE THREAD

**Issue by dreams3290** [aws/aws-lambda-dotnet#501]
I am trying to publish a powershell core script which leverages couple of az modules to lambda function.  This a small two liner script which runs fine in my local but when published to lambda, getting run time error. Below is the error . Any idea why this is happening?

{
  "errorType": "LambdaException",
  "errorMessage": "An exception was thrown when the constructor for type 'functionName.Bootstrap' was invoked. Check inner exception for more details.",
  "cause": {
    "errorType": "TargetInvocationException",
    "errorMessage": "Exception has been thrown by the target of an invocation.",
    "stackTrace": [
      "at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)",
      "at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)"
    ],
    "cause": {
      "errorType": "RuntimeException",
      **"errorMessage": "The variable '$pathToInstallationChecks' cannot be retrieved because it has not been set.",**
      "stackTrace": [
        "at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost..ctor()",
        "at functionName.Bootstrap..ctor() in path\\Bootstrap.cs:line 7"
      ]
    }
  }
}

**Comment by klaytaybai** [comment]
Hi @dreams3290, this doesn't seem to have anything to do with AWS.  The $pathToInstallationChecks variable is used by the Azure modules that you are trying to use.  If you're seeing this error, I suggest attempting to set this variable to an installation path yourself in your script.
