### ISSUE TITLE
Change the JsonConvert.DefaultSettings ContractResolver to use CamelCasePropertyNamesContractResolve in AWS Lambda using .NET SDK 

### ISSUE THREAD

**Issue by luizgustavogp** [aws/aws-lambda-dotnet#502]
The AWS Lambda.NET SDK use Json.NET for serialization by default. I'd like to change the ContractResolver to use CamelCasePropertyNamesContractResolver like this.

I tried to do it in the Lambda Contructor: 
 
```C#
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver()
                };
```

But the configuration was not applied. I don´t like to modify my Model classes. I want to modify it in the serialization time.

**Expected Behavior**
The JSON result returned by my Lambda was like that:
```JSON
{
  "id": "a1bd0b39-6823-4208-a1ca-4151665241aa",
  "color": "Black",
  "message": "Hello"
}
```
**Current Behavior**
The JSON result returned by my Lambda is:
```JSON
{
  "Id": "a1bd0b39-6823-4208-a1ca-4151665241aa",
  "Color": "Black",
  "Message": "Hello"
}
```
**Steps to Reproduce (for bugs)**
Create a new .NET Lambda and put in the constructor the following setting:

```C#
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver()
                };
```

**.NET Core Info**

* .NET Core version used for development: 2.1 
* .NET Core version installed in the environment where application runs: 2.1

**StackOverflow Question:**

[Link](https://stackoverflow.com/questions/57431991/change-the-jsonconvert-defaultsettings-contractresolver-to-use-camelcaseproperty)

**Comment by ashishdhingra** [comment]
Hi @luizgustavogp,

Good morning.

I was going through backlog and came across this issue. Could you please refer https://stackoverflow.com/questions/54209781/custom-serializer-settings and confirm if it works?

Thanks,
Ashish
