### ISSUE TITLE
Publish-AWSPowerShellLambda error calling AssumeRole

### ISSUE THREAD

**Issue by pandaedward** [aws/aws-lambda-dotnet#505]
Hi team,

We use ```Publish-AWSPowerShellLambda``` to package up and deploy Powershell lambda function using cross-role mechanism. 

A simple deploy using the below command:

`Publish-AWSPowerShellLambda -ScriptPath ./kube-deploy.ps1 -Name pwsh-kube-deploy  -IAMRoleArn arn:aws:iam::123456789012:role/lambda-exe-role -Region ap-southeast-2 -ProfileName profile-one`

But the command always fail at assuming the role:

```
Created publish archive (/Users/xyz/projects/pwsh-deploy-lambda/kube-deploy/kube-deploy/bin/Release/netcoreapp2.1/kube-deploy.zip).
Error retrieving configuration for function pwsh-kube-deploy: Error calling AssumeRole for role arn:aws:iam::123456789012:role/Organisation-role
Error publishing PowerShell Lambda Function: 255
CALLSTACK:
Command                     Arguments                                                                                                                                    Location
-------                     ---------                                                                                                                                    --------
_deployProject              {{PowerShellFunctionHandler=$null}, {PowerShellFunctionHandler=$null}, {PowerShellFunctionHandler=$null}, {PowerShellFunctionHandler=$null}} _DeploymentFunctions.ps1: line 192
Publish-AWSPowerShellLambda {{StagingDirectory=./$null}, {StagingDirectory=./$null}, {StagingDirectory=./$null}, {StagingDirectory=./$null}…}                            Publish-AWSPowerShellLambda.ps1: line 326
<ScriptBlock>               {{=$null}, {=$null}, {=$null}, {=$null}}                                                                                                     <No file>
At /Users/xyz/.local/share/powershell/Modules/AWSLambdaPSCore/1.2.0.0/Private/_DeploymentFunctions.ps1:194 char:13
+             throw $msg
+             ~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Error publishing Po\u2026        <No file>
:String) [], RuntimeException
+ FullyQualifiedErrorId : Error publishing PowerShell Lambda Function: 255
CALLSTACK:
Command                     Arguments                                                                                                                                    Location
-------                     ---------                                                                                                                                    --------
_deployProject              {{PowerShellFunctionHandler=$null}, {PowerShellFunctionHandler=$null}, {PowerShellFunctionHandler=$null}, {PowerShellFunctionHandler=$null}} _DeploymentFunctions.ps1: line 192
Publish-AWSPowerShellLambda {{StagingDirectory=./$null}, {StagingDirectory=./$null}, {StagingDirectory=./$null}, {StagingDirectory=./$null}…}                            Publish-AWSPowerShellLambda.ps1: line 326
<ScriptBlock>               {{=$null}, {=$null}, {=$null}, {=$null}}                                                                                                     <No file>
```

I can confirm that `default` and `profile-one` AWS profile is in place and I have been passing `-ProfileName` no problem with other cmdlet e.g. `Get-EC2Instance`

**Comment by Yottster** [comment]
Ran in to that same error when we started to require MFA for a role.
If thats the case for you as well, you will need to add 
`mfa_serial = arn:aws:iam::[account]:mfa/[username]` to your profile.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-mfa

This would mean that `Get-EC2Instance` shouldnt work for you right now as well though.

**Comment by normj** [comment]
@pandaedward Are you using MFA with your Assume role as well. I have a [PR](https://github.com/aws/aws-extensions-for-dotnet-cli/pull/80) for the underlying .NET Core Global Tool that the publish cmdlet uses. The PR is ready to go out I just need to do the actual release.

**Comment by pandaedward** [comment]
@Yottster I've already have mfa_serial in the profile. The profile is working well for my bash aws-cli command, just not the powershell version it. 

@normj Good to hear that there is a PR! For now the work around is setting the profile with ```Set-AWSCredential -ProfileName virtual_migration``` before publishing

**Comment by jltjohanlindqvist** [comment]
@normj has there been any progress with adding support for MFA in the .NET Core Global tool? Would be really nice to have!
