### ISSUE TITLE
Specification of stage

### ISSUE THREAD

**Issue by FrederikNygaardSvendsen** [aws/aws-lambda-dotnet#51]
Hello guys

**Regarding serverless AspNetCoreWebAPI on lambda:**
How do i specify which stages should be created for the API Gateway? It seems the "Prod" and "Stage" stages are generated by default. We would like to create an entire stack for our Dev, Test and Prod environment, and it would be neat if those only contained that specific stage (eg. Dev stage for our Dev environment/stack)

I assume this needs to be configured somehow through the serverless.template?

Thanks in advance

**Comment by normj** [comment]
It sounds like what you would like is to define Prod, Test and Dev stages and have .NET Core tooling deploy to the dev stage and then you would have your process of when to promote the function to the other stages. Does that sound about right what you are wanting?

The serverless.template is a CloudFormation template that uses the [AWS Serverless Application Model](https://github.com/awslabs/serverless-application-model) to transform the AWS::Serverless::* resources into the more basic [CloudFormation resources](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html).

With the current AWS Serverless Transformations you can not do what you are asking with also using our Lambda tools. I think you would need to write your own swagger definition and upload that to S3, then package up your code and do your own CloudFormation deployment. I know the AWS Serverless team is working on expanding on you can do with the AWS Serverless Application transform. So this might be something they add in the future.

The other option is to not use the transform and use the CloudFormation resources directly. If you deploy the blueprint now and then look in the Stack View -> Template tab you can see how those serverless resources are expanded out. In that case one of the resources you would use is `AWS::Lambda::Function` to define the function and where the code is. Our .NET Core tooling does not currently update the `Code` property for Lambda functions like it does for `AWS::Serverless::Function` but if this is something you are interested in I can update the tooling to update that field as well.
