### ISSUE TITLE
Use Amazon.Lambda.Logging.AspNetCore with TestLambdaLogger

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-lambda-dotnet#510]
I have a Lambda function that I'd like to use with .NET's built i8n logging framework. Here is my logging setup code:

```
services.AddLogging(builder =>
{
	var options = new LambdaLoggerOptions()
	{
		IncludeLogLevel = true,
		IncludeException = true,
		IncludeEventId = true
	};

	options.Filter = (category, logLevel) =>
	{
		if (string.Equals(category, "Microsoft", StringComparison.Ordinal))
		{
			return (logLevel >= LogLevel.Warning);
		}

		return true;
	};

	builder.AddLambdaLogger(options);
});
```

I would also like to be able to log messages when running a local integration test. In my integration test, I am creating a `TestLambdaContext` instance from the `Amazon.Lambda.TestUtilities` package. This instance comes with a `TestLambdaLogger` instance for it's `Logger` property.

I can see that the `Amazon.Lambda.Logging.AspNetCore` package uses the static `LambdaLogger` class for it's logging - https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore/LambdaILogger.cs. This means my test context and logger are useless. Is tehre a way to use these two packages together so I can get logging working locally?

**Comment by martincostello** [comment]
I just stumbled across this issue, here’s a commit to a lambda of my own where I wire up the logging to xunit for tests: https://github.com/martincostello/alexa-london-travel/commit/cb729ffc665197111b86504ce01f0aaba358e864

**Comment by ashishdhingra** [comment]
Hi @andyfurniss4, 

Please confirm if you were able to make your scenario work using input by @martincostello and if this issue could be closed.

Thanks,
Ashish
