### ISSUE TITLE
SendFileAsync is not implemented for Serverless ASP.NET Core functions

### ISSUE THREAD

**Issue by arndklocker** [aws/aws-lambda-dotnet#511]
We want to use client side blazor with aws lambda, but we get the following Exception "NotImplementedException: SendFileAsync is not implemented for Serverless ASP.NET Core functions". It seem there is a problem for all static files (e.g. css files, images, …)

`Amazon.Lambda.AspNetCoreServer.Internal.InvokeFeatures.Microsoft.AspNetCore.Http.Features.IHttpResponseBodyFeature.SendFileAsync(string path, long offset, Nullable<long> count, CancellationToken cancellationToken)`

**Comment by arndklocker** [comment]
Yes this bug ist in .NET Core 3.0.
If you request any static file from the 'wwwroot' directory (e.g. lib/jquery/dist/jquery.js), ASP.NET Core triggers SendFileAsync.

**Comment by normj** [comment]
Support for SendFileAsync was released as a part of version 4.0.0 of Amazon.Lambda.AspNetCoreServer.
