### ISSUE TITLE
Logging LogLevel should be handled as namespace prefix

### ISSUE THREAD

**Issue by wdolek** [aws/aws-lambda-dotnet#519]
It is common to use typed `ILogger<T>` in .NET - this will produce category which equals to full type name, so for example `ILogger<HttpClient>` has category `System.Net.Http.HttpClient`.

Usually, this should be enough to have `Debug` level for `HttpClient`:

```javascript
    "LogLevel": {
      "Microsoft": "Information",
      "System": "Warning",
      "System.Net": "Information",
      "System.Net.Http": "Debug"
    }
```

Yet in order to make this work, wildcards must be used like this:

```javascript
    "LogLevel": {
      "Microsoft.*": "Information",
      "System.*": "Warning",
      "System.Net.*": "Information",
      "System.Net.Http.*": "Debug"
    }
```

I spent quite a lot of time debugging my configuration not realizing this. In addition to wildcards, I propose adding simple support of namespace prefixes as well, which is common in .NET.

Framework documentation: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1).

**Comment by normj** [comment]
PR merged and released
