### ISSUE TITLE
template-parameters only recognizing the first parameter

### ISSUE THREAD

**Issue by Artin-ST** [aws/aws-lambda-dotnet#524]
I'm using the following command to deploy a .net core serverless lambda function.  Instead of using aws-lambda-tools-defaults.json I'm passing in all the values to the command. however I'm having an issue with the template paramters.  For some reason only the first paramter is being recognized, not sure what I'm doing wrong here.

```shell
dotnet lambda deploy-serverless \
	--region ca-central-1 \
	--stack-name Dev-Application \
	--s3-bucket dev-deploy \
	--s3-prefix Dev-Application \
	--template Application.yaml \
	--template-parameters Environment=Dev;CognitoStackName=Dev-Cognito;DataStackName=Dev-Data
```

I get the following error

> Template Parameters Applied:
	Environment: Dev
Error creating CloudFormation change set: Parameters: [DataStackName, CognitoStackName] must have values

Regards
Artin

**Comment by Artin-ST** [comment]
Worked with AWS support to try and figure this out. The following worked.

```shell
dotnet lambda deploy-serverless \
	--region ca-central-1 \
	--stack-name Dev-Application \
	--s3-bucket dev-deploy \
	--s3-prefix Dev-Application \
	--template Application.yaml \
	--template-parameters 'Environment=Dev;CognitoStackName=Dev-Cognito;DataStackName=Dev-Data'
```
Not sure what the quotes were required as its not in the help text.

`
 -tp    | --template-parameters          CloudFormation template parameters. Format is <key1>=<value1>;<key2>=<value2>
`
I'm curious if anyone knows the reason for needing the quote.

**Comment by Kralizek** [comment]
Which console are you using?

**Comment by Artin-ST** [comment]
Sorry, should have mentioned that in my original post.

macOS Terminal.

**Comment by chrisoverzero** [comment]
macOS Terminal.app is bash (or in particularly newer versions, zsh), and in bash, the semicolon is the statement separator. The first version of your command is indeed ending with only one template parameter set. Then it’s setting an environment variable `CognitoStackName` to a value for the scope of a command, running no command, and dropping the variable value. It does it again for `DataStackName`. 

There’s neither bug nor workaround here – quoting the value is required. 

(I once ran into the same problem with `curl` and a URL with a semicolon in it. I will never get those hours of my life back. 😜)

**Comment by dwilsonbst** [comment]
I have a similar problem, is there a proper syntax for escaping the semicolons to be used as a literal value instead of seperator?
Example "param1=this;param2=this;that" where "this;that" requires a literal semicolon.

**Comment by andrewlangemann** [comment]
> I have a similar problem, is there a proper syntax for escaping the semicolons to be used as a literal value instead of seperator?
> Example "param1=this;param2=this;that" where "this;that" requires a literal semicolon.

@dwilsonbst I am also having the same issue - did you figure out a solution?

**Comment by andrewlangemann** [comment]
> I have a similar problem, is there a proper syntax for escaping the semicolons to be used as a literal value instead of seperator?
> Example "param1=this;param2=this;that" where "this;that" requires a literal semicolon.

@dwilsonbst I figured out a solution by looking at the code in [aws-extensions-for-dotnet-cli](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/d32048587fcbac721e183dcb260d3f6868cabfc6/src/Amazon.Common.DotNetCli.Tools/Utilities.cs). You need to do the following:
``"param1=this;param2=\`"this:that\`""``

To escape the quote in PowerShell, you must use a backtick. This will then be processed by C#, which needs the quote escaped using a backslash.

**Comment by dwilsonbst** [comment]
@andrewlangemann yes, we found a way to make this work. We are using bash script so keep in mind any escaping that might be specific here:

` --template-parameters "test=1;ConnectionString=\"user=this;password=that;foo=bar\""`

**Comment by ashishdhingra** [comment]
Hi @Artin-ST,

I see that you worked with AWS Support and the resolution was provided. Please confirm if we could close this issue.

Thanks,
Ashish

**Comment by Artin-ST** [comment]
Yes my issue was resolved, thank you.

**Comment by naresh9949** [comment]
i have tried it, but it is not working

Command :  dotnet lambda deploy-serverless --stack-name qa-ind-example --s3-bucket bucket --template serverless.yml  --template-parameters "test=1;ConnectionString=\"user=this;password=that;foo=bar\""

Error : 

password=that : The term 'password=that' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:239
+ ... parameters "test=1;ConnectionString=\"user=this;password=that;foo=bar ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (password=that:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

foo=bar\ : The term 'foo=bar\' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:253
+ ... ameters "test=1;ConnectionString=\"user=this;password=that;foo=bar\""
+                                                                ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (foo=bar\:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
