### ISSUE TITLE
AWS Serverless Concurrent requests

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#527]
Will it still be true in the future that C# AWS Serverless Applications (that are perfectly capable of handing concurrent Web requests) that a C# Lambda Instances will only handle a single request at a time.

As our Lambda based AWS Serverless websites grow, the number of requests grow. At the point where the either the ramp up (i.e. a sudden increase in requests) or the overall volume exceeds the maximum number of specified lambda instances, subsequent requests are handed a 500 error (which really means an infrastructure resource allocation failure. This is not a graceful response to the users.

Is the current issue of no concurrent calls through a single Lambda instance a result of billing (computing the correct time associated with a Lambda instance) or a technical requirement?

I understand that there is a point at which one may move from AWS Serverless to a fixed cost EC2 solution but workloads, especially on newer sites, is variable.

I am still assessing where Server side Blazor and AWS Lambda might end up.

**Comment by normj** [comment]
Having one event being handled by a single Lambda compute environment at a time is a fundamental design of Lambda and is highly unlikely to change. Also that design is not tied to whether the function is written in .NET or Node.js. That is done at the service dispatching level.

This talk from the Lambda Principal engineers at re:Invent last year is really interesting about how Lambda works under the hood and how it scales. https://www.youtube.com/watch?v=QdzV04T_kec

I'm going to close this here as there is nothing we can change on our end about how events are dispatched.

**Comment by genifycom** [comment]
Thank you for the link Norm. I missed this one somehow.
