### ISSUE TITLE
AWS Lambda and Blazor server side

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#528]
Once we have DotNet 3.0 or 3.1 LTS running in Lambda, how will we we support Server Side Blazor.

In AWS Lambda, WebSockets are not supported and can only be implemented via the WebSocket interface for API gateway.

Since the websocket piece is hidden, then in its current form it will not work.

Will there be any solution for running Server Side Blazor in AWS Lambda?

**Comment by normj** [comment]
That is a good question about Blazor but I don't have the answer. I hope to research that soon and any input would be greatly appreciated.

**Comment by msimpsonnz** [comment]
Server side Blazor uses SignalR under the hood, the client connection state is stored in memory on the server. If the client connection is lost the session would need to be resumed and state would be lost, you could build a SignalR server but this is getting away from the desire for this to be serverless.

**Comment by galvesribeiro** [comment]
Just dropping my 2c. I would say that isn't feasible at all for serverless stacks like lambda. You need the server to keep the state in memory. The only way is if you "serialize" the state on something like Redis and implement a whole set of internal blazor components to get this state from there. I'm not sure Blazor currently would support that case. It goes way being just having the serverless websockets for transport (i.e. SignalR). It is a matter of state management which I believe isn't something modular right now on Blazor...

For serverless blazor, you still have an option for the client-side/webassembly mode (still in preview) which you can host on S3 and then use lambda as a "webApi" for it.

**Comment by ehartford** [comment]
Fargate

**Comment by dharmaturtle** [comment]
To augment the Fargate answer: https://youtu.be/UfPGdYbtDTg?t=2599

Slides: https://d1.awsstatic.com/events/reinvent/2019/REPEAT_1_Developing_serverless_.NET_Core_on_AWS_WIN308-R1.pdf

**Comment by classifieds-dev** [comment]
Expanding on the idea of using a backplane Mass Transit provides a SignalR backplane that can be used as a work-around.

https://masstransit-project.com/advanced/signalr/

I was using that before I moved from containers to serverless suing aws api gateway.

**Comment by classifieds-dev** [comment]
Its probably worth mentioning that using containers with an application load balancer is going to be far more expensive than using the web socket api gateway with lambda. Even just using the alb with lambda targets will be more expensive.
