### ISSUE TITLE
Feature Request: Version Status Roadmap

### ISSUE THREAD

**Issue by sliedig** [aws/aws-lambda-dotnet#530]
Feature Request: Include the planned/future runtime support in the Version Status section of the readme.

**Comment by beeradmoore** [comment]
@sliedig , how would this differ from [Version Status](https://github.com/aws/aws-lambda-dotnet#version-status)

**Comment by beeradmoore** [comment]
@sliedig how would this differ from the current Version Status aside from saying 3.1 is planned?

**Comment by sliedig** [comment]
I would be nice to get some estimated timeframes for when the releases are expected to be available, and how AWS is dealing with versions that have reached end of life (ref https://dotnet.microsoft.com/download/dotnet-core), i.e. when you can no longer create new functions for a specific version.

**Comment by ashishdhingra** [comment]
Hi @sliedig,

Good afternoon.

I was going through the backlog and came across this issue. I do not see any activity on this issue for quite long. This doesn't appear to be a feature request. If nothing needs to be done here, kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by sliedig** [comment]
It's no longer a feature request, because you removed the version status table from the readme.

https://github.com/aws/aws-lambda-dotnet/commit/e53cb11a0dc8326f0a29acac1ea780cc4cd83c12#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Not really sure why it was removed. I would have thought this is useful information. Where do users go now to find the details about supported versions and patches?

**Comment by ashishdhingra** [comment]
> It's no longer a feature request, because you removed the version status table from the readme.
> 
> [e53cb11#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5](https://github.com/aws/aws-lambda-dotnet/commit/e53cb11a0dc8326f0a29acac1ea780cc4cd83c12#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
> 
> Not really sure why it was removed. I would have thought this is useful information. Where do users go now to find the details about supported versions and patches?

Hi @sliedig,

Please refer to comment https://github.com/aws/aws-lambda-dotnet/issues/806#issuecomment-777823194, it is related to version table and provides guidance on why it was removed by development team. Kindly review the same and confirm if this issue could be closed.

Thanks,
Ashish
