### ISSUE TITLE
2.1.12 is not supported

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-lambda-dotnet#531]
Hi.

I noticed that the version status table in README.md states that 2.1.12 is supported. I just upgraded and I got an error that 2.1.11 is the latest supported patch.

**Comment by hounddog22030** [comment]
+1

Received this message in Lambda.  Please advise.

It was not possible to find any compatible framework version
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
The specified framework 'Microsoft.AspNetCore.All', version '2.1.12' was not found.
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
- Check application dependencies and target a framework version installed at:
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
/var/lang/bin/
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
- Installing .NET Core prerequisites might help resolve this problem:
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
- The .NET Core framework and SDK can be installed from:
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
https://aka.ms/dotnet-download
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
- The following versions are installed:
2019/09/30/[$LATEST]443deefce6f6441d864fa038c6bfb8ae

02:03:26
2.1.11 at [/var/lang/bin/shared/Microsoft.AspNetCore.All]

**Comment by starkcolin** [comment]
Same, it's hard to believe this issue has been open 25 days with no comment.

**Comment by msimpsonnz** [comment]
.Net Core 2.1 has moved to implicit versioning for the meta packages [see here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1#implicit-versioning)

Are you specifying a version in your code?
Do you have a repro example you can share?

The guidance is also to move to `Microsoft.AspNetCore.App` from `Microsoft.AspNetCore.All` as detailed [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1#update-aspnet-core-21), which could be relevant to @hounddog22030

**Comment by starkcolin** [comment]
Thanks for the reply.  I am aware of the changes to ASP.NET Core but I was under the impression that Lambda still required an explicit version to be set.  I set the project up soon after Lambda support for .NET Core 2.1 came out, and all the documentation at the time indicated that an explicit version was required.
I see now that the csproj file for a serverless ASP.NET Core project created by `dotnet new` does not specify a version, so clearly that is no longer the case (or perhaps never was).
I have confirmed that the deployment works successfully by omitting the version number.

Thanks for your assistance, but regardless, the README should probably still be updated to reflect the actual values.

**Comment by normj** [comment]
Yes the explicit version number is no longer required. 

For those that are curious about the background. When .NET Core 2.1 first came out and you referenced the ASP.NET Core shared framework the .NET Core build would be default set the version in the runtime.config.json file to the latest version installed on the machine doing the bundling. The runtime.config.json is a .NET Core specific file and is included with the package bundle which the .NET Core runtime uses to configure itself. When the version of ASP.NET Core was set to a newer version then Lambda had it would fail with a terrible error message. To avoid the confusion of the terrible error messages we initially required Lambda projects to explicit set a value for the version so we can make sure it was supported in Lambda.

I can't remember which patch version of .NET Core but they changed the packaging process to now set the version of ASP.NET Core in the runtime.config.json to be 2.1.0 unless an explicit version was set. The runtime would always use the latest version that it had. So this removed the need for the Lambda tooling to validate the version number.

**Comment by raRaRa** [comment]
Thanks. I removed the version and upgraded `Amazon.Lambda.Tools` to get this to work.

```dotnet tool update -g Amazon.Lambda.Tools```
