### ISSUE TITLE
How to use custom JSON converters with Lambda function

### ISSUE THREAD

**Issue by tap-andy** [aws/aws-lambda-dotnet#532]
I've created a Lambda function using the VS extension. I want to change my function to serialize enum values as strings. I can see that there are several constructors for the `JsonSerializer` class, one of which allows you to specify custom converters. The problem is, I can't figure out how I'm meant to use these extra constructors.

By default, the scaffolded function code just adds the `LambdaSerializer` attribute to the assembly and I guess this just uses the parameterless constructor. How can I change my function to use a different constructor and give it the necessary enum converter?

**Comment by klaytaybai** [comment]
This [README](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Core) provides a little more info.  You'll need to write your own serializer that implements the ILambdaSerializer interface.  Can you take a look at this documentation, read some more about JSON serializers, and let us know if you are still having issues?
