### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer & ALB. Content-Encoding: gzip

### ISSUE THREAD

**Issue by TommyN** [aws/aws-lambda-dotnet#534]
Hi,

I'm using Amazon.Lambda.AspNetCoreServer with ALB and I'm unsure how I can return gzip'ed content. 

In `startup.cs` I've added 
```
services.AddResponseCompression()
...
app.UseResponseCompression();
```
This works fine when testing locally, but not when I deploy the lambda and hit the ALB endpoint.

According to the documentation ([supporting binary content](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md#supporting-binary-response-content)) it seems a workaround might be to register my content-type as binary, but I'd like to base my response on the incoming `Accept-Encoding` header, and not gzip unless there is a Accept-Encoding: gzip header.

Is this doable?

My setup is:
Cloudfront <-> ALB <-> Lambda (AspNetCoreServer)

It's possible to configure Cloudfront to compress the content, but when I tested this previously, conditional GET requests never returned 304 (Not Modified).

Any advice on how to configure my setup so I can support both gzip and non-gzip content would be greatly appreciated. For now my API is not using any compression.

**Comment by msimpsonnz** [comment]
Are you using HTTPS? Have you seen #355

What content are you compressing? Is this GET or POST?

**Comment by TommyN** [comment]
> Are you using HTTPS? Have you seen #355

I'm currently using HTTP between Cloudfront and the Origin. 
I'll have a look at the issue you referenced.
> What content are you compressing? Is this GET or POST?

It's JSON content and only for GET requests.

**Comment by phillip-haydon** [comment]
When you created your lambda target did you tick multiple header option?

![image](https://user-images.githubusercontent.com/895629/71145582-16eaa200-225d-11ea-91fc-4865d60a3fe6.png)

If this isn't ticked the headers won't be passed back out correctly.

**Comment by chazt3n** [comment]
@TommyN how are you running a lambda which is triggered by an ALB locally?

**Comment by TommyN** [comment]
I just have a plain asp.net core web api app that I've [deployed to AWS Lambda](https://aws.amazon.com/blogs/developer/running-serverless-asp-net-core-web-apis-with-amazon-lambda/). When testing locally I run the asp.net core app under Visual Studio (or dotnet run) and send request using Fiddler.
Not sure if this is what you meant though.

**Comment by chazt3n** [comment]
yes that answers the question thank you, we're just testing with invoke() locally now using SAM

**Comment by ashishdhingra** [comment]
Hi @TommyN,

Good afternoon.

I was going through the issue backlog and came across this guidance question. Please have a look at issue https://github.com/aws/aws-lambda-dotnet/issues/355 and see if it works for you. Thereafter, kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by TommyN** [comment]
I ended up ignoring the Accept-Encoding header and always gzip'ing the response :/ 
#355 will probably work for us. Closing this ticket.
