### ISSUE TITLE
Use Lambda With Application Load Balancer and API Gateway Simultaneously

### ISSUE THREAD

**Issue by richardkeller411** [aws/aws-lambda-dotnet#536]
Should be able to determine by the Context or Request what the type of request is and build Request/Response accordingly.

**Comment by msimpsonnz** [comment]
Or you could have a shared lib with the logic and call that from two separate distinct functions?

**Comment by richardkeller411** [comment]
Seems like it would be easier to abstract in SDK...

https://serverless-training.com/articles/api-gateway-vs-application-load-balancer-technical-details/#how-to-use-lambda-with-application-load-balancer-and-api-gateway-simultaneously

**Comment by normj** [comment]
I choose not to do this because the requests are slightly different which required separate .NET types. They could share a common base type for common fields but if I do that which package would the common base class live. I didn't really like the idea of creating a whole package for for a couple common base types. A downside of creating a type with all the possible properties is I don't know how these different events will grow over time.

If you don't care about type information and are only using the common properties you can always ignore the typed classes and use Newtonsoft's JObject as the request and response. That would make it work closer to the python example using dynamic typing.

**Comment by richardkeller411** [comment]
I can understand that although you already did a bunch of work in the Response objects to "fill in the blanks" between the differences of APIGateway and ALB.   I'll close then not to leave it hanging open

**Comment by clearwaterstream** [comment]
@richardkeller411 @normj Assuming which request is coming over, I'm thinking something like this could work (.NET Core 2.1):

```csharp
public class LambdaEntryPoint
{
	public async Task<Stream> Handler(Stream stream, ILambdaContext context)
	{
		object resp = null;

		// CAN THIS COME FROM ILambdaContext.RequesType please?? (or other means)
		var requestType = "APIGatewayProxyRequest";

		if (requestType == nameof(APIGatewayProxyRequest))
		{
			var req = Deserialize<APIGatewayProxyRequest>(stream);

			resp = await APIGatewayEntryPoint.Instance.FunctionHandlerAsync(req, context);
		}
		else if (requestType == nameof(ApplicationLoadBalancerRequest))
		{
			var req = Deserialize<ApplicationLoadBalancerRequest>(stream);

			resp = await ALBEntryPoint.Instance.FunctionHandlerAsync(req, context);
		}

		var ms = new MemoryStream();

		using (var sw = new StreamWriter(ms, Encoding.UTF8, 1024, true)) // leave ms open...
		{
			using (var jw = new JsonTextWriter(sw))
			{
				var ser = JsonSerializer.Create();

				ser.Serialize(jw, resp);
			}
		}

		ms.Position = 0;

		return ms;
	}

	class APIGatewayEntryPoint : APIGatewayProxyFunction
	{
		public static readonly APIGatewayEntryPoint Instance = new APIGatewayEntryPoint();

		protected override void Init(IWebHostBuilder builder)
		{
			builder.UseStartup<Startup>();
		}
	}

	class ALBEntryPoint : ApplicationLoadBalancerFunction
	{
		public static readonly ALBEntryPoint Instance = new ALBEntryPoint();
		
		protected override void Init(IWebHostBuilder builder)
		{
			builder.UseStartup<Startup>();
		}
	}

	static T Deserialize<T>(Stream stream)
	{
		using (var sr = new StreamReader(stream))
		{
			using (var jr = new JsonTextReader(sr))
			{
				var ser = JsonSerializer.Create();

				return ser.Deserialize<T>(jr);
			}
		}
	}
}
```
This requires some way of knowing of which request is coming over [612](https://github.com/aws/aws-lambda-dotnet/issues/612)

You could also convert json to string, interrogate it, figure out the request type, then continue on with deserialization ...
