### ISSUE TITLE
log4net and postgresql

### ISSUE THREAD

**Issue by rodney-lai** [aws/aws-lambda-dotnet#54]
I'm trying to get a lambda working with log4net and postgresql, but I'm getting an error running the lambda.  If I remove the reference to the postgresql dll, the lambda works.  Runs fine locally on my Windows machine.

```

{
  "errorType": "TypeInitializationException",
  "errorMessage": "The type initializer for 'log4net_test.Function' threw an exception.",
  "stackTrace": [
    "at log4net_test.Function.FunctionHandler(String input, ILambdaContext context)",
    "at lambda_method(Closure , Stream , Stream , ContextInfo )"
  ],
  "cause": {
    "errorType": "TypeInitializationException",
    "errorMessage": "The type initializer for 'log4net.Core.LoggerManager' threw an exception.",
    "stackTrace": [
      "at log4net.Core.LoggerManager.CreateRepository(String repository)",
      "at log4net_test.Function..cctor()"
    ],
    "cause": {
      "errorType": "PlatformNotSupportedException",
      "errorMessage": "Operation is not supported on this platform.",
      "stackTrace": [
        "at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription()",
        "at log4net.Core.LoggerManager.GetVersionInfo()",
        "at log4net.Core.LoggerManager..cctor()"
      ]
    }
  }
}

```

project.json

```

{
  "version": "1.0.0-*",
  "buildOptions": {
  },
  "publishOptions": {
    "include": [
      "log4net.config"
    ]
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Amazon.Lambda.Core": "1.0.0*",
    "Amazon.Lambda.Serialization.Json": "1.0.1",
    "Amazon.Lambda.Tools": {
      "type": "build",
      "version": "1.1.0-preview1"
    },
    "log4net": "2.0.7",
    "System.Diagnostics.TraceSource": "4.0.0",
    "Npgsql.EntityFrameworkCore.PostgreSQL": "1.1.0"
  },

  "tools": {
    "Amazon.Lambda.Tools": "1.1.0-preview1"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

```

```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Amazon.Lambda.Core;
using Amazon.Lambda.Serialization;

using log4net;
using log4net.Config;
using log4net.Repository;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializerAttribute(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace log4net_test
{
    public class Function
    {
      private static readonly ILoggerRepository m_repo = LogManager.CreateRepository("test");
      private static readonly ILog m_log = LogManager.GetLogger("test",typeof(Function));

        public string FunctionHandler(string input, ILambdaContext context)
        {         
            XmlConfigurator.Configure(m_repo,new System.IO.FileInfo("log4net.config"));
            Console.WriteLine("FunctionHandler[" + input + "]");
            m_log.Info("FunctionHandler[log4net][" + input + "]");
            return input?.ToUpper();
        }
    }
}


```

**Comment by normj** [comment]
You are listing version 1.1.0 for Npgsql.EntityFrameworkCore.PostgreSQL which is pulling in dependencies from .NET Core 1.1. Lambda supports 1.0 of .NET Core. I got your function to work when I changed the referenced of Npgsql.EntityFrameworkCore.PostgreSQL to 1.0.2.

**Comment by rodney-lai** [comment]
Switching the Postgresql reference fixed the problem.

Now I'm trying to use Log4Net to send logging message to Papertrail using the RemoteSyslogAppender, but I'm not getting any logging message.  Any ideas what could be wrong?

**Comment by normj** [comment]
Can you provide a simple example reproducing the issue?

**Comment by rodney-lai** [comment]
I'm following the instructions on the papertrail site

http://help.papertrailapp.com/kb/configuration/log4net-logging/

log4net.config - replace {X} with appropriate config

\<?xml version="1.0" encoding="utf-8" ?>
\<log4net>
  \<appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
    \<layout type="log4net.Layout.PatternLayout">
      \<conversionPattern value="%date [%thread] %-5level %logger - %message%newline" />
    \</layout>
  \</appender>
  \<appender name="PapertrailRemoteSyslogAppender" type="log4net.Appender.RemoteSyslogAppender">
    \<facility value="Local6" />
    \<identity value="%date{yyyy-MM-ddTHH:mm:ss.ffffffzzz} %P{log4net:HostName} MyApp" />
    \<layout type="log4net.Layout.PatternLayout" value="%level - %message%newline" />
    \<remoteAddress value="logs{X}.papertrailapp.com" />
    \<remotePort value="{XXXX}" />
  \</appender>
  \<root>
    \<level value="ALL" />
    \<appender-ref ref="ConsoleAppender" />
    \<appender-ref ref="PapertrailRemoteSyslogAppender" />
  \</root>
\</log4net>

I see logging to Cloudwatch from the ConsoleAppender, but nothing in papertrail.
My lambda is running in a private subnet with access to the internet via a NAT Gateway

**Comment by normj** [comment]
Closing as the postgresql issue has been resolved. Sorry I haven't had time to look into papertrail and I'm unlikely to have any time soon. It sounds most likely a configuration issue that would be out of scope of what we can support here. If you find a specific Lambda issue feel free to open a new issue on that.
