### ISSUE TITLE
How to call lambda function in asp.net mvc?

### ISSUE THREAD

**Issue by DavidPhysics** [aws/aws-lambda-dotnet#541]
I have the asp.net web API and want to execute the AWS lambda function in the ASP.Net web API project.
When I run my web API, the web API will show the Http 500 error code in the local server.
Could you tell me how to call the AWS lambda function, then execute?

Environment: Web api with ASP.Net 4.7 MVC
Compiler: Visual Studio 2017
IIS: IIS8 

Error code part: 

> InvokeResponse response = lambdaClient.Invoke(request);

Code part:
> [HttpPost]
[Route("api/ContactTest/Send_SMS_Messages/")]
public async Task<HttpStatusCode> SNS_SMS_Messages([FromBody] AWS_Context.SNS_SMS_Messages value)
{
    Amazon.Lambda.AmazonLambdaConfig lambdaConfig = new Amazon.Lambda.AmazonLambdaConfig() {
RegionEndpoint = RegionEndpoint.USEast1
    };
    Amazon.Lambda.AmazonLambdaClient lambdaClient = new Amazon.Lambda.AmazonLambdaClient(sAws_access_key, sAws_secret_key, lambdaConfig);
    InvokeRequest request = new InvokeRequest() {
FunctionName = "SNS_SMS_Phone",
Payload = JsonConvert.SerializeObject(value)
};
    InvokeResponse response = lambdaClient.Invoke(request);
    if (response.StatusCode == 200)
return HttpStatusCode.OK;
    else
return (HttpStatusCode)response.StatusCode;
}

**Comment by msimpsonnz** [comment]
Hi
This isn't really the place for general questions around Lambda and .NET, I would suggest you try the [AWS Forums](https://forums.aws.amazon.com)
You can see more details around the Invoke errors [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-invoke-error-502-500/)
You can also log more details on the response from
```
string functionError = response.FunctionError;
string logResult = response.LogResult;
```

**Comment by DavidPhysics** [comment]
> Hi
> This isn't really the place for general questions around Lambda and .NET, I would suggest you try the [AWS Forums](https://forums.aws.amazon.com)
> You can see more details around the Invoke errors [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-invoke-error-502-500/)
> You can also log more details on the response from
> 
> ```
> string functionError = response.FunctionError;
> string logResult = response.LogResult;
> ```

Thanks. I have solved this problem.
