### ISSUE TITLE
lambda layers for .net core 3?

### ISSUE THREAD

**Issue by techbits00** [aws/aws-lambda-dotnet#543]
I was wondering how do you create lambda layer if you are working with custom runtime? .net core 3. 
@normj  has two blogs talking about using custom runtime but none of them speaks about layers support. In one of the online webinar back in April (AWS Fireside chat) the demo for layers was again on .net 2.1

While the self contained application with ReadyToRun are considerable, I was wondering if there is a way to package .net core 3 runtime in the layer and prejit (optimize) it the same way Norm mentioned in his blogpost. 

 I have seen layers with other runtimes including CPP. However my efforts of creating a layer runs into ground with error

```
This assembly was expected to be in the local runtime store as the application was published using the following target manifest files: 
path: 'lib/netstandard2.0/Amazon.Lambda.Core.dll'

```

AWS documentation itself talks about publishing layers on this document
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html

Any pointers?

**Comment by normj** [comment]
We don't have any way in our tooling to support both custom runtime and .NET layers. For both .NET Layers and custom runtime we are relying on dotnet CLI commands `dotnet publish` and `dotnet store`. 

Essentially with `dotnet store` which is used to create the .NET layer a manifest is generated that is passed into `dotnet publish` command when creating the deployment bundle. For .NET Core 2.1 Lambda function the `dotnet publish` command will use the manifest file to figure out what assemblies to filter out of the deployment bundle. For custom runtime we pass in the `--self-contained true` flag to the `dotnet publish` command to create a deployment bundle with the .NET Core 3.0 runtime. Unfortunately when you pass in `--self-contained true` to `dotnet publish` the publish command ignores any manifests passed into it which makes the layer useless.

**Comment by techbits00** [comment]
Thanks for the reply Norm. I had seen this behavior while working with the publish command that it ignores the manifest file and still packages the dependencies in the output. Seems like there is no easy way past this at this point, my concern was more with the package size and with Zac's recent blog post it seems like the best option is the ready2run.

**Comment by ashishdhingra** [comment]
Hi @techbits00,

Good afternoon.

I was going through the backlog and came across this issue. Looks like nothing is required to be done for this issue based on your conversation with Norm. If this is the case, please confirm if we could close the issue.

Thanks,
Ashish

**Comment by techbits00** [comment]
HI Ashish,
Yes, this item is pretty much irrelevant at this point and can be closed!

Thanks,
