### ISSUE TITLE
Can Asp.net core 3.0 Razor Page Application Run on Lambda?

### ISSUE THREAD

**Issue by lehoangphan** [aws/aws-lambda-dotnet#545]
I has the Razor Page App (.net core 3.0), I I make it run on AWS Lambda? App has the Blazor Component, but render Static Mode

**Comment by lantrix** [comment]
The [documentation](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-lambda.html) suggests a requirement for _.NET Core 2.1 SDK_ only, so I'd say **probably not**.

**Comment by andymac4182** [comment]
@lehoangphan If that mode of blazor doesn't require websockets then yes :) You can use the Bring your own runtime method of deployment

**Comment by normj** [comment]
Here is a sample I put together using razor pages with .NET Core 3.0 on Lambda and Custom Runtimes. https://github.com/normj/LambdaNETCoreSamples/tree/master/CustomRuntimeAspNetCore30

I haven't tried Blazor with static mode. I'm curious how that works for you.

**Comment by normj** [comment]
Closing as I believe this has been answered. Although any feedback on Blazor with static rendering would be appreciated.
