### ISSUE TITLE
Value 'C#' at 'runtime' failed to satisfy constraint

### ISSUE THREAD

**Issue by akempe** [aws/aws-lambda-dotnet#55]
Hey, I'm trying to deploy a function, but keep getting this:

> Error updating configuration for Lambda function: 1 validation error detected: Value 'C#' at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [java8, nodejs, nodejs4.3, python2.7]

What value should I be putting for the `-frun` param?

thanks!

**Comment by normj** [comment]
`-frun` should be `dotnetcore1.0`. I'll ping the service team to get the error message updated.

**Comment by akempe** [comment]
lovely. all working. feel free to close the issue if you're not using it to track that error message.

**Comment by normj** [comment]
Closing this but I have opened a ticket on the Lambda team to update the error message.
