### ISSUE TITLE
requestTime missing in APIGatewayProxyRequest

### ISSUE THREAD

**Issue by shaheer-k** [aws/aws-lambda-dotnet#550]
Hi

I dont see requestTime property in APIGatewayProxyRequest. Its available in java, go, etc.. When it will be available in APIGatewayProxyRequest.

Regards,

Shaheer

**Comment by normj** [comment]
I created a PR to add the missing fields. I probably won't be able to get his shipped till after re:Invent next week. https://github.com/aws/aws-lambda-dotnet/pull/551

**Comment by shaheer-k** [comment]
Its urgent for us to measure RequeatTimeEpoch from API gateway. Please find this merge request.
#552

**Comment by normj** [comment]
Version 1.3.0 of Amazon.Lambda.APIGatewayEvents was shipped with this field along with a few others that were missing.
