### ISSUE TITLE
Support Lambda destinations

### ISSUE THREAD

**Issue by Binjaaa** [aws/aws-lambda-dotnet#555]
Is there any plan to support Lambda destinations?

**Comment by normj** [comment]
Yes, I plan on updating the tooling to allow specify destinations. I won't be able to get to that work till after re:Invent.

**Comment by Binjaaa** [comment]
@normj is there any update on this?

**Comment by classifieds-dev** [comment]
Prior to switching to serverless development I was using MassTransit with rabbitmq to defer elastic search indexing to a background process running in a separate container image. In doing research for lambda it looks like the best option for serverless might be to skip a custom message broker and use destinations instead. In that light is there any update on this integration? I figure I could always keep using mass transit and swap out the transport with sqs instead. However, lambda destinations seems like the best solution.
