### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer Request.ContentLength is not being set

### ISSUE THREAD

**Issue by clearwaterstream** [aws/aws-lambda-dotnet#559]
I rely on this property to detect empty payloads. I deployed an ASP.NET Core lambda behind and API Gateway and I was able to confirm that `Request.ContentLength` is null. It is otherwise *not null* when I run the code behind IIS (locally or on EC2). `Request.Body.Length` is an unsupported property (throws an exception) so I currently do not have an alternative to `Request.ContentLength`.

To repro:

Create a simple lambda, add this "mirror method", deploy behind API Gateway, and post something. I wonder if CloudFront is stripping the `content-length` header.

```csharp
[HttpPost]
public async Task<IActionResult> Mirror()
{
	using(var sr = new StreamReader(Request.Body))
	{
		var content = await sr.ReadToEndAsync();

		var sb = new StringBuilder();

		sb.AppendLine($"Request content length: {Request.ContentLength}");

		sb.Append(content);

		return Content(sb.ToString());
	}
}
```

Thanks!

**Comment by clearwaterstream** [comment]
Update, indeed `content-length` header is not being passed on it seems.

```csharp
[HttpPost]
public async Task<IActionResult> Mirror()
{
	using(var sr = new StreamReader(Request.Body))
	{
		var content = await sr.ReadToEndAsync();

		var sb = new StringBuilder();

		sb.AppendLine($"Request content length: {Request.ContentLength}");
		sb.AppendLine($"Content length header: {Request.Headers["Content-Length"]}");

		sb.Append(content);

		return Content(sb.ToString());
	}
}
```

**Comment by normj** [comment]
Thanks for reporting the issue. I have checked in a fix into the dev branch which will go out with the next release. https://github.com/aws/aws-lambda-dotnet/commit/ae2523af289ba94ded30f1233159eca731755cfe

**Comment by clearwaterstream** [comment]
Great, thank you!

**Comment by normj** [comment]
Version 4.1.0 of Amazon.Lambda.AspNetCoreServer has shipped with this fix. Thanks for letting us know about the issue.
