### ISSUE TITLE
CI System not allowing deploy-serverless due to permissions

### ISSUE THREAD

**Issue by kylegalbraith** [aws/aws-lambda-dotnet#56]
We are trying to make use of `dotnet lambda deploy-serverless` from our TeamCity instance, but are bumping into permissions issues and we know the quick solution (open up the policy to allow iam:*) but that is not very ideal.

It appears that Clouformation allows use to specify an IAM Role during stack creation that it will assume to create the resources. However, I do not see any mechanism of doing this in the lambda deploy tools or am I missing something? 

It seems that this would be ideal:
`dotnet lambda deploy-serverless --profile only-cf-access` -- use a user in TeamCity that only has access to Cloudformation, but pass in the IAM role to use in the creation of the stack.

**Comment by normj** [comment]
You are correct we should expose the role-arn used by CloudFormation through the command. I'll add that to our backlog.

**Comment by normj** [comment]
I pushed version `1.2.0-preview1` of `Amazon.Lambda.Tools` that has a new `--cloudformation-role` option for `deploy-serverless` so you can specify an IAM role for CloudFormation to assume when creating or updating the stack.

**Comment by normj** [comment]
Closing because I believe the `--cloudformation-role` option will solve your problem. If not feel free to reopen.
