### ISSUE TITLE
Lambda Bootstrap graceful shutdown

### ISSUE THREAD

**Issue by kosmakoff** [aws/aws-lambda-dotnet#560]
It's not necessarily an issue with this project, I just can't figure out where to look for an answer.

I noticed that `LambdaBootstrap.RunAsync()` accepts a `CancellationToken` as if it were possible to stop the Lambda runtime on some signal. However I was not able to find the way to detect the provisioned Lambda Shutdown. Is it possible? If it is, I'd suggest to add this example to Custom Runtime code snippet.

**Comment by normj** [comment]
If you are asking to detect when the Lambda compute environment is being torn down that isn't possible. There is no code event that occurs when a compute environment is reclaimed.
