### ISSUE TITLE
Missmatch between events causing confusion

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-lambda-dotnet#563]
When writing a custom Gateway API Authorizer, I consume the event:

```csharp
        public static Task<APIGatewayCustomAuthorizerResponse> FunctionHandler(APIGatewayCustomAuthorizerRequest input, ILambdaContext context)
        {
            ...
        }
```

When building the response, the response class has:

```csharp
var result = new APIGatewayCustomAuthorizerResponse
{
    Context = new APIGatewayCustomAuthorizerContextOutput
    {
        ["Banana"] = "Yellow"
    },
    ...
};
```

If you look at the implementation of `APIGatewayCustomAuthorizerContextOutput`

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerContextOutput.cs

You can see it implement Dictionary, and has no property called `Claims`.

When this is eventually passed down to an ASP.NET Core Api, and you need to extract the claims back out, you need to go into the Request Items.

```csharp
var proxyRequest = Request.HttpContext.Items["LambdaRequestObject"] as APIGatewayProxyRequest;
```

This contains:

```csharp
proxyRequest.RequestContext.Authorizer
```

The implementation of `Authorizer` is:

https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerContext.cs

This /does/ contain a property called `Claims`

This is super confusinig and I just spent the last few hours trying to figure out why my claims were empty. 

Can't `Claims` pull the claims from `this.` being the dictionary itself rather than building an entirely new list?

**Comment by klaytaybai** [comment]
Thanks @phillip-haydon for the feedback.  I agree that this is confusing.  I'll get back to you with another response when our expert on the subject is back form vacation.

**Comment by normj** [comment]
This behavior was done because the behavior for claims is different between coming from a custom authorizer versus using a Cognito User Pool as the authorizer. Admittedly I think we optimized for the Cognito User Pool and didn't give enough thought for the custom authorizer case. 

What I think we should do is investigate that if there is no "claims" property which a user pool uses with nested JSON values then maybe create the Claims list from the property keys of the APIGatewayCustomAuthorizerContext.

**Comment by phillip-haydon** [comment]
I assume that the de-serialization is based on the property of `Claims` when coming from Cognito. 

So in that case couldn't you do something like change:

```csharp
        Dictionary<string, string> _claims;
        /// <summary>
        /// Gets or sets the claims coming from Cognito
        /// </summary>
        public Dictionary<string, string> Claims
        {
            get
            {
                if(_claims == null)
                {
                    _claims = new Dictionary<string, string>();

                    object value;
                    if(this.TryGetValue("claims", out value))
                    {
                        JObject jsonClaims = value as JObject;
                        if (jsonClaims != null)
                        {
                            foreach (JProperty property in jsonClaims.Properties())
                            {
                                _claims[property.Name] = property.Value?.ToString();

                            }
                        }
                    }
                }

                return _claims;
            }
            set
            {
                this._claims = value;
            }
        }
```

To

```csharp
        /// <summary>
        /// Gets or sets the claims coming from Cognito
        /// </summary>
        public Dictionary<string, string> Claims
        {
            get
            {
                return this;
            }
            set
            {
                if(value != null)
                {
                    object claims;

                    if (value.TryGetValue("claims", out claims))
                    {
                        JObject jsonClaims = claims as JObject;
                        if (jsonClaims != null)
                        {
                            foreach (JProperty property in jsonClaims.Properties())
                            {
                                this[property.Name] = property.Value?.ToString();
                            }
                        }
                    }
                }
            }
        }
```
