### ISSUE TITLE
Cannot publish new lambda from docker container

### ISSUE THREAD

**Issue by bo67192** [aws/aws-lambda-dotnet#565]
Hello,

I'm trying to build out a powershell lambda function, but I'm getting errors.

Because I use powershel 5.1 on my laptop I'm trying to use a Docker container for development. Here's my setup so far

docker run -v "$((pwd).path)/lambda:c:\\lambda" -v "$($HOME)/.aws:c:\\users\\containeradministrator\\.aws" -it mcr.microsoft.com/powershell:6.2.3-windowsservercore-1803

(this gets me into a running windows container). Then I run

Install-Module AWSLambdaPSCore;
Install-Module AWS.Tools.Installer;
Import-module AWS.Tools.Installer;
Install-AWSToolsModule -Name AWS.Tools.IdentityManagement;
Get-AWSPowerShellLambdaTemplate;
New-AWSPowerShellLambda -Template Basic;
.\\dotnet-install.ps1; # to get the dotnet exe on the cli

Which should get me the AWS powershell tools, AWS Powershell Lambda functions, and dotnet CLI. Next I run

New-AWSPowerShellLambda -Template Basic

And I get a new powershell directory with a basic script. Lastly I run

Publish-AWSPowerShellLambda -Name PsHelloWorld -ScriptPath .\\Basic\\Basic.ps1 -Region us-east-1 -ProfileName sandbox

But I see this error

Configuring PowerShell to version 6.1.1
Generating C# project C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\Basic\\PsHelloWorld.csproj used to create Lambda function bundle.
Generating C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\Basic\\Bootstrap.cs to load PowerShell script and required modules in Lambda environment.
Generating aws-lambda-tools-defaults.json config file with default values used when publishing project.
Copying PowerShell script to staging directory
Deploying to AWS Lambda
Restoring .NET Lambda deployment tool
Initiate deployment
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\\Users\\ContainerAdministrator\\.dotnet\\tools\\.store\\amazon.lambda.tools\\3.3.1\\amazon.lambda.tools\\3.3.1\\tools\\netcoreapp2.1\\any\\].
If this is a framework-dependent application, install the runtime in the global location [C:\\Program Files\\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\\SOFTWARE\\dotnet\\Setup\\InstalledVersions\\x64\\InstallLocation].

What am I doing wrong? How can I fix this?

**Comment by msimpsonnz** [comment]
Could be something to do with the container image?
I just spun up an Ubuntu image and install pwsh and dotnet and works fine

**Comment by bo67192** [comment]
@msimpsonnz which Ubuntu image did you use? I'll give it another go.

I should add I was using docker desktop on Windows 10

**Comment by bo67192** [comment]
This container seems to be working for me

https://hub.docker.com/_/microsoft-dotnet-core-sdk

**Comment by msimpsonnz** [comment]
I was just using the latest vanilla Ubuntu image

**Comment by ashishdhingra** [comment]
Hi @bo67192,

Good evening.

I was going thorough the list of backlog issues and came across this one. In case this is no longer an issue, please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by rickjacobo** [comment]
Just wanted to leave this as it may help others in a similar scenario - I created a docker container with all the dependencies required to publish a PowerShell Function to AWS Lambda using a custom Docker image. 

Feel free to check out the work at:
https://hub.docker.com/r/rickjacobo/lambda-powershell-project-builder

## Project Notes
- The lambda-powershell-project-builder container has all the dependencies required to get started quickly with PowerShell on AWS Lamb
- The create-project.ps1 script runs the Publish-AWSPowerShellLambda command with the values collected during the script execution and creates the edit and publish scripts on the fly based on your answers. Finally, it launches the 'aws configure' cli command for so you can enter your aws "Access Key Id" and "Secret Access key" which is required for - -publishing your Lambda application.
- The publish-.ps1 script run the Publish-AWSPowerShellLambda script with some sensible defaults
