### ISSUE TITLE
Publish-AWSPowershellLambda generating deployment larger than 250MB

### ISSUE THREAD

**Issue by jeffj254** [aws/aws-lambda-dotnet#566]
I'm just getting started with Powershell on Lambda.  I've been following the getting started guide here: https://aws.amazon.com/blogs/developer/announcing-lambda-support-for-powershell-core/

I've setup my environment and installed all the necessary modules.  I'm trying to publish an extremely basic Powershell script just to learn a bit more about how this works before I start writing real functions

My steps:
1. Create a new Lambda using the basic template
New-AWSPowershellLambda -ScriptName JeffTest -Template Basic
2. Add a couple simple lines to the script to see how things behave
get-s3bucket
$test = get-s3bucket
write-host $test
write-host "End of test Lambda"
3. Publish lambda
Publish-AWSPowershellLambda -ScriptPath .\JeffTest.ps1 -Name JeffTest -region us-west-2

The publish then fails with the error:
Error creating Lambda function: Unzipped size must be smaller than 262144000 bytes

If I run New-AWSPowershellLambdaPackage and examine the output I have a 37MB zip file that unzips into 275MB of files, so clearly the commandlet is generating a deployment package that is too large.

I have not added any additional modules to my test, only the default AWSPowerShell.NetCore module is being required.  I notice that this module alone on my workstation is 246MB uncompressed, so it seems like it is too large for this to ever work.

Am I doing something wrong here?  Is there a way to reduce the size of the lambda package? 

I'm currently using the latest version 4.0.2.0 of AWSPowerShell.NetCore.

**Comment by jeffj254** [comment]
One additional note, I tried switching the version of AWSPowerShell.NetCore that my function required to an older version I have installed (3.3.590.0) and I was able to successfully publish the Lambda.  Using the older version of the module dropped the zip size down to 29MB and the unzipped size down to 144MB.

I guess 4.x versions might be too large for lambda usage?

**Comment by jeffj254** [comment]
After some additional reading I think I might have the solution to my issue.  AWSPowerShell.NetCore is a monolithic module that includes everything for all AWS services and supports Powershell 3 all the way to Powershell 6.

Instead of loading one giant module I can use the AWS.Tools modules (https://github.com/aws/aws-tools-for-powershell/issues/67)  which are modular and allow me to only load the commandlets I need for my function.  Doing it this way and only requiring aws.tools.s3 gives me a deployment zip size of 11MB and an uncompressed size of 33MB.  Much better.

Might be worth updating the basic template to not reference the latest version of AWSPowerShell.NetCore though, since it's too large to deploy with a Lambda

**Comment by GloverChris** [comment]
You'll need to un-comment the section in the lambda  below. This will force the machine to work with the appropriate module otherwise you get a bunch of DLLs bundled into your zip which makes it huge

`Requires -Modules @{ModuleName='AWSPowerShell.NetCore';ModuleVersion='4.0.4.0'}
`

**Comment by brendan-sherrin** [comment]
> 
> 
> You'll need to un-comment the section in the lambda below. This will force the machine to work with the appropriate module otherwise you get a bunch of DLLs bundled into your zip which makes it huge
> 
> `Requires -Modules @{ModuleName='AWSPowerShell.NetCore';ModuleVersion='4.0.4.0'} `
Just tried uncommenting this and it didn't load the Module into the Lambda, don't believe that's the answer: #Requires -Modules @{ModuleName='AWSPowerShell.NetCore';ModuleVersion='4.0.5.0'}

That also gives the following error from the Lambda itself:
START RequestId: 762bd5bd-e3b4-48a5-97af-5da66f68a46c Version: $LATEST
[Error] - The term 'Requires' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by ashishdhingra** [comment]
@jeffj254, 

Good afternoon.

I was going through the backlog and encountered this issue. Looks like you had found solution to your problem. Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by jeffj254** [comment]
I suppose, though I think the issue still exists if you create a new lambda using the basic template and you have AWSPowerShell.NetCore installed since that will be the required module.

Some sort of documentation update might be useful to note that the NetCore module is too large to be deployed with a Lambda would probably be helpful.

**Comment by GloverChris** [comment]
You’re supposed to use the modular module for lambda development in the powershell language.

Regards,
Chris
________________________________

**Comment by ashishdhingra** [comment]
Hi @jeffj254,

I just checked, the documentation link [Installing AWS Tools for PowerShell on Linux or macOS](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html) and [Installing the AWS Tools for PowerShell on Windows](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html) mentions about the large `AWSPowerShell.NetCore` module. Hope this helps, let me know if this issue could be closed.

Thanks,
Ashish

**Comment by brendan-sherrin** [comment]
@ashishdhingra I'd be thinking add a note to the documentation that the single large AWSPowerShell.NetCore module will exceed the maximum upload size on Lambda as stands

**Comment by ashishdhingra** [comment]
@jeffj254 @brendan-sherrin Thanks for the feedback. I will discuss with the team if this could be added at appropriate place in documentation.

**Comment by GloverChris** [comment]
@ashishdhingra the tools for NT community is rather confusing due to there being so many options. AWS has already recommended which tool to use which is the modular install. Can you guys just remove the other tools from the docs or is there something  like dependency issues or something we don’t see that’s preventing AWS from being more organized with tools provided to NT community? IMHO the modular tool should be THE tool to use.

Regards,
Chris
________________________________

**Comment by ashishdhingra** [comment]
[Migrating from AWS Tools for PowerShell Version 3.3 to Version 4](https://docs.aws.amazon.com/powershell/latest/userguide/v4migration.html) specifies details of `New Fully Modularized AWS.Tools Version`

**Comment by ashishdhingra** [comment]
The guide https://docs.aws.amazon.com/powershell/latest/userguide/pstools-welcome.html recommends to use modularized version for production.
