### ISSUE TITLE
dotnet lambda package-ci packs everything

### ISSUE THREAD

**Issue by tofalck** [aws/aws-lambda-dotnet#574]
dotnet core 3.0

@normj I think dotnet lambda package-ci used to pack only the bin folder build output when called from the root (where the sln and template files are located).

It seems to be packing the entire tree - source, obj, bin - the works, relative to where you call it from. Can this be fixed somehow with a switch or is it related to #206?

dotnet lambda package-ci --configuration Release --template serverless.template.json --region eu-west-1 --s3-bucket package --framework netcoreapp3.0 --output-package ServerlessApp.zip --output-template ServerlessApp.json

![image](https://user-images.githubusercontent.com/2613099/73196329-b5f19c00-412f-11ea-8f92-24cd8cf91de2.png)

**Comment by normj** [comment]
My guess is you have `serverless.template.json` at the solution folder level and not the project level and the it looks like the CodeUri for the lambda resource is set to '.'. What `package-ci` will do is look at the directory pointed to by `CodeUri` relative the template and see if it is a .NET project folder. It does that by looking for a project file. If it finds one it does the usually `dotnet publish` and zips up the output. In your case it looks like you have CodeUri set to '.' with the template being at the solution level so it determines that the folder is not a .NET project folder. Whenever the tool is not pointing to a .NET project folder it assumes the user just wants to zip up the folder and sent it up. This works for when the developer has their own way of building their .NET project or it is pointing to a Node.js or Python folder.

It is fine to have `serverless.template.json` at the solution level but you should update the CodeUri in the template to have a relative path to the .NET project folder. If the CodeUri is not set then the tool will assume the directory containing `serverless.template.json` is the root folder.

Note I'm talking about setting the CodeUri property if you are using the `AWS::Serverless::Function` resource. If you are using `AWS::Lambda::Function` then set Code/S3Key to the relative path to of the .NET Project directory.

**Comment by tofalck** [comment]
My template is below two folders down from where the sln file is. And then the lambda projects in their own folder.

I updated my template to point to the folder with the lambda project (./FolderName) and that seems to have fixed my problem. 

To be honest I forgot to put CodeUri in my template in the first place - perhaps the tool could auto-add it if the user is so forgetful as I am :-)

I suggest the CLI dotnet extension docs to be updated with more info on how to use the command (copy-paste example), the full list of options, and especially the difference between AWS::Serverless::Function and AWS::Lambda::Function. And perhaps a recommended directory structure.

Other than that - thanks... 👍
