### ISSUE TITLE
Inconsistency with README.md and AWS Environment

### ISSUE THREAD

**Issue by W0GER** [aws/aws-lambda-dotnet#575]
The README.md page reports that the Currently Supported Patch for 2.1 is 2.1.13
https://github.com/aws/aws-lambda-dotnet/blob/master/README.md

However, when attempting to run 2.1.13 or 2.1.14 we are seeing the following error in the CloudWatch logs. It appears that only 2.1.12 is installed. 

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.14' was not found.
- Check application dependencies and target a framework version installed at:
/var/lang/bin/
- Installing .NET Core prerequisites might help resolve this problem:
https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
- The .NET Core framework and SDK can be installed from:
https://aka.ms/dotnet-download
- The following versions are installed:
2.1.12 at [/var/lang/bin/shared/Microsoft.AspNetCore.App] 
```

**Comment by msimpsonnz** [comment]
Check this issue with seems similar, you don’t need to specify NET version
https://github.com/aws/aws-lambda-dotnet/issues/531

**Comment by ashishdhingra** [comment]
Hi @W0GER,

 Please advise if the inputs in the issue #531 resolves your issue and if we could close this issue.

Thanks,
Ashish
