### ISSUE TITLE
Async method doesn't run on Program.cs file.

### ISSUE THREAD

**Issue by prakash-patel** [aws/aws-lambda-dotnet#577]
I was trying to follow this article (https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-1/) to run DB Migration script Async on program.cs file. I used the step 4, locally works fine but as as soon as i deployed to  aws lambda, some reason it's never run `InitializeDatabase()` method. I am using .net core 2.1.

``` c#
public static async Task Main(string[] args)
        {
            IWebHost webHost = CreateWebHostBuilder(args).Build();
            await InitializeDatabaseAsync(webHost);
            await webHost.RunAsync();
        }

        private static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();

        private static async Task InitializeDatabaseAsync(IWebHost webHost)
        {
            using (var scope = webHost.Services.CreateScope())
            {
                try
                {
                    // Get the DbContext instance
                    var myDbContext = scope.ServiceProvider.GetRequiredService<AppsContext>();
                    LambdaLogger.Log("Database migration start InitializeDatabase().");
                    
                    //Do the migration asynchronously
                    await myDbContext.Database.MigrateAsync().ConfigureAwait(false);
                    LambdaLogger.Log("Database migration stop InitializeDatabase().");
                }
                catch (Exception ex)
                {
                    LambdaLogger.Log("An error occurred while initializing the database.");
                    throw;
                }
            }
        }
```

**Comment by normj** [comment]
I assume this is running an ASP.NET Core app as a Lambda function. In that case none of the code is called from the main function when running in Lambda. Instead the setup logic is replaced with the logic in the class in your project that derives from `Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction` often called `LambdaEntryPoint`. In that class you can override the `PostCreateWebHost` to add additional setup logic.

I would be careful with initializing a database as part of a Lambda function startup because there will potentially be many process running at the same time. Also that can also affect your cold start performance for your Lambda functions every time the Lambda service spins off another process to make sure the database has been initialized.

**Comment by prakash-patel** [comment]
I won't be initializing a database, that would be part of CI pipeline `pre-deployment` step. I am just using that as an example. Thanks for your advice 👍.  

I am using Lambda Application to create this .Net Core API. I do have `LocalEntryPoint` class. In order to get `PostCreateWebHost` do you know which class i have to inherit from?

below is the entire file look like. 
```c#
/// <summary>
    /// The Main function can be used to run the ASP.NET Core application locally using the Kestrel webserver.
    /// </summary>
    public class LocalEntryPoint
    {
        public static async Task Main(string[] args)
        {
            IWebHost webHost = CreateWebHostBuilder(args).Build();
            await InitializeDatabaseAsync(webHost);
            await webHost.RunAsync();
        }

        private static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();

        private static async Task InitializeDatabaseAsync(IWebHost webHost)
        {
            using (var scope = webHost.Services.CreateScope())
            {
                try
                {
                    // Get the DbContext instance
                    var myDbContext = scope.ServiceProvider.GetRequiredService<AppsContext>();
                    LambdaLogger.Log("Database migration start InitializeDatabase().");

                    //Do the migration asynchronously
                    await myDbContext.Database.MigrateAsync().ConfigureAwait(false);
                    LambdaLogger.Log("Database migration stop InitializeDatabase().");
                }
                catch (Exception ex)
                {
                    LambdaLogger.Log("An error occurred while initializing the database.");
                    throw;
                }
            }
        }
    }
```

**Comment by normj** [comment]
If you used one of our templates you should also have `LambdaEntryPoint` in your project. Here is an example of one.

```csharp
namespace AWSServerless5
{
    public class LambdaEntryPoint :
        // When using an ELB's Application Load Balancer as the event source change 
        // the base class to Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction
        Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseStartup<Startup>();
        }

        protected override void PostCreateWebHost(IWebHost webHost)
        {
            // TODO Do some more configuration
        }
    }
}
```

**Comment by prakash-patel** [comment]
Yes, I see it now. Thanks for your answer.

**Comment by prakash-patel** [comment]
I am trying to comparing between **Lambda Application** vs **Lambda Function**.  In Lambda Application, i am using `Startup.cs` file with .Net core dependency injection to setting up service for Identity service and SQS. In Lambda function i kind of `new` up all those service.

I execute the code for both using API Gateway. I am getting response in **Lambda Application** faster than **Lambda Function**. Is that because Application running in IWebHost and it's also using API Gateway as proxy and not setting up actual endpoint in it?

Any information would be great help to me understand how this process under lambda?

**Comment by ashishdhingra** [comment]
Hi @prakash-patel,

Good afternoon.

A **Lambda function** is a piece of code (managed by AWS) that is executed whenever it is triggered by an event from an event source. A **Lambda application** is a cloud application that includes one or more Lambda functions, as well as potentially other types of services.

More details could be found at [AWS Lambda applications](https://docs.aws.amazon.com/lambda/latest/dg/deploying-lambda-apps.html). [AWS Lambda FAQs](https://aws.amazon.com/lambda/faqs/) could also provide helpful information.

Please let me know if this issue could be closed.

Thanks,
Ashish
