### ISSUE TITLE
Avoid print exception to CloudWatch when lambda failed

### ISSUE THREAD

**Issue by safv12** [aws/aws-lambda-dotnet#578]
Hi, when I throw an exception from my C# handler in AWS Lambda it is printing the exception to CloudWatch. I there any way to avoid this behavior.

**Comment by normj** [comment]
There is no way right now, can you explain your use case where you don't want the error written to CloudWatch logs?

**Comment by safv12** [comment]
Thaks @normj, yes, let me explain.

We are currently logging the error but formatted, for example:

`{"severity":"Error","timestamp":...,"request_id":"1b264f6f-a480-4af0-be1a-068488713eec", "message": "...` and so on.

We send all this logs to Splunk and we are having throubles with the exception at the end of the request, thats why we want to remove it.

I know we can do something from the Splunk side but we have no permission as a team to do the changes and I was looking another way to do it.

If is this irrelevant to the repository feel free to close the issue.

**Comment by petarrepac** [comment]
why you don't just wrap your function handler in a try.. catch and in the catch block you just log and swallow the exception?

that way you will have your exception logged and aws lambda will think all was well (will not see any exception going out)

**Comment by safv12** [comment]
I need to throw the exception to handle it in a Step Function. Is there any other way to catch error in StepFunctions without throwing them from the lambda?
