### ISSUE TITLE
PreviewAspNetCoreWebAPI is there a swagger.json missing?

### ISSUE THREAD

**Issue by kylegalbraith** [aws/aws-lambda-dotnet#58]
I am looking into following the PreviewAspNetCoreWebAPI example in order to create a dotnet core Web API and route it via lambda. But I am curious what the best approach is to use here.

1. Do you create a single lambda function and have all API endpoints in APIGW go through that single lambda? It seems this is the case, but curious what others think.
2. Do you define a swagger.json and setup all your endpoints to go to the single lambda? Curious on this as well as there is no swagger.json in that blueprint.

**Comment by normj** [comment]
The idea with PreviewAspNetCoreWebAPI is to have one Lambda function that forwards the entire APIGW request into the ASP.NET Core framework and have that route to the property Web API Controller. If you look at the serverless.template you can see how only one function is defined.

**Comment by kylegalbraith** [comment]
Right, I suppose my question is more along the lines of what does this look like from an APIGW config standpoint? Do I still define all of my API's in swagger, but have the function they all call be the one lambda function that routes all APIGW requests back through the dotnet core Web API?

**Comment by normj** [comment]
The serverless.template configures API Gateway to have one resource responding to all HTTP methods using the API Gateway proxy feature. The proxy feature makes it so that all URLs go to the same lambda function.

Here is a link describing API Gateway proxies.

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

**Comment by normj** [comment]
I believe this is answered so I'm closing this. If you have more questions feel free to reopen.
