### ISSUE TITLE
Inconsistency in apigatway examples for proxy lambda ?

### ISSUE THREAD

**Issue by RoyiNamir** [aws/aws-lambda-dotnet#580]
I already know that

  [*For API Gateway to handle a Lambda function's response, the response must be JSON in this format:*][1]

    {
        "isBase64Encoded": true|false,
        "statusCode": httpStatusCode,
        "headers": { "headerName": "headerValue", ... },
        "body": "..."
    }

I've also verified it by checking [the doc's example][2] for a regular `Function Handler`.

[![enter image description here][3]][3]

But, looking at the [*second example*][4] on the same page, it shows a serverless application lambda, which is actually a controller

However: the controller inherits `: ControllerBase` , and not `: Controller` as [I see when I create a new lambda serverless project][5]  
Also - I don't see that they use the same response structure as in the first example on that same page.

**Question:**

Why doesn't the second example forced to return the same fixed structure JSON as in the first example on the same page? and why the controllers base class are different?

  [1]: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format
  [2]: https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.APIGatewayEvents#function-handler
  [3]: https://i.stack.imgur.com/kjwbH.png
  [4]: https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.APIGatewayEvents#microsoftaspnetcoremvc-controller
  [5]: https://i.imgur.com/1EPWYua.jpg

**Comment by normj** [comment]
As far as Controller vs ControllerBase from the ASP.NET Core Framework both work but ControllerBase does make more sense. I should update the blueprints to use ControllerBase.

The return of a controller method doesn't need to match what API Gateway expects. It can return whatever you would normal want to return back from a controller. The Amazoon.Lambda.AspNetCoreServer package that is hosting the ASP.NET Core application in Lambda takes care of translating the response that came back from the controller into what API Gateway expects.

**Comment by RoyiNamir** [comment]
As always, I thank you. @normj

**Comment by ashishdhingra** [comment]
Hi @RoyiNamir,

Good afternoon.

I was going through backlog of open issues. Looks like @norm provided guidance to your question. Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by RoyiNamir** [comment]
@ashishdhingra  Sure it can be closed :-)
