### ISSUE TITLE
Connection Refused Error When Running dotnet lambda deploy-function In WSL

### ISSUE THREAD

**Issue by danbo0001** [aws/aws-lambda-dotnet#582]
Hi,

I am using the latest version of the tools on Windows 10:-
Amazon Lambda Tools for .NET Core applications (3.3.1)

When running a deploy from the Visual Studio developer command prompt, the lambda deploys successfully:-
dotnet lambda deploy-function --config-file aws-lambda-tools-defaults.json

(snip)
Created publish archive (D:\Dan\Documents\src\aws-lambda-alb_3.1\AwsLambdaAlb\bin\Release\netcoreapp3.1\AwsLambdaAlb.zip).
Updating code for existing function
Updating runtime configuration for function AwsLambdaAlb

When running from inside WSL, most of it works fine (the publish, changing permissions and zipping), but when it gets to the bit where it talks to AWS, I get a connection refused:-

(snip)
Created publish archive (/mnt/d/Dan/Documents/src/aws-lambda-alb_3.1/AwsLambdaAlb/bin/Release/netcoreapp3.1/AwsLambdaAlb.zip).
Error retrieving configuration for function AwsLambdaAlb: Connection refused

I installed the tools in cmd and in WSL the same way, using:-
dotnet tool install -g Amazon.Lambda.Tools

I also checked the aws cli works fine with the same profile used in the lambda tools config (using the command aws lambda list-functions --profile <the-profile>. The connection to the internet from WSL is working (verified by pinging google).

I wanted to used WSL to try out the readytorun feature as I don't have a real linux box handy, plus I have used WSL extensively and successfully with Fargate so it really should be ok to use it with lambda too,

Can anyone think of any reason why this would fail from WSL?

Thanks in advance
Dan

**Comment by klaytaybai** [comment]
Hi,

We're curious if the credentials are accidentally misconfigured in WSL.  Could you please let us know if running `aws sts get-caller-identity` on both Windows and WSL using Powershell or a regular cmd command shell outputs the same results?  There may be a discrepancy in the shared credentials file (e.g. ~/.aws/credentials), shared config file (e.g. ~/.aws/config), or aws-lambda-tools-defaults.json file.

**Comment by danbo0001** [comment]
Hi, 

I ran it in cmd and WSL and got the same response for both:-
>aws sts get-caller-identity --profile dan-dev
{
    "UserId": "***",
    "Account": "***",
    "Arn": "arn:aws:iam::***:user/dan-dev"
}

I did add --profile dan-dev to the aws sts command because the profile I am using (which is also set as such in aws-lambda-tools-defaults.json) is not the default profile in my configuration as I have many accounts I connect to.

I did a version check of the awscli and they are slightly different:-

CMD>aws --version
aws-cli/1.16.179 Python/3.6.0 Windows/10 botocore/1.12.169

WSL$ aws --version
aws-cli/1.16.262 Python/2.7.15+ Linux/4.4.0-18362-Microsoft botocore/1.12.252

However, I am not sure if this version difference is significant as I am running a huge amount of awscli commands from both cmd/gitbash and WSL and they are all running fine (e.g. cloudformation, fargate, s3, iam, and more).

I checked another dotnet lambda function to see if it was just deploy-function with the problem, but that failed in WSL with the same Connection Refused error:-

dotnet lambda list-functions --profile dan-dev
Amazon Lambda Tools for .NET Core applications (3.3.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Enter AWS Region: (The region to connect to AWS services, if not set region will be detected from the environment.)
eu-west-1
Error listing Lambda functions: Connection refused

But running the awscli equivalent in WSL works fine:-

aws lambda list-functions --profile dan-dev

Visual Studio's publish to lambda also works fine, but I am guessing it uses cmd or powershell anyway?

I had a look at the cmd line options for dotnet lambda deploy-function to see if there is any verbose logging switch, but I couldn't see one - is there anything I can do to see what's going on?

Thanks
Dan

**Comment by danbo0001** [comment]
With respect to the sts command in my post above, I just noticed that the formatting removed my asterisks that I put in to replace my actual account id etc. Just to confirm then, running the sts command in both cmd and WSL worked successfully and the output was identical :)

**Comment by danbo0001** [comment]
Hi, can anyone help with this?

**Comment by bjorg** [comment]
Odd. I'm able to build, publish and deploy just fine with [LambdaSharp](https://lambdasharp.net) in WSL. Not sure why `dotnet lambda` would be different.

**Comment by ashishdhingra** [comment]
@danbo0001 Please let me know how profile and credential resolution are configured. If it using environment variables, .aws user profile, etc.?

**Comment by danbo0001** [comment]
@ashishdhingra i have creds configured using .aws user profile

**Comment by ashishdhingra** [comment]
@danbo0001 This is more likely an environmental issue, not the .NET CLI or SDK issue. I will try to look into it and let you know my findings.

**Comment by ashishdhingra** [comment]
Hi @danbo0001,

Good evening.

Unfortunately, I'm unable to reproduce the error. After setting up the WSL environment (with Ubuntu), using .NET CLI, I created a new lambda function and was successfully able to deploy the new function:

<img width="673" alt="Screen Shot 2020-09-24 at 5 08 34 PM" src="https://user-images.githubusercontent.com/67916761/94212645-901cc280-fe89-11ea-9cbc-87fc56bce671.png">

<img width="1122" alt="Screen Shot 2020-09-24 at 5 09 42 PM" src="https://user-images.githubusercontent.com/67916761/94212650-94e17680-fe89-11ea-8b38-87b382d7d08b.png">

Kindly note that I'm using version 4.1.0 (latest) of Amazon Lambda Tools (refer bash prompt). Kindly try updating to the latest version of AWS Tools and see if this issue is resolved.

Hence, looks like it's more likely an environmental issue (network, firewall, etc.). Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by danbo0001** [comment]
Hi Ashish,

To be honest, while I appreciate you looking into this issue now, it is now September and I raised this issue in February. That is 7 months ago!!!

I gave up trying to make it work a long time ago due to the lack of response and have since moved on projects twice now in that time. I no longer have the ability to even test out your suggestion without setting everything up from scratch again.

So you may as well close this issue as unresolved. I think I may be coming back to using this stuff early next year so if the issue reoccurs and the response rates to these problems are better, I will re-raise the issue then.

Many Thanks
Dan
