### ISSUE TITLE
not able to read environment variable.

### ISSUE THREAD

**Issue by prakash-patel** [aws/aws-lambda-dotnet#583]
I have setup environment variable in `aws-lambda-tools-defaults.json.json` file like below. 
```
{
    "region" : "us-east-1",
    "configuration" : "Release",
    "framework"     : "netcoreapp2.1",
    "function-name" : "FunctionName",
    "function-description" : "some description.",
    "function-handler"     : "ProjectNamespace::FunctionName::HandleAsync",
    "function-memory-size" : 256,
    "function-role"        : "FUNCTION_ROLE",
    "function-timeout"     : 15,
    "function-runtime"     : "dotnetcore2.1",
    "function-security-groups" : "FUNCTION_SECURITY_GROUPS",
    "environment-variables"    : "\"ConfigFileKey\"=\"config-files\""
}
```

Some reason i am not able to read that variable when i debug application. It works fine when i deployed code to lambda.

`var configKey = Environment.GetEnvironmentVariable("ConfigFileKey")`

**Comment by martonx** [comment]
Because of you should set your debugging environment variables in Visual Studio launchsettings.json

**Comment by prakash-patel** [comment]
Thanks for quick reply. I updated `launchsettings.json` file to below and it started working.
```
{
  "profiles": {
    "Mock Lambda Test Tool": {
      "commandName": "Executable",
      "commandLineArgs": "--port 5051",
      "workingDirectory": ".\\bin\\Debug\\netcoreapp2.1",
      "executablePath": "C:\\Users\\%USERNAME%\\.dotnet\\tools\\dotnet-lambda-test-tool-2.1.exe",
      "environmentVariables": {
        "ConfigFileKey": "config-files",
      }
    }
  }
}
```

**Comment by sl-bassamtayba** [comment]
Hi, 
Do you know why the environment-variables exists in the aws-lambda-tools-defaults.json? 
is it supposed to be used? if yes, how?
thank you

**Comment by prakash-patel** [comment]
I hope this https://medium.com/devtechblogs/https-medium-com-lior-k-sh-five-features-csharp-dotnet-core-aws-lambda-function-9b2d1a3d681b article help you to understand why `environment-variables` exists
![image](https://user-images.githubusercontent.com/938054/101659793-0dc58880-3a0c-11eb-90c5-d0a36505a0a2.png)

**Comment by kapdo** [comment]
if u are using dotnet lambda deploy-serverless, this wont work as it expects only basic parameters to be loaded from config file and environment variables in this case needs to be configured in serverless template. 
If u use dotnet lambda deploy-function, environment-variables will be loaded correctly.
if u debuuging locally, mention them in launch.json
