### ISSUE TITLE
AWS Serverless Application IAM Role

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#584]
When creating an AWS Serverless Application (Template ASP.NET Core Web App) in Visual Studio 2019, the "Publish to AWS Lambda" dialog does not allow us to specify an IAM Role.

In order to set the IAM Role we have to manually modify the aws-lambda-tools-defaults.json file and set the "function-role"       : "arn:aws:iam::xxxxxxxxxxxx:role/my-role"

Is it possible to include the Lambda Role in the "Publish to AWS Lambda" dialog box?

**Comment by klaytaybai** [comment]
It's a good ask.  Can you please recreate this issue in https://github.com/aws/aws-toolkit-visual-studio/issues?

**Comment by genifycom** [comment]
Thanks for pointing that out :-) Recreated.
