### ISSUE TITLE
bootstrap file missing from blueprint

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-lambda-dotnet#585]
I tried to create a custom runtime lambda for testing yesterday
``` Powershell
dotnet new lambda.CustomRuntimeFunction --name TryNetCore31
```

But it seems there is not `bootstrap` file included, is it normal?
https://github.com/aws/aws-lambda-dotnet/tree/master/Blueprints/BlueprintDefinitions/Msbuild-NETCore_2_1/CustomRuntimeFunction/template/src/BlueprintBaseName.1

![image](https://user-images.githubusercontent.com/4518597/75003286-40fd5200-54a2-11ea-9048-77e90bf02638.png)

**Comment by normj** [comment]
Thanks for pointing this out I need to update the README file for the blueprint. I recently changed the blueprint to name the assembly `bootstrap` instead of using a bash script called `bootstrap`. I did this to reduce the cold start. Using the bash `bootstrap` way caused 2 process to have to spin up during cold start.

**Comment by jasonycw** [comment]
Thanks for the reply. Since native `dotnetcore3.1` seems to have no ETA and for the new Lambda functions that we are planning, we are thinking to use the custom runtime instead of keep using `dotnetcore2.1`.

The current template seems not working quite right without Googling a bunch of difference tutorials (the official AWS tutorials/blogs aren't clear on what to do with .NET Core custom runtime), changing the `.csproj` here and there, manually adding `bootstrap` and contacting the AWS support. 

`dotnet lambda deploy-function` seems to still work but if I use `sam package` and then `aws cloudformation deploy` there will be some permission issue with the lambda. AWS Lambda support team asked me to contact CloudFormation support team to check on the issue, but I will just point it out here for the record.

**Comment by ashishdhingra** [comment]
Hi @jasonycw, 

Good morning.

I was going through issue backlog and came across this issue. Please let me know if this is still an issue or we could close it.

Thanks,
Ashish

**Comment by jasonycw** [comment]
Hi @ashishdhingra 

The file is still missing here
https://www.github.com/aws/aws-lambda-dotnet/tree/master/Blueprints%2FBlueprintDefinitions%2Fnetcore3.1%2FCustomRuntimeFunction%2Ftemplate%2Fsrc%2FBlueprintBaseName.1

Although I am not using custom runtime anymore, the README still show the needs of `bootstrap` while there is no such thing in the template.

**Comment by ashishdhingra** [comment]
@jasonycw Thanks. It appears Readme needs to be updated.
