### ISSUE TITLE
APIGatewayCustomAuthorizerPolicy.IAMPolicyStatement missing Condition element

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-lambda-dotnet#588]
IAMPolicyStatement  in [APIGatewayCustomAuthorizerPolicy](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerPolicy.cs) is missing the `Condition` element, as [described in the IAM user guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_statement.html).

**Comment by klaytaybai** [comment]
That it is.  Thank you.

**Comment by hauntingEcho** [comment]
This is still an issue

**Comment by yofitec** [comment]
Still not there.

If you inherit from these classes and add the missing Condition in your new class, producing a valid policy document,
does the Gateway simply accept a valid policy statements with Conditions ?

**Comment by ashishdhingra** [comment]
POCO update, should be a quick fix.

**Comment by ashishdhingra** [comment]
@hauntingEcho / @yofitec Good morning. I was revisiting this feature request. Although, the issue appears to refer to missing `Condition` element as described in [IAM JSON policy elements: Statement](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_statement.html), the [Statement reference of IAM policies for executing API in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-calling-api-permissions) does not describe use of `Condition` element. The class [APIGatewayCustomAuthorizerPolicy](https://github.com/aws/aws-lambda-dotnet/blob/f6157b550b7f83ede4e0546d58237ef5c5549580/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerPolicy.cs#L8) is used in [APIGatewayCustomAuthorizerV2IamResponse](https://github.com/aws/aws-lambda-dotnet/blob/f6157b550b7f83ede4e0546d58237ef5c5549580/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerV2IamResponse.cs#L11C18-L11C57) and [APIGatewayCustomAuthorizerResponse](https://github.com/aws/aws-lambda-dotnet/blob/f6157b550b7f83ede4e0546d58237ef5c5549580/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerResponse.cs#L9C18-L9C52). None of the below reference links describe use of `Condition` element:
- [Working with AWS Lambda authorizers for HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html)
- [Statement reference of IAM policies for executing API in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-calling-api-permissions)

So I'm unsure if the `Condition` element should be supported in [APIGatewayCustomAuthorizerPolicy](https://github.com/aws/aws-lambda-dotnet/blob/f6157b550b7f83ede4e0546d58237ef5c5549580/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerPolicy.cs#L8) class. Could you please share any reference you might have where it mentions that `Condition` element should be supported in the executing API in API Gateway?

Thanks,
Ashish

**Comment by hauntingEcho** [comment]
Hi Ashish,

As this was at a previous job (and I am no longer using dotnet actively) I don't still have a whole lot of context for (or stake in) this issue anymore, but the main reasons would be:

* it refers to the statements as 'IAM policy' statements
* the documentation does link through to the IAM docs [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/permissions.html), in the first line
* the statement reference which you linked claims to just be for the action & resource formats (in the intro paragraph)

If it is true that API Gateway doesn't respect all parts of a regular IAM policy statement, despite continually referring to them as IAM policy statements, I'd expect to see that called out in the documentation rather than just assumed by omission in the API Gateway section - so this could also be resolved by clarifying the docs if it's true that API Gateway does not support `Condition`

**Comment by ashishdhingra** [comment]
Opened internal ticket P136777466 with service team for clarification.

**Comment by ashishdhingra** [comment]
Changes released in [Amazon.Lambda.APIGatewayEvents 2.7.1](https://www.nuget.org/packages/Amazon.Lambda.APIGatewayEvents/2.7.1). Also update to [Amazon.Lambda.Serialization.Json 2.2.2](https://www.nuget.org/packages/Amazon.Lambda.Serialization.Json/2.2.2)
