### ISSUE TITLE
Debugging the AWS lambda services created with .NET Core Web Api locally using AWS .NET Mock Lambda Test Tool

### ISSUE THREAD

**Issue by harikishan89** [aws/aws-lambda-dotnet#589]
How do I debug a AWS lambda services created with .NET Core Web Api locally using AWS .NET Mock Lambda Test Tool?

**Comment by clearwaterstream** [comment]
@harikishan89 ASP.NET Core lambda functions are regular ASP.NET Core apps, so you can run them using IIS or IISExpress locally. That is how I test. The APIGateway entry point (or ALB entry point) only gets used when deployed to AWS environment. As a side note, I'm working on a tool to allow inter-lambda communication locally by leveraging IIS Express. Still wip but I'm fairly close -- https://github.com/clearwaterstream/aws-lambda-aspdotnetcore-appmesh

**Comment by klaytaybai** [comment]
@clearwaterstream, thanks for providing some guidance.
Would you be interested in collaborating with AWS on your aws-lambda-aspdotnetcore-appmesh project?  The team hasn't had a chance to look it over yet, but I think @normj might be interested in talking more about it.

**Comment by clearwaterstream** [comment]
@klaytaybai absolutely :)

It would be very beneficial to have your team and @norm look it over and provide input on approach, etc.

**Comment by petarrepac** [comment]
Why IIS or IIS Express?
you don't need that
ASP.NET Core runs it's own HTTP server called Kestrel

- hit F5 
  - opens console
- fire requests using browser, Fiddler, Postman, ....

you can locally test all your HTTP processing, filters, controllers, business logic, .....
gets you 95% of the way
for those 5% you will always (no matter the tool) have to test in AWS environment

**Comment by clearwaterstream** [comment]
@petarrepac -- very good point. My old Beanstalk habit that makes not sense for Lambdas. In fact complicates things unnecessarily. I'll drop IIS Express and IIS from the solution.

**Comment by clearwaterstream** [comment]
I've upped the tools version to support 3.1, coinciding with https://aws.amazon.com/blogs/compute/announcing-aws-lambda-supports-for-net-core-3-1/

`dotnet tool update -g AWSLambda.AspNetCoreAppMesh.Catalog`

then update the `AWSLambda.AspNetCoreAppMesh` nuget pkg and off you go.

https://github.com/clearwaterstream/aws-lambda-aspdotnetcore-appmesh

**Comment by ashishdhingra** [comment]
Hi @harikishan89,

Good afternoon.

I don't think the Lambda Mock Test Tool can be used to test AWS Lambda APIs created using ASP.NET Core WebAPI.  As @clearwaterstream  and @petarrepac mentioned, the APIs can be tested using IIS/IIS Express/Kestrel. Lambda Mock Test Tool is used to test lambda functions outside the AWS Lambda environment. Please let me know if this provides enough guidance and if this issue could be closes.

Thanks,
Ashish
Please let me know if

**Comment by michaelsync** [comment]
It seems like Debug with IIS option has been removed from AWS VS toolkit. The only option there is only "Mock Lambda Test Tool".

**Comment by JoanVilarino** [comment]
I tried using that payload and it works but I my api has parameters in the way /add/5/10 ... the function is called but I get 0 for the parameters... where should I add them to the payload? Right now I'm setting both "resource" and "path" to /add/5/5 but it doesn't work...
