### ISSUE TITLE
Internal Error when calling through API Gateway using Feb 9 release

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#59]
I have rebuilt an base ASP.CORE application this morning with yesterdays release. When I say Base, I mean a new ASP.CORE 1.0 Web API with only the values controller).

I am using in project.json:

    "Amazon.Lambda.AspNetCoreServer": "0.9.0-preview1",
    "Amazon.Lambda.Tools": {
      "version": "1.2.0-preview1",
      "type": "build"
    }

The Invoke in test function works fine for api/values and returns the expected result and the log is recorded in CloudWatch.

Then I added the serverless.template and replaced the handler as per the Invent demo.

When I call via the Stack (i.e. https://xxx.execute-api.us-west-2.amazonaws.com/Prod/api/values). I get a 500 returned and nothing in the CloudWatch logs.

Anyone else seeing this?

Thanks,

Dave

**Comment by normj** [comment]
There was an issue on the CloudFormation service side that was causing the permissions to not be correctly setup when the CloudFormation stack was being created/updated. The fix has rolled out to most regions and you should see things back to normal after your next deployment.

**Comment by genifycom** [comment]
Thank you Norm. Appears to be fixed now.
