### ISSUE TITLE
Cannot invoke APIGatewayProxyFunction from within a running ASP.NET Core App (Kestrel)

### ISSUE THREAD

**Issue by clearwaterstream** [aws/aws-lambda-dotnet#590]
See https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/test/TestWebApp

Let's say within [ResourcePathController.cs](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/test/TestWebApp/Controllers/ResourcePathController.cs) I add a new method:

```csharp
[HttpGet]
public Task CallSelf()
{
    var requestContent = "read contents of values-get-all-apigateway-request.json";
    var context = new TestLambdaContext();

    var lambdaFunction = new ApiGatewayLambdaFunction();
    var request = JsonConvert.DeserializeObject<APIGatewayProxyRequest>(requestContent);
            
    var resp = await lambdaFunction.FunctionHandlerAsync(request, context);
}
```
[values-get-all-apigateway-request.json](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/test/Amazon.Lambda.AspNetCoreServer.Test/values-get-all-apigateway-request.json)

What I find is that I will always get a 400 response code when running this code _**within**_ a live ASP.NET Core App (i.e. Kestrel + IIS or IIS Express)

If I run the same code within a test project or console app -- all is good. I have a suspicion Kestrel and [LambdaServer](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/Internal/LambdaServer.cs) somehow collide. 

I get that in real world you will never have this scenario -- it's either Kestrel locally or LambdaServer when deployed on AWS, but why can't it be both.

Any idea how I can get this to work?

Thanks!!

**Comment by clearwaterstream** [comment]
Found the cause, not the solution. If Kestrel is configure to be behind IIS or IIS Express, it will ONLY accept requests from those reverse proxies. Hitting the routes directly will cause

`'MS-ASPNETCORE-TOKEN' does not match the expected pairing token`

error. So nothing to do with LambdaServer.

https://github.com/dotnet/AspNetCore.Docs/issues/9920

**Comment by clearwaterstream** [comment]
If anyone else is interested, here's the solution:

```csharp
var startupFilters = services.GetServices<IStartupFilter>();

string pairingToken = null;

if (startupFilters != null)
{
	var iisFilter = startupFilters.FirstOrDefault(x => x.GetType().Name == "IISSetupFilter");

	if(iisFilter != null)
	{
		var fieldInfo = iisFilter.GetType().GetField("_pairingToken", BindingFlags.Instance | BindingFlags.NonPublic);

		pairingToken = (string)fieldInfo.GetValue(iisFilter);
	}
}

var context = new TestLambdaContext();

var lambdaFunction = new ApiGatewayLambdaFunction();
var request = JsonConvert.DeserializeObject<APIGatewayProxyRequest>(requestContent);

if (request.Headers == null)
	request.Headers = new Dictionary<string, string>();

request.Headers["MS-ASPNETCORE-TOKEN"] = pairingToken; // That's the fix

var resp = await lambdaFunction.FunctionHandlerAsync(request, context);
```

**Comment by normj** [comment]
Interesting. I was testing with out IIS and didn't have any problems. Now I understand why. Can I ask what is your use case for this unusual pattern?

**Comment by normj** [comment]
@clearwaterstream  Ah I betting this dealing with your work on https://github.com/clearwaterstream/aws-lambda-aspdotnetcore-appmesh. I'm trying to carve some time to take a look into

**Comment by clearwaterstream** [comment]
It's not uncommon for developers to want to debug their APIs or microservices locally, that includes flows that span multiple microservices.

I've been using Invoke()  for cross-lambda communication found in `AmazonLambdaClient`. It's by no means a queue or a services bus, but for request-response it's perfect. No need to setup private API Gateways. Async flow is not too bad either, in many situations.

The trouble is, Invoke() does not work when debugging locally. No problem. I had an idea to marshall the `InvokeRequests` over http, locally, taking advantage of the fact that you can run ASP.NET Core apps under IIS or IIS Express locally.

The idea is to send the `InvokeRequest` locally over http, the receiver would then deserialize and extract the `APIGatewayProxyRequest`, and then use the `APIGatewayProxyFunction` to execute the request, returning the response  to be marshalled back to the caller.

It's work in progress, but I'm making headway: https://github.com/clearwaterstream/aws-lambda-aspdotnetcore-appmesh
