### ISSUE TITLE
Strongly typed object as request parameter

### ISSUE THREAD

**Issue by augustoporto** [aws/aws-lambda-dotnet#593]
Hello, how you doing?

I'm having an issue when my lambda function is being called from any source different from the Mock Lambda Test Tool. I'm currently trying to test my published lambda functions using Postman.

The function is not throwing any exception, but doesn't receive my object correctly, and instantiates a new one.

This is my function:

```
[LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
public async Task<APIGatewayProxyResponse> AddParceiroFunction(ParceiroRequest parceiroRequest)
{
           /// call the service using the request param
}
```

The request object model have only 3 string properties: Nome, Status and Credencial.

The JSON obejct I'm using to test is the same as I'm using in Mock Test:

```
{
	"Nome" : "Test Nome",
	"Status" : "Active",
	"Credencial" : "aaaa1234"
}
```

**Comment by msimpsonnz** [comment]
Can you publish a sample repo of the code you are using?
Have you tried using the "Test" function in the AWS Lambda Console, if you create a new test and select API Gateway Proxy, you can test without Postman just to confirm
https://docs.aws.amazon.com/lambda/latest/dg/getting-started-create-function.html#get-started-invoke-manually
