### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer.Internal.InvokeFeatures.Revision is always 0 causes `FeatureReferences` does not work.

### ISSUE THREAD

**Issue by jiabiao** [aws/aws-lambda-dotnet#596]
Please the the line below, the InvokeFeatures.Revision is always 0.
https://github.com/aws/aws-lambda-dotnet/blob/61a2f2417def737f5a84286be8aac2c7c3b2e77e/Libraries/src/Amazon.Lambda.AspNetCoreServer/Internal/InvokeFeatures.cs#L55

aspnetcore use `FeatureReferences` to cache Feature, when the Revision is not changed, it will use the  ```public TCache Cache;``` field.
https://github.com/dotnet/aspnetcore/blob/7cf264f25ae77d9a6b235a85c66dc13835e5b398/src/Http/Http.Features/src/FeatureReferences.cs#L69

This means that if `FeatureReferences` cached something, it will never be refreshed even the value has been changed. This happened when we use Nlog  `AspNetLayoutRendererBase` class:
https://github.com/NLog/NLog.Web/blob/7c6861d0cc9cf2560da7f905131330a0aebe2caa/src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs#L29

When the `Logger<APIGatewayProxyFunction>` logs somethings, because the `RequestServicesContainerMiddleware` has not been invoked. So the `HttpContext.RequestServices` is null. . 
Then the `DefaultHttpContext` use `FeatureReferences` to cache this null value.
And all subsequent access to `HttpContext.RequestServices` will get cached null value. because the the revision is not changed.(always 0) .

This cause many middlewares (AuthenticationMiddleware,  MvcMiddleware etc.) throw null exceptions because they depend on `HttpContext.RequestServices`.  

I created a sample lambda without any dependencies,  which can reproduce this issue.
please see https://github.com/jiabiao/AwsAspnetFeaturesRevisionIssue

**Comment by klaytaybai** [comment]
Thanks for all the info.  We'll try to get to this soon.

**Comment by normj** [comment]
Thanks for the example repository that really helps. 

On my dev machine I updated the logic to increment the revision number similar to the implementation in the aspnet core repository is done but that didn't make a difference with services returning null. Interestingly if I comment out your code in the test logger then services is not null in the request pipeline. 

I'm still looking into but wanted to give a status update of what I have found so far.

**Comment by normj** [comment]
I created the following PR to fix the issue. Thanks again for reporting the issue and providing the repo repository.

https://github.com/aws/aws-lambda-dotnet/pull/602.

I'll update this issue when the fix gets released. Out of curiosity what is your urgency for the fix? I would like to bundle this fix with the upcoming updates for .NET Core 3.1 but I don't want to leave you blocked.

**Comment by jiabiao** [comment]
Thanks @normj 
Thanks for the quick fix.   It's OK to bundle this fix with .NET Core 3.1.

**Comment by normj** [comment]
As part of today's .NET Core 3.1 release Amazon.Lambda.AspNetCoreServer 5.0.0 went out with this fix. Thanks for your patiences with bundling this with the 3.1 release.

**Comment by jiabiao** [comment]
Thanks, we are working on upgrading the project to .net core 3.1.

**Comment by normj** [comment]
Glad to hear about upgrading to .NET Core 3.1 but to be clear the fix in 5.0.0 is also valid for .NET Core 2.1 as well.
