### ISSUE TITLE
Projects fail now after installing VS2017

### ISSUE THREAD

**Issue by timheuer** [aws/aws-lambda-dotnet#6]
After I install VS2017 RC and try to create a new C# Lambda function using Visual Studio it fails with:

```
1>------ Rebuild All started: Project: EchoLambdaTest, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Users\timheuer\documents\visual studio 2015\Projects\EchoLambdaTest\EchoLambdaTest" --configuration Debug --no-dependencies --no-incremental
1>  Microsoft (R) Build Engine version 15.1.0.0
1>  Copyright (C) Microsoft Corporation. All rights reserved.
**1>MSBUILD : error MSB1009: Project file does not exist.**
1>  Switch: C:\Users\timheuer\documents\visual studio 2015\Projects\EchoLambdaTest\EchoLambdaTest
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

This previously worked prior to installing VS2017.

**Comment by normj** [comment]
This is happening because we are not writing a global.json file pointing to the project.json based dotnet SDK when we create the project. I hope to push that fix soon. In the meantime you can get around this by adding a global.json file to the solution directory with the following content.

```
{
  "sdk": {
    "version": "1.0.0-preview2-003133"
  }
}
```

**Comment by timheuer** [comment]
@normj still not working for me.  That just now shows me a dialog to download an SDK -- but the link doesn't take me anywhere where the download is available.  Should it be -003131 per https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md

**Comment by timheuer** [comment]
Or I think the .NET Core SDK is now in preview 3 -- I just downloaded it again and now I have 1.0.0-preview3-004056, but changing global.json to that I still get the original error I logged the issue with "Project not found"

**Comment by timheuer** [comment]
:-( looks like I'm screwed.  When I also follow instructions for #4 nothing changes.  The project still fails to build now saying it can't find the 1.0.0-preview2-003131 SDK in the progfiles\dotnet folder (which is true, it isn't there anymore).  If I update it to the installed version then it says it can't find a props file.  Help!

**Comment by timheuer** [comment]
Got it back working after a few different tries.  #4 and `dotnet restore` helped.
