### ISSUE TITLE
LogGroup name in Amazon.Lambda.Logging.AspNetCore

### ISSUE THREAD

**Issue by ymreplacegroup** [aws/aws-lambda-dotnet#600]
Hi, 
Is there any way to set LogGroup for Amazon.Lambda.Logging.AspNetCore?

**Comment by normj** [comment]
No, it always logs to the Log Stream that the Lambda service has assigned to the Lambda container.

**Comment by ymreplacegroup** [comment]
Is it possible to add this feature? I have set of lambda functions and want to group logs by environment and provider for further processing.

**Comment by normj** [comment]
Sorry but not likely. Amazon.Lambda.Logging.AspNetCore is a very thin wrapper around the ILambdaContext.Logger. It doesn't actually do anything with the CloudWatch Log. I would recommend going to the [Lambda forums](https://forums.aws.amazon.com/forum.jspa?forumID=186) and suggest they make the assigned Log Group for a Lambda function configurable. The more customer feedback they get helps drive their backlog.

**Comment by ymreplacegroup** [comment]
Ok. 
Thanks!
