### ISSUE TITLE
Migrate to HTTP API for API Gateway

### ISSUE THREAD

**Issue by raRaRa** [aws/aws-lambda-dotnet#601]
Hi. I was just curious what are the required steps to migrate from REST API to HTTP API?

AFAIK it should be as simple to change `serverless.template` to use HTTP API instead of REST API? It would be really neat if there could be some explanation in the `README`.

Thanks.

**Comment by normj** [comment]
If you are deploying via CloudFormation using the SAM resource `AWS::Serverless::Function` you just need to change the event type from `Api` to `HttpApi`.

The new HTTP API supports 2 different payload formats 1.0 and 2.0. The 1.0 format is very similar to REST API and is what `Amazon.Lambda.APIGatewayEvents` and `Amazon.Lambda.AspNetCoreServer` currently support. I'll try and get those packages updated for the 2.0 format soon.

**Comment by raRaRa** [comment]
Thanks for the detailed response @normj. I ran into the `AggregateException` issue that someone else ran into, with the latest version of `Amazon.Lambda.AspNetCoreServer`. I reported it to the closed issue. Just let me know if I should open a new issue for it.

**Comment by normj** [comment]
I think the issue is the SAM resource `AWS::Serverless::Function` is defaulting to the new 2.0 payload format which I haven't updated `Amazon.Lambda.APIGatewayEvents` and `Amazon.Lambda.AspNetCoreServer` for yet. To force the 1.0 format set the `PayloadFormatVersion` attribute to `1.0`. Sorry the Visual Studio intellisense will flag `PayloadFormatVersion` as an error as the schema hasn't gotten updated for the new 2.0 payload version.

```json
"AspNetCoreFunction": {
    "Type": "AWS::Serverless::Function",
    "Properties": {
    "Handler": "HttpApiTest::HttpApiTest.LambdaEntryPoint::FunctionHandlerAsync",
    "Runtime": "dotnetcore3.1",
    "CodeUri": "",
    "MemorySize": 512,
    "Timeout": 30,
    "Role": null,
    "Policies": [
        "AWSLambdaFullAccess"
    ],
    "Environment": {
        "Variables": {
        "LAMBDA_NET_SERIALIZER_DEBUG" : "true"
        }
    },
    "Events": {
        "ProxyResource": {
        "Type": "HttpApi",
        "Properties": {
            "Path": "/{proxy+}",
            "Method": "ANY",
            "PayloadFormatVersion" : "1.0"
        }
        },
        "RootResource": {
        "Type": "HttpApi",
        "Properties": {
            "Path": "/",
            "Method": "ANY",
            "PayloadFormatVersion" : "1.0"
        }
        }
    }
    }
}
}
```

**Comment by normj** [comment]
Version 2.0.0 of **Amazon.Lambda.APIGatewayEvents** has the classes `APIGatewayHttpApiV2ProxyRequest` and `APIGatewayHttpApiV2ProxyResponse` to support payload format 2.0.
