### ISSUE TITLE
What dotnet publish command are used in the aws lambda dotnet tools

### ISSUE THREAD

**Issue by max-market-engine** [aws/aws-lambda-dotnet#604]
Due to the command "dotnet lambda package" doesn't fit in our CI/CD process, I am trying to replicate some of the part of logic of what you guys have done. I am facing an issue of "permission denied" or "bootstrap is not found" after deploying lambda to aws. 

The problem is, if I use command "dotnet publish $PathToPorject --selft-contained true --configuration Release --runtime rhel.7.2-x64 --output $PathOfOutput", what is generated in the output folder seems different with what is generated by "dotnet lambda package". I compared the number of files and files, they seems to be the same. I use the same zip script to generate the zip file, however only my published files do not work. 

Environment: Windows Server 2012 and Windows 10
Scripts: Powershell (is used to publish .net core project)
python (is used to zip the files to deploy and change )
Framework: .net core 2.2
Lambda template: custom rumtime template

**Comment by normj** [comment]
Out of curiosity why doesn't "dotnet lambda package" fit in your CI/CD process?

Dealing with Linux file permissions on Windows is not great. The .NET Core API don't support the permissions when run on Windows, at least 2.1 doesn't, so we use a separate tool we wrote in Go to manage the file permissions and create the zip archive. The executable can be found [here](https://github.com/aws/aws-extensions-for-dotnet-cli/tree/master/src/Amazon.Lambda.Tools/Resources) and the source is [here](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/BuildLambdaZip/build-lambda-zip.go).

**Comment by max-market-engine** [comment]
> Out of curiosity why doesn't "dotnet lambda package" fit in your CI/CD process?
Becasue we want to build/generaete the package first, then using the same package (with app settings transformation per env) to deploy to different environments. "dotnet lambda package" does all the thing in one go, we actually want to seprate into publishing and zipping steps. 

I check your Go source code, I did the exactly the same thing in the python script to mange the file permissions and create the zip archive. The code snippet:
zinfo.external_attr = 0o0777 << 16 --> 777
zinfo.create_system = 3 --> Unix system 
But python seems not working. 
Is Go the only solution to create zip archive on Windows?

**Comment by normj** [comment]
I won't say it is the only solution but it is the one we found and went with it. Go was also easy to be portable for us.

**Comment by max-market-engine** [comment]
> I won't say it is the only solution but it is the one we found and went with it. Go was also easy to be portable for us.

Thanks for the information normj. I can confirm that Python, Powershell and batch scripts don't work for this case. I will try Golang.
