### ISSUE TITLE
Custom Websocket API name breaks send message in DotNet Lambda

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#605]
To reproduce. Create a Websocket API in API Gateway and assign a custom domain name.

Use Norms sample Websocket code from here https://github.com/normj/netcore-simple-websockets-chat-app

If you wscat to the URL shown by the api e.g. wscat -c wss://{YOUR-API-ID}.execute-api.{YOUR-REGION}.amazonaws.com/prod
then all works fine.
If you wscat to the custom domain name e.g. wscat -c wss://wss.mydomain.com then you will receive an error like this "Error posting message to JtaPLdOEyK4Acjg=: Credential should be scoped to a valid region, not 'us-east-1'"

If you specify a region in the AmazonApiGatewayManagementApiClient instance, then you will get a POST error to the connection.

This means that currently you cannot use a custom name for a WebSocket API.

Is this fixable?

**Comment by normj** [comment]
Interesting I haven't tried using CustomDomains before using AmazonApiGatewayManagementApiClient. Can you try setting the `AuthenticationRegion` property on the `AmazonApiGatewayManagementApiConfig` to the region the WebSocket API is deployed to. Something like this.

```csharp
var config = new Amazon.ApiGatewayManagementApi.AmazonApiGatewayManagementApiConfig
{
    AuthenticationRegion = Amazon.RegionEndpoint.USWest2.SystemName,
    ServiceURL = endpoint
};
var client = new Amazon.ApiGatewayManagementApi.AmazonApiGatewayManagementApiClient(config);

**Comment by genifycom** [comment]
Thanks Norm.

I tried this and found the following:
On the Line
await client.PostToConnectionAsync(postConnectionRequest);

Logs show:
Post to connection 0: J50O8dhXyK4CH9g=
Error posting message to J50O8dhXyK4CH9g=: No method found matching route prod/@connections/J50O8dhXyK4CH9g= for http method POST.

at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at PFWSServerSendMessage.Function.FunctionHandler(APIGatewayProxyRequest request, ILambdaContext context

So this seems to be the same result as if I set the region explicitly in the AmazonApiGatewayManagementApiClient 

The DynamoDB connection seems to be correct

**Comment by antsaia** [comment]
I'm having the same issue

**Comment by antsaia** [comment]
I'm having the same issues. The generic API endpoint works well for the ServiceURL, but if I switch it to the custom domain (which points to the same API GW stage endpoint) it throws exceptions.

**Comment by antsaia** [comment]
Ok I was able to get this working. If you follow @normj 's example above exactly, and only include ServiceURL and AuthenticationRegion in the AmazonApiGatewayManagementApiConfig, then it would correctly with the Custom Domain.

AmazonApiGatewayManagementApiConfig
{
    AuthenticationRegion = Amazon.RegionEndpoint.USWest2.SystemName,
    ServiceURL = endpoint
};

**Comment by genifycom** [comment]
This is how I have the code . Currently using Lambda DotNet Core 3.1 on USEast1

` var config = new Amazon.ApiGatewayManagementApi.AmazonApiGatewayManagementApiConfig
                {
                    AuthenticationRegion = Amazon.RegionEndpoint.USEast1.SystemName,
                    ServiceURL = endpoint
                };
                var client = new Amazon.ApiGatewayManagementApi.AmazonApiGatewayManagementApiClient(config);`

I am still getting "Error posting message to L3ZW_ezjIAMCFRw=: No method found matching route dev/@connections/L3ZW_ezjIAMCFRw= for http method POST."

What else can I try?

**Comment by bjorg** [comment]
Might be useful to post the IAM role JSON generated by SAM for this. Or, conversely, to build this in vanilla CloudFormation.

**Comment by antsaia** [comment]
@genifycom Make sure you have a deployment and stage defined in your serverless template. Also I've noticed on occasion I'm having to deploy the API stage manually, because updating the cloudformation through VS does not always deploy the API automatically. Not sure why.

`		"WebSockets" : {
			"Type": "AWS::ApiGatewayV2::Api",
			"Properties": {
				"Name": {
					"Fn::Join": ["", [{
						"Ref": "Environment"
					}, "WebSockets"]]
				},
				"ProtocolType": "WEBSOCKET",
				"RouteSelectionExpression" : "$request.body.action"
			}
		},
	        "WebSocketsDeployment" : {
			"Type": "AWS::ApiGatewayV2::Deployment",
                        "DependsOn" : [
				"SocketDefaultRoute", 
			],
			"Properties": {
				"ApiId" : { "Ref" : "WebSockets" }
			}
		},
		"WebSocketsStage" : {
			"Type": "AWS::ApiGatewayV2::Stage",
			"Properties": {
				"StageName" : "Prod",
                                "Description" : "Prod Stage",
                                "DeploymentId" : { "Ref" : "WebSocketsDeployment" },
				"ApiId" : { "Ref" : "WebSockets" },
				"AutoDeploy" : true
			}
		},`

**Comment by bjorg** [comment]
Not sure how SAM does it, but for [LambdaSharp](https://lambdasharp.net), I had to generate a checksum of the API Gateway resources in the template to ensure that if anything has changed, it gets a new deployment. Otherwise, if the deployment resource doesn't change, CloudFormation will not publish the API Gateway stage again. Might be a bug in SAM.

**Comment by ashishdhingra** [comment]
Hi @genifycom,

Good afternoon.

I was going through the issue backlog and came across this one. I see some inputs by @antsaia. Please advise if we are good to close this issue.

Thanks,
Ashish
