### ISSUE TITLE
Unable to invoke dotnet lambda using wsl command

### ISSUE THREAD

**Issue by eduherminio** [aws/aws-lambda-dotnet#606]
I have `Amazon.Lambda.Tools` installed in my WSL and if I just run `bash` and `dotnet lambda package` inside of it, everything works as expected.

However, when I try to script it using [`wsl` command](https://devblogs.microsoft.com/commandline/a-guide-to-invoking-wsl/): `wsl dotnet lambda package`, I get the following error as if I didn't have `Amazon.Lambda.Tools` installed.

> Could not execute because the specified command or file was not found.
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET Core program, but dotnet-lambda does not exist.
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Not that I can run `wsl dotnet build` or `wsl dotnet --info` without any isssue.

**Comment by bjorg** [comment]
Very interesting. I can confirm the same. I don't think that's a AWS lambda tooling issue though. Have you tried other dotnet tools? I suspect there is a difference between opening a shell in WSL and just running a command.

**Comment by bjorg** [comment]
And since you're kindred soul in using WSL, I just wanted to share this article on using _Amazon Linux 2_ on WSL, which enables _ReadyToRun_ compilation (which might well be the reason you're using it in the first place!).
https://dev.to/lambdasharp/building-aws-lambda-functions-with-net-core-3-1-on-amazon-linux-2-using-windows-terminal-53ld

**Comment by eduherminio** [comment]
> which enables ReadyToRun compilation (which might well be the reason you're using it in the first place!).

Guilty 😆 

Thanks!

**Comment by ashishdhingra** [comment]
Hi @eduherminio, 

Based on input by @bjorg, please let us know if this is still an issue. 

Thanks,
Ashish

**Comment by eduherminio** [comment]
Hi @ashishdhingra.
After some tests, I'm confident this is not only an AWS lambda issue.
Thanks.
