### ISSUE TITLE
Empty AppData folder created on macOS

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#61]
Hello,

I keep noticing that when using your amazing `dotnet lambda` command, it will create an empty folder at `~/AppData/Local/AWSToolkit`. I understand the `AppData` folder only exists on windows machines. Please have a look into this issue, thanks.

**Comment by normj** [comment]
Thanks I'll take a look.

**Comment by vellozzi** [comment]
This issue has been fixed.  Please upgrade to version 1.5 of Amazon Lambda Tools.
