### ISSUE TITLE
Allow APIGatewayProxyFunction to handle other event types

### ISSUE THREAD

**Issue by clearwaterstream** [aws/aws-lambda-dotnet#612]
As per [536](https://github.com/aws/aws-lambda-dotnet/issues/536), I get that `APIGatewayProxyFunction` and `ApplicationLoadBalancerFunction` are different animals and one cannot merge them into one. Coolio.

I'm looking at allowing my APIGatewayProxyFunction to handle other events, such as `SNSEvent`s, in addition to the usual `APIGatewayProxyRequest`s.

Why? Because for synchrounous invocation I'll go through API Gateway, and for async I'll use SNS. I may subscribe to other event types as well.

I could add two entry points, and deploy the function twice -- one configure with a different handler, re-using the same code. But that adds operational costs (deployment, monitoring, etc).

--- OR ---

I can have a "one-handler-to-rule-them-all". I created a "DreamHandler" (this is for the .NET Core 2.1 runtime):

```csharp
public class LambdaEntryPoint : APIGatewayProxyFunction
{
	protected override void Init(IWebHostBuilder builder)
	{
		builder.UseStartup<Startup>();
	}

	public async Task<Stream> DreamHandler(Stream stream, ILambdaContext context)
	{
		object resp = null;

                // CAN THIS COME FROM ILambdaContext.RequesType please?? (or other means)		
                var requestType = "APIGatewayProxyRequest";

		if (requestType == nameof(APIGatewayProxyRequest))
		{
			var req = Deserialize<APIGatewayProxyRequest>(stream);

			 // INVOKE the existing handler
                        resp = await FunctionHandlerAsync(req, context);
		}
		else if(requestType == nameof(SNSEvent))
		{
			var req = Deserialize<SNSEvent>(stream);

			resp = "ok";
		}
		// and so on ...

		var ms = new MemoryStream();

		using(var sw = new StreamWriter(ms, Encoding.UTF8, 1024, true)) // leave ms open...
		{
			using(var jw = new JsonTextWriter(sw))
			{
				var ser = JsonSerializer.Create();

				ser.Serialize(jw, resp);
			}
		}

                ms.Position = 0;

		return ms;
	}

	static T Deserialize<T>(Stream stream)
	{
		using(var sr = new StreamReader(stream))
		{
			using(var jr = new JsonTextReader(sr))
			{
				var ser = new JsonSerializer();

				return ser.Deserialize<T>(jr);
			}
		}
	}
}
```

* The above works. Tested behind an API Gateway. All Good.

* I cannot tell, however, what the request type is. I've interrogated `ILambdaContext` and nothing interesting there. Is there some place else I can infer this info from? If not, can this info be made available?

Thanks!!

**Comment by clearwaterstream** [comment]
P.S. I could peek at the json that's coming in and determine what's coming in before deciding to deserialize, but I was hoping for something cleaner....

**Comment by normj** [comment]
I understand your desire but the Lambda service doesn't send anything into the context to identity the message source.

Any type of change would have to come from the Lambda service and out of the scope of the .NET tooling/libraries. I would recommend posting on the service's forums https://forums.aws.amazon.com/forum.jspa?forumID=186

**Comment by clearwaterstream** [comment]
Understood, thanks for considering and for the tip re forums.
