### ISSUE TITLE
logging strings with line breaks prints multiple messages in cloudwatch

### ISSUE THREAD

**Issue by RMarinaro** [aws/aws-lambda-dotnet#613]
Hi there,

When I print a message with line breaks in it like this

```
nlogLogger.Info(@"nlog line
breaks
see how it
handles this");

LambdaLogger.Log(@"lambda logger line
break
see how
it handles it");

Console.WriteLine(@"long line
see how console write
handles it");
```
It looks like this in cloudwatch

![image](https://user-images.githubusercontent.com/864391/78310016-a3725500-751a-11ea-8eca-acbcf2d84f26.png)

I've tried using nlog, lambda's built in logger, and simple console.writes

I'm using a self contained 3.1 .netcoreapp using Amazon.Lambda.AspNetCoreServer 4.1.0  Is this intended behavior or a side-effect or running as a self contained app? Are there any work around like setting line breaks somehow at the logger level?

**Comment by ashishdhingra** [comment]
Hi @RMarinaro,

Good evening.

Thanks for posting the guidance question. Based on my research while going through various blogs/articles, any string after the new line character '`\n`' (even '`\n\r`' for DOS based systems) is split to the next entry in CloudWatch Logs. The below string has 4 new line characters:

```
@"nlog line
breaks
see how it
handles this"
```

And hence CloudWatch splits this into 4 separate entries. It appears that this behavior is controlled by CloudWatch. The workaround is to convert new line character '`\n`' to carriage return '`\r`', in which case, the CloudWatch would group the multi-line string into one entry.

Please let me know if this guidance helps and let me know if this issue could be closed.

Thanks,
Ashish

**Comment by kellertk** [comment]
This issue has not recieved a response in 2 weeks. If you want to keep this issue open, please just leave a comment below and auto-close will be canceled.

**Comment by RMarinaro** [comment]
thanks for your help, I used this layout and it worked for anyone that has the same issue
`${replace-newlines:replacement=\r:${message}}`

**Comment by catalingavan** [comment]
> thanks for your help, I used this layout and it worked for anyone that has the same issue
> `${replace-newlines:replacement=\r:${message}}`

hi. Can you provide a sample code, please?

**Comment by RMarinaro** [comment]
So in my case I am using NLog but this was my solution

NLog.config

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true">
  <variable name="CustomLayout" value="${callsite}:${callsite-linenumber}|${machinename}:tid-${threadid}|${longdate}|${level}|${replace-newlines:replacement=\r:${message}}|${exception:format=tostring}"/>


  <targets>
    <target name="logconsole" xsi:type="ColoredConsole" layout="${CustomLayout}" />
  </targets>

  <rules>
        <logger name="*" minlevel="Info" writeTo="logconsole" />
  </rules>

</nlog>

```

Then you can just configure NLog in the main as you would normally

`            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`

**Comment by gregtayl** [comment]
Is there a workaround for this? We're running into the same problem, using .NET 5 lambdas.

**Comment by RMarinaro** [comment]
It would be the same principle, you need to replace all \n with \r 

If you are using standard MS logging you will need to write your own logger. 

https://stackoverflow.com/questions/44230373/is-there-a-way-to-format-the-output-format-in-net-core-logging

**Comment by olexxxiy** [comment]
> It would be the same principle, you need to replace all \n with \r

Thanks, this actually helped.
