### ISSUE TITLE
AWS Lambda Templates for API Gateway Proxy

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#618]
In the next release of the AWS Toolkit for Visual Studio could you please include a template for use with API Gateway (proxy integration)?

This is a common use case and a template would help.

Thank you

**Comment by normj** [comment]
Thanks for the feedback on the templates. I have been wanting to expand on them. 

How would this template be different then the existing `Empty Serverless` template which sets up an API Gateway with proxy integration?

**Comment by genifycom** [comment]
I was thinking of the Lambda Functions. In those blueprints there are no gateway examples.

Something along the lines of:

/// <summary>
/// API Gateway example for AWLS Lambda Function proxy integration
/// </summary>
/// <param name="apigateway_event">Incoming API Gateway event</param>
/// <param name="context"></param>
/// <returns></returns>
public APIGatewayProxyResponse FunctionHandler(APIGatewayProxyRequest apigateway_event, ILambdaContext context)
{
	//Output format of a Lambda function for proxy integration
	var response = new APIGatewayProxyResponse
	{
		StatusCode = (int)HttpStatusCode.OK,
		Body = JsonConvert.SerializeObject("Lambda function return"),
		Headers = new Dictionary<string, string> { { "Content-Type", "application/json" }, { "Access-Control-Allow-Origin", "*" } }
	};
	return response;
}

**Comment by 3GDXC** [comment]
@normj would also be good to have an example to show #WebSockets usage

**Comment by bjorg** [comment]
The payloads are _almost_ identical. I use the same base class for handling REST API and WebSocket invocations.
