### ISSUE TITLE
Lambda/SecurityToken Method not found: Amazon.Runtime.RequestRetryMode

### ISSUE THREAD

**Issue by JaydenMaalouf** [aws/aws-lambda-dotnet#619]
With the latest version version of AWSSDK.SecurityToken (v3.3.104.57): instancing any AWSSDK client inside of a Lambda function will cause an exception to be thrown.

## Expected Behavior
When attempting to instance any SDK client inside a Lambda function, whilst using an assumed role (which requires SecurityToken package), the application will instance said client with the assumed credentials and everything will be happy days!

## Current Behavior
As soon as the Lambda function is called and the AWSSDK Client is instanced a System.MissingMethodException will be thrown.

**Message:** Method not found: 'Amazon.Runtime.RequestRetryMode Amazon.Runtime.IClientConfig.get_RetryMode()'.
**Inner Exception:** NULL
**Stack Trace:** 
```
at Amazon.EC2.AmazonEC2Client.CustomizeRuntimePipeline(RuntimePipeline pipeline)
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
```

## Possible Solution
Rolling back AWSSDK.SecurityToken to a previous package version resolves the issue.

## Steps to Reproduce (for bugs)
Create a blank Lambda (with a function) with AWS Visual Studio Toolkit
Add AWSSDK.EC2 NuGet package
Add AWSSDK.SecurityToken v3.3.104.57 NuGet package
Create a private readonly variable inside the Lambda function
```csharp
private readonly AmazonEC2Client _ec2Client = new AmazonEC2Client();
```
Run the Lambda Mock and execute the function.
Exception will be thrown when the client is being instanced.

## Context
Latest SecurityToken package is unusable (locally) in this state.

## Your Environment
Tested with:
Amazon.Lambda.Core v1.1.0
Amazon.Lambda.Serialization.Json v1.7.0
AWSSDK.EC2 v3.3.168.16
AWSSDK.SecurityToken 3.3.104.57
.NET Core 2.1
Visual Studio Professional 2017

**Comment by normj** [comment]
Version 0.10.1 of the test tool is out with the fix. If you close and reopen the Solution in Visual Studio that should automatically update you to the latest version with the fix.

**Comment by JaydenMaalouf** [comment]
I've updated to the latest and it is no longer throwing the exception from above - it is throwing the missing method exception on the Microsoft.Extensions.Logging package but it looks like that is due to our implementation rather than the Lambda Mocking Tool.

Thanks so much! Absolute legend.
