### ISSUE TITLE
 Amazon.Lambda.TestTool 0.10.1 is not working but 0.9.5 is

### ISSUE THREAD

**Issue by matsola** [aws/aws-lambda-dotnet#623]
Hi,

We have experienced a problem when upgrading from 0.9.5 to 0.10.1 for Amazon.Lambda.TestTool.

We are working in Rider and when we try to start we get a couple of different error messages.

`A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/.../.dotnet/tools/.store/amazon.lambda.testtool-2.1/0.10.1/amazon.lambda.testtool-2.1/0.10.1/tools/netcoreapp2.1/any/'`

And when trying to debug: dgbshim directory missing. But this might be releated to Rider.

Has anyone any idea why this might be happening?

If i add the file `Amazon.Lambda.TestTool.runtimeconfig.json` to `/Users/.../.dotnet/tools/.store/amazon.lambda.testtool-2.1/0.10.1/amazon.lambda.testtool-2.1/0.10.1/tools/netcoreapp2.1/any/` I get a bit further and actually is able to run the application but dotnet crashes.

```
❯ dotnet --version
3.1.201
```

`❯ dotnet --list-sdks`
```
2.2.100 [/usr/local/share/dotnet/sdk]
2.2.401 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]
3.1.100 [/usr/local/share/dotnet/sdk]
3.1.201 [/usr/local/share/dotnet/sdk]
```

Running Mac OSX 10.15.4

More details will be added soon.

**Comment by MujahidRashid** [comment]
Jetbrains rider 2019.3.4
Configuration done according to the documentation in this link 
https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider

**Comment by Jono20201** [comment]
Also encountering this issue.

**Comment by normj** [comment]
Thanks for letting me know. The documentation on the README file was out of date which has now been updated. As part of the `0.10.0` the tool was broken up to support both .NET Core 3.1 and 2.1. In the old version Amazon.Lambda.TestTool.dll was the entry point assembly but now that is just a class library. There is a separate entry assembly for either .NET Core 3.1 or 2.1 called `Amazon.Lambda.TestTool.WebTesterXX.dll`. Check out the updated [README](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider) file and let me know if that clears things up.

**Comment by matsola** [comment]
Thanks for the update.

Now it seems to be working! 

Thanks!
