### ISSUE TITLE
FunctionHandlerAsync boxing/unboxing of request/response

### ISSUE THREAD

**Issue by 3GDXC** [aws/aws-lambda-dotnet#625]
I'm attempting to creating a generic function handler, that accepts a (boxed) request and determines the type (unboxed) object information; based on the unboxed type information the handler then creates and marshals calls to internal classes derived from the ApplicationLoadbalancer, APIGatewayProxy thus allowing the code to be deployed in a number of configurations.

I'm experiencing an issue when the FunctionHandlerAsync is called, the expected request is not (boxed) with the correct type information, the object type information is always JsonElement ?

How can I identify the boxed type information?

**Comment by normj** [comment]
Sorry I'm not understand what you mean by boxing/unboxing in this context. Can you provide a code snippet?

**Comment by 3GDXC** [comment]
@normj I'm wanting to allow a Lambda function handler to allow any object type so the function can be triggered from the api gateway, application load balancer and/or any other type of source; at present the Lambda entry point doesn't support method overloading based of parameter types;  therefore the I was hoping having a method signature of Task<object> FunctionHandler(object request, ILambdaContext context) would allow/supply the boxed object and metadata on the object would allow the FunctionHandler to determine the correct type.  However this is not the case.

How can I determine what type of the request has been supplied, when accessing the object (stream) directly ?

**Comment by petarrepac** [comment]
Not ideal, but works.....


        private static string GetEventPayload(Stream stream)
        {
            string payload;
            using (var streamReader = new StreamReader(stream))
            {
                payload = streamReader.ReadToEnd();
            }

            return payload;
        }

        private static ScheduledEventRequest GetScheduledEventRequest(string payload)
        {
            try
            {
                ScheduledEventRequest request = JsonConvert.DeserializeObject<ScheduledEventRequest>(payload);

                // verify that it is an ScheduledEvent
                if (request?.Source == "aws.events")
                {
                    return request;
                }
                else
                {
                    return null;
                }
            }
            catch
            {
                return null;
            }
        }



        // this lambda is invoked by:
        // scheduled event
        // s3 event 
        public async Task FunctionHandlerAsync(Stream stream, ILambdaContext context)
        {
        	string payload = GetEventPayload(stream);
        	Console.WriteLine("Received payload on next line.");
        	Console.WriteLine(payload)	
        	var scheduledEventRequest = GetScheduledEventRequest(payload)	
        	if (scheduledEventRequest != null)
        	{
        	    await CallFoo(scheduledEventRequest, _settings);
        	}
        	else
        	 ..
		}

**Comment by 3GDXC** [comment]
@petarrepac thanks, but how do I know what object was sent to the handler without deserializing? do I need to try and deserialize the stream for each type and check the property values? or this there metadata within the serialized object that is common and can be used to determine the type? possible even something in the ILambdaContext having metadata about the request object source/type ?

**Comment by petarrepac** [comment]
> but how do I know what object was sent to the handler without deserializing? 

AWS Lambdas are always invoked using JSON, as far as I know, 
so you need to take a look in JSON to see what, who, ....

> do I need to try and deserialize the stream for each type and check the property values? or this there metadata within the serialized object that is common and can be used to determine the type? possible even something in the ILambdaContext having metadata about the request object source/type ?

I don't think there is such metadata
look here: 
[https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Core](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Core)

also, I think you can yourself call a Lambda with any JSON payload you want

you probably know in advance who will be calling your lambda so you can make a test call, look in CW and see what are the properties and create a C# class for that

at some point you probably want to move from untyped JSON into strongly-typed .NET object instance

**Comment by 3GDXC** [comment]
@normj would it at all be possible to consider adding a EventBase abstract class to the Amazon.Lambda.Core and have every event class (including APIGatwayProxyRequest etc) derive from this base; as this would then allow the deserializer to know the type of the EventSource (as with S3, SQS, SNS) and in turn allow better support for strong typing and method overloading.

**Comment by petarrepac** [comment]
@3GDXC 
deserializer takes in JSON and returns and instance of type T
it cannot look into base class to help him as that info in in destination, not source

**Comment by 3GDXC** [comment]
@petarrepac that is not correct as deserialization returns a object if you don't supply it the a T and you can cast the object into a base case that can give you access to type information and subsequently create the strongly typed accordingly.  your also able to deserialize to dynamic etc. I've done this a few time when wrapping RESTful APIs the key is to have some metadata in a consistent location/property that allows this and deriving from a base class would provide that.

**Comment by petarrepac** [comment]
Pseudo code:

	class A
	{
	   public string FirstName {get; set;}
	}

	class B
	{
	   public string FirstName {get; set;}
	}

	object someObject = deserializer.GetInstance("{FirstName: 'John'}");

	Console.WriteLine(someObject.GetType().ToString());

what is the output?

**Comment by 3GDXC** [comment]
@petarrepac you mis the point you can the serialized object you show has no metadata type infomation; if you have a property name "objecType" : "someNamespace.someclass" you get do Type.GetType("someNamespace.someclass") and return a strong type without hardcoding the deserializer with T and the returned object type is then shown a the someNamespace.someclass

**Comment by 3GDXC** [comment]
@petarrepac happy to do a repo to show just this; if you like

**Comment by petarrepac** [comment]
>  if you have a property name "objecType" : "someNamespace.someclass"
if you mean above as part of JSON, be aware you cannot change JSON coming into Lambda

**Comment by 3GDXC** [comment]
@petarrepac this is the problem as I would have expected some type information somewhere to be provided with regards to the source of the calling event/trigger and therefore be able to deduce from this the type of the payload instead of having to attempt to check the payload for multiple property values.  :'(

**Comment by petarrepac** [comment]
@3GDXC 
JSON payloads are not defined by the AWS .NET team and cannot be bound to particular stack (Java, .NET, python, GO, ...)

therefore JSON cannot contain assemblyName, namespace, class name specific to .NET

**Comment by 3GDXC** [comment]
@petarrepac again you misunderstand; the metadata around the source of the event/request is not bound to the language; I only used the above as an example to your point about deserialization; what I'm asking here is what can I use to allow my code to determine what/were the payload has come from?  TBH I can't believe there is no way to find what has triggered the lambda and/or serverless application; maybe this is not the correct place to ask the question, but given I'm working in .netcore  I was hoping it was.

**Comment by bjorg** [comment]
You will need to deserialize the object (e.g. `JsonDocument`) and inspect it. To make matters worse, you'll have to guess on the type using heuristics since the messages contains no hints to what it is.

I had to do something similar in my custom resource base class since CloudFormation allows either an SNS topic or Lambda function as `ServiceToken`. However, the payloads are quite different. So the base class has to inspect the message to determine how it came in.
https://github.com/LambdaSharp/LambdaSharpTool/blob/master/src/LambdaSharp/CustomResource/ALambdaCustomResourceFunction.cs#L233

**Comment by grahamehorner** [comment]
@normj @bjorg @petarrepac @3GDXC I believe that the ILambdaContext may have something your looking for i.e. the InvokedFunctionArn this may allow you to map the event type by pattern matching and therefore given some indication with regards to what strongly typed object to use when deserializing.  I'll defer to @normj for more information as I'm new to the AWS space and I'm just getting to grips with the .netcore sdks at present.

**Comment by ashishdhingra** [comment]
Hi @3GDXC,

I think what @bjorg and @petarrepac mentioned point to the correct understanding. Please let me know if any further input is required and if we are good to close this issue.

Thanks,
Ashish
