### ISSUE TITLE
Amazon.Lambda.Serialization.SystemTextJson.LambdaJsonSerializer options customizations ignore when in debug mode

### ISSUE THREAD

**Issue by rpopovych** [aws/aws-lambda-dotnet#628]
I am trying to use custom serialization options in the new `Amazon.Lambda.Serialization.SystemTextJson.LambdaJsonSerializer`. It looks like they are ignored in Debug mode (LAMBDA_NET_SERIALIZER_DEBUG = true).

```
public class LambdaSerializer : Amazon.Lambda.Serialization.SystemTextJson.LambdaJsonSerializer
{
    public LambdaSerializer() : base(Customizer) { }

    private static void Customizer(JsonSerializerOptions options)
    {
        options.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;
    }
}
```

https://github.com/aws/aws-lambda-dotnet/blob/65ba2c967214fa5c88e9d3717fc6efdba3afc01c/Libraries/src/Amazon.Lambda.Serialization.SystemTextJson/LambdaJsonSerializer.cs#L74-L88

**Comment by normj** [comment]
I'm addressing this issue with this PR https://github.com/aws/aws-lambda-dotnet/pull/636 that also addressing the camel casing issue.

**Comment by normj** [comment]
Version 2.0.0 of Amazon.Lambda.Serialization.SystemTextJson is out with the change. Main take away it update the serializer class to be `DefaultLambdaJsonSerializer`.

I also published a blog post that has a section describing the change.
https://aws.amazon.com/blogs/developer/one-month-update-to-net-core-3-1-lambda/

**Comment by rpopovych** [comment]
Thank you!
