### ISSUE TITLE
Sending/Receiving KinesisEvent with .NET Core throws System.InvalidOperationException : Timeouts are not supported on this stream

### ISSUE THREAD

**Issue by tofalck** [aws/aws-lambda-dotnet#63]
I have two lambda functions. 

One is a Kinesis producer and sends kinesis events using the AmazonKinesisClient.PutRecordAsync method.

It seems to be breaking consistently when trying to serialize the event with a:

```csharp
Newtonsoft.Json.JsonSerializationException : Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'.
  ----> System.InvalidOperationException : Timeouts are not supported on this stream.
.
.
.
   at Amazon.Lambda.Serialization.Json.JsonSerializer.Serialize[T](T response, Stream responseStream) in D:\Jenkins\jobs\lambda-packages\workspace\LambdaSandboxCoreCLRApi\Libraries\src\Amazon.Lambda.Serialization.Json\JsonSerializer.cs:line 35
```
To investigate I have been trying to reproduce the circumstances with this test (I have borrowed the Base64ToMemoryStream method from the AWS SDK..) and it fails consistently on jsonSerializer.Serialize(originalKinesisEvent, ms):

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Amazon;
using Amazon.Lambda.KinesisEvents;
using Newtonsoft.Json;
using NUnit.Framework;
using JsonSerializer = Amazon.Lambda.Serialization.Json.JsonSerializer;

namespace Test
{
    [TestFixture]
    public class TestOfJsonSerializer
    {
        [Test]
        public void Serialize_UsingKinesisEvent_RecordDataShouldSerializeAndDeserializeWithNoError()
        {
            var originalKinesisEvent = new KinesisEvent()
            {
                Records = new List<KinesisEvent.KinesisEventRecord>()
                    {
                        new KinesisEvent.KinesisEventRecord()
                        {
                            AwsRegion = RegionEndpoint.EUCentral1.SystemName,
                            EventId = "shardId-000000000000:49568167373333333333333333333333333333333333333333333333",
                            EventName = "aws:kinesis:record",
                            EventSource = "aws:kinesis",
                            EventSourceARN = "arn:aws:kinesis:us-east-1:123456789012:stream/simple-stream",
                            EventVersion = "1.0",
                            InvokeIdentityArn = "arn:aws:iam::123456789012:role/LambdaRole",
                            Kinesis = new KinesisEvent.Record()
                            {
                                ApproximateArrivalTimestamp = DateTime.Now,
                                Data = Base64ToMemoryStream(Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new {Text = "SomeText"}))))
                            }
                        }
                    }
            };

            using (var ms = new MemoryStream())
            {
                var jsonSerializer = new JsonSerializer();

                //This breaks consistently...
                jsonSerializer.Serialize(originalKinesisEvent, ms);

                var base64String = Convert.ToBase64String(ms.ToArray());

                using (var base64ToMemoryStream = Base64ToMemoryStream(base64String))
                {
                    var deserializedKinesisEvent = jsonSerializer.Deserialize<KinesisEvent>(base64ToMemoryStream); ;
                    Assert.IsNotNull(deserializedKinesisEvent);
                }
            }
        }

        public static MemoryStream Base64ToMemoryStream(string dataBase64)
        {
            var dataBytes = Convert.FromBase64String(dataBase64);
            var stream = new MemoryStream(dataBytes);
            return stream;
        }
    }
}
```

My project.json:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Amazon.Lambda.Core": "1.0.0*",
    "Amazon.Lambda.TestUtilities": "1.0.0*",
    "NUnit": "3.6.0",
    "dotnet-test-nunit": "3.4.0-beta-3",
    "Newtonsoft.Json": "9.0.2-beta2"
  },

  "testRunner": "nunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by PavelSafronov** [comment]
The `KinesisEvent` objects are designed to be deserialized from JSON that a Lambda function receives as Kinesis events, and the [Amazon.Lambda.Serialization.Json](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Serialization.Json) package includes [special-case code](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Serialization.Json/AwsResolver.cs#L31-L44) to properly deserialize the `MemoryStream Data` property. If you need to serialize these objects, you'll need to implement similar logic when serializing.

That being said, aside from testing, is there a reason that you need to create Kinesis event JSON? These events should always be coming from AWS services like Kinesis, hence why we did not include this special serialization logic.

**Comment by tofalck** [comment]
@PavelSafronov,
I understand that the aws machinery takes care of serialization in both ends and eventually drops the deserialized Kinesis event object into the receiving lambda..
It uses that special case JsonSerializer which I am also using in my unit test. 
My lambda's are marked with the attribute telling aws to use that serializer. 

Of course the kinesis event object is delivered to the receiving lambda, but it also fails at some point when I read the memory stream with the shown exception - at least in my setup. 

My lambda's are async Task<>. 

I therefore began investigating hence my serialization test, which I believe reproduces the exception that is being thrown. 

I noticed that in your Kinesis event unit tests you don't seem to be serializing but only deserializing from a json file with two records.

**Comment by PavelSafronov** [comment]
Serializing `KinesisEvent`and other similar event objects is not the goal of these sets of libraries, so the specific scenario you are testing is not intended to work, hence why you're seeing these exceptions.

If you want to serialize these events you'll need to implement the custom logic similar to the [existing deserialization code](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Serialization.Json/AwsResolver.cs#L31-L44).

If you feel that this is an important use-case and others may benefit from it, you can submit a pull-request adding serialization support to the [Amazon.Lambda.Serialization.Json package](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Serialization.Json).

**Comment by tofalck** [comment]
I have no interest in serializing the kinesis event. 

So I am sorry if I haven't been unclear on this. 

In my receiving lambda I loop through the records and write new Kinesis records to another stream using PutRecordAsync, which I suppose serialize the record object into a Kinesis event json using the special case json serializer? This scenario does not go well and throws the aforementioned exception hence my investigation trying to isolate the issue. 
Any suggestions?

**Comment by rknewbow** [comment]
Unless I'm missing something, it seems like you should be getting the data out of the incoming KinesisEvent object and then building a new PutRequestRequest using that data. You shouldn't be reserializing the entire Kinesis event. Something like the following.

```C#
        public async Task ReceiveRecords(KinesisEvent kinesisEvent, ILambdaContext context)
        {
            foreach (var record in kinesisEvent.Records)
            {
                // Do something with the record

                // Send the data to a different Kinesis stream
                var putRecordRequest = new PutRecordRequest
                {
                    StreamName = "DifferentStream",
                    Data = record.Kinesis.Data
                };

                await this.kinesisClient.PutRecordAsync(putRecordRequest);
            }
        }
```

**Comment by tofalck** [comment]
Which is exactly what I am doing, although I am new'ing a MemoryStream containing the context specific data for the particular stream. 
I'll try to find time to do a full sample project to show case the issue.

**Comment by rknewbow** [comment]
```
using (var ms = new MemoryStream())
            {
                var jsonSerializer = new JsonSerializer();

                //This breaks consistently...
                jsonSerializer.Serialize(originalKinesisEvent, ms);

                var base64String = Convert.ToBase64String(ms.ToArray());

                using (var base64ToMemoryStream = Base64ToMemoryStream(base64String))
                {
                    var deserializedKinesisEvent = jsonSerializer.Deserialize<KinesisEvent>(base64ToMemoryStream); ;
                    Assert.IsNotNull(deserializedKinesisEvent);
                }
            }
```

From your test code above `jsonSerializer.Serialize(originalKinesisEvent, ms);` will not serialize without you creating a custom converter to handle the MemoryStream object. This is not a KinesisEvent issue, but simply the default JSON.Net serialization behavior. To serialize the MemoryStream you have to first convert it to a Byte array and then JSON.Net will serialize that as a Base 64 encoded string.

See this SO for details on that:
[http://stackoverflow.com/questions/30331027/newtonsoft-json-net-how-to-serialize-content-of-a-stream](url)

When the PutRecordRequest is marshalled by the SDK that conversion is handled for you. This has nothing to do with the KinesisEvent or even JSON.Net. The KinesisEvent class exists solely as a helper class to *receive* Kinesis events in a C# Lambda. You're going to get the same raw event data whether your Lamdba is written in Java, Python, Node.js etc... There is nothing on the sender side that would be populating and serializing a C# specific KinesisEvent object.

As mentioned before, I can't think of a reason why you would need to serialize the KinesisEvent except for testing where you want to store the event in a file similar to what the KinesisEvent unit test does. Even though you said you are doing exactly what I posted before, it seems like you are trying to explicitly serialize an object somewhere in your code which contains an instance of MemoryStream.

Hope that helps. Sorry for the long-winded response.

Ryan

**Comment by tofalck** [comment]
Oh boy - I had a log statement buried somewhere to log the incoming KinesisEvent object where it got serialized. 
My bad. 
But as a closing remark I really think the serializer should be updated to support serialization of the KinesisEvent type too for this very reason....
Anyway - closing this issue. Thanks for the input 👍
