### ISSUE TITLE
API gateway Base URL does not include stage

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#630]
If you create an "AWS Serverless Application" with blueprint "ASP.NET Core Web App" and "Publish to AWS Lambda", you will get back a URL from the stack that includes your stage

e.g. https://jnv67fw1ij.execute-api.us-east-1.amazonaws.com/Prod

If your page (say the Index page) includes Javascript to make an Ajax call back to the index page

e.g
fetch('/Index?handler=List');
or
fetch('~/Index?jhandler=List');
or
fetch('Index?jhandler=List');

Then the Ajax call will fail with a 403. Examination of the URL shows that the stage has been excluded from the call.

e.g. https://jnv67fw1ij.execute-api.us-east-1.amazonaws.com/Index?handler=List

So while this code works fine in development, in Lambda the code does not work.

Why has the stage been dropped from the base URL? How do people deal with this?

In  Javascript, it is not easy to tell the current environment (Windows or Linux or Lambda) in order to change the URL to include the stage.

Suggestions?

**Comment by martonx** [comment]
Use ./Index?handler=List

**Comment by genifycom** [comment]
Thank you for the response. Just tried it and same result.

**Comment by genifycom** [comment]
Workaround is to use the follow JavaScript

var baseurl = window.location.origin + window.location.pathname;
baseurl += baseurl.endsWith("/") ? "" : "/"

This does include the stage.
