### ISSUE TITLE
AW Lambda 3.1 and PublishReadyToRun

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#631]
Is there any documentation on how to use AOT/PublishReadyToRun in AWS Lambda dotnet 3.1?

Thanks

**Comment by bjorg** [comment]
You have to compiled on _Amazon Linux 2_ to enable _ReadyToRun_.

I wrote up a guide here on using _Amazon Linux 2_ with WSL: https://dev.to/lambdasharp/building-aws-lambda-functions-with-net-core-3-1-on-amazon-linux-2-using-windows-terminal-53ld

You will still need to pass in the appropriate arguments to enable _ReadyToRun_ compilation. Alternatively, [LambdaSharp](https://lambdasharp.net/) automatically compiles _ReadyToRun_ binaries when used on _Amazon Linux 2_.

**Comment by esukirno** [comment]
@bjorg. I used amazonlinux:2 docker image to publish dotnet core 3.1 lambda.
The only time I can get dotnet core 3.1 lambda with ReadyToRun enabled is with self contained set to true. 
I tried publishing the same lambda with self contained set to false and the lambda threw an error with the following warning

[WARN] (invoke@invoke.c:297 errno: Address family not supported by protocol) run_dotnet(dotnet_path, &args) failed

Does this mean that we can only use ReadyToRun with self contained set to true?

**Comment by bjorg** [comment]
@esukirno You have to specify the runtime as well.
```
dotnet build --configuration Release --framework netcoreapp3.1 --runtime linux-x64 /p:PublishReadyToRun=true /p:TieredCompilation=false /p:TieredCompilationQuickJit=false
```
-or- if you use [AWS Lambda Tools](https://aws.amazon.com/blogs/developer/net-core-global-tools-for-aws/)
```
dotnet lambda --configuration Release --framework netcoreapp3.1 --msbuild-parameters "/p:PublishReadyToRun=true /p:TieredCompilation=false /p:TieredCompilationQuickJit=false"
```

**Comment by esukirno** [comment]
Cheers. That was the same command that I use. Possibly I was not using the right docker image. 

I managed to publish ReadyToRun package (non self contained) using AWS CodeBuild.

**Comment by bjorg** [comment]
@esukirno if this is no longer an issue, please consider closing the ticket.

**Comment by simon10says** [comment]
Hi @bjorg , I'm having some problem trying to package using amazonlinux:2 docker image with the `dotnet lambda` command. 

Basically, I'm using `dotnet lambda package-ci` command, but it seems like the `--msbuild-parameters` is not triggering at all. However, with `dotnet lambda package` command, it works fine. I've opened an issue [here](https://github.com/aws/aws-lambda-dotnet/issues/663#issue-613388019). Could you please advise?

**Comment by bjorg** [comment]
@simon10says I would look at the code for the tool and trace down the command. It's possible the `--mdbuild-parameters` option is not being recognized. Unfortunately, the tool doesn't error out when an unrecognized option is passed in. It just ignores it.

This should be a good place to start: https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/PackageCICommand.cs

If need be, clone the repo, download it and add debugging statements as needed. If it is indeed a bug in the `dotnet lambda` tool, I'm sure the AWS .NET team would appreciate a pull request.

**Comment by simon10says** [comment]
@bjorg , I'm still quite new with aws lambda and don't have enough skill yet to contribute ... however, taking a look at the code logic and hint from [this issue](https://github.com/aws/aws-extensions-for-dotnet-cli/issues/103#issuecomment-593413072), it seems like  [this logic](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/cd08dd91d6acfef94538fdc91c04098cae4d06c4/src/Amazon.Lambda.Tools/TemplateProcessor/TemplateProcessorManager.cs#L230) is the issue.

```c#
// If the project is in the same directory as the CloudFormation template then use any parameters
// there were specified on the command to build the project.
if (IsCurrentDirectory(field.GetLocalPath()))
{
      if (!string.IsNullOrEmpty(this.DefaultOptions.TargetFramework))
          command.TargetFramework = this.DefaultOptions.TargetFramework;
                
      command.Configuration = this.DefaultOptions.Configuration;
      command.DisableVersionCheck = this.DefaultOptions.DisableVersionCheck;
      command.MSBuildParameters = this.DefaultOptions.MSBuildParameters;
}
```
It seems like the cloudformation template needs to be in the same location as the Project. If not, it will not only ignore `msbuild-parameters`, but also `configuration` and `disableversioncheck`.  I can't figure out the reason why. Would you be able to take a closer look at it?

**Comment by bjorg** [comment]
@simon10says Sorry, I just a community contributor who wrote the guide on how to build on Amazon Linux 2 using WSL, which this issue pertains to. This is an AWS tooling issue, either someone from AWS helps you or you need to help yourself. Since you filed this issue back in May [here](https://github.com/aws/aws-lambda-dotnet/issues/663) and [here](https://github.com/aws/aws-extensions-for-dotnet-cli/issues/122), you might be on your own. Maybe just use `package` and work around it?

**Comment by simon10says** [comment]
Oh ... I thought you were from AWS. Sorry. 2 months without any response from AWS, I guess I'm on my own. I tried using `package`, but because I've multiple functions in multiple projects, it doesn't work for me. 

Thanks for your reply.

**Comment by simon10says** [comment]
Is there a way to confirm the lambda function is deployed with `ReadyToRun=true`?

I deployed my lambda with `/p:PublishReadyToRun=true /p:TieredCompilation=false /p:TieredCompilationQuickJit=false`. I then download the zip file from my S3, unzip, and in the `runtimeconfig.json` file I've the following:

```xml
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.Runtime.TieredCompilation": false,
      "System.Runtime.TieredCompilation.QuickJit": false
    }
  }
}
```

**Comment by bjorg** [comment]
I don't know of a direct way to tell, but if you compile with and without _ReadyToRun_, you will see that the latter produces assemblies that are quite a bit bigger.

**Comment by ashishdhingra** [comment]
Hi @genifycom, @esukirno, 

Based on above communication, please advise if this issue could be closed.

Thanks,
Ashish
