### ISSUE TITLE
API Gateway and multiple AWS Serverless Applications

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#632]
Is it possible to add an AWS Serverless application as a resource in an existing API Gateway?

It all works fine in its own API gateway as published by Visual Studio to a Stack.

In the existing API Gateway, I added a new Resource /myapp with an ANY underneath and a proxy under that (just like the Stack published API Gateway).

Both of these point to the AWS Serverless Lambda Application with proxy integration as per the standalone stack.

I get 404 errors.

Does anyone have a working solution for slotting an AWS Serverless Applications into an existing API Gateway or are we restricted to one AWS Serverless Application per API gateway?

**Comment by genifycom** [comment]
I realize what I must do. Override the Lambda function handler and remove the extra resource (i.e. remove /myapp) from the url before passing to routing.

**Comment by genifycom** [comment]
`public abstract class APIGatewayProxyFunction : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        public override async Task<APIGatewayProxyResponse> FunctionHandlerAsync(APIGatewayProxyRequest request, ILambdaContext lambdaContext)
        {
            LambdaLogger.Log("In overridden FunctionHandlerAsync…");

            return await base.FunctionHandlerAsync(request, lambdaContext);
        }
    } `

Is this the correct way to override the Lambda ASP Serverless Application FunctionHandler in ASP.NET Core 3.1?

**Comment by normj** [comment]
I think this section in the README might help you understand how to change how the path base is computed.

https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer#web-app-path-base

**Comment by ashishdhingra** [comment]
Hi @genifycom, 

Please let me know if you need any more guidance on the above scenario or if we are good to close this issue.

Thanks,
Ashish
