### ISSUE TITLE
Q: where can I find the lamda runtime image

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#637]
not sure if this is the correct place to ask this question; please forgive me if it's not.

I'm new to AWS services and would like to fully understand the lambda environment and event flow, to which end I'm looking for access to the current dotnetcore3.1 lambda runtime image as I understand this is the foundation on which the dotnetcore3.1 lambda code is deployed & ran.

1) is this accessible/downloadable? if so where can I find these?
2) are the base image build scripts available ? if so where can I find these?

thanks in advance for any help.

**Comment by msimpsonnz** [comment]
The images are not public but you can use SAM CLI for a local environment
https://aws.amazon.com/serverless/sam/

There is also lambci for docker images that mimic the Lambda environment, which is a cut down Amazon Linux instance
https://github.com/lambci

**Comment by grahamehorner** [comment]
@msimpsonnz many thanks for your reply, I will look into these two options; do you happen to know what differences these have compared to the Amazon Linux 2 used for the Lambda runtime for .netcore 3.1 ? would they be listed anywhere ?

**Comment by msimpsonnz** [comment]
It really depends on what you are trying to achieve? Your code has limited access to the underlying file system as a non privileged user.
Your code is run from /var/task but you can also use layers which are mounted to /opt
