### ISSUE TITLE
Q: lambda function client details

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#638]
Is there any list that has details of the information used/set by the client and held in the ILambdaContext ClientContext object ?
 
https://docs.aws.amazon.com/lambda/latest/dg/lambda-invocation.html seems to suggest that a client could be identified using this information ?

**Comment by msimpsonnz** [comment]
Here is the context info
https://docs.aws.amazon.com/lambda/latest/dg/csharp-context.html

**Comment by grahamehorner** [comment]
@msimpsonnz thanks for your replay; I'll rephrase my question with regards the ILambdaContext and client information.

Q: Is there any information that allows a lambda to identify the client user-agent (i.e. $context.identity.userAgent) ?
Q: Is there any list of AWS services user-agent string ? 

I would like to have the lambda identify what triggered the invocation.  If these values aren't populate by AWS services that trigger the invocation of the lambda; how or what can be used to identify the triggering service/client?

Hope that makes more sense as to what I'm trying to achieve and/or learn with regards to AWS lambda/serverless applications

**Comment by ashishdhingra** [comment]
Hi @grahamehorner,

Good afternoon.

I was going through the issue backlog and came across this guidance question.

Lambda functions could be triggered by different means. One of the way is that some other AWS Service triggers Lambda function (for example, CloudWatch). In this case, appropriate event object is passed to the Lambda function, e.g., [CloudWatchEvent](https://github.com/aws/aws-lambda-dotnet/blob/c350c6d5e2a76a3f6975f13350f95caa5028957c/Libraries/src/Amazon.Lambda.CloudWatchEvents/CloudWatchEvent.cs#L14), which normally has some useful properties that could be examined on case by case basis. You may also write generic Lambda function handler that receives `Stream` object as the first parameter and then examine the JSON received while invoking the Lambda function. I came across the following articles that you might find useful for this scenario:

- [5 Useful Features of C# .NET Core Lambda function](https://medium.com/devtechblogs/https-medium-com-lior-k-sh-five-features-csharp-dotnet-core-aws-lambda-function-9b2d1a3d681b)

- [Under the Hood of .NET-Based Lambda Function Parameters](https://dzone.com/articles/under-the-hood-of-net-core-lambda-request)

Kindly note that these articles should be used just as a reference and not the actual production implementation. Please ensure to test any code changes in the staging environment.

Please let me know if this provides the necessary guidance and if this issue could be closed.

Thanks,
Ashish
