### ISSUE TITLE
System.Data.SqlClient throws exception  Unable to load DLL 'System.Net.Security.Native'

### ISSUE THREAD

**Issue by RichardS1** [aws/aws-lambda-dotnet#639]
I have been working on a project for a couple of weeks that processes files from an S3 bucket and adds data to a Sql Server database (using Dapper) based on the contents of the file. I have been using the Mock Lambda Test Tool throughout the process.

Last week I tried to move from dotnetcore 2.1 to 3.1 and updated the Mock Test Tool. The test tool kept failing, so I moved back down to 2.1, but I am still getting problems with the System.Data.SqlClient NuGet library.

My current problem is that as soon as I try to connect to my local database with a Trusted_Connection=True, I get an exception  Unable to load DLL 'System.Net.Security.Native'.

Like every programmer ever, let me start with, "This worked yesterday, what happened?"

Any ideas would be appreciated.

**Comment by martincostello** [comment]
While it doesn’t explain why it’s stopped working, System.Data.SqlClient is now considered “legacy”: https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

If you use Microsoft.Data.SqlClient instead does your application work again?

**Comment by RichardS1** [comment]
Thanks for the suggestion, but I get the same error. using Microsoft.Data.SqlClient.

**Comment by labrev** [comment]
A very similar issue was mentioned in this issue:  #617 

It's not the same error but it's an issue with the Mock Lambda Test Tool not running with Microsoft.Data.SqlClient package installed.

**Comment by normj** [comment]
Could you try and experiment for me and in your csproj file add the property `CopyLocalLockFileAssemblies` with a value of `true` and see if that changes your behavior?

Here is a full csproj file example.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="1.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.1" />
  </ItemGroup>
</Project>
```

**Comment by RichardS1** [comment]
@labrev, thanks! Issue #617, was the reason I backed down to netcoreapp2.1

**Comment by RichardS1** [comment]
@normj, 

When I add the line in the project file, but keep the project at netcoreapp2.1, I get an exception:

`An exception was thrown trying to process the record. System.Data.SqlClient is not supported on this platform.`

If I use Microsoft.Data.SqlClient, I get the same exception.

When I switch to netcoreapp3.1, using Microsoft.Data.SqlClient 1.1.2, and included the CopyLocalLockFileAssemblies line, The Mock Test Tool 3.1 works.

**Comment by labrev** [comment]
@normj That worked for me.  The Mock Lambda Test Tool opened and I was able to successfully debug the function.  Thanks for the help!
