### ISSUE TITLE
pathParameters is missing in APIGatewayHttpApiV2ProxyRequest

### ISSUE THREAD

**Issue by KiCD** [aws/aws-lambda-dotnet#640]
Hi,

There is not PathParameters property in APIGatewayHttpApiV2ProxyRequest. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

Can you please add it?

Best regards,
Cristina

**Comment by normj** [comment]
In the current version of the **Amazon.Lambda.APIGatewayEvents** package you can use `APIGatewayHttpApiV2ProxyRequest` and `APIGatewayHttpApiV2ProxyResponse`  for the V2 proxy format.

**Comment by KiCD** [comment]
As far as I can see **APIGatewayHttpApiV2ProxyRequest** in **Amazon.Lambda.APIGatewayEvents** version 2.0.0 has no **PathParameters** property. What am I missing?

**Comment by normj** [comment]
You are right it is missing `PathParameters`. I have submitted the PR https://github.com/aws/aws-lambda-dotnet/pull/646 to add the property to the class.

**Comment by normj** [comment]
Version 2.1.0 of Amazon.Lambda.APIGatewayEvents went out today with this fix. Thanks for reporting the issue.

**Comment by KiCD** [comment]
Thank you
