### ISSUE TITLE
Using proxy+ API Gateway configuration with 2.0 payload?

### ISSUE THREAD

**Issue by winzig** [aws/aws-lambda-dotnet#644]
I've configured a new AWS API Gateway (HTTP) endpoint mapping a route of `/{proxy+}` to an AWS Lambda .NET Core WebAPI application with multiple endpoints defined internally for WebAPI.

It was failing with a 500 error after setting it up. Cloudwatch logs showed:

```
Object reference not set to an instance of an object.: NullReferenceException
   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.MarshallRequest(InvokeFeatures features, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.FunctionHandlerAsync(TREQUEST request, ILambdaContext lambdaContext)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
```

I assumed the problem was with in some other part of my configuration (since most of the example code I found for setting this up assumed .NET Core 2.x instead of my 3.x), and so it took me a while to realize that if I go into the Advanced Settings of the route definition, and changed the payload format from the default 2.0 format to the 1.0 format, it would work fine. 

<img width="1003" alt="Screen Shot 2020-04-23 at 11 51 06 AM" src="https://user-images.githubusercontent.com/127062/80138205-4e45c400-8559-11ea-82ef-a04fc31a1a80.png">

Is there a reason `Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction` requires the 1.0 payload? Is that optimal/desired?

Also, is there an official AWS documentation of the .NET WebAPI technique using the special `/{proxy+}` route definition? I actually only realized this setup was possible when I stumbled upon a third party explanation of mapping a single API Gateway route to multiple endpoints in WebAPI.  So far have not been able to find official documentation of how it works, etc.

**Comment by normj** [comment]
When you want to use HTTP API with 2.0 payload you need to change the base class from `APIGatewayProxyFunction ` to `APIGatewayHttpApiV2ProxyFunction`. I have a blog post coming out on that covers this very soon.

**Comment by winzig** [comment]
Thanks @normj that works! 

Are there any blog posts or documentation on the best way to wire up the Websocket API Gateway stuff to a .NET WebAPI Lambda using similar techniques?

**Comment by winzig** [comment]
@normj I've tried integrating the WebSocket API gateway into this existing lambda function a few ways and so far not having much luck. 

First I tried pointing my $connect WebSocket route to the same Lambda function, and after troubleshooting, it looks like the WebSocket payload requires the APIGatewayProxyFunction like the 1.0 HTTP payload, so I switched over to that and am getting null reference exceptions again. 

Next I tried routing the WebSocket gateway to the existing HTTP gateway using HTTP. This seems to almost work, except I don't see where the ConnectionId info is that we need to communicate with web sockets. 

Is there any documentation on wiring up WebSocket gateway to a .NET WebAPI project?

**Comment by classifieds-dev** [comment]
I was able to get web sockets working using the standard proxy.

***csharp
using Microsoft.AspNetCore.Hosting;
using Amazon.Lambda.AspNetCoreServer;
using Microsoft.AspNetCore.Http.Features;
using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.Core;
using Serilog;
using Amazon.Lambda.AspNetCoreServer.Internal;
using Newtonsoft.Json;
using System.Collections.Generic;
using Chat.Models;
using System.Text;
using System.IO;

namespace Chat
{
    public class Function : APIGatewayProxyFunction
    {

        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseSerilog((context, loggerConfiguration) =>
                {
                    loggerConfiguration.ReadFrom.Configuration(context.Configuration);
                }, true, false)
                .UseStartup<Startup>();
        }

        protected override void MarshallRequest(InvokeFeatures features, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
        {

            if(apiGatewayRequest.HttpMethod == null)
            {
                apiGatewayRequest.Path = "/";
                apiGatewayRequest.Resource = "/";
                apiGatewayRequest.HttpMethod = "GET";

                lambdaContext.Logger.LogLine("REQUEST: " + JsonConvert.SerializeObject(apiGatewayRequest));
                lambdaContext.Logger.LogLine("CONTEXT: " + JsonConvert.SerializeObject(lambdaContext));
                lambdaContext.Logger.LogLine($"Route Key: {apiGatewayRequest.RequestContext.RouteKey}");

                if (apiGatewayRequest.QueryStringParameters != null && apiGatewayRequest.QueryStringParameters.ContainsKey("token"))
                {
                    var token = apiGatewayRequest.QueryStringParameters["token"];
                    apiGatewayRequest.Headers.Add("Authorization", $"Bearer {token}");
                    apiGatewayRequest.MultiValueHeaders.Add("Authorization", new List<string> { $"Bearer {token}" });
                }

                if (apiGatewayRequest.RequestContext.RouteKey == "messages")
                {
                    var evt = JsonConvert.DeserializeObject<MessagesEvent>(apiGatewayRequest.Body);
                    apiGatewayRequest.QueryStringParameters = new Dictionary<string, string> {
                    { "recipientId", evt.RecipientId }
                };
                    apiGatewayRequest.MultiValueQueryStringParameters = new Dictionary<string, IList<string>> {
                    { "recipientId", new List<string> { evt.RecipientId } }
                };
                }
            }

            lambdaContext.Logger.LogLine("REQUEST: " + JsonConvert.SerializeObject(apiGatewayRequest));
            lambdaContext.Logger.LogLine("CONTEXT: " + JsonConvert.SerializeObject(lambdaContext));

            base.MarshallRequest(features, apiGatewayRequest, lambdaContext);
        }

        protected override void PostMarshallRequestFeature(IHttpRequestFeature aspNetCoreRequestFeature, APIGatewayProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
        {
            if(apiGatewayRequest.RequestContext.EventType != null)
            {
                if (apiGatewayRequest.RequestContext.EventType == "CONNECT")
                {
                    aspNetCoreRequestFeature.Path = "/connect";

                }
                else if (apiGatewayRequest.RequestContext.EventType == "DISCONNECT")
                {
                    aspNetCoreRequestFeature.Path = "/disconnect";

                }
                else if (apiGatewayRequest.RequestContext.RouteKey == "conversations")
                {
                    aspNetCoreRequestFeature.Path = "/chatconversations";

                }
                else if (apiGatewayRequest.RequestContext.RouteKey == "message")
                {
                    var evt = JsonConvert.DeserializeObject<MessageEvent>(apiGatewayRequest.Body);
                    var byteArray = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(evt.Message));
                    var stream = new MemoryStream(byteArray);
                    aspNetCoreRequestFeature.Path = "/chatmessage";
                    aspNetCoreRequestFeature.Body = stream;
                    aspNetCoreRequestFeature.Headers.Add("Content-Type", "application/json");
                    aspNetCoreRequestFeature.Headers.Add("Accepts", "application/json");
                    aspNetCoreRequestFeature.Method = "POST";

                }
                else if (apiGatewayRequest.RequestContext.RouteKey == "messages")
                {
                    aspNetCoreRequestFeature.Path = $"/chatmessages";
                }
            }

            if (apiGatewayRequest.RequestContext.EventType == null)
            {
                aspNetCoreRequestFeature.PathBase = "/chat/";
                lambdaContext.Logger.LogLine("CONTEXT: " + JsonConvert.SerializeObject(lambdaContext));

                // The minus one is ensure path is always at least set to `/`
                aspNetCoreRequestFeature.Path =
                    aspNetCoreRequestFeature.Path.Substring(aspNetCoreRequestFeature.PathBase.Length - 1);
                lambdaContext.Logger.LogLine($"Path: {aspNetCoreRequestFeature.Path}, PathBase: {aspNetCoreRequestFeature.PathBase}");
            }

        }

    }
}
***csharp

The primary trick was settings all this info at the top before calling the parent marshal method.

***csharp
                apiGatewayRequest.Path = "/";
                apiGatewayRequest.Resource = "/";
                apiGatewayRequest.HttpMethod = "GET";
***csharp

Once I mocked all that I was successfully able to handle a websocket request like a standard rest api request.

The other piece was than mapping the route keys and event types to their respective rest / http equivalents. That is what is being done PostMarshallRequestFeature. 

I'm explicitly mapping all this here. However, I'm sure this could be done in an automated fashion by mapping the body of the request to an event and using the event info to route dynamically based on custom attributes on a class and methods. That would probably be the most ideal solution. However, this seems to work well. It also provides me with the ability to use the lambda in both api gateway and api gateway web socket as a sort of hybrid.

Here is an example of the controller.

***csharp
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.Core;
using Chat.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Shared.Models;
using Shared.Services;

namespace Chat.Controllers
{
    [ApiController]
    //[Authorize(Policy = "RegisteredUser")]
    public class ChatController : ControllerBase
    {
        private readonly ILogger<ChatController> _logger;
        private readonly ChatRepository _chatRepository;
        private readonly AuthApi _authApi;

        public ChatController(ILogger<ChatController> logger, ChatRepository chatRepository, AuthApi authApi)
        {
            _logger = logger;
            _chatRepository = chatRepository;
            _authApi = authApi;
        }

        [HttpGet("chatconversations")]
        public ActionResult<List<ChatConversation>> Conversations()
        {
            _logger.LogDebug("Get conversations");
            // @todo find user associated with connection.
            // var sub = await _authApi.GetUserId();
            return _chatRepository.GetConversations("123");
        }

        [HttpGet("chatmessages")]
        public ActionResult<List<ChatMessage>> Messages(string recipientId)
        {
            _logger.LogDebug($"Get messages for recipient {recipientId}");
            var userId = "123";
            return _chatRepository.GetMessages(userId, recipientId);
        }

        [HttpPost("chatmessage")]
        public ActionResult<ChatMessage> Message(ChatMessage message)
        {
            _logger.LogDebug("Send message");
            _logger.LogDebug($"message: {JsonConvert.SerializeObject(message)}");
            return message;
        }

        [Route("connect")]
        public ActionResult Connect()
        {
            var request = HttpContext.Items["LambdaRequestObject"] as APIGatewayProxyRequest;
            var context = HttpContext.Items["LambdaContext"] as ILambdaContext;
            // var sub = await _authApi.GetUserId();
            _logger.LogDebug("Connect to web socket");
            _logger.LogDebug(JsonConvert.SerializeObject(request));
            _logger.LogDebug(JsonConvert.SerializeObject(context));
            // _logger.LogDebug($"sub: ${sub}");
            // await _chatRepository.createConnection(request.RequestContext.ConnectionId, "test");
            return StatusCode(200);
        }

        [Route("disconnect")]
        public ActionResult<string> disconnect()
        {
            _logger.LogDebug("Disconnect from websocket");
            return "This is a test";
        }

    }
}
**csharp

**Comment by winzig** [comment]
Thanks for sharing this technique @classifieds-dev! I'm curious if Amazon plans on baking some of this kind of technique into their Marshall methods. I'm thinking a new attribute, similar to the `Route()` attributes provided by MVC, but specifically for auto routing of WebSocket requests. 

E.g. `AWSWebSocketRoute("$connect")` put on top of a controller method, and modifications to the Marshall methods to understand those and route accordingly?

**Comment by classifieds-dev** [comment]
I was thinking a more generic event / action http system. Where the event / action is extracted from the body and mapped to a route based info within the action such as the name. I think that would work well with web sockets since client side communication is typically done like so.

ws.send(JSON.stringify({ action: "myaction" data: { ... }}));

**Comment by winzig** [comment]
Yeah, this could be similar to MVC's normal routing based on the controller and action names. E.g. maybe decorate the controller class at the top with `[WebSocketGateway]` attribute to let it know, and then each method is routed based on that incoming action property on the JSON, and the remaining properties are mapped into the parameters of the methods.

**Comment by diegosasw** [comment]
Is there anything new on this? Getting started now with web sockets and trying to find a nice way to use AspNet web api to react to API gateway web socket events.

Is there any syntactic sugar already in this package to easily tell a controller or IActionResult that the request comes from a websocket?

Would be great if the action is the value used for http route and the data can be extracted as an object from body or similar.

**Comment by diegosasw** [comment]
I created a bug (I think it is) because the deserialization with `[FromBody]` does not work as expected as per @classifieds-dev nice answer on dealing with websocket event requests.

https://github.com/aws/aws-lambda-dotnet/issues/819

**Comment by classifieds-dev** [comment]
I think the best solution is to proxy it.

**Comment by diegosasw** [comment]
I am not using kubernetes. I'm using lambda. Planning on using it at least. Didn't know about that bad performance but I wonder what's the difference between websocket and http at the lambda level. Isn't the websocket connections dealt with at the gateway api and for the lambda the payload event is actually "similar"?

Or do you mean using .net lambda in general for both websocket and http is slow?

At the moment I'm just exploring options but the priority is using lambda, if possible as a container (.net5) and if possible one single lambda function for all websocket + http write endpoints (and therefore this dotnet package seems great).

Keen to read more about it though! Thanks for the tips

**Comment by classifieds-dev** [comment]
Lambda is inherently slow deployed as .NET programs. The c# / .NET environment takes about 2+ seconds to cold start. Other languages take milliseconds.

**Comment by winzig** [comment]
Can you guys take this discussion elsewhere please?
