### ISSUE TITLE
FeatureRequest: The passing of ApiGatewayStage variables into Lambda IConfiguration

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#645]
Please consider injection of a Microsoft.Extensions.Configuration.Memory MemoryConfigurationSource into the ConfigureAppConfiguration which can be populated/updated upon receiving a request from the ApIGatewayRequest with the StageVariables keys & values; thus allowing the same deployment instance of lambda code to be invoked from one/more the ApiGateway configurations with staging values overriding other configuration value sources.

**Comment by normj** [comment]
Interesting. Can give a bit more detail about how that would work? Since ConfigureAppConfiguration is only called once per instantiation of the Lambda compute environment and not for every request how would the configuration get updated per request?

**Comment by grahamehorner** [comment]
@normj I'm quite new to the aws and how lambda works; but one possible solution would be to fork the request pipeline based on the ARN of the source event and thus have the gateway stage variables be used as settings similar to how you would with multi-tenanted applications.
