### ISSUE TITLE
Community: join discussion on AWS Lambda .NET on Slack at awsdevelopers.slack.com

### ISSUE THREAD

**Issue by bjorg** [aws/aws-lambda-dotnet#647]
AWS has a Slack group for developers with a #dotnet channel. Unfortunately, Slack doesn't have a signup form, but you can message me your email address privately on twitter `@lambdasharp` (DMs are open) or directly via email at lambdasharp@gmail.com. Just mention `#dotnet` and I'll know what to do. ;)

**Comment by normj** [comment]
Thanks for submitting this @bjorg. I have pinned this to keep its attention.
