### ISSUE TITLE
Incorrect type used when creating Logger

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#648]
The type used when creating the Logger should be TREQUEST or AbstractAspNetCoreFunction<TREQUEST,TRESPONSE> IMHO

https://github.com/aws/aws-lambda-dotnet/blame/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L262

**Comment by normj** [comment]
Good catch. I pushed the change into the dev branch to go out with the next release. https://github.com/aws/aws-lambda-dotnet/commit/745bb003ba895091930ae35b5b81e23715c732eb

**Comment by normj** [comment]
Version 5.1.0 of Amazon.Lambda.AspNetCoreServer went out with this change.
