### ISSUE TITLE
dotnet lambda deploy-serverless fails to create Lambda

### ISSUE THREAD

**Issue by shailajayadav** [aws/aws-lambda-dotnet#654]
Hi,
I am trying to deploy the Nop Comm .Net application to lambda so I can use its API.
While running the below command I am getting these errors. Not sure what's wrong I am doing here. Using new version of Lambda.
`dotnet lambda deploy-serverless` 

<img width="1440" alt="Screen Shot 2020-04-28 at 4 07 47 PM" src="https://user-images.githubusercontent.com/26118364/80546429-76bf2b00-896a-11ea-9ead-f80967e96296.png">

Please let me know if there Is there way to fix this issue.

Updated: Just to add..When I am uploading the ZIP folder on lambda and manually creating the API gateway . That time its works fine.

**Comment by normj** [comment]
I'm only vaguely familiar with Nop. Can you share your csproj file so I can get a better understanding what is included with Nop?

**Comment by shailajayadav** [comment]
https://github.com/nopSolutions/nopCommerce

This is the application which  I am trying to deploy to lambda. Also find the attached csproj.
[Nop.Web.csproj.zip](https://github.com/aws/aws-lambda-dotnet/files/4549332/Nop.Web.csproj.zip)

**Comment by martonx** [comment]
NopCommerce is a full blown .Net Core E-Commerce system. AWS Lambda is for small .Net Core jobs, even behind API Gateway. I seriously doubt, wheather you'll be able to run NopCommerce on AWS Lambda. Use EC2, Container, Beanstalk etc for it.

**Comment by shailajayadav** [comment]
> NopCommerce is a full blown .Net Core E-Commerce system. AWS Lambda is for small .Net Core jobs, even behind API Gateway. I seriously doubt, wheather you'll be able to run NopCommerce on AWS Lambda. Use EC2, Container, Beanstalk etc for it.

Can We deploy few apis of NopCom to Lambda?

**Comment by ashishdhingra** [comment]
Hi @shailajayadav, 

Please refer the section **Web applications** on [AWS Documentation](https://aws.amazon.com/lambda/) home page. It has a link to [sample application](https://github.com/aws-samples/lambda-refarch-webapp) which gives overview on how to develop APIs on AWS Lambda.

Thanks,
Ashish
