### ISSUE TITLE
Init called twice causing service registrations to fail

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#657]
The virtual Init method is called twice from [AbstractAspNetCoreFunction.cs#L288](https://github.com/aws/aws-lambda-dotnet/blame/8ddd91b6c043d067727e50f5490ff2108a6c0ade/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L288) causing service registrations to fail and/or register mulitple instances when a developer is using Init to add to the DI system

**Comment by ashishdhingra** [comment]
Hi @grahamehorner,

Looking at the code [AbstractAspNetCoreFunction.cs#L288](https://github.com/aws/aws-lambda-dotnet/blame/8ddd91b6c043d067727e50f5490ff2108a6c0ade/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L288) one of the Init is invoked for `WebHostBuilder` and other one if for `HostBuilder`. So this doesn't appear to be a bug. Please confirm if there is any specific issue you are facing. If yes, kindly share the code solution to troubleshoot the issue.

Thanks,
Ashish
