### ISSUE TITLE
use TryAddSingleton for LambdaServer

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#658]
IMHO the TryAddSingleton should be used to reduce/remove the need for checking for multiple LambdaServer registrations [Utilities.cs#L58](https://github.com/aws/aws-lambda-dotnet/blame/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/Internal/Utilities.cs#L58) and therefor reduce complexity of implementation

**Comment by NGL321** [comment]
@grahamehorner Thank you for the suggestion! I will pass it along and someone will update this issue.

😸
