### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction::Unknown error responding to request: InvalidOperationException:

### ISSUE THREAD

**Issue by drewsb** [aws/aws-lambda-dotnet#659]
We are using Mock Lambda Test Tool to test API gateway proxy requests in our serverless ASP.NET API, and we are receiving the following dependency injection error: 

**Error Exception**
`[Error] Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction: [0]: Unknown error responding to request: InvalidOperationException:
System.InvalidOperationException: Unable to resolve service for type 'TaxAPI.Services.IUserService' while attempting to activate 'TaxAPI.Controllers.UserController'.`

We correctly added these services in the Startup class, and these requests work as expected in the AWS environment after deploying to AWS Lambda as well as testing through IIS Express. We only see this issue when we use the mock lambda tool. Is there any reason why the Mock tool doesn't inject service dependencies properly for this setup? I've added the following code for reference.

**ConfigureServices.cs**
`        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            // Add S3 to the ASP.NET Core dependency injection framework.
            services.AddTransient<ITaxEntityService, TaxEntityService>()
                .AddTransient<IUserService, UserService>()
                .AddTransient<ISecretAccessService, SecretAccessService>()
                ;

            services.AddLogging(logging => LambdaLoggingService.SetupLogger(_env.IsDevelopment(), logging, Configuration));

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Tax API Demo", Version = "v1" });
            });
        }`

**LambdaEntryPoint.cs**
`    public class LambdaEntryPoint : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        /// <summary>
        /// The builder has configuration, logging and Amazon API Gateway already configured. The startup class
        /// needs to be configured in this method using the UseStartup<>() method.
        /// </summary>
        /// <param name="builder"></param>
        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseStartup<Startup>();
        }
    }`

**Comment by DmitriyVorobey** [comment]
I have the same issue. I am using API gateway proxy with serverless ASP.NET API and receiving the same exception. I tried another DI methods, but get the same result.
```
AddSiglethon()
AddScoped()
```

**Comment by ckuetbach** [comment]
Did you try the same with an older version of the CoreServer?

`<PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="5.0.0" />`

After updating to 5.1.1 I run into some trouble with dependency injection as well. I am still investigating. But it looks like the `.ConfigureService` is not called.

This one:
https://github.com/d-velop/dvelop-app-template-cs/blob/feature/55_Dependencies/AwsLambda/Entrypoint/LambdaEntryPoint.cs#L49

**Comment by ashishdhingra** [comment]
Hi @drewsb, 

Good afternoon.

I was able to reproduce the issue using the sample application generated by VS Serverless template and using a sample implementation of IUserService and UserService. I will have a developer look at the issue and will update the thread once we get a response.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @drewsb,

Based on input from developer, Mock Test Tool is best suited for testing `plain` Lambda functions. The best alternative is to test API Gateway Proxy requests as normal ASP.NET Core application via IISExpress or IIS. Please let me know if testing using IISExpress works for you.

Thanks,
Ashish
