### ISSUE TITLE
Logging info using Console.WriteLine does not show up in Lambda Console

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#66]
Hello AWS,

As the [document](http://docs.aws.amazon.com/lambda/latest/dg/dotnet-logging.html#how-to-find-logs-dotnet) says:
<img width="864" alt="screen shot 2017-02-20 at 7 36 03 pm" src="https://cloud.githubusercontent.com/assets/18595104/23146359/22036c1c-f7a4-11e6-9ef7-12fea52eba67.png">

When using `Console.WriteLine`, the written info should be shown in the Lambda console. However, it doesn't work. Only `context.Logger` works.

Code:
<img width="285" alt="screen shot 2017-02-20 at 7 37 42 pm" src="https://cloud.githubusercontent.com/assets/18595104/23146379/4555205c-f7a4-11e6-8f6a-bc2772b79c21.png">

Result: (it should say `Hello` twice)
<img width="603" alt="screen shot 2017-02-20 at 7 37 47 pm" src="https://cloud.githubusercontent.com/assets/18595104/23146383/4b33eefe-f7a4-11e6-825f-ca2a2cd4799a.png">

**Comment by Kralizek** [comment]
When working with ASP.NET Core applications hosted in lambda, we can't use the log provider contained in Microsoft.Extensions.Logging.Console.

I was thinking about opening a new issue, but then I saw this one.

**Comment by MZhoume** [comment]
@Kralizek I am not so sure we are talking about the same problem. I was talking about using `Console.WriteLine` and the logger provided by AWS `IContext.Logger.LogLine`. 

I was using `dotnet core` not `ASP.NET core`.

**Comment by PavelSafronov** [comment]
@MZhoume The documentation is not very clear about this and we will update it, but this is the expected result. The Console outputs are gathered after function execution and eventually logged to CloudWatch Logs, while context.Logger calls are logged during execution and are available in the AWS Web Console's "Log output" section. All logs, however, will always end up in CloudWatch Logs.

@Kralizek Sounds like a different problem, so feel free to open a new issue with your repro code.

**Comment by normj** [comment]
Closing as I believe this is answered. Feel free to reopen if there are more questions.

**Comment by MZhoume** [comment]
@PavelSafronov @normj Thanks that did answer my question.
