### ISSUE TITLE
PublishSingleFile Invalid input specification: Must specify the host binary

### ISSUE THREAD

**Issue by classifieds-dev** [aws/aws-lambda-dotnet#662]
Hello, I'm trying to create a single file self contained lambda application with a custom runtime. I have successfully been able to publish using ready to run and trimmed. However, whenever I enable single file publishing the following error occurs. Have anyone been able successfully use ready to run, trimming, and single file publishing together in combination to build a custom runtime lambda application?

Publishing Error:

Invalid input specification: Must specify the host binary

Command:

dotnet lambda package --project-location src/Classifieds.Chat --msbuild-parameters "--self-contained true"

Here is my project file.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <!-- <RuntimeIdentifier>osx.10.13-x64</RuntimeIdentifier> -->
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <AWSProjectType>Lambda</AWSProjectType>
    <OutputType>exe</OutputType>
    <AssemblyName>bootstrap</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.7.0" />
    <PackageReference Include="CassandraCSharpDriver" Version="3.14.0" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.3" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="AWSSDK.ApiGatewayManagementApi" Version="3.3.101.103" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Classifieds.Shared\Models\ChatMessage.cs;..\Classifieds.Shared\Models\ChatConnection.cs;..\Classifieds.Shared\Models\ChatConversation.cs;..\Classifieds.Shared\Models\PublicUserProfile.cs;;..\Classifieds.Shared\Services\AuthApi.cs;">
        <Link>_Inlined\Classifieds.Shared\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Remove="bootstrap" />
  </ItemGroup>
  <ItemGroup>
    <None Include="AmazonRootCA1.pem" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="Mappings\" />
    <Folder Include="Controllers\" />
    <Folder Include="Models\" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bootstrap" ExcludeFromSingleFile="">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by msimpsonnz** [comment]
Is there a specific reason you need to do this? Lambda now has a 3.1 runtime so shipping the whole thing doesn’t make sense to me

**Comment by classifieds-dev** [comment]
I'm under the impression cold start time and file size can be significantly decreased by using ready to run. However, ready to run does not optimize the file size. To optimize file size two things need to be done. One is use trimming to remove unused dependencies. The other to combat including the entire runtime file size is to use a single executable via publish single file. Right now I can't get that last part to work. So each lambda of mine includes all the dll files which is significant bloat.

**Comment by classifieds-dev** [comment]
I began building one of my apis in go only to compare the difference in performance.

c#:
EPORT RequestId: d8db7f50-d25e-44c3-9dd8-08d4553d591c	Duration: 6740.11 ms	Billed Duration: 7900 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	Init Duration: 1077.26 ms

go:
REPORT RequestId: adc36a17-b30f-48d5-908e-ef9f00b9b16b	Duration: 6.00 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 58 MB

**Comment by Yottster** [comment]
@classifieds-dev you should probably scale up your c# lambda to match the go one if you want to make a comparison. With that said go might still win and match your use-case better.

**Comment by classifieds-dev** [comment]
REPORT RequestId: 042a94a7-f479-4f28-b4fe-bdb539c90383	Duration: 6.50 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 66 MB

**Comment by Kralizek** [comment]
> I'm having a very difficult time understanding c# over go for new development on aws serverless acrchitecture.

I'd say .NET Standard compatibility is a big winning of Lambda on .NET. Also, the ability for a small team to use the same language on serverless and server-ed components of the architecture is a great advantage, especially for small teams.

**Comment by esukirno** [comment]
@classifieds-dev I find .net core lambda performs better with higher memory size. You can get significant performance improvement by increasing from 128 MB to 1024 MB or even 2048 MB. Albeit at some point further increase won't improve much.

I am struggling to understand the benefit of self contained publishing. Self contained generates massive payload, hence initialise much slower.

Out of curiosity, are you able to publish ReadyToRun with self contained = false?

**Comment by ashishdhingra** [comment]
Hi @classifieds-dev,

Good afternoon.

I was going through the backlog and came across this issue. Could you please share the version of .NET Core 3.x used to reproduce the issue? There was a similar issue in Microsoft's .NET repo https://github.com/dotnet/sdk/pull/3892, but I'm not sure if it is related.

Thanks,
Ashish

**Comment by classifieds-dev** [comment]
3.1.202

**Comment by ashishdhingra** [comment]
Hi @classifieds-dev,

Good afternoon.

Somehow, I'm unable to reproduce the issue on .NET Core version 3.1.403. The command `dotnet lambda package --project-location src/Classifieds.Chat --msbuild-parameters "--self-contained true"` works fine. Could you please try upgrading your .NET Core version and check if the issue is still reproducible. As mentioned earlier, there was a similar issue in Microsoft's .NET repo https://github.com/dotnet/sdk/pull/3892, and might be it got fixed in later version.

Thanks,
Ashish
