### ISSUE TITLE
Getting error while deploying to Lambda

### ISSUE THREAD

**Issue by shailajayadav** [aws/aws-lambda-dotnet#664]
When I am trying to deploy my application to Lambda , I am receiving the below error. I am not able to find solution  online. Not sure what I am missing here.
` dotnet lambda deploy-serverles`

<img width="1440" alt="Screen Shot 2020-05-06 at 4 16 58 PM" src="https://user-images.githubusercontent.com/26118364/81237694-1b69ea00-8fb5-11ea-8d20-463ca430f85d.png">

**Comment by ashishdhingra** [comment]
Duplicate of #654
