### ISSUE TITLE
Q: SystemsManagerExtensions usage

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#666]
Q: given that `SystemsManagerExtensions` require AWS credentials to connect/communicate with System Parameter Store what is the best approach to allow a Lambda to load configuration from the System Parameter Store during startup? 

When using `ConfigureHostConfiguration` or `ConfigureAppConfiguration` the AWS credentials may NOT be loaded prior to using the `SystemsManagerExtensions` ?

**Comment by ashishdhingra** [comment]
Hi @grahamehorner,

I'm not sure if it helps, the following blog posts might provide some guidance:

- [The Right Way to Store Secrets using Parameter Store](https://aws.amazon.com/blogs/mt/the-right-way-to-store-secrets-using-parameter-store/)

- [Sharing Secrets with AWS Lambda Using AWS Systems Manager Parameter Store](https://aws.amazon.com/blogs/compute/sharing-secrets-with-aws-lambda-using-aws-systems-manager-parameter-store/)

Please let me know if it helps and if this issue could be closed.

Thanks,
Ashish
