### ISSUE TITLE
New project system

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-lambda-dotnet#67]
With the release of Visual Studio 2017, project.json projects will be abandoned in favor of the new csproj.

I know that the lambda tools are marked as preview for this very reason. My question is, transitioning to the project system will introduce any change on how we consume the package?

**Comment by normj** [comment]
The experience using Visual Studio and the Lambda commands added to the dotnet CLI should stay the same. 

We purposely kept the project system for Lambda functions the same as regular .NET Core projects so that they would work with the upcoming migration tooling for the new project system.

**Comment by normj** [comment]
We just released a preview version of the Visual Studio 2017 support. Check it out and let us know what you think.

https://aws.amazon.com/blogs/developer/preview-of-the-aws-toolkit-for-visual-studio-2017/

**Comment by normj** [comment]
Closing this as I believe it is answered. If you issues with the preview of the VS tooling feel free to add your feedback to its issue.

https://github.com/aws/aws-lambda-dotnet/issues/71

**Comment by Kralizek** [comment]
Not sure if it's a browser-related issue, but the file was saved by Microsoft Edge with the ZIP extension instead of VSIX.

**Comment by normj** [comment]
That was odd, thanks for letting us know. We have fixed the issue.
