### ISSUE TITLE
Q: API Gateway Proxy Request

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-lambda-dotnet#671]
I'm looking to create a HttpClient implementation to assist with testing of LambdaServerless Application/Functions to which end I would like to understand how/what the API Gateway does to encode the HTTP request into the APIGatewayProxyRequest ie. the mappings of headers/uri and/or where/what values go into the APIGatewayProxyRequest RequestContext etc.

The APIGatewayProxyResponse seem self explanatory so that is fine

Is there any documentation and/or published code I can reference to simulate these values or populate from a .NET HttpRequestMessage to allow myself to achieve the above ?

**Comment by msimpsonnz** [comment]
You can look at Amazon.Lambda.Core to see what is going on
https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Core
This takes a stream and deserialises based on the event type
The APIGW Event types also have their own lib with the refs

**Comment by ashishdhingra** [comment]
Hi @grahamehorner,

Good afternoon.

Please advise if you need further guidance on this issue or if this could be closed.

Thanks,
Ashish
