### ISSUE TITLE
What is the default "dotnet publish" settings that are used by "dotnet lambda package" 

### ISSUE THREAD

**Issue by maxrkzhou** [aws/aws-lambda-dotnet#674]
I developed a aws lambda on .NET core 2.2. I tried to use default dotnet "publish" command to generate "ready-to-deploy" package for the lambda. The command I used is `dotnet publish --project path_to_lambda_project -c Release --runtime "rhel-x64" --self-contained true -o path_to_output_folder` But the generated files seem to be different with what is generated by `dotnet lambda package`. 
Can you please let me know what's the default settings that are used?

**Comment by NGL321** [comment]
Hey @maxrkzhou,

`dotnet lambda package` does more than just `dotnet publish` and zip the contents. [This article](https://aws.amazon.com/blogs/developer/deploying-net-core-aws-lambda-functions-from-the-command-line/) should clarify. Let me know if this answers your question!

😸 😷
