### ISSUE TITLE
ECSTaskStateChangeEvent cannot be deserialized properly

### ISSUE THREAD

**Issue by stang-tgs** [aws/aws-lambda-dotnet#675]
`ECSTaskStateChangeEvent` cannot be deserialized properly by lambda due to differences in the definition of `Attachment.Details`.  `Attachment.Details` are returned as a List of `{"name" : "name", "value" : "value}` pairs, not a List of `KeyValuePair<string, string>`

This is the exception:

```
Error converting the Lambda event JSON payload to type Amazon.Lambda.CloudWatchEvents.ECSEvents.ECSTaskStateChangeEvent: The JSON value could not be converted to System.Collections.Generic.List`1[System.Collections.Generic.KeyValuePair`2[System.String,System.String]]. Path: $.detail.attachments[0].details[0] | LineNumber: 0 | BytePositionInLine: 412.: JsonSerializerException
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
```

**Comment by NGL321** [comment]
Hi @stang-tgs,
Thank you for reaching out, and thank you as well for submitting a fix. We will resolve this issue when someone has a chance to review your PR.

😸

**Comment by ashishdhingra** [comment]
Fixed in [Amazon.Lambda.CloudWatchEvents 3.0.0](https://www.nuget.org/packages/Amazon.Lambda.CloudWatchEvents/3.0.0)
