### ISSUE TITLE
Lambda Test Tool - Restarting debug sessions automatically when source is edited

### ISSUE THREAD

**Issue by pharindoko** [aws/aws-lambda-dotnet#678]
Hey guys,

I created a template where I use the lamba test tool. (see here: [serverlessDotNetStarter](https://github.com/pharindoko/serverlessDotNetStarter))

I`m missing some kind of reload feature when I used the Lambda test tool.
Does someone have an idea how to do this using vs code ?

I tried to do this in combination with the a launch.json and task.json file

I tested following tasks.json

````
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build",
      "command": "dotnet",
      "type": "process",
      "args": [
        "watch",
        "build",
        "${workspaceFolder}/AwsDotnetCsharp.csproj",
        "/property:GenerateFullPaths=true",
        "/consoleloggerparameters:NoSummary"
      ],
      "problemMatcher": "$msCompile"
    }
  ]
}
```

Yes it does start the watcher and on filechanges it will rebuild, but it can`t start the browser and lambda test tool anymore :-/ It just watches for the build itself and does not relaunch / launch.

br,

Florian

**Comment by NGL321** [comment]
Hey @pharindoko,

I believe you are looking for something like [this](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited). If this _isn't_ what you are looking for please let me know!

:smile_cat: :mask:

**Comment by pharindoko** [comment]
@NGL321 
That‘s a good summarization of my request :P thanks.

**Comment by pharindoko** [comment]
Hey, 
sorry I`m looking for a file change / monitor tool that restarts the process mentioned in launch.json on file change.

So something similar to nodemon in js.
Dotnet watch is meant for that, but doesn`t work with your tool it seems.

So using vs-code/lambda-mock-tool/c# I cannot currently restart the tool on filechange.

br,

Flo
