### ISSUE TITLE
.NET Core 3.1 runtime incompatibility with Amazon.Lambda.Logging.AspNetCore 3.0.0

### ISSUE THREAD

**Issue by wdolek** [aws/aws-lambda-dotnet#679]
We are in process of migrating our Lambdas to .NET Core 3.1 and I just found one incompatibility when using `Amazon.Lambda.Logging.AspNetCore` version `3.0.0`.

We are using logger scopes (to decorate all log messages with certain value).

Exception being thrown:
```
Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.: TypeLoadException
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.BeginScope[TState](TState state)
   at Acme.Common.Extensions.LoggerExtensions.BeginScopeWithInformationalVersion(ILogger logger, Assembly assembly) in /builds/Acme.Common/Extensions/LoggerExtensions.cs:line 19
   at Acme.Common.Extensions.LoggerExtensions.BeginScopeWithInformationalVersion[T](ILogger logger) in /builds/Acme.Common/Extensions/LoggerExtensions.cs:line 10
   at Acme.Le.LeHandler.Handler(Dictionary`2 input, ILambdaContext context) in /builds/Acme.LeHandler/LeHandler.cs:line 89
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
```

Our _csproj_ looks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.0.1" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.4" />
  </ItemGroup>

  // ...

</Project>
```

I'm suspecting (and actually verified after `dotnet publish`) that there's version clash, since `Amazon.Lambda.Logging.AspNetCore` is referencing:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.0" />
  </ItemGroup>
```

One of breaking change between 2.1 and 3.1 is that `NullScope` is now `internal`.

**Proposed solution**:
I suggest to use [version range](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges) for those dependencies like this:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="[3.1,3.2)" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="[3.1,3.2)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[3.1,3.2)" />
  </ItemGroup>
```

I don't expect any impact on functionality (haven't tried yet), I can prepare PR - if you agree with my suggestion.

**Comment by wdolek** [comment]
@normj apology for confusing projects. I've created PR solely focusing on `Amazon.Lambda.Logging.AspNetCore` - not sure whether _small-step approach_ is right in this case, there are probably more libs deserving update.

**Comment by lorenh** [comment]
Just curious about the status of this fix?  I've been holding off integrating the Amazon.Lambda.Logging.AspNetCore package until I see how this issue turns out.

**Comment by wdolek** [comment]
@lorenh If you are not using scopes, it _should_ be fine to go on even with current version.

Unfortunately I didn't have time to verify my PR with our Lambda. As workaround, we switched simply to `Microsoft.Extensions.Logging.Console` with `Systemd` formatting (our Lambda is not called so often, so we are OK with that). If you had time to try my change, I'll be more than happy 🙇

**Comment by wdolek** [comment]
@lorenh I was checking our implementation and couldn't find any special configuration to enable that. Only thing we do is changing Console logger format to `systemd`.

```json
{
  "Logging": {
    "LogLevel": { },
    "Console": {
      "IncludeScopes": true,
      "DisableColors": true,
      "Format": "Systemd"
    }
  }
}
```

**Comment by normj** [comment]
Sorry forgot to circle back on this issue but the fix for this was released on 6/24

https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2020-06-24
