### ISSUE TITLE
Change logging in runtime Console App Lambda

### ISSUE THREAD

**Issue by Cenarius1** [aws/aws-lambda-dotnet#680]
Hi,
I would like to change logging level in lambda runtime base on variable, ex. environment variable.
I am building .NET Core console app, not ASP.NET Core App. 
1. Is it possible? 
2. Should I do workaround? 
3. Should I edit code?

Please help

Regards
Cenarius

**Comment by ashishdhingra** [comment]
Hi @Cenarius1, 

Thanks for posting the guidance question. Please have a look at [Using AWS Lambda environment variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html), the example code for C# listed in the article is:

```C#
string region = Environment.GetEnvironmentVariable("AWS_REGION");
```

Kindly let me know if it helps.

Thanks,
Ashish
