### ISSUE TITLE
Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest is missing methodArn parameter

### ISSUE THREAD

**Issue by ProfessionalAmateur** [aws/aws-lambda-dotnet#681]
The [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-input.html) for a REQUEST type custom lambda authorizer shows there should be a parameter called `methodArn` in the APIGatewayProxy request but I am not seeing in in the class.  I'm using the AWS SDK using .net-core3.1.  Am I using the correct input class for the function handler or is the `methodArn` parameter missing?

``` c#
namespace Amazon.Lambda.APIGatewayEvents
{
   public class APIGatewayProxyRequest
   {
      public APIGatewayProxyRequest();

      public string Resource { get; set; }
      public string Path { get; set; }
      public string HttpMethod { get; set; }
      public IDictionary<string, string> Headers { get; set; }
      public IDictionary<string, IList<string>> MultiValueHeaders { get; set; }
      public IDictionary<string, string> QueryStringParameters { get; set; }
      public IDictionary<string, IList<string>> MultiValueQueryStringParameters { get; set; }
      public IDictionary<string, string> PathParameters { get; set; }
      public IDictionary<string, string> StageVariables { get; set; }
      public ProxyRequestContext RequestContext { get; set; }
      public string Body { get; set; }
      public bool IsBase64Encoded { get; set; }

      <...SNIP...>
   }
}
```

**Comment by ProfessionalAmateur** [comment]
Does this look like a bug?  Is this the proper place to file a bug report?  What else can I do, to assess the lambda authorizer for REQUESTS

**Comment by msimpsonnz** [comment]
Use the Custom Authorizer request?
https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerRequest.cs

**Comment by ProfessionalAmateur** [comment]
@msimpsonnz I think that will work perfectly.  I couldnt find documentation on when to use teh APIGatewatyProxyRequest vs the suggested APIGatewayCustomAuthorizerRequest (albeit Im very new to lambda authorizers), is there a better location than the documentation I linked to above?  

I appreciate the response!

**Comment by msimpsonnz** [comment]
No worries, I appreciate it’s not obvious as the models haven’t been update to reflect the name change from “Custom Authorizer” to new name of “Lambda Authorizer”
This would also reflect in searching on the web so I would use the old name for some examples
This is a great guide too
https://www.alexdebrie.com/posts/lambda-custom-authorizers/

**Comment by ProfessionalAmateur** [comment]
Thanks!  I appreciate your time!
