### ISSUE TITLE
Crypto cannot find System.Security.Cryptography.Native.OpenSsl

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#69]
Running locally works fine.

Deployed to Lambda, this was working fine until a couple of days ago (Note I have updated the AWS toolkit to Version 3.13.741.0)) . Now this gives:

An unhandled exception has occurred: The type initializer for 'Crypto' threw an exception.
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.

I can see "runtime.native.System.Security.Cryptography.OpenSsl/4.3.0-preview1-24530-04" in the project.lock.json

Anyone else seeing this?

**Comment by normj** [comment]
Could you share your project.json and sample code of how you might be using the Crypto library so I can understand the dependencies for the lambda function?

**Comment by normj** [comment]
Is this still happening? The last release did have features to improve the handling of native dependencies so I want to make sure there was not issue with that code.

Looking at the original post again you mentioned seeing runtime.native.System.Security.Cryptography.OpenSsl/4.3.0-preview1-24530-04 in the project.lock.json file. The 4.3.0 versions of the core NuGet packages are for .NET Core 1.1. So you might have added a .NET Core 1.1 reference to your project which is causing problems.

**Comment by genifycom** [comment]
Hi Norm,

Yes just tested it again and still getting:

System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.

It happens when I try to create BasicAWSCredentials

                var credentials = new BasicAWSCredentials(AWSAccessKeyId, AWSSecretKey);

this works locally.

Here are my dependencies from project.json

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",

    //Extra requirements
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",

    //Lambda Requirements
    "AWSSDK.Extensions.NETCore.Setup": "3.3.0.3",
    "AWSSDK.CognitoIdentityProvider": "3.3.2.4",
    "Amazon.Lambda.AspNetCoreServer": "0.9.0-preview1",
    "AWSSDK.Core": "3.3.8.2",
    "AWSSDK.S3": "3.3.5.7",
 
    "Amazon.Lambda.Tools": {
      "version": "1.3.0-preview1",
      "type": "build"
    }
  },

I am trying to upload a file to S3 and want to manually get credentials to do this.

Thanks,

Dave

**Comment by normj** [comment]
I'm still not able to reproduce the problem with these dependencies. You mention before of seeing runtime.native.System.Security.Cryptography.OpenSsl in your project.lock.json file which I'm not seeing in my case. Can you send me the snippet of your project.lock.json file that calls out that reference?

**Comment by genifycom** [comment]
Hi Norm, I am not referencing Crypto

**Comment by normj** [comment]
Yes, I was just wondering if in the project.lock.json file that might give a clue as to which of your declared dependencies is bringing in that Crypto dependency.

**Comment by PavelSafronov** [comment]
Can you try deleting the `project.lock.json` file and performing `dotnet restore` on the project? I wonder if something got cached accidentally and is causing these issues.

**Comment by genifycom** [comment]
I am going to close this as I am looking to transition to Visual Studio 2017. Once I have that going, I will retest this.

Thanks
