### ISSUE TITLE
OData orderby is failing on .net core 3.1 lambda due to wrong URL escaping

### ISSUE THREAD

**Issue by grascioni** [aws/aws-lambda-dotnet#694]
When I submit a GET request with a querystring like "?$top=100&$orderby=OrderDate%20desc", in the server I see that it was escaped to "?$orderby=OrderDate+desc&$top=100" (note the **plus sign**).

Using Amazon.Lambda.AspNetCoreServer 5.1.0.

Do you have any ideas what should I do to fix this? A configuration change in API Gateway maybe? Thanks.

**Comment by grascioni** [comment]
Did more investigation, and I think it's related to https://github.com/OData/WebApi/issues/1227.

In the SQL profiler, I see that on my local environment the query is made through **exec sp_executesql** and all the ODATA parameters are being used. However, on AWS Lambda the query is executed as direct TSQL, and none of the ODATA parameters are considered.

**Comment by jeremymcgee73** [comment]
Hmmm. I wonder if the project I'm working on has the same issue. I'm using postgres, so I can't run profiler. I'll need to figure out how to see the query EF core is using.

**Comment by grascioni** [comment]
You can use EF's logging, something like

```
       private readonly ILoggerFactory _loggerFactory;

        public DataContext(DbContextOptions options, ILoggerFactory loggerFactory) : base(options) {
            _loggerFactory = loggerFactory;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            if (_loggerFactory != null && Debugger.IsAttached) {
                optionsBuilder.UseLoggerFactory(_loggerFactory);
            }
        }
```

**Comment by lreb** [comment]
Any update on this?, I have the same issue, I am using:
Net core 3.1.302
Microsoft.AspNetCore.OData 7.4.1

**Comment by Sayan751** [comment]
It seems that it is a general issue with double-escaped query string; once escaped by browser and then AWS escapes that again.

Decoding the `APIGatewayHttpApiV2ProxyRequest#RawQueryString` has worked for me.

```c#
using System.Net;
using Amazon.Lambda.APIGatewayEvents;
using Amazon.Lambda.AspNetCoreServer;
using Amazon.Lambda.AspNetCoreServer.Internal;
using Amazon.Lambda.Core;

public class CustomAPIGatewayHttpApiV2ProxyFunction : APIGatewayHttpApiV2ProxyFunction
{
  protected override void MarshallRequest(InvokeFeatures features, APIGatewayHttpApiV2ProxyRequest apiGatewayRequest, ILambdaContext lambdaContext)
  {
     apiGatewayRequest.RawQueryString = WebUtility.UrlDecode(apiGatewayRequest.RawQueryString);
     base.MarshallRequest(features, apiGatewayRequest, lambdaContext);
  }
}
```

The lambda entry point class then should extend this custom class.

```c#
public class LambdaEntryPoint : CustomAPIGatewayHttpApiV2ProxyFunction { 
  /// 
}
```

**Comment by ashishdhingra** [comment]
Hi @grascioni,

Please check if this has been fixed in the latest version. There was a fix for a similar issue https://github.com/aws/aws-lambda-dotnet/issues/720 implemented few days back.

Thanks,
Ashish

**Comment by grascioni** [comment]
Thanks for the heads-up, @ashishdhingra, but it didn't work.

Had to revert back to the workaround (CustomEnableQuery attribute) suggested in [this ODATA issue](https://github.com/OData/WebApi/issues/1227).

Seems there's still an issue related to the order of action filters in Lambda with .NET ODATA.
