### ISSUE TITLE
Max parameters / -tp command length via CLI or inside of aws-lambda-tools-defaults.json

### ISSUE THREAD

**Issue by lswiski** [aws/aws-lambda-dotnet#699]
DOTNET SDK v3.1.1-xxx on Linux (RHEL v8.0.x) 

I have a decent amount of parameters and it seems to cutoff regardless of the manor I use to pass them (via command line or via the aws-lambda-tools-defaults.json configuration file). 

from aws-lambda-tools-defaults.json:
``` json
 "template-parameters": "Environment=qa;ApiBucketName=bobs-app-qa-api;DbAdminUserName=admin;DbAdminUserPasswo
rd=XXXXXXXXXXX;ShouldCreateApiBucket=true;DataSubnetIdAZA=subnet-xxxxxxxxxxxxxxx;DataSubnetIdAZB=subnet-xxxxxxxxxxxxxxx
;DataSubnetIdAZC=subnet-xxxxxxxxxxxxxxx;ComputePrivSubnetIdAZA=subnet-xxxxxxxxxxxxxxx;ComputePrivSubnetIdAZB=subnet-xxxxxxxxxxxxxxx;ComputePrivSubnetIdAZC=subnet-xxxxxxxxxxxxxxx;IOTLambdaSG=sg-xxxxxxxxxxxxxxx;IOTDataSG=sg-xxxxxxxxxxxxxxx
c;IOTDataSubnetGroup=iot-rds-subnet-group",
```
Works when this is removed:
```bash
ComputePrivSubnetIdAZB=subnet-xxxxxxxxxxxxxxx;ComputePrivSubnetIdAZC=subnet-xxxxxxxxxxxxxxx;IOTLambdaSG=sg-xxxxxxxxxxxxxxx;IOTDataSG=sg-xxxxxxxxxxxxxxx
c;IOTDataSubnetGroup=iot-rds-subnet-group

```

I know that there are better ways to do this via cloud formation but, updating the structure of the cloud formation is not an option right now, so we are dealing w/ this via parameters instead of mappings or importing / breaking the templates apart and making them aware of the other resources (which will be done in the future).

I wouldn't think that the above would break..

OS Checks:

`env |wc -c`
2423
  
`getconf ARG_MAX`
2097152

This is really driving me nuts - available 24/7 to help debug or help get to the bottom of this!

Thank you,

-Luke

**Comment by lswiski** [comment]
Doesn't work either way.

**Comment by msimpsonnz** [comment]
aws cloudformation command Doesn’t work? If so I’d suggest troubleshooting that
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html

**Comment by NGL321** [comment]
@lswiski 
It is possible this is a bug, but since you are experiencing the same behavior in the CLI, its much more likely an issue with Cloudformation or your local environment. I will look into this more and give an update if I find anything conclusive.

It could be helpful to see the output you are getting as well as the specific commands being executed.


😸 😷
