### ISSUE TITLE
Install dotnet cli tools as part of Lambda AMI

### ISSUE THREAD

**Issue by joel-cunningham** [aws/aws-lambda-dotnet#70]
When publishing a dotnet core application to lambda it is done so that the application can run standalone without using 'dotnet run'.

Is it possible to get the dotnet cli tools installed as part of the Lambda AMI? This will allow more use cases for dotnet on lambda including compiling of applications.

https://github.com/dotnet/cli

Please let me know if there is a better place to ask for this feature.

**Comment by PavelSafronov** [comment]
This repo is mostly for the NuGet packages and Blueprints, not the actual service itself. The [AWS Lambda forum](https://forums.aws.amazon.com/forum.jspa?forumID=186) is a better place to ask for this feature.
