### ISSUE TITLE
Asp.net core in memory cache still alive before timeout ? 

### ISSUE THREAD

**Issue by lehoangphan** [aws/aws-lambda-dotnet#700]
I use the Asp.net core **Razor Page** Serverless App deployed on AWS Lambda 

I implement the _in memory cache, and Cache Tag Helper_ in my app, it will be expired after **5 minutes** 

If the function is set time out: 15 minutes 

function executed in 5 second 

Question:
So in final, what time will function and memory end ? after 5 second, 5 minutes, or 15 minutes ? 

thanks

**Comment by normj** [comment]
The 15 minute timeout is how long an individual request can be processed before it times out. The data in the in-memory cache will stay around for the 5 minutes **but** in that lambda processing container. Keep in mind typically in Lambda you have lots lambda processing containers each one handles one request at a time. So in a production system with many concurrent users your requests will be going through many different lambda processing containers. This page might give a better description on how Lambda scales https://docs.aws.amazon.com/lambda/latest/dg/invocation-scaling.html
