### ISSUE TITLE
Make AbstractAspNetCoreFunction.Init() async

### ISSUE THREAD

**Issue by damianh** [aws/aws-lambda-dotnet#702]
Make this method async: https://github.com/aws/aws-lambda-dotnet/blob/b54acef044860345c7c201a078713fe3b026c285/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L189

## Describe the Feature

When initializing a webhost it is desirable to be able to load configuration asynchronously. For example, from Secrets Manager or Parameter Store. As this method is Sync, one is forced to use the nasty `GetAwaiter().GetResult()` when calling async APIs from within this methods.

This has a bit of knock on effect, however the function handler:

https://github.com/aws/aws-lambda-dotnet/blob/b54acef044860345c7c201a078713fe3b026c285/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L431-L436

... is already async so this change is entirely possible.

### Is your Feature Request related to a problem?

More of a quality-of-life improvement.

## Proposed Solution

- Add an `InitAsync()` methods so it's not breaking.
- Call `InitAsync()` before calling `Init()` - users should only override one but if they override both things should still work.
- Optional - add `[Obsolete("..", false)]` attribute to `Init()`

### Describe alternatives you've considered

Currently using `GetAwaiter().GetResult()` which is not desirable, especially when already in an async context (via the function handler).

## Additional Context

Real world usage - loading config from Secrets Manager and Paramater Store.

Marking is as _potentially_ breaking, though making it non-breaking would be preferable.

### Environment

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by normj** [comment]
This is a valid feature request. I would be willing to take in a PR for this otherwise I will get to it when I can.

**Comment by damianh** [comment]
I've taken a look and it appears it won't be possible without a breaking change. The default mechanism to intitialize the aspnet core webhost is calling `Start()` from a constructor which will always be synchronous.

https://github.com/aws/aws-lambda-dotnet/blob/e2bb81a4b48a402570b0de828772067938ca5671/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L103-L111

Ultimately `Init()` is called via here: 
https://github.com/aws/aws-lambda-dotnet/blob/e2bb81a4b48a402570b0de828772067938ca5671/Libraries/src/Amazon.Lambda.AspNetCoreServer/HostBuilderExtensions.cs#L57
... which is inside a sync action that comes from `IHostBuilder.ConfigureWebHostDefaults()` of which whose API you don't have control over.

The only thing I can think of is to add nother virtual that invoked only if the `StartupMode` is set to `FirstRequest` and invoke it from within:
https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L433-L436

Something like:

```csharp
if (!IsStarted)
{
    await PreInitAsync();
    Start();
}

To be honest, I don't understand why one startup mode would have advantage or disadvantage over the other. In terms of a lambda lifecycle, it's only ever going to be _effectively_ initialized on first request.

**Comment by mungojam** [comment]
I've hit a similar thing with `APIGatewayProxyFunction` since I want to do an async operation during the `PostMarshallResponseFeature()` abstract call but can't do it properly because it isn't async

**Comment by damianh** [comment]
Hi Norm, sorry dropped the ball this. Had a chance to look at over the holidays and on reflecion I think adding yet another virtual member `PreInitAsycn` doesn't make things simpler for the end user. They'd probably end up writing code like:

```csharp

private IConfiguration _config;

public overide async Task PreInitAsync()
{
	_config = await LoadConfigAsync();
}

public overide void Init(IWebHostBuilder builder)
{
	builder.UseConfiguration(_config);
}
```

I'm also not happy with the oxymoronic name.

My current thinking is to make a breaking change - Remove `StartupMode` (I still don't know why it exists or why one would prefer `Constructor` over `FirstRequest`), initialize on first request and make `Init()` -> `InitAsync()`.

**Comment by mungojam** [comment]
Still relevant

**Comment by ashishdhingra** [comment]
Needs review. @normj Please check if this is still relevant.
