### ISSUE TITLE
3.1 AWS Test Tool hangs upon waiting on async result, 2.1 doesn't

### ISSUE THREAD

**Issue by mhelbig-oz** [aws/aws-lambda-dotnet#704]
## The Question

I'm in the process of upgrading my lambdas from 2.1 to 3.1. Upon finishing the conversion they appear to be starting and loading their input, but they hang on the first time they await any kind of async result. As a test, I made a small async function and tried it in my 2.1 environment versus the new code in 3.1:

		
```
public async Task<string> ImmaGenerateAString()
{
	await Task.Delay(500);
	return "Blah";
}

public string FunctionHandler(Stream input, ILambdaContext context)
{
	OZ.AWS.Lambda.Log(ImmaGenerateAString().Result);
        ...
```

In 2.1 this will log, in 3.1 it never completes.

I'm stumped what is causing this. I made a new empty 3.1 project and it exhibits the same behavior on my machine. Was there some kind of fundamental change in the way this works that I missed?

### Environment
* Build Version: 0.10.0
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  3.1

**Comment by normj** [comment]
Thanks for reporting the issue. I'm assuming you are talking about the test tool. I have identified the problem being in 3.1 the tool uses server side Blazor which uses a synchronization context which triggers the deadlock when the Lambda code blocks on async calls.

I have pushed out a PR to work around the issue. https://github.com/aws/aws-lambda-dotnet/pull/705

**Comment by mhelbig-oz** [comment]
Thank you for the quick turn around! Pardon my ignorance, but I'm having trouble figuring out approximately when this will be released.

**Comment by normj** [comment]
I just pushed out version 0.10.1 of the tool. So if you are using Visual Studio the next time you restart visual studio and debug it should download the new version. To confirm you have the newest version you can run the command in the command window.

```
dotnet tool list -g
```

You should see 0.10.1 for amazon.lambda.testtool-3.1.

If for some reason you don't you can manually update running the following command:

```
dotnet tool update -g amazon.lambda.testtool-3.1
```

**Comment by mhelbig-oz** [comment]
Perfect thank you so much!
