### ISSUE TITLE
Use .NET Generic Host For Non-AspCore Lambda Blueprints

### ISSUE THREAD

**Issue by cristeh** [aws/aws-lambda-dotnet#709]
There are a lot of cases where one would like to have an AWS lambda that is not an ASP Core application, but still benefit from Microsoft's logging, DI and other Microsoft.Extensions.* packages. 
Some libraries allow to go around this to a degree, but their implementations are quite awkward and custom, and sometimes even hide potentially harmful bugs(DI trees leaking or holding captive dependencies which show up in reused containers).
Microsoft recently introduced https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1 that could be repurposed for lambda usages.

## Describe the Feature
Create a library that uses the .NET Generic Host for non-AspCore envs and generate blueprints used in the most common scenarios(such as SQS and SNS subscriptions) based on it.

### Is your Feature Request related to a problem?
Microsoft.Extensions.* provide a lot of valuable libraries that are commonly used by .NET core developers even in non-ASP related circumstances, but such uses were problematic before the introduction of the Generic Host functionality. 
Now that such functionality exists, a 1st class implementation from AWS would allow us to take advantage of those libraries without dealing with boilerplate/3rd party libraries/half-baked implementations due to the lack of knowledge of the AWS lambda internals. 
It also has the potential to help in other areas, such as optimizing the application for container reuse.

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by andyfurniss4** [comment]
I was just coming here to create the very same issue. I just tried to create a Lambda function for an API Gateway Authorizer and would like to use DI, Logging and Configuration extensions with the IHostBuilder but sadly there only seems to be a few, very specific base classes for your function class (API Gateway proxy function, load balancer).

+1 for this.

**Comment by Kralizek** [comment]
You could give a try to the templates I have created here: https://github.com/Kralizek/AWSLambdaSharpTemplate

**Comment by acraven** [comment]
This sounds like what I'm looking for. I've inherited a code-base containing multiple lambdas that using a custom framework; the framework provides some hooks for DI customisation that are executed the first time a handler is invoked during a cold start and the IServiceProvider is stored in a field for the remaining life of the instance for warm starts.

The concept of initialising the generic host when the lambda cold starts makes perfect sense to me, and would allow me to separate the initialisation and implementation concerns that are clumsily bundled together in our code-base.

I can probably spare some time if there's anything I can help with.

**Comment by normj** [comment]
Our answer for how to use DI in Lambda is using our upcoming `Amazon.Lambda.Annotations` library. I'm going to close this issue and I encourage the discussion of needed features into that library's design thread. https://github.com/aws/aws-lambda-dotnet/issues/979

**Comment by JuanZamudioGBM** [comment]
@normj  How does Amazon.Lambda.Annotations help in the original question of the OP?

If I have a Lambda that does not use ASP.NET and I want to use IHostBuilder to add  ConfigureLogging (with AddSystemdConsole) how can I achieve that with Amazon.Lambda.Annotations?

**Comment by normj** [comment]
@JuanZamudioGBM Is there a reason you specifically need the `IHostBuilder`? You can configure logging via the `IServiceCollection` in the `Startup` class.

```csharp
    [Amazon.Lambda.Annotations.LambdaStartup]
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging(configure =>
            {
                configure.AddSystemdConsole();
            });
        }
    }


    public class Functions
    {
        [LambdaFunction()]
        [HttpApi(LambdaHttpMethod.Get, "/")]
        public string Default([FromServices] ILogger<Functions> logger)
        {
            logger.LogInformation("Test Logger");

            return "Test Function";
        }
    }
```

**Comment by JuanZamudioGBM** [comment]
@normj  I was under the impression that IHostBuilder was the preferred way to initialize configuration and logging in the latest frameworks.

Thanks for the snippet.

**Comment by normj** [comment]
I view the `IHostBuilder` serving at least 2 purposes. The first is helping configure the `IServiceCollection` which is what you are talking about. The second is starting the process via the `StartAsync` or `Build().Start()` operations. The starting process would be confusing in Lambda because Lambda controls the process flow. 

I believe the extension methods available for `IServiceCollection` should be sufficient compared to `IHostBuilder`. If you feel strongly that we should have some sort of host builder I recommend moving the conversation to the main feedback thread on this library. https://github.com/aws/aws-lambda-dotnet/issues/979
