### ISSUE TITLE
Preview of the AWS Toolkit for Visual Studio 2017

### ISSUE THREAD

**Issue by normj** [aws/aws-lambda-dotnet#71]
Today we released a preview of our AWS Toolkit for Visual Studio that includes support for the release candidate (RC) version of Visual Studio 2017. Because this Visual Studio release contains some significant changes for extension developers, we're making this preview available in advance of the formal release. We highly encourage you to pass along feedback about any issues you find or whether you were successful using the preview by commenting on this GitHub issue.

## AWS Lambda .NET Core Support ##

Visual Studio 2017 also contains support for the new MSBuild project system for .NET Core projects. With this preview of the toolkit, we've updated the .NET Core Lambda support to use the new build system. For existing Lambda projects based on the Visual Studio 2015 project.json-based build system, Visual Studio 2017 offers to migrate them to the new build system when you open the projects.

## Downloading and Installing the Preview ##
The AWS Toolkit for Visual Studio contains MSBuild target files for AWS CloudFormation projects. In previous releases of Visual Studio, you had to install these files and dependencies for an extension outside of the Visual Studio folder hierarchy. This required us to use a Windows Installer to install the toolkit. Starting with Visual Studio 2017, these MSBuild extensions exist within the Visual Studio folder hierarchy and can be installed from the VSIX extension package without an installer. As the installer technology we use doesn't yet support Visual Studio 2017, we've decided to distribute the preview as a VSIX file only.

**To install the preview**
* Download the VSIX file from the [preview link](https://sdk-for-net.amazonwebservices.com/preview/AWSToolkitPackage.VS2017.vsix)
* Double-click the VSIX file. This launches the VSIX Installer process, as shown.

After the installer finishes, the toolkit functions as it has in previous versions of Visual Studio.

**Comment by TheRubble** [comment]
Works a treat thanks.

**Comment by genifycom** [comment]
Using this and works well.
Thank you for the VS 2017 support!

**Comment by steveataws** [comment]
Hi everyone,

You may have noticed this morning that we promoted the toolkit preview for Visual Studio 2017 to General Availability (GA), https://aws.amazon.com/blogs/developer/general-availability-of-the-aws-toolkit-for-visual-studio-2017/.

We're closing this thread now that we've released. If anyone has any outstanding issues, we ask that you raise a new issue in this repo and we'll investigate.

Thanks for helping us test out the package and providing feedback!
