### ISSUE TITLE
Invalid cookie handling for APIGatewayHttpApiV2ProxyFunction request and response

### ISSUE THREAD

**Issue by sleeuwen** [aws/aws-lambda-dotnet#713]
## Description

The `APIGatewayHttpApiV2ProxyFunction` does not correctly set the Cookie header for a request, and also doesn't correctly set the `Set-Cookie` header on responses.

For the requests, the value of the `Cookie:` header is passed through in the `Cookies` property of the `APIGatewayHttpApiV2ProxyRequest`, but never used. The `Cookie:` header itself is omitted from the `Headers` property which means cookies are never set in the ASP.NET Core Request object.

On responses, the `Set-Cookie` header is added to the `Headers` property of the `APIGatewayHttpApiV2ProxyFunction`, which combines multiple values comma-separated. These values should instead be added to the `Cookies` property to correctly have API Gateway return multiple `Set-Cookie` headers. The comma-separated value is invalid and does not work in browsers.

## Reproduction Steps

Create a new Lambda with an API Gateway with HTTP API and response format V2. Use the default Lambda web app template, and try to set multiple cookies and read them back in from the controller. 

### Environment

* Build Version: 5.1.3
* OS Info: Arch Linux
* Build Environment: Terminal `dotnet`
* Targeted .NET Platform: netcoreapp3.1

## Resolution

I have been able to work around this by adding the following code blocks in my LambdaEntryPoint to set the correct values for request and response, but I would expect this to be done in the ProxyFunction.

```csharp
protected override void PostMarshallRequestFeature(IHttpRequestFeature httpRequest, APIGatewayHttpApiV2ProxyRequest lambdaRequest, ILambdaContext lambdaContext)
{
    httpRequest.Headers[HeaderNames.Cookie] = string.Join(';', lambdaRequest.Cookies);
}

protected override void PostMarshallResponseFeature(IHttpResponseFeature httpResponse, APIGatewayHttpApiV2ProxyResponse lambdaResponse, ILambdaContext lambdaContext)
{
    lambdaResponse.Headers?.Remove(HeaderNames.SetCookie);
    lambdaResponse.Cookies = httpResponse.Headers[HeaderNames.SetCookie].ToArray();
}
```

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @sleeuwen,

Thanks for reporting an issue. I will pass on this issue to developer for further investigation and update this issue once there is an update.

Regards,
Ashish

**Comment by petli** [comment]
Thanks for the workaround, this bit me too. Though I had to handle that `lambdaRequest.Cookies` may be null:

        protected override void PostMarshallRequestFeature(IHttpRequestFeature httpRequest, 
                                                           APIGatewayHttpApiV2ProxyRequest lambdaRequest, 
                                                           ILambdaContext lambdaContext)
        {
            if (lambdaRequest.Cookies != null)
            {
                httpRequest.Headers[HeaderNames.Cookie] = string.Join(';', lambdaRequest.Cookies);
            }
        }

**Comment by AZarenin** [comment]
I have exactly the same issue and raised a bug report, but, unfortunately, in the wrong branch: https://github.com/aws/aws-sdk-net/issues/1691. Now I will follow this bug report - hopefully the new release of respective nuget will come out soon!

**Comment by normj** [comment]
Version 5.1.4 of Amazon.Lambda.AspNetCoreServer has been released with the PR containing the fix.
