### ISSUE TITLE
Lambda Test Tool not providing clean output when using amplify GraphQL Api To invoke

### ISSUE THREAD

**Issue by staticinteger** [aws/aws-lambda-dotnet#715]
## The Question

Is there a config option to stop the log output so that I get a clean response?

When I run `amplify mock` and invoke my .net function from my GraphQL API the response is filled with log information and not a clean data. 

#### Example of the output I'm getting:
```
{
  "data": {
    "comprehend": "AWS .NET Core 3.1 Mock Lambda Test Tool (0.10.1)\nLoaded local Lambda runtime from project output /Users/[REDACTED]/Development/[REDACTED]/amplify/backend/function/comprehend/src/bin/Debug/netcoreapp3.1\nExecuting Lambda function without web interface\nFound Lambda config file /Users/[REDACTED]/Development/[REDACTED]/amplify/backend/function/comprehend/src/aws-lambda-tools-defaults.json\n... Using config file /Users/[REDACTED[/Development/[REDACTED]/amplify/backend/function/comprehend/src/aws-lambda-tools-defaults.json\n... Using function handler comprehend::comprehend.comprehend::LambdaHandler\n... Using payload with from the file /Users/[REDACTED]/Development/[REDACTED]/amplify/backend/function/comprehend/amplifykYuBsn/event.json\n... Setting AWS_PROFILE environment variable to default.\n... No default AWS region configured. The --region switch can be used to configure an AWS Region.\nCaptured Log information:\n\nRequest executed successfully\nResponse:\n\"This is a test\""
  }
}
```

#### Expected output is:
```
{
  "data": {
    "comprehend": "This is a test"
  }
}
```

Let me know if you need any more info and / or I am making some kind of mistake. Appreciate it!

### Environment

* Build Version: 0.10.1 
* OS Info: OSX Catalina
* Build Environment: VSCode + Terminal `amplify mock` 
* Targeted .NET Platform:  Not sure.

---

This is a :question: general question

**Comment by staticinteger** [comment]
Didn't mean to close this, sorry about that!

**Comment by ashishdhingra** [comment]
Hi @staticinteger, 

I'm not sure on is using Lambda Test Tool with AWS Amplify is a supported scenario looking at the [command line options](https://github.com/aws/aws-lambda-dotnet/blob/e2bb81a4b48a402570b0de828772067938ca5671/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/CommandLineOptions.cs#L6) for Lambda Test Tool, I don't see an option to supress verbose output.

Thanks,
Ashish

**Comment by staticinteger** [comment]
@ashishdhingra Thanks! I'll contribute to the project and add support for AWS Amplify. Hoping I can add support for this since it is essential to how I develop using AWS Amplify :)

**Comment by staticinteger** [comment]
@ashishdhingra Is there any documentation / tips you can give me on how to get the project up and running for local development on the lambda test tool? That would be super helpful! :D

**Comment by ashishdhingra** [comment]
Hi @staticinteger,

The [aws-lambda-dotnet -> LambdaTestTool](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool) has Readme that list details of this tool. Hope it helps. Please let me know if this issue could be closed. Feel free to submit a PR with your contribution.

Thanks,
Ashish
