### ISSUE TITLE
Guaranteeing logs are flushed - Best Practices

### ISSUE THREAD

**Issue by mhelbig-oz** [aws/aws-lambda-dotnet#717]
## The Question
Is there a proper way to guarantee that all log calls are written to Cloudwatch prior to a Lambda exiting? I see very rare cases where according to the logs, it appears that the Lambda just exits part way through. No exceptions are logged, and the logs I put in to flag success never make it to the file. This is flagged as an error by our internal processes, and every investigation I've done for these seem to indicate that everything did run successfully we just stopped logging partway through the invocation.

I am logging using Amazon.Lambda.Core.LambdaLogger.Log. If I use the logger on the ILambdaContext could it avoid this issue? Is there a flush I could call somewhere?

### Environment
* Package Version: Amazon.Lambda.Core 1.1
* OS Info: Amazon Linux
* Build Environment: Visual Studio
* Targeted .NET Platform:  Core 3.1

---

This is a :question: general question

**Comment by mhelbig-oz** [comment]
It's going to take me some time to write up an example and get results, but I'll try to get to it this week.

**Comment by mhelbig-oz** [comment]
Just posting a comment on here in case anyone runs into this, this has been verified to be an issue with AWS but no one has given me a timeline for a fix.

**Comment by nCubed** [comment]
@mhelbig-oz Was there ever a final recommendation of which logger to use? The static logger or the context logger?

**Comment by mhelbig-oz** [comment]
Nope and they haven't fixed it. We just add a sleep prior to closing which makes them money so I guess they are happy.

**Comment by bgourlie** [comment]
I don't believe this is specific to any logger implementation, as I've encountered it with both the AWS vended java logger as well as when simply writing to stdout using `System.out.println` (lambda logs anything written to stdin).

In our case, we were producing thousands of log entries in a loop, which seems to overwhelm whatever mechanism reads stdin and pushes entries to the log stream.
