### ISSUE TITLE
AWSLambdaPSCore - ErrorAction Stop errors on install dotnet global tool

### ISSUE THREAD

**Issue by bgelens** [aws/aws-lambda-dotnet#725]
## Description

`New-AWSPowerShellLambdaPackage -ErrorAction Stop` or `$ErrorActionPreference = 'Stop'; New-AWSPowerShellLambdaPackage` will throw an error that should be handled.

Error:

![image](https://user-images.githubusercontent.com/10071039/91288755-a869c680-e791-11ea-8654-422b9f973d89.png)

## Reproduction Steps

See above

### Environment

PowerShell 7.0.3 on MacOS and Ubuntu 18.04
AWSLambdaPSCore v2.0.0.0

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

I'll add a PR
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-lambda-dotnet/pull/726 has been merged. Closing this issue.
