### ISSUE TITLE
Publish profiles - Supply credentials on cmd line.

### ISSUE THREAD

**Issue by TheRubble** [aws/aws-lambda-dotnet#73]
Hi,

Currently I don't have the ability to provide the publish profile as the build agent is hosted in VSTS. Is it possible to supply the Access Key, Secret and Account number on the cmd line? These are currently protected by roles in the build system.

dotnet lambda deploy-serverless -secret ??? -Access ?? -Accno

Thanks

**Comment by normj** [comment]
Can you set the environment variable AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY before executing dotnet lambda commands? If no profile is specified the environment variables will be used.

**Comment by TheRubble** [comment]
Perfect
