### ISSUE TITLE
Support Cognito Pre Token Generation Event

### ISSUE THREAD

**Issue by GuzzoLM** [aws/aws-lambda-dotnet#732]
## Describe the Feature
Cognito can call a lambda before token generation to allow customization of identity token claims.
As described [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html)

## Proposed Solution
The solution is to add the contract for this event on the library

## Additional Context
I'm trying to add claims to an identity token based on the user groups that a user belongs to.

* [X] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by jon-armen** [comment]
This is covered by #1051

**Comment by normj** [comment]
PR #1051 has been released as part of version 2.1.0 of Amazon.Lambda.CognitoEvents which implements this feature.
