### ISSUE TITLE
How to know lambda local URL and call it from another function using Mock Lambda Test Tool

### ISSUE THREAD

**Issue by pablocastilla** [aws/aws-lambda-dotnet#734]
## The Question
Hi

I have a project in VS with two functions, I just want to call one function from the other one in the local environment (of course debugging both of them).

How could I do it? The first one is triggered by a sqs message and the second one by REST. I am executing the environment using the Mock Lambda Test Tool. 

Should I use another tool?

Also:
how could I know the local url of the rest one?

Thanks

### Environment

* Build Version: latest
* OS Info: Windows 10 
* Build Environment:  Visual Studio 2019
* Targeted .NET Platform:  3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @pablocastilla,

Good morning. 

Lambda Test Tool is recommended for testing simple functional handlers and it would be better to use tested using IIS/IIS Express/Kestrel to test REST endpoints. However, you could refer the guidance provided in https://github.com/aws/aws-lambda-dotnet/issues/589#issuecomment-682179425 to test API methods locally.

Handler that is executed via SQS message can be tested using Lambda Test Tool by selecting appropriate request type in Lambda Test Tool and customizing the request parameters. Please refer [Lambda Test Tool Readme](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool) for more details. 

The URL for Lambda test tool could be determined from the console window (which is launched while invoking test tool) or browser URL.

Please let me know if this helps and if this issue could be closed.

Thanks,
Ashish

**Comment by pablocastilla** [comment]
Hi!

Thanks for the response. I think it helps and you can close.

As a suggestion I would like to have somekind of debugging tool that executes every lambda in the project and their interactions, that way I can do some small integration tests in which one lambda call another and so on.

Thanks
