### ISSUE TITLE
Support NTLM Auth Inside Lambda Functions

### ISSUE THREAD

**Issue by pnquest** [aws/aws-lambda-dotnet#735]
Currently NTLM authentication from within a .net core lambda cannot be done because of a missing dependency the .net core runtime needs to achieve this.

## Describe the Feature

Add in the missing required libraries to make NTLM auth work in a .net core lambda.

### Is your Feature Request related to a problem?

We are struggling to consume older soap-based services that rely on NTLM authentication.

## Proposed Solution

There seems to be 2 options here:
1. Install the gssntlmssp (sometimes called gss-ntlmssp) in the lambda runtime so it is available for use
2. update to the latest version of the krb5-libs package, which would allow users to package the above library with their lambda since the gssapi config location is configurable in that version.
---

This is a :rocket: Feature Request

**Comment by oshea00** [comment]
I'm wondering if the recently announced capability to use custom containers for lambdas provides a way to add these dependencies?

**Comment by pnquest** [comment]
@oshea00 Yes, that would be a solution, however I am under the (possibly false) impression that you must host your images with ECR, We use a different solution for all our build artifacts including docker containers.

**Comment by jstallm** [comment]
What is the latest on this? Is the workaround to convert the lambda runtime to a custom runtime, then install a custom plugin? If so, that process is not well documented. Can we get some clarification on this process please?

**Comment by ashishdhingra** [comment]
@pnquest Not sure of this would help, could you please refer section `System.Drawing support with container images` at [.NET 5 AWS Lambda Support with Container Images](https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/). It provides some pointers on how to include native dependencies. May be it could help in your scenario as proposed by you in issue description.

**Comment by michaelsync-mt** [comment]
Any update on this?
