### ISSUE TITLE
Authentication info is not available in request context for mTLS

### ISSUE THREAD

**Issue by albertocorrales** [aws/aws-lambda-dotnet#736]
## Description
mTLS support was recently delivered for API Gateway. https://aws.amazon.com/blogs/compute/introducing-mutual-tls-authentication-for-amazon-api-gateway/. However, we are not able to get the client certificate, since the new "authorization" object is not available in requestContext object.

![image](https://user-images.githubusercontent.com/33038414/94065277-382f7e80-fdeb-11ea-915d-8f5c700f7710.png)

## Reproduction Steps
Authorization section is not available in ProxyRequestContext object, as we can see in https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayProxyRequest.cs

### Environment

* Build Version: master
* Targeted .NET Platform:  3.1

## Resolution
In order to solve this issue, object ProxyRequestContext should be extended with new "authorization" section

---

This is a :bug: bug-report

**Comment by normj** [comment]
Thanks for bringing this to our attention. Looks like a pretty simple update to the event class.

**Comment by normj** [comment]
I submitted PR to add the new fields.
https://github.com/aws/aws-lambda-dotnet/pull/737

**Comment by normj** [comment]
Version 2.2.0 of Amazon.Lambda.APIGatewayEvents is out with the new properties for mTLS.
