### ISSUE TITLE
Add support for binary response content

### ISSUE THREAD

**Issue by ebekker** [aws/aws-lambda-dotnet#74]
As described in [this AWS Developer Forum post](https://forums.aws.amazon.com/thread.jspa?messageID=760374#760374), in order to support binary response content from a Lambda function invoked by API Gateway proxy, the Lambda response needs to include the `isBase64Encoded: true` flag in its JSON response payload.

The most recent revision of the [`APIGatewayProxyResponse`](https://github.com/aws/aws-lambda-dotnet/blob/144df7cb7988ae8fb007d5ea7e172d23faff0d5b/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayProxyResponse.cs) response model class does not include such a flag and the furthermore, the [`AspNetCoreServer`](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer) package would need to provide a means of *triggering* (and *flagging*) the base64-encoding when binary response content is returned from a controller action method.

**Comment by ebekker** [comment]
Adding the additional flag is trivial and would support the basic use-case when authoring C# Lambda functions that handle [`APIGatewayEvents`](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.APIGatewayEvents).

However, the `AspNetCoreServer` support is a bit trickier -- a controller action method returns an `IActionResult` instance and its content ultimately gets serialized into a string in all cases.  However, it's not always clear just from that instance, if the raw result should be encoded directly (Base64) or transformed to UTF8.

After some experimentation I'm thinking that a good compromise that would minimize the impact on the normal controller code would be to put some flags and options on the base `APIGatewayProxyFunction` class, since this needs to be sub-classed in any event and at a minimum that subclass would contain Lambda-specific logic such as a call to the extension method `UseApiGateway()`.

I'm thinking about 2 possible approaches to support:
* set a global "always-on" boolean that simply indicates that all responses from all controllers actions should be treated literally and don't do any transformation on anything
* setup a collection of one or more `Content-Type` header values to look for that would *trigger* the Base64-encoding and flagging, for example, when ever a response for `application/octet-stream` or `application/zip` or some image content type -- that would trigger the raw response bytes to be transformed into a Base64-encoding, and it would set the flag `isBase64Encoded` to true in the Labmda response to the API Gateway.

**Comment by normj** [comment]
Closing the issue because it is being tracked in a pull request
https://github.com/aws/aws-lambda-dotnet/pull/75

**Comment by damianh** [comment]
>  the AspNetCoreServer package would need to provide a means of triggering (and flagging) the base64-encoding

Came here to report the same isue. Had same problem with my https://github.com/damianh/AwsLambdaOwin
