### ISSUE TITLE
Error when I deploy my lambda 

### ISSUE THREAD

**Issue by dalton5** [aws/aws-lambda-dotnet#740]
Hi,

For information it worked two days ago and it doesn't work anymore.

I publish my lambda and I do not understand I have the error below:

> ... publish: Authorization\Users\Entity\restosAppService.cs(463,18): warning CS0219: The variable 'loadExternal' is assigned but its value is never used [C:\Users\mike\Documents\GitHub\restoproj\aspnet-core\src\restoproj.Dev.Application\restoproj.Dev.Application.csproj]
... publish:   restoproj.Dev.Application -> C:\Users\mike\Documents\GitHub\restoproj\aspnet-core\src\restoproj.Dev.Application\bin\Release\netcoreapp2.2\restoproj.Dev.Application.dll
Failed to create application package
Error packaging up project in C:\Users\mike\Documents\GitHub\restoproj\aspnet-core\src\restoproj.Dev.Web.Host\. for CloudFormation resource DefaultFunction

I try to investigate but I do not have anymore clues.

Where can I get more clues to undersatnd the issue?

My config is as below:

.json config

`{
    "region" : "us-east-1",
    "profile" : "lambdaAws",
    "s3-bucket" : "wtbucketlambda",
    "template"  : "serverless.template",
    "stack-name" : "WT",
    "configuration" : "Release",
    "framework"     : "netcoreapp2.2",
    "msbuild-parameters" : "--self-contained true"
}`

My serverless.template file

`{
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Transform" : "AWS::Serverless-2016-10-31",
  "Description" : "Starting template for an AWS Serverless Application.",
  "Resources" : {
    "DefaultFunction" : {
      "Type" : "AWS::Serverless::Function",
      "Properties": {
       "Handler": "not_required_for_custom_runtime",
				"Runtime": "provided",
        "CodeUri": "",
        "Description": "Default function",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [ "AWSLambdaFullAccess", "AmazonSSMReadOnlyAccess",
    "AWSLambdaVPCAccessExecutionRole" ],
        "Events": {
          "ProxyResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/{proxy+}",
              "Method": "ANY"
            }
          },
            "APIWarmingSchedule": {
                        "Type": "Schedule",
                        "Properties": {
                            "Schedule": "rate(5 minutes)",
                            "Input": "{ \"Resource\": \"WarmingLambda\", \"Body\": \"5\" }"
                        }
        }
      }
    }
    }
  },
  "Outputs" : {
    "ApiURL" : {
        "Description" : "API endpoint URL for Prod environment",
        "Value" : { "Fn::Sub" : "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/" }
    }
  
  }
}`

**Comment by ashishdhingra** [comment]
Hi @dalton5, 

Good afternoon.

At first glance, looking at the issue above, it appears to be a build issue. Please confirm if you are able to build solution locally, if you changed .NET version, any change in the project done in the past 2 days, credentials change, etc. Also, please share detailed log to troubleshoot further.

Thanks,
Ashish

**Comment by dalton5** [comment]
Ok. It finally works. I have absolutely no ideas on what was the issue. Thanks
