### ISSUE TITLE
Returning compressed(gzip) json from API running inside of Amazon.Lambda.AspNetCoreServer behind ELB

### ISSUE THREAD

**Issue by stuartdga** [aws/aws-lambda-dotnet#741]
## The Question
I can't get my ASP.NET WebAPI running in a Lambda serverless function to return a compressed response.
I know that this seems identitical to issue [355](https://github.com/aws/aws-lambda-dotnet/issues/355) but in this instance the Lambda function is not behind an API Gateway. Instead it is behind an Elastic Load Balancer (Server: awselb/2.0). I followed the steps from issue 355 but that doesn't seem to work. My json repsonse is never compressed. If I run my API outside of Lambda, the response is compressed. Is there a reason that I can't get a compressed response from my Lambda function running behind ELB?

### Environment

* Build Version: 
* OS Info: AWS Lambda
* Build Environment: Azure DevOps
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @stuartdga,

Good afternoon.

I'm not sure if it helps, could you please check the post https://stackoverflow.com/questions/47067212/does-aws-application-load-balancer-actually-support-compression on StackOverflow. Let me know if it provides some guidance.

Thanks,
Ashish

**Comment by stuartdga** [comment]
Sorry, the article referenced didn't help. Look at this:

[Amazon.Lambda.AspNetCoreServer README.md](https://github.com/aws/aws-lambda-dotnet/blob/1103e40db774608a2e7bd1c9391ceddfb4cda8b8/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md
)

It specifically describes how to return the binary response from the lambda function. This is not working for me behind ELB.

**Comment by ashishdhingra** [comment]
Hi @stuartdga,

Good morning.

As per StackOverflow post, I don't think load balancer would compress the responses. Please refer to the article [Response compression in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.1), try using the Gzip compression provider. Let me know if it works.

Thanks,
Ashish

**Comment by stuartdga** [comment]
I am already implementing the correct GZip compression using .NET Core. This has been tested and working. The compression is failing **AFTER** I have deployed to the Web API to my Lambda function that is behind the ELB. 

I have also read this: [Supporting Binary Response Content](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer#supporting-binary-response-content)

But this simply isn't working.

**Comment by ashishdhingra** [comment]
Hi @stuartdga,

Good afternoon.

Unfortunately, all the examples that I have seen so far specify the use of API Gateway. From the link [Supporting Binary Response Content](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer#supporting-binary-response-content) that you shared, it also specifies that no changes are required in ALB for binary content. Request you to share sample code solution so that I can try to troubleshoot the issue.

Thanks,
Ashish

**Comment by senseicz** [comment]
Hello @stuartdga , have you ever resolved this issue, please?

I'm trying to come up with a solution for oversized API response when 2 lambdas communicate with each other and one respond with really large amount of data. Both lambdas are .Net Core 6. Large data response producer have ResponseCompression middleware enabled and additional middleware is inspecting size of compressed response body and if larger than threshold, it will dump full response to S3, modify response status code and add location of S3 file into a response header. It is then on consumer to handle this properly.
When running locally, I can confirm request headers contain Accept-Encoding: gzip, deflate header, response body is properly gzipped when inspected and response headers have Content-Encoding: gzip response header as well as my custom one with S3 file location.
However, when deployed to AWS, behind ALB, request headers are the same but when inspecting response body, it is **not** gzipped and there is no Content-Encoding header either. I'm still able to gzip response body and save as file to S3 but even when I replace response body with empty stream, lambda still emit 502 Bad Gateway error indicating that response body was over 6MB limit. What is really annoying  is that lambda itself finish without error, that 502 Bad Gateway error is generated later (my speculation is when response is passing ALB).
Seems to me like AWS Lambda AspNetCoreServer is somehow messing with .Net native ResponseCompression middleware, somehow disabling it and only leaving response compression on some later stage outside of my lambda process.

Any idea appreciated.
