### ISSUE TITLE
Lambda WebAPI with ODATA and Swagger - Works when run locally, doesn't work in unit tests or when deployed

### ISSUE THREAD

**Issue by vozeldr** [aws/aws-lambda-dotnet#749]
# Lambda WebAPI with ODATA and Swagger - Works when run locally, doesn't work in unit tests or when deployed

I created a [github repo](https://github.com/vozeldr/DotNetLambda3/tree/features/ImplementOdataAndSwagger) that shows a basic example based on the `serverless.AspNetCore30WebAPI` template.

The master branch is the unaltered code as created by the template. 

The branch `features/ImplementOdataAndSwagger` has been upgraded to 3.1 and has ODATA and Swagger configured. 
It displays the issues below:

- Will not display the swagger documentation through the API gateway/lambda.
    + Returns a 404 not found for the `swagger.json` file and for `index.html`
    + Swagger works fine when run locally.
- Does not correctly respond to ODATA query string parameters in the unit tests or when deployed as a Lambda.
    + It does return ODATA when the path `odata/WeatherForecast` is hit
    + Any of the expected behaviors like $filter, $select, $count, $skip, $top do not work
    + When run locally, the ODATA query-enabled endpoint operates correctly, i.e. performing a GET request to
    https://localhost:5001/odata/WeatherForecast?$select=id,temperatureC&$skip=2&$top=5&$count=true will return
    5 items starting with item #3. It will only return the Id and TemperatureC properties. It also returns the
    total count of 20 items.
    
```json
{
  "@odata.context":"https://localhost:5001/odata/$metadata#WeatherForecast(Id,TemperatureC)",
  "@odata.count":20,
  "value":[
    {"Id":3,"TemperatureC":41},
    {"Id":4,"TemperatureC":4},
    {"Id":5,"TemperatureC":40},
    {"Id":6,"TemperatureC":1},
    {"Id":7,"TemperatureC":9}
  ]
}
```

## The Question

Simply, what am I missing here and how do I get it to work?

### Environment

* Build Version: Amazon.Lambda.AspNetCoreServer 4.0.0, Amazon.Lambda.RuntimeSupport 1.0.0
* OS Info: Pop!_OS 20.04
* Build Environment: JetBrains Rider / CLI
* Targeted .NET Platform:  netcoreapp3.1 / Microsoft.NET.Sdk.Web

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @vozeldr,

Good morning.

Please try enabling CloudWatch logging to capture the query string parameters and provide the generated log for further troubleshooting. I will try to troubleshoot the issue at my end and will keep you posted of any findings.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @vozeldr,

I enabled CloudWatch logging in your project using `AWS.Logger.AspNetCore` package and deployed using the Serverless template. When I access the URL https://xxxxxxxx.execute-api.us-east-2.amazonaws.com/Prod/WeatherForecast?$select=id,temperatureC&$skip=2&$top=5&$count=true, I could see the following in the CloudWatch log:
```
[Information] DotNetLambda.Controllers.WeatherForecastController: Request QueryString: ?$count=true&$select=id%2CtemperatureC&$skip=2&$top=5  
```

Looks like the QueryString is URL Encoded which could be causing the Data query not to work. It appears similar to the existing issue https://github.com/aws/aws-lambda-dotnet/issues/694. It also references issue in OData repository which appears to have a workaround https://github.com/OData/WebApi/issues/1227#issuecomment-368782008.

When I try to GET the URL https://xxxxxxxx.execute-api.us-east-2.amazonaws.com/Prod/index.html it returns the below error:

<img width="1475" alt="Screen Shot 2020-10-14 at 10 48 29 AM" src="https://user-images.githubusercontent.com/67916761/96026053-dcb14900-0e0a-11eb-9251-785902c368b4.png">

However, when I hot the URL https://xxxxxxxx.execute-api.us-east-2.amazonaws.com/Prod/swagger/v1/swagger.json, I do get the swagger.json:

<img width="1389" alt="Screen Shot 2020-10-14 at 10 54 42 AM" src="https://user-images.githubusercontent.com/67916761/96026687-b809a100-0e0b-11eb-90bb-20629fcaaec0.png">

Please refer comment https://github.com/aws/aws-lambda-dotnet/issues/216#issuecomment-400969490 for possible resolution.

Let me know if the workaround for the OData issue works and if guidance for swagger JSON issue is helpful, and is this issue could be closed.

Thanks,
Ashish

**Comment by vozeldr** [comment]
I do appreciate you looking into this, but I don't think that having the `,` in the query string is the problem. Even a very simple query string like `?$select=name` does not work. I'll test out the workarounds you linked me to though.

**Comment by vozeldr** [comment]
Ok, so the goofy workaround of creating a CustomEnableQueryAttribute from 4.5 years ago works to get ODATA query strings working, so that's something.

For the swagger issue, using the resolution linked to above does make swagger start working when deployed but breaks it when running locally. I think ultimately that was closed referencing [this as the solution](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/856#issuecomment-415900061) but that BasePath property doesn't seem to exist any more. This is another problem from over 4 years ago. Doing something hacky like this in Startup.cs gets it working both locally and when deployed:

```csharp
app.UseSwaggerUI(c =>
{
    string endpointUrl =
        $"{(string.IsNullOrEmpty(Environment.GetEnvironmentVariable("AWS_LAMBDA_FUNCTION_NAME")) ? string.Empty : "/Prod")}/swagger/v1/swagger.json";
    c.SwaggerEndpoint(endpointUrl, "Example REST API v1");
    c.RoutePrefix = string.Empty;
});
```

**Comment by nathanvj** [comment]
@vozeldr If I may ask, what did you do to fix the issue where the Lambda does not correctly respond to the OData query parameters?

I'm currently experiencing the same issue, and the proposed fix of creating a `CustomEnableQueryAttribute` does not work for me:

```cs
public class CustomEnableQueryAttribute : EnableQueryAttribute
{
    public CustomEnableQueryAttribute()
    {
    }

    /// <summary>
    /// See https://github.com/OData/WebApi/issues/1227
    /// </summary>
    public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
    {
        actionExecutedContext.HttpContext.Response.StatusCode = 200;
        base.OnActionExecuted(actionExecutedContext);
    }

    public override void ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)
    {
        try
        {
            if (queryOptions.SelectExpand is not null)
            {
                List<string> roles = request.HttpContext.User.GetRoles();
                queryOptions.SelectExpand.Validator = new ODataExpandValidator(roles);
            }

            base.ValidateQuery(request, queryOptions);
        }
        catch (Exception e)
        {
            throw new ODataQueryException(e.Message);
        }
    }
}
```

**Comment by vozeldr** [comment]
@nathanvj I'm sorry, but I'm not working at that company anymore and don't remember what the fix was. I think I was able to get it mostly working with a lot of fiddling.
