### ISSUE TITLE
AspNetCoreWebApp Blueprint Does Handle Binary Media Types

### ISSUE THREAD

**Issue by csantos** [aws/aws-lambda-dotnet#754]
## Description
The SAM template in serverless.template does not set the binaryMediaTypes configuration to */* so that binary files (e.g. images, pdf) could be returned to the browser with the correct media type. 

## Reproduction Steps
* Create a new project using the AspNetCoreWebApp blueprint 
* Include an image in the MVC project
* Deploy the Lambda function, and API Gateway using the blueprint's SAM template
* Request the image using the API Gateway's URL using the browser, taking note of the media type returned. The image will not be rendered correctly.

### Environment
* Build Version: Amazon Lambda Tools for .NET Core applications (3.3.0)
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform: .NET Core

## Resolution
- [X ] :wave: I can/would-like-to implement a fix for this problem myself

Add the definition of the API definition so that the BinaryMediaTypes property can be specified.

"AspNetCoreApi": {
  "Type": "AWS::Serverless::Api",
  "Properties": {
      "StageName": "Prod",
      "BinaryMediaTypes": [ "*~1*" ]
  }
}

---

This is a :bug: bug-report

**Comment by normj** [comment]
The PR has been merged and released.
