### ISSUE TITLE
Not able to locate the corresponding sources for Amazon Lamda Core and other packages from Nuget library

### ISSUE THREAD

**Issue by rahulmohang** [aws/aws-lambda-dotnet#759]
Hi all,

We were trying to find corresponding source code for a few libraries like the following:

{
    "LibraryName": "Amazon.Lambda.APIGatewayEvents",
    "LibraryVersion": "1.2.0"
  },
  {
    "LibraryName": "Amazon.Lambda.AspNetCoreServer",
    "LibraryVersion": "3.0.0"
  },
  {
    "LibraryName": "Amazon.Lambda.Core",
    "LibraryVersion": "1.1.0"
  },
  {
    "LibraryName": "Amazon.Lambda.DynamoDBEvents",
    "LibraryVersion": "1.1.0"
  }

We got the binaries from  https://www.nuget.org/packages/Amazon.Lambda.Core. However, we cannot locate the source code of exact versions from github. 

We are not sure of the versions of the components mentioned at https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src.

Can you please help us locate the corresponding source code for the packages?

Regards,
Rahul
 

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @rahulmohang,

Good morning.

The exact source code for the specified versions could be figured out by examining the history of the corresponding `.csproj` file and tracking the last commit which had the specified version. For instance, commit https://github.com/aws/aws-lambda-dotnet/commit/c5cdebd74a4ffc73bf0165842ba05bc4947494a5#diff-501b305679d3cafdc0d7089342d6c63b36e7062f2813a892a80e6abacfcdc224 is the last one to have version 1.2.0 for Amazon.Lambda.APIGatewayEvents. Then you could use GIT commands to get the specified commit from the repository. Normally any version bump would have commit message like `Version bump Amazon.Lambda.APIGatewayEvents to 1.3.0` (for example).

Hope above information helps and let me know if we could close this issue.

Thanks,
Ashish

**Comment by rahulmohang** [comment]
Hi Ashish, 

Good morning.

I will inform my colleagues. I will come back to you.

**Comment by rahulmohang** [comment]
Hi Ashish, 

Please close the issue. 

Regards,
Rahul
