### ISSUE TITLE
Can AWS lambda accept multipart file from Spring

### ISSUE THREAD

**Issue by ArtjomProzorov** [aws/aws-lambda-dotnet#760]
Hey guys i am totally stuck, which is why i am sending a request here.

I have set content types in amazon binary media input field also in mapping template inout field and even tried through IntelliJ AWS Toolkit, however i still get the same error that Multipartfile cannot be processed.

```
"errorMessage": "An error occurred during JSON parsing",
        "errorType": "java.lang.RuntimeException",
        "stackTrace": [],
        "cause": {
            "errorMessage": "com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.web.multipart.MultipartFile` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information\n at [Source: (ByteArrayInputStream); line: 1, column: 1]",
            "errorType": "java.io.UncheckedIOException",
            "stackTrace": [
                "com.amazonaws.services.lambda.runtime.serialization.factories.JacksonFactory$InternalSerializer.fromJson(JacksonFactory.java:184)"
            ],
            "cause": {
                "errorMessage": "Cannot construct instance of `org.springframework.web.multipart.MultipartFile`

This is my lambda

    ```
@Component
    public class Hello implements Function<MultipartFile, String> {
    
        private AmazonClient amazonClient;
    
        @Override
        public String apply(MultipartFile multipartFile) {
            return amazonClient.uploadFile(multipartFile);
    
        }

AWS toolkit Embedded 

Invoking Lambda function: mylambda1
Error invoking Lambda: Could not parse request body into json: Could not parse payload into json: Unexpected character ('%' (code 37)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (byte[])"%PDF-1.3
%����

**Comment by ashishdhingra** [comment]
Hi @ArtjomProzorov,

Good morning.

Please confirm of you are using AWS .NET SDK or AWS Java SDK. If using Java SDK, then this issue needs to be transferred to  https://github.com/aws/aws-sdk-java.

Thanks,
Ashish
