### ISSUE TITLE
Failed to create CloudFormation change set: Received malformed response

### ISSUE THREAD

**Issue by dalton5** [aws/aws-lambda-dotnet#761]
Hi,

When I publish my aws lambda function I have a final error with this:

Uploading to S3. (Bucket: wtbucketlambda Key: WT-serverless-xxxxxx.template)
... Progress: 100%
Found existing stack: True
CloudFormation change set created
... Waiting for change set to be reviewed
Failed to create CloudFormation change set: Received malformed response from transform AWS::Serverless-2016-10-31
Failed to publish AWS Serverless application

Do you know how can I fix it?

It's a big issue because I can't publish my lambda function

Thanks,

My serverless template:

`{
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Transform" : "AWS::Serverless-2016-10-31",
  "Description" : "Starting template for an AWS Serverless Application.",
  "Resources" : {
    "DefaultFunction" : {
      "Type" : "AWS::Serverless::Function",
      "Properties": {
       "Handler": "not_required_for_custom_runtime",
				"Runtime": "provided",
        "CodeUri": "",
        "Description": "Default function",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [ "AWSLambdaFullAccess", "AmazonSSMReadOnlyAccess",
    "AWSLambdaVPCAccessExecutionRole" ],
        "Events": {
          "ProxyResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/{proxy+}",
              "Method": "ANY"
            }
          },
            "APIWarmingSchedule": {
                        "Type": "Schedule",
                        "Properties": {
                            "Schedule": "rate(5 minutes)",
                            "Input": "{ \"Resource\": \"WarmingLambda\", \"Body\": \"5\" }"
                        }
        }
      }
    }
    }
  },
  "Outputs" : {
    "ApiURL" : {
        "Description" : "API endpoint URL for Prod environment",
        "Value" : { "Fn::Sub" : "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/" }
    }
  
  }
}`

My aws lambda tools default json file

{
    "region" : "us-east-1",
    "profile" : "wetip",
    "s3-bucket" : "wtbucketlambda",
    "template"  : "serverless.template",
    "stack-name" : "WT",
    "configuration" : "Release",
    "framework"     : "netcoreapp2.2",
    "msbuild-parameters" : "--self-contained true"
}

**Comment by chgong** [comment]
I have the same issue.

My template:
{
   "AWSTemplateFormatVersion":"2010-09-09",
   "Transform":"AWS::Serverless-2016-10-31",
   "Description":"An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.",
   "Parameters":{
      "ShouldCreateBucket":{
         "Type":"String",
         "AllowedValues":[
            "true",
            "false"
         ],
         "Description":"If true then the S3 bucket that will be proxied will be created with the CloudFormation stack."
      },
      "BucketName":{
         "Type":"String",
         "Description":"Name of S3 bucket that will be proxied. If left blank a name will be generated.",
         "MinLength":"0"
      }
   },
   "Conditions":{
      "CreateS3Bucket":{
         "Fn::Equals":[
            {
               "Ref":"ShouldCreateBucket"
            },
            "true"
         ]
      },
      "BucketNameGenerated":{
         "Fn::Equals":[
            {
               "Ref":"BucketName"
            },
            ""
         ]
      }
   },
   "Resources":{
      "AspNetCoreFunction":{
         "Type":"AWS::Serverless::Function",
         "Properties":{
            "Handler":"xxx::xxx.LambdaEntryPoint::FunctionHandlerAsync",
            "Runtime":"dotnetcore3.1",
            "CodeUri":"s3://xxx/xxx/AspNetCoreFunction-CodeUri-637343401555849743-637343401710605189.zip",
            "MemorySize":256,
            "Timeout":30,
            "Role":null,
            "Policies":[
               "AWSLambdaFullAccess"
            ],
            "Environment":{
               "Variables":{
                  "AppS3Bucket":{
                     "Fn::If":[
                        "CreateS3Bucket",
                        {
                           "Ref":"Bucket"
                        },
                        {
                           "Ref":"BucketName"
                        }
                     ]
                  }
               }
            },
            "Events":{
               "ProxyResource":{
                  "Type":"Api",
                  "Properties":{
                     "Path":"/{proxy+}",
                     "Method":"ANY"
                  }
               },
               "RootResource":{
                  "Type":"Api",
                  "Properties":{
                     "Path":"/",
                     "Method":"ANY"
                  }
               }
            }
         }
      },
      "Bucket":{
         "Type":"AWS::S3::Bucket",
         "Condition":"CreateS3Bucket",
         "Properties":{
            "BucketName":{
               "Fn::If":[
                  "BucketNameGenerated",
                  {
                     "Ref":"AWS::NoValue"
                  },
                  {
                     "Ref":"BucketName"
                  }
               ]
            }
         }
      }
   },
   "Outputs":{
      "ApiURL":{
         "Description":"API endpoint URL for Prod environment",
         "Value":{
            "Fn::Sub":"https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
         }
      },
      "S3ProxyBucket":{
         "Value":{
            "Fn::If":[
               "CreateS3Bucket",
               {
                  "Ref":"Bucket"
               },
               {
                  "Ref":"BucketName"
               }
            ]
         }
      }
   }
}

**Comment by ckalan** [comment]
Having the same issue since last a few hours. It was working yesterday with the same template

**Comment by matthewdenobrega** [comment]
Same for me for a template that is unchanged and was working previously, so this looks like a regression.

**Comment by NithuPMTR** [comment]
I'm facing the same issue too. However, the aws health check dashboard does not show any indicators for service disruptions in us-east-1. Is everyone seeing this issue in us-east-1?

An older thread of similar issue which was due to aws service being down. https://github.com/aws/serverless-application-model/issues/793

**Comment by NithuPMTR** [comment]
This seems to be fixed now !

**Comment by ashishdhingra** [comment]
Hi @dalton5,

Good morning.

Per comment from @NithuPMTR, please verify if this works now for you and confirm if this issue could be closed.

Thanks,
Ashish

**Comment by chgong** [comment]
It works for me now.

**Comment by dalton5** [comment]
Yes it works. You can close. thanks

**Comment by orr-levinger** [comment]
same issue again..

**Comment by piiertho** [comment]
> same issue again..

I confirm, same issue.

**Comment by Laberbear** [comment]
Can confirm as well

**Comment by MatiasSasRise** [comment]
Can confirm as well, same issue

**Comment by agustinezequielgomez-rise** [comment]
Same issue here

**Comment by rizidoro** [comment]
Same issue here

**Comment by nxp9** [comment]
Received malformed response from transform AWS::Serverless-2016-10-31

Deploying to us-east-1

**Comment by itshari** [comment]
Seeing the same issue.

**Comment by Unisay** [comment]
Same here: `us-east-1`

**Comment by rogeriozambon** [comment]
Same issue here trying to deploy in `us-east`

**Comment by thoreg** [comment]
same here :(

**Comment by ItayGoren** [comment]
same here :( us-east-1 as well

**Comment by titiloxx** [comment]
same here :( us-east-1 as well

**Comment by gabrielnarruda** [comment]
Same here, in us-east-1 as well

**Comment by SharmaPawan98** [comment]
Is this issue only appearing in us-east-1 only or in other regions as well ?

**Comment by sab3d** [comment]
same here, us-east-1

**Comment by thoreg** [comment]
@ashishdhingra ^^^

**Comment by SMisra92** [comment]
Same here facing the issue in us-east-1

**Comment by yueshi-w** [comment]
same here, us-east-1

**Comment by sspaniel** [comment]
also experiencing this issue in us-east-1
working in us-east-2 and us-west-2

**Comment by rogeriozambon** [comment]
> Is this issue only appearing in us-east-1 only or in other regions as well ?

I've deployed in `sa-east` and it worked as well

**Comment by ashishdhingra** [comment]
Hi All,

The issue is tracked here https://github.com/aws/aws-lambda-dotnet/issues/765. Looks like there is a service outage for us-east-1 region. Service teams are working on it and the issue should be resolved soon.

Thanks,
Ashish

**Comment by slitsevych** [comment]
facing the same issue when attempting to update/create SAM stack in N.Virginia. 
I wish I found this thread earlier as I've already deleted stack thinking that the problem would be solved by recreating it from scratch(

**Comment by mochi-co** [comment]
Same here, us-east-1

**Comment by sherpaBen** [comment]
same here, us-east-1

**Comment by sonal-bansal** [comment]
same here, us-east-1

**Comment by danludwig** [comment]
yeah me too, us-east-1.

**Comment by slitsevych** [comment]
us-east-1 region is experiencing lots of outages. we can monitor [AWS service health dashboard](https://status.aws.amazon.com/) to check current status of outages/operational issues. 

As for issue which seems to be the one that is actual for our issues here is **Kinesis operational issue:**

> 8:05 AM PST: Kinesis is experiencing increased API errors in the US-EAST-1 Region. This is also causing issues with ACM, Amplify Console, API Gateway, AppStream2, AppSync, Athena, Cloudformation, Cloudtrail, CloudWatch, Cognito, Connect, DynamoDB, EventBridge, IoT Services, Lambda, LEX, Managed Blockchain, Resource Groups, SageMaker, Support Console, and Workspaces. This issue has also affected our ability to post updates to the Service Health Dashboard.

**Comment by Breno709** [comment]
same here, us-east-1

**Comment by SanjayMevada** [comment]
Has same issue for last 2 hours in us-east-1. 

Error: Failed to create managed resources: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state

Tried in us-east-2 and it worked.

**Comment by karadikid** [comment]
Same issue US-EAST-1 Trying 2.

**Comment by karadikid** [comment]
Successful US-EAST-2.  Hallelujah!

**Comment by FregosoRd** [comment]
Please let us know when the service is restored

**Comment by karadikid** [comment]
Fixed!

Thanks!

**Comment by darwin-cjessen** [comment]
This works for me in US-EAST-1 but I get the error mentioned above in EU-CENTRAL-1
