### ISSUE TITLE
What is supposed to be used for the factory?

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-lambda-dotnet#762]
The Amazon.Lambda.Logging.AspNetCore example in the root readme reads

` var loggerfactory = new TestLoggerFactory().AddLambdaLogger(loggerOptions);`

But, I am guessing we're not supposed to use TestLoggerFactory?

What LoggerFactory should we use in order to read all settings from appsettings.json?  Microsoft.Extensions.Logging.LoggerFactory?

**Comment by ashishdhingra** [comment]
Readme at https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore

**Comment by ashishdhingra** [comment]
Hi @hounddog22030,

Good morning.

Please confirm if you tried using the following code instead:
```C#
public void Configure(ILoggerFactory loggerFactory)
{
    var configuration = new ConfigurationBuilder()
        .AddJsonFile(APPSETTINGS_PATH)
        .Build();

    var loggerOptions = new LambdaLoggerOptions(configuration);
    
    // Configure Lambda logging
    loggerFactory
        .AddLambdaLogger(loggerOptions);
}
``` 

I think the line `var loggerfactory = new TestLoggerFactory().AddLambdaLogger(loggerOptions);` is redundant. Kindly let me know if above code works for you. In that case, the [Readme](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore) needs to be updated.

Thanks,
Ashish

**Comment by hounddog22030** [comment]
I don't really know how to get ahold of the ILoggerFactory?  This is all in a Lambda function (not Lambda ASP.NET Core).

How would I get an ILoggerFactory?

I ended up using this:

`        private static void SetupLogging(ILoggingBuilder loggingBuilder)
        {
            var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                .Build();

            var loggerOptions = new LambdaLoggerOptions(configuration);

            loggingBuilder.AddLambdaLogger(loggerOptions);
        }
`

**Comment by ashishdhingra** [comment]
Hi @hounddog22030,

Please refer Microsoft's documentation [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1). The [ILoggerFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#create-a-custom-logger) class should be injected by ASP.NET runtime automatically. 

For non-host console applications, refer [Logging providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#logging-providers-1) section, it creates a new logger factory using `LoggerFactory.Create()`.

Hope this helps and let me know if the proposed code worked for you.

Thanks,
Ashish
