### ISSUE TITLE
Custom runtimes need improved logging support

### ISSUE THREAD

**Issue by szilvaa** [aws/aws-lambda-dotnet#763]
I'm using .net5 as a custom runtime. I get separate log messages as described in https://github.com/aws/aws-lambda-dotnet/issues/613.

The same code running on standard runtime does not exhibit this behavior.

After some digging through the code. I found that loggers added with [ILoggerFactoryExtensions.AddLambdaLogger](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore/ILoggerFactoryExtensions.cs#L19) ultimately use [LambdaLogger.Log](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.Core/LambdaLogger.cs#L28). This function uses Console.WriteLine _via a delegate_. The delegate is private but interestingly there's a [test](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/test/Amazon.Lambda.Logging.AspNetCore.Tests/LoggingTests.cs#L545) to ensure that it can be replaced!
The presence of the indirection and the test to redirect it makes me believe that the standard runtime redirects and replaces `\n` with `\r` before using `Console.WriteLine`.

## Describe the Feature
I want loggers added with AddLambdaLogger to replace `\n` with `\r` even when a custom runtime is used.

### Is your Feature Request related to a problem?
https://github.com/aws/aws-lambda-dotnet/issues/613

## Proposed Solution
Either implement the `\n` to `\r` substitution in the LambdaLogger class directly or use the redirection mechanism to this conditionally when RuntimeSupport is used.

### Describe alternatives you've considered
I can use reflection to take advantage of this redirection but then everybody has to do this. 

## Additional Context
I'm trying to get the right logs (without extra linebreaks) with custom runtime.

### Environment
This isn't environment specific.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by gregtayl** [comment]
Is there a workaround for this? We're running into the same problem, using .NET 5 lambdas.
