### ISSUE TITLE
Amazon.Lambda.RuntimeSupport.LambdaConsoleLogger should go through the LambdaLogger

### ISSUE THREAD

**Issue by szilvaa** [aws/aws-lambda-dotnet#764]
When using a custom runtime, logging is troublesome due to the presence of `\n` characters that are normally replaced by `\r` when using a standard runtime.
This has been discussed in #613 and #763. Further testing reveals that `Amazon.Lambda.RuntimeSupport.LambdaConsoleLogger` directly writes to the Console without going though `Amazon.Lambda.Core.LambdaLogger`. So even if #763 is fixed, code that calls `context.Logger.LogLine` directly will experience difference in behavior between custom vs. standard runtime.

## Describe the Feature
I want messaged logged via `context.Logger.LogLine` to be "sanitized" (`\n` replaced with `\r`).

### Is your Feature Request related to a problem?
#613

## Proposed Solution
The code should replace `\n` with `\r` directly or we should fix #763 and make sure that `Amazon.Lambda.RuntimeSupport.LambdaConsoleLogger`  calls `Amazon.Lambda.Core.LambdaLogger`.

### Describe alternatives you've considered
Manually replace `\n` with `\r` at callsites. This is tedious.

## Additional Context
I'd like to be able to use .net5 which means I have to use custom runtime and this logging trouble is causing extra work.

### Environment
I'm trying to get the right logs (without extra linebreaks) with custom runtime.

* [ x ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by gregtayl** [comment]
Is there a workaround for this? We're running into the same problem, using .NET 5 lambdas.
