### ISSUE TITLE
Object reference not set to an instance of an object API gateway event .NET

### ISSUE THREAD

**Issue by IbrahimHabibeh** [aws/aws-lambda-dotnet#771]
Hi, I was recently trying to pass in some JSON to my lambda function using the .NET sdk for AWS. I just finished programming it and testing it out using a mock lambda tool. I get no errors whatsoever on there using the mock lambda tool. Now after uploading my code to AWS lambda and trying to trigger it via API Gateway. Whenever I try this is throws a Object reference not set to an instance of an object error (NullException). Now I've done some testing like trying to analyze what was being returned. The gatewayEvent.Body property is not null and I was successfully able to confirm that, yet whenever I try to access anything it throws that error. Below I will show my logs(attached as file) and some of my code. 

The error is thrown on this line:
            dynamic data = JObject.Parse(gatewayEvent.Body);

```C#
public string FunctionHandler(APIGatewayHttpApiV2ProxyRequest gatewayEvent, ILambdaContext context)
        {

            dynamic data = JObject.Parse(gatewayEvent.Body);
            DynamoDBEvent dynamoEvent = new DynamoDBEvent
            {
                Records = new List<DynamoDBEvent.DynamodbStreamRecord>() { new DynamoDBEvent.DynamodbStreamRecord() }
            };
            dynamoEvent.Records[0].EventSourceArn = "arn:aws:dynamodb:us-west-2:264105872605:table/Reviews";
            dynamoEvent.Records[0].EventSource = "aws:dynamodb";
            dynamoEvent.Records[0].AwsRegion = data.region;
            dynamoEvent.Records[0].EventName = "INSERT";

            dynamoEvent.Records[0].Dynamodb = new StreamRecord
            {
                Keys = new Dictionary<string, AttributeValue>()
                {
                    ["eventIdentifier"] = new AttributeValue { S = data.eventIdentifier },
                    ["id"] = new AttributeValue { S = data.id },
                    ["product-name"] = new AttributeValue { S = data.productName },
                    ["review"] = new AttributeValue { S = data.review },
                    ["name"] = new AttributeValue { S = data.name },
                    ["account-id"] = new AttributeValue { S = data.accountID },
                    ["rating"] = new AttributeValue { N = data.rating }
                }
            };
            foreach (var record in dynamoEvent.Records)
            {
                string tableName = record.Dynamodb.Keys["product-name"].S.Replace(" ", String.Empty);

                string json;
                
                return record.Dynamodb.Keys["eventIdentifier"].S switch
                {
                    "5168" => json = PutItemReviewAsync(ref tableName, new Dictionary<string, AttributeValue> { { "account-id", record.Dynamodb.Keys["account-id"] }, { "id", record.Dynamodb.Keys["id"] }, { "name", record.Dynamodb.Keys["name"] }, { "product-name", record.Dynamodb.Keys["product-name"] }, { "rating", record.Dynamodb.Keys["rating"] }, { "review", record.Dynamodb.Keys["review"] } }),
                    "4319" => DeleteReviewAsync(ref tableName,
record.Dynamodb.Keys["account-id"].S),
                    _ => throw new NotImplementedException(),
                };
            }

            return "{\"statusCode\": 400}";
        }
```
sorry if this code looks messy. Im just doing this for testing purposes right now.

**Comment by ashishdhingra** [comment]
Hi @IbrahimHabibeh,

Good morning.

As you mentioned, you are getting error on the line:
```C#
dynamic data = JObject.Parse(gatewayEvent.Body);
```

So looks like `gatewayEvent.Body` is `null`. `JObject.Parse` is a method from the Newtonsoft JSON library. Please share the following in order to troubleshoot the issue:

- How did you found out in live environment that `gatewayEvent.Body` is not null?

- Could you please share the complete code solution?

- Steps you used to integrate with API Gateway.

- How are you invoking the function exposed via API Gateway?

- CloudWatch Logs.

Kindly note that the URL of the application is of the form https://<random-value>.execute-api.<region>.amazonaws.com/Prod (notice the capital `P` in Prod).

Following articles might provide some guidance:
- [AWS Serverless API using .NET Core 2.0](https://www.codeproject.com/Articles/1200959/AWS-Serverless-API-using-NET-Core)
- [Developing .NET Core AWS Lambda functions](https://aws.amazon.com/blogs/compute/developing-net-core-aws-lambda-functions/)

Thanks,
Ashish

**Comment by IbrahimHabibeh** [comment]
How did you found out in live environment that gatewayEvent.Body is not null?

I found this out by just putting `return gatewayEvent.Body` on the first line of the function. I will attach a log with the output of that.

Could you please share the complete code solution?

Attached to this comment

Steps you used to integrate with API Gateway & How are you invoking the function exposed via API Gateway?

1. Create the API and set it as a trigger for my lambda function
2. enable CORS and lambda proxy 
3. Created a resource called id, which uses a product id as an extension to the path
4. Created a post method to trigger the lambda function
5. Integration type set to lambda proxy
6. Selected the test tab to send through the following: {id}: ihjgij, Headers set to Content-Type: application/json (API gateway sends through other headers by default, which can be found in the log I sent last time), and request body set to this:

{
    "id": "ihjgij",
    "product-name": "Color Sensor",
    "eventIdentifier": "5168",
    "review": "test",
    "accountID": "f74hrfwf",
    "rating": 5,
    "region": "us-west-2",
    "name": "Ibrahim Habibeh"
}

or a one liner
{\"id\": \"u9ttm90\",\"productName\": \"Color Sensor\",\"rating\": 5,\"name\": \"Ibrahim Habibeh\",\"accountID\": \"ng84g-tgg894g\",\"review\": \"test\", \"eventIdentifier\": \"5168\", \"region\": \"us-west-2\"}

CloudWatch Logs:


START RequestId: 191452bd-02ec-4015-840e-538ee9e6f4a1 Version: $LATEST
--
Object reference not set to an instance of an object.: NullReferenceException   at ReviewsDynamoDB.Function.FunctionHandler(APIGatewayHttpApiV2ProxyRequest gatewayEvent, ILambdaContext context) in C:\src\ReviewsDynamoDB\ReviewsDynamoDB\Function.cs:line 20   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
END RequestId: 191452bd-02ec-4015-840e-538ee9e6f4a1
REPORT RequestId: 191452bd-02ec-4015-840e-538ee9e6f4a1	Duration: 2532.96 ms	Billed Duration: 2533 ms	Memory Size: 192 MB	Max Memory Used: 77 MB	Init Duration: 164.62 ms

----------
Cloudwatch with 1st line return statement:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                                 message                                                                                  |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| START RequestId: 9e4880c6-dd60-4847-9002-45c62693eb26 Version: $LATEST                                                                                                   |
| END RequestId: 9e4880c6-dd60-4847-9002-45c62693eb26                                                                                                                      |
| REPORT RequestId: 9e4880c6-dd60-4847-9002-45c62693eb26 Duration: 347.09 ms Billed Duration: 348 ms Memory Size: 192 MB Max Memory Used: 64 MB Init Duration: 172.78 ms   |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[ReviewsDynamoDB.zip](https://github.com/aws/aws-lambda-dotnet/files/5655428/ReviewsDynamoDB.zip)

**Comment by ashishdhingra** [comment]
Hi @IbrahimHabibeh,

While deploying Lambda, please Set environment variable LAMBDA_NET_SERIALIZER_DEBUG to true. This will dump the JSON of what input is being sent to Lambda function in CloudWatch Logs. Thereafter, kindly share the CloudWatch Logs to troubleshoot the issue.

Thanks,
Ashish

**Comment by IbrahimHabibeh** [comment]
Ok, I was just looking at my code and my json and I saw that product-name was actually suppose to be productName. It must've been throwing the error when it was getting parsed, which seems rather odd for it to be thrown there since it wasnt being accessed. This ended up just being a common human error on my part and I would like to thank you for the time you put in to try and help me resolve my issue. I will be closing the issue now and if something happens to come up I will reopen it.
