### ISSUE TITLE
Lambda Insights reports Custom Runtime for .NET Core 3.1 Runtime

### ISSUE THREAD

**Issue by ryancormack** [aws/aws-lambda-dotnet#772]
## Description
Lambda Insights provides additional information about a function's invocation. Part of this includes the Runtime the function was invoked on. Snippet:

``` js
{"total_network": 84,
    "version": "$LATEST",
    "function_name": "customruntimebug-dev-hello",
    "runtime": "Custom",
    "used_memory_avg": 60,
    "shutdown_reason": "spindown"}
```

It would be expected that the `runtime` property would be `dotnetcore3.1` as per the [supported runtimes in the docs](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-insights.html#monitoring-insights-runtimes).

## Reproduction Steps
Create a new Lambda using the .NET Core 3.1 runtime. This could be done with the Serverless Framework if Serverless is installed globally as an npm module:
`sls create --template aws-csharp --path customRuntimeBug`
`cd customRuntimeBug`

Ensure the correct Lambda Layer is added for Enhanced Insights, `arn:aws:lambda:${self:provider.region}:580247275435:layer:LambdaInsightsExtension:2` and the function has access to write and create logs for the `/aws/lambda-insights` log group

`sls deploy` to deploy the lambda
`sls invoke -f hello` to invoke the lambda.

Then check the Logs created at `/aws/lambda-insights`.

A full code sample containing reproduction steps can be found here [https://github.com/ryancormack/aws-lambda-net-insights-runtime](https://github.com/ryancormack/aws-lambda-net-insights-runtime)

### Logs

<details><summary>An example Insights log output created from the above</summary>

```js
{
    "cpu_system_time": 270,
    "agent_memory_avg": 8516949,
    "tmp_used": 538333184,
    "function_name": "customruntimebug-dev-hello",
    "fd_max": 118209,
    "cpu_total_time": 560,
    "memory_utilization": 5,
    "shutdown_reason": "spindown",
    "event_type": "performance",
    "total_network": 84,
    "threads_max": 9,
    "rx_bytes": 42,
    "version": "$LATEST",
    "cold_start": true,
    "used_memory_max": 60,
    "tmp_max": 551346176,
    "agent_memory_max": 8994816,
    "cpu_user_time": 290,
    "used_memory_samples": 18,
    "request_id": "e4363ee0-090a-4af0-b231-90a4ab9a6d16",
    "fd_use": 416,
    "runtime": "Custom",
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "LambdaInsights",
                "Dimensions": [
                    [
                        "function_name"
                    ],
                    [
                        "function_name",
                        "version"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "cpu_total_time",
                        "Unit": "Milliseconds"
                    },
                    {
                        "Name": "tx_bytes",
                        "Unit": "Bytes"
                    },
                    {
                        "Name": "rx_bytes",
                        "Unit": "Bytes"
                    },
                    {
                        "Name": "total_network",
                        "Unit": "Bytes"
                    },
                    {
                        "Name": "used_memory_max",
                        "Unit": "Megabytes"
                    },
                    {
                        "Name": "total_memory",
                        "Unit": "Megabytes"
                    },
                    {
                        "Name": "memory_utilization",
                        "Unit": "Percent"
                    }
                ]
            }
        ],
        "Timestamp": 1607288421276,
        "LambdaInsights": {
            "ShareTelemetry": true
        }
    },
    "shutdown": 1,
    "tx_bytes": 42,
    "total_memory": 1024,
    "used_memory_avg": 60,
    "agent_version": "1.0.54.0",
    "trace_id": "1-5fcd44f0-2fed7e1b15b8dbde3e88c4d3"
}
```
</details>

### Environment

* Build Version: Built with .NET 3.1.402
* OS Info: Windows 10 build time, .NET Core 3.1 Lambda runtime
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
- [ ] :wave: I can just ignore this property

---

This is a :bug: bug-report

**Comment by ryancormack** [comment]
It seems that `runtime` reporting was removed and/or is no longer logged in Lambda Layer versions 11 and 12. I was experiencing this bug on Lambda Layer version 2, which was the preview version. It looks like it was removed before going to GA, so this is likely a feature rather than a .NET or Lambda Insights issue

**Comment by ashishdhingra** [comment]
Hi @ryancormack,

Good morning.

From the Logs shared above, looks like the runtime is logged as `Custom` which is same as what you used. Not sure if this is an issue. Is the runtime correctly logged `dotnetcore3.1` when using .NET Core 3.1 runtime (not your custom runtime)?

Thanks,
Ashish

**Comment by ryancormack** [comment]
Hi @ashishdhingra 👋 
I think that is actually the problem. I [am using](https://github.com/ryancormack/aws-lambda-net-insights-runtime/blob/main/customRuntimeBug/serverless.yml#L7) the `dotnetcore3.1` runtime in my sample project and the Lambda Insights were reporting this as `Custom`.

However, in my comment I mentioned that in later (the general availability versions, rather than the public preview version) the `runtime` property is not being reported by Lambda Insights at all, which makes me think that the property has just been fully removed from the Insights reporting?

**Comment by normj** [comment]
@ashishdhingra I asked @ryancormack to log this. I can take lead on this one.

**Comment by normj** [comment]
@ryancormack I was able to reproduce what you are seeing. Interesting enough a Node.js Lambda function doesn't have the runtime field. I'm reaching out to the service team that owns this to get a better understanding what is going on.

**Comment by jaredcnance** [comment]
@ryancormack that’s correct. The runtime field was removed prior to the GA release version. Lambda insights runs as a Lambda Insights extension and is unaware of which runtime is being used.

**Comment by ryancormack** [comment]
@jaredcnance Thanks for the reply. Makes sense 👍
