### ISSUE TITLE
Could not load file or assembly. An operation is not legal in the current state.

### ISSUE THREAD

**Issue by cosminPintea** [aws/aws-lambda-dotnet#780]
## Description
I have an AWS lambda -function in c# whitch fail when I am trying to run the function in debug mode using "Mock Lambda Test Tool". The function doesn't throw any error if I executed using invoke from my main program.
The actual error is:
 "Could not load file or assembly 'nunit.engine.core, Version=3.11.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'. An operation is not legal in the current state. (0x80131509)"

## Reproduction Steps

Install the AWS Lambda test tool package: https://aws.amazon.com/blogs/developer/debugging-net-core-aws-lambda-functions-using-the-aws-net-mock-lambda-test-tool/
Create an empty AWS Lambda project (.Net Core c#)
Add the nunit.engine.core  package as a dependency
Try to create a Nunit test engine  " using (ITestEngine engine = TestEngineActivator.CreateInstance()) {}"
Run the debugger
Send any request

trow this error:
 "Could not load file or assembly 'nunit.engine.core, Version=3.11.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'. An operation is not legal in the current state. (0x80131509)"

### Environment

* Build Version: 
* OS Info:  Windows 10 
* Build Environment:  Visual Studio 2019
* Targeted .NET Platform:  .Net Core 3.1

## Resolution
There is this comment on another issue:
https://github.com/aws/aws-lambda-dotnet/issues/419#issuecomment-494655461 

I think this could be the cause. Any idea how to fix this? 
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible using Visual Studio when using Empty Lambda Function AWS template, adding the above code, running using the Lambda Test Tool and sending the sample request.
**.csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>

    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    <PackageReference Include="NUnit.Engine" Version="3.11.1" />
  </ItemGroup>
</Project>
```

**Function.cs**
```C#
using Amazon.Lambda.Core;
using NUnit.Engine;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace AWSLambdaNUnitDependency_Issue780
{
    public class Function
    {
        
        /// <summary>
        /// A simple function that takes a string and does a ToUpper
        /// </summary>
        /// <param name="input"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        public string FunctionHandler(string input, ILambdaContext context)
        {
            using (ITestEngine engine = TestEngineActivator.CreateInstance())
            {
                return input?.ToUpper();
            }
        }
    }
}
```

**Lambda Test Tool version:** AWS .NET Core 3.1 Mock Lambda Test Tool (0.11.0)

**Comment by ashishdhingra** [comment]
Works fine when deployed to AWS Lambda environment. Issue appears to be only with the Lambda Test Tool.

**Comment by JordanSkousen** [comment]
I am experiencing this issue as well when trying to debug with the Test Tool, but with the `Google.Apis.Auth` package.

`System.IO.FileLoadException: Could not load file or assembly 'Google.Apis.Auth, Version=1.49.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab'. An operation is not legal in the current state. (0x80131509)`

**Comment by ashishdhingra** [comment]
Hi @cosminPintea,

Could you please try using version `0.11.3` of Lambda Test Tool and see if this no longer an issues?

Thanks,
Ashish

**Comment by mwanchap** [comment]
I was receiving the same exception while using the Mock Lambda Test Tool with one particular lambda project - it worked fine when deployed, and all the other lambdas worked with the test tool except this one. I noticed that their `bin/Debug` directories all contained the dll referenced by the exception message, whereas for the troublesome project it was missing.
The solution turned out to be adding this property to the .csproj file (copied from the lambda project template):
```xml
<!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
```
