### ISSUE TITLE
Default project from visual studio 2019 template (Aws Serverless API Project With .NET 5) not getting deployed

### ISSUE THREAD

**Issue by akshayshah2050** [aws/aws-lambda-dotnet#784]
## Description
Default template project from AWS blueprints not getting deployed to AWS for .NET 5

## Reproduction Steps
1. Create A New ASP.NET Core Web API with AWS Serverless Application template targeting .NET 5 (Using VS 2019 template)
2. Using installed AWS toolkit from Visual Studio 2019 try to publish the solution to AWS Lambda 

### Logs
AWS::Lambda::Function | AspNetCoreFunction | 
Unable to determine service/operation name to be authorized (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: d96c7c99-2156-43cb-a8a6-c60f1df4d6be; Proxy: null)

### Environment
.NET 5
Visual Studio 2019 (16.8.3)

## Resolution
NA

## If I create the same project targeting .NET Core 3.1 then it works fine

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @akshayshah2050,

Good evening.

There are AWS blueprints available for AWS Serverless Application targeting .NET 5 - `.NET 5 (Container Image)` and `ASP.NET Core 5 (Container Image)`. Please confirm which one did you use? You also need to have Docker installed for deployment to AWS Lambda.

Thanks,
Ashish

**Comment by akshayshah2050** [comment]
I used ASP.NET Core 5 (Container Image) as the blueprint.
Also I have docker installed

**Comment by akshayshah2050** [comment]
@ashishdhingra any updates on this?

**Comment by ashishdhingra** [comment]
Hi @akshayshah2050,

Good morning.

My apologies for replying late. I have requested developer to have a look at it and we should have an update soon.

Thanks,
Ashish

**Comment by akshayshah2050** [comment]
Hi @ashishdhingra 
Any updates on this? Please let me know the ETA on this...

**Comment by normj** [comment]
What region are you attempting to deploy to?

**Comment by akshayshah2050** [comment]
@normj The region is Asia Pacific (Mumbai) ap-south-1

**Comment by normj** [comment]
Lambda's container support isn't in all regions yet and sadly ap-south-1 is one of the regions the support is not there which is what is triggering this confusing error message.

The announcement blog mentioned the supported regions "You can use container images to deploy your Lambda functions today in US East (N. Virginia), US East (Ohio), US West (Oregon), Asia Pacific (Tokyo), Asia Pacific (Singapore), Europe (Ireland), Europe (Frankfurt), South America (São Paulo). We are working to add support in more Regions soon." https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

Hopefully now that we are all back from the new years Lambda will get the support out in more regions soon.

**Comment by ashishdhingra** [comment]
Closing this issue based on inputs from Norm.
