### ISSUE TITLE
S3ProxyController constructor bad check for empty bucket name

### ISSUE THREAD

**Issue by AndybSe** [aws/aws-lambda-dotnet#79]
Hi

Sorry if this is vrong project to report error . 

Yeoman template aws-lambda-dotnet
ASP.NET Core Web API (AWS Serverless) 

**S3ProxyController**

has check: 
if(this.BucketName == null)

That will fail if run locally (dotnet run) since BucketName will be empty ("")

Suggested code change:
String.IsNullOrEmpty(this.BucketName)

Thanks!

Best regards
Andreas

**Comment by gokarnm** [comment]
Hi @AndybSe, this is the correct repository, thanks for reporting this! We'll fix it.

**Comment by normj** [comment]
New blueprints have been pushed with this fix
