### ISSUE TITLE
Pass custom parameter to AWS lambda function Handler in c#

### ISSUE THREAD

**Issue by Namrataijare** [aws/aws-lambda-dotnet#793]
Hi,
I am trying to pass custom object as a input parameter to function handler in c#. It is working fine locally. I have created the api gateway in aws lambda function. and trying to call that api through postman. I am passing custom object input parameter in body and returning the same object. but input is passing as null to the function handler.

public Rootobject FunctionHandler(EmailData input, ILambdaContext context)
{
var data = JsonConvert.SerializeObject(input);
Rootobject rootobject = new Rootobject()
{
isBase64Encoded = false,
statusCode = 200,
body = data
};
return rootobject;
}

public class EmailData
{
public string EmailAddress { get; set; }
public List<KeyValuePair<string, string>> files { get; set; }

}
 This is my code. Can anyone tell me what is the issue. 
Do I need to configure anything in api gateway to pass the custom object parameter?
Please help me.

**Comment by ashishdhingra** [comment]
Hi @Namrataijare,

Good afternoon.

Thanks for posting guidance question. Please confirm the following:

- Are you using `[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]` in your program?
- Share the API Gateway settings with screenshots (if possible)
- While deploying Lambda, please set environment variable `LAMBDA_NET_SERIALIZER_DEBUG` to `true`. This will dump the JSON of what input is being sent to Lambda function in CloudWatch Logs. Thereafter, kindly share the CloudWatch Logs to troubleshoot the issue.

Thanks,
Ashish

**Comment by Namrataijare** [comment]
Hi @ashishdhingra,

I got some alternative solution. Instead of directly passing class object as a input I am using APIGatewayHttpApiV2ProxyRequest object as a input parameter and passing my input in the body and then deserializing it with my class. 



 public APIGatewayProxyResponse FunctionHandler(APIGatewayHttpApiV2ProxyRequest input, ILambdaContext context)
        {
 EmailBody emailBody = new EmailBody();
            emailBody = JsonConvert.DeserializeObject<EmailBody>(input?.Body);
  var response = new APIGatewayProxyResponse
            {
                StatusCode = (int)HttpStatusCode.OK,
                Body = "Mail sent successfully!",
                Headers = new Dictionary<string,
               string> { { "Content-Type", "application/json" } }
            };

            return response;
}



 public class EmailBody
    {
        public string EmailAddress { get; set; }

        public FilesData[] Files { get; set; }
    }

    public class FilesData
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
    
    
   Let me know if this is the right approach. can I use  APIGatewayHttpApiV2ProxyRequest object parameter as input?

**Comment by Namrataijare** [comment]
I am setting Lambda Integration Proxy to true in api gateway.

**Comment by ashishdhingra** [comment]
Hi @Namrataijare,

Good morning.

Following articles could be helpful for your scenario:
- [Developing .NET Core AWS Lambda functions](https://aws.amazon.com/blogs/compute/developing-net-core-aws-lambda-functions/)
- [Creating a Serverless Application with .NET Core, AWS Lambda and AWS API Gateway](https://www.jerriepelser.com/blog/dotnet-core-aws-lambda-serverless-application/)
- [Learning Resources](https://github.com/aws/aws-lambda-dotnet/blob/master/Docs/Learning_Resources.md) in [aws-lambda-dotnet](https://github.com/aws/aws-lambda-dotnet) repository
- [Launch a C# .NET Core Lambda Function — Step by Step](https://medium.com/devtechblogs/launch-a-c-net-core-lambda-function-in-aws-step-by-step-5e4636516758) _(external website, use as reference only)_ 
- [Amazon.Lambda.APIGatewayEvents](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.APIGatewayEvents) in [aws-lambda-dotnet](https://github.com/aws/aws-lambda-dotnet) repository Readme.

Thanks,
Ashish

**Comment by Namrataijare** [comment]
Thanks @ashishdhingra 

I will look into it.

**Comment by ashishdhingra** [comment]
Closing this issue since the provided articles provide necessary guidance. Please feel free to open a new issue if further assistance is required.
