### ISSUE TITLE
Accessing policy object coming from Custom Authorizer output within a separate business logic Lambda

### ISSUE THREAD

**Issue by keyurpd** [aws/aws-lambda-dotnet#796]
We have a separate custom lambda authorizer that validates incoming OIDC tokens and outputs a policy object with allow/deny, principal-id etc. Now we have a separate .net core business logic function that needs to read this principal-id and other custom outputs that the upstream authorizer might have sent.
*Question*: Is there a documentation and/or a sample where we can find how to read incoming context within the business logic Lambda?

https://github.com/aws/aws-lambda-dotnet/blob/8d61a2f72f40b8d92af88bb479b184fae7ed2150/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L446

**Comment by ashishdhingra** [comment]
Hi @keyurpd,

Good afternoon.

Thanks for posting the question. I'm not sure if I get the clear understanding of the question, following articles might be helpful (even though they don't document .NET specific example):

- [Use AWS Lambda authorizers with a third-party identity provider to secure Amazon API Gateway REST APIs](https://aws.amazon.com/blogs/security/use-aws-lambda-authorizers-with-a-third-party-identity-provider-to-secure-amazon-api-gateway-rest-apis/)
- [https://aws.amazon.com/blogs/compute/introducing-custom-authorizers-in-amazon-api-gateway/](https://aws.amazon.com/blogs/compute/introducing-custom-authorizers-in-amazon-api-gateway/)

Also refer [Tutorial: Build and Test a Serverless Application with AWS Lambda ](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/lambda-build-test-severless-app.html). LambdaContext should be available when the API is called. If this is not what is required, would it be possible for you to share the code snippet of your Lambda function?

Thanks,
Ashish

**Comment by keyurpd** [comment]
> LambdaContext should be available

Question is, how to access that when the downstream lambda is a .net core api? Following picture can help understand.
![image](https://user-images.githubusercontent.com/18165518/103977884-36be7200-51a0-11eb-89d7-320c0d922bce.png)

**Comment by ashishdhingra** [comment]
Hi @keyurpd,

LambdaContext should be available via `this.HttpContext.Items["LambdaContext"]` (Refer the below screenshot).
<img width="645" alt="Screen Shot 2021-01-07 at 11 25 36 PM" src="https://user-images.githubusercontent.com/67916761/103986591-e44d6900-513f-11eb-900c-5adb26ed84a0.png">

Please test at your end and confirm if this issue could be closed.

Thanks,
Ashish

**Comment by keyurpd** [comment]
This is good, thank you @ashishdhingra. It can be closed.
Though I also hope there were some samples/documentation available at the official site, language specific.

**Comment by ashishdhingra** [comment]
@keyurpd Thanks for confirming. I will make a noted of identifying a place for documentation update. Closing this issue.
