### ISSUE TITLE
Are there plans to add support for a AWS Connect ContactFlowEvents

### ISSUE THREAD

**Issue by MarkRichardsNH** [aws/aws-lambda-dotnet#799]
## The Question
I need to write a lambda with .NET core that supports requests from Amazon Connect.
https://docs.aws.amazon.com/connect/latest/adminguide/connect-lambda-functions.html 

As I don't see this is the list of supported events I believe I'm going to have to manually define a class that will map to the JSON that amazon connect sends. 

Assuming that no-one is currently working on support for this, is there a best practice guide for adding support for JSON messages that are not part of the supported event types (aside from create an input type that matches!) 

Sample event below
```JSON
{
    "Details": {
        "ContactData": {
            "Attributes": {},
            "Channel": "VOICE",
            "ContactId": "4a573372-1f28-4e26-b97b-XXXXXXXXXXX",
            "CustomerEndpoint": {
                "Address": "+1234567890",
                "Type": "TELEPHONE_NUMBER"
            },
            "InitialContactId": "4a573372-1f28-4e26-b97b-XXXXXXXXXXX",
            "InitiationMethod": "INBOUND | OUTBOUND | TRANSFER | CALLBACK",
            "InstanceARN": "arn:aws:connect:aws-region:1234567890:instance/c8c0e68d-2200-4265-82c0-XXXXXXXXXX",
            "PreviousContactId": "4a573372-1f28-4e26-b97b-XXXXXXXXXXX",
            "Queue": {
               "ARN": "arn:aws:connect:eu-west-2:111111111111:instance/cccccccc-bbbb-dddd-eeee-ffffffffffff/queue/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
               "Name": "PasswordReset"
             },
            "SystemEndpoint": {
                "Address": "+1234567890",
                "Type": "TELEPHONE_NUMBER"
            }
        },
        "Parameters": {
            "sentAttributeKey": "sentAttributeValue"
        }
    },
    "Name": "ContactFlowEvent"
}
```

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @MarkRichardsNH,

Thanks for posting the guidance question.

Based on my discussion with the development team, I'm marking this issue as `feature-request`. While I'm not certain about the timeline at this stage, this would be worked upon as the issues are prioritized.

I'm not aware of any best practice guide, however, you could have a look at the existing events to see the pattern and try implementing the new event on the similar design. Also, feel free to contribute in the form of PR if you get everything working.

Thanks,
Ashish

**Comment by MarkRichardsNH** [comment]
@ashishdhingra thanks for the response. 

I already have something working, so I just need to validate across some use cases.

I'm not the Amazon Connect party in this transaction, I'm just providing a service to them, so as it stands it's just a mapping of the fields without much thought ! 

Hence I think It will need some testing before I share

**Comment by ashishdhingra** [comment]
New package [Amazon.Lambda.ConnectEvents 1.0.0](https://www.nuget.org/packages/Amazon.Lambda.ConnectEvents/1.0.0) released.
