### ISSUE TITLE
lambda dotnet limit on POST size?

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#80]
When posting a large file to my lambda dotnet API, I received back:

HTTP/1.1 413 Request Entity Too Large
X-Cache: Error from cloudfront

Normally, this would be something configured in IIS like so:

<standardEndpoints>
    <webHttpEndpoint>
        <standardEndpoint name="" 
                         helpEnabled="true" 
                         automaticFormatSelectionEnabled="true"                   
                         maxReceivedMessageSize="2147483647">
        </standardEndpoint>
    </webHttpEndpoint>
</standardEndpoints>

How would we configure this in lambda dotnet and what are the current limits?

Thanks,

Dave

**Comment by normj** [comment]
Lambda has a 6 meg limit on request size. If you are trying to upload something bigger then that you should upload to S3 first and have the Lambda function pull the object down from S3.

http://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by normj** [comment]
I believed this is answered. Feel free to reopen if you have more questions.

**Comment by Rogeriohsjr** [comment]
Hi, I have a question on top of that, if I build an application to upload to S3, how I can solve this issue? Should I use Elastic beanstalk to host my application or somehow I should take another approach to upload to S3?

Basically I was thinking something like Cloud -> My Application <-> S3

**Comment by andymac4182** [comment]
You can create a signed url and upload to S3 directly from the client. This will ensure that they can upload only the paths you specify and also will remove the requirement for you to wait around while the file uploads.
