### ISSUE TITLE
Dependency injection in Lambdas with .NET Core 3.1

### ISSUE THREAD

**Issue by yenhanshih** [aws/aws-lambda-dotnet#800]
## The Question
**Question 1** It is my understanding is that in .NET Core 3.1, using the generic `IHostBuilder` is supported when bootstrapping the code. Why is it that I need to override both `Init(IHostBuilder)` and `Init(IWebHostBuilder)`?
```
public class Function : APIGatewayProxyFunction
{
    protected override void Init(IHostBuilder hostBuilder)
    {
        hostBuilder.ConfigureServices(s =>
        {
            s.AddScoped<ISomeService, SomeService>();
        });
    }

    public async Task<APIGatewayProxyResponse> FunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
    {
         // Code
    }
}
```
This throws the follwing error at runtime indicating that I need to be using `IWebHostBuilder`.
```
An exception was thrown when the constructor for type 'MyFunction.Function' was invoked. Check inner exception for more details.: LambdaException
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
No application configured. Please specify an application via IWebHostBuilder.UseStartup, IWebHostBuilder.Configure, or specifying the startup assembly via StartupAssemblyKey in the web host configuration.: InvalidOperationException
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2.Start()
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor(StartupMode startupMode)
   at Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2..ctor()
   at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
   at Refyne.Serverless.GetProvider.Function..ctor()
```
So in order to get around that error, I was able to make it into the `FunctionHandler` by overriding the `Init(IWebHostBuilder)` as well with `Startup.cs` doing the same exact thing as `Init(IHostBuilder)`
```
public class Function : APIGatewayProxyFunction
{
    protected override void Init(IHostBuilder hostBuilder)
    {
        hostBuilder.ConfigureServices(s =>
        {
            s.AddScoped<ISomeService, SomeService>();
        });
    }
    
    protected override void Init(IWebHostBuilder builder)
    {
        builder.UseStartup<Startup>();
    }
    
    public async Task<APIGatewayProxyResponse> FunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
    {
         // Code
    }
}
```
Startup.cs
```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        s.AddScoped<ISomeService, SomeService>();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
    }
}
```
**Question 2** The main question being, how would I be able to inject `ISomeService` into my `FunctionHandler`?

### Environment

* Build Version: Amazon.Lambda.AspNetCoreServer 5.3.0
* OS Info: Windows 10
* Build Environment: VSCode + AWS ToolKit for debugging
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @yenhanshih,

Good morning.

Thanks for posting the guidance question. The link [Bootstrapping application (IWebHostBuilder vs IHostBuilder)](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md#bootstrapping-application-iwebhostbuilder-vs-ihostbuilder) explains about the bootstrapping process when using `Amazon.Lambda.AspNetCoreServer` package. The ideal place to configure dependencies would be the `ConfigureServices(IServiceCollection services)` method in `Startup.cs`. Please refer section **ASP.NET Core dependency injection** at [Configuring the AWS SDK for .NET with .NET Core](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html) for more information.

My understanding is that you are trying to use `Amazon.Lambda.AspNetCoreServer` package to develop Serverless WebAPI Using AWS Lambda. Hence you would be using controllers to expose your WebAPI and use DI to access services in that controller.

In case you are looking to use DI in simple Lambda functions, article [Add .NET Core DI and Config Goodness to AWS Lambda Functions](https://blog.tonysneed.com/2018/12/16/add-net-core-di-and-config-goodness-to-aws-lambda-functions/) might be helpful. (**NOTE:** The article should be used for reference purposes only. AWS support is not responsible for any production issues when using the code).

Thanks,
Ashish
