### ISSUE TITLE
Rename Amazon.Lambda.Logging.AspNetCore package

### ISSUE THREAD

**Issue by damianh** [aws/aws-lambda-dotnet#801]
This is a nit-picky one :)

The package `Amazon.Lambda.Logging.AspNetCore` doesn't actually depend on or indeed has anything to do with AspNetCore in any way.

![image](https://user-images.githubusercontent.com/57436/106325879-d3de6900-627b-11eb-82f0-578275548d3f.png)

**Comment by normj** [comment]
I agree adding `AspNetCore` was not the write suffix but not sure about changing the name of a 5 year old package. Since there isn't really a name for the modern Microsoft logging system what would you call the package?

**Comment by damianh** [comment]
Yeah the logging stuff started in aspnet core and was peeled out into `Microsoft.Extensions.Logging`. 

If you were to change it, I'd suggest `Amazon.Lambda.Extensions.Logging` or just simply `Amazon.Lambda.Logging`. 

The upcoming .NET 6 LTS release is probably the one reasonable time to make this sort of change.
