### ISSUE TITLE
Lambda Test Tool starting with paused state

### ISSUE THREAD

**Issue by rohit3d2003** [aws/aws-lambda-dotnet#804]
## Description
Created a brand new AWS Serverless project and started Mock test tool. It ran with a paused state

![image](https://user-images.githubusercontent.com/16943885/107123183-032f4000-6851-11eb-980d-15f70b3617ae.png)

## Reproduction Steps
1. Create AWS Serverless Application Project
2. Click Mock Lambda Test Tool

### Environment
* Build Version: 0.11.1
* OS Info: Windows 10 19042.746
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  .Net Core 3.1

**Comment by ashishdhingra** [comment]
Hi @rohit3d2003,

Good morning.

The error clearly states that the execution is paused on the debugger. This could also happen if there is exception in your code which also causes debugger to pause. Please check your Visual Studio state.

Thanks,
Ashish

**Comment by rohit3d2003** [comment]
@ashishdhingra - I created a brand new project with AWS Empty Serverless template and hence there isn't any custom code that's throwing an exception. Also, there isn't any breakpoint in code as well

<img width="802" alt="Screen Shot 2021-02-07 at 7 44 49 AM" src="https://user-images.githubusercontent.com/16943885/107151625-6637da00-6918-11eb-89a7-d169d48ef4dd.png">

**Comment by ashishdhingra** [comment]
Hi @rohit3d2003,

Could you please share the template used for Lambda serverless project - is it targeting .NET Core 3.1 or .NET 5 Container image?

Thanks,
Ashish

**Comment by rohit3d2003** [comment]
Hi @ashishdhingra - it is targeting .Net Core 3.1. To my surprise, all the previous AWS Serverless Applications that I had build targeting .Net Core 3.1 are running into same issue which makes me believe that some update have corrupted the installation.

Things I have already tried:

- Uninstall & Reinstall DotNetTest tools
- Updated VS to latest available version
- Updated Windows to latest version

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra - it is targeting .Net Core 3.1. To my surprise, all the previous AWS Serverless Applications that I had build targeting .Net Core 3.1 are running into same issue which makes me believe that some update have corrupted the installation.
> 
> Things I have already tried:
> 
> * Uninstall & Reinstall DotNetTest tools
> * Updated VS to latest available version
> * Updated Windows to latest version

Hi @rohit3d2003,

Unfortunately, I'm unable to reproduce the issue. I created a new AWS Lambda Serverless project and ran the project with Lambda Test Tool. It worked perfectly fine as shown in the below screenshot:
<img width="2244" alt="Screen Shot 2021-02-08 at 11 09 33 AM" src="https://user-images.githubusercontent.com/67916761/107269674-c608b080-69fe-11eb-9933-f1e5f1832dfd.png">

Yes, if I **stop the debugging**, then I see the same behavior as you reported (which is expected):
<img width="2244" alt="Screen Shot 2021-02-08 at 11 17 28 AM" src="https://user-images.githubusercontent.com/67916761/107270145-6e1e7980-69ff-11eb-8483-dcd4f9de8c32.png">

Just FYI, I'm using version `0.11.1` of Mock Lambda Test tool and AWS Toolkit for Visual Studio 2019 version `1.20.1.0`.

Thanks,
Ashish

**Comment by andersonbytech** [comment]
This happens because of an installed Chrome or Edge addon, find out what it is and disable it or get the link and open it in an anonymous tab.
