### ISSUE TITLE
Allow host to be configurable on Amazon.Lambda.TestTool

### ISSUE THREAD

**Issue by dougludlow** [aws/aws-lambda-dotnet#805]
Currently the `dotnet-lambda-test-tool-x.x.exe` cannot be run from Docker containers because it is bound to `localhost` by default. 

## Describe the Feature
Allow a `--host` option to be passed into the tool to allow the host to be configurable.

Example: `dotnet dotnet-lambda-test-tool-5.0 --host "*"`

### Is your Feature Request related to a problem?
The problem being solved is that the tool can't be run from a Docker container. It's fairly common to install tools and dependencies in container images for development, to avoid having developers on a project install all the various tools and dependencies manually. They just build the container and then go.

## Proposed Solution
Allow a `--host` option to be passed into the tool to allow the host to be configurable.

### Describe alternatives you've considered
Alternatively, the host could also be defaulted to "*", however this use case, in particular, is for support with Docker containers.

## Additional Context
See above.

### Environment

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

I've already made the adjustments on a fork (added a `--host` flag) and it works, still need to add tests, but I wanted to see if this was a direction that should be taken.

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
This needs to be reviewed with the team.

@dougludlow Feel free to contribute a PR since you might be able to implement and test this feature request.

**Comment by normj** [comment]
I think this is a valid feature request. @dougludlow if you want to submit a PR for the feature to get the feature request implemented sooner please tag me on the PR.

**Comment by dougludlow** [comment]
@normj, @ashishdhingra thanks, I can dust off my fork and take a stab at it.

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-lambda-dotnet/pull/1253 appears to be merged. Closing this feature request.
