### ISSUE TITLE
Newly created empty lambda function does not compile with dotnet CLI 1.0.1

### ISSUE THREAD

**Issue by dariusdamalakas** [aws/aws-lambda-dotnet#81]
Hi, first of all, thanks to devs for all the effort in making this possible.  This looks like a very helpful set of tools. 

I do have an issue though - newly created empty lambda function does not compile with dotn CLI 1.0.1. 
`dotnet restore` fails with error `MSB1003`.   Should templates work with CLI 1.0.1?  Am i missing anything?

````
$ npm install -g generator-aws-lambda-dotnet
generator-aws-lambda-dotnet@1.0.14 
<....>

$ yo aws-lambda-dotnet
<hit enter for all answers>

$ cd EmptyFunction

$ ls
global.json  src/  test/

$ dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

$ dotnet -h
.NET Command Line Tools (1.0.1)
````

New empty console project works fine though.  Here's the output:
````
$ dotnet new console -n app2
Content generation time: 56.4729 ms
The template "Console Application" created successfully.

$ cd app2/

$ dotnet restore
<..>

$ dotnet run
Hello World!
````

**Comment by Kralizek** [comment]
@dariusdamalakas  Can you print here the content of the global.json? I think there is an SDK version mismatch.

**Comment by normj** [comment]
We are working on publishing new blue prints based on the new msbuild project format.

**Comment by dariusdamalakas** [comment]
@Kralizek 

````
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}

````


@normj  thanks, will wait for this then

**Comment by normj** [comment]
I'm finishing up the blog post now with more details but if you want to try it now read on.

For the new msbuild project format we are switching away from Yeoman and integrating with `dotnet new`. That way you don't have to install any separate tooling. To install our templates for `dotnet new` run the following command:

`dotnet new -i Amazon.Lambda.Templates::*`

That will install the templates from the NuGet package [Amazon.Lambda.Templates](https://www.nuget.org/packages/Amazon.Lambda.Templates/). 

If you run `dotnet new -all` you will see the Lambda blueprints.

I should get the blog post out tomorrow with more details.

**Comment by bjorg** [comment]
Can't wait to try out the new tooling at the next λ# hackathon. The need to have nodejs and yeoman always felt out of place. Glad to see it go!

**Comment by dariusdamalakas** [comment]
Closing the issue. Have installed templates.
