### ISSUE TITLE
Lambda environment variables passed to container

### ISSUE THREAD

**Issue by dwayne-mss** [aws/aws-lambda-dotnet#812]
I have implemented a Lambda function using the new container feature.  I have set an environment variable in the Lambda definition, but it does not appear to be passed to the container when it is started.  All of the code for the function is in the container, but the code has no method to access the variable.

## Describe the Feature
During the startup of the Lambda function, the container should be started with any Lambda environment variables passed to the container.  The docker run command provides for passing environment variables into the container.

### Is your Feature Request related to a problem?
Yes.  The container I have implemented is basically limited in use.  I have to create a new container for each Lambda function that is based on the container (i.e. telling the container which deployment environment is being supported by the function.

## Proposed Solution
I believe the code that starts the docker container just needs to pass each of the Lambda's environment variables.

### Describe alternatives you've considered
None

## Additional Context
I would like to pass in a runtime environment variable into the container to let it know thinks like name of SSM parameter to retrieve.

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @dwayne-mss,

Good morning.

It's a nice feature where Lambda environment variables could be passed by runtime automatically to container. However, I'm not sure if this should be feature request in the SDK (if SDK controls the start of Docker container) or for the Lambda service team.

Thanks,
Ashish

**Comment by dwayne-mss** [comment]
Yeah... I wasn't sure either.  Didn't know if method would be to inject when the container is started (would be normal approach for docker) or by making an SDK API call from within the container to retrieve the environment.  Figured I would start here... not sure how to submit a request to the other team responsible for code that starts container.  Thanks for the response.

**Comment by saintmie** [comment]
I'm facing the same issue.
I want to pass a lambda environment variables to the container.
I cannot set the variables before in the dockerfile, as they are defined during my deployment.

**Comment by normj** [comment]
I must be missing something because it works for me. I have the following Lambda function that returns the value of an environment variable.

```
public class Function
{
    public string FunctionHandler(string input, ILambdaContext context)
    {
        return Environment.GetEnvironmentVariable(input);
    }
}
```

I have deployed as a container with the `foo` environment variable set to `bar`

![image](https://user-images.githubusercontent.com/1653751/233734433-bbb4a0b4-6a23-44a7-83c4-18f8c330e060.png)

And when I execute the function it returns back the environment variable

![image](https://user-images.githubusercontent.com/1653751/233734635-908a6dbc-3524-43f1-9e2f-d4c9bed89358.png)

Am I misunderstanding something?

**Comment by petarrepac** [comment]
Env vars are supported with AWS Lambda images 
[https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-parms](url)

Also, I cannot see how this could be connected to .NET support in lambda.

Are you sure you published your lambda and are executing the lambda version that you intended to execute ?
Env vars are part of the lambda version that was published.
