### ISSUE TITLE
Difference between Windows and Linux using PutObjectRequest InputStream

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#820]
## Description
I have a method in DotNet Core 3.1 to upload an image to S3 like this (cut down for brevity)
```C#
        public static void AddImage(string bucket_name, string prefix, string image_name, IFormFile file)
        {
            using (s3Client = new AmazonS3Client(aws_access_key, aws_secret_key, Amazon.RegionEndpoint.USWest2))
            {
                using (Stream fileToUpload = file.OpenReadStream())
                {
                    PutObjectRequest put_request = new PutObjectRequest
                    {
                        BucketName = bucket_name,
                        Key = $"{prefix}/{image_name}",
                        InputStream = fileToUpload
                    };
                    PutObjectResponse put_response = s3Client.PutObjectAsync(put_request).Result;
                }
            }
        }
```
Running in Windows (debug via Visual Studio) this works fine when called from Postman. The sample image is Size: 132.05 KB (135 217 bytes) and correctly shows as an image.

I publish this to Lambda and use the same Postman call to send the same image. This time, the image is Size: 236.92 KB (242 603 bytes) and the first bytes are EF BF BD EF BF BD EF BF BD EF BF BD

Since the postman send is exactly the same, I am assuming that the abstract Stream is writing differently in Windows vs Linux? But this seems highly unlikely.

What am I missing here? What mechanism do others use to do this reliably in Lambda?

**Comment by genifycom** [comment]
Confirmation on adding this method:

        public string AddImage([FromQuery] string barcode, [FromQuery] string name, [FromForm(Name = "file")] IFormFile file)
        {
            //return AddImage("pf-picture-inventory", $"{barcode}/", name, file);

            using (var fileToUpload = file.OpenReadStream())
            {
                using (var memoryStream = new MemoryStream())
                {
                    fileToUpload.CopyTo(memoryStream);
                    var bytes = memoryStream.ToArray();
                    var subset = bytes.Take(10);
                    string result = string.Empty;
                    foreach(var abyte in subset)
                    {
                        result += abyte.ToString("X2") + " ";
                    }
                    return result;
                }
            }
        }

For my same image:
In windows, this returns: FF D8 FF E0 00 10 4A 46 49 46
In Lambda this returns: EF BF BD EF BF BD EF BF BD EF

**Comment by ashishdhingra** [comment]
Stackoverflow Post https://stackoverflow.com/questions/41756190/api-gateway-post-multipart-form-data provides some guidance.

**Comment by genifycom** [comment]
Ah, thank you so much. I didn't even think about this being an issue!

Perhaps the CloudStack generation for an AWS Lambda publish from Visual Studio should either add this Binary media type or at least warn us?

**Comment by ashishdhingra** [comment]
@genifycom You may also try exploring option in API Gateway settings as StackOverflow post mentioned. Just mentioning here.
