### ISSUE TITLE
.Net 5 documentation

### ISSUE THREAD

**Issue by soccerboymalloy-patriot** [aws/aws-lambda-dotnet#821]
## Describe the Feature
The [.NET 5 AWS Lambda Support with Container Images](https://aws.amazon.com/blogs/developer/net-5-aws-lambda-support-with-container-images/) blog post links to the [Lambda Test Tool's README](https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool) for testing information. However, there is no information here regarding the version for .Net 5.

It would be helpful to have formal documentation for .Net 5.

**Comment by ashishdhingra** [comment]
Readme lists .NET 5 and .NET 6 versions in the table at https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#versions-of-the-tool. Closing this issue.
