### ISSUE TITLE
Error after publishing to AWS from visual studio

### ISSUE THREAD

**Issue by jashton-vintel** [aws/aws-lambda-dotnet#829]
I've got a very strange issue all of a sudden which i can't seem to solve. I'm using visual studio community 2019 and have recently installed the .NET 5 SDK (which is the only thing i can think has changed other than a visual studio update). I can create a 'AWS Lambda Project' just fine and when running this straight after creating it the Mock lamda Tool opens fine. However once i publish this to my AWS lambda function and try to run it i get the following error message.

**Error Message:**
FileNotFoundException: Could not load file or assembly 'LambdaTest, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

I'm really stuck here and need this to work to proceed with development. Does anyone have any ideas?

**Comment by jashton-vintel** [comment]
It's worth noting that whilst i've installed .NET 5 i'm still trying to create a .NET 3.1 lambda function and i'm creating a 'Empty Function' from the 'New AWS Lambda' project wizard.

**Comment by jashton-vintel** [comment]
Some further info from my investigation here..

My original 'aws-lambda-tools-defaults.json' file looks like this:

`
{
    "Information" : [
        "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
        "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
        "dotnet lambda help",
        "All the command line options for the Lambda command can be specified in this file."
    ],
    "profile"     : "VIntel",
    "region"      : "eu-west-2",
    "configuration" : "Release",
    "framework"     : "netcoreapp3.1",
    "function-runtime" : "dotnetcore3.1",
    "function-memory-size" : 512,
    "function-timeout"     : 15,
    "function-handler"     : "LambdaTest::VIntel.Skill.Function::FunctionHandler"
}`

However when publishing this file is altered to look like:

`
{
    "Information" : [
        "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
        "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
        "dotnet lambda help",
        "All the command line options for the Lambda command can be specified in this file."
    ],
    "profile"     : "VIntel",
    "region"      : "eu-west-2",
    "configuration" : "Release",
    "framework"     : "netcoreapp3.1",
    "function-runtime" : "dotnetcore3.1",
    "function-memory-size" : 512,
    "function-timeout"     : 15,
    "function-handler"     : "LambdaTest::VIntel.Skill.Function::FunctionHandler",
    "function-name"        : "VintelSkill",
    "function-description" : "",
    "package-type"         : "Zip",
    "function-role"        : "<role here>",
    "tracing-mode"         : "PassThrough",
    "environment-variables" : "",
    "image-tag"             : ""
}`

Removing the extra generated JSON from the file makes the mock tool load again.

**Comment by ashishdhingra** [comment]
Hi @jashton-vintel,

Good morning.

Unfortunately I'm unable to reproduce the issue with .NET SDK 5.0 installed. 

1. Created a new AWS Empty function lambda project using Visual Studio template.
**.csproj file**
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>

    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
  </ItemGroup>
</Project>
```
**aws-lambda-tools.defaults.json**
```JSON

{
    "Information" : [
        "This file provides default values for the deployment wizard inside Visual Studio and the AWS Lambda commands added to the .NET Core CLI.",
        "To learn more about the Lambda commands with the .NET Core CLI execute the following command at the command line in the project root directory.",
        "dotnet lambda help",
        "All the command line options for the Lambda command can be specified in this file."
    ],
    "profile"     : "default",
    "region"      : "eu-west-2",
    "configuration" : "Release",
    "framework"     : "netcoreapp3.1",
    "function-runtime" : "dotnetcore3.1",
    "function-memory-size" : 256,
    "function-timeout"     : 30,
    "function-handler"     : "AWSEmptyLambda_Issue829::AWSEmptyLambda_Issue829.Function::FunctionHandler",
    "function-name"        : "TestFunction",
    "package-type"         : "Zip",
    "function-role"        : "arn:aws:iam::139480602983:role/lambda_exec_TestFunction",
    "tracing-mode"         : "PassThrough",
    "environment-variables" : "",
    "image-tag"             : ""
}
```
**Function.cs**
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Amazon.Lambda.Core;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace AWSEmptyLambda_Issue829
{
    public class Function
    {
        
        /// <summary>
        /// A simple function that takes a string and does a ToUpper
        /// </summary>
        /// <param name="input"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        public string FunctionHandler(string input, ILambdaContext context)
        {
            return input?.ToUpper();
        }
    }
}
```
**AWS Toolkit for Visual Studio version:** 1.20.1.0
<br/>
2. Ran the function using Lambda Test Tool. [**Works fine**]
3. Deployed to `eu-west-2` region using Visual Stuydio `Publish to Lambda` option.
4. Invoked the deployed Lambda function. [**Works fine**]

Please compare your project with above. May be you have extra reference for `LambdaTest` assembly. Kindly confirm.

Thanks,
Ashish

**Comment by batni** [comment]
I had the same problem and Modified function-handler in aws-lambda-tools-defaults.json to reflect lambda function the error is gone now 

![image](https://user-images.githubusercontent.com/12651952/186884966-3be29243-6d74-44b0-bb59-8fbf3ac98f70.png)
