### ISSUE TITLE
Difference between dotnet lambda invoke-function and aws lambda invoke regarding payload json

### ISSUE THREAD

**Issue by diegosasw** [aws/aws-lambda-dotnet#830]
## The Question
What's the difference between how dotnet lambda invokes functions and how the AWS CLI does it?
```
dotnet lambda invoke-function lambda-dotnet-function --payload "Just Checking If Everything is OK" --profile diegosasw
```
and
```
aws --profile diegosasw lambda invoke --function-name lambda-dotnet-function --payload '{foo}' response.json
```
I'm not sure whether there is a way to see what AWS CLI command is the dotnet lambda tool generating behind the scenes, but that could help me understand why I cannot invoke a lambda function with AWS CLI and the same function can be invoked with dotnet lambda. See
```
$ dotnet lambda invoke-function lambda-dotnet-function --payload "Just Checking If Everything is OK" --profile diegosasw
Amazon Lambda Tools for .NET Core applications (5.0.1)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Payload:
"JUST CHECKING IF EVERYTHING IS OK"

Log Tail:
START RequestId: 0d28525a-4edc-4391-889d-4a21d0e88832 Version: $LATEST
END RequestId: 0d28525a-4edc-4391-889d-4a21d0e88832
REPORT RequestId: 0d28525a-4edc-4391-889d-4a21d0e88832  Duration: 1.21 ms       Billed Duration: 2 ms   Memory Size: 128 MB     Max Memory Used: 65 MB
```
and
```
$ aws --profile diegosasw lambda invoke --function-name lambda-dotnet-function --payload "Just Checking If Everything is OK" out

An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Unrecognized token 'Just': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"Just Checking If Everything is OK"; line: 1, column: 6]
```
How can I invoke this with AWS CLI or view the equivalent? Is the dotnet lambda using the AWS CLI at all?

### Environment
Ubuntu 20.04 LTS as WSL2 in Windows 10

Sample code: https://gitlab.com/sunnyatticsoftware/sandbox/localstack-sandbox/-/tree/master/03-lambda-dotnet-empty 
---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @diegosasw,

Good morning.

Thanks for posting guidance question. While I cannot comment on AWS CLI command, you may check [aws/aws-cli](https://github.com/aws/aws-cli) repository. But looking at the output posted by you for `aws lambda invoke` command, it appears that AWS CLI is trying to convert payload to JSON. You may try changing your command to below and see if it works (notice that I added escaped double quote at beginning and end of the payload string):
```
aws --profile diegosasw lambda invoke --function-name lambda-dotnet-function --payload "\"Just Checking If Everything is OK\"" out
```

For .NET CLI `dotnet lambda invoke-function` command, you may check [InvokeFunctionCommand](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/9639f8f4902349d289491b290979a3a1671cc0a5/src/Amazon.Lambda.Tools/Commands/InvokeFunctionCommand.cs#L84). The code while parsing payload text adds escaped double quotes at beginning and end of payload text automatically if the text does not contain JSON data delimited by `{` at the beginning. Hence, your payload text works with .NET CLI automatically.

Hope this provides necessary guidance. Kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by diegosasw** [comment]
I read somewhere that AWS CLI v2 requires base64, but this still fails
```
aws --profile diegosasw lambda invoke --function-name lambda-dotnet-function --payload $(echo 'hola amigos' | base64) response.json

An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Could not parse payload into json: Unrecognized token 'aG9sYSBhbWlnb3MK': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"aG9sYSBhbWlnb3MK"; line: 1, column: 33]
```

**Comment by ashishdhingra** [comment]
Hi @diegosasw,

Does the command  `aws --profile diegosasw lambda invoke --function-name lambda-dotnet-function --payload "\"Just Checking If Everything is OK\"" out` fails. I'm not sure about the base64 requirement, that should not be the case while you are invoking Lambda function from AWS CLI. Kindly check AWS CLI v2 documentation https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/invoke.html for `lambda invoke` command. Kindly note that there could be difference with respect to escaping on Windows and Linux command lines.

In case you still face the issue, please open a new issue in [aws/aws-cli](https://github.com/aws/aws-cli) repository.

Thanks,
Ashish

**Comment by diegosasw** [comment]
Life saver! It works great, sorry for the silly question. I was experimenting with base64 thinking the problem could be related to that and didn't even't think about that
```
$ aws --profile diegosasw lambda invoke --function-name lambda-dotnet-function --payload "\"Just Checking If Everything is OK\"" out
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```

And thanks for the useful links!
