### ISSUE TITLE
How can I use dotnet lambda to invoke lambda in LocalStack?

### ISSUE THREAD

**Issue by diegosasw** [aws/aws-lambda-dotnet#831]
## The Question
Is there any way to invoke a lambda function installed in LocalStack? (AWS in local)
```
dotnet lambda invoke-function lambda-dotnet-function --payload "Just Checking If Everything is OK" --profile diegosasw
```
Something like this would be the way to invoke it locally
```
$awslocal lambda invoke --function-name lambda-dotnet-function --payload "Just Checking If Everything is OK" out
```
which is the same as
```
aws --endpoint-url=http://localhost:4566 lambda invoke --function-name lambda-dotnet-function --payload "Just Checking If Everything i
s OK" out
```

I can't make those AWS CLI invokations work either locally or remotely as per https://github.com/aws/aws-lambda-dotnet/issues/830 but it's serves as a sample.

In other words, can I specify a `--endpoint-url=http://localhost:4566` or similar to `dotnet lambda` so that it can run against LocalStack?

### Environment
Ubuntu 20.04 as WSL2 under Windows 10
LocalStack
---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @diegosasw,

Good morning.

Thanks for posting guidance question. I'm afraid LocalStack is not a supported environment for providing any support. Are you facing the issue after deploying to AWS production environment? Also for `dotnet lambda` CLI extension, check [aws/aws-extensions-for-dotnet-cli](https://github.com/aws/aws-extensions-for-dotnet-cli) repository. If you check the code for [InvokeFunctionCommand](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/9639f8f4902349d289491b290979a3a1671cc0a5/src/Amazon.Lambda.Tools/Commands/InvokeFunctionCommand.cs#L16), it only considers `function name` and `payload` as arguments. There is no argument to specify endpoint URL. Hope this answers your question. Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by diegosasw** [comment]
Thanks, perfectly explained. Great links. Closing question.
