### ISSUE TITLE
Dotnet inotify failure during high load

### ISSUE THREAD

**Issue by CameronFiederer** [aws/aws-lambda-dotnet#836]
## Description
We're seeing: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.

## Reproduction Steps
Reviewing our logs - we've been seeing this failure intermittently during high load periods. Last weekend had a dramatic spike in cases. 

![image](https://user-images.githubusercontent.com/5839172/111323399-37f89900-8640-11eb-89ef-add141413c90.png)
![image](https://user-images.githubusercontent.com/5839172/111323457-4777e200-8640-11eb-8e31-fc9fcf5b9317.png)
![image](https://user-images.githubusercontent.com/5839172/111323997-be14df80-8640-11eb-9f29-7d16397a8064.png) < zoomed in on spike to 780 invocations with ~10 concurrent executions

### Logs
Stack trace:  TERMINATED-UNEXPECTEDLY {"ExceptionDetail": {"Type": "System.IO.IOException", "HResult": 24, "Message": "The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.", "Source": "System.IO.FileSystem.Watcher", "StackTrace": "   at System.IO.FileSystemWatcher.StartRaisingEvents()\n   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()\n   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)\n   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)\n   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)\n   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)\n   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)\n   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()\n   at Spsc.DataEngine.AnalyticsDataService.Configuration.CommonConfigurationExtensions.AddCommonConfiguration(IConfigurationBuilder builder)\n   at Spsc.DataEngine.AnalyticsDataService.CommandLine.Program.<>c__DisplayClass1_0.<Run>b__0(IConfigurationBuilder c)\n   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()\n   at Microsoft.Extensions.Hosting.HostBuilder.Build()\n   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)\n   at Spsc.DataEngine.AnalyticsDataService.CommandLine.Program.Run(JObject lambdaInput)\n   at Spsc.DataEngine.AnalyticsDataService.CommandLine.Program.Run(JObject lambdaInput)"}}

### Environment
Error occurring during AWS Lambda Execution
* Targeted .NET Platform:  
<TargetFramework>netcoreapp3.1</TargetFramework>

## Resolution
We've seen this before when we're running docker containers in ECS, not quite sure how to craft a work around with lambda(non-containerized): http://blog.travisgosselin.com/configured-user-limit-inotify-instances/

Do we have to switch to containerized lambda to implement the fixes in the above article(randomizing our user id)(We're making the AddJsonFile change - but based on the above article, that is likely only going to lessen, but not stop the severity of the issue)?

**Comment by ashishdhingra** [comment]
Hi @CameronFiederer,

Good morning.

Kindly confirm if you are using AWS Serverless Application on Lambda. The article http://blog.travisgosselin.com/configured-user-limit-inotify-instances/, as you mentioned, might help. It talks about setting `reloadOnChange` for `appsettings.json` to `false`:

```C#
configuration = new ConfigurationBuilder()
                     .SetBasePath(Directory.GetCurrentDirectory())    
                     .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
```

Please try the above suggestion and confirm if it helps.

Thanks,
Ashish
