### ISSUE TITLE
.NET Web API in Lambda - Cancel work on client abort

### ISSUE THREAD

**Issue by jaknor** [aws/aws-lambda-dotnet#837]
## The Question

Hi,

I am running a .NET Web API inside AWS lambda using Amazon.Lambda.AspNetCoreServer. I am using MVC and want to stop requests from processing if the client cancels the request. Is this something I can do when running .NET inside AWS Lambda?

I know that when hosting .NET in IIS or Kestrel you can inject a CancellationToken into your action which will bind it to HttpContext.RequestAborted. I've tested this successfully on my machine using IIS Express, however, when trying this in AWS lambda the cancellation token is never triggered. 

### Environment

* Build Version: 
  * Amazon.Lambda.AspNetCoreServer: 5.3.1
  * Amazon.Lambda.Core: 1.2.0
  * Amazon.Lambda.Serialization.Json: 1.8.0
  * AWSSDK.Extensions.NETCore.Setup: 3.3.101
  * 
* OS Info:  AWS Lambda
* Build Environment:  CodeBuild
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :question: general question

**Comment by normj** [comment]
This won't work in the AWS Lambda case. When the Lambda function is executing the ASP.NET Core request it is doing it in isolation from the client who would call cancel. Once the Lambda function is complete it sends the results back to API Gateway to pass down to the user.

**Comment by jaknor** [comment]
OK, thanks for letting me know.
