### ISSUE TITLE
System.Diagnostics.TraceSource.dll not packed correctly when deploying lambdas

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#84]
Hello Lambda,

When using `DbConnection`, say to connect to a MySql database, it requires `System.Diagnostics.TraceSource.dll`. However, when running `dotnet lambda deploy-function`, the required dll file were buried in `runtimes/unix/lib/netstandard1.3/System.Diagnostics.TraceSource.dll`, which renders the `DbConnection` failed to load.

I noticed that you have successfully found the requirements and packed those two additional files:
```
... publish: Adding additional file runtimes/unix/lib/netstandard1.3/System.Data.SqlClient.dll
... publish: Adding additional file runtimes/unix/lib/netstandard1.3/System.IO.Pipes.dll
```

After further investigation, it seems like when publishing lambda,  it will make sure all the package in `dependencies` field will be flattened, but the `System.Diagnostics.TraceSource.dll` only appears in `compile` field, and will be target to the specific version for `unix` or `win` during the runtime. However, the runtime lambda provided does not work this way.
```
"System.Diagnostics.TraceSource/4.0.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.NETCore.Platforms": "1.0.1",
          "System.Collections": "4.0.11",
          "System.Diagnostics.Debug": "4.0.11",
          "System.Globalization": "4.0.11",
          "System.Resources.ResourceManager": "4.0.1",
          "System.Runtime": "4.1.0",
          "System.Runtime.Extensions": "4.1.0",
          "System.Threading": "4.0.11",
          "runtime.native.System": "4.0.0"
        },
        "compile": {
          "ref/netstandard1.3/System.Diagnostics.TraceSource.dll": {}
        },
        "runtimeTargets": {
          "runtimes/unix/lib/netstandard1.3/System.Diagnostics.TraceSource.dll": {
            "assetType": "runtime",
            "rid": "unix"
          },
          "runtimes/win/lib/netstandard1.3/System.Diagnostics.TraceSource.dll": {
            "assetType": "runtime",
            "rid": "win"
          }
        }
      },
```

Any idea how to fix this issue?

Thanks

**Comment by normj** [comment]
What version of Amazon.Lambda.Tools are you referencing in your project? Also if you could share your project.json or csproj file that would be really helpful.

**Comment by MZhoume** [comment]
@normj Apparently after update to version 1.4.0 solves this issue. We were using 1.2.0-preview1.

So that brought up another question, is there a way to quickly update all the dependencies version in project.json?

**Comment by normj** [comment]
Ahh that makes sense. It was in version 1.3.0-preview1 that we did a lot work on reworking the runtime dependencies.

I don't know of any .NET Core tooling to update all the dependencies and right now that can be tricky because it might push you to .NET Core 1.1 versions of the system packages.

**Comment by MZhoume** [comment]
@normj Hopefully it would become possible in dotnet-cli v2.

Thanks for the job, it was awesome.
