### ISSUE TITLE
The stack's current state of UPDATE_ROLLBACK_FAILED is invalid for updating

### ISSUE THREAD

**Issue by dalton5** [aws/aws-lambda-dotnet#842]
Hi,

I have the error "The stack's current state of UPDATE_ROLLBACK_FAILED is invalid for updating"

Please see below. What can be the cause?

How can I investigate?

It worked 1 month ago

![image](https://user-images.githubusercontent.com/8339768/112701797-e0ed9200-8e91-11eb-86c6-0cbf4d1ef83f.png)

Thanks,

**Comment by dalton5** [comment]
THese are more detials I found

![image](https://user-images.githubusercontent.com/8339768/112702078-a59f9300-8e92-11eb-9bb2-e522ec4d7792.png)

**Comment by ashishdhingra** [comment]
Hi @dalton5,

Good afternoon.

The new policy name is `AWSLambda_FullAccess` (arn:aws:iam::aws:policy/AWSLambda_FullAccess). The old policy name is no longer available. Lambda functions currently configured with old policy continue to work. Please let me know if this resolves your issue.

Thanks,
Ashish

**Comment by dalton5** [comment]
I still have the issue. I need to change the policy name in the serverless.template file.

Do I need to change it in another place?

**Comment by ashishdhingra** [comment]
> I still have the issue. I need to change the policy name in the serverless.template file.
> 
> Do I need to change it in another place?

@dalton5 Changing in `serverless.template` should work. I just tested it with a Serverless application using `dotnet lambda deploy-serverless`:
- Had `serverless.template` with policy `AWSLambdaFullAccess`. It gave the same error as you reported.
- Changed policy in `serverless.template` to `AWSLambda_FullAccess`. It worked and created new serverless application.

Please let me know if you face any issues.

Thanks,
Ashish

**Comment by dalton5** [comment]
Did not work for me. I use the visual studio addin. 

But I renewed the name of the stack and it works. The config was not overwritten on my old stack. Don't know why.

Thanks for your help

**Comment by ashishdhingra** [comment]
> Did not work for me. I use the visual studio addin.
> 
> But I renewed the name of the stack and it works. The config was not overwritten on my old stack. Don't know why.
> 
> Thanks for your help

@dalton5 Unfortunately I do not have existing stack with policy `AWSLambdaFullAccess` already applied, hence could not investigate the issue. Now that it works for you, kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by dalton5** [comment]
Yes you can close. Thanks
