### ISSUE TITLE
AWS .NET Mock Lambda Test Tool - NullReferenceException when returning a Stream

### ISSUE THREAD

**Issue by unencoded-code** [aws/aws-lambda-dotnet#843]
## Description

I have a simple function that handles input and output streams directly without using serialization. When published to a Lambda function on AWS, the function works as expected. The function takes the user's input as a stream, converts it to a string and then back to a stream which is returned by the function. When run on AWS, user input is reflected as expected. The source code for this function is shown below:

```
public class Function
    {
        public Stream FunctionHandler(Stream userInput, ILambdaContext context)
        {
            string JsonString;
            using (var reader = new StreamReader(userInput))
            {
                JsonString = reader.ReadToEnd();
            }

            byte[] bytes = System.Text.Encoding.UTF8.GetBytes(JsonString);
            MemoryStream stream = new MemoryStream(bytes);
            return stream;
        }
    }
```

When running the function with the AWS .NET Mock Lambda Test Tool, the following error is thrown when the function returns the stream:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Amazon.Lambda.TestTool
  StackTrace:
   at Amazon.Lambda.TestTool.Runtime.LambdaExecutor.<ProcessReturnAsync>d__4.MoveNext() in C:\codebuild\tmp\output\src245625219\src\Tools\LambdaTestTool\src\Amazon.Lambda.TestTool\Runtime\LambdaExecutor.cs:line 162
```

## Reproduction Steps

1. Create an empty AWS Lambda C# project in Visual Studio 2019 using version 1.20.1.0 of the AWS Toolkit.
2. Replace the default function with the code above
3. Comment out or remove the default serializer attribute:
`[assembly: LambdaSerializer(typeof(DefaultLambdaJsonSerializer))]`
4. Start debugging the function in Visual Studio to launch the AWS .NET Mock Lambda Test Tool.
5. Submit any input (such as "Test") to the function via Test Tool "Function Input" box to observe the error.

### Logs
Please let me know if there is more information I can provide here to help.

![image](https://user-images.githubusercontent.com/18757122/113203911-8626b280-9264-11eb-9929-fdd499640bd9.png)

### Environment

* Build Version: AWS Toolkit 1.20.1.0, Amazon Lambda Core 1.2.0
* OS Info:  Windows 10 Version 20H2
* Build Environment: Visual Studio 2019 Version 16.9.3
* Targeted .NET Platform:  .NET Core 3.1

## Resolution

Is it possible to better emulate the behaviour of real Lambda functions when handling stream output?

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible when using function signature `Stream FunctionHandler(Stream userInput, ILambdaContext context)`.

**Comment by fbouteruche** [comment]
I also face this issue. Quite annoying when you have to deal with raw Stream.

**Comment by mirousek** [comment]
I have same problem when async lambda handler returns untyped Task. In mock tool it seems like the handler has crashed although it run correctly.
