### ISSUE TITLE
Blueprint Serverless ASP.NET Core Web Application with Razor Pages gives 403 error for favicon.ico

### ISSUE THREAD

**Issue by hashitha** [aws/aws-lambda-dotnet#844]
## Description
favicon.ico gives 403 error when running in Lambda but it works locally. See screenshot

![image](https://user-images.githubusercontent.com/10569142/113499180-7ea62880-9546-11eb-9d5f-704f169b4ac4.png)

## Reproduction Steps
1. Create AWS Serverless application and select blueprint ASP.Net Core Web App (Serverless ASP.NET Core Web Application with Razor Pages)
![image](https://user-images.githubusercontent.com/10569142/113499202-aa291300-9546-11eb-9d79-b417e8af1cfb.png)

2. Right-Click project and Publish to AWS Lambda
3. Open the AWS Serverless URL

 
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @hashitha,

Good morning.

Could you please follow guidance at [Supporting Binary Response Content](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md#supporting-binary-response-content) and confirm if it works for you?

Thanks,
Ashish
