### ISSUE TITLE
Add APIGatewayCustomAuthorizerRequest V2

### ISSUE THREAD

**Issue by carlin-q-scott** [aws/aws-lambda-dotnet#845]
Add support for APIGatewayCustomAuthorizerRequest V2

## Describe the Feature
[APIGatewayCustomAuthorizerRequest.cs](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayCustomAuthorizerRequest.cs) is not compatible with [format 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html#http-api-lambda-authorizer.payload-format)

### Is your Feature Request related to a problem?

I can't deserialize the latest request format for Api Gateway Custom Authorizers.

### Describe alternatives you've considered

Roll my own AuthorizerRequest class.

## Additional Context

I get a 500 internal server error when my HttpApiGateway attempts to call my Lambda Authorizer Function.

### Environment

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @carlin-q-scott,

Good afternoon.

Thanks for raising the issue. As of now, we cannot commit on the timeline by which this feature request could be reviewed and prioritized. However, it would really help if you could submit a PR for this change.

Thanks,
Ashish

**Comment by Glen-Moonpig** [comment]
Make sure to add the response class also 👍

**Comment by kjones** [comment]
Seems like this is still needed? I don't see these classes in the [current SDK](https://github.com/aws/aws-lambda-dotnet/tree/f9beed29dcb842f86c8cfb46e9bb59b585858d2f/Libraries/src/Amazon.Lambda.APIGatewayEvents).

**Comment by normj** [comment]
The PR with this change has been released as part of version 2.6.0 of Amazon.Lambda.APIGatewayEvents
