### ISSUE TITLE
"Can't find type" - Rider on Ubuntu 20.10 - .NET Test Tool

### ISSUE THREAD

**Issue by bschaatsbergen** [aws/aws-lambda-dotnet#851]
### Environment

* Build Version: 
* OS Info: Ubuntu 20.10
* Build Environment: Rider
* Targeted .NET Platform:  .NET Core 3.1

---

This is a general question

I've recently moved from Windows to Ubuntu and started using Rider as my .NET IDE, now I'm trying to get the AWS .NET Lambda Test Tool to work and followed the readme in the repo carefully but I can't seem to figure out why my setup isn't working.. It's complaining about a the type that can't be found of the method I'm pointing to..

exe path I'm pointing to: 
`/home/bruno/.dotnet/tools/.store/amazon.lambda.testtool-3.1/0.11.3/amazon.lambda.testtool-3.1/0.11.3/tools/netcoreapp3.1/any/Amazon.Lambda.TestTool.BlazorTester.dll`

I've tried pointing to both root dir of the project and debug dir
`/home/bruno/Work/tariffinfo-export/src/TariffInfo.Export.Processor.Lambda/`
`/home/bruno/Work/tariffinfo-export/src/TariffInfo.Export.Processor.Lambda/bin/Debug/netcoreapp3.1`

I use an additional aws-lambda-tools-defaults-mainqueuehandler.json, which looks like this:

```json
{
  "Information": [""],
  "profile": "playpenprofile",
  "region": "eu-west-2",
  "framework": "netcoreapp3.1",
  "function-handler": "TariffInfo.Export.Processor.Lambda::TariffInfo.Export.Processor.Lambda.EventHandler::HandleEventAsync",
  "function-name": "TariffInfo.Export.Processor.Lambda.EventHandler"
}
```
My class EventHandler.cs is located under /home/bruno/Work/tariffinfo-export/src/TariffInfo.Export.Processor.Lambda/

The error I'm getting is: "Failed to find type TariffInfo.Export.Processor.Lambda.EventHandler"

![image](https://user-images.githubusercontent.com/58337159/114320274-800ebc80-9b15-11eb-977c-80d6719a6c42.png)

**Comment by bschaatsbergen** [comment]
I'm able to reproduce it on the .NET Core 2.1 Test Tool in a different project whilst making use of:
`/home/bruno/.dotnet/tools/.store/amazon.lambda.testtool-2.1/0.11.3/amazon.lambda.testtool-2.1/0.11.3/tools/netcoreapp2.1/any/Amazon.Lambda.TestTool.WebTester21.dll`

I've a slight feeling I'm either doing something wrong or I've overseen that the tool is not supported in the environment I'm working on, anyhoo would love to hear if others are facing this issue or what I could do to fix it :smile_cat:

**Comment by bschaatsbergen** [comment]
**Resolved**

After creating an **omnisharp.json**

Containing the following config:

```
{
    "fileOptions": {
      "excludeSearchPatterns": [
        "**/bin/**/*",
        "**/obj/**/*"
      ]
    },
    "msbuild": {
        "Platform": "rhel.7.2-x64"
    }
}
```

**Comment by pmihalcin** [comment]
@bschaatsbergen Did you do anything special to have `~/.dotnet/tools/.store` created? I'm on Ubuntu 20.04 and this subfolder doesn't get created for me after I install lambda test tool globally.

**Comment by bschaatsbergen** [comment]
@pmihalcin Hmm this should be done by default, when taking a look under the hood this is what happens:

When dotnet tool install --global executes, it…

- uses dotnet restore with special parameters to fetch the package.
- extracts the package into $HOME/.dotnet/.store/(package id)/(version)
- Generates an executable in $HOME/.dotnet/tools

**Comment by pmihalcin** [comment]
@bschaatsbergen yes, indeed, hidden folders were hidden :)
Now I can execute functionm thanks.

I've hit another issue where lambda test tool doesn't load transitive dependencies.
I can see these dependencies in `bin/Debug/netcoreapp3.1`, but lambda test tool doesn't load them.
When I copy these dependencies to `~/.dotnet/tools/.store/amazon.lambda.testtool-3.1/0.11.3/amazon.lambda.testtool-3.1/0.11.3/tools/netcoreapp3.1/any`, then function executes properly.

Have you hit such issue before?

It seems it is Rider specific issue, because we have to do some special Rider steps as mentioned here: https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#configure-for-jetbrains-rider or I might be mistaken and it is how Lambda test tool works

**Comment by bschaatsbergen** [comment]
You should not copy dependecies there as the installation of the lambda tool will already install it there _too_ by default. Just point Rider to that path @pmihalcin

**Comment by pmihalcin** [comment]
@bschaatsbergen the problem I'm facing is that transitive dependencies are not installed to `~/.dotnet/tools/.store/amazon.lambda.testtool-3.1/0.11.3/amazon.lambda.testtool-3.1/0.11.3/tools/netcoreapp3.1/any`. That's the reason I have to copy them there. Have you faced such problem before?
