### ISSUE TITLE
Blog Blueprint does not work out-of-box

### ISSUE THREAD

**Issue by ppittle** [aws/aws-lambda-dotnet#852]
## Description
The Blog Blueprint does not work out-of-the-box and requires several modifications to make operational.

1. Modify **[serverless.template](https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/netcore3.1/DynamoDBBlogAPI/template/src/BlueprintBaseName.1/serverless.template#L61)** to assign appropriate dynamodb role to `GetBlogs`, `GetBlog`, `AddBlog`, and `RemoveBlog`:
```json
Policies": [
   "AWSLambda_FullAccess",
   "AmazonDynamoDBFullAccess"  // <--- necessary to add
],
```
2.  Decorate [`Blog.Id`](https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/netcore3.1/DynamoDBBlogAPI/template/src/BlueprintBaseName.1/Blog.cs#L10) with `[DyanmoDBHashKey]` attribute.
```csharp
public class Blog
{
    [DynamoDBHashKey]
    public string Id { get; set; }
}
```

## Reproduction Steps

1. In Visual Studio, create a new Project using the **AWS Serverless Application** Project Template

![image](https://user-images.githubusercontent.com/1190907/114485692-38de0580-9bc1-11eb-9add-71d07d9f7431.png)

1. Select **Blog API using Dynamo DB** Blueprint.

![image](https://user-images.githubusercontent.com/1190907/114485760-53b07a00-9bc1-11eb-906a-3b6d221dee44.png)

1. Right click on the Project and Publish to AWS Lambda

![image](https://user-images.githubusercontent.com/1190907/114485825-717ddf00-9bc1-11eb-8ad7-7018e47f41b1.png)

1. Run the `testScript.ps1` (contents below).

**Expect: ** Script should complete successfully.

### Logs

```
"Message":"User: arn:aws:sts::8xxxxxxxxx4:assumed-role/example-GetBlogsRole-TF8JQS710Q8H/example-GetBlogs-2K8167JQPX14 is not authorized to perform:
     | dynamodb:DescribeTable on resource:
     | arn:aws:dynamodb:us-west-2:8xxxxxxxxx4table/example-BlogTable-1QOLWPD4OM63Y"
```

### Environment

* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  3.1

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

## Test Script:

```powershell
Param(
    [Parameter(Mandatory=$true)]
    [String]
    $apiUrl)

if ($apiUrl.EndsWith("/") -ne $true){
    $apiUrl = $apiUrl+"/"
}
 
Write-Host
Write-Host "PUT"
$newBlog = "{ 'Name': 'Test1', 'Content': 'Good Blog'}"
$put = Invoke-WebRequest $apiUrl -Method Put -Body $newBlog
if ($put.StatusCode -ne 200) {
    Write-Error "Failed to Put:"
    Write-Error $put.Content
    return
}
else {
    Write-Host "Put: 200"
}
$newBlogId = $put.Content
Write-Host "New BlogId: $newBlogId"

Write-Host
Write-Host "GET-ALL"
$getAll = Invoke-WebRequest $apiUrl
if ($getAll.StatusCode -ne 200) {
    Write-Error "Failed to GetAll:"
    Write-Error $getAll.Content
    return
}
else {
    Write-Host "Get All: 200"
    Write-Host $getAll.Content | ConvertFrom-Json
}

Write-Host
Write-Host "GET"
$get = Invoke-WebRequest "$apiUrl$newBlogId"
if ($get.StatusCode -ne 200) {
    Write-Error "Failed to Get $newBlogId :"
    Write-Error $get.Content
    return
}
else {
    Write-Host "Get $newBlogId : 200"
    Write-Host $get.Content | ConvertFrom-Json
}

Write-Host
Write-Host "DELETE"
$deleteUrl = $apiUrl+"?Id=" +$newBlogId
$delete = Invoke-WebRequest $deleteUrl -Method Delete
if ($delete.StatusCode -ne 200) {
    Write-Error "Failed to Delete $newBlogId :"
    Write-Error $delete.Content
    return
}
else {
    Write-Host "Delete $newBlogId : 200"
    Write-Host $delete.Content | ConvertFrom-Json
}

Write-Host "Test Completed SUCCESSFULLY"

```

Thanks to @rahulpnath for reporting this.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Fixed in latest .NET CLI blueprints. PR https://github.com/aws/aws-toolkit-visual-studio-staging/pull/457 for AWS Toolkit for Visual Studio team is pending review/merge. Closing this since the backlog item is closed.
