### ISSUE TITLE
HttpContext.Connection.RemotePort is not the remote client's port

### ISSUE THREAD

**Issue by YDKK** [aws/aws-lambda-dotnet#855]
## Description

In #89, the support of obtaining `HttpContext.Connection.RemotePort` value from the APIGatewayProxyRequest's `Headers["X-Forwarded-Port"]` is implemented.
However, this value is not a remote client's port, but the API Gateway's listen port.

## Reproduction Steps

1. In Visual Studio, create a new Project using the **AWS Serverless Application** Project Template.
2. Choose **ASP.NET Core 5 (Container I...** blueprint.
3. Create a new controller with the code like below.
```cs
[HttpGet]
public IActionResult Test()
{
    var c = Request.HttpContext.Connection;
    Logger.LogInformation($"Source IP address: {c.RemoteIpAddress}, port: {c.RemotePort}");
    return Ok();
}
```
4. Right click on the Project and Publish to AWS Lambda.
5. Access to the controller over the API Gateway and check the logger output.

### Logs

The logs will be like this.
```
[Information] TestApi.Controllers.TestController: Source IP address: xx.xx.xxx.xxx, port: 443 
```
The source IP address shows the real remote client's IP address, but the port shows the API Gateway's listen port.

### Environment

* Build Version: 5.3.0
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET 5.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Needs investigation.
