### ISSUE TITLE
Unable to find Amazon.Lambda.TestTool.WebTester31.dll

### ISSUE THREAD

**Issue by pmihalcin** [aws/aws-lambda-dotnet#859]
## The Question
I'm following https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md
and I successfully installed `dotnet tool install -g Amazon.Lambda.TestTool-3.1`

Now I would like to find `Amazon.Lambda.TestTool.WebTester31.dll`
https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#configure-for-jetbrains-rider
but I don't have any `.store` folder under `~/.dotnet/tools`
The only thing I have in `~/.dotnet/tools` is `dotnet-lambda-test-tool-3.1`

Please note I'm on Ubuntu

Is there anything else I should do?

Thanks for any help

### Environment

* Build Version: 
* OS Info: Ubuntu 20.04.2 LTS 
* Build Environment: Jetbrains Rider + Terminal `dotnet` 
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @pmihalcin,

Thanks for posting the guidance question. You are correct, I was unable to find  `Amazon.Lambda.TestTool.WebTester31.dll` on both Windows and Mac terminal after installing the test tool using command  `dotnet tool install -g Amazon.Lambda.TestTool-3.1`.
- Mac terminal path: `/Users/<<username>>/.dotnet/tools/.store/amazon.lambda.testtool-3.1/0.11.3/amazon.lambda.testtool-3.1/0.11.3/tools/netcoreapp3.1/any`
- Windows path: `<<drive:>>\Users\<<username>>\.dotnet\tools\.store\amazon.lambda.testtool-3.1\0.11.3\amazon.lambda.testtool-3.1\0.11.3\tools\netcoreapp3.1\any`

I will get in touch with development team and get back to you on this.

Thanks,
Ashish

**Comment by pmihalcin** [comment]
@ashishdhingra I uninstalled version `0.11.3` and installed `0.10.1`
```
dotnet tool uninstall --global Amazon.Lambda.TestTool-3.1
dotnet tool install --global Amazon.Lambda.TestTool-3.1 --version 0.10.1
```
and I still don't see any `.store` folder and `dotnet-lambda-test-tool-3.1` is the only binary I see in `~/.dotnet/tools`

**Comment by ashishdhingra** [comment]
> @ashishdhingra I uninstalled version `0.11.3` and installed `0.10.1`
> 
> ```
> dotnet tool uninstall --global Amazon.Lambda.TestTool-3.1
> dotnet tool install --global Amazon.Lambda.TestTool-3.1 --version 0.10.1
> ```
> 
> and I still don't see any `.store` folder and `dotnet-lambda-test-tool-3.1` is the only binary I see in `~/.dotnet/tools`

@pmihalcin The `.store` folder is the hidden folder, you can simply navigate to it:

<img width="914" alt="Screen Shot 2021-05-12 at 10 30 40 AM" src="https://user-images.githubusercontent.com/67916761/118019009-58299900-b30d-11eb-95e6-b25e866c3753.png">

**Comment by pmihalcin** [comment]
Oh yeah, my bad. Thanks a lot, I somehow haven't realized that `ls` output doesn't contain hidden folders by default. Now I can see it.

**Comment by ashishdhingra** [comment]
> Oh yeah, my bad. Thanks a lot, I somehow haven't realized that `ls` output doesn't contain hidden folders by default. Now I can see it.

@pmihalcin In case the issue is resolved, please let me know let me know if this could be closed.

Thanks,
Ashish

**Comment by pmihalcin** [comment]
It is working now.

How to for future self:

- `dotnet tool install --global Amazon.Lambda.TestTool-3.1 --version 0.11.3`

- set `Exe path` field in .NET Executable run configuration to `/home/.../.dotnet/tools/.store/amazon.lambda.testtool-3.1/0.11.3/amazon.lambda.testtool-3.1/0.11.3/tools/netcoreapp3.1/any/Amazon.Lambda.TestTool.BlazorTester.dll` + replace `...` with your username
- set the `Working directory` field to the .NET Core Lambda project root

Information distilled from https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#configure-for-jetbrains-rider
