### ISSUE TITLE
Lambda test tool doesn't load transitive dependencies

### ISSUE THREAD

**Issue by pmihalcin** [aws/aws-lambda-dotnet#861]
## The Question
I have Rider .NET Executable run configuration and I can now run lambda test tool to execute function handler.

When I execute function handler, it only knows about direct compile dependencies, but it seems it can't recognize runtime dependencies, hence my function handler fails.
I can see that all dependencies are located in project's `bin/Debug/netcoreapp3.1` folder, but lambda test tool doesn't load all of them.

When I manually copy dlls to `~/.dotnet/tools/.store/amazon.lambda.testtool-3.1/0.11.3/amazon.lambda.testtool-3.1/0.11.3/tools/netcoreapp3.1/any`, it is working.

How does Lambda test tool load dependencies?
Can I somehow supply additional list of dlls to be included to lambda test tool scope?

### Environment

* Build Version: amazon.lambda.testtool-3.1 0.11.3 
* OS Info: Ubuntu 20.04.2 LTS 
* Build Environment: Jetbrains Rider + Terminal `dotnet` 
* Targeted .NET Platform:  .NET Core 3.1 

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @pmihalcin,

Good morning.

Please try using the `CopyLocalLockFileAssemblies` element with a value of `true` in your `.csproj` file as mentioned in https://github.com/aws/aws-lambda-dotnet/issues/639 and see if it resolves your issue.
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    ...
    ...
  </ItemGroup>
</Project>
```

Thanks,
Ashish

**Comment by pmihalcin** [comment]
@ashishdhingra I already have it in `.csproj`

**Comment by ashishdhingra** [comment]
Hi @pmihalcin,

Could you please provide more details about runtime dependencies and how they are used in your project? Perhaps, a sample application would be helpful.

Thanks,
Ashish

**Comment by pmihalcin** [comment]
All these dependencies are company ones, so it's not simple for me to put together such sample. The thing is there is some service discovery mechanism which looks at all dlls which are present and based on the presence it knows what service to configure. These dependencies are not visible to lambda test tool unless I copy them alongside `BlazorTester.dll`
Is there any way how I can debug what lambda test tool does in the background, so that I can provide it to you?

**Comment by ashishdhingra** [comment]
Hi @pmihalcin,

Good morning.

My apologies for the delayed reply. Based on my analysis, for more information on how Lambda Test Tool resolves the dependencies, please refer the code in https://github.com/aws/aws-lambda-dotnet/blob/00009c7d4fb4fb406c355a99d11d142718ba4374/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/TestToolStartup.cs#L35. [Amazon.Lambda.TestTool.BlazorTester](https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool.BlazorTester/Program.cs) is a simple program with entry point which invokes the Lambda Test Tool Startup to launch the Lambda test tool. You could get some help by examining https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/tests/Amazon.Lambda.TestTool.Tests.Shared/NoUiStartupTests.cs class on how to debug the test tool code.

Hope this helps.

Thanks,
Ashish
