### ISSUE TITLE
Amazon.Lambda.AspNetCoreServer `OnStarting()` is not called on response

### ISSUE THREAD

**Issue by williamdenton** [aws/aws-lambda-dotnet#866]
## Description

A common pattern for attaching headers to the response in ASP.Net is to use the [`Response.OnStarting()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ihttpresponsefeature.onstarting?view=aspnetcore-3.1#Microsoft_AspNetCore_Http_Features_IHttpResponseFeature_OnStarting_System_Func_System_Object_System_Threading_Tasks_Task__System_Object_) callback to attach headers at the last possible moment before the response is written to the wire.

When using a lambda with `ApplicationLoadBalancerFunction`, the OnStarting callback is not executed. This means that headers added using this technique are not included in the response object `ApplicationLoadBalancerResponse`

https://github.com/aws/aws-lambda-dotnet/blob/20046865db2afd3cf57b1d92d492f1fb4ec08a9d/Libraries/src/Amazon.Lambda.AspNetCoreServer/ApplicationLoadBalancerFunction.cs#L133-L146

`OnCompleted` Is not called either.

I have not confirmed, but strongly suspect this same bug exists in the ApiGateway Response handling logic too.

## Reproduction Steps

If you have a function like this, the headers included will not be rendered in the ALB response:

```cs
SetHeadersOnHttpContext(HttpContext context)
{
	context.Response.OnStarting(() => {
		context.Response.Headers.Add("X-My-Header", "my _header_value");
		return Task.CompletedTask;
	});
}
```

### Logs
N/A

### Environment
* Build Version: Amazon.Lambda.AspNetCoreServer 6.0.2
* OS Info: Lambda
* Build Environment: Any
* Targeted .NET Platform:  3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

The code in `ApplicationLoadBalancerFunction.cs` above needs to call OnStarting() and OnCompleted()

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @williamdenton,

Good afternoon.

Somehow, I'm unable to reproduce the issue. Here are the steps:
- Create a new WebAPI serverless application using Visual Studio AWS template.
- Modify the `LambdaEntryPoint` class to inherit from `Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction`:
```C#
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace AWSServerless6
{
    public class LambdaEntryPoint : Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction
    {
        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseStartup<Startup>();
        }

        
        protected override void Init(IHostBuilder builder)
        {
        }
    }
}
```
- Configure the middleware in `Startup.Configure()` to invoke `SetHeadersOnHttpContext` as shown below:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace AWSServerless6
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public static IConfiguration Configuration { get; private set; }

        // This method gets called by the runtime. Use this method to add services to the container
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.Use(async (context, nextMiddleware) =>
            {
                SetHeadersOnHttpContext(context);
                await nextMiddleware();
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Welcome to running ASP.NET Core on AWS Lambda");
                });
            });

            
        }

        public void SetHeadersOnHttpContext(HttpContext context)
        {
            context.Response.OnStarting(() => {
                context.Response.Headers.Add("X-My-Header", "my_header_value");
                return Task.CompletedTask;
            });
        }
    }
}
```
- Deploy the project to AWS Lambda.
- Follow steps at [Lambda functions as targets for Application Load Balancers](https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/) to create Application Load balancer with Lambda function as target.
- Invoke the endpoint using Application Load Balancer DNS name (e.g. http://testloadbalancer-xxxxxxxxxx.us-east-2.elb.amazonaws.com/api/values)

**RESULT:**
WebAPI result is returned along with the headers set inside `OnStarting()` delegate.
<img width="1567" alt="Screen Shot 2021-07-26 at 2 27 33 PM" src="https://user-images.githubusercontent.com/67916761/127062481-ceec4b28-42db-482b-924a-ed8d6a16e933.png">

Thanks,
Ashish
