### ISSUE TITLE
Cannot publish AWS Serverless Application for ASP.NET Core 5 if it references a Blazor Client project

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#871]
## Description
I want to publish an AWS Serverless Application for ASP.NET Core 5 that can also serve up Blazor client files.

## Reproduction Steps
On Windows 10, Visual Studio 2019 Version 16.10.0 with AWS Toolkit Version 1.21.2.0

1. Create an AWS Serverless Application project and select ASP.NET Core 5 (Container Image). Default name is AWSServerless1
This will publish fine and run in Lambda

2. Next add a Blazor WebAssembly App. Default name is WebApplication1.
3. Add a project reference in AWSServerless1 to reference WebApplication1.

Now try to publish to Lambda AWSServerless1. This produces the error:

`... publish: C:\Program Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets(617,5): error MSB4096: The item "C:\Dev\Projects\AWSBlazor\WebApplication1\bin\Release\net5.0\WebApplication1.runtimeconfig.json" in item list "AllPublishItemsFullPathWithTargetPath" does not define a value for metadata "RelativePath".  In order to use this metadata, either qualify it by specifying %(AllPublishItemsFullPathWithTargetPath.RelativePath), or ensure that all items in this list define a value for this metadata. [C:\Dev\Projects\AWSBlazor\WebApplication1\WebApplication1.csproj]`

Based on an answer by mrwcjoughin, this only works for them with the .NET SDK Version 5.0.101
Changing to this with global.json and { "sdk": { "version": "5.0.101" } }
the error message now changes to:

`... publish: C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(143,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [C:\Dev\Projects\AWSBlazor\WebApplication1\WebApplication1.csproj]`

### Logs
```
Deleted previous publish folder
... invoking 'dotnet publish', working folder 'C:\Dev\Projects\AWSBlazor\AWSServerless1\.\./bin/Release/net5.0/linux-x64/publish'
... dotnet publish "C:\Dev\Projects\AWSBlazor\AWSServerless1\." --output "C:\Dev\Projects\AWSBlazor\AWSServerless1\.\./bin/Release/net5.0/linux-x64/publish" --configuration "Release" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false 
... publish: Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
... publish: Copyright (C) Microsoft Corporation. All rights reserved.
... publish:   Determining projects to restore...
... publish:   Restored C:\Dev\Projects\AWSBlazor\AWSServerless1\AWSServerless1.csproj (in 211 ms).
... publish:   Restored C:\Dev\Projects\AWSBlazor\WebApplication1\WebApplication1.csproj (in 211 ms).
... publish:   WebApplication1 -> C:\Dev\Projects\AWSBlazor\WebApplication1\bin\Release\net5.0\WebApplication1.dll
... publish:   WebApplication1 (Blazor output) -> C:\Dev\Projects\AWSBlazor\WebApplication1\bin\Release\net5.0\wwwroot
... publish:   AWSServerless1 -> C:\Dev\Projects\AWSBlazor\AWSServerless1\bin\Release\net5.0\linux-x64\AWSServerless1.dll
... publish: C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(143,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [C:\Dev\Projects\AWSBlazor\WebApplication1\WebApplication1.csproj]
Error executing "dotnet publish"
```

### Environment

* Build Version: Amazon.Lambda.AspNetCoreServer Version 5.3.0
* OS Info: Windows 10 version 20H2
* Build Environment: Visual Studio version 16.10.0
* Targeted .NET Platform:  5.0

## Resolution
Research and asking about RelativePath has not allowed a resolution.
- [x] :wave: I can/would-like-to implement a fix for this problem myself

I have tried .NET SDK 5.0.101 and .NET SDK 5.0.202
101 produces the second error and 202 produces the first.

How do we set self-contained using the Visual Studio deployment?

I tried adding to aws-lambda-tools-defaults.json
 "msbuild-parameters": "--self-contained true /p:AssemblyName=bootstrap",
 but alas same error.

---

This is a :bug: bug-report

**Comment by genifycom** [comment]
Hi Ashish,
Is there anywhere I can find more info on this to workaround?
Thanks

**Comment by ashishdhingra** [comment]
Reproducible using standard `dot net publish`.
- When using `dotnet publish --configuration "Release" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false -v d` (notice that `/p:GenerateRuntimeConfigurationFiles=true`), it's giving the below error:
```
/usr/local/share/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets(617,5): error MSB4096: The item "/Users/<user>/TestServerlessBlazor_Issue871/WebApplication1/bin/Release/net5.0/WebApplication1.runtimeconfig.json" in item list "AllPublishItemsFullPathWithTargetPath" does not define a value for metadata "RelativePath".  In order to use this metadata, either qualify it by specifying %(AllPublishItemsFullPathWithTargetPath.RelativePath), or ensure that all items in this list define a value for this metadata. [/Users/<user>/TestServerlessBlazor_Issue871/WebApplication1/WebApplication1.csproj]
```
- When using `dotnet publish --configuration "Release" /p:GenerateRuntimeConfigurationFiles=false --runtime linux-x64 --self-contained false -v d` (notice that `/p:GenerateRuntimeConfigurationFiles=false`), it's giving the below error:
```
/usr/local/share/dotnet/sdk/5.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(143,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/Users/<user>/TestServerlessBlazor_Issue871/WebApplication1/WebApplication1.csproj]
```

**Comment by genifycom** [comment]
Thanks for the update. I reached out to the DotNet team but did not get anything back on metadata RelativePath and I agree that No. 2 will block me anyway.

So with .NET SDK 5.0.202 and 
dotnet publish --configuration "Release" /p:GenerateRuntimeConfigurationFiles=false --runtime linux-x64 --self-contained true -v d
the publish succeeds, so I guess I can push this to an ECR container and deploy to Lambda from there?

**Comment by genifycom** [comment]
Ashish,

Is there anyone you know who can help me with this one?

**Comment by normj** [comment]
You can work around the issue by moving the building of the .NET code into the Dockerfile. For example here is a Dockerfile I wrote that copies the sources into the container and builds it there. 

```
FROM public.ecr.aws/lambda/dotnet:5.0 AS base

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /src
COPY ["ServerlessBlazorWasmTest/ServerlessBlazorWasmTest.csproj", "ServerlessBlazorWasmTest/"]
COPY ["WebApplication1/WebApplication1.csproj", "WebApplication1/"]

RUN dotnet restore "WebApplication1/WebApplication1.csproj"
RUN dotnet restore "ServerlessBlazorWasmTest/ServerlessBlazorWasmTest.csproj"

COPY . .

WORKDIR "/src/ServerlessBlazorWasmTest"
RUN dotnet build "ServerlessBlazorWasmTest.csproj" --configuration Release --output /app/build

FROM build AS publish
RUN dotnet publish "ServerlessBlazorWasmTest.csproj" \
            --configuration Release \ 
            --output /app/publish

FROM base AS final
WORKDIR /var/task
COPY --from=publish /app/publish .
```

**Note**: You need to remove the `docker-host-build-output-dir` property from the **aws-lambda-tools-defaults.json** file so that the toolkit code won't think you want it to do a .NET build before invoking the Docker build.

**Comment by genifycom** [comment]
Thanks Norm, this was enormously helpful. I am trying this approach.

**Comment by genifycom** [comment]
Do I need to provide an ENTRYPOINT override somewhere?

I am woefully inexperienced at creating DotNet Core containers.

**Comment by genifycom** [comment]
The lambda built complains as follows "dotnet exec needs a managed .dll or .exe extension. The application specified was '/var/task/BlazorDebugProxy/BrowserDebugHost.runtimeconfig.json'"

Can you advise what I am missing in the Dockerfile?
