### ISSUE TITLE
What's the Leading Text when I create a Scope?  e.g. "[40m[32minfo[39m[22m[49m: "

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-lambda-dotnet#872]
When I create a scope (logger.CreateScope("Xyz")),  I get something like:

[40m[32minfo[39m[22m[49m: BubbleBoy.WebApi.Controllers.Parts.EntityControllerBase[0]

## The Question
What's the "[40m[32minfo[39m[22m[49m:" all about? 

### Environment
AWS Lambda .net core 3.1

**Comment by Kralizek** [comment]
I would say these are the codes returned when coloring the output. Try disable that with an environment variable.

**Comment by ashishdhingra** [comment]
Hi @hounddog22030,

Thanks for posting the guidance question. Please refer to existing issue https://github.com/aws/aws-logging-dotnet/issues/133 where extra log is emitted by ASP.NET middleware. Kindly let me know if it helps.

Thanks,
Ashish

**Comment by hounddog22030** [comment]
> Please refer to existing issue [aws/aws-logging-dotnet#133](https://github.com/aws/aws-logging-dotnet/issues/133) where extra log is emitted by ASP.NET middleware. Kindly let me know if it helps.

Reviewed the post.  I am concluding that I need to also configure "Logging", not just "Lambda.Logging" in order to control the chattiness and get rid of the cryptic leading text.  

I only had "Lambda.Logging" in the appsetting.json, so the other ASP.NET logging is just going to the console and ending up being written to the CloudWatch logs (probably as write and not writeline).  And, that might be the cryptic text that's showing up?

Am I on the right paths with these conclusions?

**Comment by ashishdhingra** [comment]
> > Please refer to existing issue [aws/aws-logging-dotnet#133](https://github.com/aws/aws-logging-dotnet/issues/133) where extra log is emitted by ASP.NET middleware. Kindly let me know if it helps.
> 
> Reviewed the post. I am concluding that I need to also configure "Logging", not just "Lambda.Logging" in order to control the chattiness and get rid of the cryptic leading text.
> 
> I only had "Lambda.Logging" in the appsetting.json, so the other ASP.NET logging is just going to the console and ending up being written to the CloudWatch logs (probably as write and not writeline). And, that might be the cryptic text that's showing up?
> 
> Am I on the right paths with these conclusions?

@hounddog22030 Yes, you are correct. Please try the resolution provided in the other issue. If everything works, kindly let me know if this issue could be closed.

Thanks,
Ashish

**Comment by hounddog22030** [comment]
With the below config I am still getting

`[41m[30mfail[39m[22m[49m: BubbleBoy.WebApi.Controllers.Parts.EntityControllerBase[0]`

But, at least the settings have quieted a lot of other things down.

`{
  "Logging": {
    "LogLevel": { // No provider, LogLevel applies to all the enabled providers.
      "Default": "Error",
      "Microsoft": "Error",
      "Microsoft.Hosting.Lifetime": "Error"
    },
    "Debug": { // Debug provider.
      "LogLevel": {
        "Default": "Error" // Overrides preceding LogLevel:Default setting.
      }
    },
    "Console": {
      "IncludeScopes": true,
      "LogLevel": {
        "Microsoft.AspNetCore.Mvc.Razor.Internal": "Error",
        "Microsoft.AspNetCore.Mvc.Razor.Razor": "Error",
        "Microsoft.AspNetCore.Mvc.Razor": "Error",
        "Default": "Error"
      }
    },
    "EventSource": {
      "LogLevel": {
        "Microsoft": "Error"
      }
    },
    "EventLog": {
      "LogLevel": {
        "Microsoft": "Error"
      }
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Error"
      }
    }
  },
  "Lambda.Logging": {
    "LogLevel": {
      "Default": "Error",
      "Microsoft": "Error",
      "Microsoft.EntityFrameworkCore.Database.Command": "Error"
    },
    "IncludeCategory": true,
    "IncludeLogLevel": true,
    "IncludeNewline": true,
    "IncludeException": true,
    "IncludeEventId": true,
    "IncludeScopes": true
  }
}`

**Comment by ashishdhingra** [comment]
@hounddog22030 Could you try the resolution in the other issue https://github.com/aws/aws-logging-dotnet/issues/133#issuecomment-677507176:
```
.ConfigureLogging((context, logging) =>
{
    logging.ClearProviders();
    
    // logging.AddAWSProvider(
    //                 formatter: (logLevel, state, exception) => $"[{logLevel}] {exception?.Message ?? state.ToString()}"
    //         );
    
    logging.AddLambdaLogger(context.Configuration.GetLambdaLoggerOptions());
})
```

**Comment by hounddog22030** [comment]
> @hounddog22030 Could you try the resolution in the other issue [aws/aws-logging-dotnet#133 (comment)](https://github.com/aws/aws-logging-dotnet/issues/133#issuecomment-677507176):
> 


Will do.  Give a couple of days to try it....

**Comment by hounddog22030** [comment]
> @hounddog22030 Could you try the resolution in the other issue [aws/aws-logging-dotnet#133 (comment)](https://github.com/aws/aws-logging-dotnet/issues/133#issuecomment-677507176)

I think that did it.  Thanks so much!
