### ISSUE TITLE
Code design limitations with APIGatewayProxyResponse and APIGatewayProxyRequest

### ISSUE THREAD

**Issue by CyborTronik** [aws/aws-lambda-dotnet#874]
Unable to use JSON requests natively with `APIGatewayProxyRequest` and `APIGatewayProxyResponse` because of  
`public string Body { get; set; }`. You can do manual serialization, which makes hard to read/debug a serialization of JSON in a string value within JSON object.
The suggested solution is to make request/response classes generic and `public T Body { get; set; }`. In this way whatever you request or send should be serialized to JSON by default behavior of Lambda framework.

**Comment by bschaatsbergen** [comment]
It would indeed be nice if we can deserialize the entire request into a strongly typed object instead of having to build this object up everytime.

**Comment by normj** [comment]
This is the design of API Gateway to return the response back to the service in this format. From Lambda and this class point of view we can't change the behavior of API Gateway.
