### ISSUE TITLE
Every time I try to download Citrix I get this error message.  "Could not load file or assembly Newtonsoft.Json Version 12.0.0.0 Culture - neutral

### ISSUE THREAD

**Issue by SarasotaMom** [aws/aws-lambda-dotnet#875]
### Environment

* Build Version: 
* OS Info: 
* Build Environment: 
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @SarasotaMom,

Good morning.

Please share the Lambda logic/design and sample code (including the `.csproj` file) which you are using to download Citrix application. The error states that the Newtonsoft.Json assembly is missing, kindly verify if this is a dependency and include it in your Lambda project if that is the case.

Thanks,
Ashish
