### ISSUE TITLE
AWS .NET Mock Lambda Test Tool - CDK Support

### ISSUE THREAD

**Issue by george2seven** [aws/aws-lambda-dotnet#878]
## The Question
Hello, 

I would like to ask if the AWS .NET Mock Lambda Test Tool support as a template input (aws-lambda-tools-defaults.json) cloudformation template generated by CDK.  

### Environment

* Build Version: .net core 3.1
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @george2seven,

Good morning.

Thanks for posting guidance question. Based on the logic at https://github.com/aws/aws-lambda-dotnet/blob/00009c7d4fb4fb406c355a99d11d142718ba4374/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/TestToolStartup.cs#L89, the Lambda Test Tool appears to use the config file `aws-lambda-tools-defaults.json` if UI is used. I'm not sure what exact configuration you are looking for to be used, but looking at the code [Utils.SearchForConfigFiles()] has the logic for finding the config files based on available function handlers. Hope this provides some guidance.

Thanks,
Ashish

**Comment by george2seven** [comment]
Hello Ashish,

Thanks for your answer.

The mockup tool detects the aws-lambda-tools-defaults.json file just fine (and indeed we use UI).  However, inside that file, there is a parameter called "template" and so far since we were using the serverless framework by point this parameter to that file we were able to have our functions loaded in the UI.  When we switched to CDK and we generated a template.yaml from CDK the UI through the ...defaults.json file is not able to load the functions to the UI.

Is there support for the mockup tool to work with the CDK-generated file that contains a list of the Lambda handlers?

Thanks
George

**Comment by ashishdhingra** [comment]
> Hello Ashish,
> 
> Thanks for your answer.
> 
> The mockup tool detects the aws-lambda-tools-defaults.json file just fine (and indeed we use UI). However, inside that file, there is a parameter called "template" and so far since we were using the serverless framework by point this parameter to that file we were able to have our functions loaded in the UI. When we switched to CDK and we generated a template.yaml from CDK the UI through the ...defaults.json file is not able to load the functions to the UI.
> 
> Is there support for the mockup tool to work with the CDK-generated file that contains a list of the Lambda handlers?
> 
> Thanks
> George

Hi @george2seven,

The logic in [Utils.SearchForConfigFiles()] appears to look for template defined in JSON file(s) if handler could not be determined. The template file, if exists, if loaded using [LambdaDefaultsConfigFileParser.LoadFromFile(LambdaConfigFile)](https://github.com/aws/aws-lambda-dotnet/blob/00009c7d4fb4fb406c355a99d11d142718ba4374/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/Runtime/LambdaDefaultsConfigFileParser.cs#L34). This class has a documentation comment `This class handles getting the configuration information from aws-lambda-tools-defaults.json file and possibly a CloudFormation template. YAML CloudFormation templates aren't supported yet.`. So looks like YAML templates are not supported in Lambda Test Tool. Hope this helps.

Thanks,
Ashish

**Comment by george2seven** [comment]
Hello Ashish,

Indeed when we generate the template by CDK (synth) with the --json parameter is recognized by the mockup tool and we can see the functions list in the UI

One suggestion would be for this to maybe be included in the documentation as a tip for others in a similar predicament to not to have to go through comments in the code to find out what is and what isn't supported

Thanks again for the support
George
