### ISSUE TITLE
Is there a ScheduledEvent for lambdas to be triggered by CloudWatch Schedule Event?

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#88]
Hello AWS,

I am trying to have a lambda function to be triggered by the CloudWatch Schedule Event, but I haven't find any Event class for the lambda handler to use. Is there one or should I just use `object` for now instead (or writing my own one).

Thanks.

**Comment by PavelSafronov** [comment]
There currently isn't a CloudWatch Schedule Event in this library, but you can define your own class and use it until then.

**Comment by Kralizek** [comment]
@MZhoume I used this class

```csharp
    public class ScheduledEvent
    {
        public string Account { get; set; }

        public string Region { get; set; }

        [JsonProperty("detail-type")]
        public string DetailType { get; set; }

        public string Source { get; set; }

        public DateTimeOffset Time { get; set; }

        public Guid Id { get; set; }

        public IReadOnlyList<string> Resources { get; set; }
    }
```

It doesn't map all the properties.

**Comment by MZhoume** [comment]
@PavelSafronov Sounds good. Would love to see it come soon.

**Comment by MZhoume** [comment]
@Kralizek Yup, thanks so much for sharing your class. The event itself does not matter that much as long as it got my lambda do things.

**Comment by PavelSafronov** [comment]
@MZhoume if the event data does not matter to you, your lambda doesn't have to have any inputs at all, and that will work.

**Comment by MZhoume** [comment]
@PavelSafronov Yep, that is what I have been doing, set the input type to be `object` and just ignore it altogether.

**Comment by PavelSafronov** [comment]
I meant that you can have a zero-parameter function like this:
```
public void FunctionHandler()
```
or this if you need `ILambdaContext`
```
public void FunctionHandler(ILambdaContext context)
```

**Comment by MZhoume** [comment]
@PavelSafronov Wow I didn't know that. Would definitely try it. Thanks for sharing. ;)

Can I ignore the context if not needed?

```cs
// like this
public void FunctionHandler(string input)
```

**Comment by PavelSafronov** [comment]
Yes, you can ignore both the input and the context if you do not need either.

**Comment by MZhoume** [comment]
@PavelSafronov Sweet! Thanks again for the amazing tool
