### ISSUE TITLE
Debug Lambda from workstation including querying RDS Postgres Database from Lambda on workstation

### ISSUE THREAD

**Issue by mikebama** [aws/aws-lambda-dotnet#883]
I am requesting the proper procedure to be able to connect to a RDS Postgres database from development workstation debug session using Visual Studio 2019 "AWS .NET Core 2.1 Mock Lambda Test Tool" and Using .NET core 2.1 to RDS Postgres database.  The Lambda is able to connect to the RDS Postgres database when published to AWS but I am unable to connect to a RDS Postgres database from development workstation debug session.  OS Info: Windows 10

**Comment by ashishdhingra** [comment]
Hi @mikebama.

Good morning.

Thanks for posting guidance question. When you debug Lambda locally using Mock Lambda Test Tool, it executes locally on your machine. For accessing RDS Postgres database from your machine, you need to add appropriate rules to your VPC. For more details, refer the following articles/documentation:
- [Connecting to an Amazon RDS DB instance](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_CommonTasks.Connect.html)
- [Troubleshooting connections to your PostgreSQL instance](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToPostgreSQLInstance.html)

Hope this helps.

Thanks,
Ashish
