### ISSUE TITLE
ApiGatewayLambdaFunction/APIGatewayHttpApiV2ProxyFunction returns status code 200 instead of 500 in case of exception

### ISSUE THREAD

**Issue by akurin** [aws/aws-lambda-dotnet#884]
## Description
Lambda functions created using Amazon.Lambda.AspNetCoreServer return incorrect status code if an exception is thrown. Instead of expected status code 500, status code 200 is returned. 

## Reproduction Steps
The tests for the issue described already exist. Just run [TestCallingWebAPI.TestDefaultResponseErrorCode](https://github.com/aws/aws-lambda-dotnet/blob/00009c7d4fb4fb406c355a99d11d142718ba4374/Libraries/test/Amazon.Lambda.AspNetCoreServer.Test/TestCallingWebAPI.cs#L126) or [TestApiGatewayHttpApiV2Calls.TestDefaultResponseErrorCode](https://github.com/aws/aws-lambda-dotnet/blob/00009c7d4fb4fb406c355a99d11d142718ba4374/Libraries/test/Amazon.Lambda.AspNetCoreServer.Test/TestApiGatewayHttpApiV2Calls.cs#L110).

### Environment
* Build Version: Amazon.Lambda.AspNetCoreServer 6.0.2
* OS Info: Fedora Linux 33
* Build Environment: dotnet cli
* Targeted .NET Platform: 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

I believe the issue was introduced in f8b4df5521d19bc53ade32432f977e7d77e1755e. It is also troubling that this code made it into the master branch at a time when the tests did not pass.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible using test [TestCallingWebAPI.TestDefaultResponseErrorCode](https://github.com/aws/aws-lambda-dotnet/blob/00009c7d4fb4fb406c355a99d11d142718ba4374/Libraries/test/Amazon.Lambda.AspNetCoreServer.Test/TestCallingWebAPI.cs#L126)

**Comment by normj** [comment]
Thanks for reporting the issue and sorry for it happening. I have a PR to get this fixed. https://github.com/aws/aws-lambda-dotnet/pull/891

You are correct about the tests. I'm also investigate to see what is going on with our build job that it is not failing our builds due to test failures.

**Comment by normj** [comment]
Version 6.0.3 of Amazon.Lambda.AspNetCoreServer was released that fixes this issue.
