### ISSUE TITLE
Development workstation debug session configure IHostingEnvironment using Visual Studio 2019 "AWS .NET Core 2.1 Mock Lambda Test Tool" and Using .NET core 2.1

### ISSUE THREAD

**Issue by mikebama** [aws/aws-lambda-dotnet#885]
AWS Support Staff,
I am requesting some guidance on what configuration such as in startup.cs and what steps are necessary to be able to use IHostingEnvironment to be able to reference specific files using IHostingEnvironment env, env.ContentRootPath, in the Lambda project and any referenced Class libraries.   Development is being done on a windows 10 workstation.
Regards,
Mike

**Comment by ashishdhingra** [comment]
Hi @mikebama,

Good afternoon.

To create a new Lambda Serverless project, you could use templates installed by Visual Studio toolkit extension or the AWS .NET Lambda tools .NET CLI extension (you could follow instructions in Readme). Kindly note that the Mock Lambda Test tool is suitable for simple lambda functions. Serverless projects could be tested using normal Visual Studio debugging using IIS Express/IIS.

Helpful references:
- https://github.com/aws/aws-lambda-dotnet/blob/master/Docs/Learning_Resources.md. This lists the learning resources.
- https://www.jerriepelser.com/blog/aspnet-core-aws-lambda-serverless-application/
- https://aws.amazon.com/blogs/developer/running-serverless-asp-net-core-web-apis-with-amazon-lambda/

Hope this helps.

Thanks,
Ashish

**Comment by mikebama** [comment]
Hello Ashish,
Thanks for your information regarding Lambdas.  Do you have any insight into the possible use of IHostingEnvironment in a AWS .NET Core 2.1 Mock Lambda.  Is it possible?

Regards,
Mike

**Comment by ashishdhingra** [comment]
> IHostingEnvironment

@mikebama I don't think so. Mock Lambda Test tool is used to test simple lambda functions in isolated emulated environment. You may be able to test API using API Gateway AWS Proxy example request from test tool interface. But as mentioned earlier, it is not the best way to test serverless projects. More details about test tool could be found at https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool.

**Comment by mikebama** [comment]
Hello Ashish,

It said the only limitations were:
No mechanism for setting custom Environment variables.
NuGet packages that use native dependencies are not supported.

Would you mind double checking with some other people in the group?

Regards,
Mike

**Comment by ashishdhingra** [comment]
> Hello Ashish,
> 
> It said the only limitations were:
> No mechanism for setting custom Environment variables.
> NuGet packages that use native dependencies are not supported.
> 
> Would you mind double checking with some other people in the group?
> 
> Regards,
> Mike

@mikebama I pasted  https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool link just for reference. If you see the section of skipping the web interface, you would notice that there are parameters like `--function-name`, etc. The tool is used to test simple Lambda functions, refer the https://github.com/aws/aws-lambda-dotnet/issues/659#issuecomment-683983050, as discussed with developer in the past.
