### ISSUE TITLE
Issue deserialising DateTime query param in C# lambda

### ISSUE THREAD

**Issue by sandeep-eroad** [aws/aws-lambda-dotnet#890]
It looks like the lambda is not deserialising the datetime query params correctly. I have controller with GET and it takes in DateTime param and it fails to deserialise `2021-05-30T10%3A59%3A59Z`. It looks like the deserialisation is not calling `HttpUtility.UrlDecode`.

I am using netcoreapp3.1.

**Comment by ashishdhingra** [comment]
Hi @sandeep-eroad,

Good morning.

Thanks for posting the guidance question. I'm assuming you are using the Serverless application with WebAPI. Unfortunately, I'm unable to reproduce the issue using the below (minimal code):
```C#
using System;
using Microsoft.AspNetCore.Mvc;

namespace AWSServerlessAPI.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public string Get(DateTime datetime)
        {
            return datetime.ToLongDateString();
        }
    }
}
```
Running this application locally and using the GET URL http://localhost:29090/api/values?datetime=2021-05-30T10:59:59Z (for example) from web browser successfully returns the result.
![Screen Shot 2021-07-14 at 9 24 23 AM](https://user-images.githubusercontent.com/67916761/125657958-8940aaf4-5c9c-461d-a0a5-0f37a5b6dca2.png)

It run successfully when deployed to Lambda as well:
![Screen Shot 2021-07-14 at 9 29 47 AM](https://user-images.githubusercontent.com/67916761/125658487-a28de49d-0ebd-40f2-b65f-c0d80d5ab021.png)

Please share the minimal code and other details, preferably in the following format:


## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by sandeep-eroad** [comment]
Can you please encode the `datetime` query param? pass it as `2021-05-30T10%3A59%3A59Z`

**Comment by ashishdhingra** [comment]
> 2021-05-30T10%3A59%3A59Z

@sandeep-eroad `datetime` parameter works fine. BTW, I'm using `Amazon.Lambda.AspNetCoreServer` version `6.0.2`.

**Comment by sandeep-eroad** [comment]
I am on version 5.1.3, I'll try upgrading to 6.0.2 to see if it is fixed in that version.

**Comment by sandeep-eroad** [comment]
I have upgraded to latest version and I still see following error 
```
Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails'.
```

**Comment by sandeep-eroad** [comment]
The response body is
```
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|95b88615-4941b2e03b48fd05.","errors":{"endDate":["The value '2021-05-30T10%3A59%3A59Z' is not valid."],"startDate":["The value '2021-05-01T11%3A00%3A00Z' is not valid."]}}
```

**Comment by sandeep-eroad** [comment]
If I run my project locally using `dotnet run` and make this call it works fine, it worked fine even before I upgraded to latest version of `Amazon.Lambda.AspNetCoreServer`, which leads me to think it has something to do with lambda deserialisation.

**Comment by ashishdhingra** [comment]
Hi @sandeep-eroad,

Here is the minimal source code for my solution:
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.0.1" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="6.0.2" />
  </ItemGroup>
</Project>
```
**ValuesController.cs** 
```C#
using System;
using Microsoft.AspNetCore.Mvc;

namespace AWSServerlessAPI.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public string Get(DateTime datetime)
        {
            return datetime.ToLongDateString();
        }
    }
}
```
**LambdaEntryPoint.cs**
```C#
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace AWSServerlessAPI
{
    /// <summary>
    /// This class extends from APIGatewayProxyFunction which contains the method FunctionHandlerAsync which is the 
    /// actual Lambda function entry point. The Lambda handler field should be set to
    /// 
    /// AWSServerlessAPI::AWSServerlessAPI.LambdaEntryPoint::FunctionHandlerAsync
    /// </summary>
    public class LambdaEntryPoint :

        // The base class must be set to match the AWS service invoking the Lambda function. If not Amazon.Lambda.AspNetCoreServer
        // will fail to convert the incoming request correctly into a valid ASP.NET Core request.
        //
        // API Gateway REST API                         -> Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
        // API Gateway HTTP API payload version 1.0     -> Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
        // API Gateway HTTP API payload version 2.0     -> Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction
        // Application Load Balancer                    -> Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction
        // 
        // Note: When using the AWS::Serverless::Function resource with an event type of "HttpApi" then payload version 2.0
        // will be the default and you must make Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction the base class.

        Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        /// <summary>
        /// The builder has configuration, logging and Amazon API Gateway already configured. The startup class
        /// needs to be configured in this method using the UseStartup<>() method.
        /// </summary>
        /// <param name="builder"></param>
        protected override void Init(IWebHostBuilder builder)
        {
            builder
                .UseStartup<Startup>();
        }

        /// <summary>
        /// Use this override to customize the services registered with the IHostBuilder. 
        /// 
        /// It is recommended not to call ConfigureWebHostDefaults to configure the IWebHostBuilder inside this method.
        /// Instead customize the IWebHostBuilder in the Init(IWebHostBuilder) overload.
        /// </summary>
        /// <param name="builder"></param>
        protected override void Init(IHostBuilder builder)
        {
        }
    }
}
```
**LocalEntryPoint.cs**
```C#
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace AWSServerlessAPI
{
    /// <summary>
    /// The Main function can be used to run the ASP.NET Core application locally using the Kestrel webserver.
    /// </summary>
    public class LocalEntryPoint
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```
Using URL http://localhost:29090/api/values?datetime=2021-05-30T10%3A59%3A59Z from web browser works fine for me.

Could you please share your sample project to reproduce the issue?

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
> If I run my project locally using `dotnet run` and make this call it works fine, it worked fine even before I upgraded to latest version of `Amazon.Lambda.AspNetCoreServer`, which leads me to think it has something to do with lambda deserialisation.

@sandeep-eroad I ran this project locally and also deployed it to Lambda environment, it works fine. Please share your sample project to reproduce the issue. Not sure if you are using old Lambda serializer.

**Comment by sandeep-eroad** [comment]
I am trying to invoke the lambda function locally but not sure what I am doing wrong as I can't find a lot of information on the web about my error.

**Comment by sandeep-eroad** [comment]
Is there proper documentation on how to invoke AwsServerless endpoints somewhere?

**Comment by sandeep-eroad** [comment]
Thanks for the sample code, mine is very similar to what you have.

**Comment by sandeep-eroad** [comment]
These are the packages we are using
```
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.1.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.5.1" />
```

**Comment by sandeep-eroad** [comment]
I have managed to invoke the lambda locally using the Lambda test tool and get same error.
![Screen Shot 2021-07-15 at 1 50 28 PM](https://user-images.githubusercontent.com/48039040/125715635-5af4923d-395c-4234-b4cc-418578e795ea.png)

**Comment by ashishdhingra** [comment]
> I have managed to invoke the lambda locally using the Lambda test tool and get same error.
> ![Screen Shot 2021-07-15 at 1 50 28 PM](https://user-images.githubusercontent.com/48039040/125715635-5af4923d-395c-4234-b4cc-418578e795ea.png)

Hi @sandeep-eroad,

Good morning.

Since the issue is not reproducible at our end, request you to share sample code solution to troubleshoot the issue. I do not think you need to URL encode parameter, web browser encodes it automatically.

Thanks,
Ashish

**Comment by sandeep-eroad** [comment]
Hi @ashishdhingra, 

I'll make a sample app for you, but the issue is not with encoding, it's with the datetime strings not being decoding. I think somewhere `HttpUtility.UrlDecode` isn't called.

**Comment by sandeep-eroad** [comment]
Hi @ashishdhingra , 

Figured out what was causing it :-). My controller was decorated with attribute `[ApiController]` which caused this issue. Removing it fixes it.

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra , 
> 
> 
> 
> Figured out what was causing it :-). My controller was decorated with attribute `[ApiController]` which caused this issue. Removing it fixes it. 

@sandeep-eroad Thanks for sharing your findings.
