### ISSUE TITLE
LambdaBootstrap hiding initialization exceptions - Custom Runtime

### ISSUE THREAD

**Issue by michelmob** [aws/aws-lambda-dotnet#892]
## Description
When using LambdaBootstrap the method RunAsync is hiding exceptions and we can´t get details if we do not include a try-catch block. 
I lost some hours trying to understand why even adding a try-catch block at the Main function but the exception was not getting there.

## Reproduction Steps
Create a new Lambda using Custom Runtime, and throws an exception inside your FinctionHandler.
```C#
   public class Function
    {      
        private static async Task Main(string[] args)
        {
            Func<object, ILambdaContext, Task<string>> func = FunctionHandler;
            using var handlerWrapper = HandlerWrapper.GetHandlerWrapper(func, new DefaultLambdaJsonSerializer());
            var bootstrap = new LambdaBootstrap(handlerWrapper);
            await bootstrap.RunAsync();     
        }

        public static async Task<string> FunctionHandler(object input, ILambdaContext context)
        { 
            throw new Exception("First exception");          

            //return await Task.FromResult("testing".ToUpper());
        }
    }
```

### Logs
If you test it, you can see that the exceptions were posted as a result, but if you open the cloud watch logs, nothing will be there, except the start and end of the request.

### Environment
Lambda environment, AWS.

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

  I've changed the method InvokeOnceAsync to re-throw the exception.

```C#
    private async Task ReportSuccessAsync(InvocationResponse response, InvocationRequest invocation, CancellationToken cancellationToken = default)
        {
            try
            {
                await Client.SendResponseAsync(invocation.LambdaContext.AwsRequestId, response?.OutputStream, cancellationToken);
            }
            finally
            {
                if (response != null && response.DisposeOutputStream)
                {
                    response.OutputStream?.Dispose();
                }
            }
        }

        internal async Task InvokeOnceAsync(CancellationToken cancellationToken = default)
        {
            using (var invocation = await Client.GetNextInvocationAsync(cancellationToken))
            {
                try
                {
                   var response = await _handler(invocation);
                    await ReportSuccessAsync(response, invocation, cancellationToken);
                }
                catch (Exception exception)
                {
                    await Client.ReportInvocationErrorAsync(invocation.LambdaContext.AwsRequestId, exception,cancellationToken);
                    throw;
                }
            }
        }
```

Thanks 

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible. Normal Lambda functions with specified runtime log exceptions properly. However, custom runtime functions hide the exception.

**Comment by plaisted** [comment]
I'm not seeing any errors (initialization or unhandled exceptions) show up in CloudWatch logs when using the AWS provided container image (public.ecr.aws/lambda/dotnet:5.0). I assume this is the same issue?
