### ISSUE TITLE
Amazon.Lambda.TestTool.WebTester21 vs Amazon.Lambda.TestTool.BlazorTester

### ISSUE THREAD

**Issue by michaelsync** [aws/aws-lambda-dotnet#895]
What are the differences between Amazon.Lambda.TestTool.WebTester21 and Amazon.Lambda.TestTool.BlazorTester? 

I found those projects in this folder https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool/src . I've googled it and I couldn't find any doc. 

I found this code in this file https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/src/Amazon.Lambda.TestTool/TestToolStartup.cs

Is it trying to load the WebTester21 or  BlazorTester based on the framework? 

```
 if (lambdaAssemblyDirectory.EndsWith("Amazon.Lambda.TestTool.WebTester21"))
                {
                    lambdaAssemblyDirectory = Path.Combine(lambdaAssemblyDirectory, $"../../tests/LambdaFunctions/netcore21/S3EventFunction/bin/Debug/{targetFramework}");
                }
                else if (lambdaAssemblyDirectory.EndsWith("Amazon.Lambda.TestTool.WebTester31"))
                {
                    lambdaAssemblyDirectory = Path.Combine(lambdaAssemblyDirectory, $"../../tests/LambdaFunctions/netcore31/S3EventFunction/bin/Debug/{targetFramework}");
                }

**Comment by ashishdhingra** [comment]
Hi @michaelsync,

Good morning. 

There is a small note in https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider section, which recommends to use BlazorTester DLL if using .NET Core Mock Lambda Test Tool 3.1 version **0.11.0**. Looks like starting from the commit https://github.com/aws/aws-lambda-dotnet/commit/71e9439b67d81fe24e27d4aaebf59bc31fa5f061#diff-8bec091626d65cfa3d34fc0857b0c7d131acb1dfd62f6ad914f78f930f7f4ecc for .NET Core Mock Lambda Test Tool 3.1 version **0.11.0**, the `Amazon.Lambda.TestTool.WebTester31` was renamed to `Amazon.Lambda.TestTool.BlazorTester`. This added support for .NET 5.

Hope this helps.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Closing the issue since relevant guidance has been provided. Feel free to open new one in case there are more questions.
