### ISSUE TITLE
Persisting wizard settings to the default file

### ISSUE THREAD

**Issue by betimd** [aws/aws-lambda-dotnet#9]
Would be very helpful to persist wizard settings to the defaults file.
When you redeploy the function it's quick and easy just click finish.

**Comment by normj** [comment]
I pushed out version 1.11.2 which has a new checkbox in the deployment wizard to save the settings to the aws-lambda-tools-defaults.json.

Also if you are using the the dotnet CLI integration provided with Amazon.Lambda.Tools. Version 1.1.0-preview1 which was released today it has the new command line arguments **--config-file** and **--persist-config-file**. They can be used to specify alternative config files and persist the values just like the wizard does.
