### ISSUE TITLE
How to allow binary response from AspNetCoreServer with API Gateway

### ISSUE THREAD

**Issue by sebastienlabine** [aws/aws-lambda-dotnet#901]
Hi,

I am trying to send down files through my lambda application, but I just can't.

I followed the guide [here](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md#supporting-binary-response-content) and the [official AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html), but still can't get my files from my api.

Here's the steps I took:

1. I didn't add any _RegisterResponseContentEncodingForContentType_ because all my media types were already supported.)
2. I Set binary media types for the API (Step 1 of the [official AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html)
3. Skipped step 2 as it didn't apply (?)
4. Redeployed the api gateway

My code is fairy simple. 
```c#
var file = await _documentService.GetFileAsync(user, documentId, cancellationToken);
if (file == null)
{
    return NotFound();
}
MemoryStream stream = new();
await file.ResponseStream.CopyToAsync(stream, cancellationToken);
var cd = new System.Net.Mime.ContentDisposition
{
    FileName = document.Name,
    Inline = true,
};
Response.Headers.Add("Content-Disposition", cd.ToString());
return File(stream.ToArray(), file.Headers.ContentType);
```

Is there anything i'm missing?

**Comment by ashishdhingra** [comment]
Hi @sebastienlabine,

Good afternoon.

As you also pointed out following all the steps mentioned at the link https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.AspNetCoreServer/README.md#supporting-binary-response-content provides some information about supporting binary content, so file downloads should work.

Please share the following:
- MIME type of files which your Lambda application is sending as download.
- Serverless project template bludeprint (WebAPI or Web application)
- Package versions (from `.csproj` file)
- .NET Core version
 
I can try to reproduce the issue at my end. 

Thanks,
Ashish
