### ISSUE TITLE
#Requires 3rd party module

### ISSUE THREAD

**Issue by u362eboi** [aws/aws-lambda-dotnet#902]
I'm looking at the possibility to migrate maintenance scripts in powershell from EC2 to Lambda.

One of the use case we have use a 3rd party module: dbatools

My question is the following: is it possible to use 3rd party modules?

I've tried the following line but every time I execute the lambda function I get an error:

`#Requires -Modules @{ModuleName='dbatools';ModuleVersion='1.1.11'}`

And the error:

```
{
  "errorType": "LambdaException",
  "errorMessage": "An exception was thrown when the constructor for type 'debug.Bootstrap' was invoked. Check inner exception for more details.",
  "cause": {
    "errorType": "TargetInvocationException",
    "errorMessage": "Exception has been thrown by the target of an invocation.",
    "stackTrace": [
      "at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)",
      "at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)",
      "at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)",
      "at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)",
      "at System.Activator.CreateInstance(Type type)"
    ],
    "cause": {
      "errorType": "ParameterBindingValidationException",
      "errorMessage": "Cannot bind argument to parameter 'Path' because it is null.",
      "stackTrace": [
        "at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost..ctor()",
        "at Amazon.Lambda.PowerShellHost.PowerShellFunctionHost..ctor(String powerShellScriptFileName)",
        "at debug.Bootstrap..ctor() in C:\\Users\\demo\\AppData\\Local\\Temp\\debug\\Bootstrap.cs:line 9"
      ]
    }
  }
}
```

### Environment

```
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS > Get-InstalledModule | select name, version | sort name

Name                              Version
----                              -------
AWS.Tools.Common                  4.1.14.0
AWS.Tools.Installer               1.0.2.0
AWS.Tools.SimpleSystemsManagement 4.1.14.0
AWSLambdaPSCore                   2.1.0.0
dbatools                          1.1.11
```

**Comment by ashishdhingra** [comment]
Hi @u362eboi,

Good afternoon.

Thanks for using guidance question.

You should be able to use the 3rd party modules in your PowerShell script. Are you using PowerShell Lambda to create and publish Lambda functions. Refer the following articles:
- [Building Lambda functions with PowerShell](https://docs.aws.amazon.com/lambda/latest/dg/lambda-powershell.html)
- Refer section `AWS Lambda functions` at https://aws.amazon.com/blogs/developer/aws-tools-for-powershell-is-now-generally-available-with-version-4-0/.

You should also ensure that any dependent modules required by your 3rd party modules are also installed.

The error indicated above is related to `dbatools`. I'm unsure about your use case and logic, but I see similar issues reported in [sqlcollaborative/dbatools](https://github.com/sqlcollaborative/dbatools) repository:
- https://github.com/sqlcollaborative/dbatools/issues/5365
- https://github.com/sqlcollaborative/dbatools/issues/4965

Thanks,
Ashish

**Comment by u362eboi** [comment]
Thank you Ashish for those two post. I went trough them. 

The first one was hinting at missing environment variables. It is indeed the case in lambda. Also there is a note that the function need to write work files. So I created the env variable for $Env:APPDATA and $Env:LOCALAPPDATA that where reference in the post and point it to /tmp. I still had the same error.

I then took a look at the configuration.ps1 file that was reference in the post. I noticed that it was looking for $Env:XDG_CONFIG_HOME. That one also doesn't exist in lambda so I created it pointing to /tmp. Again, without success.

One other point that I find disturbing is to find references to my PC environment in the error messages from Lambda.
`"at debug.Bootstrap..ctor() in C:\\Users\\demo\\AppData\\Local\\Temp\\debug\\Bootstrap.cs:line 9"`
So I went to my linux env and tried to generate the same package and noticed the same pattern.
`"at debug.Bootstrap..ctor() in /tmp/debug/Bootstrap.cs:line 9"`
I have no knowledge on how the package is generate but I don't think there should be any references left to my PC once it's upload to Lambda. With my limited knowledge of Powershell and .Net, I have no idea where to look at.

**Comment by ashishdhingra** [comment]
@u362eboi Could you please share your sample script which might be causing the error? Kindly make sure to remove any sensitive information.

**Comment by u362eboi** [comment]
@ashishdhingra You don't need anything else then the following line:
`#Requires -Modules @{ModuleName='dbatools';ModuleVersion='1.1.11'}`
At this point I'm not even trying to use any command in it.
[debug.ps1.txt](https://github.com/aws/aws-lambda-dotnet/files/7015680/debug.ps1.txt)

To build the package I use the following commands
`Install-Module dbatools -scope currentuser`
`New-AWSPowerShellLambdaPackage -ScriptPath .\debug.ps1 -OutputPackage debug.zip`

I then push to lambda making sure I have the correct LambdaHandler and Enviroment Variable for powershell trough the GUI.
Since it does generate a large zip file, it'll need more then the default 15 sec timeout. I've set mine to 30 sec.

**Comment by ashishdhingra** [comment]
> New-AWSPowerShellLambdaPackage -ScriptPath .\debug.ps1 -OutputPackage debug.zip

@u362eboi I was able to reproduce the issue when using the `dbatools` module. However, for testing purposes, using another 3rd party module `RandomPasswordGenerator` executes the following script successfully:
```PowerShell
#Requires -Modules @{ModuleName='RandomPasswordGenerator';ModuleVersion='1.0.1'}

# Uncomment to send the input event to CloudWatch Logs
Write-Host (ConvertTo-Json -InputObject $LambdaInput -Compress -Depth 5)
$randpass = Get-RandomPassword
Write-Host (ConvertTo-Json -InputObject $randpass -Compress -Depth 5)
$PSVersionTable
```
This generates the following output in CloudWatch logs:
```
START RequestId: a800ab3a-a4e3-4db1-9f89-e9503f3b0ff9 Version: $LATEST
Importing module ./Modules/RandomPasswordGenerator/1.0.1/RandomPasswordGenerator.psd1
[Information] - {"key1":"value1","key2":"value2","key3":"value3"}
[Information] - {"PasswordValue":"w]81cr9Y^+7p4XO","PasswordId":"Pass1"}
END RequestId: a800ab3a-a4e3-4db1-9f89-e9503f3b0ff9
REPORT RequestId: a800ab3a-a4e3-4db1-9f89-e9503f3b0ff9	Duration: 1800.15 ms	Billed Duration: 1801 ms	Memory Size: 512 MB	Max Memory Used: 147 MB	Init Duration: 1747.54 ms	
```
There is definitely some issue with the `dbatools` when using with PowerShell Lambda. Kindly note that Lambda runs on minimal `linux-x64` environment, I'm not sure if `dbatools` has any compatibility issues with this environment.

I would suggest you open an issue in [sqlcollaborative/dbatools](https://github.com/sqlcollaborative/dbatools) repository.

Thanks,
Ashish

**Comment by u362eboi** [comment]
@ashishdhingra I'll try to open an issue on the dbatools side. I'm also looking at other alternatives like a powershell container on ECS. Thanks for your help.
