### ISSUE TITLE
await Task does not work as expected

### ISSUE THREAD

**Issue by MZhoume** [aws/aws-lambda-dotnet#91]
Hello AWS,

I am working with async calls using in lambda handler. However, the program does not work as expected. Error: `"errorMessage": "RequestId: 991fc1fc-1558-11e7-bd03-3bb3c9d9b1b0 Process exited before completing request"`

So I did some logging, it seems that the program ran the first line of code, but stopped when running the second one. Is there anything wrong with the way I am writing the async call?

Thanks!

```cs
public async Task FunctionHandler()
{
    var sqsClient = new AmazonSQSClient();
    var sqsResponse = await sqsClient.ReceiveMessageAsync(QueueUrl);

    foreach (var message in sqsResponse.Messages)
    {
              // do something
    }
}
```

**Comment by PavelSafronov** [comment]
It's possible the client was unable to reach the internet. Are you executing this in a VPC?

You can try the below function to test the internet connection. If the function can access the internet, it will succeed without output. If the internet is not reachable, you'll see an error reported.
```
public async Task Function()
{
    using (var client = new HttpClient())
    {
        client.Timeout = TimeSpan.FromSeconds(10);
        await client.GetStringAsync("https://httpbin.org/delay/5");
    }
}
```

**Comment by MZhoume** [comment]
@PavelSafronov It generates the same error as before. :(

**Comment by PavelSafronov** [comment]
Hmm, that is very strange. Can you create a project with the function I supplied, verify that this produces the `"Process exited before completing request"` error, and share that project? This will be the fastest way to diagnose what's happening and why you're encountering this problem.

**Comment by slang25** [comment]
Could it be that receiving messages from SQS can wait for up to 20 seconds, and the lambda timeout defaults to 3?

**Comment by PavelSafronov** [comment]
Are you receiving the `"Process exited before completing request"` error after only 3 seconds?
Lambda's [maximum execution duration per request](http://docs.aws.amazon.com/lambda/latest/dg/limits.html) is 5 minutes, so it's unlikely that this is what you're experiencing.

**Comment by slang25** [comment]
The max is 5 minutes, but the default is 3 seconds, `ReceiveMessageAsync` will poll for 20 seconds with an empty queue, it seems very likely that this is the issue here.

**Comment by slang25** [comment]
The default timeout is 3 seconds, you can change this to 5 minutes. `ReceiveMessageAsync` will poll for 20 seconds with an empty queue.

I would expect this to return "Process exited before completing request" in this scenario, so I'd say all signs point to this, of course I could be wrong.

**Comment by PavelSafronov** [comment]
The default is 30 seconds, and can be changed to 5 minutes, but Lambda responds with a different error in that case:
`{"errorMessage":"2017-03-31T20:06:14.621Z 12345678-9012-3456-7890-123456789012 Task timed out after 30.00 seconds"}`

It doesn't look like the timeout is the issue here, though it probably won't hurt to increase it if you know ahead of time that the execution may take as long as 20 seconds.

Can you try creating the standalone project I suggested [earlier](https://github.com/aws/aws-lambda-dotnet/issues/91#issuecomment-290614316)?

**Comment by MZhoume** [comment]
@PavelSafronov it is kind of hard to create that demo project. 

So the thing is, I have a shared project for multiple projects. If the lambda project has reference to that shared project, it will generate that error (only for the one with `async Task` return type, not others). If the lambda project does not have the reference, it will have the `Process exited before completing request` error. 

Is there any way that we can get the detailed running log? Maybe there is an exception thrown somewhere.

**Comment by MZhoume** [comment]
@PavelSafronov I tried to wrap the entire async call in a `Task.Factory.StartNew(async () => {}).Wait();` so that it will become a synced call. However, it runs all the statements before the `await` call, and just stopped right there (no error this time, just stopped running). Any idea how to debug this?

**Comment by PavelSafronov** [comment]
Creating the stand-alone project is what I would recommend. This would isolate the exact nature of the problem and would allow us to provide either a fix or a workaround. WIthout a clear repro case we aren't able to identify what's causing this issue, so there really isn't much we can do about this.

**Comment by MZhoume** [comment]
@PavelSafronov So I have successfully created a demo function that will generate such error. It turns out the program can be super easy. The real problem seems to be the reference to some dlls (even if you don't use them).

Please have a look at it: https://github.com/MZhoume/DemoFunction/tree/master/DemoFunction

**Comment by MZhoume** [comment]
@PavelSafronov also the startup time is around 5s... is there anything wrong with it?

```
START RequestId: a0a45d79-18ab-11e7-a367-eb6aad656cd3 Version: $LATEST
END RequestId: a0a45d79-18ab-11e7-a367-eb6aad656cd3
REPORT RequestId: a0a45d79-18ab-11e7-a367-eb6aad656cd3	Duration: 4519.83 ms	Billed Duration: 4600 ms 	Memory Size: 256 MB	Max Memory Used: 51 MB	
RequestId: a0a45d79-18ab-11e7-a367-eb6aad656cd3 Process exited before completing request
```

**Comment by PavelSafronov** [comment]
Thanks for the repo.
The underlying issue here is that both jose-jwt 2.2 and System.Data.Common 4.3 target .NET Core 1.1, while Lambda currently only supports .NET Core 1.0. I was able to get the repo working by downgrading dependencies to jose-jwl 2.1 and System.Data.Common 4.1.

Immediately after a Lambda function is updated, a function invocation will take longer due to cold-start, where Lambda first needs to setup the container containing your function. This is expected.

**Comment by MZhoume** [comment]
@PavelSafronov Thanks for the feedback. I will keep an eye on the version next time.

Where did you get the targeting version of the packages? Nuget?

**Comment by PavelSafronov** [comment]
The versions are specified in the project.json. So in your repro repo, [this is line where you reference "System.Data.Common": "4.3.0"](https://github.com/MZhoume/DemoFunction/blob/master/DemoFunction/project.json#L17), and for jose-wt I verified [that package's info in NuGet](https://www.nuget.org/packages/jose-jwt).

**Comment by MZhoume** [comment]
@PavelSafronov but let's say for `jose-jwt`, the dependent version of .net standard is `.NETStandard 1.4`, for `jose-jwt` version 2.1.0 (which is targeting .net core 1.0.

**Comment by PavelSafronov** [comment]
[jose-jwt](https://www.nuget.org/packages/jose-jwt/2.2.0) has dependencies on a number of 4.3 packages (such as `System.IO.Compression (>= 4.3.0)`), and that's the clear sign that this depends on 1.1, which Lambda does not support.

**Comment by MZhoume** [comment]
@PavelSafronov make sense. 

Is there a way for lambda to display this kind of runtime error to the user so it will be much faster for the user to determine which package to downgrade?

**Comment by PavelSafronov** [comment]
We're looking into this, but I'm not sure when this functionality will be available.

**Comment by MZhoume** [comment]
@PavelSafronov Thanks for your help!

**Comment by ibuchan72390** [comment]
This thread just absolutely saved me. I've been dealing with this issue intermittently for about a week now and have not been able to make the connection.  I thought it was something specifically related to the use of an async method.  I never made the connection between the Framework disparity in my downstream referenced project that uses System.Data.Common 4.3.0.
