### ISSUE TITLE
API Gateway Proxy: headers are case sensitive

### ISSUE THREAD

**Issue by Mikilll94** [aws/aws-lambda-dotnet#915]
## Description

HTTP headers are case insensitive according to the HTTP spec. However, the only way to access request headers is:
```cs
request.Headers["My-header"];
```
which is case sensitive.

## Reproduction Steps

This code below should return the same header value:

```cs
var header1 = request.Headers["My-header"];
var header2 = request.Headers["My-hEAder"];
var header3 = request.Headers["my-headEr"];
```

but it's returning different values because header name is case sensitive. You can easily check this code by yourself.

### Logs
No logs are necessary.

### Environment

* Build Version: Amazon.Lambda.Core 2.0.0, Amazon.Lambda.APIGatewayEvents 2.4.0
* OS Info: Windows 10
* Build Environment: VSCode + Terminal `dotnet`
* Targeted .NET Platform: netcoreapp3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Similar issue https://github.com/aws/aws-lambda-go/issues/117 reported for Go.

**Comment by ashishdhingra** [comment]
Hi @Mikilll94,

Good afternoon.

Thanks for reporting the issue. Could you please share your use case and sample code to reproduce the issue? This would help us investigate further.

Thanks,
Ashish

**Comment by Mikilll94** [comment]
Hello, @ashishdhingra 

The sample code is as follows:
```cs
    public APIGatewayProxyResponse MyFunction(
        APIGatewayProxyRequest request,
        ILambdaContext context)
    {
      var header1 = request.Headers["My-header"];
      var header2 = request.Headers["My-hEAder"];
      var header3 = request.Headers["my-headEr"];

      context.Logger.LogLine("Header 1 " + header1);
      context.Logger.LogLine("Header 2 " + header2);
      context.Logger.LogLine("Header 3 " + header3);

      return new APIGatewayProxyResponse
      {
          StatusCode = 200,
      };
    }
```

Just send an HTTP request with "My header" header which will trigger MyFunction function from API Gateway. Then check the Cloudwatch logs. This line `var header2 = request.Headers["My-hEAder"];` will throw KeyNotFound exception. This should not happen because headers are case insensitive according to the HTTP spec.

**My use case:**
axios (JavaScript HTTP library) convert all headers to lowercase when sending a request https://github.com/axios/axios/issues/413

That's why I need to access HTTP headers in a case insensitive way.

**Comment by ashishdhingra** [comment]
@Mikilll94 Thanks for your response. I just came across [Amazon API Gateway important notes](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html). For the bullet point `API Gateway enacts the following restrictions and limitations when handling methods with either Lambda integration or HTTP integration`, it mentions `Header names and query parameters are processed in a case-sensitive way.`. Looks like this is a limitation from the service side where user could send 2 headers with same name, but different in case. Given this limitation, I'm not sure how this could be implemented in Lambda HLL. Hope this helps.

**Comment by mlhpdx** [comment]
This issue should be re-opened IMHO.  The given explanation is understandable, but insufficient for leaving the implementation as-is.  An updated (suffixed, or otherwise distinguishable type name that avoids breaking existing apps) could easily be introduced that implements the correct behavior.  It's simply a matter of looking at "x-foo-a" and "x-foo-A" as being the same header, and hence being multi-valued.  The instance of the Dictionary implementing those properties should then be created with the insensitive comparison option (`new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase)`).

It's problematic to leave this glaring (and surprising and frustrating) non-conformance with the specification in place.

**Comment by toddjcrane** [comment]
repinging @ashishdhingra for visibility
