### ISSUE TITLE
Missing Amazon.Lambda.TestTool.WebTester31.dll from Mac Setup

### ISSUE THREAD

**Issue by yemanasyan** [aws/aws-lambda-dotnet#916]
## Description
I'm upgrading AWS Lambda project to dotnet core 3.1. I was running the lambda locally using Rider and the test tool. I installed .net core 3.1 and then installed the test tool 3.1 as [described here](https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#installing-and-running). I went through the same steps previously for dotnet core 2.1 it worked. I still can install Amazon.Lambda.TestTool-3.1, but it misses the `Amazon.Lambda.TestTool.WebTester31.dll`. Based on instructions from [here](https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#configure-for-jetbrains-rider) I need it to be able to run it by Rider (like in the case of Amazon.Lambda.TestTool-2.1). In the screenshot you can see all the files that I have in the directory:
<img width="1333" alt="Screen Shot 2021-09-27 at 5 09 47 PM" src="https://user-images.githubusercontent.com/4953775/134992159-f04fa31d-320b-4bea-ab5a-415e8df887dc.png">

Can someone update [the readme](https://github.com/aws/aws-lambda-dotnet/blob/master/Tools/LambdaTestTool/README.md#configure-for-jetbrains-rider) or add the `Amazon.Lambda.TestTool.WebTester31.dll` file?

### Environment
* OS Info: OSX Big Sur
* Build Environment: Rider
* Targeted .NET Platform:  dotnet core 3.1

**Comment by ashishdhingra** [comment]
Hi @yemanasyan,

Good morning.

Thanks for posting the question. Please refer the https://github.com/aws/aws-lambda-dotnet/issues/895#issuecomment-892878394 for the similar reported issue. There is a small note in https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider section, which recommends to use BlazorTester DLL if using .NET Core Mock Lambda Test Tool 3.1 version **0.11.0**. Looks like starting from the commit https://github.com/aws/aws-lambda-dotnet/commit/71e9439b67d81fe24e27d4aaebf59bc31fa5f061#diff-8bec091626d65cfa3d34fc0857b0c7d131acb1dfd62f6ad914f78f930f7f4ecc for .NET Core Mock Lambda Test Tool 3.1 version **0.11.0**, the `Amazon.Lambda.TestTool.WebTester31` was renamed to `Amazon.Lambda.TestTool.BlazorTester`. This added support for .NET 5.

Hope this helps.

Thanks,
Ashish

**Comment by yemanasyan** [comment]
Hi Ashish,

Thanks a lot for your reply, didn't read it carefully. Will close the bug.
