### ISSUE TITLE
Swagger documentation accessibility

### ISSUE THREAD

**Issue by olifer** [aws/aws-lambda-dotnet#92]
I have added swagger documentatin to my project and it works perfectly fine when I run it locally. However, once I try to reach it in AWS through API GW that acts as a proxy and redirects all calls to lambda, I get 403 (Forbidden). It seems like it cannot be found.
Should any special configuration be done to enable access to the swagger interface?

**Comment by PavelSafronov** [comment]
Is your question about Amazon Lambda/Amazon API Gateway functionality, or about an issue you've found with the libraries and Blueprints hosted in this repo?

**Comment by olifer** [comment]
Hi Pavel,

You could close the issue, since it has been resolved when I added CloudFront (not sure though what was wrong initially). Sorry for the disturbance.

**Comment by PavelSafronov** [comment]
No worries, glad you got this working.
