### ISSUE TITLE
Workaround: .NET Custom Runtime fails with ARM

### ISSUE THREAD

**Issue by normj** [aws/aws-lambda-dotnet#920]
# .NET Custom Runtime fails with ARM

Custom runtimes are typically used to run newer versions of .NET like .NET 5 and 6. When deploying a .NET Lambda function using Custom Runtimes with the architecture set to arm64, the Lambda function fails at runtime with the following error.

```
Cannot get symbol ucol_setMaxVariable_50 from libicui18n
Error: /lib64/libicui18n.so.50: undefined symbol: ucol_setMaxVariable_50
Aborted
```

This is due to .NET requiring version 53 and above of the native dependency `libicu` and Amazon Linux 2 has version 50. We are looking at getting the version of libicu updated in Amazon Linux 2.

To workaround this issue, you can include a newer version of libicu in your Lambda function that will unblock custom runtimes. To include libicu with your .NET Lambda function, include the following snippet in your csproj or fsproj file.

```
<ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.6" />
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
</ItemGroup>
```

**Comment by memark** [comment]
Even better would be with a conditional item group:

```
<ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
	<RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9"/>
	<PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9"/>
</ItemGroup>
```
Otherwise the application won't be runnable on other platforms, e.g. on a developer machine or any non-linux-arm64 system.

**Comment by AbbTek** [comment]
I'm trying to update our lambda project to NET Core 7. I'm including Microsoft.ICU.ICU4C.Runtime, but I'm getting the following error. 

Failed to load /var/task/libcoreclr.so, error: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /var/task/libcoreclr.so)

**Comment by martincostello** [comment]
See #1310

**Comment by ashishdhingra** [comment]
Closing the issue since the related issue https://github.com/aws/aws-lambda-dotnet/issues/1310 is now closed.
