### ISSUE TITLE
Amazon.Lambda.CloudWatchEvents.BatchEvents.Job: serialization from JSON created by AWS Batch fails 

### ISSUE THREAD

**Issue by paul-michalik** [aws/aws-lambda-dotnet#926]
## Description

De-serialization of JSON object which represents the AWS Batch job state change event created by AWS Batch integration with Amazon EventBridge fails.

## Reproduction Steps

Try to de-serialize an job state change event using any Lambda serializer based on `System.Text.Json`

```cs
        [DataTestMethod]
        [DataRow("data/events/batch-state-change-event-fully-initialized-runnable.json")]
        public void Can_Round_Trip_Serialize_Real_Batch_Event_With_Default_Serializer(string eventFilePath)
        {
            var serializer = new Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();
            using (var readableStream = new FileStream(eventFilePath, FileMode.Open, FileAccess.Read)) {
                var expected = serializer.Deserialize<Amazon.Lambda.CloudWatchEvents.BatchEvents.BatchJobStateChangeEvent>(readableStream);
                using (var stream = new MemoryStream()) {
                    serializer.Serialize(expected, stream);
                    stream.Position = 0L;
                    var actual = serializer.Deserialize<Amazon.Lambda.CloudWatchEvents.BatchEvents.BatchJobStateChangeEvent>(stream);
                    actual.Should().BeEquivalentTo(expected);
                }
            }
        }
```
where `batch-state-change-event-fully-initialized-runnable.json` is a valid JSON object generated by Amazon EventBridge, for example (only the relevant attributes shown):

```json
{
    "version": "0",
    "id": "f878d98d-342c-a4f4-b80d-31f23d495be0",
    "detail-type": "Batch Job State Change",
    "source": "aws.batch",
    "account": "123456789123",
    "time": "2021-10-07T21:55:58Z",
    "region": "eu-central-1",
    "resources": [
        "arn:aws:batch:eu-central-1:123456789123:job/94c029d8-d190-4325-8b91-cd6ef43d22a1"
    ],
    "detail": {
        "container": {
            "environment": [
                {
                    "name": "MANAGED_BY_AWS",
                    "value": "STARTED_BY_STEP_FUNCTIONS"
                }
            ]
        }
    }
}
```

### Environment

* Build Version: 
* OS Info:  AmazonLinux
* Build Environment:  SAM, terminal dotnet, build container for AmazonLinux Lambda
* Targeted .NET Platform:  .NET 5

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

The attempt to de-serialize `ContainerDetail.Environment` property of type `List<KeyValuePair<string, string>>` fails because `KeyValuePair<string,string>` requires JSON of the form `{ "key": "MyKey", "value": "MyValue" }` and not `{ "name": "MyKey", "value": "MyValue" }` as created by Amazon EventBridge. Proposal: Do not use `List<KeyValuePair<string, string>>`. Use `List<NameValuePair<string, string>>`  where `NameValuePair` is a custom type similar to this:
```cs
struct NameValuePair<TName, TValue> {
    public TName Name { get; init; }
    public TValue Value { get; init; }
}
```
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Fixed in [Amazon.Lambda.CloudWatchEvents 4.0.0](https://www.nuget.org/packages/Amazon.Lambda.CloudWatchEvents/4.0.0). Kindly refer [RELEASE.CHANGELOG.md](https://github.com/aws/aws-lambda-dotnet/blob/master/RELEASE.CHANGELOG.md) for breaking changes.
