### ISSUE TITLE
Deploy Serverless Application to HTTP API

### ISSUE THREAD

**Issue by genifycom** [aws/aws-lambda-dotnet#933]
Currently the AWS Publish to Lambda function creates a REST API Gateway resource which makes it difficult to attach the generated Lambda Application to an HTTP API Gateway.

## Describe the Feature
Add an API deployment type to the Deployment dialog for Publish AWS Serverless Application to choose the type of API Gateway to deploy to.

This is because the LambdaEntryPoint must determine the type of Gateway event it will receive as per:

        // API Gateway REST API                         -> Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
        // API Gateway HTTP API payload version 1.0     -> Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
        // API Gateway HTTP API payload version 2.0     -> Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction
        // Application Load Balancer                    -> Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction

### Is your Feature Request related to a problem?
Currently, you must choose Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction in order to test the Lambda function. But this will not allow you to move this function to an HTTP API Gateway.

## Proposed Solution
Allow the user to choose which API Gateway type to deploy to.

### Describe alternatives you've considered
Because there is a code change required for each API type, there is no easy alternative using the Visual Studio deployment method.

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
This should probably move/duplicated to https://github.com/aws/aws-toolkit-visual-studio. Needs review with the team.

**Comment by ashishdhingra** [comment]
May be the better alternative is to add a sample request for HTTP API Gateway event type.
