### ISSUE TITLE
build.ps1 doesn't work with PowerShell version 5.1

### ISSUE THREAD

**Issue by bryanjhogan** [aws/aws-lambda-dotnet#936]
## Description
I am trying to build the AWS Lambda Container Images using the PowerShell script located here - https://github.com/aws/aws-lambda-dotnet/tree/master/LambdaRuntimeDockerfiles

I am using Powershell version 5.1.19041.1237 on Windows 10. 

When I run `.\build.ps1` I expect a docker image to be built, instead I get - 

```
Join-Path : A positional parameter cannot be found that accepts argument 'net5'.
At C:\dev\github\aws-lambda-dotnet\LambdaRuntimeDockerfiles\build.ps1:26 char:26
+ ... Path -Path (Join-Path $PWD '.\LambdaRuntimeDockerfiles\Images\' $Targ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
```

## Reproduction Steps
Using Window 10 with PowerShell version 5.1.19041.1237 run `build.ps1` from the `aws-lambda-dotnet\LambdaRuntimeDockerfiles` directory. 

### Environment
* OS Info: Windows 10
* Powershell Version: 5.1.19041.1237

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
This appears to be incompatibility issue with Windows PowerShell 5.1. It works on PowerShell 7.1.

**Comment by ashovlin** [comment]
Closing now that #950 has been merged, thanks again for the PR!
