### ISSUE TITLE
Missing key from ICognitoIdentity?

### ISSUE THREAD

**Issue by Thaina** [aws/aws-lambda-dotnet#94]
In aws lambda it seem like there are many property in `context.identity`

As someone defined here https://forums.aws.amazon.com/thread.jspa?threadID=204244

But in C# library `context.Identity` has only `ID` and `PoolID`. And context object has no method to access dynamic object

How can I access those property such as userAgent?

**Comment by PavelSafronov** [comment]
I believe that you can retrieve that information from the `APIGatewayProxyRequest` object. For instance, the [UserAgent property](https://github.com/aws/aws-lambda-dotnet/blob/359c1285903070eeadc5e462f67108253cdd4c02/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayProxyRequest.cs#L169) can be acessed through `APIGatewayProxyRequest.RequestContext.Identity.UserAgent`.
