### ISSUE TITLE
NET Mock request body is null issue

### ISSUE THREAD

**Issue by devowl** [aws/aws-lambda-dotnet#948]
## Description
Hello, i'm newby for AWS, and have weird behavior. When Mock test tools calls my Function some why the request fields are null. I have created serverless app based on code from Blog example

![image](https://user-images.githubusercontent.com/8266223/139597588-034cd6b4-9ab8-4788-ba7c-b9860f554fdb.png)

Here is function function config:

> "GetRates": {
>             "Type": "AWS::Serverless::Function",
>             "Properties": {
>                 "Handler": "CE.Aws.Exchange.Application::CE.Aws.Exchange.Application.ClientFunctions::GetRatesAsync",
>                 "Runtime": "dotnetcore3.1",
>                 "MemorySize": 128,
>                 "Timeout": 10,
>                 "Role": null,
>                 "Policies": [
>                     "AWSLambda_FullAccess"
>                 ],
>                 "Events": {
>                     "PutResource": {
>                         "Type": "Api",
>                         "Properties": {
>                             "Path": "/",
>                             "Method": "GET" }}}}},

If you need more info let me know

Thanks for any help

### Environment

**dotnet-lambda-test-tool-3.1.exe** product version is: 0.11.3
* Build Version:
![image](https://user-images.githubusercontent.com/8266223/139597740-989c3269-a009-4e33-a280-88aa32318cea.png)
* OS Info: Windows 10
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  net core 3.1

**Comment by bdriggs-axian** [comment]
Youre using the wrong JSON template. Your request model in your function is `APIGatewayProxyRequest` so your JSON needs to match this model. I am assuming the JSON you are using, should be set to the `Body` property of the `APIGatewayProxyRequest`. Try this JSON

```json
{
  "resource": "/my/path",
  "path": "/my/path",
  "httpMethod": "GET",
  "headers": {
    "header1": "value1",
    "header2": "value2"
  },
  "multiValueHeaders": {
    "header1": [
      "value1"
    ],
    "header2": [
      "value1",
      "value2"
    ]
  },
  "queryStringParameters": {
    "parameter1": "value1",
    "parameter2": "value"
  },
  "multiValueQueryStringParameters": {
    "parameter1": [
      "value1",
      "value2"
    ],
    "parameter2": [
      "value"
    ]
  },
  "requestContext": {
    "accountId": "123456789012",
    "apiId": "id",
    "authorizer": {
      "claims": null,
      "scopes": null
    },
    "domainName": "id.execute-api.us-east-1.amazonaws.com",
    "domainPrefix": "id",
    "extendedRequestId": "request-id",
    "httpMethod": "GET",
    "path": "/my/path",
    "protocol": "HTTP/1.1",
    "requestId": "id=",
    "requestTime": "04/Mar/2020:19:15:17 +0000",
    "requestTimeEpoch": 1583349317135,
    "resourceId": null,
    "resourcePath": "/my/path",
    "stage": "$default"
  },
  "pathParameters": null,
  "stageVariables": null,
  "body": "<Your Actual Json Payload Here>",
  "isBase64Encoded": false
}
```

You can see full example here: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

Note didnt test this, but you should get the idea.

**Comment by devowl** [comment]
Thanks you very much, i will try to moving in this way next week

**Comment by devowl** [comment]
Got it! I have realized whats going wrong. If i wanna to pass the JSON as body from my first message i should use this request body:

```
{
   "body":"{\"Interval\":0,\"CurrencyName\":\"RUB\"}"
}
```

In another words Mock request must be matched to APIGatewayProxyRequest class for de serialization.

The issue could be closed. @bdriggs-axian  thanks to you a lot again!
