### ISSUE TITLE
Where is profile config file?

### ISSUE THREAD

**Issue by rui-infotrack** [aws/aws-lambda-dotnet#95]
Hi, could you tell me when I run `dotnet lambda deploy-function`, which AWS profile file I'll be using?

When I publish lambda from Visual Studio, it asks me to create a new profile. Please see screenshot to understand what I'm talking about

![image](https://cloud.githubusercontent.com/assets/12144265/24805321/a8784118-1bf4-11e7-8555-21e8bce86a4c.png)

So I created one but I made a mistake, however there's no way I find so far to delete the broken profile, so I created another one, etc. When I run dotnet lambda deploy command, I'm supposed to choose a profile, therefore I'm just wondering what is the file that the deploy command searches.

Thanks a lot

**Comment by bjorg** [comment]
You can specify the profile using `--profile` on the CLI.

Do this to see all available options:
```
dotnet lambda help deploy-function 
```

If you use the same profile name across all developers, you can also capture it in your `aws-lambda-tools-defaults.json` file.

**Comment by PavelSafronov** [comment]
AWS Toolkit for Visual Studio keeps an encrypted profile store, and this is where the profiles are stored, and where the Lambda tools will look for your profile. Since you have the toolkit installed you can open it with _View_->_AWS Explorer_. Once the explorer is open you can add/modify/delete existing profiles.

**Comment by rui-infotrack** [comment]
@bjorg and @PavelSafronov , thank you very much for the reply. I have another question: say if I want to use `dotnet lambda deploy-function --profile xxx`, what kind of format does this profile file look like? I want to check in this profile somewhere so that I don't have to configure it again on another machine.

**Comment by bjorg** [comment]
@rui-infotrack, the profile is a simple text file. You can read about it here http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

As a best practice, unless you encrypt the profile file, you should not store it in shared folder/project/etc.

**Comment by rui-infotrack** [comment]
@bjorg thank you for the help : )
