### ISSUE TITLE
How to configure the AWS profile used by `dotnet test`?

### ISSUE THREAD

**Issue by bjorg** [aws/aws-lambda-dotnet#96]
I use the `profile` property in `aws-lambda-tools-defaults.json` to set my default AWS profile for deploying lambda functions. However, when I run `dotnet test` it uses the `default` profile in `~/.aws/credentials`. Is there a way to inherit the AWS profile from the project that is being tested?

**Comment by normj** [comment]
The `aws-lambda-defaults.json` is specifying the role for deployment not for execution. I see your point though we do need an easy way for test project to specify which profile to use for testing. I wonder if that is a feature we should add to the TestUtilties package.

**Comment by NachoColl** [comment]
any update on this?

**Comment by mstueck** [comment]
Is there any documentation on how to get the AWS SDK configured when running the unit tests locally?

**Comment by ashishdhingra** [comment]
Hi @bjorg,

Good afternoon.

I was going through backlog and came across this issue. Please advise if input provided by @normj provides guidance about how `aws-lambda-tools-defaults.json` is used. Kindly let me know if this issue could be closed in case no action is required.

Thanks,
Ashish

**Comment by bjorg** [comment]
I stopped using `dotnet lambda` a while back. Sorry, I can't comment if this issue has been addressed since. Thanks for the follow-up though.

**Comment by ashishdhingra** [comment]
Closing this for lack of traction.
