### ISSUE TITLE
Add Source Link support

### ISSUE THREAD

**Issue by qidydl** [aws/aws-lambda-dotnet#968]
Adding support for [Source Link](https://github.com/dotnet/sourcelink) would improve the debugging experience for the AWS .NET libraries and make it easier to trace back to source code to investigate issues.

## Describe the Feature
Source Link embeds information in a NuGet package that identifies the repository and commit that was used to build the package, so that developer tools (e.g. Visual Studio) can download the source when debugging, so that developers can then step through it, set breakpoints, etc. It also establishes a traceability link.

### Is your Feature Request related to a problem?
I'm having some difficulty with logging, and it would be easier to investigate if I could know exactly what the Amazon.Lambda.AspNetCoreServer library is doing when it's running.

## Proposed Solution
There are a few project properties to set (maybe in the shared buildtools\common.props?) and a package to reference that automatically supports GitHub. That would affect a lot of projects so maybe it is tested on just one or a few first. It would take effect with the next release.

### Describe alternatives you've considered
I'm not sure if there are any alternatives to Source Link that achieve the same thing. Source Link seems to be a standard at least within the .NET/NuGet community.

## Additional Context
I'm trying to understand the run-time behavior of libraries like Amazon.Lambda.AspNetCoreServer in detail so I can use them correctly. More documentation and examples can help, but are unlikely to always cover every corner case.

### Environment
This should not be specific to any environment, although not all tools may take advantage of the Source Link metadata.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by jon-armen** [comment]
@ashishdhingra  - I have submitted #1089 for this issue.  @qidydl , do you believe this would resolve?

**Comment by ashishdhingra** [comment]
Resolving because this is done by default with .NET 8.
