### ISSUE TITLE
Add support for local testing with Lambda Test Tool for .NET 6 when using the `Container Image` blueprint

### ISSUE THREAD

**Issue by TrongTheAlpaca** [aws/aws-lambda-dotnet#975]
![image](https://user-images.githubusercontent.com/46680221/141792481-8ffb3639-3ca9-45dd-bae7-c6f1f50272d5.png)

## Describe the Feature
In the current version of the Lambda Test Tool, local debugging of lambda functions running on .NET 6 is not supported when using the `Container Image` blueprint.

## Proposed Solution
Add support for Lambda function running on .NET 6, similar to how the current `Container Image` blueprint supports .Net Core 3.1 and .NET 5 out-of-the-box.

## Reproduction of the problem
Changing the `workingDirectory` value in `properties/launchSettings.json` to refer to `net6.0`:
```json
{
  "profiles": {
    "Mock Lambda Test Tool": {
      "commandName": "Executable",
      "executablePath": "%USERPROFILE%\\.dotnet\\tools\\dotnet-lambda-test-tool-5.0.exe",
      "commandLineArgs": "--port 5050",
      "workingDirectory": ".\\bin\\$(Configuration)\\net6.0"
    }
  }
}
```
Change target framework:
![image](https://user-images.githubusercontent.com/46680221/141793936-e29cf643-a8cc-4cab-b6bc-bfbddcb2894f.png)

The error I get when I try to invoke the Lambda function locally:
![image](https://user-images.githubusercontent.com/46680221/141793767-809580db-1a9d-4a05-8d93-b3c2c9b02ab4.png)

## Notes
This issue is most likely blocked behind the issue https://github.com/aws/aws-lambda-base-images/issues/27.

**Comment by ashishdhingra** [comment]
Should this be moved to https://github.com/aws/aws-toolkit-visual-studio?

**Comment by TrongTheAlpaca** [comment]
> Should this be moved to https://github.com/aws/aws-toolkit-visual-studio?

Ah perhaps, I am not sure myself! 😅

**Comment by normj** [comment]
This belongs in this repo. This repo contains the code for the test tool. We need to spin up a new version for .NET 6 which we will do soon. Once we have the NuGet package released for a .NET 6 version of the tool we will need to do a small update to the VS toolkit.

**Comment by sjd2021** [comment]
Is an entirely different tool used for Rider? Half of my team uses Rider, and it's been a struggle to find a good BYOD strategy while developing on the AWS stack for .NET developers because the mechanisms for locally testing lambdas seem to be very different.

**Comment by normj** [comment]
@sjd2021 There are instructions on how to configure the .NET Lambda test tool for Rider here. Let me know if the instructions aren't clear https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool#configure-for-jetbrains-rider

@TrongTheAlpaca Yesterday released the .NET 6 version of the tool. https://www.nuget.org/packages/Amazon.Lambda.TestTool-6.0/ Visual Studio toolkit hasn't been updated yet to autoconfigure it so you will have to manually install the tool via the `dotnet tool install --global Amazon.Lambda.TestTool-6.0 --version 0.11.3` command and editing your `launchSettings.json` file.

**Comment by sjd2021** [comment]
Thank you! I swear the documentation from the actual AWS site linked to two different paths at one point. I'll try this out.
