### ISSUE TITLE
How to deploy lambda function using Apple M1 processor?

### ISSUE THREAD

**Issue by az-oolloow** [aws/aws-lambda-dotnet#986]
I have this new Apple M1 silicon computer running mac OS.

I have installed .net core sdk 3.1 (x64), 5.0 (x64) and 6.0 (ARM64 and x64).

I am running the basic

```
dotnet lambda deploy-function myFunc --function-role myRole
```

command.

I have tried the following:

* Launch terminal without Rosetta and run the above
* Launch terminal with Rosetta and run the above
* Launch terminal without Rosetta and run "/usr/local/share/dotnet/x64/dotnet" lambda deploy-function myFunc --function-role myRole
* 
In all cases I get:
```
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib,

error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib, 0x0001):

tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')),

'/usr/local/lib/libhostpolicy.dylib' (no such file),

'/usr/lib/libhostpolicy.dylib' (no such file)

An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.20]
```

**Comment by ashishdhingra** [comment]
Appears to be similar to https://github.com/aws/aws-extensions-for-dotnet-cli/issues/192

**Comment by ashishdhingra** [comment]
Hi @az-oolloow,

Looking at https://github.com/dotnet/runtime/issues/59168 and https://github.com/dotnet/sdk/issues/22380, this appears to be the issue with side-by-side install of .NET 6 ARM64 and .NET x64. Please try following guidance mentioned in https://github.com/dotnet/sdk/issues/22380#issuecomment-964044326 and see if it works for you. 

Thanks,
Ashish
