### ISSUE TITLE
Contents of self-created Lambda Runtime image differes from expected

### ISSUE THREAD

**Issue by TrongTheAlpaca** [aws/aws-lambda-dotnet#987]
## Preface
At the time of writing, the official .NET 6 Lambda image has **not** been pushed to the following image repositories:
- https://gallery.ecr.aws/lambda/dotnet
- https://registry.hub.docker.com/r/amazon/aws-lambda-dotnet/tags

A relevant issue is brought up here:
- https://github.com/aws/aws-lambda-base-images/issues/27

## Description

A temporary fix is to create the needed runtime image yourself, explained in https://github.com/aws/aws-lambda-dotnet/issues/889#issuecomment-964415658.

Unsure if it is intended, but the resulting .NET 6 image created using the mentioned instructions **differs** in structure from the official images. To properly highlight this difference, I will ignore comparison with .NET 6 image and only use .NET 5 as a point of reference, as the problem is reproducable with that version as well.

See images below (ignore highlighted words):

![image](https://user-images.githubusercontent.com/46680221/142638767-7da92cd9-8561-485e-9e01-4831887295d3.png)![image](https://user-images.githubusercontent.com/46680221/142639113-2db38f40-aa52-494f-8825-f58a8aed2e26.png)
**Left tree:** Content tree to the is from the image `public.ecr.aws/lambda/dotnet:5.0` from https://gallery.ecr.aws/lambda/dotnet
**Right tree:** Content tree of the created image when following the instructions from https://github.com/aws/aws-lambda-dotnet/issues/889#issuecomment-964415658 to create a .NET 5 image.

Note that `Bootstrap.sh` is not found in the same location. For the self-created .NET 5 lambda image, the file is instead in `var/runtime/Bootstrap.sh`, as seen below:
![image](https://user-images.githubusercontent.com/46680221/142642558-f9ce358d-af36-44dc-878a-552b426ff159.png)

As mentioned above, creating a .NET 6 equivalent image will have a similar structure.
Is this difference intended? I can imagine that this does have an implication on the usage of the images.

**Comment by TrongTheAlpaca** [comment]
Am I correct that this difference is due to this specific commit: 9668ee860d748b0717502cd6ecbc28dbac74d1b3?
It seems intentional? Does this change have implications on how Lambda functions interact with the image compared to older versions of the image?

**Comment by normj** [comment]
The change was intentional to match other Lambda runtimes. It won't have any impact to the experience because the `/lambda-entrypoint.sh` is used as the container entrypoint. The lambda-entrypoint.sh script has been updated but the location hasn't changed for that file.

**Comment by TrongTheAlpaca** [comment]
Ah I see, thanks! The answer is sufficient, so I will be closing this issue now.
