### ISSUE TITLE
Support yaml in the DeployServerlessCommand

### ISSUE THREAD

**Issue by jakejscott** [aws/aws-lambda-dotnet#99]
Would be nice if we could use yaml in the templates:
https://github.com/aws/aws-lambda-dotnet/blob/9bb1988f33f8126b5de130ef12e13ec6f822a983/Libraries/src/Amazon.Lambda.Tools/Commands/DeployServerlessCommand.cs#L586

**Comment by normj** [comment]
Getting the VS toolkit's CloudFormation editor to support Yaml is a big job this unlikely to happen soon. Would you be happy without the toolkit support as long as you could use Yaml using the .NET CLI integration?

**Comment by superlogical** [comment]
At the moment I've settled on using Visual Studio Cloudformation Editor to edit JSON and that's pretty nice.

And then Powershell + AWS Powershell and VS Code for the rest.

So I'm not super worried about Yaml suppport now.

**Comment by derwasp** [comment]
@normj I can live without visual studio's intellisense. But yml support would be very cool to have. Can you please reopen this case?

**Comment by normj** [comment]
Reopening as a feature request for @derwasp

**Comment by ccp-ccollins** [comment]
"Would you be happy without the toolkit support as long as you could use Yaml using the .NET CLI integration?"

+1 for this.  That is exactly what I want.  The inability to put comments in JSON is a major pain point for me, and I'd rather use YAML with no intellisense than JSON with it.  if `dotnet lambda deploy-serverless` could understand a serverless.template in yaml syntax, I'd be a happy camper.

My current thought is that it would probably fit my workflow better to use `aws cloudformation package` and `aws cloudformation deploy` directly.  Perhaps some of that functionality can be borrowed by the dotnet tool?

**Comment by jakejscott** [comment]
Shameless plug for my C# based Cloudformation library (which supports .net 45 and dotnet core). 

I parse the Cloudformation JSON schema, and use Roslyn to generate the C# API for all the AWS resources.

https://github.com/jakejscott/Humidifier

I plan to move all our serverless deployments which currently are done using a mixture of powershell `dotnet lambda package` and Cloudformation hand coded JSON....  to dotnet core based C# console app. Main reason being that I can code everything in C# and it be cross platform. This allows us to dev/test deployments from a dev machine, but also run them in a CI/CD system which is Linux/Docker based. I didn't want to have to maintain both powershell scripts on Windows and bash scripts on Linux.

**Comment by normj** [comment]
Looks cool @jakejscott 

@ccp-ccollins Thanks for the +1, I agree it would be great to get that work done. I'm just looking to find some time to do it.

**Comment by normj** [comment]
Version 1.8.0 of the cli package Amazon.Lambda.Tools was just released which supports YAML based Cloudformation templates.

A Visual Studio release will happen soon with the update as well. The VS update will just be for adding the ability to deploy with a YAML template not updates to the editor for intellisense.

**Comment by jakejscott** [comment]
@normj Cool thanks for the update, nice work!

**Comment by red8888** [comment]
How does this work? I just created a new project with the AWS Serverless template (the empty one) and serverless.template file is in json. If I put yaml in there VS seems to not read it
